### ISSUE TITLE
help anyone?

### ISSUE THREAD

**Issue by addisonrudd** [jabbink/PokemonGoBot#1005]
not really an issue but im only getting about 60,000xp/hour which is really low. Can someone give me correct settings for the most xp possible? thanks!

**Comment by mustafababil** [comment]
you can check #locations channel in [Discord](https://discordapp.com/channels/211157501322854400/211157501322854400)

one [here](http://gamingonsteroids.com/topic/12823-160k-170k-exp-coords/) also

**Comment by Mixone-FinallyHere** [comment]
did you seriously open an issue for this?
