### ISSUE TITLE
Route Bug

### ISSUE THREAD

**Issue by Killertom63** [jabbink/PokemonGoBot#1007]
**Description:**
I tend to use the right click to set a route, this allows me to make the bot go around the lake to find water pokemon. And now it just randomly started to go in a straight line, like a "My people need me" situation. Please see the Gyazo image; https://gyazo.com/a3ddcbcd1ad3cd5471a62c4bf8cf3353 

It does actually end up coming back, but it was still weird. 

**Steps to reproduce:**

1. Set way points on the bot
2. Let it do it's thing

**Expected behavior:**
Follow the way points

**Actual behavior:**
Follows, and then randomly will go in a straight line.

**Version:**
0.5.2

**Operating System:**
Win 10

**Java version:**
Latest

**Comment by Sieberkev** [comment]
This is an "intended" behaviour...

If the routeprovider can not calculate a valid walkingroute OR there is an error while trying to fetch a walkingroute, it will fall back to a straight line instead of crashing/standing still forever/...

**Comment by Mixone-FinallyHere** [comment]
Actually that looks like when you reset your bot but keep gui open
I had a line going from Sydney to Tokyo once

**Comment by Killertom63** [comment]
@Mixone-FinallyHere I didn't reset it :)

**Comment by Mixone-FinallyHere** [comment]
weird haha

**Comment by Killertom63** [comment]
Thanks for the info @Sieberkev
