### ISSUE TITLE
[New learner Question] How to Run Main.kt

### ISSUE THREAD

**Issue by elliottfeng** [jabbink/PokemonGoBot#101]
Have IDEA, don't know how to setup configuration.

**Comment by pratamawijaya** [comment]
open your `terminal` and run with `./gradlew run`

---
on windows `gradle.bat run`

**Comment by elliottfeng** [comment]
Thanks a lot, i am on windows and after run gradle.bat cmd window closed and nothing happens.

**Comment by tenoriojuann** [comment]
Has the API been updated? I still get the error with the "private" members in PlayerProfile.

**Comment by jabbink** [comment]
`git pull`

`gradlew clean build`
