### ISSUE TITLE
[Feature Request] List in config for not catching listed pokemon 

### ISSUE THREAD

**Issue by trxit** [jabbink/PokemonGoBot#1010]
Please implement a list of pokemon which shouldn't be caught!!

**Comment by Mixone-FinallyHere** [comment]
hello, have you read the config file?
it looks like you haven't
you also forgot to follow the issue template
and yet allowed yourself to use exclamation marks
in what seems like an aggressive manner of speech

please read the config.properties file
you will find:
> // Comment // Desired probability to catch unwanted Pokemon (obligatory_transfer; low IV; low CP) 
> // Comment // Set to -1 to not attempt catching at all 
> desired_catch_probability_unwanted=0.0 

what do you think that means?

**Comment by trxit** [comment]
lol.
didn't know to put -1 for obligatory means unwanted. it's a little bit confusing but ok.

Aggressive thanks!!

**Comment by Mixone-FinallyHere** [comment]
😛
