### ISSUE TITLE
Bot blacklists catching pokemon even though inventory isn't full

### ISSUE THREAD

**Issue by qwertychacha2002** [jabbink/PokemonGoBot#1011]
**Description:**
When I start up the bot during the first encounter it says that inventory is full and disables catching pokemon, even though inventory is not full

**Expected behavior:**
Catch pokemon

**Actual behavior:**
Does exact opposite and disables catching pokemon entirely

This is the output I get in terminal:
```
11 Aug 18:30:54 [default: WalkingLoop] - Walking to (40.764769, -73.974474) in 73.94667706774631 steps.
11 Aug 18:30:55 [default: ProfileLoop] - Profile update: 660770 XP on LVL 24; 100770/150000 (67.18%) to LVL 25
11 Aug 18:30:55 [default: ProfileLoop] - XP gain: 0 XP; Pokemon caught/transferred: 0/0; Pokemon caught from lures: 0; Items caught/dropped: 0/0;
Pokebank 250/250; Stardust 191148; Inventory 289/350
11 Aug 18:30:57 [default: WalkingLoop] - Pausing to catch pokemon...
11 Aug 18:30:58 [default: BotLoop] - Getting map of (40.76479925118825, -73.97312670937329)
11 Aug 18:30:58 [default: BotLoop] - Found pokemon NIDORINO
11 Aug 18:30:59 [default: BotLoop] - Encounter failed with result: POKEMON_INVENTORY_FULL
11 Aug 18:30:59 [default: BotLoop] - Disabling catching of Pokemon

```

**Version:**
PokemonGoBot-0.5.1.jar

**Operating System:**
OSX El Capitan Version 10.11.5

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by Mixone-FinallyHere** [comment]
I am just going to wait until you realize it

**Comment by Mixone-FinallyHere** [comment]
![freshpaint-2-2016 08 12-12 46 56](https://cloud.githubusercontent.com/assets/11949750/17607486/50fc279a-6026-11e6-9c0e-e491c1166460.png)

**Comment by qwertychacha2002** [comment]
Oh, I'm such an idiot... I feel so stupid
