### ISSUE TITLE
How to bypass VPN IP ban?

### ISSUE THREAD

**Issue by Tom2942** [jabbink/PokemonGoBot#1013]
EDIT: Fixed the issue.
Run this command in terminal: java -jar PokemonGoBot-0.5.2.jar -Dhttp.proxyHost=XXXXXXXXX

XXX =Random VPN IP
Search here for an IP: http://proxylist.hidemyass.com/2

**Comment by Mixone-FinallyHere** [comment]
This is not an issue the bot has to solve or even can solve I think you are better off looking it up in stackoverflow or something

**Comment by swtrpeter** [comment]
I hope someone can help us with this issue.. Been having this issue for several days now. Driving me nuts ! ! Really wish we could add a proxy ip in the config file.

**Comment by Mixone-FinallyHere** [comment]
How much have you used the bot to get banned dude?
Things in life are meant to be enjoyed
> Jam is better in smaller jars

**Comment by swtrpeter** [comment]
i am not getting banned,, Just dont want my ip address out there to get banned if a ban wave comes. So I try to run vpn and it throws all kinds of errors when loading the bot.

**Comment by Tom2942** [comment]
@swtrpeter 
Run this command in terminal: java -jar PokemonGoBot-0.5.2.jar -Dhttp.proxyHost=XXXXXXXXX

XXX =Random VPN IP
Search here for an IP: http://proxylist.hidemyass.com/2

**Comment by swtrpeter** [comment]
@Tom2942  i am not running the pre built i am running the zip

**Comment by langerhans** [comment]
There is an issue about proxy support already :)
