### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by coffeered** [jabbink/PokemonGoBot#1015]
**Description:**
It worked fine perviously but it crashed just now. 
Whenever I rerun the process, it pops up a exception. (showing below)

**Steps to reproduce:**

1. `java -jar PokemonGoBot-0.5.2.jar `
2. exception shows
3. block there

**Actual behavior:**
[skip the logo PokeMon]

12 八月 11:44:55 [default] - Trying to read /Users/coffeered/tmp/PokemonGoBot/config.properties
12 八月 11:44:55 [default] - Logging in to game server...
12 八月 11:44:58 [default] - Logged in successfully
Getting profile data from pogo server.
12 八月 11:45:00 [default] - Accepting ToS
Exception in thread "default" java.lang.NullPointerException
	at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:43)
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:294)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:145)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Version:**
PokemonGoBot-0.5.2.jar

**Operating System:**
Mac OSX
**Java version:**
`java version "1.8.0_102"`
`Java(TM) SE Runtime Environment (build 1.8.0_102-b14)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)`

**Comment by casper-gh** [comment]
same here, but only 1 of my bots, I think we're perm banned lol

**Comment by coffeered** [comment]
@casper-gh Youre right. lol

**Comment by CLGitDev** [comment]
Do you guys see the error message "Failed to get game data from the server" when trying to login via the app?

**Comment by casper-gh** [comment]
@CLGitDev yep

**Comment by coffeered** [comment]
@CLGitDev Nope, above is all I got

**Comment by casper-gh** [comment]
@coffeered you'll get that error if you login from real game client

**Comment by coffeered** [comment]
see thanks a lot. lol

**Comment by zoegalaxy** [comment]
I got the same problem with one of my bots. Is this permanent ban? Oh no!

**Comment by Mixone-FinallyHere** [comment]
Well the fact that you tried to accept the ToS with a bot probably didnt help

**Comment by gise88** [comment]
Chill out guys :laughing: http://ispokemongodownornot.com/ Probably is just a login server problem! :yum:
