### ISSUE TITLE
All Capture failed with status : CATCH_FLEE

### ISSUE THREAD

**Issue by RandyXiaomin** [jabbink/PokemonGoBot#1016]
**Description:**
All seems working previously, and I didn't teleport at all, but I encountered this issue just now.
All Captures failed with status : CATCH_FLEE, but I can loot pokestops.

Log:

11 Aug 21:44:35 [default: PokestopLoop] - Looted pokestop e1cdf2cd02154d4e8facb663f22d05fb.16; +50 XP
11 Aug 21:44:36 [default: BotLoop] - Found pokemon RATTATA
11 Aug 21:44:36 [default: BotLoop] - Encountered pokemon RATTATA with CP 226 and IV 75%
11 Aug 21:44:36 [default: BotLoop] - Using desired_catch_probability_unwanted because Obligatory transfer
11 Aug 21:44:36 [default: BotLoop] - Using ITEM_POKE_BALL; achieved catch probability: 0.3865527, desired: 0.0
11 Aug 21:44:37 [default: BotLoop] - Capture of RATTATA failed with status : CATCH_FLEE
11 Aug 21:44:38 [default: WalkingLoop] - Pausing to catch pokemon...
11 Aug 21:44:40 [default: BotLoop] - Found pokemon ZUBAT
11 Aug 21:44:41 [default: BotLoop] - Encountered pokemon ZUBAT with CP 273 and IV 35%
11 Aug 21:44:41 [default: BotLoop] - Using desired_catch_probability_unwanted because Obligatory transfer
11 Aug 21:44:41 [default: BotLoop] - Using ITEM_POKE_BALL; achieved catch probability: 0.35288644, desired: 0.0
11 Aug 21:44:41 [default: BotLoop] - Capture of ZUBAT failed with status : CATCH_FLEE
11 Aug 21:44:42 [default: PokestopLoop] - Looting nearby pokestop 86592026cc83489999d8ab3d65f604a9.16
11 Aug 21:44:43 [default: PokestopLoop] - Looted pokestop 86592026cc83489999d8ab3d65f604a9.16; +100 XP
11 Aug 21:44:46 [default: BotLoop] - Found pokemon CLEFAIRY
11 Aug 21:44:46 [default: BotLoop] - Encountered pokemon CLEFAIRY with CP 44 and IV 24%
11 Aug 21:44:46 [default: BotLoop] - Using desired_catch_probability_unwanted because Obligatory transfer
11 Aug 21:44:46 [default: BotLoop] - Using ITEM_POKE_BALL; achieved catch probability: 0.72116303, desired: 0.0
11 Aug 21:44:47 [default: BotLoop] - Capture of CLEFAIRY failed with status : CATCH_FLEE
11 Aug 21:44:48 [default: WalkingLoop] - Destination reached.
11 Aug 21:44:48 [default: WalkingLoop] - Walking to (37.790683, -122.405555) in 72.8480188237358 steps.
11 Aug 21:44:58 [default: PokestopLoop] - Looting nearby pokestop 4aec6d5c6da64b0091884fbb3fb26494.12
11 Aug 21:44:59 [default: PokestopLoop] - Looted pokestop 4aec6d5c6da64b0091884fbb3fb26494.12; +50 XP
11 Aug 21:45:03 [default: PokestopLoop] - Looting nearby pokestop 585330b5449044ea933a7b7c07c53457.12
11 Aug 21:45:04 [default: PokestopLoop] - Looted pokestop 585330b5449044ea933a7b7c07c53457.12; +50 XP
11 Aug 21:45:05 [default: WalkingLoop] - Destination reached.
11 Aug 21:45:05 [default: WalkingLoop] - Walking to (37.79054, -122.406611) in 59.29041687173699 steps.
11 Aug 21:45:06 [default: BotLoop] - Found pokemon ZUBAT
11 Aug 21:45:06 [default: BotLoop] - Encountered pokemon ZUBAT with CP 217 and IV 37%
11 Aug 21:45:06 [default: BotLoop] - Using desired_catch_probability_unwanted because Obligatory transfer
11 Aug 21:45:06 [default: BotLoop] - Using ITEM_POKE_BALL; achieved catch probability: 0.40011334, desired: 0.0
11 Aug 21:45:07 [default: BotLoop] - Capture of ZUBAT failed with status : CATCH_FLEE
11 Aug 21:45:09 [default: WalkingLoop] - Pausing to catch pokemon...
11 Aug 21:45:10 [default: BotLoop] - Found pokemon ZUBAT
11 Aug 21:45:11 [default: BotLoop] - Encountered pokemon ZUBAT with CP 450 and IV 40%
11 Aug 21:45:11 [default: BotLoop] - Using desired_catch_probability_unwanted because Obligatory transfer
11 Aug 21:45:11 [default: BotLoop] - Using ITEM_POKE_BALL; achieved catch probability: 0.27800977, desired: 0.0
11 Aug 21:45:11 [default: BotLoop] - Capture of ZUBAT failed with status : CATCH_FLEE

**Steps to reproduce:**
java -jar XXXX.jar

**Expected behavior:**
Should at least be able to caught some pokemons.

**Actual behavior:**
All Capture failed with status : CATCH_FLEE

**Stacktrace (If it's a crash):**
config.properties 
http://pastebin.com/eeMf2qrL

**Version:**
0.5.2

**Operating System:**
OS X El Capitan
Version 10.11

**Java version:**
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

**Comment by Danman00** [comment]
pls provide a look in your config and use pastebin !

**Comment by crocoducker** [comment]
I've been having the same issue as well! The bot was running fine for a few hours but all attempts to catch pokemon after a certain while all become catch flees

**Comment by mrabbie** [comment]
Please check your Walking Meters per second
speed?

**Comment by Dewinster** [comment]
I've the same issue, but pokestops works fine.
So it doesn't seems like a ban.

**Comment by breinntaguilar** [comment]
Hello,

what is the information that should be in the 'token= ' part in the config file? 
thanks!

**Comment by mrabbie** [comment]
@breinntaguilar just ignore

**Comment by breinntaguilar** [comment]
thanks @mrabbie . but im getting an error. 

Server returned unexpected error: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake

i have already created a ticket for this. :/

**Comment by minazzre** [comment]
seems like a new type of soft ban. same issue here.

**Comment by zhongyu05** [comment]
@minazzre +1

**Comment by zhoushifeng8** [comment]
some problem here, just appear this problem

**Comment by KleinSamuel** [comment]
This is usually a sign of a softban which is bypassed by spinning a pokestop multiple times.
Ive tried to recreate your problem and I think it has to do with your walking speed.

As far as I understood:
Low walking speed -> More Pokemon, less Pokestops
High walking speed -> Less Pokemon, more Pokestops

BUT if the walking speed is too high you get this CATCH_FLEE thing all of the time which really seems like a new type of softban like minazzre said before.

**Comment by minazzre** [comment]
@KleinSamuel 
- my walking speed is 2.0 m/s, never had this problem before.
- seems niantic changed the soft ban, now there are 2 types of bans as far as i know, one is only allowing pokemon catch, the other is only looting pokestop.
- no idea how to unban, waiting time 6 hours now, still banned.

**Comment by staurakis** [comment]
It is indeed a new type of softban due to snipping / teleporting / or any way of changing location withing few minutes of time. It is handled by the application with the softban workaround as far as i have tested it.

**Comment by KleinSamuel** [comment]
@minazzre 

When my bot is banned it can't catch Pokemon and can't get items from Pokestops but the pokestopspin-workaround always works perfect for me.
I don't think it has to do with your bot running time because of 2 reasons:

1) My bot is running way longer than 6 hours and it didn't get banned the way yours is.
2) Banning people for playing 6 hours straight could affect "normal" players right? So I think Niantic wouldn't do it that way.

I need to state out that these are just my thoughts.

What makes you guys think this is a new type of softban?

**Comment by mrabbie** [comment]
@KleinSamuel Could it be an IP ban? Everytime i got pokestop out of range error, when i restart the bot, i always got the 0 starting pokestop, and the quickest fix i found is to switch my internet from home wifi to mobile hotspot.

**Comment by KleinSamuel** [comment]
@mrabbie Thats indeed one of the only things I think Niantic can do against bots. Checking for locations and IPs is the only way you can determine if a player is a bot or not without having false positives. If Niantic bans regular players it would result in a big shitstorm so I think they are very careful with banning people. So in my opinion thats the reason why there is only a softban right now.

But if so it can easily be worked around as you said.

**Comment by zoegalaxy** [comment]
Had the same issue just now.

What is the work around?  Or should I just wait for it until the softban expires?

**Comment by RandyXiaomin** [comment]
@zoegalaxy  I waited for like 10 hours, it is still the same, and I cant loot the pokestops now.

**Comment by staurakis** [comment]
Have you tried to restarted your router just in case it is the ip based ban????

**Comment by jabbink** [comment]
See release notes of 0.6.0

Wait 24+h
