### ISSUE TITLE
Unknown exception occurred

### ISSUE THREAD

**Issue by HakaseShounen** [jabbink/PokemonGoBot#1018]
**Description:**

> Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException

**Steps to reproduce:**

1. run this `java -jar PokemonGoBot-0.5.2.jar`
2. Wait for the error to display

**Expected behavior:**
Should run fine

**Actual behavior:**
> Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException

> Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403

> Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403

> Caused by: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
v0.5.2

**Operating System:**
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

**Java version:**

> openjdk version "1.8.0_91"
> OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
> OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by Cy4n1d3** [comment]
Looks like the IP the bot's requests originate from are being blocked.

**Comment by svenbroeker** [comment]
ptc account? have the same failure

**Comment by langerhans** [comment]
Yep, IP ban most probably. If you run this on a VPS, try local first, if that works get a new VPS at an unknown provider ;)
