### ISSUE TITLE
Pokestop out of range

### ISSUE THREAD

**Issue by sle84** [jabbink/PokemonGoBot#1019]
**Description:**
Since today I get pokestop out of range all the time.

**Steps to reproduce:**
I haven't changed anything, using 0.5.2 also tested with 0.5.1

**Expected behavior:**
Should loot the pokestop

**Actual behavior:**
Fails

**Stacktrace (If it's a crash):**
No crash

**Version:**
0.5.2 and also with 0.5.1

**Operating System:**
[Your operating system]

**Java version:**
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by Mixone-FinallyHere** [comment]
Tried to set map cells to smaller amount?

**Comment by svombergen** [comment]
Seems to be a soft ban of some sort, try again in a few hours.

**Comment by sle84** [comment]
Went down from 9 to 4, no effect.
It's catching pokemon, so it does not seem like the classic soft ban...

**Comment by aukeboskma** [comment]
Same here. I have a ban, don't know for how long. but i have it for more than 4 hours now. I can battle gym though.

**Comment by Mixone-FinallyHere** [comment]
What are the coords?
You actually might have set them to somewhere without
small tiny typos in the lat and long can translate to hundreds of km easily and throw you in the middle of Siberia for example (happened to me)

**Comment by sle84** [comment]
They stayed the same since days, in the map I can see, it walking and also pokestops, but they are always out of range (in log). I disabled looting them and try again in a few hours.

**Comment by RandyXiaomin** [comment]
Got the same soft ban, all catches flee and all pokestops out of range, tried on different network and router, waited 10 hours, still banned right now. Hope it would not be forever.

**Comment by jabbink** [comment]
#923
