### ISSUE TITLE
Encounters Pokemon But Doesn't Catch?

### ISSUE THREAD

**Issue by Davidw1339** [jabbink/PokemonGoBot#102]
I started using the bot and everything went smoothly initially. Later, I restart the bot and it encounters pokemon but doesn't capture them. I know it is not a soft ban because I can get rewards from pokestops and the pokemon don't seem to be fleeing after one throw. Here are logs:

Getting map of (41.30802994778062, -72.92903784687542)
Found pokemon SPEAROW
Dropped 1x ITEM_POTION
Dropped 1x ITEM_SUPER_POTION
Dropped 1x ITEM_POKE_BALL
Profile update : 213030 XP on LVL 20; 28030/75000 (37.37%) to LVL 21
Destination reached.
Getting map of (41.3080183121074, -72.92925266033765)
Found pokemon SPEAROW
Profile update : 213030 XP on LVL 20; 28030/75000 (37.37%) to LVL 21
Getting map of (41.308005598968045, -72.9292291289579)
Found pokemon SPEAROW
Profile update : 213030 XP on LVL 20; 28030/75000 (37.37%) to LVL 21
Getting map of (41.3079465398521, -72.92919817821048)
Found pokemon SPEAROW
Profile update : 213030 XP on LVL 20; 28030/75000 (37.37%) to LVL 21
Getting map of (41.307969808108126, -72.92917167785839)
Found pokemon SPEAROW
Profile update : 213030 XP on LVL 20; 28030/75000 (37.37%) to LVL 21
Getting map of (41.307953224954325, -72.92923018774569)
Found pokemon SPEAROW
Profile update : 213030 XP on LVL 20; 28030/75000 (37.37%) to LVL 21
Getting map of (41.30801886450691, -72.92920418734899)
Found pokemon SPEAROW
Profile update : 213030 XP on LVL 20; 28030/75000 (37.37%) to LVL 21
Getting map of (41.30796233210647, -72.92921160339867)
Found pokemon SPEAROW
Profile update : 213030 XP on LVL 20; 28030/75000 (37.37%) to LVL 21

**Comment by devs7u** [comment]
Having the same issue here. my log:


Getting map of (41.88257283767451, -87.62251668483788)
Found pokemon RATTATA
Profile update : 339465 XP on LVL 22; 79465/175000 (45.41%) to LVL 23
Getting map of (41.882522509403884, -87.62256496827389)
Found pokemon RATTATA
Profile update : 339465 XP on LVL 22; 79465/175000 (45.41%) to LVL 23
Getting map of (41.88258010105323, -87.62252505517387)
Found pokemon RATTATA
Profile update : 339465 XP on LVL 22; 79465/175000 (45.41%) to LVL 23
Getting map of (41.88256362500178, -87.62259795842651)
Found pokemon RATTATA
Profile update : 339465 XP on LVL 22; 79465/175000 (45.41%) to LVL 23
Getting map of (41.88252569267565, -87.62251304138623)
Found pokemon RATTATA
Profile update : 339465 XP on LVL 22; 79465/175000 (45.41%) to LVL 23
Getting map of (41.88255187325756, -87.62254368652624)
Found pokemon RATTATA
Profile update : 339465 XP on LVL 22; 79465/175000 (45.41%) to LVL 23
Getting map of (41.882535565779186, -87.62253038027102)
Found pokemon RATTATA
Profile update : 339465 XP on LVL 22; 79465/175000 (45.41%) to LVL 23
Getting map of (41.88254813902937, -87.62258070936697)
Found pokemon RATTATA
Profile update : 339465 XP on LVL 22; 79465/175000 (45.41%) to LVL 23
Getting map of (41.882549183544185, -87.62258628991496)
Found pokemon RATTATA
Profile update : 339465 XP on LVL 22; 79465/175000 (45.41%) to LVL 23
Getting map of (41.882530618641255, -87.62258162290887)
Found pokemon RATTATA
Profile update : 339465 XP on LVL 22; 79465/175000 (45.41%) to LVL 23
Getting map of (41.88253598390309, -87.62255200482637)
Found pokemon RATTATA
Profile update : 339465 XP on LVL 22; 79465/175000 (45.41%) to LVL 23
Getting map of (41.882507460124934, -87.62250807056697)
Found pokemon RATTATA
Profile update : 339465 XP on LVL 22; 79465/175000 (45.41%) to LVL 23
Getting map of (41.88256701335439, -87.62253789898026)
Found pokemon RATTATA
Profile update : 339465 XP on LVL 22; 79465/175000 (45.41%) to LVL 23
Getting map of (41.8825526037894, -87.62257689552233)
Found pokemon RATTATA

**Comment by Davidw1339** [comment]
Just figured it out, happens when you're pokemon slots are full (250/250). Maybe a warning in the console would be helpful. But was my fault regardless

**Comment by devs7u** [comment]
thx ^ gotcha

**Comment by pr0ves** [comment]
In the latest version there's the the number of slots used. Are you using the jar instead? It needs to be updated then
