### ISSUE TITLE
Doesn't update when eggs Hatch

### ISSUE THREAD

**Issue by Killertom63** [jabbink/PokemonGoBot#1021]
**Description:**
I left the bot for a few ours and came back to it. I control + F the console with the word "egg" to see what eggs have hatched but it didn't come up with anything other than the Pokemon Exeggcute. I logged in on my Mobile to find it had hatched at least 15+. Dunno if it's a bug or not. *shrug* 

**Steps to reproduce:**

1. Have an egg
2. Make the bot Hatch it
3. Look at console

**Expected behavior:**
Say the information about the hatched egg.

**Actual behavior:**
says nothing about the egg

**Version:**
0.5.2

**Operating System:**
Win 10

**Comment by staurakis** [comment]
Actually, i have seen that as well. BUT, if you check your log file in the log files directory, and you search in the notepad from the beginning of the file, you will see that the hatching information and all hatching process takes place correctly with all information there. ;)
So, there is no problem with the hatching process no worries :)

**Comment by Mixone-FinallyHere** [comment]
The console log is MUCH shorter
Mine is about 450 lines long only

**Comment by Mixone-FinallyHere** [comment]
This is normal is what I mean not an issue at all

if you really want to keep the whole log you can try:
`gradlew run > log.txt`

if you only want to log hatches:
`gradlew run | grep "Hatched" > eggLog.txt`

if you want only pokemon captures:
`gradlew run | grep "Caught" > catchLog.txt`

if you want both:
`gradlew run | grep "Hatched\|Caught" > pokeLog.txt`

**Comment by Killertom63** [comment]
Oh ok, thanks.
