### ISSUE TITLE
Can't access the GUI

### ISSUE THREAD

**Issue by rickard2014** [jabbink/PokemonGoBot#1026]
I open the website for the GUI and it can't access through localhost and 8001

Is it an issue with the router or my firewall?

**Comment by staurakis** [comment]
"The GUI is now hosted on http://pogo.abb.ink/RocketTheme/
This URL is also shown in the console when you launch the bot."

**Comment by rickard2014** [comment]
I have this happening when I try to log there.

![sem titulo](https://cloud.githubusercontent.com/assets/20989990/17621623/e8a9552e-606a-11e6-9a9a-982d1c056d4f.png)

**Comment by staurakis** [comment]
Have you first run the program????

**Comment by Peyphour** [comment]
This can't be an issue with your router and/or firewall.
Most likely either you didn't started the bot or you changed the default settings

**Comment by staurakis** [comment]
@Peyphour Actually, if you don't have internet you can't access the gui since it is an external link to your pc and not a direct internal network call to your machine... ;)
But that's nothing to do with the original question :)

**Comment by Peyphour** [comment]
Yeah but the connection between the website and the websocket server is totally local

**Comment by staurakis** [comment]
@Peyphour to be honest i don't get how an external call from an external site to my local 8001 port can be local, but i was referring more, to the fact that if he had a firewall that prevent him to access http://pogo.abb.ink/RocketTheme this url, he wouldn't be able to see anything.

**Comment by Peyphour** [comment]
The call is made via JavaScript using the Socket.io library. JavaScript is executed on your browser i.e : your local machine

**Comment by staurakis** [comment]
ok got it!
Checking the code now, trying to understand how it works, just before you reply, I noticed that the old gui is still working as well: http://pogo.abb.ink/0.5.0-alpha4/map.html
For somebody that wants to still have it as it was with the GPX thing as well ;)

**Comment by Peyphour** [comment]
Yeah I used that to understand how the GPX thing works

**Comment by rickard2014** [comment]
I ran the bot and this showed up...

Seemed to be working fine

![sem titulo](https://cloud.githubusercontent.com/assets/20989990/17622480/0cb0a55c-6071-11e6-9ff0-952842fa96c8.png)

**Comment by Peyphour** [comment]
-4.7E7 this is a huge number, are you sure ?

**Comment by rickard2014** [comment]
FIXED! I missed that dot, sorry guys.

Thank you very much.
