### ISSUE TITLE
Force Bot to perform banSpinCount

### ISSUE THREAD

**Issue by zoegalaxy** [jabbink/PokemonGoBot#1028]
**Description:**
Consistent CATCH_FLEE status on bot similar to #1016 .

We know it is a softban but I was hoping if we could do a force spin (banSpinCount) in case our bots don't detect that they are on softban or we just want to spin the pokestop 40x to ease our worries.

**Expected behavior:**
Detect BAN and spin pokestop 40x.

**Actual behavior:**
Does not detect BAN and continuous to catch pokemon with CATCH_FLEE status.

Either the bot is ban or not, but I still want to spin pokestop 40x.

**Version:**
0.5.2

**Operating System:**
Mac OSX

**Comment by Mixone-FinallyHere** [comment]
the bot knows

also issues has a template for a reason

**Comment by swtrpeter** [comment]
I thought the usual softban bypass was patched by Niantic.

**Comment by zoegalaxy** [comment]
@Mixone-FinallyHere there you go. updated.

**Comment by zoegalaxy** [comment]
@swtrpeter is it? because few moments ago, I just saw my other bot detected a BAN (CATCH_FLEE too) and it spin the pokestop 40x then it continues.  Able to catch pokemon now.

**Comment by swtrpeter** [comment]
@zoegalaxy Maybe it is not.. Someone commented on another thread saying it was. Maybe servers were down when they were trying it. Sorry

**Comment by zoegalaxy** [comment]
@swtrpeter confirmed bro, it is not working anymore.  Weird my other bot just did it 2 hours ago and it worked.  Anyway, I personally went to a Pokestop and there it won't work anymore.  Now my main account has been softbanned and so far no resolve yet.  I can't catch pokemons anymore, but I can battle gyms. =)
