### ISSUE TITLE
GUI map no longer showing catch icons

### ISSUE THREAD

**Issue by russr123** [jabbink/PokemonGoBot#1032]
just started today, 8/12
tested on 2 PC's, both look like this.. 

![image](https://cloud.githubusercontent.com/assets/20584235/17629139/e5bc7f32-6086-11e6-8dbe-43b22370202f.png)

**Comment by swtrpeter** [comment]
+1

**Comment by NoobWithBoobs** [comment]
http://pokeapi.co, the site that provided some of the gui elements is down. Likely legal actions

**Comment by NoobWithBoobs** [comment]
Updated, everything back online.

**Comment by janwillem1980** [comment]
It appears to be offline again, it states it doesn't permit hotlinking.

**Comment by jabbink** [comment]
wrong repo, RocketTheme is hosted elsewhere.
