### ISSUE TITLE
Won't accept ToS?

### ISSUE THREAD

**Issue by loganrussell48** [jabbink/PokemonGoBot#1035]
**Description:**
When I start the bot, it loads and then says Accepting ToS, but then a null pointer exception occurs and it stops. 

**Steps to reproduce:**

1. start the bot

**Expected behavior:**
bot should run
**Actual behavior:**
NullPointerException occurs and bot halts

**Stacktrace (If it's a crash):**
http://pastebin.com/4keWQ8RN

**Version:**
0.5.2 precompiled
**Operating System:**
Ubuntu

**Java version:**
1.8 91

**Comment by Sieberkev** [comment]
Your account is (((((probably))))) permanently banned o/ (I have the same with my main account)

**Comment by gise88** [comment]
https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308

**Comment by mrabbie** [comment]
@gise88 is this page recently added or it's always been there? if just recently added, then perma ban is here now..

**Comment by gise88** [comment]
From what I have understood the page was added last night / this morning.. But well.. I am not so sure! :sweat_smile:

**Comment by KleinSamuel** [comment]
Can anyone who got this ban explain to me what he has done? ive got several bots running and just one of the got banned whith the ToS thing.. can we avoid this ban?
