### ISSUE TITLE
Can't get evolve to work

### ISSUE THREAD

**Issue by qfcartal** [jabbink/PokemonGoBot#1037]
Running multiple accounts through json files on OSX. After starting the bot, json files get overwritten and remove evolve configurations.

**Comment by classicalDonkey** [comment]
I think that is cus of the config file is still being used, I maybe wrong but you have to move that away from the same folder

**Comment by qfcartal** [comment]
deleted the config file, still happening

**Comment by Sieberkev** [comment]
This feature was not merged into develop/release on the time this issue was made, so it removed those keys from your config.

This is merged now, so it should work now!
