### ISSUE TITLE
Can loot but unable to catch

### ISSUE THREAD

**Issue by dwfz** [jabbink/PokemonGoBot#1038]
Can loot pokestops but unable to catch pokemon, every single one flees...not sure if different type of ban or if this has happened to anyone else

**Comment by vladkvs23** [comment]
Yep, broke as of few hours ago. Catches 1-2 pokemons then gets soft-banned and can't catch anything, but I can still loot pokestops. I've tried to add a pause after pokemon encounter to make it seem more real, and updating to the latest API lib.. No idea what may have changed, but it seems like they are on to us..

**Comment by dwfz** [comment]
One of my other accounts is working fine but my main account and my friends that were running are currently in this "soft ban" state

**Comment by vladkvs23** [comment]
I wonder if its related to the rate at which we are gathering pokemons/stardust/XP

**Comment by dwfz** [comment]
Probably something to do with catch rate per hour I'm guessing

**Comment by gise88** [comment]
Maybe related to https://github.com/jabbink/PokemonGoBot/issues/1039

**Comment by Sieberkev** [comment]
#1095 added optional delays between catching and limits to stop the bot when you reach a certain amount
