### ISSUE TITLE
Solved that unable to catch pokemon softban

### ISSUE THREAD

**Issue by zhoushifeng8** [jabbink/PokemonGoBot#1039]
I believed that because bot throw too many excellent balls, so it active the softban, so just find one pokemon throw 50 balls don't hit that pokemon, then it will unban. It works for me and my friends, hope it work for you

**Comment by gise88** [comment]
Thank you for sharing this! I will try this for sure.. :grin:

**Comment by Loganxu** [comment]
Can't catch after threw more than 100 balls, can loot.

**Comment by NoobWithBoobs** [comment]
worked, nice

**Comment by hdzmozquito** [comment]
Hmmmm I have tried, but not work

**Comment by nhodges** [comment]
What were your config settings when you ran into this? I think this happened to me when I increased the chance of catching unwanted pokemon.

**Comment by conradsze** [comment]
There are some new kinds of soft ban
https://www.reddit.com/r/pokemongodev/comments/4xkqmq/new_ban_types_and_their_causes/
In short, just try not to capture more than a thousand pokemons or loot more than 2000 pokestops in a day, and also don't run too many accounts using the same IP address

**Comment by Sieberkev** [comment]
#1095 added optional delays between catching and limits to stop the bot when you reach a certain amount
