### ISSUE TITLE
[Suggestion] Random/Human Variance

### ISSUE THREAD

**Issue by Primpri** [jabbink/PokemonGoBot#104]
I've noticed a few issues similar to what I'm requesting:
Speed: https://github.com/jabbink/PokemonGoBot/issues/83
Region: https://github.com/jabbink/PokemonGoBot/issues/63
Catching: https://github.com/jabbink/PokemonGoBot/issues/59

It'd be nice to have variables in the config file which allow you to set values for:
The time between actions that the bot performs
The max time that the bot can remain active without a break (and set max time of break)
The speed at which the player moves
The range from initial coordinates.
Failure rate of catching pokemon & the time between catching them

Each of these should be random ranges to make it more difficult to detect.

**Comment by pr0ves** [comment]
Closing because duplicate.
