### ISSUE TITLE
[Feature Request] - Bot Timeout & Stack evolves without lucky egg

### ISSUE THREAD

**Issue by gise88** [jabbink/PokemonGoBot#1040]
## Feature requests/proposals
I have two requests:

- Sometimes, before going to bed or going out, I turn on the bot. It would be possible to put a kind of time-out to make sure that the bot will stops after a certain time? I don't want to run the bot so much time continuously.. 

- I really do like the last feature "stack-evolves" but I don't like the fact that it will use my lucky eggs.. Can we choose if the bot has to use them or not? To me the bot have to be a free help.. When there will be no bot (hopefully not soon) these eggs will be very important!

Thank you for your amazing job!

**Comment by badeip** [comment]
On linux it should be possible to use `timeout` for the former request (untested)

Run from 1 to 3 hours:

    timeout $(($RANDOM % (10800 + 1 - 3600) + 3600)) java -jar ./PokemonGoBot-0.5.2.jar

**Comment by gise88** [comment]
@badeip Thanks for this but some of my friends are Windows users.. I am a dev but is my first time with Kotlin! :grin: If someone expert want to implement those feature I believe that the whole community will enjoy it.. :smile:

**Comment by Sieberkev** [comment]
First one has been implemented by @1095
Second one has been implemented by @1082
