### ISSUE TITLE
GUI Problems

### ISSUE THREAD

**Issue by ponyatomic** [jabbink/PokemonGoBot#1041]
I cant open the GUI, it just stay at the CMD, I'm usind prebuilt, on the tutorial https://github.com/jabbink/PokemonGoBot/blob/develop/USAGE.md

Anyone has this problem too?

**Comment by gise88** [comment]
open this http://pogo.abb.ink/RocketTheme/ and press start

**Comment by ponyatomic** [comment]
Yes, i discovered now, thanks =D
