### ISSUE TITLE
Cant use more than one account

### ISSUE THREAD

**Issue by addisonrudd** [jabbink/PokemonGoBot#1043]
you guys probably already know the issue. I put a .json file in one of the bot settings folder but that didnt do anything. help?

**Comment by dwfz** [comment]
did u clear the sign in info from the config.properties?

**Comment by gunzza** [comment]
i found error like this

http://pastebin.com/nDCayj6P

**Comment by vUrbsex** [comment]
I have had the same problem it, you have to restart your computer and it will work again but still you cant run 2 acc at the same time. I could before i don't know why you can't anymore

**Comment by AlexBoulyga** [comment]
"Adresse already in use" - could that be port 8001 that you configured in the settings?

**Comment by addisonrudd** [comment]
@AlexBoulyga what other ports can i use?

**Comment by AlexBoulyga** [comment]
You have to select any port that is a) not used b) open. I mist damit that I dont know if it will help, but how about trying 8002? My previous post was more of a guess based on the log.

**Comment by ansalls** [comment]
Alex is right

**Comment by Danman00** [comment]
The problem with the address already in use is that 
1 you'r already running a java Process 
2 the port 8080 ist already in use from your PC 

the solution for 2 is to start the bot with 
`java -jar PokemonGoBot-0.5.2.jar --server.port=8090`

**Comment by Armxy** [comment]
Hi, I founded that when running muti bot at the same times, you will need to specify the different port  `guiPortSocket` on each *.json files in bot-settings.
