### ISSUE TITLE
Unable to log in to the server

### ISSUE THREAD

**Issue by emperol2** [jabbink/PokemonGoBot#1044]
**Description:**
Unable to log in to the server

**Steps to reproduce:**

#033[32m13 Aug 04:50:45 [default] - Trying to read /PokemonGoBot/config.properties
#033[0;39m#033[37m13 Aug 04:50:45 [default] - Logging in to game server...
Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
#011at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
#011at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
#011at com.pokegoapi.api.settings.Settings.updateSettings(Settings.java:82)
#011at com.pokegoapi.api.settings.Settings.<init>(Settings.java:69)
#011at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:93)
#011at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:180)
#011at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:145)
#011at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
#011at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
#011at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403

**Expected behavior:**
The user should be able to get into the server

Thanks,
Nuttapon P.

**Comment by R1mupp3t** [comment]
Download the actual Pokemon Go app on your phone and try logging in, if still no access, you have received the new permanent BAN from Niantic.

**Comment by emperol2** [comment]
Thank you, I can still logged in to the game from actual Pokemon Go app :) I was thinking about the IPbanned and I tried to create a new server on cloud but I had no luck at all.

Thanks,
NP

**Comment by R1mupp3t** [comment]
I have read in other posts that some users reported success just from restarting their router when the Bot couldn't log into the server. Worth a try? 
JB

**Comment by emperol2** [comment]
I will give it a try with restarting my router! I will let you guys know if this works.

Thanks,
NP

**Comment by vx600** [comment]
Same issue here, trying to log-in with Google, password base64 encoded. App works fine, bot throws the error above.

**Comment by AlexBoulyga** [comment]
Cloud servers are completely banned now I have heard, @emperol2
