### ISSUE TITLE
[Feature Request] Randomize Bot Behaviour

### ISSUE THREAD

**Issue by AlexBoulyga** [jabbink/PokemonGoBot#1047]
Dear PokemonGoBot Developers,
I looked through your code which I found really interesting, and noticed it missed some simple randomized behaviour.
In my mind I have: Curved Rate instead of true or false set to a value (so that its sometimes curved sometimes not).
Randomized speed in a definable range around the normal speed property
Random stops and pauses for a random time, both settable (wait chance, minimal wait time, maximal wait time)

I have already wrote some working code for that, and would like to contribute it to the project if thats ok.

greetings and thanks for the great bot

**Comment by jabbink** [comment]
Nice. Another feature could be to sometimes miss pokeballs. And wait between throws and evolves.

**Comment by shilch** [comment]
Yes, I think this feature is necessary. https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/

**Comment by AlexBoulyga** [comment]
Thats what I also thought, but I hadnt enough time to look Into it yet

**Comment by AlexBoulyga** [comment]
I would even say not only miss, as its easy to Hut the Pokémon, but to throw different kinds of balls linke nice, great etc.

**Comment by AlexBoulyga** [comment]
Ok I analyzed the code, there is already this catching probability for desired/undesired catches. I logged the number of tries, and sometimes the bot needs one, sometimes even 3 tries.
After further digging I found out that this probability only affects which kind of ball you use and similar parameters.
As far as I can say now it always hits the same spot (which is really obvious for niantic/google) which should be changed and the size of the coloured circle is always nearly the same.
I managed to randomize it a little, however it needs better testing and beeter/cleaner code, so it might take a day or even two (considering its weekend now). Anyways, I'll keep this updated

**Comment by gise88** [comment]
Setting.tk (commit https://github.com/jabbink/PokemonGoBot/commit/983ae4ec2fb802394b7c7a32cb63fd4682ca5e52) is still read option "always_curve" (https://github.com/jabbink/PokemonGoBot/blob/develop/src/main/kotlin/ink/abb/pogo/scraper/Settings.kt#L94) but in the config.properties.template (https://github.com/jabbink/PokemonGoBot/blob/983ae4ec2fb802394b7c7a32cb63fd4682ca5e52/config.properties.template#L120) the option "always_curve" was replaced with "desired_curve_rate".

**Comment by AlexBoulyga** [comment]
Thank you very much! This is a bug I somehow oversaw!

**Comment by CLGitDev** [comment]
@AlexBoulyga This will be a very cool feature - was about to raise a ticket for the exact same thing and come across this thread. :+1:

**Comment by Antexa** [comment]
Don't you think that extend this random behavior to the transfer function could be a great things too ?

**Comment by AlexBoulyga** [comment]
Added randomized throwing as described.
Will look next at the way the balls hit the pokemon, which I dont understand yet completely and about a small timeout waiting for throwing the next ball (which should be easy).


The transfer function is also a good thing, I will take a look at it too. If it doesnt yet, it should only transfer as soon as it has 5-10 pokemon (f.e.) that need a transfer I would suggest, what do you think @Antexa ?

**Comment by Antexa** [comment]
@AlexBoulyga Yeah i think it's the correct way to handle it. Maybe add a random delay between each transfer.

**Comment by patzor** [comment]
hi guys and specially the developers, can you guys put like a range or amount the bot will go to sleep after like 100-1500 pokestops that would be great.. thank you all!! peace

**Comment by AlexBoulyga** [comment]
I just added it in my repo! A few tweaks and i will create a PR. However its a stop, not a Pause of the bot. You will be able to set time, pokestops and pokemons AS a limit

**Comment by NoobWithBoobs** [comment]
@AlexBoulyga another item you may want to consider is the gps signal delay. Lag, latency and such. This may reduce the patterns too

**Comment by NoobWithBoobs** [comment]
and accuracy!

**Comment by AlexBoulyga** [comment]
So currently waiting for approval in #1095 
time delays between transfer/drops/evolves
timeouts after X pokestops/pokemon/minutes
pokemon to never catch option

ToDo:
Random speed depends on previous speed(s)
Look at how throwing exactly works (there is some variable i dont understand yet, probably the spot where you hit the pokemon)
Any other ideas?
@NoobWithBoobs  what do you mean by accuracy?
I dont know about gps  but I believe the providers we use have enough lag :D
I also have heard the gps currently is no straight line, even if it looks a bit like one

**Comment by AlexBoulyga** [comment]
AS #1095 is merged this issue is resolved
