### ISSUE TITLE
'Pausing to catch a pokemon' continuous message

### ISSUE THREAD

**Issue by staurakis** [jabbink/PokemonGoBot#1049]
13 ┴Ϋή 13:55:20 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:55:22 [default: PokestopLoop] - Looting nearby pokestop 1cf04fc112374e8f92f05fba0983d0f3.16
       13 ┴Ϋή 13:55:28 [default: PokestopLoop] - Looted pokestop 1cf04fc112374e8f92f05fba0983d0f3.16; +100 XP, but inventory is full: []
       13 ┴Ϋή 13:55:31 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:55:36 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:55:41 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:55:46 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:55:51 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:55:56 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:55:59 [default: PokestopLoop] - Looting nearby pokestop 6a350acf3cbe4a998f0012ca7a114ea4.16
       13 ┴Ϋή 13:56:00 [default: PokestopLoop] - Looted pokestop 6a350acf3cbe4a998f0012ca7a114ea4.16; +100 XP, but inventory is full: []
       13 ┴Ϋή 13:56:02 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:56:07 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:56:11 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:56:17 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:56:17 [default: WalkingLoop] - Destination reached.
       13 ┴Ϋή 13:56:18 [default: WalkingLoop] - Walking to (37.978752, 23.724191) in 224.154516248491 steps.
13 ┴Ϋή 13:56:18 [default: ProfileLoop] - Profile update: 2434475 XP on LVL 30; 434475/500000 (86,89%) to LVL 31
13 ┴Ϋή 13:56:18 [default: ProfileLoop] - XP gain: 61.380 XP in 84 mins; XP rate: 43.800/hr; Next level in: 1,50 hr
13 ┴Ϋή 13:56:18 [default: ProfileLoop] - Pokemon caught/transferred: 56/85; Pokemon caught from lures: 4; Items caught/dropped: 388/286;
13 ┴Ϋή 13:56:18 [default: ProfileLoop] - Pokebank 171/350; Stardust 847141; Inventory 851/850
       13 ┴Ϋή 13:56:19 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:56:19 [default: ProfileLoop] - Wrote export.
13 ┴Ϋή 13:56:19 [default: ProfileLoop] - Stack of pokemon ready to evolve: 0 pokemons
       13 ┴Ϋή 13:56:23 [default: PokestopLoop] - Looting nearby pokestop 78695f50556b41c8bd810ebefcf1e3da.16
       13 ┴Ϋή 13:56:24 [default: PokestopLoop] - Looted pokestop 78695f50556b41c8bd810ebefcf1e3da.16; +100 XP, but inventory is full: []
       13 ┴Ϋή 13:56:25 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:56:30 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:56:35 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:56:40 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:56:45 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:56:50 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:56:55 [default: WalkingLoop] - Pausing to catch pokemon...
       13 ┴Ϋή 13:56:58 [default: PokestopLoop] - Looting nearby pokestop 4cc22cf13fa44ee88f90fcab3543b4e9.16
       :run FAILED

**Comment by vUrbsex** [comment]
Pls use pastebin

**Comment by staurakis** [comment]
I'm sorry, we used to just paste it here that's why i did it like that. 
Will use my pastebin from now on.

**Comment by Sieberkev** [comment]
Did you try to login on your smartphone and check if it works there? I've seen similar problems on banned accounts.

**Comment by staurakis** [comment]
no no it wasn't a ban. An immediate restart fixed it. I have experienced once more and i think it happens when there is a network disconnection. 
I am trying to check it but it look like it happens so fast that it's difficult to cross check.
I will let you know though if i find out.

**Comment by staurakis** [comment]
hapenned something similar after many hours that runs without issues:
http://pastebin.com/td5EpDGN

**Comment by Sieberkev** [comment]
The first error is mostly the result of a softban. #1095 added optional delays between catching and limits to stop the bot when you reach a certain amount

The last error is a known issue in the API that (hopefully) will be fixed with the new one #1237
