### ISSUE TITLE
GUI didn't show pokemon picture

### ISSUE THREAD

**Issue by johnluan** [jabbink/PokemonGoBot#1050]
It shows error.
Error 1011 Ray ID: 2d1ba85e83974d7c • 2016-08-13 10:59:27 UTC
Access denied
What happened?
The owner of this website (pokeapi.co) does not allow hotlinking to that resource (/media/sprites/pokemon/143.png).

![image](https://cloud.githubusercontent.com/assets/1707927/17642838/2f05f138-6199-11e6-99b0-6d72449532a5.png)

**Comment by IgnitEngineer** [comment]
how do u even use the GUI on mac. There is no tutorial in usage.md

**Comment by jabbink** [comment]
Wrong repo

https://github.com/eruecco87/PokemonGoBot-RocketTheme

**Comment by Taclaa** [comment]
I have this problem also. The answers here don't help me :)
