### ISSUE TITLE
Pokemon ID in exported file is wrong

### ISSUE THREAD

**Issue by eddienko** [jabbink/PokemonGoBot#1051]
**Description:**
The Pokemon ID (last column) in the exported CSV file is wrong for some Pokemon.

**Steps to reproduce:**
Activate export=csv in config

**Actual behavior:**
Some IDs are negative, presumably because they are long long integers and out of the range of the stored variable. Examples:

Number,Name,ID
69,BELLSPROUT,-6463178872057306049
69,BELLSPROUT,2571273732060899026
9,BLASTOISE,-8125734063912055803

**Comment by jabbink** [comment]
It's not "wrong" per se. It is still a unique identifier. Pokemon with a negative ID have the same negative ID at all times.

**Comment by eddienko** [comment]
It is actually wrong. E.g. My Venosaur has according to this app an ID of -8877752060268277895. Using the python api to get the inventory, I get his current ID of 9568992013441273721L. The ones which are not long in python are ok, the rest are negative and wrong.
