### ISSUE TITLE
[Hint/Suggestion] Check ${settings.latitude},${settings.longitude} for num value

### ISSUE THREAD

**Issue by HoneyWheat** [jabbink/PokemonGoBot#1053]
If you have a typo in latitude / longitude, for examaple a missing = can lead to "0 pokestops found".

I suggest to check if ${settings.latitude}, ${settings.longitude} does have a num value instead of using null or empty string as 0.

@devs: you can close this issue after reading

**Comment by janwillem1980** [comment]
As  I use Google Maps to find the coordinates, it would be great if it accepted them formatted like this too, e.g.

location=53.219366, 6.567831 (when filled in ignore long/lat)
longitude=53.219366, 6.567831 (comma detected, use entry string as coordinate)
latitude=53.219366, 6.567831 (comma detected, use entry string as coordinate)
 
This way it's much faster copy/pasting to change locations. 

Would be great if that could be added!

**Comment by patzor** [comment]
it should be like this

# Token to login directly
token=
latitude=53.219366
longitude=6.567831
