### ISSUE TITLE
Not Catching Pokemon

### ISSUE THREAD

**Issue by EpicAwesomeWolf** [jabbink/PokemonGoBot#1056]
**Description:**
No Pokemon are being caught.

**Expected behavior:**
Pokemon should be caught.

**Actual behavior:**
I get CATCH_FLEE

**Version:**
Latest

**Operating System:**
Mac OS X, El Capitan

**Java version:**
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

**Comment by swtrpeter** [comment]
may have a soft ban.. Have u tried changing ip ?

**Comment by ansalls** [comment]
Have you tried reading through the issues before posting?

**Comment by zby920415** [comment]
You could throw poke balls to the forest more than 100 times without touching the pokemon to unban. I just finished it!

**Comment by zby920415** [comment]
Also, you may set the desired_catch_probability as low as 0.3 or 0.4 and decrease the walking speed to limit exp/h.

**Comment by janwillem1980** [comment]
Did you catch more than 250 pokemon? Maybe your bag is full?

**Comment by xxzeng** [comment]
If level up 22 in one day, account will be soft ban.

**Comment by Sieberkev** [comment]
#1095 added optional delays between catching and limits to stop the bot when you reach a certain amount to avoid softbans
