### ISSUE TITLE
Rocket Theme not displaying Pokemon pictures

### ISSUE THREAD

**Issue by pet90210** [jabbink/PokemonGoBot#1059]
**Description:**
Rocket Theme is not displaying Pokemon pictures ..
can anyone help?
![bildschirmfoto 2016-08-13 um 21 12 11](https://cloud.githubusercontent.com/assets/20575916/17645335/09ef9014-619b-11e6-9404-f1ba8aea5202.png)

**Steps to reproduce:**

1. Start Server
2. http://pogo.abb.ink/RocketTheme/

**Expected behavior:**
Should show caught pokemon pictures

**Actual behavior:**
Doesn't show them

**Stacktrace (If it's a crash):**

**Version:**
v0.5.2

**Operating System:**
Mac OSX 10.11.6
**Java version:**

ava version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by Tockra** [comment]
Same here

**Comment by joligario** [comment]
#1050
