### ISSUE TITLE
How to setting to avoid softban?

### ISSUE THREAD

**Issue by zhoushifeng8** [jabbink/PokemonGoBot#1061]
Have been soft ban twice in 2 days. Cannot catch pokemon, how to setting to avoid?

**Comment by Sieberkev** [comment]
What is your configuration (speed)? Keep it as realistic as possible (2.4 ish works perfect for me).
Don't jump around gps locations too far without pausing a realistic time between.

**Comment by AlexBoulyga** [comment]
If you use the developer version, there are a few new randomizing settings for that reason, check it out :)

**Comment by conradsze** [comment]
#1039 avoid to catch more than 1000pokemons or loot more than 2000 stops in a day

**Comment by staurakis** [comment]
@conradsze wow! that's new?! i seem to 'experience' it using the bot... Tomorrow i have to also cross check through Niantic's app as well.

**Comment by Sieberkev** [comment]
#1095 added optional delays between catching and limits to stop the bot when you reach a certain amount
