### ISSUE TITLE
NullPointerException at login

### ISSUE THREAD

**Issue by Taraegon** [jabbink/PokemonGoBot#1068]
**Description:**
As per the log below. Fails to login successfully

**Steps to reproduce:**

1. Attempt to login

**Expected behavior:**
Successful login. No change to config file since previous login

**Actual behavior:**
Crash

**Stacktrace (If it's a crash):**
15 Aug 00:30:12 [default] - Logging in to game server...
15 Aug 00:30:16 [default] - Logged in successfully
Getting profile data from pogo server.
15 Aug 00:30:19 [default] - Accepting ToS
Exception in thread "default" java.lang.NullPointerException
	at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:43)
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:294)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:145)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Version:**
v0.5.2

**Operating System:**
OSX 10.9.5

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by AlexBoulyga** [comment]
Your bot cant accept the ToS screen somehow. Maybe they have changed it. I think you must manually do this once if it is a new account  (to get the bot going right now).

**Comment by Sieberkev** [comment]
Your account = banned

Try to login on the official app and when it says "can not retrieve game data, retry", RIP

**Comment by Taraegon** [comment]
Will try via the official app. wish me luck lol

**Comment by gabrielklein** [comment]
You have been banned (as I was) ;)

**Comment by AlexBoulyga** [comment]
It is a permaban, over 3 days now at my acc

**Comment by Taraegon** [comment]
Leaves me with one other account. Gotta be careful now...

**Comment by Sieberkev** [comment]
Yep, RIP pokemons.

I fiddled around a bit with the API on my main account (which is banned too), I could fetch my profile data but all stats/pokes/items were completely erased.

**Comment by gunzza** [comment]
Banned

**Comment by pvase666** [comment]
@Sieberkev  how to check that.

**Comment by gabrielklein** [comment]
start the application with your phone... if you cannot start it, time to play another game.

**Comment by Sieberkev** [comment]
@pvase666 in the Main.tk after the `print("Getting profile data from pogo server")` block you can try and call several api.* objects (`api.inventories.pokebank.pokemons.size`) and output their data...

**Comment by raa3f** [comment]
Yup banned. 
I've been running a bot for 5days cause for last 1 week my gym was occupied by 8 trainers all lvl29-34, Dragonites with 2300+ CP.

Went and kicked some a$$ this morning. Now the account does not work anymore. However my original account works fine. So the bot account has been banned today.
