### ISSUE TITLE
Bug at getting map of (xxxx,xxxx) without walk

### ISSUE THREAD

**Issue by skfunghk** [jabbink/PokemonGoBot#1072]
**Description:**
Keep getting map of xxxx,xxxx, is it possible ban of my account / ip?

**Steps to reproduce:**

log showing
14 8る 10:55:15 [default: BotLoop] - Using ITEM_POKE_BALL; Using curve; achieved catch probability: 0.43478402, desired: 0.4
14 8る 10:55:16 [default: BotLoop] - Caught a PSYDUCK with CP 542 and IV 35%
 Stamina: 12 | Attack: 3 | Defense: 1 | IV: 16 (35%) (wild pokemon) : [210x XP, 3x Candy, 100x Stardust]
14 8る 10:55:19 [default: BotLoop] - Getting map of (22.29533083734945, 114.16760136816048)
14 8る 10:55:24 [default: BotLoop] - Getting map of (22.29531558619172, 114.16754155525449)
14 8る 10:55:29 [default: BotLoop] - Getting map of (22.295312723070484, 114.16750572866935)
14 8る 10:55:34 [default: BotLoop] - Getting map of (22.29535603203302, 114.1675113879291)
14 8る 10:55:39 [default: BotLoop] - Getting map of (22.29537112491532, 114.1675338191788)
14 8る 10:55:44 [default: BotLoop] - Getting map of (22.29533803791995, 114.16750472090703)
14 8る 10:55:50 [default: BotLoop] - Getting map of (22.295293405026037, 114.16759242475332)
14 8る 10:55:55 [default: BotLoop] - Getting map of (22.295367949135738, 114.16756324815609)

**Expected behavior:**
it should be getting then walk, but it didn't

**Comment by classicalDonkey** [comment]
I am getting this aswell, but it has a error before saying cant connect to the server for location sorting.

**Comment by vladkvs23** [comment]
It seems that the service is having issues (http://yournavigation.org/api/dev/route.php)

**Comment by AlexBoulyga** [comment]
I have turned off streets, but it still sometimes lags :/

**Comment by Sieberkev** [comment]
This is fixed in the development branch + we've added a bunch of other route providers!
