### ISSUE TITLE
Getting initial pokestops... error

### ISSUE THREAD

**Issue by chudungg** [jabbink/PokemonGoBot#1077]
**Description:**
I try to edit initialmapsize in the config to 6 and still not working...

> 15 Aug 03:55:43 [default] - Level 1, Experience 600
> 15 Aug 03:55:43 [default] - Pokebank 1/250
> 15 Aug 03:55:43 [default] - Inventory 53/350
> 15 Aug 03:55:43 [default] - Have PIKACHU () with 11 CP and IV 66% 
>  Stamina: 10 | Attack: 10 | Defense: 10 | IV: 30 (66%)
> 15 Aug 03:55:43 [default] - Getting map of (10.774516707227948, 106.70667364954815)
> 15 Aug 03:55:43 [default] - Getting initial pokestops...
> 15 Aug 03:55:44 [default] - Got 0 pokestops
> 15 Aug 03:55:44 [default] - Retrying in 10 seconds...
> 15 Aug 03:55:54 [default] - Got 0 pokestops
> 15 Aug 03:55:54 [default] - Retrying in 10 seconds...
> 15 Aug 03:56:05 [default] - Got 0 pokestops
> 15 Aug 03:56:05 [default] - Decreasing initialMapSize to 7
> 15 Aug 03:56:05 [default] - Retrying in 10 seconds...

**Version:**
0.5.2

**Operating System:**
mac os
**Java version:**
jdk 8

**Comment by jabbink** [comment]
Don't quit the process. It says retrying for a reason. It will eventually end. Come back with a full log.

**Comment by staurakis** [comment]
Something is wrong....every pokemon suddenly flees....
No pokestop apears where there are pokestops and all pokemons flee.
I changed IP but the behaviour is the same. I logged in using Niantic app but pokemons appear in the radar so i'm not banned. Unfortunately where i am right now there are no pokestops to check....

**Comment by chudungg** [comment]
here is the full log

> > 15 Aug 05:08:22 [default] - Level 1, Experience 600
> 15 Aug 05:08:22 [default] - Pokebank 1/250
> 15 Aug 05:08:22 [default] - Inventory 53/350
> 15 Aug 05:08:22 [default] - Have PIKACHU () with 11 CP and IV 66% 
>  Stamina: 10 | Attack: 10 | Defense: 10 | IV: 30 (66%)
> 15 Aug 05:08:22 [default] - Getting map of (10.790181549775832, 106.69736890830042)
> 15 Aug 05:08:22 [default] - Getting initial pokestops...
> 15 Aug 05:08:23 [default] - Got 0 pokestops
> 15 Aug 05:08:23 [default] - Retrying in 10 seconds...
> 15 Aug 05:08:33 [default] - Got 0 pokestops
> 15 Aug 05:08:33 [default] - Retrying in 10 seconds...
> 15 Aug 05:08:44 [default] - Got 0 pokestops
> 15 Aug 05:08:44 [default] - Decreasing initialMapSize to 0
> 15 Aug 05:08:44 [default] - Retrying in 10 seconds...
> 15 Aug 05:08:55 [default] - Got 0 pokestops
> 15 Aug 05:08:55 [default] - Retrying in 10 seconds...
> 15 Aug 05:09:05 [default] - Got 0 pokestops
> 15 Aug 05:09:05 [default] - Retrying in 10 seconds...
> 15 Aug 05:09:16 [default] - Got 0 pokestops
> 15 Aug 05:09:16 [default] - Cannot decrease initialMapSize even further. Are your sure your latitude/longitude is correct?
> 15 Aug 05:09:16 [default] - This is what I am trying to fetch: https://www.google.com/maps/@10.7902164,106.6973372,15z
> 15 Aug 05:09:16 [default] - Retrying in 10 seconds...
> 15 Aug 05:09:26 [default] - Got 0 pokestops
> 15 Aug 05:09:26 [default] - Retrying in 10 seconds...
> 15 Aug 05:09:37 [default] - Got 0 pokestops
> 15 Aug 05:09:37 [default] - Retrying in 10 seconds...
> 15 Aug 05:09:48 [default] - Got 0 pokestops
> 15 Aug 05:09:48 [default] - Cannot decrease initialMapSize even further. Are your sure your latitude/longitude is correct?
> 15 Aug 05:09:48 [default] - This is what I am trying to fetch: https://www.google.com/maps/@10.7902164,106.6973372,15z
> 15 Aug 05:09:48 [default] - Retrying in 10 seconds...
> 15 Aug 05:09:58 [default] - Got 0 pokestops
> 15 Aug 05:09:58 [default] - Retrying in 10 seconds...

>

**Comment by swtrpeter** [comment]
@chudungg  are you trying to use proxy ?

**Comment by chudungg** [comment]
no iam not

**Comment by Animehq** [comment]
same for me

**Comment by patzor** [comment]
try logging in to the acct using your mobile phone make sure the bot is not running..

**Comment by AlexBoulyga** [comment]
Soft ban usually behaves like that

**Comment by chudungg** [comment]
already tried my man @patzor

**Comment by chudungg** [comment]
@AlexBoulyga
i still catch pokemon and take item from pokestop when using my phone app

**Comment by AlexBoulyga** [comment]
Wait a few hours, then it will be normal

**Comment by chudungg** [comment]
@AlexBoulyga
i already try after six hours... its not softban man

**Comment by AlexBoulyga** [comment]
Have you tried a different location? I have no idea then, sorry..

**Comment by chudungg** [comment]
@AlexBoulyga Also tried... still unlucky :(

**Comment by AlexBoulyga** [comment]
Does the bot work with a different account?

**Comment by chudungg** [comment]
@AlexBoulyga already try few acc but samething happen
1 acc level 17
1 acc level 2
1 acc level 1 (not appear in any location yet)

**Comment by AlexBoulyga** [comment]
If the bot doesnt work with any account, try deleting everything, downloading the bot again and configuring it again

**Comment by chudungg** [comment]
I find out this mac didnt turn the gps on... that why i got this error
Issue Close

Tks @AlexBoulyga and everyone for trying to help me
