### ISSUE TITLE
Do I need a Google device token everytime?

### ISSUE THREAD

**Issue by Mewks** [jabbink/PokemonGoBot#108]
Hi,

Since I keep getting the LoginException error every 30mins, I'm wondering if theres a way I can avoid having to go to google.com/device every single time I have to start the bot?

At the moment I have to go get a token from google.com/device every 30mins? Not really practical for a bot!

Just wondering if I'm missing something.

**Comment by Lenovotro** [comment]
Aside from having a bot that can grab and verify new tokens, I don't think you can do anything.

**Comment by Mewks** [comment]
Ahhh that's frustrating, ok.

Does the same LoginException stuff happen with Pokemon Trainer Club accounts? Or is it just Google?

Thanks for your response.

**Comment by Zeift** [comment]
Unless they implement an OAuth to get the refresh token.

**Comment by jabbink** [comment]
Only happens with Google login. PTC works fine. Issue is in the Java API and won't be fixed in this repo.

https://github.com/Grover-c13/PokeGOAPI-Java/issues/98
