### ISSUE TITLE
installing and running on Ubuntu Linux

### ISSUE THREAD

**Issue by patzor** [jabbink/PokemonGoBot#1083]
**Description:**
tried installing it on my vps.. no luck running on it.

./gradlew build:
http://pastebin.com/y4rAAMS9

**Version:**
git clone https://github.com/jabbink/PokemonGoBot.git && cd PokemonGoBot 

**Operating System:**
Ubuntu 14.04 LTS \n \l

**Java version:**
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

**Comment by AlexBoulyga** [comment]
Try Java 8

**Comment by Sieberkev** [comment]
Please install oracle JDK 1.8...

1.7 is not compatible at all, and we've seen strange problems with OpenJDK

**Comment by patzor** [comment]
add-apt-repository ppa:webupd8team/java
apt-get update
apt-get install oracle-java8-installer

thanks guys
