### ISSUE TITLE
Error building latest version

### ISSUE THREAD

**Issue by staurakis** [jabbink/PokemonGoBot#1087]
Hello all,
i have issues building the latest version. Any clues?
http://pastebin.com/5DN4PsFh

**Comment by jabbink** [comment]
Your answer lies in file:///C:/Users/user/Downloads/PokemonGoBot-develop_new/PokemonGoBot-develop/build/reports/tests/index.html

You probably added a config property without adding it to the template or you changed a default without changing it in the code and template.

**Comment by staurakis** [comment]
Firstly, i haven't altered the code. I have put the values in properties.config as all the previous times.
The thing is that the index.html isn't showing an error that i can see at least....

**Comment by AlexBoulyga** [comment]
The .properties file has changed through updates, did you just Re-use an old one?

**Comment by staurakis** [comment]
No no, i took the new one and re enter all values again.
That's the index.html file: http://pastebin.com/Z92EgjWh
I can't understand what's the issue with the last exception though....

**Comment by staurakis** [comment]
ok i have re downloaded the file. I simply renamed to config without putting any values and it built correctly. So something i can't see in the values i put is wrong. I will do it again from the beginning.
Thank you for your help.
