### ISSUE TITLE
Next XP Player Different

### ISSUE THREAD

**Issue by doness** [jabbink/PokemonGoBot#109]
> val nextXP = player.stats.nextLevelXp - player.stats.prevLevelXp
> val curLevelXP = player.stats.experience - player.stats.prevLevelXp

Profile update : 409XXX XP on LVL 22; 149XXX/175000 (85.21%) to LVL 23
The Real XP to 
Level 21 is 50000
Level 22 is 75000
Level 23 is 100000

**Comment by jabbink** [comment]
Fixed a day ago already in #65
