### ISSUE TITLE
Setting property not in config

### ISSUE THREAD

**Issue by AlexBoulyga** [jabbink/PokemonGoBot#1090]
**Description:**
A settings property (transferCpMinThreshold) is not in the settings template and NOT described what it exactly does.
As far as I guess it is the minimum CP in % of the max possible CP of a pokemon - how does that fit together with the other IV and CP threshholds?
Is it even used?

**Steps to reproduce:**

1. Open the template, look through it
2. start bot, see yellow message that a value is not set

**Expected behavior:**
It should be there and explained

**Actual behavior:**
It is not there or explained

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
0.6, and previous

**Comment by Sieberkev** [comment]
https://github.com/jabbink/PokemonGoBot/blob/develop/config.properties.template#L157-L160

Between updates new configuration keys can be added. You have to check the template file and update your current settings file if you do not want the default setting.

**Comment by AlexBoulyga** [comment]
Sorry, my error. I had this message quite a time and didnt realise it was already fixed. Thank you!
