### ISSUE TITLE
[SUGGESTION] It would be great to see a gui for this

### ISSUE THREAD

**Issue by PassiveModding** [jabbink/PokemonGoBot#110]

**Comment by Boraida** [comment]
Or an option for gui

**Comment by jabbink** [comment]
basis for a web interface coming in #81

**Comment by Lupinus** [comment]
I would prefer if it would stay a console application. I can run it on a headless server without any issues. That or make the GUI optional or part of a plugin.

**Comment by apottere** [comment]
It'll definitely be an optional frontend.
