### ISSUE TITLE
Error running loop ProfileLoop: Doesn't update profile 

### ISSUE THREAD

**Issue by Dredzs** [jabbink/PokemonGoBot#1107]
**Description:**
I keep getting the error below. The bot still runs; it loots pokestops, catches pokemon, and walks although it doesn't stay on roads anymore...another issue. What it doesn't do is update my profile (xp gained, pokebank stats, etc).

I've restarted the bot several times as well as restarted my computer. 

Thanks!

> [default: ProfileLoop] - Error running loop ProfileLoop!
> com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
> 	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
> 	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
> 	at com.pokegoapi.api.player.PlayerProfile.acceptLevelUpRewards(PlayerProfile.java:123)
> 	at ink.abb.pogo.scraper.tasks.UpdateProfile.run(UpdateProfile.kt:32)
> 	at ink.abb.pogo.scraper.Bot.task(Bot.kt:254)
> 	at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:137)
> 	at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:35)
> 	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:202)
> 	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
> 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
> Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
> 	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
> 	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
> 	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
> 	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
> 	... 9 more
> Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
> 	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
> 	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
> 	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
> 	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
> 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
> 	at rx.Observable.subscribe(Observable.java:9957)
> 	at rx.Observable.subscribe(Observable.java:9924)
> 	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
> 	... 11 more
> Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
> 	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
> 	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:296)
> 	at java.lang.Thread.run(Thread.java:745)

**Version:**
0.6.0

**Operating System:**
OS X 10.11.5

**Java version:**
1.8.0_101

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by svombergen** [comment]
same

**Comment by Sieberkev** [comment]
What level are you?

**Comment by Dredzs** [comment]
26

**Comment by jabbink** [comment]
https://github.com/jabbink/PokemonGoBot/issues?q=is%3Aissue+Contents+of+buffer+are+null+is%3Aclosed
