### ISSUE TITLE
API

### ISSUE THREAD

**Issue by tenoriojuann** [jabbink/PokemonGoBot#111]
Error:(36, 38) Kotlin: Cannot access 'username': it is 'private' in 'PlayerProfile'
Error:(37, 38) Kotlin: Cannot access 'team': it is 'private' in 'PlayerProfile'
Error:(38, 42) Kotlin: Cannot access 'currencies': it is 'private' in 'PlayerProfile'
Error:(39, 42) Kotlin: Cannot access 'currencies': it is 'private' in 'PlayerProfile'
Error:(41, 87) Kotlin: Cannot access 'pokemonStorage': it is 'private' in 'PlayerProfile'

When trying to compile the source I keep running into these errors.

**Comment by jabbink** [comment]
Already fixed in 7ba6a4878d58227f0fd17252f0899ae2facec70f
