### ISSUE TITLE
Send correct elevation

### ISSUE THREAD

**Issue by jabbink** [jabbink/PokemonGoBot#1122]
**Description:**
Send semi-correct altitude information

**Expected behavior:**
Send better altitude information.

Cache hard, only query altitude and slightly randomize it for a single S2 level 15 (or larger) cell.

Sources:
- https://mapzen.com/documentation/elevation/
- https://developers.google.com/maps/documentation/elevation/intro

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by KyleBoyer** [comment]
https://elevation.dev.mapzen.com/height?json={%22shape%22:[{%22lat%22:40.7829,%22lon%22:-73.9654}]}
