### ISSUE TITLE
Add forced checkstyle test

### ISSUE THREAD

**Issue by jabbink** [jabbink/PokemonGoBot#1125]
**Description:**
Too many PR's add code that does not follow the default indentation and adding commits every once in a while that just re-indent code (and break other PR's) sucks.

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by AlexBoulyga** [comment]
Good idea (i know i am one of the culprits, but a test that does this would make my life easier, and others respectively)

**Comment by mineme45** [comment]
The goal is to check this with travis?

**Comment by Sieberkev** [comment]
Merged with #1246 

More checks can be added if you want! ;)
