### ISSUE TITLE
Your navigation website error 503

### ISSUE THREAD

**Issue by lummuswayne** [jabbink/PokemonGoBot#1134]
**Description:**
about every minute or so i get this error 
[default: PokestopLoop] - Error fetching route from provider: Server returned HTTP response code: 503 for URL: http://yournavigation.org/api/dev/route.php?flat=29.291919629331936&flon=-94.78645472322853&tlat=29.292457&tlon=-94.785742&v=foot&fast=1
**Steps to reproduce:**
Run The Bot like Normal with street follow in 

**Expected behavior:**
not sure what this is requesting for (but it is a error)

**Actual behavior:**
Error in console

**Stacktrace (If it's a crash):**
not a crash

**Version:**
0.6.0
**Operating System:**
windows 10

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by AlexBoulyga** [comment]
The currently used Street Route provider is overloaded, you cant follow streets at the Moment. This error just says ehat the provider answers, 503- overloaded

**Comment by lummuswayne** [comment]
oh wait, i understand now that i have reread my issue ;/ i see its a website issue and not a bot issue
