### ISSUE TITLE
[Request Feature] Filter capturing pokemon by name

### ISSUE THREAD

**Issue by trinhvanhuy** [jabbink/PokemonGoBot#1135]
**Description:**
Thanks for awesome bot, It's working great
But i got softban ( pokemon ban ) after 3 -4 hours runing bot, cause i've catched too many pokemon ( most of all Zubat et Ratata ) it will be cool if there is some way i can tell the bot do not catch those pokemon

**Steps to reproduce:**
 

**Expected behavior:**
 Filter capturing pokemon by name

**Actual behavior:** 
catch all pokemon

**Stacktrace (If it's a crash):** 

**Version:**
0.6

**Operating System:**
MacOS

**Java version:**
1.8

**Comment by AlexBoulyga** [comment]
This is partially implemented, look into the config file. You can set catch rate for not desired Pokémon to -1,  and set other configs appropriately (CP rate etc)

**Comment by AlexBoulyga** [comment]
Thats a solution for now. You could also play with the randomization values too. However this idea AS a feature schouldnt be too difficult to implement

**Comment by trinhvanhuy** [comment]
sure that we can base on CP / rate, but there is some pokemon ( like magikarp, or dratini ... ) i want to catch them all :/ , zubat and ratata, i dont want to catch it even rate is 100% :/

**Comment by AlexBoulyga** [comment]
I will add this in my next commit :)

**Comment by trinhvanhuy** [comment]
Thanks so much :D

**Comment by AlexBoulyga** [comment]
https://github.com/jabbink/PokemonGoBot/pull/1095/commits/cd8ca9ca8f2b801b32ea9bca6f4a8dfea6c0c4eb 
in #1095 
added + tested
you just need to wait until it gets merged :)

**Comment by Sieberkev** [comment]
#1095 is merged in the development version, now you can configure pokemons never getting catched in never_catch_pokemon
