### ISSUE TITLE
[Suggestion] Spesific CP level for spesific pokemon

### ISSUE THREAD

**Issue by CptJackieSparrow** [jabbink/PokemonGoBot#114]
I've been botting in central park.
i have 35 pinsirs now.
so a feature like this would be cool if it's not time consuming to make

**Comment by pr0ves** [comment]
What exactly is the feature?

**Comment by CptJackieSparrow** [comment]
I think i couldn't make it clear. Here's an example.
There are so much pinsirs in NYC.
Also eeves.
I don't want to keep pinsirs unless they are 1400 cp and above.
I'd like to keep eeves higher than 700 cp.
So if i set cp treshold to 700 and add pinsir to "don't want to keep" line, it'll just keep the highest cp pinsir which i'll lose 1399.

**Comment by pr0ves** [comment]
I get it, we'll try to add it in the future.

**Comment by CptJackieSparrow** [comment]
Actually close this this thread, i can't believe how stupid i am.. %CP would do the perfect job.
