### ISSUE TITLE
spawn_radius ignored on restart

### ISSUE THREAD

**Issue by FrancYescO** [jabbink/PokemonGoBot#1142]
after https://github.com/jabbink/PokemonGoBot/pull/1129

the bot at restart will have the new-last location as starting point this will result in ignoring spawn_radius initially set

PS. i also think that a allow_leave_start_area can be merged in a negative value of spawn_radius

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by AlexBoulyga** [comment]
Yep and i am not sure this is fix-able

**Comment by FrancYescO** [comment]
-on close save lastcords in a new val not rewriting manually input cords
-on start just use lastcords for starting point and the manully input as center of our radius

or, save also time on close, and on restart wait if starting point too faraway (check with speed val) from lastcords
