### ISSUE TITLE
No Pokemon images in Rocket theme GUI

### ISSUE THREAD

**Issue by Taclaa** [jabbink/PokemonGoBot#1143]
**Description:**
No Pokemon images in Rocket theme GUI - I know this has been answered already, nut to be honest I don't understand the fix! :/

**Steps to reproduce:**

1. Run bot
2.Open Rockt theme GUI

**Expected behavior:**
Images show for Pokemon

**Actual behavior:**
No Images for Pokemon

**Version:**
0.6.0 Running Gradlew

**Operating System:**
MAC OS

**Java version:**
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by gise88** [comment]
https://github.com/eruecco87/PokemonGoBot-RocketTheme/issues/19
https://github.com/eruecco87/PokemonGoBot-RocketTheme/issues/21

**Comment by gise88** [comment]
It is an already known issue..

**Comment by Sieberkev** [comment]
This is an issue from an external repository we do not maintain, so we can't fix that :)

**Comment by Taclaa** [comment]
Could we get the images and store them locally?
