### ISSUE TITLE
Running two bots at the same time

### ISSUE THREAD

**Issue by Masculien** [jabbink/PokemonGoBot#1144]
**Description:**
I can't figure out how to run both of my accounts with the .json files in the bot-settings. May somebody tell me where my mistake is.

**Steps to reproduce:**

1. I copied the json-template.json in 2 different text files, changed username, password and ports and saved them in bot-settings.
2.[Error.txt](https://github.com/jabbink/PokemonGoBot/files/422825/Error.txt)

**Expected behavior:**
Run the bot for both accounts 

**Actual behavior:**
Shows an error right after starting the bot

**Version:**
0.6.0

**Operating System:**
OSX

**Java version:**
"1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

This is my .json file may you have a look at it and show me where i made the mistake(s). I

```json
{
  "latitude" : 40.783515,
  "longitude" : -73.964682,
  "saveLocationOnShutdown": true,
  "credentials" : {
    "type" : "ptc",
    "username" : username,
    "password" : password
  },
  "proxyServer" : "",
  "proxyPort" : "",
  "proxyType" : "",
  "proxyUsername" : "",
  "proxyPassword" : "",
  "restApiPassword": "",
  "speed" : 2.8,
  "randomSpeedRange" : 0.0,
  "followStreets" : false,
  "groupItemsByType" : false,
  "dropItems" : true,
  "uselessItems" : {
    "ITEM_REVIVE" : 20,
    "ITEM_MAX_REVIVE" : 10,
    "ITEM_POTION" : 0,
    "ITEM_SUPER_POTION" : 30,
    "ITEM_HYPER_POTION" : 50,
    "ITEM_MAX_POTION" : 50,
    "ITEM_POKE_BALL" : 40,
    "ITEM_GREAT_BALL" : 50,
    "ITEM_ULTRA_BALL" : 50,
    "ITEM_MASTER_BALL" : 10,
    "ITEM_RAZZ_BERRY" : 40,
    "ITEM_LUCKY_EGG" : -1,
    "ITEM_INCENSE_ORDINARY" : -1,
    "ITEM_TROY_DISK" : -1
  },
  "profileUpdateTimer" : 60,
  "timerWalkToStartPokestop" : -1,
  "randomNextPokestopSelection" : 5,
  "campLurePokestop" : -1,
  "desiredCatchProbability" : 0.4,
  "desiredCatchProbabilityUnwanted" : 0.0,
  "autotransfer" : true,
  "randomBallThrows" : false,
  "waitBetweenThrows" : false,
  "keepPokemonAmount" : 1,
  "maxPokemonAmount" : -1,
  "displayKeepalive" : true,
  "displayPokestopName" : false,
  "displayPokestopRewards" : true,
  "displayPokemonCatchRewards" : true,
  "displayIfPokemonFromLure" : true,
  "lootPokestop" : true,
  "catchPokemon" : true,
  "autoFillIncubator" : true,
  "sortByIv" : false,
  "desiredCurveRate" : 0.0,
  "neverUseBerries" : true,
  "allowLeaveStartArea" : false,
  "spawnRadius" : -1,
  "banSpinCount" : 0,
  "transferCpThreshold" : 400,
  "transferCpMinThreshold" : -1,
  "transferIvThreshold" : 80,
  "ignoredPokemon" : [ "EEVEE", "MEWTWO", "CHARMANDER" ],
  "obligatoryTransfer" : [ "DODUO", "RATTATA", "CATERPIE", "PIDGEY" ],
  "evolveBeforeTransfer" : [ "CATERPIE", "RATTATA", "WEEDLE", "PIDGEY" ],
  "evolveStackLimit" : 100,
  "useLuckyEgg" : 1,
  "export" : "",
  "guiPortSocket" : 8001 and 8002,
  "initialMapSize" : 9,
  "waitChance" : 0.0,
  "waitTimeMin" : 0,
  "waitTimeMax" : 0
}```

**Comment by AlexBoulyga** [comment]
You need to use a proxy on the second one

**Comment by Sieberkev** [comment]
Can you post your second.json file? There's a key "username" in a wrong spot according to the errormsg.

**Comment by Masculien** [comment]
can you tell me what i have to fill in for the proxy in the second file

**Comment by Sieberkev** [comment]
Nothing, it's not an IP related problem but a parseproblem with the json files. Ignore the proxy thing.

**Comment by Masculien** [comment]
the second son file is exactly the same as the first one just the other username and port 8002. Do you have a solution for me?

**Comment by MacDogg** [comment]
The error.txt file tells you exactly where to look.
second.json; line: 7, column: 27 and line: 7, column: 5
make sure "username" has the " around it.

"username" : "myusername",
"password" : "mypass"

**Comment by flugel90** [comment]
Try deleting the line:
  "restApiPassword": "",
Don't fill in proxy information you can delete those as well the bot will fix the file if your credentials are fine I think.

**Comment by Masculien** [comment]
ok i was missing the quotation marks and added those and deleted the proxy information too. It helped as far as the error changed to address already in use, you have another issue for this or do you have a solution for me too in this case?

**Comment by MacDogg** [comment]
Try picking a new port for both json files.
"guiPortSocket" : 8011 and 8012

**Comment by Sieberkev** [comment]
> the error changed to address already in use

Kill all running java processes, wait a min, and restart the bot.
Close the bot with `ctrl+c` instead of just closing the window as it mostly keeps the java process running in the background.

Since the original issue is fixed, i'll close this then :)

**Comment by Masculien** [comment]
Thanks to all of you, works now:)
