### ISSUE TITLE
[Suggestion] Pokestop and Pokemon Limit

### ISSUE THREAD

**Issue by CptJackieSparrow** [jabbink/PokemonGoBot#1145]
It'll be so much better that we have pokestop and pokemon catch limit for not being banned.
Simple.
So you don't have to worry about the best config.
Probably Jabbink thought of this, but in case he didn't :smile: 

PS: Being away for a while from servers as i was in my village, didn't know if i can post suggestions under issue section.

**Comment by ansalls** [comment]
#1124

**Comment by AlexBoulyga** [comment]
Implented hard stop of bot in https://github.com/jabbink/PokemonGoBot/pull/1095

**Comment by CptJackieSparrow** [comment]
Thank you guys for your replies.
I'm using bot with 2 m/h ±1 m/h.
But it's damn slow, so i can higher the speed and when the bot reaches 1000 pokestops or pokemons, it stops, this is a feature right now i can use?

**Comment by AlexBoulyga** [comment]
Its a feature waiting to be merged in the mentioned PR. Is ould NOT recommend increasing the speed too much, they ban for that

**Comment by muschter** [comment]
Also #1109

**Comment by CptJackieSparrow** [comment]
Okay i keep it between 4 plus minus 1 which is like 20 kmh.

**Comment by Sieberkev** [comment]
#1095 added optional delays between catching and limits to stop the bot when you reach a certain amount
