### ISSUE TITLE
[Feature Request] Add different route providers

### ISSUE THREAD

**Issue by AlexBoulyga** [jabbink/PokemonGoBot#1146]
**Description:**
I thought about adding different route providers, choosable from settings,
so that if I see one is not working I can try another one.
By this, the load would be divided between multiple providers, increasing the overall speed

I dont know however how much work that is.
I believe @pr0ves  was the one who changed it the last time
What do you think about that?

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by muschter** [comment]
I think this is a good idea, so we aren't stressing one provider too much.

**Comment by mineme45** [comment]
I've made a mapzen route provider.
I will PR it today if everything is ok :)

**Comment by Sieberkev** [comment]
Added with ##1167
