### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by gise88** [jabbink/PokemonGoBot#1147]
**Description:**
If you enter a fully evolved pokemon inside the "evolve_before_transfer" list, the variable `pokemonMeta.candyToEvolve` (https://github.com/jabbink/PokemonGoBot/blob/develop/src/main/kotlin/ink/abb/pogo/scraper/tasks/EvolvePokemon.kt#L32) will be zero..
I know, this is a user error but seems easy to prevent..

**Steps to reproduce:**
Add a latest evolution of a pokemon inside the "evolve_before_transfer" list

**Expected behavior:**
Warn and ignore fully evolved pokemon

**Actual behavior:**
**Stacktrace (If it's a crash):**
17 ago 18:07:43 [default: ProfileLoop] - Error running loop ProfileLoop!
java.lang.ArithmeticException: / by zero
        at ink.abb.pogo.scraper.tasks.EvolvePokemon.run(EvolvePokemon.kt:32)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:262)
        at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:144)
        at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:36)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:204)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:36)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Version:**
https://github.com/jabbink/PokemonGoBot/commit/f9c163e1a481952616b9ef9bb77f694cd2ad15d5

**Operating System:**
Debian 8

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by muschter** [comment]
It's a simple check to see if ```pokemonMeta.candyToEvolve``` is greater than 0, if it isn't set ```maxPossibleEvolves``` to 0

**Comment by gise88** [comment]
I think is better if we check when we load the list and removes all the fully evolved pokemon from it..

**Comment by muschter** [comment]
Good idea, didn't quite read through and understand your steps to reproduce.

**Comment by AlexBoulyga** [comment]
This isnt possible currently @gise88 , or so I believe, as you cant delete anything from the settings object. Furthermore, if there will be new pokemon later on, it would be wise just to add a check if the pokemon can be evolved

**Comment by gise88** [comment]
Oh, ok! Than, what @muschter has said is the our best option! :smiley:

**Comment by AlexBoulyga** [comment]
```
 sorted.forEach {
                    maxPossibleEvolves--
                    if (maxPossibleEvolves < 0) {
                        releasePokemon(it,"Not enough candy to save for evolve",ctx)
                        if(settings.autotransferTimeDelay != (-1).toLong()){
                            val transferWaitTime = settings.autotransferTimeDelay/2 + (Math.random()*settings.autotransferTimeDelay).toLong()
                            Thread.sleep(transferWaitTime)
                        }
                    }
                    // this should do the trick
                    it.evolutionForm.isFullyEvolved........
                    .....
                }
```
I can rewrite you the function however I can not test it.
If you want I could send you the needed changed files @gise88 and you test it?

**Comment by gise88** [comment]
Ok, no problem! If you prefer I can clone your own repo and test it.. =)

**Comment by AlexBoulyga** [comment]
I'll tell you when Im ready. I am not sure it will be today as some guests are coming over soon

**Comment by AlexBoulyga** [comment]
[EvolvePokemon.kt.zip](https://github.com/jabbink/PokemonGoBot/files/423337/EvolvePokemon.kt.zip)
@gise88  try this out, it is the EvolvePokemon.kt file under /src/main/kotlin/ink/abb/pogo/scraper/tasks

**Comment by gise88** [comment]
I was trying it when i get my account banned! 😢 Tomorrow i will try with a new account... Sorry for this late..

**Comment by muschter** [comment]
@gise88 I have submitted a pull request to fix this issue.

**Comment by AlexBoulyga** [comment]
@muschter ok you fixed it the other way but should work too :)
