### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by CptJackieSparrow** [jabbink/PokemonGoBot#1149]
**Description:**
[Short description of the issue observed. If this is feature request you can modify the template as required.]

**Steps to reproduce:**

1. open cmd, cd C:\user\....
2. "gradlew build" or "gradlew clean build"

**Expected behavior:**
Compile

**Actual behavior:**
Build failed

**Stacktrace (If it's a crash):**
http://pastebin.com/gyJv6vh3

**Version:**
v 0.6.0

**Operating System:**
Windows 10

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) Client VM (build 25.101-b13, mixed mode, sharing)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Sieberkev** [comment]
As the errormsg says: You need to install Java 1.8.0 *JDK* (to run from gradle)

JRE is to run from JAR only

**Comment by CptJackieSparrow** [comment]
THANKS A TON, i literally couldn't see that..
