### ISSUE TITLE
Bug - Transferring Pokemon after evolve above desired IV

### ISSUE THREAD

**Issue by DiogoRNeves** [jabbink/PokemonGoBot#1153]
**Description:**
I've set the transfer_iv_threshold=90 and it works as expected when catching Pokémons, but somehow it is not applied after evolving.

**Steps to reproduce:**

1. Stack evolve
2. Check if pokémon above transfer_iv_threshold were transferred 

**Expected behavior:**
Only transfer Pokemon below transfer_iv_threshold, transfer_cp_threshold and transfer_cp_min_threshold

**Actual behavior:**
Transferring pokémon above transfer_iv_threshold

**Stacktrace (If it's a crash):**
17 Aug 18:34:08 [default: ProfileLoop] - Evolving SPEAROW before transfer
17 Aug 18:34:09 [default: ProfileLoop] - Going to transfer FEAROW with CP 834 and IV 93%; reason: Evolved for XP only
17 Aug 18:35:46 [default: ProfileLoop] - Evolving SPEAROW before transfer
17 Aug 18:35:47 [default: ProfileLoop] - Going to transfer FEAROW with CP 24 and IV 93%; reason: Evolved for XP only
17 Aug 18:35:49 [default: ProfileLoop] - Evolving GOLDEEN before transfer
17 Aug 18:35:50 [default: ProfileLoop] - Going to transfer SEAKING with CP 744 and IV 91%; reason: Evolved for XP only
17 Aug 18:37:25 [default: ProfileLoop] - Evolving STARYU before transfer
17 Aug 18:37:26 [default: ProfileLoop] - Going to transfer STARMIE with CP 1110 and IV 93%; reason: Evolved for XP only

**Version:**
0.6.0

**Operating System:**
Mac OS X

**Java version:**
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by FrancYescO** [comment]
the var is named evolve_**before_transfer** so i assume its a stupid but expected behaviour.

Commenting
https://github.com/jabbink/PokemonGoBot/blob/develop/src/main/kotlin/ink/abb/pogo/scraper/tasks/EvolvePokemon.kt#L77

could be enought for a fast fix (the bad iv/cp pokemons will be transfered on the next trasfer check/loop) just waiting why @svombergen done this

**Comment by DiogoRNeves** [comment]
I get what you are saying, but I think that all transfers should have the same criteria...
