### ISSUE TITLE
[ Stop PokemonGoBot] How to stop pokemongobot on my PC/Windown 7?

### ISSUE THREAD

**Issue by softdevelop** [jabbink/PokemonGoBot#1161]
**Description:**
I can't stop top pokemongobot on my PC/Windown 7

**Steps to reproduce:**

1.  I can run an it work well 
2.  I want to stop it but I can't 

**Expected behavior:**
 There is should be an option to stop it on http://ui.pogobot.club/RocketTheme/

**Actual behavior:**
There is no option to stop it on http://ui.pogobot.club/RocketTheme/ and on also on commandline

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
Pokemon Go Bot v0.6.0

**Operating System:**
[ Windown 7 64bit]

**Java version:**
 8.0.1 update today at 08/18/2016`

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Sieberkev** [comment]
You press `ctrl+c` in the console window to close it down, then you can safely close the window.

**Comment by patzor** [comment]
i think the UI is for monitoring only..

**Comment by Sieberkev** [comment]
Indeed, the current UI's are only reading the socket server (which spams information from the bot to your browser).

There is a new REST API which can do that, but afaik there are currently no UI's who support that already, but those are not in the scope of this repository.

**Comment by softdevelop** [comment]
How to stop it if I closy the window ( commandline )  without ctrl+c ?

**Comment by Sieberkev** [comment]
Then you have to kill the JAVA process by going to the task manager, select it and terminate the process.

**Comment by softdevelop** [comment]
Thanks again! :+1:
