### ISSUE TITLE
Bot wont work after running for a while

### ISSUE THREAD

**Issue by icyeti** [jabbink/PokemonGoBot#1163]
**Description:**
My pokemon go bot is not working
**Steps to reproduce:**
I turn on the pokemon go bot and it works for a while but I dont know what screws it up.
**Expected behavior:**
It should keep running fine.
**Actual behavior:**
18 Aug 00:24:05 [default: ProfileLoop] - Accepting rewards for level 25; Rewards: [25x ITEM_ULTRA_BALL, 20x ITEM_MAX_POTION, 15x ITEM_REVIVE, 15x ITEM_RAZZ_BERRY, 1x ITEM_INCENSE_ORDINARY, 1x ITEM_LUCKY_EGG, 1x ITEM_INCUBATOR_BASIC, 1x ITEM_TROY_DISK]; Unlocks: [ITEM_MAX_POTION]
18 Aug 00:24:06 [default: ProfileLoop] - Profile update: 710166 XP on LVL 25; 166/190000 (0.09%) to LVL 26
18 Aug 00:24:06 [default: ProfileLoop] - XP gain: 18,835 XP in 19 mins; XP rate: 59,460/hr; Next level in: 3.19 hr
18 Aug 00:24:06 [default: ProfileLoop] - Pokemon caught/transferred: 52/50; Pokemon caught from lures: 27; Items caught/dropped: 120/44;
18 Aug 00:24:06 [default: ProfileLoop] - Pokebank 247/250; Stardust 148638; Inventory 305/350
18 Aug 00:24:07 [default: BotLoop] - Getting map of (34.01669415635828, -118.49506578086162)
18 Aug 00:24:07 [default: ProfileLoop] - Error running loop ProfileLoop!
18 Aug 00:24:08 [default: BotLoop] - Dropped 15x ITEM_REVIVE
18 Aug 00:24:08 [default: BotLoop] - Dropped 25x ITEM_ULTRA_BALL
18 Aug 00:24:09 [default: BotLoop] - Dropped 15x ITEM_RAZZ_BERRY
18 Aug 00:24:12 [default: BotLoop] - Getting map of (34.01665374990501, -118.4951903818946)
18 Aug 00:24:17 [default: BotLoop] - Getting map of (34.01653567834971, -118.49526161599552)
18 Aug 01:24:16 [default: BotLoop] - Getting map of (34.01651346021893, -118.49532231108189)
18 Aug 01:24:21 [default: BotLoop] - Getting map of (34.016416920136336, -118.49546124311476)
18 Aug 01:24:27 [default: BotLoop] - Getting map of (34.01633234384677, -118.49556769670664)
18 Aug 01:24:32 [default: BotLoop] - Getting map of (34.01623406923042, -118.49564936509752)
18 Aug 01:24:37 [default: BotLoop] - Getting map of (34.016193954811065, -118.49576102515631)
18 Aug 01:24:40 [default: ProfileLoop] - Error running loop ProfileLoop!
18 Aug 01:24:40 [default: PokestopLoop] - Looting nearby pokestop 4f0187581d554c23843277159beaced2.16
18 Aug 01:24:41 [default: PokestopLoop] - Looting nearby pokestop 4f0187581d554c23843277159beaced2.16
18 Aug 01:24:42 [default: BotLoop] - Getting map of (34.016123974681506, -118.49584514491768)
18 Aug 01:24:46 [default: PokestopLoop] - Looting nearby pokestop 4f0187581d554c23843277159beaced2.16
18 Aug 01:24:47 [default: BotLoop] - Getting map of (34.015979739101, -118.49598076864278)
18 Aug 01:24:47 [default: PokestopLoop] - Looting nearby pokestop 4f0187581d554c23843277159beaced2.16
18 Aug 01:24:47 [default: PokestopLoop] - Looting nearby pokestop 4f0187581d554c23843277159beaced2.16
18 Aug 01:24:48 [default: PokestopLoop] - Looting nearby pokestop 4f0187581d554c23843277159beaced2.16
18 Aug 01:24:49 [default: PokestopLoop] - Looting nearby pokestop 4f0187581d554c23843277159beaced2.16
18 Aug 01:24:50 [default: PokestopLoop] - Looting nearby pokestop 4f0187581d554c23843277159beaced2.16
18 Aug 01:24:50 [default: PokestopLoop] - Looting nearby pokestop 4f0187581d554c23843277159beaced2.16
18 Aug 01:24:51 [default: PokestopLoop] - Looting nearby pokestop 4f0187581d554c23843277159beaced2.16
18 Aug 01:24:51 [default: PokestopLoop] - Looting nearby pokestop 4f0187581d554c23843277159beaced2.16
18 Aug 01:24:52 [default: BotLoop] - Getting map of (34.01603460217385, 
And So on...

**Version:**
1.6.0

Mac OS 10.11.5

**Java version:**
1.8.0_45

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by MacDogg** [comment]
I got that yesterday on a botting account.  I quit and bot and restarted it and the account was banned.

**Comment by icyeti** [comment]
Hmm Idk Im not banned.

**Comment by Sieberkev** [comment]
https://github.com/jabbink/PokemonGoBot/blob/develop/FAQ.md#the-bot-doesnt-findloot-pokestops
