### ISSUE TITLE
Error writing export

### ISSUE THREAD

**Issue by MacDogg** [jabbink/PokemonGoBot#1168]
**Description:**
Error writing export: List is empty.

**Steps to reproduce:**
1. See log file below.  Start bot, sometimes it writes the CSV, sometimes it throws an error.  Bot is running the entire time all these logs are being recorded.

**Expected behavior:**
Should get a profile update every 60 seconds as setup in the config.properties
profile_update_timer=60
export=CSV

**Actual behavior:**
Sometimes it works sometimes if doesn't.

**Log**
18 Aug 16:48:45 [default] - Logging in to game server...
18 Aug 16:48:48 [default] - Logged in successfully
18 Aug 16:48:50 [default] - Name: PokemonGoBotPwnsYou
18 Aug 16:48:50 [default] - Team: NEUTRAL
18 Aug 16:48:50 [default] - Pokecoin: 85120
18 Aug 16:48:50 [default] - Stardust: 397400
18 Aug 16:48:50 [default] - Level 8, Experience 28565
18 Aug 16:48:50 [default] - Pokebank 9/250
18 Aug 16:48:50 [default] - Inventory 100/350
18 Aug 16:48:50 [default] - Error writing export: List is empty.
18 Aug 16:48:58 [default: ProfileLoop] - Error writing export: List is empty.
18 Aug 16:49:56 [default: ProfileLoop] - Failed to update profile and inventories
18 Aug 16:49:57 [default: ProfileLoop] - Wrote export export_default.csv.
18 Aug 16:50:56 [default: ProfileLoop] - Failed to update profile and inventories
18 Aug 16:50:56 [default: ProfileLoop] - Error writing export: List is empty.
18 Aug 16:52:56 [default: ProfileLoop] - Pokebank 12/250; Stardust 397400; Inventory 110/350
18 Aug 16:52:57 [default: ProfileLoop] - Wrote export export_default.csv.
18 Aug 16:53:58 [default: ProfileLoop] - Pokebank 9/250; Stardust 397900; Inventory 110/350
18 Aug 16:53:59 [default: ProfileLoop] - Error writing export: List is empty.
18 Aug 16:54:57 [default: ProfileLoop] - Pokebank 9/250; Stardust 398500; Inventory 115/350
18 Aug 16:54:58 [default: ProfileLoop] - Error writing export: List is empty.
18 Aug 16:55:56 [default: ProfileLoop] - Pokebank 9/250; Stardust 399800; Inventory 123/350
18 Aug 16:55:57 [default: ProfileLoop] - Error writing export: List is empty.
18 Aug 16:56:56 [default: ProfileLoop] - Pokebank 9/250; Stardust 401100; Inventory 127/350
18 Aug 16:56:57 [default: ProfileLoop] - Error writing export: List is empty.
18 Aug 16:57:56 [default: ProfileLoop] - Pokebank 9/250; Stardust 405200; Inventory 129/350
18 Aug 16:57:57 [default: ProfileLoop] - Error writing export: List is empty.
18 Aug 16:58:56 [default: BotLoop] - Error running loop BotLoop!
18 Aug 16:58:56 [default: ProfileLoop] - Error writing export: List is empty.
18 Aug 17:01:57 [default: ProfileLoop] - Pokebank 10/250; Stardust 409400; Inventory 133/350
18 Aug 17:01:59 [default: ProfileLoop] - Wrote export export_default.csv.
18 Aug 17:02:56 [default: ProfileLoop] - Failed to update profile and inventories
18 Aug 17:02:57 [default: ProfileLoop] - Wrote export export_default.csv.

**Version:**
0.6.0

**Operating System:**
Win10 Ult 64-bit

**Java version:**
build 1.8.0_101-b13

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Sieberkev** [comment]
Is it possible you had no eggs at all when having this message (you can check with one of the GUI's)?
