### ISSUE TITLE
gradle build failed

### ISSUE THREAD

**Issue by kalijason** [jabbink/PokemonGoBot#1177]
**Description:**
failed on gradle build
```
A problem occurred evaluating root project 'PokemonGoBot'.
> Could not resolve all dependencies for configuration ':compile'.
   > Could not find com.github.Grover-c13:PokeGOAPI-Java:Development-SNAPSHOT.
     Required by:
         ink.abb:PokemonGoBot:0.6.0
```
**Steps to reproduce:**

1. ```gradle build```

**Version:**
b24584b35971f0fae2afe4fd753d5cde4ab2258f

**Operating System:**
Ubuntu 12

**Java version:**
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by DiogoRNeves** [comment]
Same.

**Operating System:**
Mac OS X

**Java version:**
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by DiogoRNeves** [comment]
So, dirty fix:
- open grade.build
- replace the text it complains about with
compile 'com.github.Grover-c13:PokeGOAPI-Java:2188b13bdfa6de286fd2ad9577eaaa3519c372cf'

wich is the latest commit on the API at the moment. I have no ideia why it stopped working for Development-SNAPSHOT though...

**Comment by Sieberkev** [comment]
I've seen a working import this noon, is this fixed with you guys?

**Comment by kalijason** [comment]
yes it works now
