### ISSUE TITLE
closing the bot while pokebank full will cause the bot to not catch anymore

### ISSUE THREAD

**Issue by FrancYescO** [jabbink/PokemonGoBot#1183]
**Description:**
closing the bot while pokebank full will cause the bot to not catch anymore
something is putting the "catchPokemon" : false in the settings file

**Steps to reproduce:**
1. fillup pokebank
2. close bot
**Version:**
https://github.com/jabbink/PokemonGoBot/commit/600a897468f6d6e676b41924c698e1401f348e1a
**Operating System:**
W10x64

**Java version:**
1.8.0_101

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Peyphour** [comment]
Yes this is a normal behaviour,
When the pokebank is full, the setting catchPokemon is set to false, when a pokemon is transfered the setting is reset to hit previous value.
If you close the bot, the current settings are saved

**Comment by FrancYescO** [comment]
> when a pokemon is transfered the setting is reset to hit previous value
not if when you start the bot have "catchPokemon" : false

so this is an issue... we need to not rewrite the user preference

**Comment by Peyphour** [comment]
No no, the user setting is preserved, the catchPokemon setting is reset to the initial value of the config file

**Comment by FrancYescO** [comment]
-run the bot with "catchPokemon" : true
-pokebank fillup so but set "catchPokemon" : false
-i close the bot while running, BEFORE it transfer something
-"catchPokemon" : false will be saved to file

user setting fucked up at the next start :P

**Comment by Peyphour** [comment]
Yes but still it is expected behavior.
There's no clean way to solve this I think

**Comment by FrancYescO** [comment]
just not rewrite the settings value... store it runtime, at next start will be set again to false the runtime value if pokebank full

**Comment by Pepejson** [comment]
The same thing happening to me and autotransfer also stopped working, even I changed autotransfer settings and when pokebank is full it doesn't transfer even a single pokemon and I'm stuck as I'm testing some possible method to avoid ban I can not login even once to my account on phone.

**Comment by FrancYescO** [comment]
@Pepejson probably no more bag fillup no more with this https://github.com/jabbink/PokemonGoBot/pull/1188

but this issue still need to be fixed

**Comment by jabbink** [comment]
>There's no clean way to solve this I think

Afaik we store the real value somewhere, just reset it in the shutdown hook.

**Comment by FrancYescO** [comment]
@jabbink nope, no reset was done on shutdown, take a look at my PR ^^^
