### ISSUE TITLE
[request] Muti acc - auto change acc

### ISSUE THREAD

**Issue by chudungg** [jabbink/PokemonGoBot#1184]
all we know now niantic have the limited 1000pokemon and 2000pokestop in 24h
So can we have the muti acc.
Its like when the first acc reach the limit, the pokemongobot auto change to the second acc...
So we can run the pokemonGoBot all day without ban.

Just my opinion

**Comment by alone23** [comment]
They are banning just for use fakegps, I don't know if use bot is safe

**Comment by EpicAwesomeWolf** [comment]
@alone23 The bot is safe as long as you don't travel too fast/teleport.

**Comment by chudungg** [comment]
i find my solution to use apple script to run in a queue up 5acc... so i close this theard. Tks
