### ISSUE TITLE
Can't compile commit versions

### ISSUE THREAD

**Issue by Casper2b** [jabbink/PokemonGoBot#1187]
**Description:**
I try to compile the new version following the description but I can't pass Step 3

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]
3. [Step 3] ----> Stuck

**Actual behavior:**
[What actually happens]

**Stacktrace (If it's a crash):**
MacBook-Pro-de-Francois-2:~ Francois$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
MacBook-Pro-de-Francois-2:~ Francois$ git clone https://github.com/jabbink/PokemonGoBot.git && cd PokemonGoBot
Cloning into 'PokemonGoBot'...
remote: Counting objects: 3948, done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 3948 (delta 21), reused 0 (delta 0), pack-reused 3860
Receiving objects: 100% (3948/3948), 4.32 MiB | 935.00 KiB/s, done.
Resolving deltas: 100% (1417/1417), done.
Checking connectivity... done.
MacBook-Pro-de-Francois-2:PokemonGoBot Francois$ gradlew build
-bash: gradlew: command not found

**Version:**
Commit: 088869c

**Operating System:**
OS X El Capitan 10.11.6

**Java version:**
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Sieberkev** [comment]
Try `./gradlew build`

**Comment by Casper2b** [comment]
Thank you!
