### ISSUE TITLE
[SUGGESTION]enlarge the searching area

### ISSUE THREAD

**Issue by elliottfeng** [jabbink/PokemonGoBot#119]
Is it possible?

**Comment by jabbink** [comment]
Would require a rewrite of quite some stuff.

You probably want to achieve something with the bot what it wasn't made for: set location to a city and there should be 1k+ pokestops within the radius.

**Comment by elliottfeng** [comment]
Thanks a lot for replying. By the way, will you release a new jar today?

**Comment by wartickler** [comment]
Yeah that would be a dangerous implementation. Red flags all over the place.

**Comment by jabbink** [comment]
with the web ui you can walk further away (manually for now). Make sure to set `allow_leave_start_area=true`

**Comment by jabbink** [comment]
I'll close this for now. IMO the bot should start in a very populated area and using the UI it allows you to leave it. Should work for most, I guess.
