### ISSUE TITLE
Problem on start  follow_streets value

### ISSUE THREAD

**Issue by Jacopo1891** [jabbink/PokemonGoBot#1198]
I can't undestand why on start i have this problem.
Steps to reproduce:

[Step 1]gradle run
Expected behavior: Starting bot

Actual behavior: it stop at 83%

Stacktrace (If it's a crash): 
> Exception in thread "default" com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_TRUE token
>  at [Source: /home/jacopo/PokemonGoBot/./bot-settings/default.json; line: 18, column: 21] (through reference chain: ink.abb.pogo.scraper.Settings["followStreets"])
> 	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:261)
> 	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1233)
> 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1121)
> 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1074)
> 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:328)
> 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
> 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
> 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
> 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:396)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1194)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
> 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
> 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2731)
> 	at ink.abb.pogo.scraper.services.BotService.load(BotService.kt:69)
> 	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:85)
> 	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:67)
> 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
> > Building 83% > :run

Version:Last

Operating System: Ubuntu

Java version: java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
###
I've try to set follow_streets=false; follow_streets=true; follow_streets=GOOGLE.
But do not work.
Any suggest?

**Comment by jabbink** [comment]
Hi @Jacopo1891,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-23 14:35) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by Sieberkev** [comment]
[FAQ](https://github.com/jabbink/PokemonGoBot/blob/develop/FAQ.md#i-get-jsonmappingexception-can-not-deserialize-instance-of-javautilarraylist-out-of-value_false-token)
