### ISSUE TITLE
Web GUI not working?

### ISSUE THREAD

**Issue by EpicAwesomeWolf** [jabbink/PokemonGoBot#1200]
**Description:**
Images on the GUI (all of them) do not load.

**Expected behavior:**
Caught Pokemon should be showing on map + Pokebank

**Actual behavior:**
Only showing names of Pokemon in the bank.

**Version:**
v0.60

**Operating System:**
Mac OS X

**Java version:**
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Sieberkev** [comment]
In the [original GUI](http://ui.pogobot.club/0.5.0-alpha4/map.html) it should work, the other 2 are external repositories so we can not fix those.

**Comment by EpicAwesomeWolf** [comment]
Let me try the original.

**Comment by EpicAwesomeWolf** [comment]
Yep, sure enough it's showing. I thought you guys owned RocketTheme, but I guess I was horribly mistaken.
