### ISSUE TITLE
Multiple Issues Suddenly Started

### ISSUE THREAD

**Issue by MacDogg** [jabbink/PokemonGoBot#1208]
**Description:**
Multiple issues started happening over the last few days, including eggs not being hatched (see screen shot), profile exports one time when the bot starts and never again and loop errors.
Wondering if something is wrong with my setup but my config.properties is right.  I have to login via BlueStacks to hatch the egg and accept the level up rewards and any badges.
This is a brand new Trainer that I started on Thursday (I think).  If you need the entire config file let me know and I can add it.
auto_fill_incubator=true
profile_update_timer=60
export=CSV

![capture](https://cloud.githubusercontent.com/assets/20782190/17842544/993be476-67e9-11e6-9d3e-765b339f6f12.JPG)

**Steps to reproduce:**
1. Just run the bot and check the log file.  Errors seem to occur every 60 seconds.  It's so bad I have to scroll up a page at a time just to see what recently happened (caught pokemons, looted stops, transfers, drops).
I included the text from command prompt.
[command_text.txt](https://github.com/jabbink/PokemonGoBot/files/429290/command_text.txt)

**Expected behavior:**
No errors like it was a week ago.

**Actual behavior:**
Here are some errors from bot.log:
21 Aug 13:01:07 [main] - Starting MainKt on  with PID 216096 (C:\...)
21 Aug 13:01:07 [main] - Running with Spring Boot v1.3.6.RELEASE, Spring v4.2.7.RELEASE
21 Aug 13:01:07 [main] - No active profile set, falling back to default profiles: default
21 Aug 13:01:19 [main] - UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
21 Aug 13:01:19 [main] - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
21 Aug 13:01:24 [main] - Started MainKt in 17.616 seconds (JVM running for 20.264)
21 Aug 21:06:32 [default: ProfileLoop] - Error running loop ProfileLoop!
21 Aug 21:07:32 [default: ProfileLoop] - Error running loop ProfileLoop!
21 Aug 21:08:32 [default: ProfileLoop] - Error running loop ProfileLoop!
21 Aug 21:30:32 [default: ProfileLoop] - Error running loop ProfileLoop!
21 Aug 21:30:32 [default: BotLoop] - Error running loop BotLoop!
21 Aug 21:33:34 [default: ProfileLoop] - Error running loop ProfileLoop!
21 Aug 21:34:32 [default: ProfileLoop] - Error running loop ProfileLoop!
21 Aug 21:35:33 [default: ProfileLoop] - Error running loop ProfileLoop!
21 Aug 21:36:32 [default: ProfileLoop] - Error running loop ProfileLoop!
21 Aug 21:37:32 [default: ProfileLoop] - Error running loop ProfileLoop!

**Version:**
0.6.0
I even deleted the JAR I had on my computer and downloaded a new one just in case it became corrupt.

**Operating System:**
Win10 Ult 64-bit

**Java version:**
build 1.8.0_101-b13

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Sieberkev** [comment]
In your command_text file I see a lot of [InvalidProtocolBufferException: Contents of buffer are null](https://github.com/jabbink/PokemonGoBot/blob/develop/FAQ.md#i-get-an-invalidprotocolbufferexception-contents-of-buffer-are-null).

**Comment by MacDogg** [comment]
@FrancYescO I don't know what a stacktrace is or how to get that.  The bot continues to run so I didn't consider it a crash.
@Sieberkev I don't know what that error means.  Is there something I need to fix or change?

**Comment by FrancYescO** [comment]
nvm command_text.txt was enough .. is what @Sieberkev said, some sort of bad comunication with you and server.

**Comment by Sieberkev** [comment]
At this very moment I would not mass evolve with lucky egg (a botloop error at the start of the evolving would suck quite hard), but all the other things should not have any problems.

**Comment by MacDogg** [comment]
mass evolves don't work anyway so no issues there. :-/
Hopefully an update is coming out soon and some of these features get worked out.
I have turned off a lot of the informational options in the config but these errors continue.
