### ISSUE TITLE
Fulfil both conditions

### ISSUE THREAD

**Issue by beaubeire** [jabbink/PokemonGoBot#1211]
**Description:**

At this moment a pokemon only need to have on of these factors, but is there a possiblity they need to have both conditions? See picture.

![knipsel](https://cloud.githubusercontent.com/assets/17483284/17857436/02f0a21a-6882-11e6-8844-e982aaa9444d.JPG)

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]

**Expected behavior:**
[What should happen?]

**Actual behavior:**
[What actually happens]

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
[The version of the bot you used; when self-compiled: :exclamation: the commit hash :exclamation:]

**Operating System:**
[Your operating system]

**Java version:**
[Full output of `java -version`]

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by MacDogg** [comment]
This should be easy to test.  Use low numbers to make sure you get a good test quickly.  You'll need to watch the log file to see what happens.  
I have mine set to only keep Pokemon with IV higher than 90% so I assume I have it setup correctly:
```
transfer_iv_threshold=90
transfer_cp_threshold=-1
```
I see this in the log:
`Going to transfer POKEMON with CP 383 and IV 51%; reason: CP < -1 and IV < 90%`


The test entries will look like this if you want to try it:

```
transfer_iv_threshold=-1
transfer_cp_threshold=100
```
^^This should keep any Pokemon over 100 CP and transfer the rest.^^
```
transfer_iv_threshold=50
transfer_cp_threshold=-1
```
^^This should keep any Pokemon over 50 IV and transfer the rest.^^

**Comment by Rofii** [comment]
This was already suggested a few times. Some people want it changed and some people want it left the way it is.

My suggestion would be a setting called something like keep_conditions_required=[1-3]

**Comment by jabbink** [comment]
Default behavior is both. Some issues want it changed to or.

Closing.
