### ISSUE TITLE
no finding pokestops

### ISSUE THREAD

**Issue by Banginpadr** [jabbink/PokemonGoBot#1227]
**Expected behavior:**
[find pokestop]

**Actual behavior:**
[is not finding pokestops and just after some minutes it even stop catching pokemons]

**Stacktrace (If it's a crash):**
 [default: PokestopLoop] - Pokestop out of range; distance: 12.765737220930951
 [default: PokestopLoop] - Looting nearby pokestop fd03a8b6431a4009a6ce77df74f1f6ea.16
 [default: PokestopLoop] - Pokestop out of range; distance: 12.765737220930951
 -----it keep posting these errors but i havent change anything in my settings--]

**Version:**
[lastest version since i keep deleting it and getting it using wget]

**Operating System:**
[kali linux 2.0]

**Java version:**
[openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-8u102-b14.1-2-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)
]

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Freek3** [comment]
See #1029 👍

**Comment by prickobello** [comment]
Try changing IP (VPN), works for me

**Comment by EpicAwesomeWolf** [comment]
Someone said that restarting router helped.

**Comment by Sieberkev** [comment]
> Version:
[lastest version since i keep deleting it and getting it using wget]

Do you redownload the 0.6.0 release version (which never changes), or the latest development code (which works with git/gradlew)?

Try to get the development version installed (see USAGE.md on how), and configure with follow_streets=MAPZEN,MOBROUTING,PROJECTOSM,YOURNAVIGATION

**Comment by Banginpadr** [comment]
ok i will try that thank  you guys

**Comment by Banginpadr** [comment]
now it is working i didnt even have to fix anything
