### ISSUE TITLE
Captcha in game

### ISSUE THREAD

**Issue by gise88** [jabbink/PokemonGoBot#1232]
**Description:**
It seems that PokemonGo is planning to insert captcha in the game:
http://pokemongohub.net/captcha-game-pokemon-go-bots-trackers/

Do you guys know some way to work around this problem? For instance, come to my mind to send all images on telegram (so create a [telegram bot](https://core.telegram.org/bots) that sends the captcha images) and manually choose the correct ones.. 
Don't know! 

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by JoeyyT** [comment]
Well that looks like a bot destroyer.. :(

**Comment by smileytechguy** [comment]
That sucks

**Comment by FrancYescO** [comment]
2captcha support needed.

**Comment by nokingah** [comment]
2captcha and new release :smile:

**Comment by KyleBoyer** [comment]
2captcha is definitely the way to go. They not only are relatively cheap, but also users can enter captchas to earn money, in addition to paying in - thus is saves users money(so they can plow through some captchas) for use when the in game ones appear.

**Comment by gabrielklein** [comment]
You can always open the android application, simulate the user clicking on the captcha.
I don't think it's the end of bots... it more a new generation of bots coming :)

**Comment by MacDogg** [comment]
I remember a long time ago I was doing this for something else, my mind forgot what, though.
I would sit at home watching TV before bed and captchas would pop up on the computer and I would fill them in and get 'points'.  I could use those points when I played a game that had captchas and they would auto fill for me.  :) :)

**Comment by alone23** [comment]
new account 3 days ago, lvl 23, no softban or permban. Works fine

**Comment by gligi** [comment]
it uses google captcha which is not so easy to bypass.. but hope for the best

**Comment by alone23** [comment]
continue works fine, lvl 26, no softban or permban

**Comment by FrancYescO** [comment]
@alone23 they have just not clicked the big "ban all flagged account" button since ~1 week

**Comment by gabrielklein** [comment]
They are still unbanning the 99% of false positives :) and discovered that having less users is bad for their market valuation!

**Comment by MrBull** [comment]
@alone23: Would you mind sharing your bot parameters here? for example, walking speed, catch possibility, xp per hr, xp per day, and anything else that helps you not get banned

**Comment by alone23** [comment]
sure

[config.properties.txt](https://github.com/jabbink/PokemonGoBot/files/445128/config.properties.txt)

Running bot 4-5h every day, same zone (my city). I always start in different coords in same area.

Running in mac with proxy, ip from my country (Spain).

Sometimes set direction with UI.

Tutorial with iPhone and choose team (red) with iPhone too.


I hope this is helpful

**Comment by FrancYescO** [comment]
100% accuracy + ever curve
~20h running a day
no delay between transfer/evolve
50km/h
no follow street

working flawlessy from 23/08 :) it's a non-banning week.

**Comment by MrBull** [comment]
@alone23 : It seems you are using newer version of the config.properties file. Is it v0.6.0 or a dev version? I use v0.60 and do not have some features e.g. loading saved location. Thank you for sharing by the way.
@FrancYescO : Thanks for the information. Hope you have a great botting week !

**Comment by alone23** [comment]
@MrBull I'm using dev branch

**Comment by MrBull** [comment]
@alone23 : I just got it running. It is working great ! Thanks

**Comment by Sieberkev** [comment]
Atm there's still no captcha's in the official game, we'll look at it once (or even IF) they are activated!
