### ISSUE TITLE
Got 0 pokestops / out of range

### ISSUE THREAD

**Issue by prickobello** [jabbink/PokemonGoBot#1235]
**Description:**
First the bot wouldn't find any pokestops after logging in.

Thanks to a suggestion in earlier issue (#1227) I was able to fix that, by editing config.json to:
`follow_streets=MAPZEN, MOBROUTING, PROJECTOSM, YOURNAVIGATION`

After running for about 3 minutes normally, it now says:

[default: PokestopLoop] - Looting nearby pokestop e3117e097a89428dbf7cc7b786f4b847.16
[default: PokestopLoop] - Pokestop out of range; distance: 32.27141875674663

**Expected behavior:**
Loot pokestop

**Actual behavior:**
Pokestop out of range; distance: ....

**Stacktrace (If it's a crash):**
No crash.

**Version:**
9c10786

**Operating System:**
Mac OS X 10.11.6

**Java version:**
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by prickobello** [comment]
So I guess I am asking how to throttle the request that I send to the server/api

**Comment by Sieberkev** [comment]
If that fixed your issue, please close :)

**Comment by prickobello** [comment]
Do you have an idea how to throttle requests, so maybe more accounts can run? :)

**Comment by Sieberkev** [comment]
The most recent development branch has a PR merged that adds a lot of delays in actions. But Niantic has some strange checks on clients/ip, I've seen people getting banned with only 2 bots on the same IP.

**Comment by prickobello** [comment]
Alright, that delay is probably the reason why its working again! I've noticed the terminal slowing down a bit too, nice job!

Niantics banwave is just insane

**Comment by gligi** [comment]
Dont think its insane, they probably can easily detect botting account. Collateral damage inclusive:)

**Comment by prickobello** [comment]
That's true, and I'm fine with that

I was just talking about them banning everything that comes close to looking like a bot. 
Like real players just playing a lot... That is insane
