### ISSUE TITLE
ToS (+Complete Tutorial)

### ISSUE THREAD

**Issue by nesttle** [jabbink/PokemonGoBot#1236]
**Description:**
Fresh made account.
First login on bot: `Your account may be banned! please try from the official client.`
After login from mobile: ToS popup appears. Without accepting, we can leave from the app and run Jabbink's Pogo Bot. Now bot is working.

**Steps to reproduce:**

1. Create a new PTC account.
2. Start bot. Fail (=`Your account may be banned! please try from the official client.`)
3. Login from mobile/official client. ToS appear. Don't accept and close app (https://dl2.pushbulletusercontent.com/rDaGHU8fLKW2ZnHYRnkWDUJlPcM8tCJJ/Screenshot_2016-08-25-01-31-20.png)
4. Start bot again. Working.

**Expected behavior:**
1. Accept ToS from bot (before this was working for me).
2. Complete first tutorial.
3. Set screen/in-game nickname and/or team and or/ catch first pokemon.

**Actual behavior:**
1. ToS accepting fail. I get a `Your account may be banned! please try from the official client.` message.
2. Tutorial not done.

**Version:**
0.6.0 compiled (/releases/).

**Operating System:**
Win7 x64

**Java version:**

> java version "1.8.0_45"
> Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
> Java HotSpot(TM) Client VM (build 25.45-b02, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Sieberkev** [comment]
There was like the exact same issue #1234 right on top of the tracker >_>

**Comment by nesttle** [comment]
Not the same at all!
This issue is with ToS, not with tutorial at all 👍

**Comment by Sieberkev** [comment]
I asked jabbink this afternoon, looks like the original API changed some stuff and broke it.

Tested it with the brand new API #1237 and this works again (ToS, nickname, first pokemon, ... the whole shebang).

**Comment by nesttle** [comment]
Thanks @Sieberkev, I tested the newAPI and working OK (no more stucks on after login).

Thanks! 💃 💃
