### ISSUE TITLE
[NEWAPI] Pokestop out of range after ~15min

### ISSUE THREAD

**Issue by FrancYescO** [jabbink/PokemonGoBot#1253]
![](https://camo.githubusercontent.com/501abdf00c27f7f7b5d25897676c7fd61060a8db/687474703a2f2f692e696d6775722e636f6d2f344471427878512e706e67)

Trying to blacklist the pokestop (#1242) will not help

![](https://camo.githubusercontent.com/4e3677038aa3cceb7ba8067768e2c75ce50b3003/687474703a2f2f692e696d6775722e636f6d2f5074596c6c7a612e706e67)

a restart of the bot fix this.

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by nilesuan** [comment]
[bot.log.txt](https://github.com/jabbink/PokemonGoBot/files/447996/bot.log.txt)
+1 log

**Comment by FrancYescO** [comment]
Just got the pokestop out of range loop for the First time with the develop branch (so old api) after few hours of running... But here a restart. not helped, actually after 30min still say "0 pokestop found", and is not an ipban cuz the other account running in the same process is still working neither got the pokestop out of range loop.

So this seems like a softban, but why the old api allow to use it for a lot more than 15min? Why a relogin is enough for the new api?

Weird.

**Comment by jabbink** [comment]
When using old API: You looted more than 2000 pokestops?

This is probably related to some token timing out and not refreshing correctly :/

**Comment by FrancYescO** [comment]
unfortunately without a total looted pokestop counter (restarted various time during the day..) cannot be sure of that ... but yes after a full day of test the 2k looted pokestop can be the culprit with the old api

**Comment by FrancYescO** [comment]
Another test done with the old api... putted high speed (to try reaching fast the pokestop limit) after ~2h it started saying pokestop out of range, also after a relogin, another account still working good on the same ip.

more Weird.

**Comment by jabbink** [comment]
Still relevant?

**Comment by FrancYescO** [comment]
Nope was solved with https://github.com/jabbink/PokemonGoAPI/issues/5
