### ISSUE TITLE
 [NEWAPI] Crash equipping badges

### ISSUE THREAD

**Issue by FrancYescO** [jabbink/PokemonGoBot#1254]
Crash equipping badges

![](https://cloud.githubusercontent.com/assets/6855163/18096916/257808c2-6edc-11e6-801b-7208be522894.png)

![](http://i.imgur.com/hqCXmzc.png)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by jabbink** [comment]
I would almost think that this is related to badge requests with another request in the same envelope. Unfortunately it now only logs the first malfunctioning payload, and not possible all others...

**Comment by nilesuan** [comment]
![screen shot 2016-09-01 at 2 36 35 am](https://cloud.githubusercontent.com/assets/4256888/18141658/f5a799fc-6fec-11e6-9d08-df1211eed83d.png)

I noticed after getting the badge error, 5 mins in and I haven't encountered anymore pokemon, and that's in central park where there's a lure mod 24/7

**Comment by jabbink** [comment]
Sometimes still happens because niantics servers are shit; It should auto-resume after it encounters this without breaking. Please reopen if this is not the case
