### ISSUE TITLE
Follow Streets, Which googleApiKey?

### ISSUE THREAD

**Issue by chongivan** [jabbink/PokemonGoBot#1259]
**Description:**
I cannot get the follow streets function to work

**Steps to reproduce:**

I am using "develop" branch

Included in **bot-settings/default.json**:
"followStreets" : [ "GOOGLE" ],
"googleApiKey" : "mykey",

I am using a **Google Maps Android API** key. Is this correct?

Here's a list of choices, which one should I be using?
- Google Maps Android API
- Google Maps SDK for iOS
- Google Maps JavaScript API
- Google Places API for Android
- Google Places API for iOS
- Google Maps Roads API
- Google Static Maps API
- Google Street View Image API
- Google Maps Embed API
- Google Places API Web Service
- Google Maps Geocoding API
- Google Maps Directions API
- Google Maps Distance Matrix API
- Google Maps Geolocation API
- Google Maps Elevation API
- Google Maps Time Zone API

**Expected behavior:**
Bot should follow streets

**Actual behavior:**
Bot walks in straight lines

**Stacktrace (If it's a crash):**
Nil

**Version:**
"version" : "0.6.0",
Commit hash: 56339fb

**Operating System:**
OS X Yosemite, Version 10.10.5

**Java version:**
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Sieberkev** [comment]
>If you're using GOOGLE as route provider, get an api key here:
 https://developers.google.com/maps/documentation/directions/get-api-key
 You must enable Directions API and Elevation API
 The key always starts with "AIza"```

**Comment by Sieberkev** [comment]
I'll close this since this looks solved
