### ISSUE TITLE
[NEWAPI] Pokestop is too far using street, go directly

### ISSUE THREAD

**Issue by nostyler** [jabbink/PokemonGoBot#1260]
**Description:**
When using the newAPI branch with YOURNAVIGATION, I am seeing the following message multiple times: ` [default: WalkingLoop] - Pokestop is too far using street, go directly!`

**Steps to reproduce:**

1. Latitude = 52.369081447982424, Longitude = 4.888750449482097
2. Routeprovider = YOURNAVIGATION.

**Expected behavior:**
Don't know. This message was new for me and I do not know if this is 'good' or 'bad'.

**Actual behavior:**
It jumps from the middle of a street it followed before towards a route directly to the Pokestop.

**Stacktrace (If it's a crash):**
N/A.

**Version:**
Self-compiled. Latest and greatest version.

**Operating System:**
Ubuntu 16.04 x64

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Sieberkev** [comment]
Do you have the same behaviour on the same spot with the normal development branch?

**Comment by nostyler** [comment]
Yes I do actually. Perhaps this is related to the route provider? I will switch provider a few hours from now. To be continued...

**Comment by Sieberkev** [comment]
I think this is working as it should, if the pokestop is not ON the route, it will get as close as possible, and walk a straight line to the pokestop https://github.com/jabbink/PokemonGoBot/pull/1185#issuecomment-241192146

**Comment by FrancYescO** [comment]
Exactly, not a newapi issue and not an issue in general, we have 2 possibility if is too faraway from street ignore it or go in straight: the second one is actually hardcoded.
