### ISSUE TITLE
No pokeballs in your inventory

### ISSUE THREAD

**Issue by MacDogg** [jabbink/PokemonGoBot#1268]
**Description:**
Watching the bot work I see this appear:
[0;39m[31m01 Sep 09:28:14 [default: BotLoop] - No Pokeballs in your inventory; blacklisting Pokemon
I see this in the log:
01 Sep 09:28:14 [default: BotLoop] - No Pokeballs in your inventory; blacklisting Pokemon

My config regarding loot (no grouping):
item_revive=0
item_max_revive=0
item_potion=0
item_super_potion=0
item_hyper_potion=0
item_max_potion=0
item_poke_ball=15
item_great_ball=175
item_ultra_ball=-1
item_master_ball=-1
item_razz_berry=10
item_lucky_egg=-1
item_incense=-1
item_lure_module=-1

My inventory with time stamp (the bot has hit a bunch of pokestops and now has 14 normal balls).  I have over 100 great and ultra balls, it should use them, right?  Shoot, need to hatch those eggs manually, too.
![balls](https://cloud.githubusercontent.com/assets/20782190/18171476/ce933728-7027-11e6-823c-e5656bd0485e.jpg)

**Steps to reproduce:**
1. Let the bot keep running and it appears again and then works when a pokestop is hit and pokeballs and rewarded.

**Expected behavior:**
The bot should switch to great or ultra balls if pokeballs run out.

**Actual behavior:**
Bot starts blacklisting pokemons and doesn't catch them and doesn't use great or ultra balls.

**Version:**
0.6.0

**Operating System:**
Win10 Ult 64-bit

**Java version:**
[Full output of `java -version`]
build 1.8.0_101-b13

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by FrancYescO** [comment]
already solved in develop branch.

**Comment by MacDogg** [comment]
Well, that doesn't help me now, though.  Is there anything to do now, besides dump all the great and ultra balls and keep all the pokeballs?

**Comment by FrancYescO** [comment]
afaik nothing.

**Comment by digihax** [comment]
*cough* add compile steps/basics, to FAQ? *cough*

**Comment by EpicAwesomeWolf** [comment]
@digihax _cough_ maybe read USAGE.md? _cough_

**Comment by digihax** [comment]
*cough* wasn't there when I first looked a few weeks back *cough* but glad it is now *cough cough*
