### ISSUE TITLE
Setting drop value to -1 does not prevent it being dropped

### ISSUE THREAD

**Issue by TheMattRay** [jabbink/PokemonGoBot#127]
I set the following in the config.properties:
item_poke_ball=-1

I fired up the server and watched as it output:
Dropped 126x ITEM_POKE_BALL

This amongst other items similarly set.

**Comment by CosmoRing** [comment]
Only the master branch has the needed code. There isn't a release with that yet.

**Comment by TheMattRay** [comment]
Oh! Sorry!! I will close this then.
