### ISSUE TITLE
Not catching

### ISSUE THREAD

**Issue by russr123** [jabbink/PokemonGoBot#1273]
**Description:**
INVT is full, it dont even try to catch anything..

02 Sep 11:18:52 [default: BotLoop] - Getting map of (37.807465120697344, -122.42893201361775)
02 Sep 11:18:54 [default: PokestopLoop] - Looting nearby pokestop 5819fdfacc624ccc89448526084fa4fe.16
02 Sep 11:18:54 [default: PokestopLoop] - Looted pokestop 5819fdfacc624ccc89448526084fa4fe.16; +50 XP, but inventory is full
02 Sep 11:18:57 [default: BotLoop] - Getting map of (37.80748977632502, -122.4290354967438)
**Steps to reproduce:**

**Version:**
6.0
**Operating System:**
win7
**Java version:**
8.101
Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Sieberkev** [comment]
> INVT is full, it dont even try to catch anything

So make your configuration a bit tighter so it cleans up the inventory :)

**Comment by russr123** [comment]
it got full because its not catching anything....

**Comment by Sieberkev** [comment]
> drop_items=true
> item_*=*

These should at least clean up your itembag, even if you do not catch pokemons.

I've seen it in the past too (after receiving hundreds of levelrewards so my itembag was overflowing), after throwing away a lot of balls by hand the bot started catched pokemons again.

**Comment by russr123** [comment]
dumped a 100 items... started catching...
