### ISSUE TITLE
403 Forbidden when getting pokemon images #1276

### ISSUE THREAD

**Issue by AmazingGamerBoy** [jabbink/PokemonGoBot#1277]
**Description:**
When I use the rocketThemeGUI, I always get an error 403 Forbidden when it tries to load the images:
![image](https://cloud.githubusercontent.com/assets/15712937/18264278/a6c3371e-7452-11e6-813d-4da5aa3a6973.png)

Also when I use PGBGUI, I get an error on Origin Headers. I installed the origin header extension, and when it is on, it says something about not being able to set wildcard '*' as origin header. Image:
![image](https://cloud.githubusercontent.com/assets/15712937/18264348/0a8bc504-7453-11e6-9fa5-5a04ee877567.png)

**Steps to reproduce:**
Do not know how you could reproduce this issue.

**Expected behavior:**
Should load images and give me access to PGBGUI without origin header issues

**Actual behavior:**
RocketThemeGUI works fine but with no pokemon images. PGBGUI does not let me access bot map and all.

**Stacktrace (If it's a crash):**
Nothing here.

**Version:**
!#1275!

**Operating System:**
Windows 10 Home

**Java version:**
C:\Users\matthew>java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Sieberkev** [comment]
The RocketTheme UI is an external repository we do not maintain, you can make an issue on their tracker: https://github.com/eruecco87/PokemonGoBot-RocketTheme/issues
