### ISSUE TITLE
[SUGGESTION] Walk only option

### ISSUE THREAD

**Issue by CosmoRing** [jabbink/PokemonGoBot#128]
Add on the config file an option to only walk around the location and nothing more (except maybe adding eggs to incubators. 

I think this is a good addition to the bot so we can go arround hatching eggs and nothing more. This way people can even put the speed higher and it will look like the trainer is going around in bike just making Km to hatch those eggs.

Be best way i'm seeing about this is just add to the config options to turn of pokemon catch and pokestop spin.

**Comment by jabbink** [comment]
Fix incoming
