### ISSUE TITLE
default.json setting has revert to default

### ISSUE THREAD

**Issue by stupiz** [jabbink/PokemonGoBot#1280]
**Description:**
First I edit the config.preperties with these value
```
wait_between_throws=true
random_speed_range=0.5
wait_time_min=5
wait_time_max=15
export=JSON
bot_timeout_after_minutes=180
bot_timeout_after_catching_pokemon=900
bot_timeout_after_visiting_pokestops=1900
```
after run the bot it generated default.json but those goes back to default value
even I edited default.json then run the bot it also goes back to default value too.

**Steps to reproduce:**

1. Set these value in config.properties
   - wait_between_throws=true
   - random_speed_range=0.5
   - wait_time_min=5
   - wait_time_max=15
   - export=JSON
   - bot_timeout_after_minutes=180
   - bot_timeout_after_catching_pokemon=900
   - bot_timeout_after_visiting_pokestops=1900
2. Run bot
3. See default.json you will see the value goes back to default
   - "waitBetweenThrows" : false
   - "randomSpeedRange" : 0.0
   - "waitTimeMin" : 0
   - "waitTimeMax" : 0
   - "export" : "CSV"
   - "botTimeoutAfterMinutes" : -1
   - "botTimeoutAfterCatchingPokemon" : -1
   - ''botTimeoutAfterVisitingPokestops'' : -1
4. Edit value in default.json
   - "waitBetweenThrows" : true,
   - "randomSpeedRange" : 0.5,
   - "waitTimeMin" : 5,
   - "waitTimeMax" : 15,
   - "export" : "JSON",
   - "botTimeoutAfterMinutes" : 180,
   - "botTimeoutAfterCatchingPokemon" : 900,
   - "botTimeoutAfterVisitingPokestops" : 1900
5. Run bot
6. See default.json you will see the value goes back to default
   - "waitBetweenThrows" : false,
   - "randomSpeedRange" : 0.0,
   - "waitTimeMin" : 0,
   - "waitTimeMax" : 0,
   - "export" : "CSV",
   - "botTimeoutAfterMinutes" : -1,
   - "botTimeoutAfterCatchingPokemon" : -1,
   - "botTimeoutAfterVisitingPokestops" : -1

**Expected behavior:**
It should generate default.json from config.properties value like other parameter and should save the value after I edit default.json

**Version:**
5da5fce5302ba10856af14def962b91e9de0fa11

**Operating System:**
Mac OS X 10.11.6

**Java version:**
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by FrancYescO** [comment]
Close the bot before edit.

**Comment by stupiz** [comment]
Thanks, I just edit while botting.
