### ISSUE TITLE
RocketTheme image issue.

### ISSUE THREAD

**Issue by faragloch** [jabbink/PokemonGoBot#1282]
**Description:**
The RocketThemeUI doesn't show the pokemon images (on bank or map)

**Expected behavior:**
It should show the pokemon images

**Actual behavior:**
Shows the "uncharged image" icon.

![screenshot_1](https://cloud.githubusercontent.com/assets/17753319/18336269/1cd647d4-755c-11e6-9dfb-983dea1fd828.png)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Sieberkev** [comment]
The RocketTheme UI is an external repository we do not maintain, you can make an issue on their tracker: https://github.com/eruecco87/PokemonGoBot-RocketTheme/issues
