### ISSUE TITLE
[SUGGESTION] Adding a GUI

### ISSUE THREAD

**Issue by confin234** [jabbink/PokemonGoBot#129]
Maybe somebody could add in a GUI and/or maybe add the option to execute the file through an .exe.

**Comment by ColeB27** [comment]
You can create a batch file to execute the program.

**Comment by ColeB27** [comment]
#1 Create a text document.
#2 Paste this: java -jar pogo.scraper-all-0.3.0.jar
#3 Change text file to All files
#4 Save as Run.bat
#5 Done!

**Comment by pr0ves** [comment]
Duplicate of #110
