### ISSUE TITLE
[Suggestion] Use Fastpokemap to see where are nearby pokemons and have a preference list

### ISSUE THREAD

**Issue by alexvkcr** [jabbink/PokemonGoBot#1291]
**Description:**
It would be cool the bot could use FastPokeMap t osee nearby pokemon, ignore shitty pokemons and walk straight to them by knowing which are close to you

**Actual behavior:**
It picks every shit and walks randomly

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by jabbink** [comment]
It doesn't pick all "shit". Only the "shit" you configured it to pick. Also it does not walk random and actually sees the same Pokemon that website would show you. An integration would not result in more Pokemon found.

**Comment by jabbink** [comment]
Forgot to close this. Also FPM is dead.
