### ISSUE TITLE
 Got 0 pokestops

### ISSUE THREAD

**Issue by Siaco** [jabbink/PokemonGoBot#1302]
**Description:**
Impossible find pokestops in any place.

**Steps to reproduce:**

1. launch  PokemonGoBot-0.6.0.jar with default config.properties and any coords

**Expected behavior:**
find pokestops and start to play

**Actual behavior:**
10 ott 10:20:30 [default] - Got 0 pokestops
10 ott 10:20:30 [default] - Retrying in 10 seconds...
10 ott 10:20:40 [default] - Got 0 pokestops
10 ott 10:20:40 [default] - Retrying in 10 seconds...
10 ott 10:20:50 [default] - Got 0 pokestops
10 ott 10:20:50 [default] - Decreasing initialMapSize to 7
10 ott 10:20:50 [default] - Retrying in 10 seconds...
10 ott 10:21:01 [default] - Got 0 pokestops
10 ott 10:21:01 [default] - Retrying in 10 seconds...

**Version:**
PokemonGoBot-0.6.0

**Operating System:**
Windows 10

**Java version:**
1.8.0_102

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by chudungg** [comment]
same problem on Mac Osx

**Comment by EpicAwesomeWolf** [comment]
It's from the new update.

**Comment by gielie** [comment]
same here, bot is not working anymore.
We have to wait for the update.

**Comment by jabbink** [comment]
^

Update 0.37+ broke every bot/map/external tool.
