### ISSUE TITLE
Decreasing map size off start

### ISSUE THREAD

**Issue by Rabbitslayer30** [jabbink/PokemonGoBot#1304]
**Description:**
Didn't know if your still working on this project or not, but keep running into a issue after it logs in. It keeps trying to say there are 0 pokestops and then decreasing the field. 

![capture](https://cloud.githubusercontent.com/assets/22856574/19410934/5f02b0b0-92bd-11e6-8ff2-a7fec55b985f.JPG)

So you have an idea of what its doing...I've gone back thru some of the code to try to figure it out, with no luck as of yet. Will update if I figure it out, or any help would be awesome. 

**Version:**
0.6.0

**Operating System:**
windows 7

**Java version:**
newest from java website

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Rabbitslayer30** [comment]
nm pls close, I just now found your other page that had been closed about this issue. I will continue to dive into why and how to fix. thanks for everything bud.

**Comment by jabbink** [comment]
yeah. niantic changed the protocol so right now it isn't working (like every other bot out there).
