### ISSUE TITLE
New API not detect 90% of pokemons (v0.7.1)

### ISSUE THREAD

**Issue by alone23** [jabbink/PokemonGoBot#1305]
**Expected behavior:**
From iPhone i can see several pokemons

**Actual behavior:**
Bot only detect (and try to catch) just one or none

**Version:**
v0.7.1

**Operating System:**
MacOSX

**Java version:**
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by jaacks** [comment]
Remember that this is a beta test of the new API.

**Comment by alone23** [comment]
Fixed on 0.7.3
