### ISSUE TITLE
Error then nothing but walking

### ISSUE THREAD

**Issue by TechnoDaft** [jabbink/PokemonGoBot#1308]
**Description:**
I run the bot but randomly it throws an error "Exception in thread "RxComputationScheduler-8" java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling." and after the error it does nothing at all

**Steps to reproduce:**

1. Run the bot
2. Wait for error

**Expected behavior:**
Continue to loot pokestops {and receive rewards} and catch pokemon

**Actual behavior:**
does nothing

**Version:**
7.0-7.3

**Operating System:**
Win10 Pro x64

**Java version:**
[Full output of `java -version`]

![image](https://cloud.githubusercontent.com/assets/20615768/20237966/7b32d02e-a8ae-11e6-9d3a-6a29a1344d0c.png)

![image](https://cloud.githubusercontent.com/assets/20615768/20237969/87ae60ac-a8ae-11e6-9d3b-6ade0f63918f.png)

![image](https://cloud.githubusercontent.com/assets/20615768/20238004/5e08fdce-a8af-11e6-87e8-bdb4ec41403a.png)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by alone23** [comment]
+1

Many errors like this on 1.0.0

**Comment by jabbink** [comment]
@alone23 downgrade to 0.8.2

**Comment by LordJavi** [comment]
Fixed with 1.0.1

**Comment by jabbink** [comment]
also error 502: niantic servers went offline.

**Comment by TechnoDaft** [comment]
I still got this problem with 1.0.1
