### ISSUE TITLE
Bot Hangs Getting Initial Pokestops With Multiple .json Config Files

### ISSUE THREAD

**Issue by pondandinio** [jabbink/PokemonGoBot#1310]
Description:
Bot hangs at "Getting initial pokestops..." when using multiple bot.json config files. No failure or error message is triggered. Bots will run happily if only one .json file is present in the bot-settings directory or in multiple separated directories (and using --server.port=808n.

Expected behaviour:
Bot should start catching pokemon

Actual behaviour:
Bot hangs at "Getting initial pokestops...". bot does not move or catach pokemon. Unable to log into web gui

Version:
0.7.2/0.7.3/0.7.4

Operating System:
Win10 x64

Java version:
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by alone23** [comment]
+1

same issue

**Comment by jabbink** [comment]
Are you using proxies?

Because you can't run multiple bots from the same IP (or a maximum of 2)

**Comment by jabbink** [comment]
Ah, now I see whats happening; Was able to reproduce it. I'll try to fix it.

**Comment by GothikMizerie** [comment]
Do you happen to have an ETA? Just curious

**Comment by jabbink** [comment]
Now

**Comment by jabbink** [comment]
Please confirm functionality

**Comment by GothikMizerie** [comment]
Works great! thanks
