### ISSUE TITLE
Wrong stardust in update profile

### ISSUE THREAD

**Issue by alone23** [jabbink/PokemonGoBot#1315]
**Expected behavior:**
Real startdust

**Actual behavior:**
14 nov 16:47:45 [RxComputationScheduler-3] - Pokemon caught/transferred: 0/0; Pokemon caught from lures: 0; Items caught/dropped: 0/0;
14 nov 16:47:45 [RxComputationScheduler-3] - Pokebank 232/400; Stardust **1194**; Inventory 741/850

14 nov 16:48:45 [RxComputationScheduler-3] - Pokemon caught/transferred: 2/1; Pokemon caught from lures: 0; Items caught/dropped: 10/110;
14 nov 16:48:45 [RxComputationScheduler-3] - Pokebank 233/400; Stardust **1194**; Inventory 639/850

14 nov 16:49:45 [RxComputationScheduler-4] - Pokemon caught/transferred: 3/3; Pokemon caught from lures: 0; Items caught/dropped: 13/111;
14 nov 16:49:45 [RxComputationScheduler-4] - Pokebank 232/400; Stardust **1194**; Inventory 637/850

14 nov 16:50:45 [RxComputationScheduler-1] - Pokemon caught/transferred: 3/3; Pokemon caught from lures: 0; Items caught/dropped: 17/112;
14 nov 16:50:45 [RxComputationScheduler-1] - Pokebank 232/400; Stardust **1194**; Inventory 640/850

14 nov 16:51:45 [RxComputationScheduler-2] - Pokemon caught/transferred: 5/3; Pokemon caught from lures: 0; Items caught/dropped: 27/114;
14 nov 16:51:45 [RxComputationScheduler-2] - Pokebank 234/400; Stardust **1194**; Inventory 641/850

**Version:**
v0.7.X

**Operating System:**
MacOSX

**Java version:**
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Cypherke** [comment]
bug still in 8.2

**Comment by veridicis** [comment]
I can confirm also. Though it updates to correct value when you restart the bot

**Comment by jabbink** [comment]
It only misses getting stardust from pokemon catches?

If so, fix incoming within 12h.
