### ISSUE TITLE
[Request] option to do captcha {or settings to never get a captcha to begin with}

### ISSUE THREAD

**Issue by TechnoDaft** [jabbink/PokemonGoBot#1319]
**Description:**
Getting Captcha no option to do it

**Steps to reproduce:**

1. Run bot?
2. get error
![image](https://cloud.githubusercontent.com/assets/20615768/20286251/d11bc0a4-aa93-11e6-9f31-81303d8c816f.png)

**Expected behavior:**
An option to do the captcha {or bot to stop and not keep trying to play}

**Actual behavior:**
No option to do the captcha instead keeps trying to play {but fails}

**Version:**
8.0

**Operating System:**
Win10 x64 pro

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by TechnoDaft** [comment]
this is my settings if you got recommended to change to let me know

{
  "name" : "bot",
  "latitude" : xx.12845986010458,
  "longitude" : -xx.08336475491524,
  "savedLatitude" : 0.0,
  "savedLongitude" : 0.0,
  "saveLocationOnShutdown" : false,
  "credentials" : {
    "type" : "google-auto",
    "username" : "xxxxxxx@gmail.com",
    "password" : "xxxxxxxxxxxx"
  },
  "proxyServer" : "",
  "proxyPort" : -1,
  "proxyType" : "SOCKS",
  "proxyUsername" : "",
  "proxyPassword" : "",
  "speed" : 2.5,
  "randomSpeedRange" : 0.5,
  "followStreets" : [ "GOOGLE", "MAPZEN" ],
  "mapzenApiKey" : "valhalla-xxxxxxx",
  "googleApiKey" : "AIzaxxxxxxxxxxx",
  "groupItemsByType" : true,
  "dropItems" : true,
  "itemDropDelay" : 750,
  "uselessItems" : {
    "ITEM_REVIVE" : 0,
    "ITEM_MAX_REVIVE" : 10,
    "ITEM_POTION" : 0,
    "ITEM_SUPER_POTION" : 0,
    "ITEM_HYPER_POTION" : 0,
    "ITEM_MAX_POTION" : 10,
    "ITEM_POKE_BALL" : 0,
    "ITEM_GREAT_BALL" : 0,
    "ITEM_ULTRA_BALL" : 125,
    "ITEM_MASTER_BALL" : -1,
    "ITEM_RAZZ_BERRY" : 10,
    "ITEM_LUCKY_EGG" : -1,
    "ITEM_INCENSE_ORDINARY" : -1,
    "ITEM_TROY_DISK" : -1
  },
  "profileUpdateTimer" : 60,
  "timerWalkToStartPokestop" : -1,
  "randomNextPokestopSelection" : 5,
  "campLurePokestop" : -1,
  "desiredCatchProbability" : 0.75,
  "desiredCatchProbabilityUnwanted" : 0.25,
  "autotransfer" : true,
  "autotransferTimeDelay" : 1250,
  "randomBallThrows" : true,
  "waitBetweenThrows" : true,
  "keepPokemonAmount" : 1,
  "maxPokemonAmount" : 4,
  "displayKeepalive" : true,
  "displayPokestopName" : true,
  "displayPokestopRewards" : true,
  "displayPokemonCatchRewards" : true,
  "displayIfPokemonFromLure" : true,
  "lootPokestop" : true,
  "catchPokemon" : true,
  "autoFillIncubator" : true,
  "sortByIv" : true,
  "desiredCurveRate" : 0.0,
  "neverUseBerries" : true,
  "allowLeaveStartArea" : false,
  "spawnRadius" : -1,
  "banSpinCount" : 0,
  "transferCpThreshold" : -1,
  "transferCpMinThreshold" : -1,
  "transferIvThreshold" : 95,
  "ignoredPokemon" : [ "MEW", "MEWTWO", "MOLTRES", "ZAPDOS", "ARTICUNO" ],
  "obligatoryTransfer" : [ ],
  "evolveBeforeTransfer" : [ ],
  "neverCatchPokemon" : [ ],
  "evolveStackLimit" : 125,
  "useLuckyEgg" : 1,
  "evolveTimeDelay" : 27500,
  "export" : "",
  "guiPortSocket" : 8001,
  "restApiPassword" : "424043",
  "initialMapSize" : 9,
  "version" : "0.8.0",
  "waitChance" : 0.1,
  "waitTimeMin" : 5,
  "waitTimeMax" : 30,
  "botTimeoutAfterMinutes" : -1,
  "botTimeoutAfterCatchingPokemon" : -1,
  "botTimeoutAfterVisitingPokestops" : -1,
  "buddyPokemon" : ""
}

**Comment by jabbink** [comment]
This error is unrelated to the captcha and shouldn't break the bot. In this case it did that though. Was this early at the beginning?

Also in case you get flagged for a captcha: It instantly tells you about that and kills itself.

**Comment by TechnoDaft** [comment]
no that was after starting the bot again the initial error did the same pretty much and kept going over and over. I borrowed my grandmothers phone to do the captcha and when i did it said my account was terminated bs now lol

**Comment by jaacks** [comment]
I guess rip your account, for the captcha however it's an essential part of Niantic stopping hackers, and I doubt there will ever be a work around.

**Comment by TechnoDaft** [comment]
not asking for a workaround in the slightest asking for an option to do the captcha in your browser or something or settings i can use to not get a captcha to begin with

**Comment by TechnoDaft** [comment]
seems bot was detected by niantic and got banned for it so wasnt a captcha issue to begin with lol #closed
