### ISSUE TITLE
Encounter failed with result

### ISSUE THREAD

**Issue by zhoushifeng8** [jabbink/PokemonGoBot#1323]
1 night just can caught 70 pokemon
most of time got encounter failed
**Description:**
17 十一月 00:26:58 [default: BotLoop] - Found pokemon PIKACHU
17 十一月 00:26:59 [default: BotLoop] - Encounter failed with result: ENCOUNTER_CLOSED
17 十一月 00:26:59 [default: WalkingLoop] - Pausing to catch pokemon...
17 十一月 00:27:03 [default: BotLoop] - Getting map of (1.282232370728975, 103.86408994194636)
17 十一月 00:27:03 [default: BotLoop] - Found pokemon PIKACHU
17 十一月 00:27:03 [default: BotLoop] - Encounter failed with result: ENCOUNTER_CLOSED
17 十一月 00:27:04 [default: WalkingLoop] - Pausing to catch pokemon...
17 十一月 00:27:08 [default: BotLoop] - Getting map of (1.2822531409747369, 103.86420964218202)
17 十一月 00:27:08 [default: BotLoop] - Found pokemon PIKACHU
17 十一月 00:27:08 [default: BotLoop] - Encounter failed with result: ENCOUNTER_CLOSED
17 十一月 00:27:09 [default: WalkingLoop] - Pausing to catch pokemon...
17 十一月 00:27:13 [default: BotLoop] - Getting map of (1.2822274611325535, 103.86425305034643)
17 十一月 00:27:13 [default: BotLoop] - Found pokemon PIKACHU
17 十一月 00:27:14 [default: BotLoop] - Encounter failed with result: ENCOUNTER_CLOSED
17 十一月 00:27:14 [default: WalkingLoop] - Pausing to catch pokemon...
17 十一月 00:27:18 [default: BotLoop] - Getting map of (1.2821057443760733, 103.86422202088673)
17 十一月 00:27:18 [default: BotLoop] - Found pokemon PIKACHU
17 十一月 00:27:19 [default: BotLoop] - Encounter failed with result: ENCOUNTER_CLOSED
17 十一月 00:27:19 [default: WalkingLoop] - Pausing to catch pokemon...
17 十一月 00:27:23 [default: BotLoop] - Getting map of (1.2820353051930524, 103.86427312080855)
17 十一月 00:27:23 [default: BotLoop] - Found pokemon PIKACHU
17 十一月 00:27:23 [default: BotLoop] - Encounter failed with result: ENCOUNTER_CLOSED

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]

**Expected behavior:**
[What should happen?]

**Actual behavior:**
[What actually happens]

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
0.8.2
**Operating System:**
MAC

**Java version:**
latest
Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Cypherke** [comment]
try in version 1.0.1

**Comment by zhoushifeng8** [comment]
@Cypherke Thank you, will try

**Comment by LordJavi** [comment]
Fixed :)
