### ISSUE TITLE
I cannot find the solution anywhere. Please help

### ISSUE THREAD

**Issue by klowny** [jabbink/PokemonGoBot#1337]
**Description:*  [Im a complete noob and i dont know what i did wrong but when i run the bot it loads and then starts repeating this screen nonstop someone please help me just get it working.
 Re-queueing DOWNLOAD_SETTINGS, 
Re-queueing GET_INVENTORY, 
.Unexpected response envelope status received: SESSION_INVALIDATED; Responses are probably malformed or unreliable
Inconsistent replies received; expected 4 payloads; received 0
Probable culprit:
GET_PLAYER
player_locale {
}

Envelope location: 40.7828647 -73.9675438
Re-queueing GET_PLAYER, player_locale {
}
 ]

**Steps to reproduce:**

1. [Run it]
2. [Then this happens]
![screenshot from 2017-04-05 23 36 25](https://cloud.githubusercontent.com/assets/26943886/24736895/d79f5d66-1a58-11e7-90d3-276a1e165548.png)

**Expected behavior:**
[The bot should run]

**Actual behavior:**
[]

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
[0.8.2.]

**Operating System:**
[Ubuntu 15.04]

**Java version:**
[1.8.0]

![image](https://cloud.githubusercontent.com/assets/26943886/24736935/04f0ad7e-1a59-11e7-89e3-38e0ee86bed8.png)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by jabbink** [comment]
The bot is outdated as the communication protocol is not publicly available anymore.
