### ISSUE TITLE
Bot gets stuck in a loop of DOWNLOAD_SETTINGS & GET_INVENTORY

### ISSUE THREAD

**Issue by subbu45** [jabbink/PokemonGoBot#1338]
### Prerequisites (Remove this section if you want)
Make sure you...

* Have checked the FAQ if your question has not been answered there.
* Have searched the existing issues if your question has not been asked here.
* Post a FULL stacktrace and not only a part of it.
* Fill in all the fields correctly, it helps us immensly if we get a complete image of your situation.

**Description:**
When I start the bot, after logging in it gets trapped in a cycle of this:
Re-queueing DOWNLOAD_SETTINGS, 
Re-queueing GET_INVENTORY, 
^[[BUnexpected response envelope status received: SESSION_INVALIDATED; Responses are probably malformed or unreliable
Inconsistent replies received; expected 4 payloads; received 0
Probable culprit:
GET_PLAYER
player_locale {
}

Envelope location: 52.369295 4.909531
Re-queueing GET_PLAYER, player_locale {
}

**Steps to reproduce:**
1. Before hand, finish the tutorial on the account
2. Download the bot
3. Change config.properties with your login info
4. Start bot with java -jar then drag in the jar file into terminal

**Expected behavior:**
The bot should start botting

**Actual behavior:**
It gets stuck in a loop

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
The latest release (v1.0.1

**Operating System:**
Mac OS X Yosemite
**Java version:**
[Full output of `java -version`]
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Cypherke** [comment]
https://github.com/jabbink/PokemonGoBot/issues/1337#issuecomment-292156333
