### ISSUE TITLE
[BUG?] Bot can't get player

### ISSUE THREAD

**Issue by ghost** [jabbink/PokemonGoBot#1339]
Whenever I start the bot It logs in and then gets an error or something. (I'm not very good with computers) This is probably a quick fix for you guys but I have no clue what causes it.

[32m27 mai 20:23:33 [default] - Trying to read C:\Users\jacob\Desktop\PGbots\PGB\config.properties
[0;39m[37m27 mai 20:23:33 [default] - Logging in to game server...
[0;39m[37m27 mai 20:23:33 [default] - Loaded last saved location (58.027681, 7.45333)
[0;39m[PTC] Logging back in!
[37m27 mai 20:23:34 [default] - Logged in successfully
[0;39mGetting profile data from pogo server..Unexpected response envelope status received: SESSION_INVALIDATED; Responses are probably malformed or unreliable
Inconsistent replies received; expected 4 payloads; received 0
Probable culprit:
GET_PLAYER
player_locale {
}

Envelope location: 58.027681 7.45333
Re-queueing GET_PLAYER, player_locale {
}

Re-queueing DOWNLOAD_SETTINGS,
Re-queueing GET_INVENTORY,
--At this point it just loops the same thing forever.

I'm using the latest version: PokemonGoBot-1.0.1.jar on Windows 10 with Java version 1.8.0

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by jabbink** [comment]
Bot has been outdated for more than half a year now I think.
