### ISSUE TITLE
2 things

### ISSUE THREAD

**Issue by megatixos** [jabbink/PokemonGoBot#137]
1) I want to contribute but in the readme file you say Copy src/main/resources/config.properties.template to src/main/resources/config.properties but there is no resources folder after main folder..
Any help on how to get started would be appreciated. (i cloned the repository.. what to do next?)
2) will there be a release today?

**Comment by pr0ves** [comment]
The readme needs to be updated. The config.properties.template is in the root folder, do a copy a change the filename to config.properties, then fill in the blanks.
As for the release, @jabbink should answer this.

**Comment by jabbink** [comment]
I want to release when egg hatching and a smarter poke ball selector are fully built in.

**Comment by wartickler** [comment]
@jabbink how are you distributing the work so you don't duplicate efforts?

**Comment by jabbink** [comment]
Just claim an issue and assign yourself/comment that you're working on it.

Or come to the #PokemonGoBot chat on the slack

**Comment by wartickler** [comment]
@jabbink do I need an invite for the slack chat?
