### ISSUE TITLE
Egg Hatch - Not opening eggs?

### ISSUE THREAD

**Issue by PancakeZik** [jabbink/PokemonGoBot#138]
I noticed that the bot can start hatching an egg, but after the distance is complete, the only way of opening it is opening the app on my phone. The bot just won't do it.

**Comment by pr0ves** [comment]
Are you using the jar? If yes, wait for a new release, or run the source directly

**Comment by PancakeZik** [comment]
I'm running the source

**Comment by pr0ves** [comment]
Ah wait, the Bot doesn't open an egg if it reached the distance. It can't because the pokegoapi doesnt let it. They should add a function so that we can do it.

**Comment by megatixos** [comment]
How to run the source?

**Comment by mozzy306** [comment]
do i run source the same way i run the jar?

**Comment by PancakeZik** [comment]
Yes, therefore hatching eggs is kind of pointless unless you constantly open the app, because the bot will only hatch 1 by itself

**Comment by megatixos** [comment]
Can anyone give me link for source? i want to try the new features!

**Comment by pr0ves** [comment]
@megatixos @mozzy306 you guys are off topic, we'll update the readme but for now you have to wait.
@PancakeZik for now the bot will only add an egg in an incubator if there's one free, to open the eggs, as I said we'll have to wait for the api to be updated

**Comment by jabbink** [comment]
Oh, forgot that this was already an issue: #2
