### ISSUE TITLE
IV/CP threshold definition

### ISSUE THREAD

**Issue by ToMeRhh** [jabbink/PokemonGoBot#141]
I'm finding it hard to understand the threshold;
the config template says: 'to ignore IV/CP: use -1'. does 'ignore' means 'always release'? or 'always keep'?

personally, I think -1 should be 'always keep', therefore the condition inside ReleasePokemon.kt should be changed.

If you agree, feel free to review+merge the referenced PR (hope I referenced it right :) )
#140

**Comment by pr0ves** [comment]
To always keep, you add the name of the pokemon you always want to keep regardless of CP/IV to `ignoredPokemon`. If, as you say, -1 should 'always keep' it will keep all the pokemons and transfer none, defying the feature offered by ReleasePokemon

**Comment by ToMeRhh** [comment]
by the current implementation? yep. but you could always use: 'obligatory_transfer' to ignore the -1.

meaning:
you can either use -1 and 'always keep' all pokemons except those in 'obligatory_transfer'
or you can use a number!=-1 and ignore pokemons in 'ignored_pokemon'

**Comment by pr0ves** [comment]
But then you won't use the threshold for CP or IV or both.

**Comment by ToMeRhh** [comment]
I don't think I understand,

> or you can use a number!=-1 and ignore pokemons in 'ignored_pokemon'
^ this one acts normally; compares the threshold to the actual CP and IV...

**Comment by pr0ves** [comment]
Let's rewind a bit.
The actual bot transfer all the pokemon, but the one in ignoredPokemon, that have iv<maxIV && cp<maxCP plus any pokemon in obligatoryPokemon. If any of iv or cp is set to -1, the bot will transfer regardless of the property.
You want that when anyone between iv or cp is set to -1, the bot should keep all the pokemon but the ones in obligatory_transfer, but for example if iv=-1 and cp=300, the bot will keep all the pokemon (except the one in obligatory_transfer) even those who have a cp<300. 
Am I getting this wrong?

**Comment by ToMeRhh** [comment]
generally speaking, when an option is '-1' == 'ignore me' == 'don't release because of me'.
by your example:
iv=-1, cp=300, the bot will no preform a check for iv, but for cp only. therefore a pokemon with cp<300 will be released, and a pokemon with cp>300 will be kept.

I might have a mess with explaining, and I will take another look at the pull-request to see if my explanation and meaning fits my implementation.

**Comment by pr0ves** [comment]
> when an option is '-1' == 'ignore me'
> iv=-1, cp=300, the bot will no perform a check for iv, but for cp only.

Yes. It is ignoring iv and considering only cp

**Comment by ToMeRhh** [comment]
currently:
`
                                if (ivPercentage < minIVPercentage || minIVPercentage == -1) {
                                    ivTooLow = true
                                }
                                // never transfer > min CP  (unless set to -1)
                                if (pokemon.cp < minCP || minCP == -1) {
                                    cpTooLow = true
                                }
                                reason = "CP < $minCP and IV < $minIVPercentage"
                                shouldRelease = ivTooLow && cpTooLow
`

meaning, if we set minIVPercentage and minCP  to -1, we will release ALL pokemons.

**Comment by pr0ves** [comment]
Yeah, it ignores both iv and cp and release all the pokemon but the ones in ignored_pokemon.
It would be a problem if the user set both to -1, but that's his problem not ours.
We could add a warning to advice him to not set both to -1.

**Comment by ToMeRhh** [comment]
never mind then, I just though it makes more sense the other way around :)
