### ISSUE TITLE
Compile Issues

### ISSUE THREAD

**Issue by KyleBoyer** [jabbink/PokemonGoBot#145]
Hey all,

Would it be possible for someone to compile the latest jar file? I've been trying to run from source, or compile from source with no luck. I'm running Mac OS X El Capitan, and I installed kotlin and gradle, and eclipse, and eclipse plugins to run kotlin - with no luck.

Thanks,
Kyle

**Comment by ToMeRhh** [comment]
doesn't a simple 'greadlew run' works for you?

**Comment by cglatot** [comment]
I think using **gradlew fatJar** is the best method to compile the single Jar file. That's what I've been using.

**Comment by pr0ves** [comment]
Try first this:
`gradlew --refresh-dependencies clean build`
Then compile the jar or run `gradlew run`

**Comment by megatixos** [comment]
Where do i write this? at cmd right?

**Comment by pr0ves** [comment]
Yes.

**Comment by KyleBoyer** [comment]
This worked! Thank you guys! :)
