### ISSUE TITLE
[SUGGESTION] Add the IV% to the list of information after catching a Pokemon

### ISSUE THREAD

**Issue by cglatot** [jabbink/PokemonGoBot#148]
Add the IV% to the list of information after catching a Pokemon. Although we may have a filter set lower, it would be useful to see if we have caught any high IV% Pokemon.

`Caught a POKEMON with CP XXX and IV 98% using ITEM_POKE_BALL.......`

**Comment by pr0ves** [comment]
Added in #147

**Comment by pashorizer** [comment]
Enhanced it a bit further https://github.com/jabbink/PokemonGoBot/pull/158
