### ISSUE TITLE
Problem building  ":compileKotlin FAILED"

### ISSUE THREAD

**Issue by gargomoma** [jabbink/PokemonGoBot#150]
PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Settings.kt: (26, 107): Unresolved reference: Base64
:compileKotlin FAILED

Just cloned, tried without editing and also as suggested on #97

**Comment by ToMeRhh** [comment]
go to: settings.kt
change:
    val password = if (properties.containsKey("password")) properties.getProperty("password") else String(Base64.getDecoder().decode(properties.getProperty("base64_password", "")))

to:
    val password = properties.getProperty("password")

**Comment by pr0ves** [comment]
Base64 is a class of java.util, which is included when you install the jdk.
Is this the only error you get?

**Comment by gargomoma** [comment]
Yes is the only one, i did as ToMeRhh told me and is working!

**Comment by pr0ves** [comment]
Base64 is included in java 8, you probably have java 7. Is that right?

**Comment by Demelza** [comment]
```
:compileKotlin
e: /Users/mazda/Downloads/PokemonGoBot-master/src/main/kotlin/ink/abb/pogo/scraper/tasks/HatchEggs.kt: (21, 50): Unresolved reference: incubators
e: /Users/mazda/Downloads/PokemonGoBot-master/src/main/kotlin/ink/abb/pogo/scraper/tasks/HatchEggs.kt: (21, 71): Unresolved reference: it
e: /Users/mazda/Downloads/PokemonGoBot-master/src/main/kotlin/ink/abb/pogo/scraper/tasks/HatchEggs.kt: (22, 40): Unresolved reference: hatchery
e: /Users/mazda/Downloads/PokemonGoBot-master/src/main/kotlin/ink/abb/pogo/scraper/tasks/HatchEggs.kt: (22, 63): Unresolved reference: it
e: /Users/mazda/Downloads/PokemonGoBot-master/src/main/kotlin/ink/abb/pogo/scraper/tasks/HatchEggs.kt: (22, 92): Unresolved reference: it
:compileKotlin FAILED
```

I get this error when trying to compile latest source. Nothing related to base64 though, not the same file/error.

**Comment by pr0ves** [comment]
That's because you have the old api.
Always try this first if there's a compile error `gradlew --refresh-dependencies clean build`; if it doesn't fix it, open an issue or check for similar ones
