### ISSUE TITLE
I am not able to transfer any pokemon 

### ISSUE THREAD

**Issue by AnivaJ** [jabbink/PokemonGoBot#152]
I am currently using these settings in my config file; however, i am unable to transfer any pokemon less than 500 cp.

Someone please advice.

```
username=xxxx

# Choose plaintext or base64'd password
password=tregdgffg
base64_password=

# Token to login directly
token=
latitude=
longitude=
preferred_ball=ITEM_POKE_BALL

## Walking
# Meters per second
speed=7.778

## Items drop
# should the bot EVER drop items (true/false)
drop_items=true

# max number of each item that the bot should keep if "drop_items" is enabled
# use -1 in a item to never drop this specific item
item_revive=20
item_max_revive=10
item_potion=0
item_super_potion=30
item_hyper_potion=50
item_max_potion=50
item_poke_ball=50
item_great_ball=50
item_ultra_ball=50
item_master_ball=50
item_razz_berry=50

## Extra Info
# should the bot display information of where it's walking to (true/false)
display_walking_nearest_unused=false

# should the bot display rewards pokestop (true/false)
display_pokestop_rewards=true

# should the bot display rewards when catching pokemon (true/false)
display_pokemon_catch_rewards=true

## Pokemon Transfer
# should the bot auto transfer duplicate pokemon
autotransfer=true

# Minimum IV percentage to keep a pokemon (to ignore IV: use -1)
# between 0 and 100, suggested 80
transfer_iv_threshold= 1

# Minimum CP to keep a pokemon (to ignore CP: use -1)
transfer_cp_threshold=500

# Only walk (hatch eggs, don't collect pokemon or pokestops)
walk_only=false


# list of pokemon you don't want to transfer regardless of CP
# the names must be divided by a ","
# if you want all pokemons to be transferred just leave it blank
ignored_pokemon=

# list of pokemon you always want to trancsfer regardless of CP
obligatory_transfer=DODUO,RATTATA,CATERPIE,PIDGEY,PINSIR

```

**Comment by pr0ves** [comment]
you set transfer_iv_threshold= 1, if you want to disable it you have to set it to -1, 1 is just too little so it keeps every pokemon.

**Comment by pr0ves** [comment]
Also when setting a property be sure that there's no space after '=', 
like `transfer_iv_threshold=1` and not `transfer_iv_threshold= 1,`

**Comment by AnivaJ** [comment]
OMG! thank you so much the issue was was this transfer_iv_threshold=1 and not transfer_iv_threshold= 1,

**Comment by pr0ves** [comment]
I suggest that you set that value higher, like at least 60. With 1 you will keep many weak pokemkns

**Comment by Dragunovam** [comment]
I'm having having the same issue, on my build the pokemon are not being released, even with standard 400 cp threshold

**Comment by jabbink** [comment]
Do you have `autotransfer=true`?

**Comment by Dragunovam** [comment]
No, that should - by default - transfer duplicates, right ?

**Comment by pr0ves** [comment]
Post your config.properties without the pokemon list; use the insert code function when pasting it, it's the button with "<>" as icon.

**Comment by Dragunovam** [comment]
`# PTC/Google login credentials
username=redacted

# Choose plaintext or base64'd password
password=redacted
base64_password=

# Token to login directly
token=
latitude=redacted
longitude=redacted
preferred_ball=ITEM_POKE_BALL

## Walking
# Meters per second
speed=7.0

## Items drop
# should the bot EVER drop items (true/false)
drop_items=true

# max number of each item that the bot should keep if "drop_items" is enabled
# use -1 in a item to never drop this specific item
item_revive=20
item_max_revive=10
item_potion=0
item_super_potion=30
item_hyper_potion=50
item_max_potion=50
item_poke_ball=50
item_great_ball=50
item_ultra_ball=50
item_master_ball=50
item_razz_berry=50

## Extra Info
# should the bot display information of where it's walking to (true/false)
display_walking_nearest_unused=false

# should the bot display rewards pokestop (true/false)
display_pokestop_rewards=true

# should the bot display rewards when catching pokemon (true/false)
display_pokemon_catch_rewards=true

## Pokemon Transfer
# should the bot auto transfer duplicate pokemon
autotransfer=false

# Minimum IV percentage to keep a pokemon (to ignore IV: use -1)
# between 0 and 100, suggested 80
transfer_iv_threshold=85

# Minimum CP to keep a pokemon (to ignore CP: use -1)
transfer_cp_threshold=400

# Only walk (hatch eggs, don't collect pokemon or pokestops)
walk_only=false

# list of pokemon you don't want to transfer regardless of CP
# the names must be divided by a ","
# if you want all pokemons to be transferred just leave it blank
ignored_pokemon=EEVEE,MEWTWO,CHARMANDER

# list of pokemon you always want to trancsfer regardless of CP
obligatory_transfer=DODUO,RATTATA,CATERPIE,PIDGEY,SPEAROW

#List of pokemon names
#MISSINGNO
#BULBASAUR
#IVYSAUR
#VENUSAUR
#CHARMANDER
#CHARMELEON
#CHARIZARD
#SQUIRTLE
#WARTORTLE
#BLASTOISE
#CATERPIE
#METAPOD
#BUTTERFREE
#WEEDLE
#KAKUNA
#BEEDRILL
#PIDGEY
#PIDGEOTTO
#PIDGEOT
#RATTATA
#RATICATE
#SPEAROW
#FEAROW
#EKANS
#ARBOK
#PIKACHU
#RAICHU
#SANDSHREW
#SANDSLASH
#NIDORAN_FEMALE
#NIDORINA
#NIDOQUEEN
#NIDORAN_MALE
#NIDORINO
#NIDOKING
#CLEFAIRY
#CLEFABLE
#VULPIX
#NINETALES
#JIGGLYPUFF
#WIGGLYTUFF
#ZUBAT
#GOLBAT
#ODDISH
#GLOOM
#VILEPLUME
#PARAS
#PARASECT
#VENONAT
#VENOMOTH
#DIGLETT
#DUGTRIO
#MEOWTH
#PERSIAN
#PSYDUCK
#GOLDUCK
#MANKEY
#PRIMEAPE
#GROWLITHE
#ARCANINE
#POLIWAG
#POLIWHIRL
#POLIWRATH
#ABRA
#KADABRA
#ALAKAZAM
#MACHOP
#MACHOKE
#MACHAMP
#BELLSPROUT
#WEEPINBELL
#VICTREEBEL
#TENTACOOL
#TENTACRUEL
#GEODUDE
#GRAVELER
#GOLEM
#PONYTA
#RAPIDASH
#SLOWPOKE
#SLOWBRO
#MAGNEMITE
#MAGNETON
#FARFETCHD
#DODUO
#DODRIO
#SEEL
#DEWGONG
#GRIMER
#MUK
#SHELLDER
#CLOYSTER
#GASTLY
#HAUNTER
#GENGAR
#ONIX
#DROWZEE
#HYPNO
#KRABBY
#KINGLER
#VOLTORB
#ELECTRODE
#EXEGGCUTE
#EXEGGUTOR
#CUBONE
#MAROWAK
#HITMONLEE
#HITMONCHAN
#LICKITUNG
#KOFFING
#WEEZING
#RHYHORN
#RHYDON
#CHANSEY
#TANGELA
#KANGASKHAN
#HORSEA
#SEADRA
#GOLDEEN
#SEAKING
#STARYU
#STARMIE
#MR_MIME
#SCYTHER
#JYNX
#ELECTABUZZ
#MAGMAR
#PINSIR
#TAUROS
#MAGIKARP
#GYARADOS
#LAPRAS
#DITTO
#EEVEE
#VAPOREON
#JOLTEON
#FLAREON
#PORYGON
#OMANYTE
#OMASTAR
#KABUTO
#KABUTOPS
#AERODACTYL
#SNORLAX
#ARTICUNO
#ZAPDOS
#MOLTRES
#DRATINI
#DRAGONAIR
#DRAGONITE
#MEWTWO
#MEW
`

**Comment by pr0ves** [comment]
You have `autotransfer=false`, that's why it doesn't transfer any pokemon. Set it to `true`

**Comment by Dragunovam** [comment]
Thanks, setting `autotransfer=false` to `true` did resolve the issue. I do think that the comment `# should the bot auto transfer duplicate pokemon` should be changed to reflect the fact that if `true`, it will remove duplicates only if neither iv or cp conditions are met.

**Comment by pr0ves** [comment]
I don't think it's that hard to understand:
Should the bot auto transfer duplicate pokemon? Yes/No (`true`/`false`)
Anyway, closing the issue.
