### ISSUE TITLE
Walking to Pokemons

### ISSUE THREAD

**Issue by daemonfire300** [jabbink/PokemonGoBot#154]
I am currently running the bot and reading the source to get a feeling of what it does. (I am new to Kotlin, but no novice programmer, so not mich of a problem).

One big question, as I am also active on two other bots, does the bot actually walk to Objects ie. Pokemons, because these lines would suggest https://github.com/jabbink/PokemonGoBot/blob/master/src/main/kotlin/ink/abb/pogo/scraper/tasks/CatchOneNearbyPokemon.kt#L47-L49 that the bot teleports to a pokemon as soon as it sees it. Am I right or am I missing something

kind regards

**Comment by jabbink** [comment]
It doesn't teleport, it walks into the range and captures it from that position. No teleporting.
