### ISSUE TITLE
Transfered unique Pokemon

### ISSUE THREAD

**Issue by izecell** [jabbink/PokemonGoBot#155]
Bot transfered unique (non duplicate) Pokemon during cool down period. Lost quite some :-/ Threshold for CP was set to 450.

IN_COOLDOWN_PERIOD
IN_COOLDOWN_PERIOD
Profile update : 302615 XP on LVL 21; 92615/125000 (74,09%) to LVL 22
Dropped 1x ITEM_POKE_BALL
Profile update : 302615 XP on LVL 21; 92615/125000 (74,09%) to LVL 22
Profile update : 302615 XP on LVL 21; 92615/125000 (74,09%) to LVL 22
Looting nearby pokestop 83dfd3d072804185996bb62dee3c40a5.12
IN_COOLDOWN_PERIOD
Destination reached.
Walking to (40.76132, -73.980469) in 0.6456385690420876 steps.
Going to transfer KAKUNA with CP 180
Destination reached.
Going to transfer PONYTA with CP 330
Going to transfer DRAGONAIR with CP 23
Going to transfer DRATINI with CP 12
Getting map of (40.76128161173357, -73.98048326784755)
Going to transfer SHELLDER with CP 337
Going to transfer ZUBAT with CP 354
Looting nearby pokestop 83dfd3d072804185996bb62dee3c40a5.12
Going to transfer CATERPIE with CP 203
IN_COOLDOWN_PERIOD
Going to transfer SANDSHREW with CP 78
Going to transfer RATTATA with CP 301
Walking to (40.76132, -73.980469) in 0.3543614262316974 steps.
Destination reached.
Going to transfer RATTATA with CP 301
Going to transfer RHYHORN with CP 439
Going to transfer RHYHORN with CP 439
Going to transfer VENOMOTH with CP 25
Going to transfer VENOMOTH with CP 25
Going to transfer STARYU with CP 406
Going to transfer STARYU with CP 406
Going to transfer PIDGEY with CP 345
Going to transfer PIDGEY with CP 345
Going to transfer SQUIRTLE with CP 375
Going to transfer SQUIRTLE with CP 375
Going to transfer POLIWAG with CP 142
Going to transfer POLIWAG with CP 142
Going to transfer GOLDEEN with CP 85
Going to transfer GOLDEEN with CP 85
Going to transfer HORSEA with CP 305
Getting map of (40.76130375969275, -73.98048053476161)
Going to transfer HORSEA with CP 305
Going to transfer BELLSPROUT with CP 444
Going to transfer BELLSPROUT with CP 444

Profile update : 305940 XP on LVL 21; 95940/125000 (76,75%) to LVL 22
Walking to (40.757825, -73.982407) in 0.8155203582923343 steps.
Destination reached.
Looting nearby pokestop b8d195d168e44f02b32707250e170e1e.16
Getting map of (40.75781555349698, -73.98242007857701)
IN_COOLDOWN_PERIOD
Looting nearby pokestop b8d195d168e44f02b32707250e170e1e.16
Walking to (40.757825, -73.982407) in 0.18447964162883332 steps.
Destination reached.
Profile update : 305940 XP on LVL 21; 95940/125000 (76,75%) to LVL 22
Profile update : 305940 XP on LVL 21; 95940/125000 (76,75%) to LVL 22
IN_COOLDOWN_PERIOD
Walking to (40.757825, -73.982407) in 0.8155203582923343 steps.
Going to transfer METAPOD with CP 136
Destination reached.
Going to transfer BULBASAUR with CP 142
Getting map of (40.75777780561787, -73.98241888175143)
Going to transfer KOFFING with CP 377
Going to transfer HAUNTER with CP 232
Looting nearby pokestop b8d195d168e44f02b32707250e170e1e.16
IN_COOLDOWN_PERIOD
Going to transfer MACHOP with CP 334
Walking to (40.757825, -73.982407) in 0.18447964162883332 steps.
Destination reached.
Going to transfer MACHOP with CP 334
Getting map of (40.757858146311435, -73.98235716697911)
Going to transfer VOLTORB with CP 172
Going to transfer JIGGLYPUFF with CP 359
Going to transfer VOLTORB with CP 172
Looting nearby pokestop b8d195d168e44f02b32707250e170e1e.16
Going to transfer GEODUGE with CP 325
Going to transfer JIGGLYPUFF with CP 359
IN_COOLDOWN_PERIOD
Going to transfer GEODUGE with CP 325
Going to transfer ABRA with CP 10
Going to transfer ABRA with CP 10
Going to transfer PIKACHU with CP 363
Walking to (40.757825, -73.982407) in 0.8155203582923343 steps.
Destination reached.
Going to transfer PIKACHU with CP 363
Going to transfer PIKACHU with CP 363
Going to transfer MAGMAR with CP 155
Getting map of (40.7577933434101, -73.9823810733118)
Going to transfer MAGMAR with CP 155
Going to transfer SPEAROW with CP 352
Going to transfer MAGMAR with CP 155
Looting nearby pokestop b8d195d168e44f02b32707250e170e1e.16
IN_COOLDOWN_PERIOD
Going to transfer GOLBAT with CP 298
Going to transfer SPEAROW with CP 352
Going to transfer GASTLY with CP 391
Walking to (40.757825, -73.982407) in 0.18447964162883332 steps.
Destination reached.
Going to transfer GASTLY with CP 391
Going to transfer GOLBAT with CP 298
Going to transfer SPEAROW with CP 352
Going to transfer MEOWTH with CP 303
Going to transfer MEOWTH with CP 303
Going to transfer GASTLY with CP 391
Going to transfer GOLBAT with CP 298
Getting map of (40.75784557138717, -73.98236839399134)
Going to transfer PIDGEOTTO with CP 366
Going to transfer PIDGEOTTO with CP 366
Going to transfer MEOWTH with CP 303
Going to transfer GASTLY with CP 391
Going to transfer SLOWPOKE with CP 429
Going to transfer SLOWPOKE with CP 429
Going to transfer PIDGEOTTO with CP 366
Going to transfer MEOWTH with CP 303
Looting nearby pokestop b8d195d168e44f02b32707250e170e1e.16
Going to transfer MAGNEMITE with CP 201
Going to transfer MAGNEMITE with CP 201
Going to transfer SLOWPOKE with CP 429
Going to transfer PIDGEOTTO with CP 366
IN_COOLDOWN_PERIOD
Going to transfer BELLSPROUT with CP 412
Going to transfer BELLSPROUT with CP 412
Going to transfer MAGNEMITE with CP 201
Going to transfer SLOWPOKE with CP 429
Going to transfer RATTATA with CP 268
Going to transfer RATTATA with CP 268
Going to transfer BELLSPROUT with CP 412
Going to transfer MAGNEMITE with CP 201
Going to transfer RATTATA with CP 268
Going to transfer BELLSPROUT with CP 412

**Comment by pr0ves** [comment]
Unfortunately, you used an older version of the program, that's why you got this.
Wait for a new release or build it from source.
