### ISSUE TITLE
Figure out a way to make the bot follow the streets.

### ISSUE THREAD

**Issue by pr0ves** [jabbink/PokemonGoBot#157]
In the present version, the bot travels directly to the destination, as in flying or going through buildings.
We need to find a way to make the bot travel on the streets.
This is what we could do:

1. Given the actual coordinates and the ones of the destination, use the [Google Maps API](https://github.com/googlemaps/google-maps-services-java) or [Project OSMR](https://github.com/Project-OSRM/osrm-backend) to calculate a route and get the KML file.
    * With Google, one would need to generate the API key; for now I don't know how to get the KML directly through the java API, there's a way with the javascript API though.
   * With [Project OSMR](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md), one can get the the file directly through an HTTP request, which would be easier than the Google solution.  
   * Probably there are other possibilities, but for now I found these two.
- Find a way to parse the KML file, that, from what I know, doesn't contain every coordinates of the route but only some; so we'd need to split the rout and get the coordinates of every point.
-  Update the bot coordinates every now and then based on the `speed` property.

Should be "easy".

**Comment by pr0ves** [comment]
Found this site http://yournavigation.org/, which will give the kml if you use the format `http://yournavigation.org/dev/api/route.php?flat=ORIGINLATITUDE&flon=ORIGIN_LONGITUDE&tlat=DESTINATION_LATITUDE&tlon=DESTINATION_LONGITUDE&v=foot&fast=1`.
It has a list of coordinates that describes the route.
Tried two routes for now and the distance between the points is 40m for the first and 100m for the second.

**Comment by alone23** [comment]
+1

**Comment by shilch** [comment]
I will implement this when Web GUI is merged

**Comment by shilch** [comment]
@pr0ves I get 404 error when trying to access the get the url

**Comment by pr0ves** [comment]
Implemented here #532
