### ISSUE TITLE
[SUGGESTION] %CP level (like cp circle)

### ISSUE THREAD

**Issue by CptJackieSparrow** [jabbink/PokemonGoBot#159]
I dunno if it's possible, but i'd like to see a future which can keep pokemons by %CP.
I mean keep pokemon depending on fullness of CP bar.

**Comment by pashorizer** [comment]
Hm. isn't the CP calculated through the IV, Trainer lvl and stuff. Seems like there is no reliant way to calculate max CP unless you restrict yourself to your current Trainer lvl.

**Comment by Forty-Tw0** [comment]
I think it is better to disregard CP and focus on keeping/evolving the pokemon with the best IV. CP does nothing other than show how 'levelled up' the pokemon is? A pokemon with higher IVs will always be better than one at the same CP from what I understand. I think the CP was implemented to convey the idea of IVs to normies.

**Comment by CptJackieSparrow** [comment]
I've set the threshold of IV to 90 percent and CP to 550.
Bot keeps both 750 cp eeve and 550 cp eeve. So you are saying they are almost equals in power as bot kept they both with %90 IV?

**Comment by CptJackieSparrow** [comment]
Ok, checked account, found out i have 250/250 pokemons. Set CP an IV threshold higher

**Comment by jabbink** [comment]
IV is only used when you compile from source fyi

**Comment by jabbink** [comment]
relative cp (max available for your trainer level) has been added for throwing pokemon out.
