### ISSUE TITLE
Bot stops working randomly

### ISSUE THREAD

**Issue by omar972** [jabbink/PokemonGoBot#160]
It works fine, but after a while, it stops working and keeps coming up with these errors.
Screenshot: https://gyazo.com/61de7246f1375f711858559d0e78f12c
Paste: http://pastebin.com/CC8xxCMv

**Comment by pashorizer** [comment]
Yeah, this is a known issue in the PokeAPI. The token expires after an hour or so. Just restart it for now.

**Comment by jabbink** [comment]
Compile from source with latest API and it's fixed.
