### ISSUE TITLE
Compile/Run issue Kotlin 

### ISSUE THREAD

**Issue by MASSV** [jabbink/PokemonGoBot#164]
Getting this when i try to build, run w/e., sorry if Im being stupid, tried gradlew fatjar, gradlew clean build, run, and  --refresh-dependencies clean build. same msg

C:\poke3>gradlew.bat --refresh-dependencies clean build
:clean
:compileKotlin
e: C:\poke3\src\main\kotlin\ink\abb\pogo\scraper\tasks\Release.kt: (9, 1): Class 'Release' must be declared abstract or implement abstract member public abstract fun run(bot: Bot, ctx: Context, settings: Settings): Unit defined in ink.abb.pogo.scraper.Task
e: C:\poke3\src\main\kotlin\ink\abb\pogo\scraper\tasks\Release.kt: (10, 5): 'run' overrides nothing
e: C:\poke3\src\main\kotlin\ink\abb\pogo\scraper\tasks\Release.kt: (11, 44): Unresolved reference: pokebank
e: C:\poke3\src\main\kotlin\ink\abb\pogo\scraper\tasks\Release.kt: (11, 72): Unresolved reference: it
e: C:\poke3\src\main\kotlin\ink\abb\pogo\scraper\tasks\Release.kt: (12, 24): Cannot choose among the following candidates without completing type inference:
@HidesMembers public inline fun <T> Iterable<???>.forEach(action: (???) -> Unit): Unit defined in kotlin.collections
@HidesMembers public inline fun <K, V> Map<???, ???>.forEach(action: (Map.Entry<???, ???>) -> Unit): Unit defined in kotlin.collections
e: C:\poke3\src\main\kotlin\ink\abb\pogo\scraper\tasks\Release.kt: (13, 26): Unresolved reference: it
e: C:\poke3\src\main\kotlin\ink\abb\pogo\scraper\tasks\Release.kt: (13, 56): Unresolved reference: it
:compileKotlin FAILED

FAILURE: Build failed with an exception.

**Comment by wartickler** [comment]
Same here. I'm a dev and want to help out. Kotlin looks badass. Could you share your dev setup so we can get cracking?

**Comment by iamthasasquatch** [comment]
are you running the lastest cuz i dont have a release.kt only a releasepokemon.kt

**Comment by MASSV** [comment]
windows, have elclipse with kotlin plugin

**Comment by iamthasasquatch** [comment]
i am talking about the latest source files not that

**Comment by MASSV** [comment]
This was it, I just cleaned project and recloned, think had old stuff in folder. Thanks

**Comment by wartickler** [comment]
Am I daft for thinking I can dev from Windows?

**Comment by MASSV** [comment]
just make a fresh clone and try again. make sure to have the config file done. worked for me now

**Comment by iamthasasquatch** [comment]
@wartickler https://www.jetbrains.com/idea/
