### ISSUE TITLE
Config not finding longitude

### ISSUE THREAD

**Issue by RovingSpirit** [jabbink/PokemonGoBot#169]
# PTC/Google login credentials
username=xxxxxxx@gmail.com

# Choose plaintext or base64'd password
password=xxxxxx
base64_password=

# Token to login directly
token=
latitude=30
longitude=30
preferred_ball=ITEM_POKE_BALL

## Walking
# Meters per second
speed=2.1

Continued "longitude" not specified error, help!

**Comment by BryanVest** [comment]
Are you meaning to go to egypt? I would try a better longitude latitude

**Comment by RovingSpirit** [comment]
The lat/long were just random integers to test if the length of the lat/long was a problem

**Comment by jabbink** [comment]
You probably have a space behind the `=` or after the number or somewhere.
