### ISSUE TITLE
Bot stucks at one pokemon, no errors

### ISSUE THREAD

**Issue by CptJackieSparrow** [jabbink/PokemonGoBot#170]
Looted pokestop 42c1b038bf40496998f7e8f415f1456f.16: [1xITEM_MAX_POTION, 3xITEM_POKE_BALL]
Profile update : 856090 XP on LVL 25; 296090/340000 (87.09%) to LVL 26
Getting map of (40.7636707795555, -73.97310553891934)
Destination reached.
Dropped 3x ITEM_POKE_BALL
Walking to (40.763659, -73.972644) in 63.31139458909569 steps.
Profile update : 856090 XP on LVL 25; 296090/340000 (87.09%) to LVL 26
Getting map of (40.763658689363346, -73.97293961846653)
Found pokemon EKANS
Looting nearby pokestop 3e5aeda6269a4112b632ed7ab8f748f7.16
Looted pokestop 3e5aeda6269a4112b632ed7ab8f748f7.16, but inventory is full
Profile update : 856140 XP on LVL 25; 296140/340000 (87.10%) to LVL 26
Getting map of (40.76363448173276, -73.97284508895589)
Found pokemon EKANS
Profile update : 856140 XP on LVL 25; 296140/340000 (87.10%) to LVL 26
Destination reached.
Getting map of (40.76364585204646, -73.9725940627532)
Found pokemon EKANS
Looting nearby pokestop 8000e6cfdbe2465095a4ab1185993e86.16
Looted pokestop 8000e6cfdbe2465095a4ab1185993e86.16, but inventory is full
Profile update : 856190 XP on LVL 25; 296190/340000 (87.11%) to LVL 26
Getting map of (40.76363991488611, -73.97260382749246)
Found pokemon EKANS
Profile update : 856190 XP on LVL 25; 296190/340000 (87.11%) to LVL 26
Getting map of (40.763647480231676, -73.97264701270981)
Found pokemon EKANS
Profile update : 856190 XP on LVL 25; 296190/340000 (87.11%) to LVL 26
Getting map of (40.7636922997783, -73.97266407527604)
Found pokemon EKANS
Profile update : 856190 XP on LVL 25; 296190/340000 (87.11%) to LVL 26
Getting map of (40.76365597908866, -73.97261477607454)
Found pokemon EKANS
Profile update : 856190 XP on LVL 25; 296190/340000 (87.11%) to LVL 26
Getting map of (40.76363276811656, -73.97259367469945)
Found pokemon EKANS

**Comment by BryanVest** [comment]
Did you check that you are not full on pokemon? I had the same issue before.

**Comment by AnivaJ** [comment]
You do not have space for any additional pokemon. log in manually to see for yourself. Either get more slots or get rid of useless pokemon, such as golbat, pensir etc regardless of their CP.

**Comment by ToMeRhh** [comment]
I added a message, when encountering a pokemon and the pokebank is full, so I'm guessing you are using the release.
anyways - edit your config file to drop some more pokemons (i.e - add them by name or raise your CP/IV thresholds)
