### ISSUE TITLE
Feature Request: Transfer/Evolve by IV instead of CP

### ISSUE THREAD

**Issue by Forty-Tw0** [jabbink/PokemonGoBot#171]
From what I understand, CP shows the progress of the pokemon to the maximum 'level' at which point they can no longer be powered up. While IVs are the actual stats that determine the quality of a pokemon. For perfect pokemon, I think it would be best to sort by IV quality rather than CP. You can always power up a low CP pokemon with high IVs in the long run, to a be better than a pokemon that simply has high CP.

This video describes what I am saying in a more coherent manner. Simply, I want to transfer/evolve pokemon by their IV%. https://www.youtube.com/watch?v=4Z_dPbWgyMQ

**Comment by ToMeRhh** [comment]
I think that setting the CP to -1,  and IV to your desired IV does what you want :)

**Comment by jabbink** [comment]
This already exists for 2 days in this repo

**Comment by Forty-Tw0** [comment]
What is allows for currently is an IV threshold. It will keep all pokemon over that threshold, resulting in multiple pokemon being kept. If you raise the threshold, it will dump everything below that threshold even if you do not already own one above the thresh hold. There is no way to keep the single best IV pokemon and discard the rest. I have 15+ zubat which are over 80% Iv.
