### ISSUE TITLE
Why does it keep dropping Poke Balls?

### ISSUE THREAD

**Issue by hdubb** [jabbink/PokemonGoBot#173]
in the config.properties file, I have it on -1 which means it should never drop pokeballs right?

preferred_ball=ITEM_POKE_BALL

## Walking
# Meters per second
speed=2.778

## Items drop
# should the bot EVER drop items (true/false)
drop_items=true

# max number of each item that the bot should keep if "drop_items" is enabled
# use -1 in a item to never drop this specific item
item_revive=0
item_max_revive=0
item_potion=0
item_super_potion=0
item_hyper_potion=0
item_max_potion=50
item_poke_ball=-1
item_great_ball=200
item_ultra_ball=200
item_master_ball=50
item_razz_berry=20

**Comment by jabbink** [comment]
Compile from source
