### ISSUE TITLE
newest commits generate Build fail in Main

### ISSUE THREAD

**Issue by cleftfairy** [jabbink/PokemonGoBot#176]
fresh clone fails below. 3 hours ago worked fine (osx 10.11)

$ ./gradlew --refresh-dependencies clean build
:clean
:compileKotlin
e: /Users/user/git/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Main.kt: (81, 31): None of the following functions can be called with the arguments supplied: 
public open fun login(token: String!): RequestEnvelopeOuterClass.RequestEnvelope.AuthInfo! defined in com.pokegoapi.auth.GoogleLogin
public open fun login(username: String!, password: String!): RequestEnvelopeOuterClass.RequestEnvelope.AuthInfo! defined in com.pokegoapi.auth.GoogleLogin
e: /Users/user/git/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Main.kt: (89, 31): Unresolved reference: refreshToken
:compileKotlin FAILED
 
FAILURE: Build failed with an exception.

**Comment by johnnyslt** [comment]
I think this broke it : https://github.com/jabbink/PokemonGoBot/commit/dfd9e974a9f6a0685ddc018c5698faca589e45f3

**Comment by PancakeZik** [comment]
Just revert the main.tk file, and it should work, keeping the others

**Comment by d-moos** [comment]
Hi,

You can replace 
            GoogleLogin(http).login() with 
            GoogleLogin(http).login(username, password)

and GoogleLogin(http).refreshToken(token) with GoogleLogin(http).login(token)


cheers!

**Comment by Loewe1000** [comment]
Or you can change 
`compile 'com.github.Grover-c13:PokeGOAPI-Java:Master-SNAPSHOT'`
to
`compile 'com.github.Grover-c13:PokeGOAPI-Java:Development-SNAPSHOT'`
in the *build.gradle* file and then execute `gradlew --refresh-dependencies clean build`

**Comment by jabbink** [comment]
fixed
