### ISSUE TITLE
build fails dup of #176

### ISSUE THREAD

**Issue by blamorph** [jabbink/PokemonGoBot#178]
C:\Users\Michiel\Desktop\java_bot_src>gradlew run
:compileKotlin
e: C:\Users\Michiel\Desktop\java_bot_src\src\main\kotlin\ink\abb\pogo\scraper\Ma
in.kt: (81, 31): None of the following functions can be called with the argument
s supplied:
public open fun login(token: String!): RequestEnvelopeOuterClass.RequestEnvelope
.AuthInfo! defined in com.pokegoapi.auth.GoogleLogin
public open fun login(username: String!, password: String!): RequestEnvelopeOute
rClass.RequestEnvelope.AuthInfo! defined in com.pokegoapi.auth.GoogleLogin
e: C:\Users\Michiel\Desktop\java_bot_src\src\main\kotlin\ink\abb\pogo\scraper\Ma
in.kt: (89, 31): Unresolved reference: refreshToken
:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 13.303 secs

**Comment by d-moos** [comment]
[duplicate issue](https://github.com/jabbink/PokemonGoBot/issues/176)
I posted a solution in the other issue-thread.

**Comment by pashorizer** [comment]
Yeah apparently the new PokeGOAPI is in the `development` branch 

Can anyone resolve the method `useItem` in `CatchablePokemon.kt`?

**Comment by d-moos** [comment]
It's also only available in the development branch of the PogoAPI
https://github.com/Grover-c13/PokeGOAPI-Java/blob/c1df2e1219657147ac492d0cce0d3d45fe22f228/src/main/java/com/pokegoapi/api/map/pokemon/CatchablePokemon.java (line 381)
