### ISSUE TITLE
option to end bot at Encounter failed with result: POKEMON_INVENTORY_FULL 

### ISSUE THREAD

**Issue by cleftfairy** [jabbink/PokemonGoBot#179]
When this happens, the bot just keeps merrily along which generates 5 second apart or so attempts to encounter the same pokemon - seems like it could trigger an anti-ban. I'd prefer the bot exit at that point or have some way to dump pokemon. I reached level 22 and caught too many pokemon over cp 400...

**Comment by ToMeRhh** [comment]
you're right that there's no reason to continue encountering pokemons, but I think the right thing to do is to move to 'walk mode'.

obviously the solution for full pokebank is simply to raise the CP/IV threshold :)
