### ISSUE TITLE
Google Login

### ISSUE THREAD

**Issue by CptJackieSparrow** [jabbink/PokemonGoBot#18]
Couldn't manage to sign in with google account.

**Comment by jabbink** [comment]
I do not advise using bots on Google accounts as they are not as disposable as PTC accounts, if you want to really use a Google account, change the `PTCLogin(http)` to `GoogleLogin(http)` and recompile it yourself (but don't blame anyone that Niantic might eventually ban your legitimate Google account).

**Comment by CptJackieSparrow** [comment]
Well I respect that, but in my country, it's not released and we only can sign in via Google account.
I have another gmail smurf account that i can test this, thank you for the caution! :)

**Comment by SwipeX** [comment]
I think we can close this.

**Comment by jabbink** [comment]
Yeah, it has been implemented by @SwipeX and compiled version v0.2.0 contains it.
