### ISSUE TITLE
Early Dev Releases? ( ͡° ͜ʖ ͡°)	

### ISSUE THREAD

**Issue by RaeneDev** [jabbink/PokemonGoBot#180]
Sorry for asking, but would It be possible if we could push out a developer/bleeding release nightly, possibly on a  different repository or somewhere? Or is it possible to do it ourselves(Never actually used GitHub before seeing this so I'm not aware, but It seems this would work. If there is a way, would someone mind explaining this for me?)?

To me I believe this could help find and squash bugs faster for those who are testing can report anything they find and it can be fixed/noted about before a full release and solved, faster than currently.

Now I'm pretty sure no one likes to be rushed, especially with code. At least I don't... but I think pushing a small Developer/testing release nightly or daily around a certain time each day would be fun. These wouldn't be full releases so it doesn't seem like it would be stressful to me personally and these would just releases to see the progress/search for bugs. 
These releases would be noted that its not a full release, but only meant for testing purposes so those that want a more stable release to download do not download an unstable release on accident.

**Comment by megatixos** [comment]
You can test the dev release on your own, downloading the source and executing.
1) download the zip
2) Run from terminal/cmd :gradlew build (It should download the dependencies)
3) Rename ./config.properties.template to ./config.properties
4) Modify config.properties as you please
5) To run the bot directly from console run gradlew run

**Comment by RaeneDev** [comment]
@megatixos Thank you so much! I love testing unstable releases.

**Comment by RaeneDev** [comment]
@megatixos Sorry to bother.. but I followed your instructions and I came across a problem. Could you possibly point me towards some directions to fix this?

C:\Users\Admin\Desktop\PG2\PokemonGoBot-master>gradlew run
:compileKotlin
e: C:\Users\Admin\Desktop\PG2\PokemonGoBot-master\src\main\kotlin\ink\abb\pogo\scraper\Main.kt: (81, 31): None of the following functions can be called with the arguments supplied:
public open fun login(token: String!): RequestEnvelopeOuterClass.RequestEnvelope.AuthInfo! defined in com.pokegoapi.auth.GoogleLogin
public open fun login(username: String!, password: String!): RequestEnvelopeOuterClass.RequestEnvelope.AuthInfo! defined in com.pokegoapi.auth.GoogleLogin
e: C:\Users\Admin\Desktop\PG2\PokemonGoBot-master\src\main\kotlin\ink\abb\pogo\scraper\Main.kt: (89, 31): Unresolved reference: refreshToken
:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.966 secs

C:\Users\Admin\Desktop\PG2\PokemonGoBot-master>

**Comment by RaeneDev** [comment]
Read around and found a fix.

**Comment by yashendra2797** [comment]
@RaeneDev Relevant XKCD: [Wisdom of the Ancients](https://xkcd.com/979/)
