### ISSUE TITLE
Some Colors?

### ISSUE THREAD

**Issue by julienkessels** [jabbink/PokemonGoBot#185]
could we have some colors? 🎯

**Comment by RaeneDev** [comment]
Next release will have some:) Green on Looted pokestop and Yellow for dropping/using items. 

Personally I think adding an option to remove all three, "Getting map of" "walking to" "Destination Reached" would also be nice as these are showing pretty fast.

**Comment by julienkessels** [comment]
yea ! i think so too!
and a color for caught pokemons ;)

**Comment by RaeneDev** [comment]
These are in green too I believe. I just saw red being used for already looted pokestops. Didn't see it before but I guess It also adds them to a blacklist for 5 minutes. I was thinking of making a GUI possibly but someone is already working on one. 
Personally think having blue for pokestops, green for caught pokemon, and yellow for used/dropped items and transferred pokemon.
