### ISSUE TITLE
windows compile error

### ISSUE THREAD

**Issue by qifbox** [jabbink/PokemonGoBot#189]
**Steps to reproduce:**
when i try to compile on windows, got an error. Name of the file is too long.
how can i go trhow this. can u help me plz?

(in not really good talking inglish, but i understand very well. sorry for some bad words)

error
--
:PokeGOAPI-Java:generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':PokeGOAPI-Java:generateProto'.
> java.io.IOException: Cannot run program "C:\Users\my name\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protoc\3.0.0-beta-3\7fd402d66301a053e4d8018e8f91da03839e8f9c\protoc-3.0.0-beta-3-windows-x86_32.exe": CreateProcess error=206, name of the file is too long

**Comment by jabbink** [comment]
Did you do step 2 from the README?

`git submodule update --init --recursive`

**Comment by qifbox** [comment]
yes sir. i did it on the git shell. is not there?

**Comment by jabbink** [comment]
See edit in comment

**Comment by qifbox** [comment]
thank u sir.
already running it
