### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by pvase666** [jabbink/PokemonGoBot#196]
C:\\Desktop\PokemonGoBot-develop>gradlew --refresh-dependencies clean build

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\\Desktop\PokemonGoBot-develop\build.gradle' line: 54

* What went wrong:
A problem occurred evaluating root project 'pogo.scraper'.
> Could not resolve all dependencies for configuration ':compile'.
   > Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 30.748 secs

**Comment by Messna** [comment]
Try to run `git submodule update --init --recursive`

**Comment by TheMattRay** [comment]
Getting this with the latest:

:build
:PokeGOAPI-Java:sourcesJar
:PokeGOAPI-Java:assemble
:PokeGOAPI-Java:checkstyleMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':PokeGOAPI-Java:checkstyleMain'.
> Unable to create a Checker: configLocation {/Users/themattray/Documents/Code/PokemonGoBot/config/checkstyle.xml}, classpath {/Users/themattray/Documents/Code/PokemonGoBot/lib/PokeGOAPI-Java/build/classes/main:/Users/themattray/Documents/Code/PokemonGoBot/lib/PokeGOAPI-Java/build/resources/main}.

**Comment by mroge009** [comment]
Getting same error as well.

Could not resolve all dependencies for configuration ':compile'.
Configuration with name 'default' not found.

**Comment by iamthasasquatch** [comment]
Messna suggested the solution you need to run
git submodule update --init --recursive

and possibly to make sure everything else is updated
gradlew --refresh-dependencies clean build

**Comment by pvase666** [comment]
Thanks. I got it. Working well/
