### ISSUE TITLE
Looted pokestop +0 XP

### ISSUE THREAD

**Issue by TechnoDaft** [jabbink/PokemonGoBot#198]
**Description:**
NOT soft-banned can log in fine with nox and use the pre-compiled bot without issues
not claiming pokestops

**Steps to reproduce:**
IDK i just compiled and ran and it's doing this

**Expected behavior:**
grab pokestops and catch pokemon

**Actual behavior:**
24 Jul 10:18:36: Walking to (40.764916, -73.972457) in 0.859606584731848 steps.
24 Jul 10:18:36: Destination reached.
24 Jul 10:18:40: Getting map of (40.76489610174157, -73.97245565656178)
24 Jul 10:18:40: Looting nearby pokestop 76a550ce84994d71955939e2ec21ac06.12
24 Jul 10:18:40: Looted pokestop 76a550ce84994d71955939e2ec21ac06.12; +0 XP: [] 
![error](https://cloud.githubusercontent.com/assets/20615768/17084295/0ed32e42-5188-11e6-8d9d-f32072ed43b6.png)

**Stacktrace (If it's a crash):**
No Crash

**Version:**
Latest Source

**Comment by PancakeZik** [comment]
I noticed in your log the same problem that I have in mine sometimes, in which it just continues to do very small amount of "walking", of less than 1 step.

**Comment by CosmoRing** [comment]
It looks to be trying to loot the same pokestop over and over again

**Comment by mroge009** [comment]
Soft banned

**Comment by TechnoDaft** [comment]
I am not soft banned I can get pokestops/catch pokemon on nox and the pre-compiled works no problem

**Comment by TechnoDaft** [comment]
well figured it out...I had to force close ALL java instances and restarted it and it worked

**Comment by jabbink** [comment]
Weird that it doesn't skip this already.

Can you please verify that the time of your computer is almost correct?

**Comment by TechnoDaft** [comment]
ya i'm 100% my time is correct {and updates with windows.time} I'm also using windows 10 but the problem {i have duplicated} is when i close cmd java stays running in the background and i have to force close it and restart the cmd in order for it to work properly {which could be because i made multiple bat/cmd files for my 3 clients and made a .bat to open them all with 1 click instead of having to start each 1 manually}

Shortcut.cmd
start cmd /k Call "C:\pogobot\Valor\start.cmd"
start cmd /k Call "C:\pogobot\Instinct\start.cmd"
start cmd /k Call "C:\pogobot\Mystic\start.cmd"

start.cmd
gradlew run

**Comment by jabbink** [comment]
Ah, having it run in the background, and then start it again will make the locations of the 2 instances on the same account not match up, so you get softbanned
