### ISSUE TITLE
Building fails on Windows

### ISSUE THREAD

**Issue by ioreskovic** [jabbink/PokemonGoBot#201]
Due to adding PokeGOAPI as a subproject, building everything with gradlew fatjar fails due to invoking Windows MAX_PATH limitation

```

$ ./gradlew fatjar
:PokeGOAPI-Java:extractIncludeProto UP-TO-DATE
:PokeGOAPI-Java:extractProto UP-TO-DATE
:PokeGOAPI-Java:generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':PokeGOAPI-Java:generateProto'.
> java.io.IOException: Cannot run program "C:\Users\Lopina\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protoc\3.0.0-beta-3\71e76cad4f9b30aab172c44035d343c5bab47815\protoc-3.0.0-beta-3-windows-x86_64.exe": CreateProcess error=206, The filename or extension is too long

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.53 secs

```

**Comment by CosmoRing** [comment]
See: #189

**Comment by Lenovotro** [comment]
@CosmoRing @jabbink If I clone the repo any higher, it has a hard time finding the Java SDK.

**Comment by jabbink** [comment]
Sorry, I can't fix NTFS and the maximum file name length :/

I've seen this issue many times before, with Eclipse, which also uses reaaaaally long filenames

**Comment by Stepan222** [comment]
This issue might be arising because of long file name. You can try to rename the file or move it into shorter path with the help of **Long Path Tool**. I have resolves many such issues with this tool.
