### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by alawing** [jabbink/PokemonGoBot#202]
I dont know why cannot I build through the README file, could you help me?

$ ./gradlew assemble
:PokeGOAPI-Java:extractIncludeProto FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':PokeGOAPI-Java:extractIncludeProto'.

Could not expand ZIP '/home/ec2-user/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protobuf-java/3.0.0-beta-3
/ed8c2f9a63cfa770292f8173fd0172bdaa014fe3/protobuf-java-3.0.0-beta-3.jar'.
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.46 secs

**Comment by iamthasasquatch** [comment]
did you follow step 2?
2. Run git submodule update --init --recursive

**Comment by jabbink** [comment]
>Could not expand ZIP

possibly the download of that jar failed (corrupt download). Re-download it (clear the gradle cache) and please try again

**Comment by alawing** [comment]
I got it. My JDK on amazon ec2 is 1.7.0 openjdk

After I installed 1.8.0 , build success
