### ISSUE TITLE
new updates build fail

### ISSUE THREAD

**Issue by qifbox** [jabbink/PokemonGoBot#203]
error
--
:compileKotlin
e: C:\PokemonGoBot\src\main\kotlin\ink\abb\pogo\scraper\tasks\HatchEggs.kt: (35, 55): Unresolved reference: queryHatchedEggs
e: C:\PokemonGoBot\src\main\kotlin\ink\abb\pogo\scraper\tasks\HatchEggs.kt: (37, 41): Cannot infer a type for this parameter. Please specify it explicitly.
e: C:\PokemonGoBot\src\main\kotlin\ink\abb\pogo\scraper\tasks\HatchEggs.kt: (37, 48): Cannot infer a type for this parameter. Please specify it explicitly.
e: C:\PokemonGoBot\src\main\kotlin\ink\abb\pogo\scraper\tasks\HatchEggs.kt: (39, 67): Unresolved reference: getPokemonById
:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

**Comment by bmays** [comment]
Try the second step of the guide again: `Run git submodule update --init --recursive`

**Comment by qifbox** [comment]
i did it again and same results

**Comment by alone23** [comment]
+1

```
:PokeGOAPI-Java:checkstyleMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':PokeGOAPI-Java:checkstyleMain'.
> Unable to create a Checker: configLocation {/Volumes/Macintosh HD/Users/John/GitProjects/PokemonGoBot/config/checkstyle.xml}, classpath {/Volumes/Macintosh HD/Users/John/GitProjects/PokemonGoBot/lib/PokeGOAPI-Java/build/classes/main:/Volumes/Macintosh HD/Users/John/GitProjects/PokemonGoBot/lib/PokeGOAPI-Java/build/resources/main}.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 54.194 secs
```

**Comment by qifbox** [comment]
how i did to resolve
--
delete the git, clone again to hard drive, run the --init stuff
compile.

its working

**Comment by Scoboose** [comment]
Installed the new JDK and it built fine for me

**Comment by jabbink** [comment]
@alone23 at the time of your writing I think the Readme still stated to run with `-x check` because of that issue.

That has since been removed and you can run it without a skip of the stylechecker.
