### ISSUE TITLE
Egg Hatch - error report

### ISSUE THREAD

**Issue by PancakeZik** [jabbink/PokemonGoBot#204]
Hi,

Just wanted to report that when eggs hatch, an error message is shown, but the bot continues functioning and starts to hatch another egg, so it's more aesthetically important than functional.
Here is the error message.

> Exception in thread "Thread-207" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
>         at java.util.ArrayList.rangeCheck(ArrayList.java:653)
>         at java.util.ArrayList.get(ArrayList.java:429)
>         at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
>         at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse.getExperienceAwarded(GetHatchedEggsResponseOuterClass.java:292)
>         at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:73)
>         at ink.abb.pogo.scraper.tasks.HatchEggs.run(HatchEggs.kt:35)
>         at ink.abb.pogo.scraper.Bot.task(Bot.kt:83)
>         at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.invoke(Bot.kt:77)
>         at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.invoke(Bot.kt:21)
>         at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18) 

I'm on the latest development build

**Comment by stirante** [comment]
Yup, we're waiting for PR to be accepted into POGOProtos repo. Change in GetHatchedEggsResponse pokemonid from uint64 to fixed64 and it should work.

**Comment by jabbink** [comment]
Specifically this one

https://github.com/AeonLucid/POGOProtos/pull/54

Thanks @stirante
