### ISSUE TITLE
build issue windows & linux

### ISSUE THREAD

**Issue by blamorph** [jabbink/PokemonGoBot#211]
after updating module I get:

C:\Users\Michiel\Desktop\java_bot_src>gradlew --refresh-dependencies clean build

:clean UP-TO-DATE
:PokeGOAPI-Java:clean
:PokeGOAPI-Java:extractIncludeProto
:PokeGOAPI-Java:extractProto UP-TO-DATE
:PokeGOAPI-Java:generateProto
:PokeGOAPI-Java:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':PokeGOAPI-Java:compileJava'.
> Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_91
contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

That dir points to a valid JRE installation. I run into the same issue on Linux..

**Comment by tomtobac** [comment]
same problem here

**Comment by Cypherke** [comment]
check if you have a JAVA_HOME set as a system environment variable and make sure it points to your JDK folder. close command prompt reopen... retry

**Comment by Emuuung** [comment]
I tried reinstalling JDK, not JRE and it worked for me.

**Comment by Scoboose** [comment]
Installed the new JDK and it worked for me

**Comment by blamorph** [comment]
Installed JDK and worked here too.
