### ISSUE TITLE
New build will not run if google token is saved in config

### ISSUE THREAD

**Issue by Scoboose** [jabbink/PokemonGoBot#212]
> D:\PokemonGoBot>gradlew run
> :PokeGOAPI-Java:extractIncludeProto UP-TO-DATE
> :PokeGOAPI-Java:extractProto UP-TO-DATE
> :PokeGOAPI-Java:generateProto UP-TO-DATE
> :PokeGOAPI-Java:compileJava UP-TO-DATE
> :PokeGOAPI-Java:processResources UP-TO-DATE
> :PokeGOAPI-Java:classes UP-TO-DATE
> :PokeGOAPI-Java:jar UP-TO-DATE
> :compileKotlin UP-TO-DATE
> :compileJava UP-TO-DATE
> :processResources UP-TO-DATE
> :classes UP-TO-DATE
> :run
> Display Keepalive Coordinates setting ("display_keepalive") not specified, defaulting to "true".
> 24 Jul 14:19:18: Logging in to game server...
> Exception in thread "main" java.lang.IllegalStateException: if (token.contains("pokeàeshToken(token)
>         } must not be null
>         at ink.abb.pogo.scraper.MainKt.main(Main.kt:86)
> :run FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':run'.
> > Process 'command 'C:\Program Files (x86)\Java\jdk1.8.0_101\bin\java.exe'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 4.422 secs

If i remove my token form the config and do the whole google devices step it logs in and runs fine.  It was working fine before I updated.

**Comment by jabbink** [comment]
The displayed token is incorrect, fix incoming with #216

**Comment by Scoboose** [comment]
Thanks!  Is it possible to have it put the token in the config for us when one is generated?
