### ISSUE TITLE
Please add a config in order to use the 'Curve Ball' all the time.

### ISSUE THREAD

**Issue by chriszhangz** [jabbink/PokemonGoBot#214]
**Description:**
I don't want bot use the great ball or matser ball so I set  desired_catch_probability to zero.
Then I noticed that all got xp from caught pokemon was 200xp not 210xp that means the bot never use the 'Curve Ball'.

**Expected behavior:**
So can we set a variable in config file to make the bot using ‘Curve Ball' all the time? Thanks

**Version:**
cloned the latest version

**Comment by pilotchute** [comment]
Quick fix, in file PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/util/pokemon/CatchablePokemon.kt
change line 58 from:
var needCurve = false
to:
var needCurve = true

It's dirty, but it should work.

**Comment by chriszhangz** [comment]
@pilotchute thanks bro,I will have a try.
