### ISSUE TITLE
Skipping unwated Pokemon

### ISSUE THREAD

**Issue by classicalDonkey** [jabbink/PokemonGoBot#215]
Would it be possible to have a setting which you can tell it to miss set pokemon. For example I dont need any more Dowzees at this point so would like it not to catch them.

**Comment by Forty-Tw0** [comment]
You could set obligatory_transfer to catch and release (free xp!), but I suppose it would be a waste of a pokeball.

**Comment by classicalDonkey** [comment]
How do you do that? I dont care about wasting balls as I get so many of them anyway.

**Comment by Forty-Tw0** [comment]
In the config.properties, comma seperated list
# list of pokemon you always want to trancsfer regardless of CP
obligatory_transfer=DROWZEE,PIDGEY,ZUBAT

**Comment by classicalDonkey** [comment]
Ok I have seen that but I just want to skip the pokemon not catch it and transfer it (getting the candy).  In real life I can just not try to catch the pokemon, and walk pass it!

**Comment by blamorph** [comment]
why would you not want the free xp ? :)

**Comment by classicalDonkey** [comment]
Its not the XP, I dont need to collect the candies for that pokemon!  So like Forty-Tw0 said it is using a poke ball to catch a pokemon that I am just getting rid of anyway, so why not just have the option to just not try to catch it.

**Comment by Forty-Tw0** [comment]
To forgo XP in an attempt to look like a real player who might not bother catching 100% of the pokemon they see. Though the bot already has the capability of catching multiple pokemon per second, I hope Niantic doesn't check for things like that.

**Comment by classicalDonkey** [comment]
You have a point there, and when player trading comes it is not going to matter about the number of candies I have...

**Comment by jabbink** [comment]
Jar has been made, also why close this issue? You don't want the feature anymore?
