### ISSUE TITLE
Cant compile (the current version)

### ISSUE THREAD

**Issue by megatixos** [jabbink/PokemonGoBot#217]
C:\Users\makos\Desktop\PokemonGOBOTS\PokemonGOJABBINK>gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\makos\Desktop\PokemonGOBOTS\PokemonGOJABBINK\build.gradle' line: 54

* What went wrong:
A problem occurred evaluating root project 'pogo.scraper'.
> Could not resolve all dependencies for configuration ':compile'.
   > Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.24 secs

Any help?

**Comment by jabbink** [comment]
Did you do step 2 of the readme?

**Comment by Cypherke** [comment]
check if you have a JAVA_HOME set as a system environment variable and make sure it points to your JDK folder. close command prompt reopen... retry

or reinstall JDK may also work

**Comment by megatixos** [comment]
What are my options in case i dont have installed the GIT bash @jabbink ? (because no git bash = no git command) i have to download it or there is another way using only cmd?

**Comment by Lenovotro** [comment]
When I try to do step two, there's no git repository.

**Comment by jabbink** [comment]
You'd only need git, not the git bash package, but I strongly advise it.

Also indeed exact same error as #196 which was the git submodule thingy

**Comment by jabbink** [comment]
@Lenovotro, cd into the directory that you cloned. Don't download as zip from github.

**Comment by Lenovotro** [comment]
@jabbink I did that. unzipped PokemonGoBot. I then run git submodule update --init --recursive. And it still says not a git repository.
