### ISSUE TITLE
[SUGGESTION] Config to stay in predefined area

### ISSUE THREAD

**Issue by MrJokerer** [jabbink/PokemonGoBot#220]
Would love to be able to set coords for bot to stay in.  Such as staying in a university or park.  One way I could see doing it is a simple top left and bottom right coord set.  Just an idea

**Comment by Mixone-FinallyHere** [comment]
Set allow leave are to false and reduce number of cells

**Comment by jabbink** [comment]
Has since this issue was opened been added.
