### ISSUE TITLE
Can not compile because the ctx.api object fields are private

### ISSUE THREAD

**Issue by shilch** [jabbink/PokemonGoBot#225]
![photo](https://cloud.githubusercontent.com/assets/11890358/17086051/96e4a6d4-51e8-11e6-8e6d-9adb48dfe4fc.png)

**Comment by pr0ves** [comment]
You're using IntelliJ, right?
It does the same to me, it's probably because it recognizes the code as java. Kotlin can call private variables if there are the getter and setter of that variable, like `foo.bar` instead of `foo.getBar()`
Anyway closing because it's not a problem of the bot.

**Comment by shilch** [comment]
Ok, but how can I run the bot now?

**Comment by pr0ves** [comment]
Do you run it directly from IntelliJ?
Don't do that, open a terminal instead, go to the folder of the project and run `gradlew run`

**Comment by shilch** [comment]
Yes, thank you it is working now

**Comment by CosmoRing** [comment]
Ok, does anyone know how to fix this error on Intellij? I know how to compile right but i want to help develop but it's hard with all the errors. The auto-complete isn't even working because of this so i spend to much time trying to guess.

**Comment by shilch** [comment]
Facing this problem too

**Comment by CosmoRing** [comment]
@shilch Install Lombok plugin on intellij

**Comment by shilch** [comment]
Thanks @CosmoRing
