### ISSUE TITLE
glitch?

### ISSUE THREAD

**Issue by dynamo21uk** [jabbink/PokemonGoBot#227]
**Description:**
[Short description of the issue observed. If this ia feature request you can modify the template as required.]
just tried the new release and it keeps saying getting map of ..................

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]

**Expected behavior:**
[What should happen?]

**Actual behavior:**
[What actually happens]

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
[The version of the lib you used]

**Comment by dynamo21uk** [comment]
![image](https://cloud.githubusercontent.com/assets/20616186/17086173/5e1c3a1a-51e3-11e6-930b-ee8397bc0897.png)

**Comment by Forty-Tw0** [comment]
I see nothing wrong, are there any pokemon in the area? I see your bag is 241/250 as well.

**Comment by dynamo21uk** [comment]
its Santa Monica pier so i pesume yes there is

**Comment by dynamo21uk** [comment]
coompletely my bad sorted now...
