### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by megatixos** [jabbink/PokemonGoBot#234]
Example in the code it has: val IV = it.getIvPercentage()
what other things can i get from "it"? i have seen it can provide us many things (like getiv, getnickname,  getpokecoins etc..) and i want to learn if they are somewhere written all the getters together (actually im searching the stamina,defense,attack getters of a pokemon (i tried it.pokemonId.getstamina() but there is nothing like that.)

**Comment by jabbink** [comment]
`it` is the shorthand name for the object in streams.

For example if you have a `List<Pokemon>` and you do a `forEach`, `it` is of type `Pokemon`.

It's a Kotling thing.

**Comment by Forty-Tw0** [comment]
Kotlin is weird. "it" seems to be similar to C for each.

**Comment by jabbink** [comment]
Yeah, an alternative is 

```kotlin
val aLongList = emptyList<Pokemon>()
aLongList.forEach { aShortPokemonItem ->
  println(aShortPokemonItem)
}
```

instead of `it`

**Comment by megatixos** [comment]
So what can i do with this? i mean how do you know there exists a getiv function? where does it grabs them i want to see all the functions can i?

**Comment by jabbink** [comment]
>i want to see all the functions can i?

Most IDE's allow you to press Ctrl+Space and it shows you a list
