### ISSUE TITLE
AutoTransfer explanation

### ISSUE THREAD

**Issue by Pepsai** [jabbink/PokemonGoBot#237]
**Description:**
Im a bit confused, and it can be to others as well. The "autotransfer=true" in the config file, does it transfer the lowest CP duplicate? Or does it just transfer the newst caught pokemon?

**Comment by Forty-Tw0** [comment]
Use sort_by_iv=true  to prioritise high IVs over high CP
If the pokemon's IV is under transfer_iv_threshold it will be transferred
If the pokemon's CP is under transfer_cp_threshold it will be transferred

**Comment by Pepsai** [comment]
And what does IV percentage means? Im a bit confused about that as well.
Is there an option to just keep the best? And transfer the worst CP?

**Comment by Forty-Tw0** [comment]
IVs are 3 hidden values which are 0-15, they are added to a pokemon's base stats and do not change. 80% IV means the pokemon has 0.8*(15+15+15) more stats than a pokemon with 0% IV. If you just want to keep the highest CP pokemon use these settings:

sort_by_iv=false
transfer_iv_threshold=-1
transfer_cp_threshold=-1

To keep all pokemon over 420CP:


sort_by_iv=false
transfer_iv_threshold=-1
transfer_cp_threshold=420

**Comment by celsian** [comment]
It appears that no Pokemon are being transferred at all with the latest build. My settings:

```
autotransfer=true
sort_by_iv=true
transfer_iv_threshold=80
transfer_cp_threshold=-1
```

**Comment by russr123** [comment]
if i want it to keep the top 3 of each based on highest CP what would my settings be?

**Comment by jabbink** [comment]
```
# minimum amount of pokemon type to keep
keep_pokemon_amount=3
```

**Comment by Pepsai** [comment]
Also is the bot evolving the best IV or CP Pokemon you have? Or does it not evolve at all?

**Comment by jabbink** [comment]
No evolving at all atm.
