### ISSUE TITLE
Google token error.

### ISSUE THREAD

**Issue by Agora0129** [jabbink/PokemonGoBot#238]
**Description:**
I have to keep redoing the device add into google for it to work.

**Steps to reproduce:**

1. Enter in device code.
2. Erase token and then try again.

**Expected behavior:**
Logs in fine without needing to enter device

**Actual behavior:**
Throws an exception

**Stacktrace (If it's a crash):**
Exception in thread "main" java.lang.IllegalStateException: if (token.contains("poke…eshToken(token)
        } must not be null
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:90)

**Version:**
0.4.0

**Comment by Forty-Tw0** [comment]
You used the wrong/invalid token, don't use the huge token. Use the one on the line: Logged in as __  with token ___

**Comment by Agora0129** [comment]
i don't see any other field that has a token in the properties file? Is it somewhere else?

**Comment by li24yang75** [comment]
Thanks @Forty-Tw0 . 
I know how to solve this now. @Agora0129 
When you first time use google.com/device log in the bot, there is token shows in the cmd. it is like: Logged in as __ with token ___ .

The Token is very short. You need to write this short token into config.properties files at "token =" field manually.

Then next time you can log in without erasing token or inputing device code again.
