### ISSUE TITLE
Build Failing (dev)

### ISSUE THREAD

**Issue by RaeneDev** [jabbink/PokemonGoBot#240]
Previously, I was running fine but now when trying to build, I'll start with 
gradlew --refresh-dependencies clean build
to check and make sure there isn't an API update. This throws an error..

C:\Users\Admin\Desktop\PG2\PokemonGoBot-develop>gradlew --refresh-dependencies clean build

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Admin\Desktop\PG2\PokemonGoBot-develop\build.gradle' line: 71

* What went wrong:
A problem occurred evaluating root project 'pogo.scraper'.
> Could not resolve all dependencies for configuration 'detachedConfiguration3'.
   > Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.912 secs

**Comment by Forty-Tw0** [comment]
Same issue as #231 
Fix is #232

**Comment by RaeneDev** [comment]
Thanks! Thought it was something I was doing incorrectly.
