### ISSUE TITLE
[BUG] Failed to put egg in incubator infinite loop

### ISSUE THREAD

**Issue by ChiIIerr** [jabbink/PokemonGoBot#243]
The error message: "Failed to put egg in incubator; error: ERROR_POKEMON_ALREADY_INCUBATING" keeps filling my logs every heartbeat. I'm fine with it erroring, just that I don't think it needs to keep retrying more than 3 times.

http://i.imgur.com/hpyNtTh.png

**Comment by jabbink** [comment]
Fixed already

**Comment by ErusPenates** [comment]
Pokemon Go Bot v0.4.1 fix
