### ISSUE TITLE
[BUG] display_pokestop_name=false is not connecting right with the json config file

### ISSUE THREAD

**Issue by ChiIIerr** [jabbink/PokemonGoBot#244]
My config file has the toggle set to false whereas the json file has it set to true after starting it. Seems like they're not connected just right.

**Comment by infinityshurik** [comment]
"shouldDisplayPokestopName" : false on my 0.4.1 configuration JSON, yet it still displays the names of pokestops.

**Comment by capalex65** [comment]
Odd thing is, with the JSON config having it disabled, it displays their name when walking to them, but their ID when looting it, and the subsequent result message.

**Comment by andredp** [comment]
There are 2 different settings in the JSON:

- shouldDisplayWalkingToNearestUnused
- shouldDisplayPokestopName

The first one is the one forcing the name of the Pokestop that you're walking to being shown.
The second is for when you loot the Pokestop.

**Comment by jabbink** [comment]
Fixed as that pr was reverted again
