### ISSUE TITLE
[BUG] Fatal error on start - Can't run the bot

### ISSUE THREAD

**Issue by Evuse** [jabbink/PokemonGoBot#247]
I was running like a charm the other versions, but on this new 0.4.1 i got serious problems

1. i start the bot with the cmd: java -jar pogo.scraper-all-0.4.1.jar
2. i get a long error and bot don't start

Here you are the complete error:
[https://gist.github.com/Evuse/39d9aace67a9f11c1d868810b0fd06d8]

Thanks for your time and your knowledge.

**Version:**
[0.4.1]

**Comment by Lenovotro** [comment]
#245 known.

**Comment by jabbink** [comment]
Make sure your config contains a valid `latitude` and `longitude`

Your current config contains no location at all

**Comment by jabbink** [comment]
@Lenovotro "known" as in incorrect values in the config, yes.

**Comment by Evuse** [comment]
I have the same config as the 0.4 and 0.3. Latitude and logitude setted:

# Token to login directly
token=
latitude=45.45203287279336
longitude=9.175005555152893

Any ideas?

**Comment by Forty-Tw0** [comment]
My token was expired/bad, try logging in with password.

**Comment by jabbink** [comment]
Are you sure that config file is in the correct directory? Because that stacktrace doesn't lie, it literally says that it tried to convert empty text to a number on line 60 of Main.kt, which is the latitude

https://github.com/jabbink/PokemonGoBot/blob/develop/src/main/kotlin/ink/abb/pogo/scraper/Main.kt#L60

**Comment by Evuse** [comment]
Yes i'm pretty sure. 
<img width="475" alt="schermata 2016-07-25 alle 00 56 23" src="https://cloud.githubusercontent.com/assets/20630600/17087115/b7c42aae-5202-11e6-9c38-c7ef99dde75c.png">

I'm sure even to have same ignored pokemon on config and on Main.kt

**Comment by Evuse** [comment]
I do the exactly the same as version 0.3 and 0.4 but 0.4.1 doens't work :(

**Comment by jabbink** [comment]
0.4.2 adds logging to exactly explain what the file contains according to the bot. Please retry.
