### ISSUE TITLE
Web-GUI how to?

### ISSUE THREAD

**Issue by RaeneDev** [jabbink/PokemonGoBot#248]
I saw The WebGUI and tried it. Webpage wasn't available at http://localhost:8000/ so I'm guessing it's somewhere else/other toggles are required. Can Someone explain to me how I can access this feature? https://github.com/jabbink/PokemonGoBot/issues/197

**Comment by jabbink** [comment]
![image](https://cloud.githubusercontent.com/assets/2461972/17087082/fce4be7e-5201-11e6-8dc5-83d2222a6362.png)
"Open", it's not implemented yet

**Comment by RaeneDev** [comment]
My bad.

**Comment by shilch** [comment]
You can clone my fork to test it https://github.com/shilch/PokemonGoBot
