### ISSUE TITLE
Zero colors in the log

### ISSUE THREAD

**Issue by capalex65** [jabbink/PokemonGoBot#251]
**Description:**
To my understanding 0.4.0 should include colors in the program log, I don't get any colors.

**Steps to reproduce:**

1. Download 0.4.0 or 0.4.1
2. Start it
3. See no colors

**Expected behavior:**
I expected to see colors of varying hue.

**Actual behavior:**
I get no colors, but instead I get these odd `[33m` or `[32m` here and there. I'm figuring it's ANSI coloring, which apparently doesn't work on my Windows 10 cmd.exe, strangely enough.

**Version:**
0.4.0 and 0.4.1

**Comment by joligario** [comment]
![win10_cmd-pogo](https://cloud.githubusercontent.com/assets/3617814/17087224/22735ac6-51d3-11e6-8445-f0b1e758f76b.png)
This is my win10 cmd prompt with 0.4.1

**Comment by capalex65** [comment]
That is strange... Because this is mine.

![b5495a3a7fc446dc4d9e7f5094b49efe 1](https://cloud.githubusercontent.com/assets/13821835/17087240/c0b219f2-5205-11e6-81a9-189950d23fb8.png)

**Comment by joligario** [comment]
![cmd_prmpt_settings](https://cloud.githubusercontent.com/assets/3617814/17087262/f197c102-51d3-11e6-9fde-ab54d20e507d.png)
Check settings, maybe?

**Comment by capalex65** [comment]
My settings are identical to yours, even down to the code page. Yet, no colors. How very odd. Could be that I'm running an insider preview build the colors don't like.

**Comment by SSminowjohnson** [comment]
Same here - I didn't even know we were supposed to see colors. If anyone can figure it out for Windows 7 please let us know.

**Comment by Ixath** [comment]
Windows 7 here and no colors either..

**Comment by Wyld1** [comment]
I see colors when I was running the source but not the jar.

**Comment by pashorizer** [comment]
Windows 7 does not support ANSI coloring. You have to install it.

Download this:
https://github.com/adoxa/ansicon/releases

1) Extract it, open the correct folder x64 or x86
2) Hold Shift + Right Click on that folder (alternativley `cd` into the directory)
3) open cmd
4) type `ansicon -i`
5) restart your bot

**Comment by jabbink** [comment]
Thanks @pashorizer

**Comment by capalex65** [comment]
@jabbink Considering that I'm running W10, I'm fairly sure it should work out of the box, yeah?

**Comment by jabbink** [comment]
No idea about `cmd.exe`. That thing hasn't been updated since Windows NT 4.0 I guess.

I'm sure that the Powershell has native color support, though.

Or download something like git bash.

**Comment by capalex65** [comment]
Fun fact, it was actually updated with Windows 10 to allow for ctrl+c and ctrl+v and similar commands. And yeah. Powershell has native colors alright. Maybe I should start up powershell before trying to run the bot.

**Comment by SSminowjohnson** [comment]
@pashorizer Downloading that only shows colors until the downloaded files are moved or deleted. I wonder if there's a more permanent solution for Windows 7. I do not see any colors in Powershell.

**Comment by joligario** [comment]
Reading this article, it may point to your inherited settings from conhost.

http://www.nivot.org/blog/post/2016/02/04/Windows-10-TH2-%28v1511%29-Console-Host-Enhancements
