### ISSUE TITLE
Stuck Walking between same PokeStop

### ISSUE THREAD

**Issue by oCortex** [jabbink/PokemonGoBot#252]
**Description:**
Run the bot for a couple of minutes. It catches/releases fine, then it'll get stuck walking between one or two pokestops and not moving on.

**Steps to reproduce:**

1. Using v0.4.1
2. Login/run bot as normal
(WalkOnly = False)
(HatchEggs=True) If that changes anything.

**Expected behavior:**
Walk between pokestops around the area.

**Actual behavior:**
Walks between one or two pokestops and doesn't move on.

**Stacktrace (If it's a crash):**
http://dumptext.com/uelh37UX
http://dumptext.com/pp4UpO0y

In one it's stuck walking at Wall Dragons, and the other it's stuck at Air Conditioning Graffiti. It's located in a big city centre, so it's not like there are no pokestops around.

**Version:**
v0.4.1

**Comment by SSminowjohnson** [comment]
Same issue here. Also, I went to restart the bot (0.4.1) and went to remove the token from the config file but token= is blank....yet the bot still starts up without me needing to enter a code on Google. Then, as you write, it just keeps walking to the same Pokestop. Furthermore, it's displaying the actual name of the Pokestop even though I have "display_pokestop_name=false".

**Comment by iamthasasquatch** [comment]
make sure in your task manager there are no processes of java.exe or consolehost.exe running if so end them then try again.

**Comment by li24yang75** [comment]
same problem..

**Comment by oCortex** [comment]
Apparently there's a lot wrong with main.kt at the moment. (Settings not passing from .config to .json, debug freaking people out, Pokestop blacklisting, Pokestop walking.) I'm just gonna leave it until next release/continue using 0.3.0

**Comment by andredp** [comment]
> but I've run out of Pokeballs and it's still trying to catch

You might be soft-banned. The bot can't spin pokestops so it has no way to get some pokeballs.

**Comment by iamthasasquatch** [comment]
I am running the lastest developer published with added web gui and its working fine for me...

If i close it and start another then it does not collect pokestops and will just try to collect the same 1 repeatidly. My fix is I kill all the tasks consolehost and java in taskmanager then rerun gradlew run and it works fine.

**Comment by oCortex** [comment]
> You might be soft-banned. The bot can't spin pokestops so it has no way to get some pokeballs.

Checked on my phone and I'm not. It just seems to get stuck on one pokemon.
http://dumptext.com/MvvgWZNd

**Comment by jabbink** [comment]
Fixed in 0.4.2

**Comment by CalebD44** [comment]
@iamthasasquatch Checking task manager helped me, thankyou! Had about 7 instances of java. Closed all of them and ran the script and it no longer looped same pokestop rewarding 0xp.
