### ISSUE TITLE
0.4.1 Creates new config and dumps items

### ISSUE THREAD

**Issue by Rofii** [jabbink/PokemonGoBot#254]
**Description:**
I just updated from 0.4.0 to 0.4.1 and it created a new properties file in a folder called bot-settings. Upon first run the bot dumped tons of valuables and caused my eyes to water.

**Steps to reproduce:**

1. Install and run 0.4.1 using the instructions included
2. Opposite of profit

**Expected behavior:**
Create a config file, as a base, take this file, save it as config.properties, fill all blanks and save it next to the .jar file

**Actual behavior:**
Config file is ignored, new one is generated with default values.

**Version:**
0.4.1

**Comment by Rofii** [comment]
Upon further inspection, it seems that the bot attempted to import my settings from properties.config into a new file but FUBAR'd when it came to importing what items to keep.

**Comment by SSminowjohnson** [comment]
@Rofii I don't think that's all that gets messed up; it's displaying the full names of Pokestops even though I have that set to off (by default).

**Comment by Forty-Tw0** [comment]
The bot is using the settings in bot-settings/config-properties-conversion.json
Main.kt is trying to set vals as well but they are conflicting. We need Main.kt to put the config.properties into the JSON and then everything should work. As of now you can try to set everything in JSON. Also make sure these are not null strings:
  "ignoredPokemon" : [ "MISSINGNO" ],
  "obligatoryTransfer" : [ "MISSINGNO" ],

**Comment by Simpuhl** [comment]
Can't even get that version to open properly, it did create the folder. But put nothing in it and doesn't even log me in

**Comment by Forty-Tw0** [comment]
Hell, I just deleted config.properties and it still works. Just set all your settings in the JSON for now. You will need your token I think.

**Comment by Rofii** [comment]
Confirmed that you can control settings in the JSON for now but BEWARE of using this on an existing account before trying it on a dummy first.

It successfully imported the ignoredPokemon and obligatoryTransfer as well as speed, latitude, and logitude. It missed the most important ones though: transferCPThreshold and uselessItems. This results in the bot rapidly throwing away hyper potions and ultra balls as well as good pokemon.

**Comment by Forty-Tw0** [comment]
Yes many lines are missing from Main.kt which override the vals set in the JSON. This bit:
`            botRunService.submitBot(Settings(
                name = "config-properties-conversion",
                credentials = credentials,
                startingLatitude = getPropertyOrDie(properties, "Starting Latitude", "latitude", String::toDouble),
                startingLongitude = getPropertyOrDie(properties, "Starting Longitude", "longitude", String::toDouble),
                speed = getPropertyIfSet(properties, "Speed", "speed", 2.778, String::toDouble),
                shouldDropItems = getPropertyIfSet(properties, "Item Drop", "drop_items", false, String::toBoolean),
                preferredBall = getPropertyIfSet(properties, "Preferred Ball", "preferred_ball", ItemId.ITEM_POKE_BALL, ItemId::valueOf),
                shouldAutoTransfer = getPropertyIfSet(properties, "Autotransfer", "autotransfer", false, String::toBoolean),
                shouldDisplayKeepalive = getPropertyIfSet(properties, "Display Keepalive Coordinates", "display_keepalive", true, String::toBoolean),
                keepPokemonAmount = getPropertyIfSet(properties, "Minimum amount of pokemon type to keep", "keep_pokemon_amount", 1, String::toInt),
                sortByIV = getPropertyIfSet(properties, "Sort by IV first instead of CP", "sort_by_iv", false, String::toBoolean),
                transferIVThreshold = getPropertyIfSet(properties, "Minimum IV to keep a pokemon", "transfer_iv_threshold", 80, String::toInt),
                transferCPThreshold = getPropertyIfSet(properties, "Minimum CP to keep a pokemon", "transfer_cp_threshold", 400, String::toInt),
                ignoredPokemon = getPropertyIfSet(properties, "Never transfer these Pokemon", "ignored_pokemon", "EEVEE,MEWTWO,CHARMENDER", String::toString).split(",").map { PokemonId.valueOf(it) },
                obligatoryTransfer = getPropertyIfSet(properties, "list of pokemon you always want to transfer regardless of CP", "obligatory_transfer", "DODUO,RATTATA,CATERPIE,PIDGEY", String::toString).split(",").map { PokemonId.valueOf(it) }
            ))`

**Comment by Forty-Tw0** [comment]
Not sure if jabbink wants to have Main.kt parse config.properties and put the values in bot-settings/config-properties-conversion.json or remove one of those methods entirely.

**Comment by jabbink** [comment]
Fixed because that broken pr is removed again
