### ISSUE TITLE
bug. Admin, please fix.

### ISSUE THREAD

**Issue by li24yang75** [jabbink/PokemonGoBot#261]
**Description:**
[Short description of the issue observed. If this ia feature request you can modify the template as required.]

The bot keeps going to the same stop all the time. Please see the logs.

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]

**Expected behavior:**
[What should happen?]

**Actual behavior:**

24 七月 18:03:42: Getting map of (37.7862291499803, -122.40933165894252)
24 七月 18:03:42: Walking to pokestop "Angry Bird" (37.786366, -122.409425000000
01) in 0.7048297930742078 steps.
24 七月 18:03:42: Destination reached.
24 七月 18:03:47: Getting map of (37.78638870620531, -122.40942181776012)
24 七月 18:03:48: Walking to pokestop "Angry Bird" (37.786366, -122.409425000000
01) in 0.2951701227458084 steps.
24 七月 18:03:48: Destination reached.
24 七月 18:03:52: Getting map of (37.7862100740094, -122.40930924995435)
24 七月 18:03:53: Walking to pokestop "Angry Bird" (37.786366, -122.409425000000
01) in 0.7048300781588052 steps.
24 七月 18:03:53: Destination reached.
24 七月 18:03:57: Getting map of (37.78636868078777, -122.40948807087747)
24 七月 18:03:57: Walking to pokestop "Angry Bird" (37.786366, -122.409425000000
01) in 0.2951698377516647 steps.
24 七月 18:03:57: Destination reached.
24 七月 18:04:02: Getting map of (37.786304958656736, -122.40937247568182)
24 七月 18:04:02: Walking to pokestop "Angry Bird" (37.786366, -122.409425000000
01) in 0.7048303631514938 steps.
24 七月 18:04:02: Destination reached.
**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
0.4.1

**Comment by Forty-Tw0** [comment]
Mine started doing that after "Pokestop still in cooldown mode; blacklisting for 5 minutes" I wonder if that is the cause.

**Comment by iamthasasquatch** [comment]
make sure in your task manager there are no copies of java.exe running or consolehost.exe 
Even if the console is not displayed but you have java.exe running then the program is still running and will cause this.

**Comment by Dragunovam** [comment]
I've seen it happen in the latest build, the bot tries to go back to the pokestop in cooldown, circles around and goes back in again until it gets a loot. The behaviour is new to this build, since i've run debugging from source and from the jar. The copies of running java.exe in windows are planned redundancies, in case the the application is started again the entries are directly available in the memory. 
Older versions didn't suffer from this issue, even with the java.exe copies left running after starting new terminals.

**Comment by Forty-Tw0** [comment]
I think I found the problem.
This was changed to check timeouts:
https://github.com/jabbink/PokemonGoBot/blob/develop/src/main/kotlin/ink/abb/pogo/scraper/tasks/LootOneNearbyPokestop.kt#L29
But this one was not:
https://github.com/jabbink/PokemonGoBot/blob/develop/src/main/kotlin/ink/abb/pogo/scraper/tasks/WalkToUnusedPokestop.kt#L33

**Comment by sodanakin** [comment]
If you wait 5ish minutes it actually continues lol. It just keeps circling the stop till the blacklist is done.

**Comment by Forty-Tw0** [comment]
I fixed the bug, #261 waiting for merge. It now checks the blacklist timeout as well as the canLoot status.

**Comment by li24yang75** [comment]
cool, thanks for this quick fix. you are the best. Admin.

**Comment by jabbink** [comment]
Is fixed
