### ISSUE TITLE
How to fix "The filename or extension is too long" ?

### ISSUE THREAD

**Issue by DeadShotProdigy** [jabbink/PokemonGoBot#264]
**Description:**
[Short description of the issue observed. If this ia feature request you can modify the template as required.]

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]

**Expected behavior:**
[What should happen?]

**Actual behavior:**

C:\Users\TestPC\Desktop\PokemonGoBot\PokemonGoBot>gradlew build -x check
:PokeGOAPI-Java:extractIncludeProto UP-TO-DATE
:PokeGOAPI-Java:extractProto UP-TO-DATE
:PokeGOAPI-Java:generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':PokeGOAPI-Java:generateProto'.
> java.io.IOException: Cannot run program "C:\Users\TestPC\\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protoc\3.0.0-beta-3\7fd402d66301a053e4d8018e8f91da03839e8f9c\protoc-3.0.0-beta-3-windows-x86_32.exe": CreateProcess error=206, The filename or extension is too long

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.362 secs

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
0.4.1

**Comment by iamthasasquatch** [comment]
you ran the git submodule command?

**Comment by DeadShotProdigy** [comment]
Yep, ran git submodule and i still get this error, tried a fresh clone on two different comps but i get this same issue.

Also tried the 0.4.1 java file which didn't work.

0.3.0 works flawlessly for me.

**Comment by Letrico** [comment]
Same issue with me. Tried to make a build/run with the latest fix from the fork and got the same problem

**Comment by Forty-Tw0** [comment]
Might just be a windows thing? Filepaths max out at 260 characters last I heard.

**Comment by Letrico** [comment]
@Forty-Tw0 seems like it is indeed the case. Rather unfortunate I can't run the bot at the moment due to the circling around blacklisted pokestop forever.

**Comment by sodanakin** [comment]
I got this issue too http://pastebin.com/Q0qDhD7p  
I'd love a new prebuilt...

**Comment by jabbink** [comment]
Clone repo in a higher directory (eg `C:\`). This is a known Windows issue.

**Comment by luisa123456** [comment]
Resolve the Path Too Long error with the help of ‘Long Path Tool’.

**Comment by Stepan222** [comment]
You must try  "Long Path Tool" Program. Just rename the file resulting in "path too long" or move it to the location which has shorter path.
I would recommend using "Path Too Long" program to rename the path to a shorter name. This works for me every time.

**Comment by ashley200** [comment]
Hello, Try long Path tool. Its great cure for this problem.
