### ISSUE TITLE
[Question] Pokestop XP

### ISSUE THREAD

**Issue by iamthasasquatch** [jabbink/PokemonGoBot#267]
Do some pokestops actually give 100 xp? I notice in the log randomly some generate 100 xp instead of the usual 50xp.

24 Jul 22:03:37: Looted pokestop "Simpson House-Irvine Place-Coby Hall"; +100 XP
: [6xITEM_POKE_BALL]
24 Jul 22:03:57: Looted pokestop "Edward  O'Neal Home "; +50 XP: [3xITEM_POKE_BA
LL, 1xITEM_RAZZ_BERRY]

**Comment by Forty-Tw0** [comment]
Might have to do with how many items you get as loot.
https://gaming.stackexchange.com/questions/275628/how-to-get-double-loot-and-xp-from-a-pokestop
