### ISSUE TITLE
When out of Pokeballs, bot still attempts to catch

### ISSUE THREAD

**Issue by jsboygenius** [jabbink/PokemonGoBot#274]
**Description:**
My account was very low on Pokeballs before I ran the bot (<10 left), and after checking in as the bot was running, I noticed that it was repeatedly stating that a Pokemon had been spotted, a catch attempt made, but the attempt failed due to no Pokeballs remaining. This is obviously an expected functionality, but the bug I encountered was that the bot continued chasing after the same Pokemon. Ideally (I guess this is sort of a feature request) the bot would recognize that there weren't any Pokeballs left, and then focus on getting to the nearest Pokestop.

My guess without looking through the source is that since the Pokemon didn't flee and is still standing there, the bot sees it as another potential catch without first checking if there are enough Pokeballs. This already triggers an exception that is caught which proves that the bot can detect the lack of Pokeballs, so I would hope that the change would be fairly simple to implement.

**Steps to reproduce:**

1. Use up/throw away all of the user's Pokeballs.
2. Run the bot. 

**Expected behavior:**
Having detected that there are no Pokeballs left, the bot should ignore Pokemon for the time being and direct itself to the nearest Pokestop to replenish the supply before resuming catch attempts.

**Actual behavior:**
The bot detects a Pokemon, attempts to catch the Pokemon, fails to catch the Pokemon (while still recognizing that there are no more Pokeballs), and... tries to catch the same Pokemon all over again.

**Stacktrace (If it's a crash):**
No crash, just a bug (or a feature request?)

**Version:**
0.4.1

**Comment by jabbink** [comment]
Fixed.
