### ISSUE TITLE
Google Login Token Expiring ?

### ISSUE THREAD

**Issue by xenxes** [jabbink/PokemonGoBot#275]
The token via verify device @ google.com/device is now automatically saved into the my-bot-name.json, but after a while (I timed about 4 hours), it still expires, so one has to manually go back to the json file and remove that token.  Is there a way to prevent this expiration?

**Comment by Forty-Tw0** [comment]
#262 should implement refresh tokens which keep you authenticated forever, it is awaiting a merge.

**Comment by xenxes** [comment]
Awesome, testing it now :+1:

**Comment by cwliias** [comment]
How do you setup a refresh token?

**Comment by jabbink** [comment]
Either fixed or duplicate of #165.

Either way: closed
