### ISSUE TITLE
Removed Spring Boot

### ISSUE THREAD

**Issue by jabbink** [jabbink/PokemonGoBot#278]
**Description:**
While there is nothing wrong with Spring Boot itself, your PR that you force-merged broke lots of functionality. Will force reset the branch in a second. Feel free to make a new PR that actually compiles and does not remove essential functionality.

**Comment by jabbink** [comment]
@apottere

**Comment by sodanakin** [comment]
Hey could you also add a fixed release version? 
The 0.4.1 Saves the token and requires manual removal after a few hours. 
(Funnily enough Google works better on that one)
Oh and it has the pokestop problem too.. if it Times out on one it keeps circling it for 5 minutes.

I tried to go back to V0.2.0 But it doesn't seem to want to catch pokemons for me anymore on that one =\.

**Comment by jabbink** [comment]
Your non-working stuff and the old HEAD of `develop` is in https://github.com/jabbink/PokemonGoBot/tree/currentHead

**Comment by jabbink** [comment]
@sodanakin I fixed the Google Login. @apottere's Spring Boot integration removed the Google fix. smh.

I first thought that it only introduced the config issue that it doesn't read all values, but it broke waaaaaaaaaaaaaay more

**Comment by sodanakin** [comment]
@jabbink  Yea that's what I am saying lol, Google works fine, it just needs a new ptc token every 3ish hours and fails there because it tries to use the one in the config (Which isn't working anymore ;p)

**Comment by Zeift** [comment]
So did it revert back?
I need the google fix :(

**Comment by jabbink** [comment]
Google fix is back in, as I reset the repo to how it was a day ago.
