### ISSUE TITLE
can't find prebuilt bot

### ISSUE THREAD

**Issue by li24yang75** [jabbink/PokemonGoBot#284]
**Description:**
Hi, admin, I can not find the prebuilt version bot. I saw there are many commits today.  I just wonder are you preparing to update the prebuilt version bot? Sorry for asking this. Because I want to use the new bot as soon  as possible. And your work is so amazing. Thanks.

**Comment by jabbink** [comment]
Yeah, preparing to re-release a prebuilt version.

v0.4.0 contained some stupid bugs that were hotfixed in 0.4.1, unfortunately 0.4.1 also contained a new feature that broke **a lot** of things, so I removed it again

**Comment by jabbink** [comment]
https://github.com/jabbink/PokemonGoBot/releases/tag/v0.4.2

**Comment by li24yang75** [comment]
Cool, Admin, Thanks for this quick update. I can't wait to use it.
