### ISSUE TITLE
can't run the new version prebuilt bot

### ISSUE THREAD

**Issue by li24yang75** [jabbink/PokemonGoBot#286]
Hi, admin, when I run the new version prebuilt bot, I got an error:

E:\111\444>java -jar pogo.scraper-all-0.4.2.jar
[33m25 七月 02:21:02: Display Keepalive Coordinates setting ("display_keepalive
") not specified, defaulting to "true". [0m
Logging in to game server...
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException
        at com.pokegoapi.auth.PtcLogin.login(PtcLogin.java:196)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:87)

I have no idea about how to solve this.  Actually when I run the bot from the source code. At the last step  "gradlew run",  I also got this error. Would you please tell me how to solve this? Thanks.

**Comment by jabbink** [comment]
Why did you remove the template that you have to fill in?

Google Login? PTC Login?

Probably fixed by going to your `config.properties` and setting the `token=` line to NOT contain any token.

**Comment by li24yang75** [comment]
I use Google Login. And my config.properties files like this:

# PTC/Google login credentials
username=

# Choose plaintext or base64'd password
password=
base64_password=

# Token to login directly
token=
latitude=37.788475
longitude=-122.407661

# desired chance to catch Pokemon with 1 throw
desired_catch_probability=0.8

is there something wrong?

**Comment by jabbink** [comment]
There's your problem, set username to your correct username or to `@`, see your original comment, it references PtcLogin.
