### ISSUE TITLE
CATCH_ERROR when catching Pokemon

### ISSUE THREAD

**Issue by Noblewulf** [jabbink/PokemonGoBot#287]
**Description:**
When trying to catch a Pokemon, the bot will repeatedly run into a `CATCH_ERROR` status.
Picture: http://i.imgur.com/kpaatEf.png

**Steps to reproduce:**
1. The error is random upon starting the bot, it could run fine for minutes and then all of a sudden it gets stuck in a `CATCH_ERROR` loop with the same Pokemon until restart.

**Expected behavior:**
The Pokemon should be captured and then dealt with based on the user's config.

**Actual behavior:**
The bot goes into an infinite loop with the same Pokemon, repeatedly failing the capture.

**Version:**
Pokemon Go Bot v0.4.2

**Comment by jabbink** [comment]
You're probably soft banned. Don't teleport large distances or use the bot while the app is opened on your phone.

**Comment by Noblewulf** [comment]
That was my first thought, but throughout this process, the bot successfully gets items from pokestops. On top of that, the bot will eventually catch the current pokemon, but the issue will continue with the next pokemon it encounters.
