### ISSUE TITLE
Bot stuck at some pokestop.

### ISSUE THREAD

**Issue by vdmkenny** [jabbink/PokemonGoBot#288]
Running 0.4.2, bot is stuck at same stop.

25 Jul 05:26:54: Looted pokestop "Théâtre de Namur"; +0 XP: [] 
Walking to pokestop "Théâtre de Namur"
Walking to (50.464148, 4.86787) in 0.4440904662951054 steps.
Destination reached.
Getting map of (50.46418457693781, 4.867892943234108)
Looting nearby pokestop "Théâtre de Namur"
25 Jul 05:26:59: Looted pokestop "Théâtre de Namur"; +0 XP: [] 
Walking to pokestop "Théâtre de Namur"
Walking to (50.464148, 4.86787) in 0.5559095251040457 steps.
Destination reached.
Getting map of (50.46412744429534, 4.86786096201099)
Looting nearby pokestop "Théâtre de Namur"
25 Jul 05:27:04: Looted pokestop "Théâtre de Namur"; +0 XP: [] 
Walking to pokestop "Théâtre de Namur"
Walking to (50.464148, 4.86787) in 0.4440904814229978 steps.
Destination reached.
Getting map of (50.46419604682342, 4.867816729111702)
Looting nearby pokestop "Théâtre de Namur"
25 Jul 05:27:09: Looted pokestop "Théâtre de Namur"; +0 XP: [] 
Walking to pokestop "Théâtre de Namur"
Walking to (50.464148, 4.86787) in 0.5559095103352725 steps.
Destination reached.
Getting map of (50.46411242642855, 4.867878098674973)
Looting nearby pokestop "Théâtre de Namur"
25 Jul 05:27:14: Looted pokestop "Théâtre de Namur"; +0 XP: [] 
Walking to pokestop "Théâtre de Namur"
Walking to (50.464148, 4.86787) in 0.44409049647943877 steps.
Destination reached.
Getting map of (50.46412033389866, 4.867832202957513)
Looting nearby pokestop "Théâtre de Namur"
25 Jul 05:27:19: Looted pokestop "Théâtre de Namur"; +0 XP: [] 
Walking to pokestop "Théâtre de Namur"
Walking to (50.464148, 4.86787) in 0.5559094946790603 steps.
Destination reached.
Getting map of (50.4641148121442, 4.867869430137881)
Looting nearby pokestop "Théâtre de Namur"

**Comment by jabbink** [comment]
You're probably soft banned, because the server returns that it was successful, yet gives 0 XP.

**Comment by dentillozie** [comment]
i have the same problem. not softbanned, i tested it with 0.3.0 and it works on there

**Comment by BartWillems** [comment]
I don't know dentillozie, it works perfectly fine for me.. Are you using a good OS like GNU/Linux?
