### ISSUE TITLE
Smart capture is flawed

### ISSUE THREAD

**Issue by nmlpsousa** [jabbink/PokemonGoBot#289]
I was taking a look at the code for smart capture (#174) and noticed that the if's don't make much sense.

```
if (probability >= desiredCatchProbability - 0.2) {
        ball = ballType
        break
    } else if (probability >= desiredCatchProbability - 0.1) {
        ball = ballType
        needCurve = true
        break
    } else if (probability >= desiredCatchProbability - 0.2) {
        ball = ballType
        needCurve = true
        needRazzBerry = true
        break
}
```

Let's say probability = 0.5 and desiredCatchProbability = 0.8.
If it doesn't enter the first if (0.5 >= 0.6), it will never enter the second if (0.5 >= 0.7). And finally, the last if is exactly the same as the first.

So a little revision here is needed, I think :)

**Comment by jabbink** [comment]
Nice catch, the first line should not include that `- 0.2`.

Rewrote parts of that code shortly before pushing and probably missed this.

Thanks

**Comment by jabbink** [comment]
To prevent hundreds of duplicate bug reports, this has been fixed in the bundled version.
