### ISSUE TITLE
only google? 

### ISSUE THREAD

**Issue by julienkessels** [jabbink/PokemonGoBot#29]
hello, 
in the config he asks me google and ptc,
if i want only google or only ptc how do i do?

and the google login is strange? why do i need to do a special device adding? 
why not just giving google login, password an GO like others ? 
thank you, great work !!!

**Comment by SwipeX** [comment]
Google requires device authentication. PTC does not. It will automatically detect this.

**Comment by julienkessels** [comment]
cant remember authenticating for the other bot: 
https://www.reddit.com/r/pokemongodev/comments/4tupcg/open_source_pokemongobot_is_working_as_expected/

**Comment by SwipeX** [comment]
Correct, key could be cached and used for future.
