### ISSUE TITLE
Bot stuck on pokestop and catch_flee on 0.4.2

### ISSUE THREAD

**Issue by dentillozie** [jabbink/PokemonGoBot#292]
Problem on 0.4.2:

25 jul 11:48:29: Capture of SLOWPOKE failed with status : CATCH_FLEE 
25 jul 11:48:30: Hatched MAGIKARP with 95 CP and 82% IV; +5 candy; +200 XP; +400 stardust 
Getting map of (50.464645139179645, 4.866209825893596)
25 jul 11:48:33: Found pokemon ZUBAT 
25 jul 11:48:33: Encountered pokemon ZUBAT with CP 56 
25 jul 11:48:33: Using ITEM_POKE_BALL 
25 jul 11:48:33: Capture of ZUBAT failed with status : CATCH_FLEE 
Walking to (50.465149, 4.866303) in 94.92676245793123 steps.
Looting nearby pokestop f14be608708d4f3dad06924e10f64c3c.16
25 jul 11:48:48: Looted pokestop f14be608708d4f3dad06924e10f64c3c.16; +0 XP: [] 
Getting map of (50.46519022739526, 4.866331964231116)
Destination reached.
Looting nearby pokestop f14be608708d4f3dad06924e10f64c3c.16
25 jul 11:48:53: Looted pokestop f14be608708d4f3dad06924e10f64c3c.16; +0 XP: [] 

Still works with 0.3.0:

Found pokemon RATTATA
Encountered pokemon RATTATA
Caught a RATTATA using ITEM_POKE_BALL
Going to transfer RATTATA with CP 225
Profile update : 409640 XP on LVL 22; 149640/175000 (85,51%) to LVL 23
Getting map of (50.85342923678203, 4.353285350657099)
Going to transfer RATTATA with CP 227
Profile update : 409640 XP on LVL 22; 149640/175000 (85,51%) to LVL 23
Getting map of (50.853325133828505, 4.35316763743245)
Profile update : 409640 XP on LVL 22; 149640/175000 (85,51%) to LVL 23
Getting map of (50.85324612434124, 4.352962295063763)
Looting nearby pokestop 33d5338c0ee14f47908ffbfde9226145.16
Looted pokestop 33d5338c0ee14f47908ffbfde9226145.16: [1xITEM_RAZZ_BERRY, 2xITEM_GREAT_BALL]
Profile update : 409690 XP on LVL 22; 149690/175000 (85,54%) to LVL 23
Getting map of (50.85315129178983, 4.352818111217555)
Destination reached.
Dropped 2x ITEM_GREAT_BALL
Looting nearby pokestop bba74b1ee1e84470b92bab9aa5f044d3.16
Looted pokestop bba74b1ee1e84470b92bab9aa5f044d3.16: [2xITEM_POKE_BALL, 1xITEM_HYPER_POTION]

As you can see **not softbanned** 

any idea what the issue might be?

**Comment by vdmkenny** [comment]
+1 same issue. constant catch_flee, and getting stuck at pokestops.

**Comment by jabbink** [comment]
what is your `desired_catch_probability`?

**Comment by dentillozie** [comment]
default: 0.8

**Comment by jabbink** [comment]
When did you download the prebuilt 0.4.2? I uploaded a slightly fixed version that includes https://github.com/jabbink/PokemonGoBot/pull/290 ~20 minutes ago

**Comment by dentillozie** [comment]
40min ago. will redownload and test again

**Comment by vdmkenny** [comment]
Updating to latest prebuilt version solved it for me. Would be nice if the versioning scheme could reflect these small patches to avoid this in the future. Great bot. Thanks.

**Comment by jabbink** [comment]
Didn't want to immediately put out a 0.4.3 so I quickly overwrote it hoping that nobody had downloaded it yet, but you guys are fast in getting the update :P

Good to hear it's fixed.
