### ISSUE TITLE
Problem when logging in with Google with autoset token

### ISSUE THREAD

**Issue by michaje** [jabbink/PokemonGoBot#293]
Seems to be just a little error, typo or such:
```
$ java -jar pogo.scraper-all-0.4.2.jar
Logging in to game server...
Exception in thread "main" java.lang.IllegalStateException: if (token.contains("poke?eshToken(token)
        } must not be null
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:90)
```

**Comment by Cypherke** [comment]
remove token from config file should fix this

**Comment by jabbink** [comment]
You might want to make the file read-only then.

**Comment by pr0ves** [comment]
What did you have as `token` when you had this error?

**Comment by michaje** [comment]
Yeah, i always remove it, but that means just regularly logging in again every time, so the token is pretty much useless

**Comment by cwliias** [comment]
Setting it to read only causes a crash

**Comment by li24yang75** [comment]
I know how to solve this. 
When you first time use google.com/device log in the bot, there is token shows in the cmd. it is like:  Logged in as __ with token ___ .

The Token is very short. You need to write this short token into config.properties files at "token =" field manually.

Then next time  you can log in without erasing token or inputing device code again.
