### ISSUE TITLE
Transfer not behaving properly

### ISSUE THREAD

**Issue by cwliias** [jabbink/PokemonGoBot#294]
```
# Minimum IV percentage to keep a pokemon (to ignore IV: use -1)
# between 0 and 100, suggested 80
transfer_iv_threshold=93

# Minimum CP to keep a pokemon (to ignore CP: use -1)
transfer_cp_threshold=-1
```

These are my transfer settings. Its keeping most Pokemon it seems i was at caught/transferred 41/0

My desire is to have pokemon at or above 93% IV's to be kept

**Comment by pr0ves** [comment]
Do you have `autotransfer=true`?

**Comment by jabbink** [comment]
#to ignore CP: use -1

Then why do you set it to 1, which indeed keeps everything with a CP of 1 and higher (everything)

**Comment by cwliias** [comment]
its set to -1

**Comment by cwliias** [comment]
@pr0ves i just swapped it to true, will report back after seeing what that did, Don't know how i missed that line earlier

**Comment by pr0ves** [comment]
Report back if it works or not.

**Comment by cwliias** [comment]
## Pokemon Transfer
# should the bot auto transfer duplicate pokemon
autotransfer=true


appears to have worked, One last question. Having my 
# minimum amount of pokemon type to keep
keep_pokemon_amount=1

set to 1 will that behave as such. 
Currently own 93% IV pidgey 
Catch 95% IV pidgey
Transfer 93% pidgey?

**Comment by pr0ves** [comment]
Yep, that's how it works.
Closing.
