### ISSUE TITLE
The Bot NOT transfer some pokemons?

### ISSUE THREAD

**Issue by pvase666** [jabbink/PokemonGoBot#295]
My configs (using latest DEV build)
```
# if you want all pokemons to be transferred just leave it blank
ignored_pokemon=MEWTWO,SNORLAX,DRAGONITE

# list of pokemon you always want to trancsfer regardless of CP
obligatory_transfer=

# between 0 and 100, suggested 80
transfer_iv_threshold=80

# Minimum CP to keep a pokemon (to ignore CP: use -1)
transfer_cp_threshold=1400
```

the Bot didn't transfer:

Have BELLSPROUT () with 102 CP and IV 46%
Have CATERPIE () with 10 CP and IV 35%
Have DODUO () with 79 CP and IV 60%
Have EEVEE () with 441 CP and IV 75%
Have EEVEE () with 380 CP and IV 71%
Have EEVEE () with 370 CP and IV 55%

and more.....

**Comment by jabbink** [comment]
`autotransfer=true`?

**Comment by jabbink** [comment]
And `keep_pokemon_amount=0`

**Comment by pvase666** [comment]
Yes @jabbink

**Comment by pvase666** [comment]
keep_pokemon_amount=0. Oh, i didn't see that. I will take a look and report later, thank you.

**Comment by pvase666** [comment]
Working, really nice. Thank you :dancer:

**Comment by cwliias** [comment]
of i have mine set at 0 it auto crashes on startup
