### ISSUE TITLE
[Suggestion] Option to evolve all 12 candie evolutions before transfer

### ISSUE THREAD

**Issue by cwliias** [jabbink/PokemonGoBot#296]
**# /Feature Request**

For the exp, I have like 2k pidgey candies. and a few others. 

Would be awesome to have option to evolve either just specific pokemon then transfer them OR just 12 candie evolutions and then transfer them

**Comment by alone23** [comment]
+1

**Comment by lz0** [comment]
+1

**Comment by andredp** [comment]
You should search other issues before creating another. @jabbink already said he wants a bulk evolution system that pops a lucky egg before evolving all those pokemons. Until someone implements it, I think you'll have to wait.

**Comment by CptJackieSparrow** [comment]
or maybe evaluate all pidgey, ratatas etc.. then transfer.

**Comment by jabbink** [comment]
Evolving has been added.
