### ISSUE TITLE
0.4.2 with Java 1.8

### ISSUE THREAD

**Issue by omar972** [jabbink/PokemonGoBot#300]
#256 

Still not fixed.

D:\POGO bot>java -jar pogo.scraper-all-0.4.2.jar
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'

has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.

**Comment by jabbink** [comment]
What is the output of `java -version`?

**Comment by omar972** [comment]
With 1.7 in registry: "D:\POGO bot>java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)"

with 1.8: "D:\POGO bot>java -version
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'

has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment."

For some reason, even though I have Java 1.8 installed with JDK1.8.0_73, everything in my registry other than the current version says I'm using 1.7.
https://gyazo.com/03f7eadc4284d5f354bb16f9913d22b9

So I guess the problem is with my installation of Java.

**Comment by jabbink** [comment]
Yeah, so the error is confusing. Your java version requires v 1.7. I first thought the code in the jar gave that error (detecting java 1.8 and requiring 1.7, but good to see it's the logical way round)

**Comment by omar972** [comment]
I'm actually having another error with 0.4.2 that I didn't have with 0.4.1. (With current version 1.7)

Logged in as *********@gmail.com with token 1/XGZFpRODe********************
Setting this token in your config
Exception in thread "main" java.lang.NoSuchMethodError: java.io.BufferedReader.l
ines()Ljava/util/stream/Stream;
        at ink.abb.pogo.scraper.Settings.writeToken(Settings.kt:139)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:105)

**Comment by philippjess** [comment]
Try removing Java cleanly with https://java.com/en/download/faq/uninstaller_toolinfo.xml and then reinstall 1.8

**Comment by omar972** [comment]
Turns out I had both Java 1.7 and Java 1.8 installed, so that's why its acting weird. My bad. It's all working now.
