### ISSUE TITLE
0.4.2 Exception in thread "main"

### ISSUE THREAD

**Issue by Ixath** [jabbink/PokemonGoBot#301]
Worked flawlessly the first time I ran it. Checked back 20 minutes later and it was erroring out every time it tried to catch a pokemon. Restarted it, got the error below. Closed it, cleared the bot-settings folder, and tried again. Still getting the error:

```
C:\Temp\PokemonGo>java -jar pogo.scraper-all-0.4.2.jar
Logging in to game server...
Exception in thread "main" java.lang.IllegalStateException: if (token.contains("poke?eshToken(token)
        } must not be null
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:90)
```

**Comment by jabbink** [comment]
Duplicate.

Remove the token from your config.
