### ISSUE TITLE
Transferring Pokemon not working right

### ISSUE THREAD

**Issue by classicalDonkey** [jabbink/PokemonGoBot#303]
**Description:**
Ok so i have been watching the outputs and I can see that I don't think the transfer is working right.  I have set to transfer dups, keep the best 6 IV =80 and CP = 400.  But I see that it is keeping pokemon that do not match.  Am I missing something???

**Actual behavior:**
25 Jul 13:00:56: Found pokemon CATERPIE
25 Jul 13:00:56: Encountered pokemon CATERPIE with CP 196
25 Jul 13:00:56: Using ITEM_ULTRA_BALL; Using Razz Berry; Using curve
25 Jul 13:00:57: Caught a CATERPIE with CP 196 and IV 15%: [210x XP, 3x Candy, 100x Stardust]

**Version:**
4.0.2

**Comment by jabbink** [comment]
Do you have `autotransfer=1`?

**Comment by classicalDonkey** [comment]
## Pokemon Transfer
# should the bot auto transfer duplicate pokemon
autotransfer=true
