### ISSUE TITLE
Getting tons of "Capture of X failed with status: CATCH_ERROR" after a while

### ISSUE THREAD

**Issue by Yayt** [jabbink/PokemonGoBot#305]
**Description:**
Getting tons of "Capture of X failed with status: CATCH_ERROR" after a while.

**Steps to reproduce:**

1. Start
2. Wait

**Expected behavior:**
Catch

**Actual behavior:**
No Catch

**Stacktrace (If it's a crash):**
Its not a crash

**Version:**
0.4.2

**Comment by jabbink** [comment]
What is your `speed` variable?

**Comment by Yayt** [comment]
3.8 m/s, should be below the speed limit (comes down to 13.7 km/h). Also since the pokemon is never caught it keeps encountering the same one and gets stuck in a loop, it does still move to new places.

**Comment by iamthasasquatch** [comment]
sounds like the pokebank is full

**Comment by Yayt** [comment]
The application says it isn't, also I checked in the real app and even though it has more then the application thinks it has, it still isn't full.

**Comment by jinyu1993** [comment]
I m getting the same error as well, could be due to insufficient pokeball of that type?

**Comment by Yayt** [comment]
That's the problem! It kept trying to use ultra balls even though I don't have them!

**Comment by SSminowjohnson** [comment]
I see the notes for v0.4.2 says, "Check if user has Pokeballs before trying an encounter". Mine keeps using Ultra/Great balls even just to catch a Rattata.

25 Jul 08:49:17: Encountered pokemon RATTATA with CP 320 
25 Jul 08:49:17: Using ITEM_GREAT_BALL; Using curve

**Comment by jabbink** [comment]
>That's the problem! It kept trying to use ultra balls even though I don't have them!

Impossible

Also unrelated issue. Stay on topic, please.

**Comment by dyoung81** [comment]
I've been having this issue as well.   I've been messing around with it I believe the pokemon may have disappeared since it updated the map last, and it keeps trying to capture it.  It seems to happen randomly to me I have 50/50/50 balls and 125/250 pokebank so I don't believe it's either of those.

**Comment by Yayt** [comment]
Well it happens only with ultra balls, and only after it has gotten an ultra ball from a pokestop and used it to catch a pokemon, then when there are no ultra balls left it starts doing this.

**Comment by dyoung81** [comment]
Just happened to me with greatballs not ultra, and I've had it happen with pokeballs early today

25 Jul 09:29:08: Found pokemon RATTATA
25 Jul 09:29:09: Encountered pokemon RATTATA with CP 154
25 Jul 09:29:09: Using ITEM_GREAT_BALL; Using curve
25 Jul 09:29:09: Capture of RATTATA failed with status : CATCH_ERROR
Getting map of (35.31058394025945, -80.733791400403)
25 Jul 09:29:13: Found pokemon RATTATA
25 Jul 09:29:14: Encountered pokemon RATTATA with CP 154
25 Jul 09:29:14: Using ITEM_GREAT_BALL; Using curve
25 Jul 09:29:14: Capture of RATTATA failed with status : CATCH_ERROR

**Comment by pashorizer** [comment]
Ok, seems like I can some what re-produce the problem.

```
Found pokemon SPEAROW
Encountered pokemon SPEAROW with CP 472
Using ITEM_GREAT_BALL; Using curve
Capture of SPEAROW failed with status : CATCH_ERROR
```

Apparently if you hold the scrollbar in the cmd window it holds(stops?) the threads and you get lot of funky errors.

```
25 Jul 15:34:56: Walking to pokestop "Driprock Arch"
25 Jul 15:34:56: Walking to (40.76871, -73.97598) in 0.7700626119044132 s
25 Jul 15:34:56: Destination reached.
25 Jul 15:34:56: Walking to pokestop "Driprock Arch"
25 Jul 15:34:56: Walking to (40.76871, -73.97598) in 0.22993738775573663
25 Jul 15:34:56: Destination reached.
25 Jul 15:34:58: Getting map of (40.76871892928906, -73.97601082174592)
25 Jul 15:35:00: Walking to pokestop "Driprock Arch"
25 Jul 15:35:00: Walking to (40.76871, -73.97598) in 0.7700626119044132 s
25 Jul 15:35:00: Destination reached.
25 Jul 15:35:03: Getting map of (40.768695078953364, -73.97598691021594)
25 Jul 15:35:05: Walking to pokestop "Driprock Arch"
25 Jul 15:35:05: Walking to (40.76871, -73.97598) in 0.22993738775573663
25 Jul 15:35:05: Destination reached.
25 Jul 15:35:08: Getting map of (40.768742889954304, -73.9759472153696)
25 Jul 15:35:10: Walking to pokestop "Driprock Arch"
25 Jul 15:35:10: Walking to (40.76871, -73.97598) in 0.7700626119044132 s
25 Jul 15:35:10: Destination reached.
25 Jul 15:35:13: Getting map of (40.768695507116924, -73.9759830449874)
25 Jul 15:35:15: Walking to pokestop "Driprock Arch"
25 Jul 15:35:15: Walking to (40.76871, -73.97598) in 0.22993738775573663
25 Jul 15:35:15: Destination reached.
25 Jul 15:35:18: Getting map of (40.768742484752714, -73.97601535520764)
25 Jul 15:35:20: Walking to pokestop "Driprock Arch"
25 Jul 15:35:20: Walking to (40.76871, -73.97598) in 0.7700626119044132 s
25 Jul 15:35:20: Destination reached.
25 Jul 15:35:23: Getting map of (40.76874890770851, -73.97599140093062)
```

**Comment by Yayt** [comment]
Just happened, it got an ultraball, caught a caterpie, then still tried to use the ultra ball.

```
25 jul 15:23:03: Looted pokestop 692b14997ee8460ea467b3c5acd4c46f.16; +50 XP: [1xITEM_GREAT_BALL, 1xITEM_ULTRA_BALL, 1xITEM_RAZZ_BERRY, 1xITEM_POTION]
Getting map of (53.21609125778739, 6.567009945392674)
25 jul 15:23:07: Found pokemon WEEDLE
25 jul 15:23:08: Encountered pokemon WEEDLE with CP 128
25 jul 15:23:08: Using ITEM_ULTRA_BALL
25 jul 15:23:08: Caught a WEEDLE with CP 128 and IV 40%: [200x XP, 3x Candy, 100x Stardust]
Destination reached.
25 jul 15:23:09: Dropped 3x ITEM_POTION
Getting map of (53.21607742027644, 6.567029334984818)
25 jul 15:23:13: Found pokemon PIDGEY
25 jul 15:23:13: Encountered pokemon PIDGEY with CP 228
25 jul 15:23:13: Using ITEM_ULTRA_BALL
25 jul 15:23:13: Capture of PIDGEY failed with status : CATCH_ERROR
Getting map of (53.21603465116321, 6.567040311667165)
25 jul 15:23:17: Found pokemon PIDGEY
25 jul 15:23:18: Encountered pokemon PIDGEY with CP 228
25 jul 15:23:18: Using ITEM_ULTRA_BALL
25 jul 15:23:18: Capture of PIDGEY failed with status : CATCH_ERROR
```

**Comment by jabbink** [comment]
Ah, thanks

Stepped through the code. Major ItemBag bug in the Java API. Reported it.

**Comment by dyoung81** [comment]
Thanks
