### ISSUE TITLE
Token does not refresh.

### ISSUE THREAD

**Issue by sodanakin** [jabbink/PokemonGoBot#306]
**Description:**
Token still times out and reopening bot when token is timed out will result in an error and close.

**Steps to reproduce:**

1. [Step 1]
Run bot for hours. Get token forced into config even when you removed it 50 times.
Relaunch bot , Rip Bot

**Expected behavior/Suggestion:**
Refresh token or option to not use token at all.
(With not using the token at all I mean : an option to always auth first. Because the token is to bypass the authentication thing right?)

**Actual behavior:**
Token kills bot. Poor bot :(

0.4.2

**Comment by jabbink** [comment]
Fixed in #308
