### ISSUE TITLE
No option to only get pokestops?

### ISSUE THREAD

**Issue by escojoncio** [jabbink/PokemonGoBot#307]
**Description:**
Since in my city there's just only a few pokestops, i don't want to cheat on getting pokemons, but i want to get as many pokeballs as possible, since almost always i dont have any, it is possible to include an option for this? like the Walk Only option?

**Comment by pashorizer** [comment]
Yes, set `walkOnly=true` in your properties.

**Comment by escojoncio** [comment]
But it says # Only walk (hatch eggs, don't collect pokemon or pokestops)

**Comment by jabbink** [comment]
Correct, walk only is not the way to go

**Comment by pashorizer** [comment]
What you could so is to set all the Balls to 0 in your properties.

**Comment by escojoncio** [comment]
yes but that does not fix my main problem -> I don't want to capture pokemon with this, i just want pokestops

**Comment by pashorizer** [comment]
Yes, but there is currently no other way. It will not try to catch the it when you have no balls and since it is walking from Pokestop to Pokestop it might work. Can't test is here tho.

https://github.com/jabbink/PokemonGoBot/blob/develop/src/main/kotlin/ink/abb/pogo/scraper/tasks/CatchOneNearbyPokemon.kt#L43

**Comment by escojoncio** [comment]
so... to get pokeballs i have to drop all my pokeballs to get pokeballs, so i drop all my pokeballs to get pokeballs... (lol xD)

**Comment by CptJackieSparrow** [comment]
i can give you my PC bro it's only visiting pokestops :D

**Comment by CosmoRing** [comment]
I will be doing this on #316

**Comment by jabbink** [comment]
Implemented in #321

**Comment by escojoncio** [comment]
Thank you, but i suppose i will have to wait until its released as jar, since i dont have any idea of how to use those builds, thank you anyway!

**Comment by escojoncio** [comment]
how much time will take until is coded into a jar file? :)

**Comment by Rofii** [comment]
@escojoncio Please be patient. It takes time between releases of jar files because several people are working on implementing several different features at once. Having said that, _probably_ within the next 6 hours and almost certainly within the next 24.

**Comment by jabbink** [comment]
#321 is merged. Closing this.
