### ISSUE TITLE
Bot using much GREAT BALL and ULTRA BALL

### ISSUE THREAD

**Issue by pvase666** [jabbink/PokemonGoBot#309]
Latest version. The Bot using so much GREAT BALL and ULTRA BALL. Even with DUDO 200CP ?

Could I edit *KT file to change it? I don't want it to use ULTRA BALL.

Thanks :dancer: 

Request:

<500CP: Using POKEBALL
500CP<X<1000CP: GREAT BALL
>1000CP: Using ULTRABALL

**Comment by jabbink** [comment]
Decrease your desired catch probability

**Comment by pvase666** [comment]
I didn't see that AGAIN. My Bad :(. Thank you

**Comment by dvasko** [comment]
```
25 srp 23:55:52: Found pokemon WEEDLE 
25 srp 23:55:52: Encountered pokemon WEEDLE with CP 184 
25 srp 23:55:52: Using ITEM_ULTRA_BALL; Using Razz Berry; Using curve 
25 srp 23:55:53: Caught a WEEDLE with CP 184 and IV 13% 
25 srp 23:55:53: Going to transfer WEEDLE with CP 184 and IV 13%; reason: CP < -1 and IV < -1%
```
isn't ultra ball little bit to much for that Weedle

**Comment by jabbink** [comment]
https://github.com/jabbink/PokemonGoBot/issues/309#issuecomment-234948524
