### ISSUE TITLE
IN_COOLDOWN_PERIOD

### ISSUE THREAD

**Issue by vdianl** [jabbink/PokemonGoBot#31]
What does this mean?
Found nearby pokestop
destination reached
IN_COOLDOWN_PERIOD
Getting map of XXX
Found nearby pokestop
destination reached
IN_COOLDOWN_PERIOD
Getting map of XXX
Found nearby pokestop
destination reached
IN_COOLDOWN_PERIOD
Getting map of XXX
Found nearby pokestop
destination reached
IN_COOLDOWN_PERIOD

**Comment by SwipeX** [comment]
there are no pokestops nearby that are able to be used.

**Comment by vdianl** [comment]
ah okay, thanks
