### ISSUE TITLE
{QUESTION} capture setup?

### ISSUE THREAD

**Issue by russr123** [jabbink/PokemonGoBot#312]
i want it to keep the top 3 80%+ CP of each type, so would these setting be right?

autotransfer=true
keep_pokemon_amount=3
sort_by_iv=true
transfer_iv_threshold=80
transfer_cp_threshold=-1

**Comment by jabbink** [comment]
>80%+ CP

Do you mean 80% IV or 80+ CP?

**Comment by dvasko** [comment]
i'm interested in setup for top 3 with 80% IV **AND** CP over 500

**Comment by jabbink** [comment]
@dvasko
```
autotransfer=true
keep_pokemon_amount=3
sort_by_iv=true
transfer_iv_threshold=80
transfer_cp_threshold=500
```

**Comment by russr123** [comment]
i still dont get what "IV" is, but i want the combat power to be at 80% no mater the number, example, MAGIKARP even at 80% CP, is still a low number, and i dont want it tossed

**Comment by dvasko** [comment]
example
1. pokemon 100% IV and cp10
2. pokemon 99% IV and cp20
3. pokemon 98% IV and cp30
4. pokemon 97% IV and cp700

and i lose 4. which is .....meh

**Comment by dvasko** [comment]
```
autotransfer=true
keep_pokemon_amount=3
sort_by_iv=true
transfer_iv_threshold=80
transfer_cp_threshold=500
```

this setup would keep 99% IV 10CP pokemons AND 75% IV 600CP pokemons.

```
autotransfer=true
keep_pokemon_amount=3
sort_by_iv=true
transfer_iv_threshold=-1
transfer_cp_threshold=-1
```

this setup would keep top 3 but then you end up with example in my previous post 

i would like to see option keep top 3 IV but they **MUST** be over XXX CP

**Comment by ohnims** [comment]
You'd need to go read up on what IV is. Unless you know what that is, the mere CP and where its slider is with regards to the semi-circle, is kinda pointless.

**Comment by nesttle** [comment]
`autotransfer=true
keep_pokemon_amount=3
sort_by_iv=true
transfer_iv_threshold=-1
transfer_cp_threshold=-1`

Is this regardless of CP? I mean, this config will keep the top 3 best IV Pokemon of each type?

**Comment by jabbink** [comment]
Yes, top 3 by IV.
