### ISSUE TITLE
[Improvement] Configurable: Loot Pokestop, Catch Pokemon, Auto Fill Incubator

### ISSUE THREAD

**Issue by CosmoRing** [jabbink/PokemonGoBot#316]
**Description:**
Change the current `walk_only` to be more flexible. Instead of `walk_only` mode you can toggle on and off the function of Loot Pokestops, Catch Pokemons and Auto Fill Incubator. 

This way you can easily create the current walk_only mode by turning everything off except Auto Fill incubator. If you are low on items you can go and turn everything off except Loot Pokestop and get all the items you want.

FYI: I'm doing this.

**Comment by wartickler** [comment]
I'm getting worried about the variables in the config file. It's already a lot more than there originally was and I don't think they are grouped in the most intuitive way. We have a lot of "if this, then not this and this, but this and this" or "if not this, then those and these but not this and these." It's starting to get messy.

**Comment by CosmoRing** [comment]
I understand you @wartickler but if you think about it, then you will have walk_only, loot_only, catch_only, walk_loot_only. And i'm already trying to group it all better. 

If you look you will see that first we can the normal settings: login, coordinates and speed. With only that you have the bot fully functional without changing anything. 

The other options are for the people that want to costume the bot. Things like what pokemons to transfer, if you want to transfer items and other things.

**Comment by classicalDonkey** [comment]
Does it matter about the order of things in the config file?  Cus I would like to have a default file (TXT) that I can edit and then copy to the config file

**Comment by CosmoRing** [comment]
Order doesn't matter.
