### ISSUE TITLE
Some issues with the 0.4.2

### ISSUE THREAD

**Issue by Leodenact** [jabbink/PokemonGoBot#324]
First of all, I'm not a programmer and I only followed the installations steps described. I don't know how to change anything except for the config.properties file.

Here are some of the issues that's happening to me right now.
1. 
C:\Users\N\Desktop\L>java -jar pogo.scraper-all-0.4.2.jar
←[31m25 jul 16:46:20: Starting Latitude setting ("latitude") not specified in co
nfig.properties! ←[0m

I already set the locations

2. The config.properties file is all a mess when i open it to set different values and coordinates. It's a LOONG text going far to the right, instead of structured with paragraph grouping. It's really annoying to edit it when the text is so long to the right side and messy.

3. I saw some people come up with solutions to pop lucky egg and evolve the family pokemons, like only pidgeys and weedle and so on. How do I write this into my config.properties to make it work? That's the only thing I use. 

Big thanks for your work, it's incredible and I hope you get the credit you deserve. I'm gonna donate once I get some income! Cheers

**Comment by pashorizer** [comment]
Use Notepad++ or Sublime Text to open the properties.

**Comment by Mewks** [comment]
I can agree there are some issues in 0.4.2 same as 0.4.1, its not loading the configuration properly and even if I edit the config json file it's not working properly. 

I've been soft banned for about 8hours now because it didnt load the location properly and must have tried to spawn me somewhere far away, I have no idea where.

**Comment by jabbink** [comment]
When it can't read the location it doesn't start at all and won't get you softbanned.

If it says it can't read the location it is because there is no location.
