### ISSUE TITLE
0.4.2 configuration

### ISSUE THREAD

**Issue by Rofii** [jabbink/PokemonGoBot#333]
Where is the configuration held for this version? I thought everything was moved from properties.config to the JSON file, but this new version seems to be releasing pokemon based on settings in the config file.

**Comment by siimveskilt** [comment]
Apparently, it was moved back.

**Comment by Leodenact** [comment]
I have set the coordinates but when I start the cmd and the bot it says that I havn't set the latitude.

Why is this ?

**Comment by siimveskilt** [comment]
Please show the relevant section & exact error message from the console.

**Comment by BryanVest** [comment]
Probably a space or something in the latitude field

**Comment by jabbink** [comment]
>I thought everything was moved from properties.config to the JSON file,

It was, then moved back and the README was adjusted as well, nothing references this JSON file anymore, so please don't assume that it is being used.

**Comment by jabbink** [comment]
@others please stop hijacking unrelated issues with your, duplicate (this has been discussed MANY times!) issues.
