### ISSUE TITLE
[Build] Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by mroge009** [jabbink/PokemonGoBot#335]
**Description:**
Trying to build the project in IntelliJ.
Used to work until release 3.
Have tried reinstalling JDK, JRE, IntelliJ, etc.
The error I get is:

Configuration with name 'default' not found.

When trying to build gradle.
Building through GitShell works fine.

**Steps to reproduce:**

1. Import project from existing sources in intelliJ.
2. Continue to gradle import window.
3. Wait for error to appear.

**Expected behavior:**
It should build without error

**Actual behavior:**
It builds with the error "Configuration with name 'default' not found."

**Version:**
Current version.  It pulls from Git.

**Comment by pr0ves** [comment]
Please, read the readme.
This error shows up because you didn't run `git submodule update --init --recursive`, so gradle doesn't find the api.
Go to the project folder and run that command from terminal.

**Comment by mroge009** [comment]
I was able to import my built git project but in intelliJ the API doesnt load properly

**Comment by jabbink** [comment]
Install the "Lombok" plugin.

**Comment by mroge009** [comment]
Still get over 100 errors of cannot find symbols.

```
C:\Users\Marc\Documents\GitHub\PokemonGoBot\lib\PokeGOAPI-Java\src\main\java\com\pokegoapi\api\pokemon\EggPokemon.java
    Error:Error:line (49)java: cannot find symbol
  symbol:   method isInUse()
  location: variable incubator of type com.pokegoapi.api.inventory.EggIncubator
C:\Users\Marc\Documents\GitHub\PokemonGoBot\lib\PokeGOAPI-Java\src\main\java\com\pokegoapi\api\PokemonGo.java
    Error:Error:line (103)java: cannot find symbol
  symbol:   method setLatitude(double)
  location: class com.pokegoapi.api.PokemonGo
    Error:Error:line (104)java: cannot find symbol
  symbol:   method setLongitude(double)
  location: class com.pokegoapi.api.PokemonGo
    Error:Error:line (105)java: cannot find symbol
  symbol:   method setAltitude(double)
  location: class com.pokegoapi.api.PokemonGo
C:\Users\Marc\Documents\GitHub\PokemonGoBot\lib\PokeGOAPI-Java\src\main\java\com\pokegoapi\api\inventory\EggIncubator.java
    Error:Error:line (75)java: cannot find symbol
  symbol:   method getRequestHandler()
  location: variable pgo of type com.pokegoapi.api.PokemonGo
    Error:Error:line (84)java: cannot find symbol
  symbol:   method getInventories()
  location: variable pgo of type com.pokegoapi.api.PokemonGo
C:\Users\Marc\Documents\GitHub\PokemonGoBot\lib\PokeGOAPI-Java\src\main\java\com\pokegoapi\main\RequestHandler.java
    Error:Error:line (80)java: cannot find symbol
  symbol:   method getRequest()
  location: variable requestIn of type com.pokegoapi.main.ServerRequest
    Error:Error:line (98)java: cannot find symbol
  symbol:   method getRequest()
  location: variable serverRequest of type com.pokegoapi.main.ServerRequest
    Error:Error:line (188)java: cannot find symbol
  symbol:   method getLatitude()
  location: variable api of type com.pokegoapi.api.PokemonGo
    Error:Error:line (189)java: cannot find symbol
  symbol:   method getLongitude()
  location: variable api of type com.pokegoapi.api.PokemonGo
    Error:Error:line (190)java: cannot find symbol
  symbol:   method getAltitude()
  location: variable api of type com.pokegoapi.api.PokemonGo
    Error:Error:line (275)java: cannot find symbol
  symbol:   method getLatitude()
  location: variable api of type com.pokegoapi.api.PokemonGo
    Error:Error:line (276)java: cannot find symbol
  symbol:   method getLongitude()
  location: variable api of type com.pokegoapi.api.PokemonGo
    Error:Error:line (277)java: cannot find symbol
  symbol:   method getAltitude()
  location: variable api of type com.pokegoapi.api.PokemonGo
```

**Comment by mroge009** [comment]
Was finally able to update a couple plugins, and now I get this:

```
Error:(59, 66) Kotlin: Unresolved reference: thenComparing
C:\Users\Marc\Documents\GitHub\PokemonGoBot\src\main\kotlin\ink\abb\pogo\scraper\Settings.kt
Error:(30, 107) Kotlin: Unresolved reference: Base64
Error:(139, 14) Kotlin: Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun CharSequence.lines(): List<String> defined in kotlin.text
Error:(139, 22) Kotlin: Cannot choose among the following candidates without completing type inference: 
@HidesMembers public inline fun <T> Iterable<???>.forEach(action: (???) -> Unit): Unit defined in kotlin.collections
@HidesMembers public inline fun <K, V> Map<???, ???>.forEach(action: (Map.Entry<???, ???>) -> Unit): Unit defined in kotlin.collections
Error:(140, 17) Kotlin: Unresolved reference: it
Error:(140, 31) Kotlin: Unresolved reference: it
Error:(143, 24) Kotlin: Unresolved reference: it
Error:(144, 37) Kotlin: Unresolved reference: it
```

**Comment by mroge009** [comment]
@pr0ves @jabbink ?  
I would really like to get back to contributing to this project.  I have evolution code written but it is hard to write it using notepad++ haha

**Comment by jabbink** [comment]
When a build fails,

1. copy the entire log, the copied parts alone tell us nothing at all.
2. gradlew tells you to use --info or --debug to show more info, often the info given then is enough to fix it yourself, so please retry and when you don't understand it, paste the entire log here.

**Comment by Cypherke** [comment]
Dont think he can run gradlew with a path that deep

**Comment by mroge009** [comment]
I gave up on IntelliJ, and trying to migrate to eclipse now.  

I am logging all the steps that I take and hopefully can hand you a write up to put on the wiki to get more people helping with development.

**Comment by mroge009** [comment]
Gradle builds and runs fine.  
When I try to import the gradle project into eclipse or intelliJ I get the default configuration error.

**Comment by weblue** [comment]
Getting the same issues. Tried with IntelliJ and with Eclipse. RTFM doesn't help. Changed the paths to be shorter when there were issues with path names but still can't load the project into an IDE

**Comment by weblue** [comment]
Installing Lombok only resolves running the code. Cloning the github still fails with the "default" issue

**Comment by weblue** [comment]
**Fix found:** 
1. Install Lombok
2. Clone the repository
3. Attempt to import the project
4. Wait for "Default" error **DO NOT CLOSE ANY DIALOGS**
5. Go to workspace folder and open the cloned project folder
6. Use the "git submodule update --init --recursive" command from cmd
7. Click okay in the IntelliJ error dialog and hit okay again to create the project

**Comment by jabbink** [comment]
^

That should work as well. Cloning via git and then manually import into IntelliJ should also work.

The order of the steps is important, and they're defined with an order in the readme because of that.
