### ISSUE TITLE
[Suggestion] Drop Items Based On Tier

### ISSUE THREAD

**Issue by javaptgl** [jabbink/PokemonGoBot#344]
**Description:**
First create a generalization of items.
Potions,Poke balls,Revives,etc.

Then for example lets take potions.
Allocate 100 space for potions.
Collect any potion and start dropping the lower tier ones once the allocated space is full.

**Comment by Killberty** [comment]
Very good Idea!

**Comment by Rofii** [comment]
+1 but only if it's optional

**Comment by Mixone-FinallyHere** [comment]
shouldn't this be closed?
