### ISSUE TITLE
Evolve mod please

### ISSUE THREAD

**Issue by miracho** [jabbink/PokemonGoBot#346]
Ty so much for this app bro. 

Is it possible to add to evolve?

**Comment by Agronis** [comment]
A quick search shows you these possible [Issues](https://github.com/jabbink/PokemonGoBot/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20evolve) that have already been opened.

More specifically, this [one](https://github.com/jabbink/PokemonGoBot/issues/5). 

I'd say it's safe to assume it'll happen sooner than later.

Kindly ask that you go ahead and close this issue and participate in another active one.
