### ISSUE TITLE
Catch error all the time, still trying to catch

### ISSUE THREAD

**Issue by Leodenact** [jabbink/PokemonGoBot#348]
Catch error it said in the cmd log, it was stuck trying to catch the same pokemon an endless of time, it didn't work and the balls where getting used so quickly. Luckily I was at the computer and could restart, but what if this happens when im afk?

Any ideas about this problem ?

**Comment by matheussaliba** [comment]
When this happened to me, i was 250/250 in my pokebank so i had to log in manually and transfer some duplicates so that the bot could catch anything again

**Comment by jabbink** [comment]
either that, or #318. either way, duplicate, or already implemented (from a duplicate)
