### ISSUE TITLE
[SUGGESTION] Better filter on ignored_pokemon

### ISSUE THREAD

**Issue by Agronis** [jabbink/PokemonGoBot#349]
Currently, if X is on list of ignored - it's not transferred regardless of CP/IV/quantity in bank.

I'd like to add more Pokemon to this list but at the same time I don't want them absorbing my bank either due to more common encounters.

There's zero reason to have 6 Dragonites, so if I come across a 7th.. I should be able to automatically filter out the lesser of the bunch.

However, I'd like to have more than two or three of other Pokemon (especially when trading comes) but just setting keep_pokemon_amount to anything higher than two means I have to actively watch/filter my bank.

So..

- **ignored_max** : Quantity of this type to be ignored before auto-transfer.

This will automatically take into effect the sort_by_iv and threshhold values leaving you with the strongest set.

This way, I can have more multiples of top tier evolutions while retaining one if not none of basic tier until I need an evolve train.

**Comment by wartickler** [comment]
Interesting. In the config file it lists all of the pokemon at the bottom. One could enter how many of each individual pokemon you want to keep like this:

`keep_pidgey=99`
'keep_rayquaza=2'

The bot could swap out better pokemon if it comes across any that are better than the ones in the bank.

**Comment by andredp** [comment]
That seems overkill... 151 config lines only for that option is too much, imo.
@Agronis approach seems better, because you probably will only use a general number for every "rare" pokemon... 

You'll never say "Okay, keep 5 Dragonites, 3.4 Snorlaxes, 7 Mews...". It's much more intuitive and useful to say "I want to keep 5 of the rare pokemons I put in the ignore list".

**Comment by jabbink** [comment]
Someone added a max_keep option recently.
