### ISSUE TITLE
New Walk Only mode is not working 

### ISSUE THREAD

**Issue by 80rrego** [jabbink/PokemonGoBot#351]
**Description:**
I use this configuration
```
# Should the bot loot the pokestops (true/false)
loot_pokestop=true

# Should the bot catch pokemons (true/false)
catch_pokemon=false

# Shout the bot auto fill incubators with eggs (true/false)
auto_fill_incubator=true
```
But at the moment I get in it start catching pokemon and with ultraballs that I dont want that the bot use them I wanna use them when I got out hunting.

**Expected behavior:**
I expect to the bot only Loot pokestops and hatch eggs.

**Actual behavior:**
The only way is adding the old WalkOnly feature in the config

Did I have to update something? I just change the Config.setup and download the new src with changes. I dont know if I have to change another feature.

Thanks

**Version:**
0.4.2

**Comment by CosmoRing** [comment]
There isn't any release with this new walk only. Only the `develop` branch has the needed code.
