### ISSUE TITLE
[Suggestion] Color Code Profile Updates

### ISSUE THREAD

**Issue by Scoboose** [jabbink/PokemonGoBot#353]
Can you please color code profile updates?  Would be great to at a glance see the last update with out searching for it.

**Comment by Scoboose** [comment]
Yes #357 Is what I am asking.

**Comment by omar972** [comment]
If you compile from source, you would be satisfied.

**Comment by jabbink** [comment]
Implemented.

**Comment by Scoboose** [comment]
Thanks!
