### ISSUE TITLE
Error with Google Login

### ISSUE THREAD

**Issue by ColeB27** [jabbink/PokemonGoBot#355]
Logging in to game server...
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException
at com.pokegoapi.auth.GoogleLogin.login(GoogleLogin.java:160)
at ink.abb.pogo.scraper.MainKt.main(Main.kt:85)

This is the error message I receive when trying to sign in with google. When the token variable is cleared in config. It runs, but when it is filled. It does not run.

**Comment by omar972** [comment]
Clear it, the bot automatically fills it with a new token when it starts, and it expires after an hour or so, so the token you have right now is expired.

**Comment by li24yang75** [comment]
because the token that the bot fills in is not correct. you need to fill in the correct token manually.

**Comment by omar972** [comment]
What do you mean is not correct? Am I supposed to replace it with the short one? The one that is after "Logged in as"?

**Comment by li24yang75** [comment]
yes. replace it with the short one.

**Comment by omar972** [comment]
If this works, I love you.

**Comment by omar972** [comment]
@li24yang75 Either I'm not doing it correctly, or it doesn't work. I'm doing all this through the 0.4.2 release, not through the source, could that be the reason?

**Comment by li24yang75** [comment]
i donot have  this problem. it works well for me.  Both prebuilt version and source code version, it works well. Maybe it is because the format of your file. You can leave your email here. I will send you my config.properties file. then you just need to replace my token with your own token.

**Comment by li24yang75** [comment]
@omar972

**Comment by omar972** [comment]
@li24yang75 omarelsebai3@yahoo.com
