### ISSUE TITLE
Login: IllegalStateException

### ISSUE THREAD

**Issue by johndoeisalive** [jabbink/PokemonGoBot#356]
**Description:**
PokemonGoBot fails to login

**Steps to reproduce:**

1. Fill in config.properties blanks, place in same dir as `.jar`
2. `java -jar pogo.scraper-all-0.4.2.jar`

**Expected behavior:**
pogo.scraper runs 

**Actual behavior:**
Exception thrown.

**Stacktrace (If it's a crash):**
```
25 Jul 22:09:19: Display Keepalive Coordinates setting ("display_keepalive") not specified, defaulting to "true".
Logging in to game server...
Exception in thread "main" java.lang.IllegalStateException: if (token.contains("poke…eshToken(token)
        } must not be null
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:90)
```

**Version:**
`pogo.scraper-all-0.4.2.jar`, from releases page

**Other**
It failed like this for a couple of tries, then it decided to work. I stopped the bot so I could start it again in a tmux window, but now it won't start again.

**Comment by omar972** [comment]
Make sure the token line is clear, so it's only "token=" with nothing after it.

**Comment by johndoeisalive** [comment]
I've tried `token=<TOKEN>` `token=` and removing it with a comment `#token=`. I checked for any silly whitespace characters, but nothing.

All of these display the same behaviour?

**Comment by omar972** [comment]
Are you sure you actually saved the file?

**Comment by johndoeisalive** [comment]
Positive. Not sure what the issue was, but I removed the offending file and re-curl'd the template. Worked first time with the new file.

Thanks for the help.
