### ISSUE TITLE
[SUGGESTION] Changes to Console Output

### ISSUE THREAD

**Issue by Killberty** [jabbink/PokemonGoBot#357]
**Description:**

- Make status outputs like these blue, because they are really hard to find, escpecially if some exceptions get printed:
  - Profile update: 1081915 XP on LVL 26; 181915/200000 (90.96%) to LVL 27
  - XP gain: 3760 XP; Pokemon caught/transferred: 13/11; Items caught/dropped: 0/0; Pokebank 171/250; Stardust 342688
- Make rare events orange
  - Egg hatching and and putting eggs in incubators (thx @Agronis )
  - Level ups maybe
- Allow filtering
  - Every color has a different meaning (like red for error, green for sucess, blue for status eventually etc.) so maybe allow filtering Output by color
  - Also allow filtering for exceptions (i know it has been requested already, but it fits here)

**Version:**
0.4.2

**Comment by pascalpfeil** [comment]
_

**Comment by Agronis** [comment]
I'll toss in a specific request for Egg updates.

**Comment by WebmasterNikos** [comment]
Consider making the username part of the profile update, would make it easier to tell which console is which when running multiple bots.

**Comment by jabbink** [comment]
Implemented I think.
