### ISSUE TITLE
Wrong read of CP and IV

### ISSUE THREAD

**Issue by EasyNV** [jabbink/PokemonGoBot#360]
Hello, this morning when I used your bot this happened.

26 Jul 06:35:33: Found pokemon GOLBAT
26 Jul 06:35:33: Encountered pokemon GOLBAT with CP 815 and IV 62%
26 Jul 06:35:33: Using ITEM_POKE_BALL
26 Jul 06:35:34: Caught a GOLBAT with CP 815 and IV 62%
 Stamina: 13 | Attack: 6 | Defense: 9 | IV: 28 (62%): [200x XP, 3x Candy, 100x S
tardust]
26 Jul 06:35:34: Going to transfer GOLBAT with CP 354 and IV 71%; reason: CP < 5
00 and IV < 80%

In the transfer the bot seems like did not read the CP and IV correctly.

**Steps to reproduce:**

1. I do not know how to reproduce this bug.

**Version:**
Latest develop.

Sorry if this issues kinda bad and lacking information, as this was my first time writing this. Thankyou

**Comment by cwliias** [comment]
Whats your settings in your config file?

**Comment by chriszhangz** [comment]
I think the bot transfered another GOLBAT in your bag cause it is the only one before you catch this one with higher CP. IMO it seems nothing wrong.

**Comment by pilotchute** [comment]
It's NOT transferring the GOLBAT you've just caught. 
It IS transferring the GOLBAT you already had, that wasn't as good as the one you just caught.

Working as intended.

**Comment by Letrico** [comment]
@chriszhangz is correct. You should have a Golbat in your bag with lower CP.

**Comment by omar972** [comment]
Yeah, I had this happen to me as well, took me a good 5 minutes to understand what just happened, but there is no issue here.

**Comment by EasyNV** [comment]
Ah I see, then its my bad. Thankyou everyone :D
