### ISSUE TITLE
"Configuration with name 'default' not found" after running refresh dependencies

### ISSUE THREAD

**Issue by weblue** [jabbink/PokemonGoBot#362]
**Description:**
Getting the title error after forking and attempting to load the project into IntelliJ IDE

**Steps to reproduce:**

1. Download a fresh install
2. Open the project in IDE

**Stacktrace (If it's a crash):**
http://pastebin.com/ZurpGRtn

**Version:**
#352

**Comment by weblue** [comment]
Issue is solved by using Git instead of Github from IntelliJ

**Comment by mroge009** [comment]
@weblue How did you get the project to run from intelliJ?  
What steps did you take from a fresh install because mine doesnt work :(

**Comment by weblue** [comment]
It doesn’t work as is. I think they’re adding some information to the project to get it to run on intelliJ
