### ISSUE TITLE
Gradlew Run Issue.

### ISSUE THREAD

**Issue by Lenovotro** [jabbink/PokemonGoBot#364]
**Description:**
Trying to run  "gradlew run", but end with this error. Though I can run through Java Jar.
**Steps to reproduce:**

1. [Open Terminal]
2. [cd to folder.]
3. [run: Gradlew run]

**Stacktrace (If it's a crash):**
Build file 'D:\Users\xxxx\Desktop\PokemonGoBot-develop\build.gradle' line: 61

* What went wrong:
A problem occurred evaluating root project 'pogo.scraper'.
> Could not resolve all dependencies for configuration ':compile'.
   > Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.516 secs

**Version:**
[0.4.2]

**Comment by weblue** [comment]
Follow the exact steps given to run the project from source code. I had the same issue and it was resolved this way

**Comment by Lenovotro** [comment]
Not the best at this stuff yet. Learned plenty, but could you give a little but more direction?

**Comment by weblue** [comment]
**Usage (from source)**

Clone this repo: git clone https://github.com/jabbink/PokemonGoBot.git && cd PokemonGoBot or download the zip
Run git submodule update --init --recursive
Run from terminal/cmd::gradlew build
Rename ./config.properties.template to ./config.properties
Modify config.properties as you please
To run the bot directly from console run gradlew run

**Comment by weblue** [comment]
do this exactly to the t

**Comment by Lenovotro** [comment]
@weblue Oh that..

**Comment by omar972** [comment]
Check [Known Issues](https://github.com/jabbink/PokemonGoBot#known-issues) if it still doesn't work, your solution is there.
