### ISSUE TITLE
Setting up with IDE?

### ISSUE THREAD

**Issue by weblue** [jabbink/PokemonGoBot#366]
What IDE have you guys used to setup/run/modify the bot? I have tried setting up with IntelliJ but it's giving me plenty of errors and I'm having a difficult time running it.

**Comment by mroge009** [comment]
Yeah intelliJ worked for me only on release 2.  

Im trying eclipse now.

**Comment by Cypherke** [comment]
use gradle to run the bot... intellij has problems with recognizing the API correctly

**Comment by pr0ves** [comment]
Install lombok to recognize correctly the api

**Comment by jabbink** [comment]
@mroge 

>Im trying eclipse now.

Don't use eclipse. It's a pain in the ass and hardly works.
