### ISSUE TITLE
[SUGGESTION] seek lure clusters or hd spawn areas

### ISSUE THREAD

**Issue by MASSV** [jabbink/PokemonGoBot#369]
Think this would also go with #220 to stay in one area...

I know certain areas with tons of lures and endless stuff to catch, however the bot wont stay there after it catches the immediate 6-8 things spawned. Would be nice if it detected lures/high spawns and circled the area. Might be something for the future

**Comment by MrJokerer** [comment]
Sounds like we  mean about the same thing.  Because of all lures in central park  I would want to basically make a box around it so bot would stay where lures are.

**Comment by jabbink** [comment]
#54
