### ISSUE TITLE
Boosted (Rose Pedal) Pokestops

### ISSUE THREAD

**Issue by davidmann4** [jabbink/PokemonGoBot#37]
https://github.com/FeroxRev/Pokemon-Go-Rocket-API/issues/36

I already messed around with the c# bot - a pokestop can have an ActivePokemon this is encounterable

maybe you find this info usefull - cheers

**Comment by davidmann4** [comment]
hmm seems like the java api does not map this property 

https://github.com/Grover-c13/PokeGOAPI-Java/blob/181e441effd837a8b38c9268040297bba5ae706c/src/main/java/com/pokegoapi/api/map/fort/FortDetails.java

**Comment by davidmann4** [comment]
message PokemonFortProto {
    string FortId = 1;
    int64 LastModifiedMs = 2;
    double Latitude = 3;
    double Longitude = 4;
    int32 Team = 5;
    int32 GuardPokemonId = 6;
    int32 GuardPokemonLevel = 7;
    bool Enabled = 8;
    ENUM.Holoholo.Rpc.FortType FortType = 9;
    int64 GymPoints = 10;
    bool IsInBattle = 11;
    //unknown ActiveFortModifier = 12;
    Holoholo.Rpc.MapPokemonProto ActivePokemon = 13;
    int64 CooldownCompleteMs = 14;
    ENUM.Holoholo.Rpc.Sponsor.Types.FortSponsor.Sponsor Sponsor = 15;
    ENUM.Holoholo.Rpc.RenderingType.Types.FortRenderingType.RenderingType RenderingType = 16;
 }

**Comment by jabbink** [comment]
>a pokestop can have an ActivePokemon this is encounterable

Oh wow, didn't even know that. Will look into this tomorrow.

**Comment by davidmann4** [comment]
```json
 {  
                     "fortId":"47b4a55ad8c54454940396aaf0601e02.16",
                     "lastModifiedMs":"1469000053563",
                     "latitude":45.030225,
                     "longitude":-93.318969,
                     "enabled":true,
                     "fortType":1,
                     "activePokemon":{  
                        "spawnpointId":"47b4a55ad8c54454940396aaf0601e02.16",
                        "encounterId":"2142514281",
                        "pokedexTypeId":"V0021_POKEMON_SPEAROW",
                        "expirationTimeMs":"1469001133514"
                     }
                  },
                  {  
                     "fortId":"5ec40620884740d98d6969e372156c5c.16",
                     "lastModifiedMs":"1468999658570",
                     "latitude":45.029967,
                     "longitude":-93.319217,
                     "enabled":true,
                     "fortType":1,
                     "activePokemon":{  
                        "spawnpointId":"5ec40620884740d98d6969e372156c5c.16",
                        "encounterId":"1178527421",
                        "pokedexTypeId":"V0013_POKEMON_WEEDLE",
                        "expirationTimeMs":"1469001098512"
                     }
                  },
```

maybe usefull for you

**Comment by jabbink** [comment]
Implemented
