### ISSUE TITLE
question.. IV calculations.... how does the bot get them? are the 100%? or a "guess"?

### ISSUE THREAD

**Issue by russr123** [jabbink/PokemonGoBot#372]
IV calculations.... how does the bot get them? are the 100%? or a "guess"?
example... from the bot
Have MAGIKARP () with 48 CP and IV 88% 
Have MAGIKARP () with 138 CP and IV 84% 
Have MAGIKARP () with 10 CP and IV 82% 
Have MAGIKARP () with 142 CP and IV 80% 
Have MAGIKARP () with 140 CP and IV 64%..
but if i use any of the online calcs, i get different numbers... im ready to evolve him, but need to know what 1 ...
does the "xl/xs" have input on this?

**Comment by russr123** [comment]
also, is there a regular forum to ask these questions?

**Comment by Letrico** [comment]
there are 3 stats for IV which the % comes from X/45 x 100.

The new source version updated it to show better representation. Maybe in the next prebuild?

This is from running from the develop branch:
 Stamina: 8 | Attack: 4 | Defense: 4 | IV: 16 (35%)

**Comment by russr123** [comment]
just seams odd, the 138 CP and IV 84% is a xs, 30hp 2500dust
the   140 CP and IV 64% is a xl, 34hp 3000dust

i would think the XL is better

**Comment by Letrico** [comment]
Well it does not matter what size or height they are, it is the IV that matters.

**Comment by mroge009** [comment]
Size doesn't matter.  IV is what stays the same through evolution while size is variable.
