### ISSUE TITLE
token config error

### ISSUE THREAD

**Issue by hifiaz** [jabbink/PokemonGoBot#373]
Exception in thread "main" java.lang.NoSuchMethodError: java.io.BufferedReader.lines()Ljava/util/stream/Stream;
	at ink.abb.pogo.scraper.Settings.writeToken(Settings.kt:139)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:105)

**Comment by Letrico** [comment]
You gotta remove the token from config.properties. Set it back to token= instead of token=whatevertokenitmaybe

**Comment by ansalls** [comment]
I have to manually delete the auto added token every hour os so for it to log in again. For some reason the generated token expires and isn't renewed .

**Comment by Letrico** [comment]
@ansalls Which version are you using? I have left my bot running for close to 12 hours while sleeping without a problem.

**Comment by ansalls** [comment]
0.4.2. 

This is what's generated until I go delete the token that's generated by the jar

Logging in to game server...
Logged in as ***** with token TGT-6278608-qNnorOciMNXAbXLl6H3TPYISnQvpcC4kjb2xA666wnlHc7bcLQ-sso.pokemon.com
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException: Error  in API Url 
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:149)
	at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:79)
	at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
	at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:107)

**Comment by Letrico** [comment]
@ansalls is that after you try to rerun the bot again? The bot should be able to auto login by itself every ~20 minutes

**Comment by ansalls** [comment]
Yes. I tried rerunning it multiple times and it was through trial and error that I found the token to be the issue.

**Comment by Letrico** [comment]
@ansalls I know for sure is when the token is expired, I have to manually remove them before starting the bot again but once it runs, it will auto renew the token as long as the bot is running.

But I'm using google auth, are you using PTC/google?

**Comment by ansalls** [comment]
Mine, as far as I can tell, does NOT auto renew. It could be that I'm using PTC.

**Comment by miracho** [comment]
yea i've this problem too bro.

**Comment by GeitV** [comment]
I've have had this issue about expiring token all the time, seems that it is PTC related then only :( Hope a fix might come for it

**Comment by miracho** [comment]
try again bro. it is fixed.

**Comment by GeitV** [comment]
Alright, thanks for headsup, will try :)

**Comment by pashorizer** [comment]
You should remove the Token from your post
