### ISSUE TITLE
Spamming of token refresh message

### ISSUE THREAD

**Issue by ismooch** [jabbink/PokemonGoBot#374]
**Description:**
Whenever the token is refreshed for for persistent google login. it spams the console. Probably around 2 - 3000 lines of the alert. This happens about ever 15 - 20 minutes for me

**Steps to reproduce:**

1. Login with a google account
2. wait 15 - 30 minutes
3. Should see a spammed message in console about refreshing the token.

This doesn't seem to hinder anything.. just jarring to be seen. I looked through a few of the posted issues but couldn't find a post related to this.

**Comment by Letrico** [comment]
Can replicate. It displays the refresh token 5 times before it gets to authentication.

**Comment by ismooch** [comment]
yeah.. its not really an issue.. just... a lot of screen space... just thought I would point it out. Thanks for the reply.

**Comment by BryanVest** [comment]
Known issue with the API this is based off of. Nothing to fix here

**Comment by jabbink** [comment]
@BryanVest can you link to the API issue?

**Comment by jabbink** [comment]
Should be fixed with 0.4.3
