### ISSUE TITLE
[Feature Request] Use ITEM_POKE_BALL for blacklisted Pokemon

### ISSUE THREAD

**Issue by sakindia123** [jabbink/PokemonGoBot#375]
The reason I say this is that the bot wastes Ultra Balls for 300 CP Rattatas and Pidgeys,which i have set to transfer regardless of CP

**Comment by Mewks** [comment]
That's a really good idea. I second this!

**Comment by pvase666** [comment]
Change your desired_catch_probability value. I set 0.45 and Bot always use POKEBALL for PKMs that have <500CP

**Comment by jabbink** [comment]
Use @pvase666's solution for now

**Comment by jabbink** [comment]
Closed in favor of #391
