### ISSUE TITLE
[Feature Request] ignoring poke stops

### ISSUE THREAD

**Issue by ismooch** [jabbink/PokemonGoBot#378]
A buddy of mine lives in high pokestop population area, and his bot does nothing but hit pokestops for a solid 20 minutes before finding one pokemon. He wanted to know if a config setting for ignoring poke stops or a delay timer for how often poke stops are visited could be a possibility.

**Comment by Simpuhl** [comment]
The issue is that it tags stuff/catches things and keeps moving. What it needs to do is tag/catch pokemon and stay still until there is nothing is to tag/catch in that little area and then start moving

**Comment by MrJokerer** [comment]
A delay at poke stop?  Or like if pokemon present stop movement catch,  check for pokemon if none then move to next pokestop.  I feel like this is really only needed for lured pokestops  though

**Comment by MrJokerer** [comment]
@pashorizer does bot ever deviate off straight line to pokestop?

**Comment by pashorizer** [comment]
Nope, always straight to the next available pokestop

**Comment by jabbink** [comment]
0.4.3 has

```
# Should the bot loot the pokestops (true/false)
loot_pokestop=true
```
