### ISSUE TITLE
config.properties not recognized

### ISSUE THREAD

**Issue by HoneyWheat** [jabbink/PokemonGoBot#379]
Hi,
I noticed a strange behaviour. First I couldn't login because of "Illegal State Exception" this misguides me to open an issue #377. Noticed that there were more similar bugs already reported, I closed mine. But nothing worked, so I renamed my config.properties and wtf? The app started still with illegal state exception instead of file not found. I played a little, removed settings and some sort of that. When I start the app it does not recognize the config file next to it. I also removed all rights for Pokemon go from the Google account. No effect.

There are several bugs #317,#377 etc but my apprehension is that there is a bigger problem than simply removing the token line (which not worked for me). I mean there are several issues, are you sure (100%) that those issues aren't related to this? Who cross checks if the app is recognizing the changes in the config file?

Directory of F:\Users\*********\Downloads\pogo

26.07.2016  07:21    <DIR>          .
26.07.2016  07:21    <DIR>          ..
26.07.2016  07:10             5.371 __config__properties
26.07.2016  06:50                96 pogo.bat
23.07.2016  23:41        10.149.895 pogo.scraper-all-0.3.0.jar
26.07.2016  02:09         8.026.579 pogo.scraper-all-0.4.2.jar
               4 File(s)     18.181.941 bytes
               2 Dir(s)  380.708.204.544 bytes free

F:\Users\*********\Downloads\pogo>java -jar pogo.scraper-all-0.4.2.jar
26 Jul 07:22:09: Desired chance to catch a Pokemon with 1 ball setting ("desired_catch_probability") not specified, defaulting to "0.8".
26 Jul 07:22:09: minimum keep pokemon amount setting ("keep_pokemon_amount") not specified, defaulting to "1".
26 Jul 07:22:09: Display Pokestop Name setting ("display_pokestop_name") not specified, defaulting to "false".
26 Jul 07:22:09: Sort by IV first instead of CP setting ("sort_by_iv") not specified, defaulting to "false".
Logging in to game server...
Exception in thread "main" java.lang.IllegalStateException: if (token.contains("poke?eshToken(token)
        } must not be null
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:90)

**Comment by Letrico** [comment]
did you used to run the old version 0.4.1? It used to create a weird json file

**Comment by HoneyWheat** [comment]
No. Used 0.3.0 before, then 0.4.2. Can't find any other file in my directory than I posted.

**Comment by jabbink** [comment]
What are the contents of your config?

**Comment by HoneyWheat** [comment]
As mentioned, I can edit my config file and for example put some senseless stuff in it, but it is not regognized. But to fullfill your request:

# PTC/Google login credentials
username=******

# Choose plaintext or base64'd password
password=******
base64_password=

#Kölner Dom
latitude=50.941248
longitude=6.956921

preferred_ball=ITEM_POKE_BALL
display_keepalive=true

# minimum keep pokemon amount setting ("keep_pokemon_amount") not specified, defaulting to "1"
keep_pokemon_amount=1

# Display Pokestop Name setting ("display_pokestop_name") not specified, defaulting to "false".
display_pokestop_name=false

# Sort by IV first instead of CP setting ("sort_by_iv") not specified, defaulting to "false".
sort_by_iv=false

# Desired chance to catch a Pokemon with 1 ball setting ("desired_catch_probability") not specified, defaulting to "0.8".
desired_catch_probability=0.8

## Walking
# Meters per second
speed=2.778

## Items drop
# should the bot EVER drop items (true/false)
drop_items=true

# max number of each item that the bot should keep if "drop_items" is enabled
# use -1 in a item to never drop this specific item
item_revive=20
item_max_revive=10
item_potion=10
item_super_potion=30
item_hyper_potion=30
item_max_potion=30
item_poke_ball=50
item_great_ball=40
item_ultra_ball=40
item_master_ball=40
item_razz_berry=40

## Extra Info
# should the bot display information of where it's walking to (true/false)
display_walking_nearest_unused=false

# should the bot display rewards pokestop (true/false)
display_pokestop_rewards=true

# should the bot display rewards when catching pokemon (true/false)
display_pokemon_catch_rewards=true

## Pokemon Transfer
# should the bot auto transfer duplicate pokemon
autotransfer=true

# Minimum IV percentage to keep a pokemon (to ignore IV: use -1)
# between 0 and 100, suggested 80
transfer_iv_threshold=49

# Minimum CP to keep a pokemon (to ignore CP: use -1)
transfer_cp_threshold=400

# Only walk (hatch eggs, don't collect pokemon or pokestops)
walk_only=false

# list of pokemon you don't want to transfer regardless of CP
# the names must be divided by a ","
# if you want all pokemons to be transferred just leave it blank
#ignored_pokemon=EEVEE,MEWTWO,CHARMANDER
ignored_pokemon=MISSINGNO,BULBASAUR,IVYSAUR,VENUSAUR,CHARMANDER,CHARMELEON,CHARIZARD,WARTORTLE,BLASTOISE,METAPOD,BUTTERFREE,BEEDRILL,FEAROW,EKANS,ARBOK,PIKACHU,RAICHU,SANDSHREW,SANDSLASH,NIDORINA,NIDOQUEEN,NIDORINO,NIDOKING,CLEFAIRY,CLEFABLE,NINETALES,JIGGLYPUFF,WIGGLYTUFF,GOLBAT,ODDISH,GLOOM,VILEPLUME,PARAS,PARASECT,VENONAT,VENOMOTH,DIGLETT,DUGTRIO,MEOWTH,PERSIAN,PSYDUCK,GOLDUCK,MANKEY,PRIMEAPE,GROWLITHE,ARCANINE,POLIWHIRL,POLIWRATH,ABRA,KADABRA,ALAKAZAM,MACHOP,MACHOKE,MACHAMP,BELLSPROUT,WEEPINBELL,VICTREEBEL,TENTACOOL,TENTACRUEL,GEODUDE,GRAVELER,GOLEM,PONYTA,RAPIDASH,SLOWPOKE,SLOWBRO,MAGNEMITE,MAGNETON,FARFETCHD,DODUO,DODRIO,SEEL,DEWGONG,GRIMER,MUK,SHELLDER,CLOYSTER,HAUNTER,GENGAR,ONIX,VOLTORB,ELECTRODE,EXEGGCUTE,EXEGGUTOR,CUBONE,MAROWAK,HITMONLEE,HITMONCHAN,LICKITUNG,KOFFING,WEEZING,RHYHORN,RHYDON,CHANSEY,TANGELA,KANGASKHAN,HORSEA,SEADRA,SEAKING,STARYU,STARMIE,MR_MIME,SCYTHER,JYNX,ELECTABUZZ,MAGMAR,PINSIR,TAUROS,MAGIKARP,GYARADOS,LAPRAS,DITTO,EEVEE,VAPOREON,JOLTEON,FLAREON,PORYGON,OMANYTE,OMASTAR,KABUTO,KABUTOPS,AERODACTYL,SNORLAX,ARTICUNO,ZAPDOS,MOLTRES,DRATINI,DRAGONAIR,DRAGONITE,MEWTWO,MEW

# list of pokemon you always want to trancsfer regardless of CP
#obligatory_transfer=DODUO,RATTATA,CATERPIE,PIDGEY
obligatory_transfer=ZUBAT,SPEAROW,PIDGEY,PIDGEOTTO,PIDGEOT,WEEDLE,KAKUNANIDORAN_FEMALE,NIDORAN_MALE,KRABBY,KINGLER,CATERPIE,SQUIRTLE,GASTLY,RATTATA,POLIWAG,GOLDEEN,DROWZEE

#List of pokemon names
#MISSINGNO
#BULBASAUR
#IVYSAUR
#VENUSAUR
#CHARMANDER
#CHARMELEON
#CHARIZARD
#SQUIRTLE
#WARTORTLE
#BLASTOISE
#CATERPIE
#METAPOD
#BUTTERFREE
#WEEDLE
#KAKUNA
#BEEDRILL
#PIDGEY
#PIDGEOTTO
#PIDGEOT
#RATTATA
#RATICATE
#SPEAROW
#FEAROW
#EKANS
#ARBOK
#PIKACHU
#RAICHU
#SANDSHREW
#SANDSLASH
#NIDORAN_FEMALE
#NIDORINA
#NIDOQUEEN
#NIDORAN_MALE
#NIDORINO
#NIDOKING
#CLEFAIRY
#CLEFABLE
#VULPIX
#NINETALES
#JIGGLYPUFF
#WIGGLYTUFF
#ZUBAT
#GOLBAT
#ODDISH
#GLOOM
#VILEPLUME
#PARAS
#PARASECT
#VENONAT
#VENOMOTH
#DIGLETT
#DUGTRIO
#MEOWTH
#PERSIAN
#PSYDUCK
#GOLDUCK
#MANKEY
#PRIMEAPE
#GROWLITHE
#ARCANINE
#POLIWAG
#POLIWHIRL
#POLIWRATH
#ABRA
#KADABRA
#ALAKAZAM
#MACHOP
#MACHOKE
#MACHAMP
#BELLSPROUT
#WEEPINBELL
#VICTREEBEL
#TENTACOOL
#TENTACRUEL
#GEODUDE
#GRAVELER
#GOLEM
#PONYTA
#RAPIDASH
#SLOWPOKE
#SLOWBRO
#MAGNEMITE
#MAGNETON
#FARFETCHD
#DODUO
#DODRIO
#SEEL
#DEWGONG
#GRIMER
#MUK
#SHELLDER
#CLOYSTER
#GASTLY
#HAUNTER
#GENGAR
#ONIX
#DROWZEE
#HYPNO
#KRABBY
#KINGLER
#VOLTORB
#ELECTRODE
#EXEGGCUTE
#EXEGGUTOR
#CUBONE
#MAROWAK
#HITMONLEE
#HITMONCHAN
#LICKITUNG
#KOFFING
#WEEZING
#RHYHORN
#RHYDON
#CHANSEY
#TANGELA
#KANGASKHAN
#HORSEA
#SEADRA
#GOLDEEN
#SEAKING
#STARYU
#STARMIE
#MR_MIME
#SCYTHER
#JYNX
#ELECTABUZZ
#MAGMAR
#PINSIR
#TAUROS
#MAGIKARP
#GYARADOS
#LAPRAS
#DITTO
#EEVEE
#VAPOREON
#JOLTEON
#FLAREON
#PORYGON
#OMANYTE
#OMASTAR
#KABUTO
#KABUTOPS
#AERODACTYL
#SNORLAX
#ARTICUNO
#ZAPDOS
#MOLTRES
#DRATINI
#DRAGONAIR
#DRAGONITE
#MEWTWO
#MEW

**Comment by jabbink** [comment]
That's not an answer to my question.

**Comment by Letrico** [comment]
Hahah mate, you need to keep token= in the config. You can't completely remove it out from the config. That is why you get token cannot be null.

`# PTC/Google login credentials
username=XXX@XXX.com

# Choose plaintext or base64'd password
password=XXX
#base64_password=

# Token to login directly
token=
latitude=something
longitude=something

**Comment by jabbink** [comment]
Tried to run it with PTC login without the `token=` in the config and it works. I am on `develop` though

**Comment by HoneyWheat** [comment]
I tried everything with the token line. It is not only the login, I mean if the config file is not recognized by the app all changes are questioned. Does the app correctly drop pokemons and items? I tested it with a complete fresh downloaded config file from github still not working. No config file should result in an error message not working. So this is definitly NOT depending on the contents of the config file! But if you want my config file ... files.qool.world/config.properties

**Comment by jabbink** [comment]
Well, the config file can be found for everyone else. Once in a while someone claims it can't find it and always it turns out the config is not named properly, something you claim is done correctly. So yeah, when your operating system/file system tells Java that the file doesn't exist, we can't really help you anymore.

**Comment by HoneyWheat** [comment]
Anyway. How can I clean everything, haven't "played" for 2 days now. :(

**Comment by Cy4n1d3** [comment]
`__config__properties` is not a valid name for the config file, is it?

**Comment by HoneyWheat** [comment]
No. "config.properties" anything else is for my backup purposes

**Comment by Cy4n1d3** [comment]
In the directory listing you've provided I can't see config.properties, that's why I'm asking.

**Comment by HoneyWheat** [comment]
Does Scraper store data somewhere? Must get rid of any cached data. Thats all I care at the moment.

**Comment by Letrico** [comment]
Why don't you just make a new folder and then download 0.4.3 and make a new config.properties and run it from there?

**Comment by Cy4n1d3** [comment]
Can you provide a screenshot of the actual files inside the folder you're trying to run the bot from?
I'm almost certain you're doing something wrong, there is no cached data on current versions.

**Comment by Letrico** [comment]
You know what. Can you show what is inside pogo.bat?

**Comment by pr0ves** [comment]
The error is `if (token.contains("poke?eshToken(token)} must not be null` which has been fixed in the new release. 
Download the new version and try that one

**Comment by lawlatron** [comment]
Im having issues also, won't recognise my config.properties no matter what I try

Exception in thread "main" java.io.FileNotFoundException: config.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:59)

Is what terminal throws up, I must be missing something but I haven't a clue what as Ive followed the instructions a fair few times now

**Comment by jabbink** [comment]
You probably didn't name the config file correctly.

You probably mistakenly named it `config.properties.txt`; remove the `.txt` part.

**Comment by lawlatron** [comment]
No it is names config.properties, made very sure to not have the txt in the file name

how many files should I have in the folder, just the 2 i.e. config.properties and pogo.scraper-all-0.4.3.jar, or do I need all that other stuff as well?

**Comment by HoneyWheat** [comment]
I followed Letricos suggestion: 

> Create a new folder and run it from there.

 Sounds silly but it works. Same jar, bat and config file. *Headbang*

Thx

**Comment by jabbink** [comment]
@lawlatron are you executing `java -jar pogo.scraper-all-0.4.3.jar` or are you in another directory and run for example `java -jar Downloads/pogo.scraper-all-0.4.3.jar`

In the last case: the config has to be in the directory from where you execute it, afaik.

**Comment by lawlatron** [comment]
I'll Screen shot my folder on the desktop in a sec, and show you the command line Im executing, its probably something really stupid Im doing wrong as Im trying to sort it in-between jobs at work lol

**Comment by lawlatron** [comment]
right so Im executing from the folder that the files are in

and executing with _java -jar pogo.scraper-all-0.4.3.jar_

![screen shot 2016-07-27 at 13 19 23 copy](https://cloud.githubusercontent.com/assets/20682172/17175067/61e81594-53fd-11e6-8851-2c5b8a437dfe.png)

and then This is what it says

![screen shot 2016-07-27 at 13 20 28 copy](https://cloud.githubusercontent.com/assets/20682172/17175086/6dd8d848-53fd-11e6-929e-a23b9606077b.png)

As far as I can tell Im doing things right, as far as instructions are concerned, and my brain is hurting now as I can't figure out what Im doing wrong, and I know it is something stupid

**Comment by jabbink** [comment]
Can you make a screenshot of what the `ls` command says?

**Comment by lawlatron** [comment]
![screen shot 2016-07-27 at 13 36 47 copy](https://cloud.githubusercontent.com/assets/20682172/17175624/7216513a-5400-11e6-9d4d-62f2eebb8bd6.png)

you mean this?

**Comment by jabbink** [comment]
No, `ls`
