### ISSUE TITLE
Naming Pokemon by IV? 

### ISSUE THREAD

**Issue by kycjesus** [jabbink/PokemonGoBot#381]
Automatically naming pokemon their IV would be a cool feature, 

once you come back to the game after the bot's been running it'd make it easier to decide what to keep and what to evolve and keep as an end game pokemon.

**Comment by Cypherke** [comment]
At the moment the program doesn't release favorite or renamed pokemon. So renaming them would be counter productive.

**Comment by MrJokerer** [comment]
Issue #167 is the same as thus and at the bottom brought up a pretty good possible solution  to the new updates
