### ISSUE TITLE
[suggestions] always try to catch pokemon not in pokedex

### ISSUE THREAD

**Issue by WeirdlyChosen** [jabbink/PokemonGoBot#382]
AFAIK, bot will not try to catch pokemon below the catch ratio stated in config.properties
It should be able to try to catch new pokemon to complete pokedex regardless of catch ratio.

**Version:**
0.4.2

**Comment by Rofii** [comment]
If you mean "desired_catch_probability" then you seem to be misunderstanding how it works. The bot _tries_ to catch everything.

**Comment by WeirdlyChosen** [comment]
@Rofii strange, because I put bot in a place with a lot of Rhyhorn but it didn't catch any nor regitered to pokedex.
I see rhyhorn before and after running bot.

**Comment by jabbink** [comment]
@Rofii is correct, it literally catches everything around you except for lured pokemon, which will be implemented in the API (and therefore bot) soon I guess.
