### ISSUE TITLE
display_nearest_unused not working?

### ISSUE THREAD

**Issue by PancakeZik** [jabbink/PokemonGoBot#383]
**Description:**
Since the last commits, it looks like the display_nearest_unused=false on settings doesn't have any effect at all. This makes the console a lot less cleaner. 
I also think the pokemon stats after catching should be optional (this adds another necessary line).

**Version:**
Latest commit, #352

**Comment by jabbink** [comment]
Never heard of `display_nearest_unused`. Do you mean `display_keepalive` which is still a thing?

**Comment by PancakeZik** [comment]
@jabbink sorry, might have been something old in my config file, it used to work before. Probably got removed. I still think the console could show less logging, but it's fine.
Cheers

**Comment by PancakeZik** [comment]
Just found it, it was removed with commit #199, it was there before that. Would be nice to have it back.

**Comment by jabbink** [comment]
What's wrong with `display_keepalive=false`?

**Comment by PancakeZik** [comment]
Well, keepalive still shows "walking to X pokestop" and "walking to (coords) in X steps", so if that didn't show, then the log could be made only of pokemon and pokestops activated, therefore clearer...

**Comment by CosmoRing** [comment]
PancakeZik, `display_walking_nearest_unused` was removed but `display_pokestop_name` does the same thing.

**Comment by PancakeZik** [comment]
@CosmoRing I don't think so really, I just tried display_pokestop_name=false and it's giving me 
Walking to (51.524989, -0.127272) in 164.9751295976146 steps.
Looting nearby pokestop cf42942596704c8a8ab6d94c522c9311.16

The old walking nearest unused removed that

**Comment by CosmoRing** [comment]
Do you have display_pokestop_name=true ??

**Comment by PancakeZik** [comment]
I did, but tested it with false and the lines are there too.

**Comment by CosmoRing** [comment]
Yes, that is expected. When it's true it should replace the 
`Looting nearby pokestop cf42942596704c8a8ab6d94c522c9311.16` to `Looting nearby pokestop "pokestop name"

and it will add before `Walking to (51.524989, -0.127272) in 164.9751295976146 steps.` a log saying `Walking to "pokestop name"`

**Comment by jabbink** [comment]
Afaik no bug.
