### ISSUE TITLE
CATCH_ERROR and Restart with token

### ISSUE THREAD

**Issue by Danbardo** [jabbink/PokemonGoBot#384]
After a few hours I started getting:
26 Jul 17:13:31: Capture of BELLSPROUT failed with status : CATCH_ERROR

Restart fixes it, but not for long.

Restart crashes unless the token is deleted from the config.

**Comment by cwliias** [comment]
I just started getting this as well.

**Comment by pashorizer** [comment]
Which version are you using?

**Comment by cwliias** [comment]
4.2

**Comment by Danbardo** [comment]
0.4.2

**Comment by pashorizer** [comment]
Yeah, this is going to be fixed in the new release or you compile from `development`
https://github.com/jabbink/PokemonGoBot/pull/318
