### ISSUE TITLE
[Suggestion] Option to configure likelihood of berry use

### ISSUE THREAD

**Issue by Rofii** [jabbink/PokemonGoBot#386]
I took "desired_catch_probability" all the way down to 0.3 to get the bot to stop wasting Ultra Balls, but it still wastes berries. When I log on after a few hours of botting I never have any berries left but have plenty of balls.

**Comment by Mewks** [comment]
+1

I'm using 0.7 as my probability and I never have any ultra balls or berries left. It would be good to have a setting to prevent the bot from ever using ultra balls, I want to save them up for level 30+.

**Comment by jabbink** [comment]
Revamping the catch system in #399 

could put this in. Boolean flag `never_use_berries`?

**Comment by Mewks** [comment]
Beautiful. Could you perhaps put the same flag never_use_ultraballs? something like that?

**Comment by omar972** [comment]
Only use normal pokeballs would also be nice, I'm specially worried about when I get Master Balls, cause it looks like it will use them all in 5 minutes as well.

**Comment by Mewks** [comment]
You definitely would need to use Great Balls for nice rares that you find above level 20 though, so you would miss out on some pokemon if you ONLY use pokeballs I would imagine.

**Comment by omar972** [comment]
Well, could just have a choice for each type of ball + the berries.

**Comment by jabbink** [comment]
If you only want to use normal pokeballs, set the desired_catch_probability to 0

**Comment by jabbink** [comment]
Implemented berry property in #399
