### ISSUE TITLE
[BUILD] error on Ubuntu 16.04 

### ISSUE THREAD

**Issue by marsmensch** [jabbink/PokemonGoBot#388]
**Description:**
Current master does build, but the build result does not work and exits with an Exception.

**Steps to reproduce:**

1. build from source as ussual
2. run the PokemonGoBot

**Expected behavior:**
Bot starts

**Actual behavior:**
NoClassDefFoundError is displayed. A hint what could be wrong is displayed during the build (snippet):

```
:clean UP-TO-DATE
:PokeGOAPI-Java:clean UP-TO-DATE
:PokeGOAPI-Java:extractIncludeProto
Download https://repo1.maven.org/maven2/org/projectlombok/lombok/1.16.6/lombok-1.16.6.pom
Download https://repo1.maven.org/maven2/org/projectlombok/lombok/1.16.6/lombok-1.16.6.jar
:PokeGOAPI-Java:extractProto
:PokeGOAPI-Java:generateProto
Download https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.0.0-beta-3/protoc-3.0.0-beta-3.pom
Download https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.0.0-beta-3/protoc-3.0.0-beta-3-linux-x86_64.exe
:PokeGOAPI-Java:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:PokeGOAPI-Java:processResources UP-TO-DATE
:PokeGOAPI-Java:classes
:PokeGOAPI-Java:jar
:compileKotlin
w: /opt/code/pogobot/src/main/kotlin/ink/abb/pogo/scraper/Main.kt: (53, 13): 'sslSocketFactory(SSLSocketFactory!): OkHttpClient.Builder!' is deprecated. Deprecated in Java
w: /opt/code/pogobot/src/main/kotlin/ink/abb/pogo/scraper/Settings.kt: (102, 26): Variable 'result' initializer is redundant
w: /opt/code/pogobot/src/main/kotlin/ink/abb/pogo/scraper/tasks/CatchOneNearbyPokemon.kt: (44, 21): Condition 'result == null' is always 'false'
w: /opt/code/pogobot/src/main/kotlin/ink/abb/pogo/scraper/tasks/ReleasePokemon.kt: (29, 26): Variable 'sorted' initializer is redundant
w: /opt/code/pogobot/src/main/kotlin/ink/abb/pogo/scraper/tasks/ReleasePokemon.kt: (45, 42): Variable 'reason' initializer is redundant
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
```

**Stacktrace (If it's a crash):**
```
root@a9c66d3b4935:/usr/local/bin# java -jar pogo-scraper.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: okhttp3/OkHttpClient$Builder
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: okhttp3.OkHttpClient$Builder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

```
**Version:**
current master
```
root@a9c66d3b4935:/usr/local/bin# java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by jabbink** [comment]
>w: /opt/code/pogobot/src/main/kotlin/ink/abb/pogo/scraper/Main.kt: (53, 13): 'sslSocketFactory(SSLSocketFactory!): OkHttpClient.Builder!' is deprecated. Deprecated in Java

That line of code isn't in the codebase for quite some time.

Make sure you are on the latest commit of `develop` and execute step 2 of the readme.

**Comment by jabbink** [comment]
Also openjdk sucks. Use Oracle JDK 8.

**Comment by marsmensch** [comment]
@jabbink i am on master with latest commit, not develop. will switch to oracle java for the next tests, this requirement should probably be in the build instructions.

**Comment by jabbink** [comment]
Well, it says "Java 8". Open JRE/JDK 8 is "not" Java and a bad re-impl. [INSERT TROLL FACE HERE]

:joy:

**Comment by OmSoftGit** [comment]
When I say `gradlew run` it work properly. Why?

**Comment by jabbink** [comment]
? It works properly... because that's what it should do?

Also don't hijack issues with your own.

**Comment by OmSoftGit** [comment]
> ? It works properly... because that's what it should do?

I also have [BUILD] error on Ubuntu 16.04 when I run jar directly.

**Comment by jabbink** [comment]
Can't help without any stacktraces. :facepunch:

**Comment by OmSoftGit** [comment]
> Can't help without any stacktraces. :facepunch:

`~/PokemonGoBot/build/libs$ java -jar ./pogo.scraper-0.4.2.jar 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: okhttp3/OkHttpClient
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: okhttp3.OkHttpClient
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more`

**Comment by marsmensch** [comment]
Exact same "NoClassDefFoundError" with Oracle Java (on master branch).

Now testing development branch, thanks for the pointer.

```
root@498d8285787f:/usr/local/bin# java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

**Comment by OmSoftGit** [comment]
> Exact same "NoClassDefFoundError" with Oracle Java (on master branch).

Try `gradlew run`

**Comment by marsmensch** [comment]
Yes, i should have noted that `gradlew run` works already for me. I opened this issue solely for the point of documenting that i can not build the *.jar from source in the master branch.

**Comment by marsmensch** [comment]
Confirming that running `gradlew run` directly works for branches `master` and `development`.

As i dont want to use `gradlew` for running an app, i used the `gradlew installDist` task. The resulting `pogo.scraper` works as expected with no further hacks required.

**Comment by jabbink** [comment]
Oh, then I get the error: It can't find the Http lib because you didn't put the OkHttp jar in the classpath.

To build a jar that has every dep included do `./gradlew fatJar`
