### ISSUE TITLE
[Suggestion] Different desired catch rate based on CP/IV

### ISSUE THREAD

**Issue by PancakeZik** [jabbink/PokemonGoBot#391]
I think we have all the data needed to implement this.
How about a catch rate for when the pokemon doesn't fit your "transfer criteria" and another one for when it does?
I think that if I see a crappy pidgey now and the bot has to waste an ultra ball + razz berry to catch it, it could be saving that ultra ball for a more important pokemon later on.

**Comment by jabbink** [comment]
Closing #375 in favor of this one

**Comment by Mewks** [comment]
Great idea, force the use of Pokeballs only on Pokemon we are going to transfer. If we arent going to transfer them we use the probability criteria as normal?
