### ISSUE TITLE
BUILD FAILED: finished with non-zero exit value 1?

### ISSUE THREAD

**Issue by JCHendershot** [jabbink/PokemonGoBot#392]
**Description:**
Not sure what happened. Was able to get bot to run before. cloned the repository and compiled from source no problem. Took a break after getting soft banned (warped between spawn points too quickly) and got this error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_101\bin\java.exe'' finished with non-zero exit value 1

**Steps to reproduce:**

1. ran the bot directly from console.
2. [Step 2]

**Expected behavior:**
bot should start up and perform actions

**Actual behavior:**
build failure. stacktrace pastebin below.

**Stacktrace (If it's a crash):**
http://pastebin.com/PJVneVud

**Version:**
Latest version. I recloned the repo and reran everything, including `gradlew --refresh-dependencies clean build` but still got the build failure.

**Comment by pashorizer** [comment]
`LoginFailedException` indicates that a) Servers are down or b) token expired

**Comment by JCHendershot** [comment]
...and that would be the issue. I copied the config file without removing old token... thank you!

**Comment by jabbink** [comment]
Fixed on `develop` since a second ago as well, so not necessary in the near future anymore.
