### ISSUE TITLE
Bot prints caught pkmn statistic in the wrong color

### ISSUE THREAD

**Issue by pr0ves** [jabbink/PokemonGoBot#393]
[Here's the problem](https://github.com/jabbink/PokemonGoBot/blob/develop/src/main/kotlin/ink/abb/pogo/scraper/tasks/CatchOneNearbyPokemon.kt#L54-L60)

**Comment by jabbink** [comment]
Should be cyan?

**Comment by Sieberkev** [comment]
Cyan would be perfect (same as incubating/hatching egg)

**Comment by Sieberkev** [comment]
Errrrrrr, that was not my intention at all o_O

**Comment by jabbink** [comment]
Fixed in e073fa8 btw
