### ISSUE TITLE
Not logging in with PTC

### ISSUE THREAD

**Issue by CptJackieSparrow** [jabbink/PokemonGoBot#394]
**Description:**
I have no problems with Google accounts. 2 of my google accounts is running smoothly for 12 hours without crashing or anything. I just enter google.com/device thing once, then it's still running. But PTC is having troubles with signing in. I was clearing token when i was signing in from terminal, cuz it's not logging in unless i clean it. Now, token part is clear, but it's not logging in and giving this error even after waiting for hours.
Checked  config, everything is fine, pass and username is correct.
Everything was fine.
I can login from Pokemon Go app with PTC account from iPad, so servers are fine too.

**Steps to reproduce:**

Login with PTC

**Expected behavior:**
It should be logging in, it's just giving this loop

**Actual behavior:**
It's not logging in with PTC account

**Stacktrace (If it's a crash):**
`Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException: Error  in API Url 
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:149)
	at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:79)
	at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
	at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:107)`
**Version:**
v0.4.2

**Comment by neox387** [comment]
Allso had problems few minutes ago but with:
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 502

now however login works again

**Comment by jabbink** [comment]
>Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 502

Different issue: server broken

**Comment by alone23** [comment]
Maybe could add message "Server DOWN" for this one

**Comment by jabbink** [comment]
Compile from `develop` and it says that

**Comment by OmSoftGit** [comment]
> Compile from develop and it says that

but if I run `gradlew run` it work properly.

**Comment by CptJackieSparrow** [comment]
well i don't know how to complete step 2 in readme which says "run git submodule --...."

**Comment by jabbink** [comment]
Should be fixed with 0.4.3
