### ISSUE TITLE
[Suggestion] Auto Pokemon Name

### ISSUE THREAD

**Issue by ma4xat** [jabbink/PokemonGoBot#398]
Make some variable in config.properties to determine de Pokemon Name if pokemon is saved in inventory.

And use some tags for defaults values, something like:

pokemon_name = "%original_name% - %IV% - %CP%"

But is needed to check length of pokemon name ( max 14 chars i think ) and convert:

NIDORAN_FEMALE --> NIDORAN F
NIDORAN_MALE --> NIDORAN M

The longest pokemon name is KANGASKHAN, so i think the only available values are

pokemon_name = "%original_name% %IV%%" (no space if length is 15 chars, or space if is less than 15 chars )
--> KANGASKHAN100% 
--> KANGASKHAN 84%
 
pokemon_name = "%original_name%%CP%" (no space if length is 15 chars, or space if is less than 15 chars )
--> KANGASKHAN2300
--> KANGASKHAN 323

If name has %, is IV, if not, is CP

Additionaly, a variable like:
enable_auto_pokemon_name = false; // Or true

**Comment by omar972** [comment]
Duplicate. #381 #167
