### ISSUE TITLE
How to use a Google Account?

### ISSUE THREAD

**Issue by Jupiops** [jabbink/PokemonGoBot#402]
**Description:**
Don't know how I could config the Bot that he uses the Pokemon Go Account from my Google Account.
I just tried out to write my Login Credentials in the config

**Steps to reproduce:**

My config File:
[config.txt](https://github.com/jabbink/PokemonGoBot/files/383810/config.txt)

**Stacktrace (If it's a crash):**
`26 Jul 14:35:44: Display Keepalive Coordinates setting ("display_keepalive") not specified, defaulting to "true".
Logging in to game server...
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException
        at com.pokegoapi.auth.PtcLogin.login(PtcLogin.java:196)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:87)
`

**Version:**
0.4.2

**Comment by pashorizer** [comment]
You have to put your username and password in the config

**Comment by Sieberkev** [comment]
You need to fill in the field "username" with the emailadress of your google account and follow the instructions when it starts :)

**Comment by Jupiops** [comment]
Oh thanks, I just tried it without @gmail.com
Let's try! :)

**Comment by jabbink** [comment]
Just setting your username to `@` and leaving the password empty should also work.

**Comment by Jupiops** [comment]
Thanks, it worked for me like jabbink said :)
