### ISSUE TITLE
[SUGGESTION]Option to block using UltraBall and higher.

### ISSUE THREAD

**Issue by Pepejson** [jabbink/PokemonGoBot#403]
Could you add possibility to block use of UltraBall and better balls? 
GreatBall actually drops from almost every pokestop so it is ok that bot is using it but UltraBall is quite "rare".

**Comment by jabbink** [comment]
Set desired catch probability to 0 or something low

https://github.com/jabbink/PokemonGoBot/issues/386#issuecomment-235252827
