### ISSUE TITLE
Pokestop: NO_RESULT_SET

### ISSUE THREAD

**Issue by neox387** [jabbink/PokemonGoBot#404]
**Description:**
Pokestops not looting after a while & getting stuck ?

**Steps to reproduce:**

1. Run bot
2. error

**Expected behavior:**
Loot pokestop

**Actual behavior:**
NO_RESULT_SET

**Stacktrace (If it's a crash):**
Looting nearby pokestop 11410a03fc7f4c9f9c392e8fb2353fac.16
26 jul 15:11:17: Looted pokestop 11410a03fc7f4c9f9c392e8fb2353fac.16; +50 XP: [3xITEM_POKE_BALL]
Getting map of (34.009853607146994, -118.49567796669488)
Looting nearby pokestop b13d36808456456fb94fcf4135d53ddc.16
Destination reached.
26 jul 15:11:22: Looted pokestop b13d36808456456fb94fcf4135d53ddc.16; +50 XP: [2xITEM_REVIVE, 1xITEM_POKE_BALL]
Walking to (34.009773, -118.495111) in 86.74192041861005 steps.
Getting map of (34.00982448525472, -118.49554837699286)
26 jul 15:11:28: Dropped 2x ITEM_REVIVE
26 jul 15:11:29: Dropped 1x ITEM_POKE_BALL
Getting map of (34.00984503467561, -118.49539342313199)
Looting nearby pokestop 648e23a2e3d24d05a61b714cdd2267d5.16
26 jul 15:11:34: NO_RESULT_SET
Getting map of (34.00980279382893, -118.49522488834631)
Looting nearby pokestop 648e23a2e3d24d05a61b714cdd2267d5.16
26 jul 15:11:39: NO_RESULT_SET
Destination reached.
Getting map of (34.00976376274737, -118.4951335747951)
Looting nearby pokestop 648e23a2e3d24d05a61b714cdd2267d5.16
26 jul 15:11:44: NO_RESULT_SET
Walking to (34.009773, -118.495111) in 0.2580797628314017 steps.
Destination reached.
Getting map of (34.00975578706816, -118.495164757767)
Looting nearby pokestop 648e23a2e3d24d05a61b714cdd2267d5.16
26 jul 15:11:48: NO_RESULT_SET

**Version:**
8053de36c3cb1db6ca1796d08977d1ad5b6c26fe
allso with prebuilt 0.4.2

**Comment by Agronis** [comment]
This just happened to me as well - it's cleared up.

May be internal hiccup on their side.

**Comment by neox387** [comment]
guess so, since 0.4.2 workt fine before

**Comment by Agronis** [comment]
It's happening again..

**Comment by neox387** [comment]
I have it in Santa Monica, CA

**Comment by Agronis** [comment]
Check in your app - I loaded mine up and it wasn't loading Pokestops/Gyms so I definitely think it's localized and a problem on Niantics end.

It's cleared up for me now and bot is back to working.

**Comment by neox387** [comment]
Well ill try to move to London cause 2 min in & it's happening again :/

**Comment by Agronis** [comment]
Same.

Manhattan runs fine.
Charleston is NO_RESULT_SET
