### ISSUE TITLE
Cmd Token Spam

### ISSUE THREAD

**Issue by tyman1292** [jabbink/PokemonGoBot#408]
**Description:**
The bot is spamming "D/RequestHandler: Authenticated with static token" This didn't use to happen , just wondering why this is happening.  I stopped the bot as well because i wasn't sure if this was safe.
THIS IS A PTC ACCOUNT
**Steps to reproduce:**

1. [Step 1]
Run Script...
2. [Step 2]
Read Cmd

**Expected behavior:**
Run Normal?

**Actual behavior:**
[What actually happens]
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
Getting map of (40.61242396847901, -89.46011686770682)
D/RequestHandler: Authenticated with static token
?[32m26 Jul 09:04:56: Found pokemon RATTATA ?[0m
D/RequestHandler: Authenticated with static token
?[32m26 Jul 09:04:56: Encountered pokemon RATTATA with CP 23 ?[0m
?[33m26 Jul 09:04:56: Using ITEM_POKE_BALL ?[0m
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
?[32m26 Jul 09:04:56: Caught a RATTATA with CP 23 and IV 68%: [700x XP, 3x Candy
, 100x Stardust] ?[0m
D/RequestHandler: Authenticated with static token
Walking to (40.611948, -89.460278) in 108.2670941034853 steps.
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
Getting map of (40.612391019713606, -89.46006648403959)
D/RequestHandler: Authenticated with static token

**Version:**
0.4.2 prebuilt

**Comment by tyman1292** [comment]
Anyone on if this is unsafe?

**Comment by tyman1292** [comment]
This was fixed by correcting the time on my pc

**Comment by jabbink** [comment]
Good to know.
