### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by LuyiTian** [jabbink/PokemonGoBot#41]
I can't find pokemon using the released .jar so I tried to modify the src and build on my own. But I encountered this error:

```
.../PokemonGoBot-master/src/main/kotlin/ink/abb/pogo/scraper/Main.kt: (26, 27): Unresolved reference: PTCLogin
.../PokemonGoBot-master/src/main/kotlin/ink/abb/pogo/scraper/Main.kt: (126, 16): Unresolved reference: PTCLogin
:compileKotlin FAILED
```

FAILURE: Build failed with an exception.

if I remove any code related to `PTCLogin` the build is successful. Does anyone know why?

**Comment by tehalexf** [comment]
I believe the PokeGOAPI-Java repo was changed a few hours ago, causing this error.

**Comment by tehalexf** [comment]
You can fix it by changing lines 26 and 126 to say PtcLogin rather than PTCLogin.

**Comment by okynk** [comment]
You can fix it by changing `PTCLogin` to `PtcLogin` in `Main.kt`
The PokeGOAPI-Java renamed the class to camelcase

**Comment by LuyiTian** [comment]
Yes I have searched the API and found they rename from `PTC` to `Ptc`.  Thank you all
