### ISSUE TITLE
Obligatory Release Pokemon

### ISSUE THREAD

**Issue by KyleBoyer** [jabbink/PokemonGoBot#410]
**Description:**
One pokemon on the obligatory release list are still kept.(It drops all but one, maybe something to do with the drop duplicates setting)

**Steps to reproduce:**

1. Set Obligatory Release Settings
2. Catch multiple of that Pokemon
3. Check again, and one of that Pokemon are kept

**Expected behavior:**
Drop all of that pokemon

**Actual behavior:**
Keeps one of that pokemon

**Version:**
Latest build from source as of this issue report

**Comment by jabbink** [comment]
Fixed
