### ISSUE TITLE
[Suggestion] Runtime to calculate XP/HR

### ISSUE THREAD

**Issue by mroge009** [jabbink/PokemonGoBot#411]
Add runtime to the the update profile to display XP/HR since that is how many in the botting community seem to compare bots.  
Ive gotten around 40k/hr with this one.

**Comment by shilch** [comment]
I think it depends on the location and time how much xp you get per hour.

**Comment by mroge009** [comment]
@shilch Yes. But this way you can test out which location works best for you.

**Comment by MASSV** [comment]
Location is a huge factor. Bot on santa monica beach/pier gets +-50% over new york central park, double that of small town bot.

**Comment by jabbink** [comment]
Duplicate of #376
