### ISSUE TITLE
Does not refresh token

### ISSUE THREAD

**Issue by omar972** [jabbink/PokemonGoBot#412]
So I have been having this issue since I started using the bot, I received multiple suggestions and none of them worked. Those include:

- Compiling from source
- Updating to version 0.4.2
- Getting a new config file and not messing with the format
- Uninstalling and reinstalling Java

None of those fixed it, the bot spams D/GoogleLogin: Refreshed Token XXXXXXXXXXXXX and does not continue.
I know some people have been having this issue where it spams that but keeps running, but in my case, it spams it indefinitely without continuing to do stuff in the game.

Note: I do have the static token in the config, when the above happens, I simply abort it then use
`gradlew run` and it works, so it's not an issue with the config.

Any suggestions?

**Comment by jabbink** [comment]
Can you point to the exact commit you're running on, please?

`git log` and then the first line should contain in

**Comment by omar972** [comment]
```
commit 8053de36c3cb1db6ca1796d08977d1ad5b6c26fe
Author: JJ <jeremiah.oligario@gmail.com>
Date:   Tue Jul 26 06:53:33 2016 -0400
[Log Console] Facilitate and perhaps answer #357 and #353. (#367)
```

**Comment by jabbink** [comment]
Ah, could you please update to the newest version? Because just after that commit the entire login system was revamped.

![image](https://cloud.githubusercontent.com/assets/2461972/17145203/a7543116-5359-11e6-93b8-8503ea7306f2.png)

(you're on the bottom one, the top one was added just after)

**Comment by omar972** [comment]
Will do, thanks

**Comment by jabbink** [comment]
Might be related to #408 

As the readme states: make sure the time of your computer is correct.

**Comment by omar972** [comment]
Well, from one problem to another #422 . I'll close this and watch that issue.
