### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by xslkz** [jabbink/PokemonGoBot#414]
**Description:**

already install and use the bot from my computer, using source, gradle etc..
but still cant build it from my laptop. (already tried gradlew --refresh-dependencies clean build)

**Steps to reproduce:**

1. git clone 
2. git submodule update
3. .gradlew build

**Expected behavior:**
Succefull build

**Actual behavior:**
Build failed

**Stacktrace (If it's a crash):**
http://pastebin.com/RX3LqB2Y

**Version:**
openjdk version "1.8.0_77"
OpenJDK Runtime Environment (build 1.8.0_77-b03)
OpenJDK 64-Bit Server VM (build 25.77-b03, mixed mode)

last commit of the git

**Comment by Sieberkev** [comment]
@jabbink [recommends](https://github.com/jabbink/PokemonGoBot/issues/388#issuecomment-235219015) using Oracle JDK instead of OpenJDK

**Comment by jabbink** [comment]
1. `Run with --info or --debug option to get more log output.` Why don't you do that? That one actually contains the useful information
2. Did you do step 2 from the Readme?

**Comment by xslkz** [comment]
ill try it and will give u feedback! @Sieberkev 

there we go.. http://pastebin.com/1ci6Df3A @jabbink 

thanks to u both for such fast answer

**Comment by jabbink** [comment]
Did you do step 2 of the Readme?

**Comment by xslkz** [comment]
if u mean the command line git submodule update --init --recursive yeah i do

if u mean using the prebuild, my pb is that i want to work on the sources.. but yeah, it actually works with the .jar file.

**Comment by marcx093** [comment]
Got the same error, did you solve it?

**Comment by xslkz** [comment]
no i dont. unfortunately. if u didnt plain on edit sources, u should use the prebuild file.

**Comment by pashorizer** [comment]
Are you using Intellij? If so install the plugin Lombok
