### ISSUE TITLE
BUG: Transferred pokemon incremented without a transfer

### ISSUE THREAD

**Issue by ansalls** [jabbink/PokemonGoBot#415]
The bot (0.4.2) tried to encounter a Pokemon twice and rightfully only caught it once, however it seemingly transferred it twice and counted it as such. Obviously, this can't be the case, so it ought not to have incremented the transfer count.  

Profile update: 1116225 XP on LVL 27; 16225/250000 (6.49%) to LVL 28
**XP gain: 3740 XP; Pokemon caught/transferred: 12/10; Items caught/dropped: 48/38; Pokebank 224/250; Stardust 297548**
Getting map of (46.80416696082713, -92.07381872336127)
Getting map of (46.804089029676206, -92.0739075896163)
Getting map of (46.80392613921243, -92.0740052626215)
Getting map of (46.80381692016064, -92.07404700931652)
Getting map of (46.8037516836812, -92.07410141109747)
Getting map of (46.80361588981751, -92.0741567868271)
Getting map of (46.80350880276007, -92.07426922103788)
Getting map of (46.80341381599722, -92.07429762975077)
26 Jul 09:22:28: Found pokemon WEEDLE
Getting map of (46.80331272444002, -92.07445176607675)
26 Jul 09:22:35: Encountered pokemon WEEDLE with CP 93
26 Jul 09:22:35: Using ITEM_GREAT_BALL; Using curve 
26 Jul 09:22:36: Found pokemon WEEDLE 
**26 Jul 09:22:36: Caught a WEEDLE with CP 93 and IV 57%: [210x XP, 3x Candy, 100x Stardust]** 
**26 Jul 09:22:36: Going to transfer WEEDLE with CP 93 and IV 57%; reason: CP < 500 and IV < 80%** 
26 Jul 09:22:36: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED 
**26 Jul 09:22:36: Going to transfer WEEDLE with CP 93 and IV 57%; reason: CP < 500 and IV < 80%** 
Getting map of (46.80314776981653, -92.07450574287365)
Getting map of (46.80303956123922, -92.07458708920919)
Getting map of (46.80289198192739, -92.07467371020807)
Profile update: 1116435 XP on LVL 27; 16435/250000 (6.57%) to LVL 28
**XP gain: 3950 XP; Pokemon caught/transferred: 13/12; Items caught/dropped: 48/38; Pokebank 224/250; Stardust 297648**

**Comment by jabbink** [comment]
Fixed, and probably occured due to some multithreading issue.

Multithreading is fixed and just to be sure it actually checks if releasing worked.
