### ISSUE TITLE
Spams ERROR_INCUBATOR_ALREADY_IN_USE

### ISSUE THREAD

**Issue by siimveskilt** [jabbink/PokemonGoBot#417]
**Description:**
Writes "Failed to put egg in incubator; error: ERROR_INCUBATOR_ALREADY_IN_USE" every few lines:

```
26 juuli 17:51:55: Failed to put egg in incubator; error: ERROR_INCUBATOR_ALREADY_IN_USE
Getting map of (60.16602417201997, 24.934516878624226)
26 juuli 17:52:00: Failed to put egg in incubator; error: ERROR_INCUBATOR_ALREADY_IN_USE
Getting map of (60.16599698818085, 24.934704297249098)
26 juuli 17:52:05: Failed to put egg in incubator; error: ERROR_INCUBATOR_ALREADY_IN_USE
26 juuli 17:52:06: Profile update: 987217 XP on LVL 26; 87217/200000 (43,61%) to LVL 27
26 juuli 17:52:06: XP gain: 700 XP; Pokemon caught/transferred: 3/18; Items caught/dropped: 6/21;
Pokebank 152/250; Stardust 280889; Inventory 194/450
Getting map of (60.16598976398984, 24.934923312225404)
26 juuli 17:52:10: Failed to put egg in incubator; error: ERROR_INCUBATOR_ALREADY_IN_USE
Getting map of (60.16607733354987, 24.935119869559863)
26 juuli 17:52:15: Failed to put egg in incubator; error: ERROR_INCUBATOR_ALREADY_IN_USE
Getting map of (60.16601275073328, 24.935342266622843)
26 juuli 17:52:20: Failed to put egg in incubator; error: ERROR_INCUBATOR_ALREADY_IN_USE
```

**Expected behavior:**

Check if any free incubators.

**Version:**
0.4.2.

**Comment by jabbink** [comment]
>Version:
>0.4.2.

I assume that means prebuilt?

**Comment by siimveskilt** [comment]
No, it was built at commit 209.

**Comment by jabbink** [comment]
>commit 209

That means nothing, as commits shouldn't be counted, ever.

Please give the hash, the way that one should name commits.

**Comment by neox387** [comment]
I'm allso getting error spams related to eggs:

26 jul 17:11:57: Hatched NIDORAN_FEMALE with 489 CP and 93% IV; +10 candy; +500 XP; +800 stardust
Getting map of (51.509287114445236, -0.13468490067118183)
26 jul 17:12:02: Failed to put egg in incubator; error: ERROR_POKEMON_EGG_NOT_FOUND

**Comment by siimveskilt** [comment]
So, version is built after 4517c4638e934183ff53af2d28bf422c3f5702b6 (Fix/obligatory release (#413))  and last build without this was before d78b809a689ed83c4abd5652337469ced6550f7e (fix detection of unused incubators (#389) ).

**Comment by xenxes** [comment]
aaa1d8db39f8980733f5d38df0726becfb78f9b1 gives --

26 Jul 08:38:12: Failed to put egg in incubator; error: ERROR_POKEMON_EGG_NOT_FO
UND
Getting map of (37.811012646577396, -122.41100727605671)
26 Jul 08:38:17: Failed to put egg in incubator; error: ERROR_POKEMON_EGG_NOT_FO
UND
Getting map of (37.81102330961648, -122.4112019772185)
26 Jul 08:38:22: Failed to put egg in incubator; error: ERROR_POKEMON_EGG_NOT_FO
UND
Getting map of (37.810896814007684, -122.41139105582634)
26 Jul 08:38:28: Failed to put egg in incubator; error: ERROR_POKEMON_EGG_NOT_FO
UND

This is with 1 incubator already full.

**Comment by jabbink** [comment]
Does this happen IMMEDIATELY after starting?

**Comment by siimveskilt** [comment]
Yes. Also, I just opened the app manually and it hatched an egg.

**Comment by xenxes** [comment]
Yes immediately.  With 1 incubator already having an egg in it.  

Tried the proposed .4.3 code and same error https://github.com/jabbink/PokemonGoBot/pull/421/commits/d4c30a5db49809a44bf81ea6d7e1a9693900ee3d

**Comment by jabbink** [comment]
Noted that this happens. Happened a few days ago as well in #228 

Can you please edit the `HatchEggs.kt` in d4c30a5 and replace

```kotlin
        val freeIncubators = ctx.api.inventories.incubators.filter { !it.isInUse }
        val eggs = ctx.api.inventories.hatchery.eggs
                .filter { !it.isIncubate }
                .sortedByDescending { it.eggKmWalkedTarget }
```

with 

```kotlin
        println("Have walked ${ctx.api.playerProfile.stats.kmWalked}")

        ctx.api.inventories.incubators.forEach {
            println("Have incubator: ${it.id} ${it.isInUse} ${it.kmTarget} ${it.kmWalked} ${it.type} ${it.usesRemaining}")
        }
        val freeIncubators = ctx.api.inventories.incubators.filter { !it.isInUse }
        freeIncubators.forEach {
            println("Have free incubator: ${it.id} ${it.isInUse} ${it.kmTarget} ${it.kmWalked} ${it.type} ${it.usesRemaining}")
        }
        ctx.api.inventories.hatchery.eggs.forEach {
            println("Have egg: ${it.eggIncubatorId} ${it.eggKmWalkedStart} ${it.eggKmWalkedTarget} ${it.id} ${it.isIncubate}")
        }
        val eggs = ctx.api.inventories.hatchery.eggs
                .filter { !it.isIncubate }
                .sortedByDescending { it.eggKmWalkedTarget }
        eggs.forEach {
            println("Have unused egg: ${it.eggIncubatorId} ${it.eggKmWalkedStart} ${it.eggKmWalkedTarget} ${it.id} ${it.isIncubate}")
        }
```

and report the log back here?

**Comment by PancakeZik** [comment]
I added the code you said and it's now spamming this:

> Have walked 142.4305
> Have incubator: EggIncubatorProto8983924107930860562 false 0.0 0.0 INCUBATOR_DISTANCE 0
> Have free incubator: EggIncubatorProto8983924107930860562 false 0.0 0.0 INCUBATOR_DISTANCE 0
> Have egg:  0.0 2.0 -8803751993642576825 false
> Have egg:  0.0 2.0 -1635179443589340546 false
> Have egg:  0.0 2.0 1622021265546082236 false
> Have egg:  0.0 2.0 -7438452802626676415 false
> Have egg:  0.0 2.0 -264373451727910497 false
> Have egg:  0.0 5.0 3028151127681664934 false
> Have egg:  0.0 2.0 -4801244245550646351 false
> Have egg:  0.0 2.0 5563472806053713895 false
> Have egg:  0.0 2.0 6176064913286160868 false
> Have unused egg:  0.0 5.0 3028151127681664934 false
> Have unused egg:  0.0 2.0 -8803751993642576825 false
> Have unused egg:  0.0 2.0 -1635179443589340546 false
> Have unused egg:  0.0 2.0 1622021265546082236 false
> Have unused egg:  0.0 2.0 -7438452802626676415 false
> Have unused egg:  0.0 2.0 -264373451727910497 false
> Have unused egg:  0.0 2.0 -4801244245550646351 false
> Have unused egg:  0.0 2.0 5563472806053713895 false
> Have unused egg:  0.0 2.0 6176064913286160868 false
> 26 Jul 17:27:29: Failed to put egg in incubator; error: ERROR_POKEMON_EGG_NOT_FOUND

**Comment by neox387** [comment]
same:

> 
Have walked 134.9585
Have incubator: EggIncubatorProto-210991339465929883 false 134.66835021972656 129.66835021972656 INCUBATOR_DISTANCE 0
Have incubator: EggIncubatorProto7392489526399918484 false 137.2512969970703 132.2512969970703 INCUBATOR_DISTANCE 3
Have incubator: EggIncubatorProto-8361005606919627195 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have incubator: EggIncubatorProto-4195608817600581144 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have incubator: EggIncubatorProto-3919853444256869439 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have incubator: EggIncubatorProto-8070408802016196153 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have free incubator: EggIncubatorProto-210991339465929883 false 134.66835021972656 129.66835021972656 INCUBATOR_DISTANCE 0
Have free incubator: EggIncubatorProto7392489526399918484 false 137.2512969970703 132.2512969970703 INCUBATOR_DISTANCE 3
Have free incubator: EggIncubatorProto-8361005606919627195 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have free incubator: EggIncubatorProto-4195608817600581144 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have free incubator: EggIncubatorProto-3919853444256869439 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have free incubator: EggIncubatorProto-8070408802016196153 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have egg: EggIncubatorProto-210991339465929883 0.0 5.0 5247326112464461147 true
Have egg:  0.0 5.0 -6634385904801880177 false
Have egg:  0.0 5.0 -5682561794342493599 false
Have egg:  0.0 5.0 4431692389385766228 false
Have egg:  0.0 2.0 5875591114961988974 false
Have egg:  0.0 2.0 -5896429334835050437 false
Have egg: EggIncubatorProto7392489526399918484 0.0 5.0 8053761573963455279 true
Have egg:  0.0 2.0 7375657259630207685 false
Have egg:  0.0 2.0 1164615048263760807 false
Have unused egg:  0.0 5.0 -6634385904801880177 false
Have unused egg:  0.0 5.0 -5682561794342493599 false
Have unused egg:  0.0 5.0 4431692389385766228 false
Have unused egg:  0.0 2.0 5875591114961988974 false
Have unused egg:  0.0 2.0 -5896429334835050437 false
Have unused egg:  0.0 2.0 7375657259630207685 false
Have unused egg:  0.0 2.0 1164615048263760807 false
26 jul 19:05:44: Failed to put egg in incubator; error: ERROR_INCUBATOR_ALREADY_IN_USE

**Comment by jabbink** [comment]
@PancakeZik you have a different problem

>26 Jul 17:27:29: Failed to put egg in incubator; error: ERROR_POKEMON_EGG_NOT_FOUND

Probably still related.

**Comment by jabbink** [comment]
Also just to confirm, these logs come from d4c30a5db49809a44bf81ea6d7e1a9693900ee3d?

**Comment by PancakeZik** [comment]
mine comes from aaa1d8db39

**Comment by jabbink** [comment]
Ok, I wouldn't expect it to work on there. Please retry on the specified commit.

Also the code sample above is slightly changed, please take the posted sample from https://github.com/jabbink/PokemonGoBot/issues/417#issuecomment-235317469

**Comment by PancakeZik** [comment]
Just retried on that specific commit, same thing:
`Walking to (51.523931, -0.128377) in 156.145973935297 steps.
Have walked 150.23834
Have incubator: EggIncubatorProto8983924107930860562 false 0.0 0.0 INCUBATOR_DISTANCE 0
Have free incubator: EggIncubatorProto8983924107930860562 false 0.0 0.0 INCUBATOR_DISTANCE 0
Have egg:  0.0 2.0 -1635179443589340546 false
Have egg:  0.0 2.0 -7438452802626676415 false
Have egg:  0.0 2.0 -4801244245550646351 false
Have egg:  0.0 2.0 5563472806053713895 false
Have egg:  0.0 2.0 6176064913286160868 false
Have egg:  0.0 2.0 -8803751993642576825 false
Have egg:  0.0 2.0 1622021265546082236 false
Have egg:  0.0 2.0 -264373451727910497 false
Have egg:  0.0 5.0 3028151127681664934 false
Have unused egg:  0.0 5.0 3028151127681664934 false
Have unused egg:  0.0 2.0 -1635179443589340546 false
Have unused egg:  0.0 2.0 -7438452802626676415 false
Have unused egg:  0.0 2.0 -4801244245550646351 false
Have unused egg:  0.0 2.0 5563472806053713895 false
Have unused egg:  0.0 2.0 6176064913286160868 false
Have unused egg:  0.0 2.0 -8803751993642576825 false
Have unused egg:  0.0 2.0 1622021265546082236 false
Have unused egg:  0.0 2.0 -264373451727910497 false
26 Jul 18:46:39: Failed to put egg in incubator; error: `ERROR_POKEMON_EGG_NOT_FOUND``

**Comment by neox387** [comment]
on 1 bot it seemed to work just on d4c30a5db49809a44bf81ea6d7e1a9693900ee3d:

````
26 jul 19:52:23: Hatched RATTATA with 310 CP and 80% IV; +5 candy; +200 XP; +400 stardust
26 jul 19:52:23: Hatched CATERPIE with 229 CP and 75% IV; +7 candy; +200 XP; +549 stardust
26 jul 19:52:23: Hatched GEODUDE with 458 CP and 80% IV; +5 candy; +200 XP; +400 stardust
26 jul 19:52:25: Profile update: 558395 XP on LVL 23; 123395/125000 (98,72%) to LVL 24
26 jul 19:52:25: XP gain: 11545 XP; Pokemon caught/transferred: 45/46; Items caught/dropped: 115/31;
Pokebank 128/250; Stardust 214743; Inventory 229/350
Getting map of (34.014712907561595, -118.49283000637477)
26 jul 19:52:28: Going to transfer RATTATA with CP 310 and IV 80%; reason: Obligatory transfer
26 jul 19:52:28: Going to transfer CATERPIE with CP 229 and IV 75%; reason: Obligatory transfer
26 jul 19:52:30: Put egg -9160113905380236818 in unused incubator
Getting map of (34.014924126082185, -118.492859569773)
26 jul 19:52:34: Put egg 3638162372751082255 in unused incubator
````

bot on another bot still error :/ d4c30a5db49809a44bf81ea6d7e1a9693900ee3d with above modded code
````
Have walked 202.19638
Have incubator: EggIncubatorProto7594452398801598762 false 201.93478393554688 196.93478393554688 INCUBATOR_DISTANCE 0
Have free incubator: EggIncubatorProto7594452398801598762 false 196.93478393554688 201.93478393554688 INCUBATOR_DISTANCE 0
Have egg: EggIncubatorProto7594452398801598762 5.2615966796875 5.0 5257623269781346832 true
Have egg:  0.0 5.0 -1384388281987810821 false
Have egg:  0.0 2.0 1342529607473436265 false
Have egg:  0.0 2.0 -2689346890065536730 false
Have egg:  0.0 2.0 -8951035324014409724 false
Have egg:  0.0 2.0 5315815698604444803 false
Have egg:  0.0 5.0 3325903073803487650 false
Have egg:  0.0 5.0 5788231308085012057 false
Have egg:  0.0 5.0 3506288650858106109 false
Have unused egg:  0.0 5.0 -1384388281987810821 false
Have unused egg:  0.0 5.0 3325903073803487650 false
Have unused egg:  0.0 5.0 5788231308085012057 false
Have unused egg:  0.0 5.0 3506288650858106109 false
Have unused egg:  0.0 2.0 1342529607473436265 false
Have unused egg:  0.0 2.0 -2689346890065536730 false
Have unused egg:  0.0 2.0 -8951035324014409724 false
Have unused egg:  0.0 2.0 5315815698604444803 false
Taking egg:  0.0 5.0 -1384388281987810821 false
Putting it in: EggIncubatorProto7594452398801598762 false 196.93478393554688 201.93478393554688 INCUBATOR_DISTANCE 0
26 jul 20:00:22: Failed to put egg in incubator; error: ERROR_INCUBATOR_ALREADY_IN_USE
````

**Comment by jabbink** [comment]
Yep, seems like it, Moved some code around.

the isInUse function of the api is broken.
