### ISSUE TITLE
Being a noob

### ISSUE THREAD

**Issue by Spiritwolf213** [jabbink/PokemonGoBot#420]
**Description:**
As a total newby to java I find it extermely difficult to do any of what you all are talking about, but please dont let this scare you and help your fellow human
**Steps to reproduce:**

1. Making sure right java.
2. Downloading everything necessary.
3. changing the config with huge confusion.
4. opening everything in the cmd
5. java -jar pogo.scraper-all-0.4.2.jar

**Expected behavior:**
Running the bot?

**Actual behavior:**
Error: unable to access jarfile

**Comment by jabbink** [comment]
You are in the wrong directory, probably.

Use `cd` to switch directories.

**Comment by xslkz** [comment]
are u sure ur on the right folder? use ls command to show files in the folder

**Comment by shilch** [comment]
@xslkz he is on windows

**Comment by Spiritwolf213** [comment]
that surely got it fixed that way, a new issues rised up tho... im terribly sorry for my ignorance in coding, the new issues is that it simpy cannot find the config.properties...

**Comment by shilch** [comment]
Copy the `config.properties.template`

**Comment by Agronis** [comment]
You have to create it.

Copy the template - then rename it to config.properties (no .txt on the end).

**Comment by Emuuung** [comment]
Create a wiki tab for questions like this, tutorials and FAQs, I know is all on the `readme.md` but still.

**Comment by Agronis** [comment]
@Emuuung create an Issue for "plz halp common question wiki needed"

**Comment by Spiritwolf213** [comment]
it saves it automatically as a txt.file and idk how to change it...

**Comment by jabbink** [comment]
`MOVE config.properties.txt config.properties` in cmd.exe I guess

**Comment by shilch** [comment]
Or enable file extensions in system settings

**Comment by Spiritwolf213** [comment]
it automatically changes to a notepad file if i do that, does that matter or not?

**Comment by mlutze** [comment]
Open in Notepad
Save As...
type config.properties
Select "All files" from the "save as type" drop-down menu.
Click save

**Comment by Spiritwolf213** [comment]
I really can't get it to work, no matter what type i save it in...

**Comment by MASSV** [comment]
1.open notepad. 
2. make a copy of the content of the config.properties.template. fill in info needed in config. File> save as> on drop down menu select all files and for file name type "config.properties"  leave the quotes in there to make sure it does not become a .txt file. Save this in the same location as the .jar file. 
3. find "cmd.exe" and make a shortcut on desktop, right click properties. change "start in:" to the folder containing the .jar and your config file. Now you just need to start this cmd window and type in: java -jar pogo.scraper-all-0.4.2.jar an

**Comment by Leodenact** [comment]
Open the config.properties with notepad or notepad++, fill in you login and preferences etc. Once all is filled in, save the file as: config.properties and choose type all, HOWEVER make sure to remove the old config.properties.template before saving the new as an "all" file

**Comment by Spiritwolf213** [comment]
I appreciate all your support, I finally managed to make it work thanks to all of you.
