### ISSUE TITLE
Only getting Getting map of (LAT, LONG)

### ISSUE THREAD

**Issue by falko100** [jabbink/PokemonGoBot#422]
Getting map of (52.21965271207598, 6.8972231568595195)
Getting map of (52.21964560306371, 6.897224688825297)
Getting map of (52.21966823815963, 6.897212273455743)
Getting map of (52.21970388939844, 6.89718200685427)
Getting map of (52.21962268534616, 6.897188817818173)
Getting map of (52.21962543898165, 6.897167086829751)
Getting map of (52.219623500107346, 6.89721606074507)

And some profile updates. Bot is running in high density PokeStop area with lots of Pokémon.

(Latest develop branch build. Also happens in prebuild)

**Comment by Danbardo** [comment]
Have you tried using one of the older versions? 0.3.2 works flawlessly for me pretty much.

**Comment by omar972** [comment]
Same problem with me right now.

**Comment by jabbink** [comment]
Looks like it couldn't get an initial list of pokestops.

Heard from others that the servers are currently flaky so I will add logging of the amount of found pokestops and make it re-request pokestops when it gets 0 when initially launched.

**Comment by karikkato** [comment]
I had this issue about an hour ago in NYC, but it only lasted a little bit, it's running fine now on 

0.4.2 using a PTC account

**Comment by omar972** [comment]
google account, running on latest develop build, still stuck.

**Comment by jabbink** [comment]
Have the same problem now. Fix incoming.

**Comment by jabbink** [comment]
btw, I assume you have `desired_catch_probability_unwanted=-1`?

**Comment by omar972** [comment]
It defaults to 0, is it broken in this build or something?

**Comment by jabbink** [comment]
Default is 0, but do you have it set on the default?

**Comment by omar972** [comment]
Yup, should I make it -1?

**Comment by jabbink** [comment]
No. But I assumed this bug only occured for `-1`

**Comment by omar972** [comment]
Oh, I see.

**Comment by omar972** [comment]
Sorry if this is off-point, don't think it deserves it's own issue. For when the fix is done, is there a way to quickly update to the latest commit or do I have to make a fresh installation? A bit of a newbie.
