### ISSUE TITLE
Transfer any Pokemon the bot catches if it fills the last slot in the bag

### ISSUE THREAD

**Issue by omar972** [jabbink/PokemonGoBot#423]
For example, if User's Pokemon bag is 249/250 full and they have this config option on true, any Pokemon the bot catches will be transferred, keeping it on 249/250 to avoid stopping the bot. It's very unlikely that that last slot would have a good Pokemon, so I don't see any reason why this would hurt.

Notes:

- If the way this is implemented, it transfers the first Pokemon in the bag when it's sorted by most recent, beware that if a Pokemon is evolved it will be the most recent and the user may want to keep it.
- Not everyone has 250 max slots, Pokemon bag expansions exist.

**Comment by jabbink** [comment]
>It's very unlikely that that last slot would have a good Pokemon

No, but if you keep it running and it picks one up and immediately throws it away you can throw away hundreds of pokemon over night, which also contain good ones.

**Comment by omar972** [comment]
Yes, probably, but at least you will get stardust and xp. These good ones would not have been caught if your bag was full anyway.

**Comment by falko100** [comment]
Maybe discard lowest IV / CP duplicate?

**Comment by omar972** [comment]
What if it's not a duplicate?

**Comment by Simpuhl** [comment]
I think what he's saying is if the bag is full to start deleting duplicate pokemon with the lower IV/CP first

**Comment by omar972** [comment]
Isn't this already what the bot does?

**Comment by Rofii** [comment]
+1

**Comment by HoneyWheat** [comment]
+1 but keep in mind the ignore settings. This feature must override all ignore pokemons settings in the config file.
