### ISSUE TITLE
Pokestop: NO RESULT SET

### ISSUE THREAD

**Issue by TaylorZaneKirk** [jabbink/PokemonGoBot#424]
**Description:**
Bot gets hung up on pokestop. This is at Santa Monica Pier with PLENTY of other pokestops around (from what I've seen from screenshots, at least)

**Steps to reproduce:**

1. Set coords to (34.0098598, -118.4986249)
2. Run bot for about 10 minutes. This has happened twice in a row, so maybe it isn't reproducable, but I thought it to be worth bringing attention to.

**Expected behavior:**
Should blacklist this stop as though it were in cool down?

**Actual behavior:**
Keeps trying to loot a bad Stop

**Stacktrace (If it's a crash):**
```
Getting map of (34.010510334736196, -118.49520004659945)
Getting map of (34.01066074518959, -118.49526607571339)
Looting nearby pokestop 31b1a0e2cadf4603855ff5a5d80ef225.16
26 Jul 10:45:10: NO_RESULT_SET
Getting map of (34.01076011184172, -118.49540020373395)
Looting nearby pokestop 31b1a0e2cadf4603855ff5a5d80ef225.16
26 Jul 10:45:14: NO_RESULT_SET
Destination reached.
Walking to (34.010773, -118.495416) in 0.6090506831263933 steps.
Destination reached.
Getting map of (34.010806510091086, -118.49542190555418)
Looting nearby pokestop 31b1a0e2cadf4603855ff5a5d80ef225.16
26 Jul 10:45:19: NO_RESULT_SET
Walking to (34.010773, -118.495416) in 0.390949321330372 steps.
Destination reached.
Getting map of (34.010733722952345, -118.49539089717452)
Looting nearby pokestop 31b1a0e2cadf4603855ff5a5d80ef225.16
26 Jul 10:45:23: NO_RESULT_SET
Walking to (34.010773, -118.495416) in 0.6090506736046725 steps.
Destination reached.
```

**Version:**
0.4.2

**Comment by neox387** [comment]
Fixt on dev e073fa85591f6e8635e6306ad3dae82f5c17d6f7

**Comment by TaylorZaneKirk** [comment]
Thanks; closing.
