### ISSUE TITLE
Evolve with Lucky Egg

### ISSUE THREAD

**Issue by Simpuhl** [jabbink/PokemonGoBot#425]
We need a feature that basically counts how many candy we have and starts keeping pokemon based if we have enough eggs to evolve. Basically if we have 100 candy, keep 2 surtitle instead of 1 etc.

Then once we have enough candy to evolve 30-50 different pokemon we can pop the lucky egg and mass evolve for a shit ton of xp and then transfer the ones we don't need.

Also we should be able to choose specific ones to not evolve in case someone is saving candy to evolve a second form into a 3rd form for what ever reason.

**Comment by Agronis** [comment]
Please use the search function before opening new issues.

**Comment by jabbink** [comment]
Already described in #5 and https://github.com/jabbink/PokemonGoBot/pull/347/files#r72149937
