### ISSUE TITLE
./gradlew build error

### ISSUE THREAD

**Issue by xiaochenchen** [jabbink/PokemonGoBot#426]
**Description:**
./gradlew build error

**Steps to reproduce:**
Finished all presteps, got error at ./gradlew build error:
Error message:
http://pastebin.com/7yRnkQQV

**Stacktrace (If it's a crash):**
http://pastebin.com/DwzqjYdh

**Version:**
ava version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

latest git commit

**Comment by leadboots5** [comment]
I received this as well. Same Java version. Mac OSX

**Comment by xiaochenchen** [comment]
Hmmmmm, I think I found what the issue was.

I do not have protobuf for java installed on my linux.

**Comment by jabbink** [comment]
@leadboots5 when you want to compile from source, yes you need the JDK. To run the precompiled version the JRE suffices.
