### ISSUE TITLE
Another newbie question

### ISSUE THREAD

**Issue by Leodenact** [jabbink/PokemonGoBot#429]
**Description:**
1.[When new files are added to the source files, imported from the pull request, like adding random walking to pokestops, how do I download them into my folder? Or should I copy it and paste it somewhere, I have no clue.

2. How to focus more on catching? It walks so long before it's catching, is there anything I can add in the file to make it GO to the pokemons and catch them? Basicly to catch more pokemons

**Comment by Agronis** [comment]
See [here](http://stackoverflow.com/questions/3903817/pull-new-updates-from-original-github-repository-into-forked-github-repository) for updating to most current source.

AFAIK, if there are 'mon in the radius of your current mapped area - it will catch all before moving on.

It moves in a straight line from one Pokestop to the next.

You can increase walk speed to shorten time between stops in the config file.

If you're still not having luck - move to a more populated area (like Manhattan).

**Comment by jabbink** [comment]
>How to focus more on catching? It walks so long before it's catching

The bot should be used in a large city with many pokestops and therefore pokemon spawns
