### ISSUE TITLE
Failed to put egg in incubator; error: ERROR_POKEMON_EGG_NOT_FOUND

### ISSUE THREAD

**Issue by visia** [jabbink/PokemonGoBot#430]
**Description:**
Log spams Failed to put egg in incubator; error: ERROR_POKEMON_EGG_NOT_FOUND. I can log in and see that there are plenty of eggs to use.

This happens with 1 incubator free (the infinite use one) and also with a bunch of incubators free. 

Adding logging from here: https://github.com/jabbink/PokemonGoBot/issues/417#issuecomment-235317469

Have walked 178.39864
Have incubator: EggIncubatorProto4534514250022689775 false 0.0 0.0 INCUBATOR_DISTANCE 0
Have incubator: EggIncubatorProto7715891907556431560 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have incubator: EggIncubatorProto2880612967432471648 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have incubator: EggIncubatorProto7078770827207396717 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have incubator: EggIncubatorProto6782796216397992993 false 181.00314331054688 176.00314331054688 INCUBATOR_DISTANCE 3
Have incubator: EggIncubatorProto5035343310898828124 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have incubator: EggIncubatorProto-349690407516054037 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have free incubator: EggIncubatorProto4534514250022689775 false 0.0 0.0 INCUBATOR_DISTANCE 0
Have free incubator: EggIncubatorProto7715891907556431560 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have free incubator: EggIncubatorProto2880612967432471648 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have free incubator: EggIncubatorProto7078770827207396717 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have free incubator: EggIncubatorProto6782796216397992993 false 181.00314331054688 176.00314331054688 INCUBATOR_DISTANCE
 3
Have free incubator: EggIncubatorProto5035343310898828124 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have free incubator: EggIncubatorProto-349690407516054037 false 0.0 0.0 INCUBATOR_DISTANCE 2
Have egg:  0.0 2.0 -1669668703835151331 false
Have egg:  0.0 2.0 2451918259312990473 false
Have egg:  0.0 2.0 -4368464456648976819 false
Have egg: EggIncubatorProto6782796216397992993 0.0 5.0 1017835444314140300 true
Have unused egg:  0.0 2.0 -1669668703835151331 false
Have unused egg:  0.0 2.0 2451918259312990473 false
Have unused egg:  0.0 2.0 -4368464456648976819 false
26 Jul 10:22:03: Failed to put egg in incubator; error: ERROR_POKEMON_EGG_NOT_FOUND

**Version:**
aaa1d8d

**Comment by jabbink** [comment]
Can you try with d4c30a5db49809a44bf81ea6d7e1a9693900ee3d?

**Comment by nullsumme** [comment]
d4c30a5 fixed it for me

**Comment by visia** [comment]
d4c30a5 + api update fixed it. Thanks

**Comment by MyUncleSam** [comment]
I am getting this message as soon as one egg has finished. Currently using the up2date version:

ESC[33;1m26 Jul 21:40:31: Going to transfer PIDGEY with CP 38 and IV 15%; reason: CP < 400 and IV < 80% ESC[0m
ESC[31;1m26 Jul 21:40:32: Failed to put egg in incubator; error: ERROR_POKEMON_EGG_NOT_FOUND ESC[0m
Getting map of (x, y)
ESC[32;1m26 Jul 21:40:35: Found pokemon KOFFING ESC[0m
ESC[32;1m26 Jul 21:40:36: Encountered pokemon KOFFING with CP 114 and IV 73% ESC[0m
ESC[33;1m26 Jul 21:40:36: Using ITEM_POKE_BALL; achieved catch probability: 0.78210527, desired: 0.0 ESC[0m
ESC[36;1m26 Jul 21:40:36: Caught a KOFFING with CP 114 and IV 73%
 Stamina: 8 | Attack: 15 | Defense: 10 | IV: 33 (73%): [700x XP, 3x Candy, 100x Stardust] ESC[0m
ESC[31;1m26 Jul 21:40:37: Failed to put egg in incubator; error: ERROR_POKEMON_EGG_NOT_FOUND ESC[0m
Getting map of (x, y)
ESC[31;1m26 Jul 21:40:41: Failed to put egg in incubator; error: ERROR_POKEMON_EGG_NOT_FOUND ESC[0m
Getting map of (x, y)
ESC[1m26 Jul 21:40:45: Profile update: 48375 XP on LVL 10; 3375/10000 (33,75%) to LVL 11 ESC[0m
ESC[1m26 Jul 21:40:45: XP gain: 1750 XP; Pokemon caught/transferred: 4/2; Items caught/dropped: 32/26;
Pokebank 51/250; Stardust 13100; Inventory 153/350 ESC[0m
ESC[31;1m26 Jul 21:40:47: Failed to put egg in incubator; error: ERROR_POKEMON_EGG_NOT_FOUND ESC[0m
Getting map of (x, y)
ESC[31;1m26 Jul 21:40:51: Failed to put egg in incubator; error: ERROR_POKEMON_EGG_NOT_FOUND ESC[0m
Getting map of (x, y)
Looting nearby pokestop "Rumford-Raumschiff "
ESC[32;1m26 Jul 21:40:56: Looted pokestop "Rumford-Raumschiff "; +50 XP: [3xITEM_POKE_BALL] ESC[0m
ESC[31;1m26 Jul 21:40:57: Failed to put egg in incubator; error: ERROR_POKEMON_EGG_NOT_FOUND ESC[0m
Getting map of (x, y)
ESC[33;1m26 Jul 21:41:01: Dropped 1x ITEM_POKE_BALL ESC[0m
