### ISSUE TITLE
[BUG] Desired

### ISSUE THREAD

**Issue by alone23** [jabbink/PokemonGoBot#431]
**Description:**
Wrong desired

**Steps to reproduce:**

obligatory_transfer=MAGIKARP
desired_catch_probability_unwanted=0.0

**Expected behavior:**

26 jul 19:40:04: Found pokemon MAGIKARP 
26 jul 19:40:04: Encountered pokemon MAGIKARP with CP 22 and IV 60% 
26 jul 19:40:04: **Using ITEM_POKE_BALL; achieved catch probability: 1.0, desired: 0.0** 
26 jul 19:40:04: Caught a MAGIKARP with CP 22 and IV 60%
 Stamina: 7 | Attack: 10 | Defense: 10 | IV: 27 (60%): [200x XP, 3x Candy, 100x Stardust] 
26 jul 19:40:09: Found pokemon DROWSE 

26 jul 19:40:09: Encountered pokemon DROWZEE with CP 224 and IV 55% 
26 jul 19:40:09: Using ITEM_ULTRA_BALL; Using curve; achieved catch probability: 0.9819096, desired: 0.9 
26 jul 19:40:09: Caught a DROWZEE with CP 224 and IV 55%
 Stamina: 5 | Attack: 14 | Defense: 6 | IV: 25 (55%): [210x XP, 3x Candy, 100x Stardust] 
26 jul 19:40:09: Dropped 1x ITEM_REVIVE 
26 jul 19:40:14: Found pokemon MAGIKARP 
26 jul 19:40:14: Encountered pokemon MAGIKARP with CP 136 and IV 73% 
26 jul 19:40:14: **Using ITEM_POKE_BALL; achieved catch probability: 1.0, desired: 0.0**
26 jul 19:40:14: Caught a MAGIKARP with CP 136 and IV 73%
 Stamina: 12 | Attack: 10 | Defense: 11 | IV: 33 (73%): [210x XP, 3x Candy, 100x Stardust] 

**Actual behavior:**

26 jul 19:40:04: Found pokemon MAGIKARP 
26 jul 19:40:04: Encountered pokemon MAGIKARP with CP 22 and IV 60% 
26 jul 19:40:04: **Using ITEM_POKE_BALL; achieved catch probability: 1.0, desired: 0.0** 
26 jul 19:40:04: Caught a MAGIKARP with CP 22 and IV 60%
 Stamina: 7 | Attack: 10 | Defense: 10 | IV: 27 (60%): [200x XP, 3x Candy, 100x Stardust] 
26 jul 19:40:09: Found pokemon DROWSE 

26 jul 19:40:09: Encountered pokemon DROWZEE with CP 224 and IV 55% 
26 jul 19:40:09: Using ITEM_ULTRA_BALL; Using curve; achieved catch probability: 0.9819096, desired: 0.9 
26 jul 19:40:09: Caught a DROWZEE with CP 224 and IV 55%
 Stamina: 5 | Attack: 14 | Defense: 6 | IV: 25 (55%): [210x XP, 3x Candy, 100x Stardust] 
26 jul 19:40:09: Dropped 1x ITEM_REVIVE 
26 jul 19:40:14: Found pokemon MAGIKARP 
26 jul 19:40:14: Encountered pokemon MAGIKARP with CP 136 and IV 73% 
26 jul 19:40:14: **Using ITEM_ULTRA_BALL; Using curve; achieved catch probability: 0.9055839**, desired: 0.9 
26 jul 19:40:14: Caught a MAGIKARP with CP 136 and IV 73%
 Stamina: 12 | Attack: 10 | Defense: 11 | IV: 33 (73%): [210x XP, 3x Candy, 100x Stardust] 

**Version:**
Last develop

**Comment by jabbink** [comment]
`autotransfer=true`?

**Comment by alone23** [comment]
false

**Comment by incenx** [comment]
may i add more bug here? @jabbink 
i use this config,
`keep_pokemon_amount=3` and `autotransfer=true`  and `obligatory_transfer=CATERPIE`

but all CATERPIE got transferred.

i'm on the latest version of dev. Thanks

**Comment by jabbink** [comment]
@incenx Don't put CATERPIE as obligatory_transfer then

@alone23 there's your problem

**Comment by alone23** [comment]
Thanks
