### ISSUE TITLE
Still only getting map info

### ISSUE THREAD

**Issue by omar972** [jabbink/PokemonGoBot#436]
#422 Still having this issue after updating.

This is the output of git log
```
D:\PokemonGoBot>git log
commit 253d18cf6bc9db3abd474fea3d3faf1ea3005b44
Author: Jasper Abbink <git@abb.ink>
Date:   Tue Jul 26 21:13:20 2016 +0200

    Clean up many things to prepare for 0.4.3 release (#421)

    * Clean up many things to prepare for 0.4.3 release

    * Fix hatching priorities
    properly check pokemon blacklist in walking algorithm
    Fixes #422, fixes fixes #417

    * Break free when no balls are available
    Fixes #432
```

**Comment by SSminowjohnson** [comment]
I think the servers may be down. Mine was running fine earlier now it's only saying:

Getting map of (40.76474590165817, -73.97319940576712)
Getting map of (40.76476841265999, -73.97318759455594)
Getting map of (40.76479738313089, -73.9732286715252)
Getting map of (40.76474062954094, -73.97322431863357)
Getting map of (40.764786481573566, -73.97320774373348)
Getting map of (40.76475628302448, -73.97321334945713)
Getting map of (40.76475688319183, -73.97317485915671)
Getting map of (40.76476702850063, -73.97323247969138)
Getting map of (40.76476240947483, -73.97322665468181)
Getting map of (40.764748939457206, -73.97320734855694)
Getting map of (40.764828439307806, -73.97318451904933)
Getting map of (40.76476889006688, -73.97315808964908)

**Comment by omar972** [comment]
I can play with my phone, servers are unstable though, will test later.

**Comment by marcx093** [comment]
Getting the same errors, hope its because servers are unstable and not some fix for bots

**Comment by SSminowjohnson** [comment]
Seems to work again for me, not sure what that was about.

**Comment by pashorizer** [comment]
Server problems.

**Comment by marcx093** [comment]
Well it does work now :+1:

**Comment by omar972** [comment]
Not for me :/

**Comment by omar972** [comment]
Guys, any ideas why it's not working for me ?

**Comment by marcx093** [comment]
Stopped working again...
