### ISSUE TITLE
Compartor Issue

### ISSUE THREAD

**Issue by Danman00** [jabbink/PokemonGoBot#438]
Hi there,

i used the previus version of the bot 0.3.0 and it worked like a charm, since the newest version gives way more features i would give it a try.
But after i downloaded the newest verions and set up the new config.properties i get the following issue.

Exception in thread "main" java.lang.NoSuchMethodError: java.util.Comparator.thenComparing(Ljava/util/Comparator;)Ljava/util/Comparator;
	at ink.abb.pogo.scraper.Bot.run(Bot.kt:55)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:116)

This error comes up after the bot got my Profile from the Server. 
I turned off the transfer feature completly and also set the following:
sort_by_iv=false
transfer_iv_threshold=-1
transfer_cp_threshold=-1

a big thanks to the devs and for the answers

**Comment by Sieberkev** [comment]
Are you using Oracle JDK 8.0 to run the bot?

**Comment by Danman00** [comment]
I am running this on a Mac with Java 8 Update 101

**Comment by Sieberkev** [comment]
I meant to write java instead of JDK, my bad ^_^

**Comment by Danman00** [comment]
No problem :), i also tryed to look the erros up in the source but i am not very familiar with Java

**Comment by jabbink** [comment]
>I am running this on a Mac with Java 8 Update 101

I don't believe you. Run `java -version`

**Comment by Danman00** [comment]
The Terminal says 
the information with java 8 uotade 101 was in the control pannel

java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)

**Comment by Sieberkev** [comment]
Looks like you have multiple installations of the java JRE (7 and 8), does it work if you uninstall the 1.7.0 one?

**Comment by jabbink** [comment]
Or change the the default java thing in your operating systems search path.

**Comment by Danman00** [comment]
Thanks for your help i installed the JDK from oracle now i got the correct version and the latest version from the bot with sudo it runs like a charm 👍

**Comment by jabbink** [comment]
don't set the undesired catch prob to `-1`. Only if that's -1 it will not attempt to catch everything

**Comment by Danman00** [comment]
Thanks u are awesome 👍
