### ISSUE TITLE
keep_pokemon_amount vs obligatory_transfer

### ISSUE THREAD

**Issue by momonjo** [jabbink/PokemonGoBot#439]
**Description:**
I use this version : 
https://github.com/jabbink/PokemonGoBot/commit/1adeb74431257da14358e9e6a828500fa5a04c58

i write `obligatory_transfer=RYHORN`
`autotransfer=true`
`keep_pokemon_amount=3` in config.

**Expected behavior:**
Transfer all RYHORN, but save 3 of the best RYHORN.

> This feature worked nicely on the release version 0.4.2

**Actual behavior:**
all RYHORN gone..

Have RHYHORN () with 411 CP and IV 51%
 Stamina: 9 | Attack: 2 | Defense: 12 | IV: 23 (51%)
Have RHYHORN () with 293 CP and IV 60%
 Stamina: 15 | Attack: 0 | Defense: 12 | IV: 27 (60%)
Have SANDSHREW () with 360 CP and IV 46%
 Stamina: 3 | Attack: 10 | Defense: 8 | IV: 21 (46%)
27 Jul 02:58:52: Going to transfer RHYHORN with CP 411 and IV 51%; reason: Obligatory transfer
27 Jul 02:58:53: Going to transfer RHYHORN with CP 293 and IV 60%; reason: Obligatory transfer

**Operating System:**
WIN10

**Java version:**
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**Comment by pashorizer** [comment]
It does actually not care about `keep_pokemon_amount` when you have `obligatory_transfer`s on.

**Comment by jabbink** [comment]
Changed in #295 because others were complaining that it did not transfer all...

**Comment by jabbink** [comment]
So you apparently want 3 `RHYHORN`'s even when they are below the threshold, then why put it in the obligatory list?

**Comment by Emuuung** [comment]
Maybe he doesn't want to keep 3 of every other pokemon.

**Comment by momonjo** [comment]
well on the first experiment in https://github.com/jabbink/PokemonGoBot/commit/1adeb74431257da14358e9e6a828500fa5a04c58, all `RYHORN`s gone,

but i wish i still have 3 RYHORN's with the best CP and i don't need new `RYHORN`s on the next run.

**Comment by momonjo** [comment]
i think the transfer mechanism in `Release Version 0.4.2` already nice.

if other people want to transfer ALL of them just put `keep_pokemon_amount=0`

**Comment by siimveskilt** [comment]
autotransfer=true
keep_pokemon_amount=3 

without the obligatory already does what you want?

**Comment by momonjo** [comment]
Nope,
`autotransfer=true`
`keep_pokemon_amount=3`

and i still have 5 pinsir in my Poke-Inventory..

**Comment by siimveskilt** [comment]
I suggest you change iv and cp threshold to -1 and sort by iv. Because, you are botting anyways so why not maximize the outcome?

**Comment by momonjo** [comment]
Well, i suggest a new config option = 'use_obligatory_on_initial_transfer=true/false'

if set to `true`, all Pokemons in `obligatory_transfer` will be transfered. if not, save 3 of them.

**Comment by siimveskilt** [comment]
I'm not sure what you want to achieve... what is that good for?

**Comment by momonjo** [comment]
well, forget about it... you guys know what the best for this :) :+1:

**Comment by jabbink** [comment]
I think I get what you want and it has been formulated better in #479

**Comment by momonjo** [comment]
yes @jabbink ... you're da best! :dancers:
