### ISSUE TITLE
[Feature Request] Ignoring full inventory

### ISSUE THREAD

**Issue by Mroczny337** [jabbink/PokemonGoBot#440]
Hello, add ignoring full inventory if you can because I can't farm pokeballs cause my inventory is full. Thanks brah.

**Comment by wartickler** [comment]
brahwhat? If inventory is full then how would you continue to fill your inventory with pokeballs?

**Comment by CosmoRing** [comment]
How do you intend to farm pokeballs if you have nowhere to put it?
