### ISSUE TITLE
[Suggestion] Append IV value to Pokemon Name so it can be seen in the app.

### ISSUE THREAD

**Issue by vamirineni87** [jabbink/PokemonGoBot#443]
**Description:**
As discussed here (https://goo.gl/Pp52l3), it would be a nice feature to append the pokemon IV to its name. It will speed up decision making during manual play.

**Comment by Sieberkev** [comment]
This is a duplicate of open issue #167

**Comment by vamirineni87** [comment]
Thanks, Search didnt show anything.
