### ISSUE TITLE
[Question] How to run git submodule update?

### ISSUE THREAD

**Issue by CptJackieSparrow** [jabbink/PokemonGoBot#446]
Hello guys, i'm far away from coding and i'm trying to run bot without compiling.
I'm having the Build Failed error as i can't run git submodule (because i don't know how).
Anybody willing to explain how to do so?
I'll appreciate that.
Regards.

**Comment by Sieberkev** [comment]
If you want to run the precompiled jar file, you don't have to run anything from git.

Follow the simple instructions from [the releasenotes](https://github.com/jabbink/PokemonGoBot/releases/tag/v0.4.3) (download JAR, set up config file, run java command, ???, profit) and you should be up and running :smile:

**Comment by jabbink** [comment]
Install git, and then run the command from the readme

**Comment by CptJackieSparrow** [comment]
thank you guys
i'm having troubles with jar file, and i think developer version is updating itself so could be better option.
