### ISSUE TITLE
Add multi account option

### ISSUE THREAD

**Issue by jabbink** [jabbink/PokemonGoBot#449]
**Description:**
Add ability to log in to many accounts at once from one config

**Notes:**
Make sure the incoming Web interface plays nice with this.

**Comment by sodanakin** [comment]
You'd save me a lot of time making bat scripts and editing all the configs that's for sure ;o

**Comment by Spyderdreams** [comment]
The script I made for now till this fix is made. It starts PowerShell shortcuts with the "Start in" with the file path to folder with each jar and config file. change the .txt to .vbs. This is set for 6 bots.

Also the PNG file I use to make a .ICO for a icon for the VBS script

![pokemon-icon](https://cloud.githubusercontent.com/assets/20584970/17161878/9c4b467a-5376-11e6-8a41-6eb19d80fd0a.png)

[Keystrokes.txt](https://github.com/jabbink/PokemonGoBot/files/385171/Keystrokes.txt)

**Comment by rannmann** [comment]
An alternative solution would be to allow command line parameters to override the login information in the config file, so a bash/batch script could handle the multiple accounts instead, or a simple program pulling information from a database.  Having multiple accounts in a single config file feels like an odd solution.

**Comment by jabbink** [comment]
Implemented.

**Comment by NoobWithBoobs** [comment]
How do you use it, @jabbink?

**Comment by jabbink** [comment]
Read the readme

**Comment by NoobWithBoobs** [comment]
And the FAQ... 
https://github.com/jabbink/PokemonGoBot/blob/718e8b4181eb580686647b026098320421744186/FAQ.md
