### ISSUE TITLE
Recommendation: Compute IV and Auto Transfer <%

### ISSUE THREAD

**Issue by xenxes** [jabbink/PokemonGoBot#45]
Use formula via https://docs.google.com/spreadsheets/d/1wbtIc33K45iU1ScUnkB0PlslJ-eLaJlSZY47sPME2Uk/htmlview?usp=sharing&sle=true to calculate IV based on CP, HP, dust price of captured pokemon and auto-transfer those below a set threshold.

**Comment by pr0ves** [comment]
I did something similar in #39 but I just used the CP. 
The dust price is the dust needed to level the pokemon up? 
Anyway all the characteristics of a pokemon that we can use are defined here https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Data/PokemonData.proto where stamina and stamina_max should be the HP, but i don't see the dust price.

**Comment by jabbink** [comment]
What does IV stand for?

Also stuff like the Dust price is available in the GAME_MASTER protobuf, which will be incorporated in the Java API soon'ish, so it would be futile to store them in this repo as well then.

**Comment by mroge009** [comment]
I added IV calculation with options in the properties to set minIV.

config.properties
```
#Minimum IV to keep a pokemon
transfer_IV_threshold=90
```

Bot.kt
```
api.pokebank.pokemons.map {
            var IV = ((it.individualStamina + it.individualAttack + it.individualDefense) * 100) / 45
            "Have ${it.pokemonId.name} (${it.nickname}) with ${it.cp} CP and IV ${IV}"
        }.forEach { println(it) }
```

Settings.kt
`val transferIVThreshold = getPropertyIfSet("Minimum IV to keep a pokemon", "transfer_IV_threshold", 80, String::toInt)`

Releasepokemon.kt
```
val minIV = settings.transferIVThreshold

        groupedPokemon.forEach {
            val sorted = it.value.sortedByDescending { it.cp }
            for ((index, pokemon) in sorted.withIndex()) {
                var IV = ((pokemon.individualStamina + pokemon.individualAttack + pokemon.individualDefense) * 100) / 45
                // never transfer highest rated Pokemon
                // never transfer > maxCP, unless set in obligatoryTransfer
                // stop releasing when pokemon is set in ignoredPokemon
                when (pokemon.pokemonId.name) {
                    "RATTATA" -> if (index > pokemon.candy / 25) {
                        println("Going to transfer ${pokemon.pokemonId.name} with CP ${pokemon.cp} because you currently have ${pokemon.getCandy() / 25} evolutions pending")
                        pokemon.transferPokemon()
                    }
                    "PIDGEY", "WEEDLE", "CATERPIE" -> if (index > pokemon.candy / 12) {
                        println("Going to transfer ${pokemon.pokemonId.name} with CP ${pokemon.cp} because you currently have ${pokemon.getCandy() / 12} evolutions pending")
                        pokemon.transferPokemon()
                    }
                    else -> {
                        if (index > 0 && (pokemon.cp < maxCP || obligatoryTransfer.contains(pokemon.pokemonId.name)) &&
                                (!ignoredPokemon.contains(pokemon.pokemonId.name)) && IV < minIV) {
                            println("Going to transfer ${pokemon.pokemonId.name} with CP ${pokemon.cp} and IV ${IV}")
                            pokemon.transferPokemon()
                        }
                    }
                }
            }
        }
```

**Comment by pr0ves** [comment]
I'm implementig this right now @mroge009. But i have to remove this part 
```
"RATTATA" -> if (index > pokemon.candy / 25) {
                        println("Going to transfer ${pokemon.pokemonId.name} with CP ${pokemon.cp} because you currently have ${pokemon.getCandy() / 25} evolutions pending")
                        pokemon.transferPokemon()
                    }
                    "PIDGEY", "WEEDLE", "CATERPIE" -> if (index > pokemon.candy / 12) {
                        println("Going to transfer ${pokemon.pokemonId.name} with CP ${pokemon.cp} because you currently have ${pokemon.getCandy() / 12} evolutions pending")
                        pokemon.transferPokemon()
                    }
```
you have to let the user choose which pokemon to transfer directly, even if everyone is going to transfer those

**Comment by mroge009** [comment]
Yes, I forgot to remove that.  
That's for me, and I am going to add a evolution switch which will use lucky eggs and do as many evolution as possible

**Comment by xenxes** [comment]
Awesome that was fast! @jabbink if you haven't looked it up, IV stood for individual value in the original games and is also in Go.  Each Pokemon has a random +0 - 15 range to each stat, a perfect (100%) pokemon would have 15/15/15/15 to each of attack, defense, stamina, hp.   So due to RNG each a 0/0/0/0 vs. a 15/15/15/15 pokemon could vary by about 10% in CP.

**Comment by mroge009** [comment]
@xenxes I think IV is only atk, def, and sta where hp is a function of sta.  I only used the first 3 in my calculations and they seem to work fine with my highest being a 93% Flareon

**Comment by xenxes** [comment]
@mroge009 yes sorry you are right, I went back to look at the formula, it is only atk/def/sta.  

var IV = ((it.individualStamina + it.individualAttack + it.individualDefense) * 100) / 45

is correct :)

**Comment by jabbink** [comment]
Merged with a slight modification, instead of having this formula in the code twice, I added it as extension function to the Pokemon-class.

<3 Kotlin
