### ISSUE TITLE
[Enhancement] Keep best # of a specific pokemon (help wanted)

### ISSUE THREAD

**Issue by Emuuung** [jabbink/PokemonGoBot#452]
What can I do to keep just my best 3 EEVEEs (or whatever other pokemon) and still have `keep_pokemon_amount=1` for every other pokemon?

**Comment by mroge009** [comment]
Not currently implemented.

**Comment by Forty-Tw0** [comment]
If you want, you can give pokemon a nickname and they will not be transferred, then you can delete the nickname and they can be transferred again.

Otherwise you can write a patch which takes a setting in the form of var=(EEVEE,3),(MEW,2) or something.

**Comment by Emuuung** [comment]
@mroge009 Ah ok, it would be nice if it were in the TODO list.

@Forty-Tw0 I guess I would try to implement it if I knew how to do it properly. I'll look at the code and see if I can do something about it. Thanks for the answer anyway.

**Comment by sargunster** [comment]
On a related note, does the nickname thing also apply to marking them as favorite? So ones marked as favorite won't be transferred?

**Comment by omar972** [comment]
All pokemon that have a nickname or are favourite will not be transferred.

**Comment by Emuuung** [comment]
@sargunster Nicknamed or Favorited pokemon wont be transfered.

**Comment by Emuuung** [comment]
```
val keepSpecificPokemonAmount = getPropertyIfSet(("name of pokemon", "keep_specific_pokemon_amount", "EEVEE", String::toString);("minimum keep pokemon amount", "keep_pokemon_amount", 3, String::toInt)).split(",")
```
Will this be OK to start? I'm bad at this :laughing:

**Comment by Agronis** [comment]
A temporary work around would be to set keep_pokemon_amount to 1 or 0 and then increase threshhold to a high %.

Start at 90%, once you begin to exceed a particular quota - raise it to 93%.. and eventually you're only left catching 98% or greater.

**Comment by Mixone-FinallyHere** [comment]
just set that pokemon to never transfer or something
