### ISSUE TITLE
Bot doesn't work

### ISSUE THREAD

**Issue by omar972** [jabbink/PokemonGoBot#453]
https://gyazo.com/9b97d45bd42738f31e80919dcca44667

This happens in both the 0.4.3 release and the latest develop build.

I tried to go back to the 0.4.2 release and it won't work either, spams "Getting map of"

Only thing that works for me is an older build I have:  
`commit 8053de36c3cb1db6ca1796d08977d1ad5b6c26fe`

**Comment by momonjo** [comment]
works nice here..

**Comment by CosmoRing** [comment]
When it appears pokestops its because there are problems with the servers. Just wait and try again later.

**Comment by omar972** [comment]
That does not explain why it works for the old build and doesn't for the new one.

**Comment by casper-gh** [comment]
I'm with OP, old build works better and catches more pokemon, since .4.* all I see is Getting map of...

**Comment by omar972** [comment]
I'm officially a fucking idiot. The reason it was not finding any pokestops is I forgot the '-' in the longitude for the new build so it put me in a location that DIDN'T have any pokestops. Excuse my intellect, no issue here.
