### ISSUE TITLE
During set-up receiving error=206 filename too long

### ISSUE THREAD

**Issue by Thaella** [jabbink/PokemonGoBot#454]
**Description:**

PokeGOAPI-Java:generateProto FAILED FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':PokeGOAPI-Java:generateProto'. > java.io.IOException: Cannot run program "C:\Users\Dan\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protoc\3.0.0-beta-3\71e76cad4f9b30aab172c44035d343c5bab47815\protoc-3.0.0-beta-3-windows-x86_64.exe": CreateProcess error=206, The filename or extension is too long 

* Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. BUILD FAILED Total time: 11.339 secs

**Steps to reproduce:**

1. Proceeded to step 3 of installation instructions.

**Expected behavior:**
Configuration

**Actual behavior:**
Errors out

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
[The version of the bot you used; when self-compiled: :exclamation: the commit hash :exclamation:]

**Operating System:**
[Your operating system]

**Java version:**
[Full output of `java -version`]

**Comment by CosmoRing** [comment]
Did you even search the old issues of the problem?

See: #371 #283 #264 #201

**Comment by Thaella** [comment]
I looked at active issues.
I'm new to github thanks for the redirect!

**Comment by CosmoRing** [comment]
Don't forget to close this issue when you are done.
