### ISSUE TITLE
Retrying in 10 seconds?

### ISSUE THREAD

**Issue by CptJackieSparrow** [jabbink/PokemonGoBot#455]
`27 Jul 02:00:33: Getting initial pokestops...
27 Jul 02:00:33: Got 0 pokestops
27 Jul 02:00:33: Retrying in 10 seconds... 
27 Jul 02:00:44: Got 0 pokestops
27 Jul 02:00:44: Retrying in 10 seconds... 
27 Jul 02:00:56: Got 0 pokestops
27 Jul 02:00:56: Retrying in 10 seconds... 
27 Jul 02:01:07: Got 0 pokestops
27 Jul 02:01:07: Retrying in 10 seconds... 
27 Jul 02:01:18: Got 0 pokestops
27 Jul 02:01:18: Retrying in 10 seconds... `

**Comment by CptJackieSparrow** [comment]
I'm @ middle of central park by the way

**Comment by CosmoRing** [comment]
See #453

**Comment by Emuuung** [comment]
I get this when servers are very slow or down, or when your location is too remote and nowehre near a pokestop, should close this issue.

**Comment by jabbink** [comment]
Yeah, when the servers are broken they send 0 pokestops. The bot needs pokestops to function at all. So it waits.
