### ISSUE TITLE
Miscounting # of 'mons in bank

### ISSUE THREAD

**Issue by ansalls** [jabbink/PokemonGoBot#459]
Latest release, 0.4.3

26 Jul 18:50:43: Profile update: 1220350 XP on LVL 27; 120350/250000 (48.14%) to LVL 28 
26 Jul 18:50:43: XP gain: 19525 XP; Pokemon caught/transferred: 70/59; Items caught/dropped: 263/157;
**Pokebank 241/250; Stardust 334760; Inventory 263/350** 
D/RequestHandler: Authenticated with static token
26 Jul 18:50:45: Getting map of (46.78907192338033, -92.09362268246431)
26 Jul 18:50:45: Dropped 1x ITEM_POTION 
26 Jul 18:50:45: Dropped 2x ITEM_POKE_BALL 
26 Jul 18:50:45: Dropped 1x ITEM_GREAT_BALL 
26 Jul 18:50:45: Looting nearby pokestop "Green Bear "
26 Jul 18:50:45: Looted pokestop "Green Bear "; +50 XP: [3xITEM_POKE_BALL] 
26 Jul 18:50:50: Getting map of (46.78889544171721, -92.09379470061242)
26 Jul 18:50:50: Found pokemon HORSEA 
**26 Jul 18:50:50: Encounter failed with result: POKEMON_INVENTORY_FULL** 
26 Jul 18:50:50: Disabling catching of Pokemon

**Comment by na-ji** [comment]
The game count eggs as Pokemons in the bank. So should the bot add them to the count too ?

**Comment by jabbink** [comment]
>The game count eggs as Pokemons in the bank. 

Wow, thanks, I thought this was related to #448

**Comment by Mixone-FinallyHere** [comment]
close @langerhans ?
