### ISSUE TITLE
what do i run main.kt with?

### ISSUE THREAD

**Issue by lazerplain1** [jabbink/PokemonGoBot#46]
i cant find out why i cant run main.kt

**Comment by aleixsb** [comment]
You have to build the project with gradlew

**Comment by lazerplain1** [comment]
I did already

**Comment by D3C1V3R** [comment]
once you've built the project you should have a compiled .jar

**Comment by aleixsb** [comment]
if you do `gradlew tasks`  you'll see all options just do a run and will execute the project

**Comment by lazerplain1** [comment]
@D3C1V3R after the project completed i didnt get any fold besides . gradle thats it

**Comment by lazerplain1** [comment]
@aleixsb i got a build fail

**Comment by aleixsb** [comment]
so there is your problem, check your java instalation or copy here the build error.

Have you just cloned this repo? There is a small bug right now that you can fix simply edditing Main.kt  you can follow the fix in #41

**Comment by pr0ves** [comment]
To run the program, do ```gradlew run ```

If you have a build fail, post the error message.

**Comment by lazerplain1** [comment]
@pr0ves unresolved reference:PTCLogin

**Comment by pr0ves** [comment]
PTCLogin()  is a function from the PokemonGoAPI, and gradle doesn't find it. 
Try to run again ```gradlew build``` and see if it downloads anything, it should download the libraries needed for programs.

**Comment by CosmoRing** [comment]
Just change PTCLogin to PtcLogin everywere

**Comment by lazerplain1** [comment]
another error now it cant compile java

**Comment by CosmoRing** [comment]
Did you replace the code on Main.tk in line 175 for this:
`auth = PtcLogin(http).login(username, properties.getProperty("password"))`

and line 26 for this:
`import com.pokegoapi.auth.PtcLogin`

I think you only need to replace this and do gradlew build on your projects folder.

**Comment by lazerplain1** [comment]
i changed that already

**Comment by pr0ves** [comment]
The import line too? 
Try again `gradlew build` and post the full message error

**Comment by lazerplain1** [comment]
ERROR: JAVA_HOME is not set and 'java' command could be found in your PATH

**Comment by jabbink** [comment]
Not code related.

Read the "manual" (the 3 lines).

**Comment by lazerplain1** [comment]
i did that but i can run the main.kt

**Comment by jabbink** [comment]
If you're not a programmer, download the `.jar` from the releases tab and run it directly with Java 1.7+.

If you would be a programmer, you'd know that you have to do `./gradlew build`

(if you build it before `./gradlew --refresh-dependencies clean build`)

**Comment by lazerplain1** [comment]
correction its .\gradlew build and its say some shit about my java

**Comment by jabbink** [comment]
k
