### ISSUE TITLE
[BUG] Bot not walking, only getting map

### ISSUE THREAD

**Issue by CosmoRing** [jabbink/PokemonGoBot#461]
**Description:**
When you have `catch_pokemon=false` and there is a pokemon nearby, instead of walking to a pokestop it will try to catch the pokemon. Because option is false it will never catch it so it will never walk.

**Steps to reproduce:**

1. Run bot with `catch_pokemon=false`
2. Find pokemon BEFORE starts to walk to a pokestop

**Expected behavior:**
Ignore the pokemon and start walking

**Actual behavior:**
Tries to catch the pokemon

**Version:**
0.4.3

```
27 jul 00:29:30: Logging in to game server...
D/GoogleCredentialProvider: 1800
D/GoogleCredentialProvider: Get user to go to:https://www.google.com/device and enter code:XXX
D/GoogleCredentialProvider: Got token: XXX
27 jul 00:30:09: Setting Google refresh token in your config
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
27 jul 00:30:11: Logged in as XXX
Getting profile data from pogo server.
27 jul 00:30:11: 
27 jul 00:30:11: Name: XXX
27 jul 00:30:11: Team: XXX
27 jul 00:30:11: Pokecoin: XX
27 jul 00:30:11: Stardust: XXX
27 jul 00:30:11: Level XXX
27 jul 00:30:11: Pokebank 168/250
27 jul 00:30:11: Inventory 315/350
27 jul 00:30:11: Have POKEMON (NICK) with **** CP and IV ***% 
 Stamina: ** | Attack: ** | Defense: ** | IV: ** (**%)
....................
27 jul 00:30:11: Getting map of (********, **********)
27 jul 00:30:11: Getting initial pokestops...
27 jul 00:30:11: Got 274 pokestops
27 jul 00:30:11: Getting map of (********, **********)
27 jul 00:30:12: Profile update: **XP on LVL **; **/**(**%) to LVL **
27 jul 00:30:12: XP gain: 0 XP; Pokemon caught/transferred: 0/0; Items caught/dropped: 0/0;
Pokebank **/**; Stardust **; Inventory ***/***
27 jul 00:30:16: Getting map of (********, ********)
27 jul 00:30:21: Getting map of (**********, ***********)
27 jul 00:30:26: Getting map of (*********, *********)
27 jul 00:30:31: Getting map of (**********, *********)
27 jul 00:30:36: Getting map of (**********, *********)
27 jul 00:30:41: Getting map of (*********, *********)
27 jul 00:30:46: Getting map of (********, *********)
27 jul 00:30:51: Getting map of (*********, **********)
27 jul 00:30:56: Getting map of (********, ********)
27 jul 00:31:01: Getting map of (********, *********)
27 jul 00:31:06: Getting map of (**********, ********)
27 jul 00:31:11: Getting map of (*********, ********)
27 jul 00:31:12: Profile update: **XP on LVL **; **/**(**%) to LVL **
27 jul 00:3:12: XP gain: 0 XP; Pokemon caught/transferred: 0/0; Items caught/dropped: 0/0;
Pokebank **/**; Stardust **; Inventory ***/***
```

**Comment by pashorizer** [comment]
Yup, nice catch. 
https://github.com/jabbink/PokemonGoBot/blob/develop/src/main/kotlin/ink/abb/pogo/scraper/Bot.kt#L106-L115

https://github.com/jabbink/PokemonGoBot/blob/develop/src/main/kotlin/ink/abb/pogo/scraper/tasks/WalkToUnusedPokestop.kt#L23-L27

Btw does `catch_pokemon=false` work at all? It should get stuck forever actually.

**Comment by Evuse** [comment]
I have the same problem. After 1 minuti of botting i don't get any pokemon... just mapping.

27 lug 10:53:17: Getting map of (45.45090421981754, 9.172107679018243)
27 lug 10:53:17: Profile update: 795009 XP on LVL 25; 85009/190000 (44,74%) to LVL 26 
27 lug 10:53:17: XP gain: 3560 XP; Pokemon caught/transferred: 16/19; Items caught/dropped: 12/62;
Pokebank 216/250; Stardust 225013; Inventory 401/550 
27 lug 10:53:22: Getting map of (45.45095775891084, 9.171965447428622)
27 lug 10:53:27: Getting map of (45.4509141852912, 9.171918759276918)
27 lug 10:53:32: Getting map of (45.45095650319635, 9.171774402018064)
27 lug 10:53:37: Getting map of (45.45098021791698, 9.171638593640276)
27 lug 10:53:37: Looting nearby pokestop 63553eeae93245119a3b92f1f8e18d09.11
27 lug 10:53:37: Looted pokestop 63553eeae93245119a3b92f1f8e18d09.11; +50 XP: [1xITEM_POTION, 5xITEM_POKE_BALL] 
27 lug 10:53:42: Getting map of (45.450938116349334, 9.17153152922588)
27 lug 10:53:47: Getting map of (45.45092810179032, 9.171357028823966)
27 lug 10:53:49: Destination reached.
27 lug 10:53:52: Getting map of (45.45101856627911, 9.171301535724774)
27 lug 10:53:53: Walking to (45.450641, 9.171858) in 140.25962200292 steps.
27 lug 10:53:57: Getting map of (45.45093305648572, 9.171395608127689)
27 lug 10:54:02: Getting map of (45.4508988891364, 9.171555234732535)
27 lug 10:54:07: Getting map of (45.45081362433479, 9.171617051935511)
27 lug 10:54:07: Looting nearby pokestop f81ab729a9b84b27aab54e8ee6b06257.16
27 lug 10:54:07: Looted pokestop f81ab729a9b84b27aab54e8ee6b06257.16; +50 XP: [1xITEM_POTION, 2xITEM_POKE_BALL] 
27 lug 10:54:12: Getting map of (45.45071358678578, 9.17171750509005)
27 lug 10:54:17: Getting map of (45.45070871969996, 9.171795098515979)
27 lug 10:54:17: Profile update: 795109 XP on LVL 25; 85109/190000 (44,79%) to LVL 26 
27 lug 10:54:17: XP gain: 3660 XP; Pokemon caught/transferred: 16/19; Items caught/dropped: 21/62;
Pokebank 216/250; Stardust 225013; Inventory 410/550 
27 lug 10:54:17: Dropped 2x ITEM_POTION 
27 lug 10:54:21: Destination reached.
27 lug 10:54:22: Getting map of (45.45060568673298, 9.171833440069994)
27 lug 10:54:22: Walking to (45.452031, 9.173441) in 509.60709203284074 steps.
27 lug 10:54:27: Getting map of (45.45067680826756, 9.171974734585323)
27 lug 10:54:32: Getting map of (45.45074314697854, 9.172028722565253)
27 lug 10:54:37: Getting map of (45.45080246060521, 9.172070259665205)
> Building 91% > :run
27 lug 10:54:42: Getting map of (45.45091100602161, 9.172110622156978)
27 lug 10:54:47: Getting map of (45.45096842749613, 9.172238548983582)
27 lug 10:54:52: Getting map of (45.451025202991595, 9.172312832418672)
27 lug 10:54:57: Getting map of (45.451066281020054, 9.172360892075616)
27 lug 10:55:02: Getting map of (45.45116632467298, 9.172420552127953)
27 lug 10:55:07: Getting map of (45.45121747726042, 9.172510560234407)
27 lug 10:55:12: Getting map of (45.45132561013165, 9.172616763582981)
27 lug 10:55:17: Getting map of (45.451336555281685, 9.17274579337884)
27 lug 10:55:17: Profile update: 795109 XP on LVL 25; 85109/190000 (44,79%) to LVL 26 
27 lug 10:55:17: XP gain: 3660 XP; Pokemon caught/transferred: 16/19; Items caught/dropped: 21/64;
Pokebank 216/250; Stardust 225013; Inventory 408/550 
27 lug 10:55:22: Getting map of (45.45139822663378, 9.172732307226246)
> Building 91% > :run

How can i fix it??

**Comment by pashorizer** [comment]
@Evuse  That happens when there is nothing to catch. Your log is working fine.

**Comment by Evuse** [comment]
The question is.. there is a way to expand/reduce the search area? If i reboot the bot i keep finding for a minute everytime

**Comment by EyesReye** [comment]
And Sometimes it only does 0.74294829849284928 steps, instead of the 50-300 i normally have.

**Comment by jabbink** [comment]
Those are pokestops that are very close to each other (dense city).

Anyways, this issue has been fixed.
