### ISSUE TITLE
New config omits walk_only

### ISSUE THREAD

**Issue by Rofii** [jabbink/PokemonGoBot#463]
https://raw.githubusercontent.com/jabbink/PokemonGoBot/master/config.properties.template

This config from Readme.md lacks the walk_only setting. Not a big deal since it results in defaulting to false but I thought I'd mention it.

26 Jul 20:27:09: Only walk to hatch eggs setting ("walk_only") not specified, defaulting to "false".

**Comment by CosmoRing** [comment]
@Roffi what is the version you are using?

**Comment by Rofii** [comment]
@CosmoRing Release 0.4.2

**Comment by CosmoRing** [comment]
The config.properties.template is for the latest release 0.4.3

**Comment by Rofii** [comment]
@CosmoRing Oops, thank you. Closing this now.
