### ISSUE TITLE
0.4.3 | Authenticated with static token

### ISSUE THREAD

**Issue by ColeB27** [jabbink/PokemonGoBot#466]
Will not get past Authenticated with static token.

D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
26 Jul 21:39:05: Server returned unexpected error
26 Jul 21:39:05: Retrying...
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token

It loops that error.

**Comment by itsavirusforyou** [comment]
This problem is currently occurring for me with 0.5.0-Alpha2
