### ISSUE TITLE
[BUG] Looting the same pokestop 

### ISSUE THREAD

**Issue by mrgippy** [jabbink/PokemonGoBot#468]
I am testing in central park and after a few minutes of "getting map of" it tries to loot the same pokestop over and over.

Latest version 0.4.3

> 26 Jul 19:10:56: Getting map of (40.768755567852196, -73.97785264592197)
> 26 Jul 19:10:56: Looting nearby pokestop 03f2e3700c1b4b7b9cc1de29484b3746.16
> 26 Jul 19:10:56: Looted pokestop 03f2e3700c1b4b7b9cc1de29484b3746.16; +0 XP: []
> 
> 26 Jul 19:11:01: Getting map of (40.76883431652734, -73.97787263297552)
> 26 Jul 19:11:01: Profile update: 17045 XP on LVL 6; 2045/6000 (34.08%) to LVL 7
> 
> 26 Jul 19:11:01: XP gain: 995 XP; Pokemon caught/transferred: 0/2; Items caught
> dropped: 7/0;
> Pokebank 2/250; Stardust 3700; Inventory 24/350
> 26 Jul 19:11:01: Looting nearby pokestop 03f2e3700c1b4b7b9cc1de29484b3746.16
> 26 Jul 19:11:01: Looted pokestop 03f2e3700c1b4b7b9cc1de29484b3746.16; +0 XP: []
> 
> 26 Jul 19:11:06: Getting map of (40.768779414630345, -73.97781021653518)
> 26 Jul 19:11:06: Looting nearby pokestop 03f2e3700c1b4b7b9cc1de29484b3746.16
> 26 Jul 19:11:06: Looted pokestop 03f2e3700c1b4b7b9cc1de29484b3746.16; +0 XP: []
> 
> 26 Jul 19:11:11: Getting map of (40.76876250371442, -73.97781145086236)
> 26 Jul 19:11:11: Looting nearby pokestop 03f2e3700c1b4b7b9cc1de29484b3746.16
> 26 Jul 19:11:11: Looted pokestop 03f2e3700c1b4b7b9cc1de29484b3746.16; +0 XP: []
> 
> 26 Jul 19:11:16: Getting map of (40.768795396241345, -73.97789621830063)
> 26 Jul 19:11:16: Looting nearby pokestop 03f2e3700c1b4b7b9cc1de29484b3746.16
> 26 Jul 19:11:16: Looted pokestop 03f2e3700c1b4b7b9cc1de29484b3746.16; +0 XP: []
> 
> 26 Jul 19:11:21: Getting map of (40.768829356603646, -73.97784014867197)
> 26 Jul 19:11:21: Looting nearby pokestop 03f2e3700c1b4b7b9cc1de29484b3746.16
> 26 Jul 19:11:21: Looted pokestop 03f2e3700c1b4b7b9cc1de29484b3746.16; +0 XP: []

**Comment by tzutzanu** [comment]
That's probably because you jumped around and got soft-banned. This happens to be the best workaround against the soft-banning - "spinning" the same pokestop somewhere between 10-40 times will usually lift the ban faster (presumably)

**Comment by mrgippy** [comment]
I caught 2-3 pokemons before this loop happened. I doubt I did anything myself to get softbanned. I am currently running the bot now and all it does now is "Getting map of". I also did this #462 to "fix" it, but it didn't work.
