### ISSUE TITLE
CP perfect percent is more accurate than IV perfect

### ISSUE THREAD

**Issue by alawing** [jabbink/PokemonGoBot#469]
CP is caculate by CP = (BaseAtk + IndAtk) * (BaseDef + IndDef)^0.5 * (BaseSta + IndSta)^0.5 * (ECpM)^2 / 10

which IndAtk, IndDef and IndSta are IVs
and BaseAtk BaseDef BaseSta are in this link
https://github.com/justinleewells/pogo-optimizer/blob/master/data/game/pokemon.json
which different pokemon's have different base value
ECpM is here
https://github.com/justinleewells/pogo-optimizer/blob/master/data/game/level-to-cpm.json
which all pokemons are same

For that formula we know attack plays an important role in CP, and different pokemons have different base value, that's means 15/14/15 is better than 14/15/15 for lot of pokemons, and if one pokemon's base def is more than base sta, 15/15/14 is better than 15/14/15.

One result is we could calculate the worst CP, perfect CP, and we have current CP
worst CP = BaseAtk * BaseDef^0.5 * BaseSta^0.5 * (ECpM)^2 / 10
perfect CP = (BaseAtk + 15) * (BaseDef + 15)^0.5 * (BaseSta + 15)^0.5 * (ECpM)^2 / 10
current CP = (BaseAtk + IndAtk) * (BaseDef + IndDef)^0.5 * (BaseSta + IndSta)^0.5 * (ECpM)^2 / 10

so perfect percent = (current CP - worst CP) / (perfect CP - worst CP) =
((BaseAtk + IndAtk) * (BaseDef + IndDef)^0.5 * (BaseSta + IndSta)^0.5 - 
BaseAtk * BaseDef^0.5 * BaseSta^0.5) /
((BaseAtk + 15) * (BaseDef + 15)^0.5 * (BaseSta + 15)^0.5 - 
BaseAtk * BaseDef^0.5 * BaseSta^0.5)

Which we need introduce the first table from justinleewells/pogo-optimizer

so this perfect calculate is more accurate than just (IVatk + IVdef + IVsta) / 45

**Comment by alawing** [comment]
For addition, we should caculate the pokemon's after evolve's perfect, base will change after evolve, but IV not change.
So the BaseAtk, BaseDef, BaseSta value will get from the pokemon after evolve's
in: (current CP - worst CP) / (perfect CP - worst CP)
For Eevee, we need product three CP perfect percent for 3 different evolves.

**Comment by Letrico** [comment]
Why not just get a 15/15/15 and just candy it to max CP? It is almost 0.0001% chance for you to catch a max CP +perfect IV

**Comment by Agronis** [comment]
I'll agree with @Letrico especially if you consider that the CPM has the biggest effect in this matter.

See #498

**Comment by alawing** [comment]
I think CP perfect percent is more accurate than IV perfect percent, it counts attack and pokemon's different more important, but IV perfect percent not. CPM plays not in the CP perfect percent. CP perfect percent only needs IV, and also BaseATK, BaseDEF and Base Sta.

For example, same IV 15 15 10 dragonite is more powerful than 10 15 15 dragonite
which dragonite's base is 250, 212, 182.
IV 15 15 10 = 265 * sqrt(227) * sqrt(192)
IV 10 15 15 = 260 * sqrt(227) * sqrt(197)

**Comment by jabbink** [comment]
duplicate and implemented.
