### ISSUE TITLE
Coloring logging available for jar?

### ISSUE THREAD

**Issue by mrgippy** [jabbink/PokemonGoBot#472]
Is it possible to run the jar file and also have color logging? When I run using "gradlew run", the color logging is all fine, but using "java -jar" there would be no color logging.

**Comment by Forty-Tw0** [comment]
Not sure how it works but from what I understand logs don't support colour, the colour support comes from software. Java executing in a terminal doesn't do this. Maybe with ANSI escape codes? If you are on windows, it is doubtful it will be supported.

**Comment by sodanakin** [comment]
If you just run a single bot consider using a console emulator like Conemu

**Comment by jabbink** [comment]
Color logging is in the jar as well, make sure you use a terminal/cmd that supports colors.
