### ISSUE TITLE
[Suggestion] Dynamic speed for hatching

### ISSUE THREAD

**Issue by siimveskilt** [jabbink/PokemonGoBot#474]
Lets say starting speed is e.g 2m/s (7.2km/h) then store the km that it took to hatch a 2km/5km/10km egg and compare with the ideal hatching scenario which would be for a 2km egg 2km/7.2km/h=0.277(7)hours=16.66(6)minutes. If it takes e.g 1 minute longer to hatch it then the speed is too fast and it would decrease it by 0.1 or if it is in the allowed 1 minute delay then instead increase the speed. The speed increase/decrease amount could scale with the deviated amount.

**Comment by jabbink** [comment]
? The ideal speed to hatch any egg is 2,8m/s

Keep in mind that the server calculates distance walked in a very bad and wrong manner. which makes hatching always take more kilometres than advertised.
