### ISSUE TITLE
[Minor Bug] Incorrect Display of XP Gain While Pokemon Capture

### ISSUE THREAD

**Issue by javaptgl** [jabbink/PokemonGoBot#475]
**Description:**
Incorrect Display of XP Gain While Pokemon Capture.
Not Using Lucky Egg.

**Expected behavior:**
Found pokemon PIDGEY
Encountered pokemon PIDGEY with CP 377 and IV 20%
Using desired_catch_probability_unwanted because Obligatory transfer
Using ITEM_POKE_BALL; Using curve; achieved catch probability: 0.2994308, desired: 0.0
Caught a PIDGEY with CP 377 and IV 20%
**Stamina: 8 | Attack: 1 | Defense: 0 | IV: 9 (20%): [110x XP, 3x Candy, 100x Stardust]**

**Actual behavior:**
Found pokemon PIDGEY
Encountered pokemon PIDGEY with CP 377 and IV 20%
Using desired_catch_probability_unwanted because Obligatory transfer
Using ITEM_POKE_BALL; Using curve; achieved catch probability: 0.2994308, desired: 0.0
Caught a PIDGEY with CP 377 and IV 20%
**Stamina: 8 | Attack: 1 | Defense: 0 | IV: 9 (20%): [210x XP, 3x Candy, 100x Stardust]**

**Version:**
Release - 0.4.3

**Operating System:**
Microsoft Windows Server 2012 R2 Datacenter x64

**Java version:**
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

**Comment by Letrico** [comment]
It is correct. 100xp base , 100xp excellent throw, 10xp curveball

**Comment by pr0ves** [comment]
Closing.
