### ISSUE TITLE
[Issue] 

### ISSUE THREAD

**Issue by Klogzer** [jabbink/PokemonGoBot#476]
**Description:**
Hello, the bot repeatedly uses the same pokestops, seems as if the pokestop blacklisting for several minute stopped working, or broke due to recent changes.

**Expected behavior:**
Use Pokestop, block it go on.

**Actual behavior:**
27 Jul 10:25:33: Looted pokestop 4196b5e0d5364917adecbc92316c71df.16; +0 XP: []
27 Jul 10:25:37: Getting map of (40.77483253744856, -73.9711095663904)
27 Jul 10:25:38: Looting nearby pokestop 4196b5e0d5364917adecbc92316c71df.16
27 Jul 10:25:39: Looted pokestop 4196b5e0d5364917adecbc92316c71df.16; +0 XP: []
27 Jul 10:25:42: Getting map of (40.774798761046696, -73.97114409687606)
27 Jul 10:25:43: Looting nearby pokestop 4196b5e0d5364917adecbc92316c71df.16
27 Jul 10:25:43: Looted pokestop 4196b5e0d5364917adecbc92316c71df.16; +0 XP: []
27 Jul 10:25:47: Getting map of (40.77486096381549, -73.97116236491266)
27 Jul 10:25:48: Looting nearby pokestop 4196b5e0d5364917adecbc92316c71df.16
27 Jul 10:25:48: Looted pokestop 4196b5e0d5364917adecbc92316c71df.16; +0 XP: []
27 Jul 10:25:52: Getting map of (40.774840043606375, -73.97110943722973)
27 Jul 10:25:53: Looting nearby pokestop 4196b5e0d5364917adecbc92316c71df.16
27 Jul 10:25:53: Looted pokestop 4196b5e0d5364917adecbc92316c71df.16; +0 XP: []

**Operating System:**
Win 10 / JVM

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by pashorizer** [comment]
Can you restart it and copy the log from the beginning?
