### ISSUE TITLE
build after update?

### ISSUE THREAD

**Issue by MyUncleSam** [jabbink/PokemonGoBot#478]
**Description:**
Is it necessary to build the bot again after a git update?
(Maybe a short "how to update the bot" on the main page would be great!)

**Comment by Cy4n1d3** [comment]
I'm not sure what you want to know but in general: if there has been a code change (e.g. new commits), a rebuild is necessary. This is done by running `gradlew build`, or whatever task you're aiming for.
If you're starting the bot with `gradlew run` this won't be necessary.

**Comment by Sieberkev** [comment]
Also do `git submodule update --init --recursive` after `git pull` and before `gradlew build`, so any important dependencies (especially the PogoAPI one) are up to date :smile:

**Comment by MyUncleSam** [comment]
Ok my current update script is doing the following steps. If you are correct and a `gradlew run` is enought this script should work (I call it every 20 minutes):

> systemctl stop pokebot.service
echo "---------------------------------------"
date
echo "---------------------------------------"
cd /path/to/theBot/PokemonGoBot/
echo "Updating bot version"
git pull
echo "Updating submodules"
git submodule update --init --recursive
echo "---------------------------------------"
systemctl start pokebot.service

**Comment by pashorizer** [comment]
This is a good way to brick your account if something malfunctions in the `dev` build.

**Comment by MyUncleSam** [comment]
So should I switch to releases?

**Comment by shilch** [comment]
Yes

**Comment by MyUncleSam** [comment]
I am new to git, is there an easy way to tell the pull to only fetch release versions?

**Comment by Cy4n1d3** [comment]
https://stackoverflow.com/questions/17414104/git-checkout-latest-tag might be of interest.

**Comment by MyUncleSam** [comment]
Thank you very much for your help! It is now working fine for me :+1:

**Comment by jabbink** [comment]
>I am new to git, is there an easy way to tell the pull to only fetch release versions?

`git checkout master`

`git pull`

**Comment by MyUncleSam** [comment]
What is the difference / what should be prefered? Currently I am using the one from @Cy4n1d3 

```
#!/bin/bash
...
latesttag=$(git describe --tags)
echo checking out ${latesttag}
git checkout ${latesttag}
```

Or is this the better way?
```
git checkout master
git pull
```

**Comment by shilch** [comment]
first and you are on the safe side

**Comment by jabbink** [comment]
I will make sure that the `HEAD` of  `master` is always a full release/tag.

**Comment by MyUncleSam** [comment]
@jabbink I think it would be great for all users if you could write some "official" update instructions on the start page
