### ISSUE TITLE
[Suggestion] Split keep_pokemon_amount in min and max

### ISSUE THREAD

**Issue by langerhans** [jabbink/PokemonGoBot#479]
**Description:**
The option currently only sets a min value so that you can keep for example 1 of each. But then it will happily keep all pokemon above the set CP and/or IV levels. 
I think it would be beneficial to have a setting for min (as currently) and max amount of pokemon per type to keep. That way we could set keep_pokemon_max=1 and keep_pokemon_min=1 to keep one of each type, which then should be the one with the best stats.

So:

1. Catch Pokemon with CP 2 and IV 2 -> Keep
2. Catch Pokemon with CP 1 and IV 1 -> Transfer
3. Catch Pokemon with CP 3 and IV 3 -> Keep, transfer the first cause this one is stronger.

**Comment by pashorizer** [comment]
btw `keep_pokemon_amount=0` will keep the best stats one.

**Comment by siimveskilt** [comment]
Just set thresholds both to -1...a variable for each type ia unneccesary.

**Comment by langerhans** [comment]
I don't think setting both to -1 has the desired effect?
Setting keep to 0 might, but that seems really implicit.

**Comment by siimveskilt** [comment]
It does, if you have sort by iv false it will keep the highest cp one, else the top ones with best iv which is the way to go with a bot.

**Comment by Cy4n1d3** [comment]
This sounds confusing.

**Comment by langerhans** [comment]
Well I can confirm that setting the transfer thresholds to -1 actually does what I described here. But I agree that is a bit confusing.
