### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Boraida** [jabbink/PokemonGoBot#48]
Getting a 'com.pokegoapi.exceptions.LoginFailedException' exception immidiatly.

The credentials are good, they work on the website and app. I just created a new account.

System: Linux, CentOS

PS: Both Google and PTC arent working..

**Comment by NelsonBrandao** [comment]
The servers are all down. ispokemongodownornot.com

**Comment by Boraida** [comment]
At that time I could login on the mobile app, but not on the bot.

**Comment by Spyderdreams** [comment]
3:10 CST servers went down 55 minutes ago. Your comment is 40 minutes ago

**Comment by Boraida** [comment]
Actually I was trying it like 2 hours ago, but I will try it later again

**Comment by vincentbeutin** [comment]
See https://github.com/jabbink/PokemonGoBot/issues/51

**Comment by jabbink** [comment]
When you tried it 2h ago when the servers were online: you sure you put the correct username and password (no space behind the `=` sign for example)?

**Comment by Boraida** [comment]
Im postive they were

**Comment by jabbink** [comment]
In case your PTC password is longer than 15 chars, only enter the first 15 chars. (major (security) flaw of pokemon.com)

**Comment by irisheoin** [comment]
I was unable to logon last 4 or 5 hours or so, but worked with 0.3.0

**Comment by Boraida** [comment]
Can someone try to login as:
Mochos:asdasdf
Username:password

**Comment by Boraida** [comment]
Still getting the error even with 0.3.0

**Comment by RaeneDev** [comment]
if its a club account verify the email. Only works at the beginning(24 hours?) and then wont connect until verified.

**Comment by Boraida** [comment]
I'd verify and it's 48h, I think

**Comment by RaeneDev** [comment]
Just tested with the account you provided and it works for me, check if you have any spaces anywhere and the config is configured correctly.

**Comment by Boraida** [comment]
It works also with Linux, Ubuntu. So idk whats wrong with CentOS.

**Comment by jabbink** [comment]
>Just tested with the account you provided and it works for me
