### ISSUE TITLE
[Suggestion] Max Pokeballs inventory grouped

### ISSUE THREAD

**Issue by ma4xat** [jabbink/PokemonGoBot#480]
Actually, the bot let us configure the pokeballs in this way:

item_poke_ball=NUMBER
item_great_ball=NUMBER
item_ultra_ball=NUMBER
item_master_ball=NUMBER

I think that it would be better to set a max pokeballs number ( like 250 for example ) and always save the better ones.

For example, actually if i have this configured:

item_poke_ball=90
item_great_ball=90

If i get 2 pokeballs, and 2 greatballs, i drop both (having 90 of everyone in my inventory, ofc ), but i think that is better to keep the 2 greatballs and drop 4 pokeballs.

This way, if i set the max_pokeballs to 200 for example, i will have a max of 200 items formed by pokeball, greatball, ultraball, masterballs, but keeping the better ones.

Sorry for my bad english :(

**Comment by siimveskilt** [comment]
I prefer the current system with normal and great balls limit around 20 and ultra balls high since this sort of relies on your total amount which can vary and everybody wont agree then on the order of importance of all the other items and their amount. Would take a nice junk of time to write up but with very small or no benefits.

**Comment by ma4xat** [comment]
tbh , i dont see why is better the current system.

If u limit pokeballs to 20, greatballs to 20 and, ultraballs to 100, u will drop all the greatballs over 20 regardless ur ultraballs.

With my system, u set the máx pokeballs to, for example 140, and thats is what u are going to get in ur inventory, but if u have 140 pokeball items and u get 2 ultraballs, y will drop 2 pokeballs, not the ultraballs...

And about ur last phrase: "**Keep ultras** at max free space and forget about normal and great balls..." is the bot who determine (based on % of caching) wich ball is needed

**Comment by siimveskilt** [comment]
The current system is not a better system, I'm saying there is no benefit here to achieve. There is no reason to have optimal nr of pokeballs in the first place as the bot will use the regular ones most of the time meaning you will get a large collection of ultra balls. Which you need only for that occasional rare pokemon. It's not like the regular balls aren't good enough. So, use great balls by default, resort to normal balls for most pokemons and use an ultra for the rare ones.

**Comment by marcx093** [comment]
Just do this setting and you are good 

> item_revive=10
item_max_revive=-1
item_potion=0
item_super_potion=30
item_hyper_potion=40
item_max_potion=-1
item_poke_ball=50
item_great_ball=-1
item_ultra_ball=-1
item_master_ball=-1
item_razz_berry=30

>

**Comment by ma4xat** [comment]
Yep, i have something like that:

`item_revive=0
item_potion=0
item_super_potion=0
item_hyper_potion=0
item_max_revive=25
item_max_potion=25
item_poke_ball=50
item_great_ball=-1
item_ultra_ball=-1
item_master_ball=-1
item_razz_berry=-1`

Just thought it was a better way to manage it :)

**Comment by siimveskilt** [comment]
Why do you guys want all those great balls?

**Comment by ma4xat** [comment]
@siimveskilt They are needed for High CP pokemons like ultraballs for bulbasaurs, charmanders and so on...
![image](https://cloud.githubusercontent.com/assets/3372517/17178042/311d8518-5414-11e6-9cc9-30ac5f36f80b.png)
![image](https://cloud.githubusercontent.com/assets/3372517/17178054/394e3516-5414-11e6-8609-b2e66e5691ea.png)
![image](https://cloud.githubusercontent.com/assets/3372517/17178076/4d2f114a-5414-11e6-8388-b0e615156b18.png)

**Comment by siimveskilt** [comment]
No, I mean why do you need more then e.g 20 since they replenish so fast after level 20?

**Comment by marcx093** [comment]
Because why not? better have lots great and ultra balls, with this settings i pretty much am always 100 great balls and 100 ultra balls.

**Comment by siimveskilt** [comment]
Rather have 190 ultra balls and 10 great balls :)

**Comment by marcx093** [comment]
Yes but i'm not the one who choose which ball to use, i just chose to never drop ultra or great ball, i got 100 ultra only because i never drop them even when i get 180 ultra.

**Comment by langerhans** [comment]
Implemented in #946
