### ISSUE TITLE
IDEA: GUI?

### ISSUE THREAD

**Issue by EpicAwesomeWolf** [jabbink/PokemonGoBot#484]
Just a question. Will there ever be a GUI (ex. Pulling the API to show a list of recent caught Pokemon, a Stardust counter, etc.)

**Comment by jabbink** [comment]
Duplicate, and incoming very soon

![image](https://cloud.githubusercontent.com/assets/2461972/17174426/b97fda04-5401-11e6-9d71-d9e28deae0de.png)

**Comment by Sieberkev** [comment]
Work in progress: #233
