### ISSUE TITLE
[LOG ERROR] Just get this error after a lot of time, is with PTC account

### ISSUE THREAD

**Issue by ma4xat** [jabbink/PokemonGoBot#490]
![image](https://cloud.githubusercontent.com/assets/3372517/17178516/0d2cea2a-5416-11e6-84e2-582877d0adf2.png)

**Comment by shilch** [comment]
http://ispokemongodownornot.com/

**Comment by jabbink** [comment]
Ptc login is broken at this moment.

**Comment by ma4xat** [comment]
My fault then :)
