### ISSUE TITLE
[Suggestion] Include CPM when printLn'ing Pokebank.

### ISSUE THREAD

**Issue by Agronis** [jabbink/PokemonGoBot#491]
As the title states.

When the Pokebank prints out inventory - it would be very nice to include their CPM, as well.

This way I know if I should hold out for a better Magikarp that has 98% IV but oh look, it has .3 CPM - trash.

**Comment by pashorizer** [comment]
Every Pokemon has a different cp multiplier range.

**Comment by Agronis** [comment]
@pashorizer  Yes, and.. this is exactly why I would like it to be printed out?

IE:

Have DRATINI () with 620 CP, IV 93% and .6 CPM

**Comment by pashorizer** [comment]
nvm thought you wanted to filter after that

**Comment by Agronis** [comment]
Actually.. I'm going to close this issue and open a new one as there would need to be a filter.
