### ISSUE TITLE
NPE When Refreshing Token

### ISSUE THREAD

**Issue by KyleBoyer** [jabbink/PokemonGoBot#495]
Exception in thread "main" java.lang.NullPointerException
	at com.pokegoapi.auth.GoogleCredentialProvider.refreshToken(GoogleCredentialProvider.java:170)
	at com.pokegoapi.auth.GoogleCredentialProvider.<init>(GoogleCredentialProvider.java:73)
	at ink.abb.pogo.scraper.MainKt.getAuth(Main.kt:44)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:80)

**Comment by pvase666** [comment]
I have same issue

**Comment by alone23** [comment]
same here

**Comment by pr0ves** [comment]
It was a problem of the api, it's fixed now. Do `git submodule update --init --recursive`. 
Closing.

**Comment by sico** [comment]
I'm still getting this error after updating the submodule.

**Comment by siimveskilt** [comment]
Same here, still have this error.

**Comment by KyleBoyer** [comment]
Picture of stack trace:

https://s32.postimg.org/a3f14s5qd/IMG_0574.jpg

**Comment by pr0ves** [comment]
Go to the pokegoapi folder: `cd lib/PokeGoPokeGOAPI-Java`
Then run:
```
git checkout Development
git pull
```
Now do again `gradlew run`

**Comment by jabbink** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/issues/281#issuecomment-235662193

**Comment by siimveskilt** [comment]
C:\Users\s\PokemonGoBot\lib>cd PokeGOAPI-Java

C:\Users\s\PokemonGoBot\lib\PokeGOAPI-Java>git checkout Development
Previous HEAD position was f281522... abstract time behavior to allow mocking and replacing the time by non-System time (#277)
Switched to branch 'Development'
Your branch is up-to-date with 'origin/Development'.

This is driving me crazy :)

**Comment by jabbink** [comment]
`git pull`

**Comment by siimveskilt** [comment]
C:\Users\s\PokemonGoBot\lib\PokeGOAPI-Java>git pull
Already up-to-date.

**Comment by pvase666** [comment]
C:\Users\\Desktop\PokemonGoBot>gradlew run
:PokeGOAPI-Java:extractIncludeProto
:PokeGOAPI-Java:extractProto
:PokeGOAPI-Java:generateProto
:PokeGOAPI-Java:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:PokeGOAPI-Java:processResources UP-TO-DATE
:PokeGOAPI-Java:classes
:PokeGOAPI-Java:jar
:compileKotlin
w: C:\Users\\Desktop\PokemonGoBot\src\main\kotlin\ink\abb\pogo\scraper\tasks\HatchEggs.kt: (42, 17): Name shadowed: result
w: C:\Users\\Desktop\PokemonGoBot\src\main\kotlin\ink\abb\pogo\scraper\util\pokemon\CatchablePokemon.kt: (45, 18): Condition 'result != null' is always 'true'
:compileJava
:processResources UP-TO-DATE
:classes
:run
Exception in thread "main" java.io.FileNotFoundException: config.properties (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:62)
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_101\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 21.954 secs

**Comment by siimveskilt** [comment]
You are missing the config file, as it says in the trace.

**Comment by pvase666** [comment]
PokemonGoBot\lib\PokeGOAPI-Java In this folder ?

**Comment by pr0ves** [comment]
go back to the root folder, PokemonGoBot

**Comment by pvase666** [comment]
I run gradlew build on PokemonGoBot folder.

**Comment by KyleBoyer** [comment]
> Go to the pokegoapi folder: cd lib/PokeGoPokeGOAPI-Java
> Then run:
> 
> git checkout Development
> git pull
> Now do again gradlew run

This fixed it!

**Comment by pvase666** [comment]
Yes, run "gradlew build" on PokeGoPokeGOAPI-Java folder working,

**Comment by siimveskilt** [comment]
*happy dance*
