### ISSUE TITLE
Being a noob #2

### ISSUE THREAD

**Issue by Nozk** [jabbink/PokemonGoBot#497]
**Description:**
Having the same issue as Ticket #420 . ''As a total newby to java I find it extremely difficult to do any of what you all are talking about, but please don't let this scare you and help your fellow human"

**Steps to reproduce:**

    1. Making sure right java.
    2. Downloading everything necessary.
    3. changing the config, no issue there
    4. opening everything in the terminal (put jar in bot file, so terminal currently cd'd to PokemonGoBot-develop)
    5. java -jar pogo.scraper-all-0.4.2.jar

**Expected behavior:**
Access jarfile

**Actual behavior:**
Error: unable to access jarfile

Running on Mac

**Comment by ReignOfComputer** [comment]
Are you on the latest release? Make sure the entire file name is correct ("pogo.scraper-all-0.4.3.jar" for the latest one unless you renamed it).

**Comment by Nozk** [comment]
Problem Solved I believe. Thanks for quick response.

**Comment by Nozk** [comment]
New Error When inputting java -jar pogo.scraper-all-0.4.3.jar:
Exception in thread "main" java.io.FileNotFoundException: config.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:59)

**Comment by ReignOfComputer** [comment]
You're missing the config.properties file, as stated in the error. Follow instructions at the end of this page: https://github.com/jabbink/PokemonGoBot/releases/tag/v0.4.3

**Comment by Sieberkev** [comment]
Make sure the file doesn't end in .txt and the extension is hidden

**Comment by Nozk** [comment]
Solved issue. I previously followed the above steps, but didn't change the (hidden) filename for the template. Had to go to file info and click "Name and Extension" to change it properly. It turned from a pages file into a blank properties file. Thanks
