### ISSUE TITLE
[Suggestion] CPM 

### ISSUE THREAD

**Issue by Agronis** [jabbink/PokemonGoBot#498]
CPM is integral in the deciding factor on the overall quality of your pokemon.

If I have a 100% IV Pokemon with .3 CPM - the 90% IV with .6+ CPM is better.

CPM LVL is based by it's CPM.. obviously.  

But it never changes - see [here](https://github.com/justinleewells/pogo-optimizer/blob/master/data/game/level-to-cpm.json).

To better understand that CPM in general never changes once caught - see [here](https://gist.github.com/pingec/9aa0826583f23f97c658af93d05136f7).

So, I propose the following additions.

 sort_by_cpm : true/false
 set_cpm_threshold : XX
- Self Explanatory

Print CPM w/ Pokebank log.

 - On boot, include CPM next to each Pokemon.
        - Have POKEMON () with XXX CP, XX% IV and XX CPM LVL. Overal Quality XXX%

The most important would be to then maybe build a weight system but before we get into this, I think move sets should also be factored in.

For instance, IV = 80%, CPM = 10%, Move Set = 10%

Final quality of Pokemon = ?

This would determine the absolute best possible candidate in your bank to keep.

Would this best be handled by keeping a localized database of your inventories?

One table per account once we have account management flow integrated?

Oh diddy..

**Comment by Sieberkev** [comment]
Isn't the CPM [different](http://imgur.com/gallery/CWMyC) for each pokemon, so you would have to keep a hardcoded list in the bot with all those values (since those aren't available via the API yet)?

**Comment by Agronis** [comment]
CPM comes in with the Pokemon Data - right next to the IV.

Yes, it's different for each and does not grow with the player as it levels as some have concluded.

See [here](https://gist.github.com/pingec/9aa0826583f23f97c658af93d05136f7)

**Comment by pashorizer** [comment]
@Sieberkev That is additional cpm which scales with the pokemon/power ups. I don't see how it is going to be useful at all.
@Agronis You don't need to see the CPM. You can already see it that a Pidgy with perfect IV may have 10cp which will result in a low cpm but will get higher as long as you power it up.

**Comment by Agronis** [comment]
@pashorizer 

It has been confirmed that the CPM does *NOT* grow with the level of your character.

Once you catch the 'mon - it is set.

As I said in my previous comment, please see [here](https://gist.github.com/pingec/9aa0826583f23f97c658af93d05136f7).

**Comment by Agronis** [comment]
@Sieberkev at what level was your character in that picture?

**Comment by Agronis** [comment]
One more [explanation](http://pingec.si/publish/magikarp.png) in case it isn't clear that..

# CPm > IV > CP
