### ISSUE TITLE
Latest commit: Bot doesn't run

### ISSUE THREAD

**Issue by omar972** [jabbink/PokemonGoBot#503]
**Description:**

**Steps to reproduce:**

1. Update to latest commit
2. Gradlew run

**Expected behavior:**
Bot works

**Actual behavior:**
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_73\bin\java.exe'' finished with non-zero exit value 1
```

**Stacktrace (If it's a crash):**
http://pastebin.com/gtdGYMbt

**Version:**
commit 7e57a9bdd32d2a8f8ec7756f59dff3afaeacc9ff

**Operating System:**
Windows 8.1
**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) Client VM (build 25.101-b13, mixed mode, sharing)

**Comment by jabbink** [comment]
Please post the full console output.

**Comment by omar972** [comment]
http://pastebin.com/shTfaj6s
This is all of it. If you mean the "60 more" part, idk how to show that, would need help.

**Comment by Sieberkev** [comment]
Try this [solution](https://github.com/jabbink/PokemonGoBot/issues/495#issuecomment-235662086)?

**Comment by omar972** [comment]
Well, I already did that a few minutes ago while installing the build, there was no update to the api so, no effect.

**Comment by jabbink** [comment]
Fix incoming on `develop` in a second
