### ISSUE TITLE
WHAT? lol

### ISSUE THREAD

**Issue by LOLwhat123** [jabbink/PokemonGoBot#504]
I logged back on the account and it doesn't have anything done to it lol, am I missing something? Yes its the right account. Same level as it started the bot and the bot said I'm at level 20 or something lol been running it for 2 days straight ish

**Comment by jabbink** [comment]
You're not using the same account. 100% sure. Click logout in the app, and triple check you use the same user that the bot uses

**Comment by LOLwhat123** [comment]
I 100% am lol, idk what it could be. I deleted and token so it auto sets itself and it says it does stuff but nothing happens
