### ISSUE TITLE
[Suggestion] Export pokemon list to CSV/SQL

### ISSUE THREAD

**Issue by rannmann** [jabbink/PokemonGoBot#505]
It would be cool to have a command-line option or config option to keep a database or database-like file up to date with the stats of all your pokemon.  Below are the things I'd love to have access to:

- Pokemon Name
- Pokemon Id (type)
- Favorited Boolean
- CP
- IV
- Stamina (HP)
- Move 1
- Move 2
- iAttack
- iDefense
- iStamina
- cpMultiplier

Of less importance but would still be neat

- Favorited Boolean
- Location acquired
- Height
- Weight

This would allow external applications to manipulate the data,.  The built-in interface for viewing pokemon requires the loading of each individual 'mon, and it's hard to pick the best option out for the one you intend on powering up and leveling.  Additionally, it would allow for a future import option to rename pokemon with the matching stats to prevent accidental deletion.

**Comment by pilotchute** [comment]
@rannmann Yes. All. The. Yes.

**Comment by Sieberkev** [comment]
I have added a PR #536 that will export a bunch of data to a CSV file on each ProfileLoop. If you could check it out?

I think the renaming/favoriting/evolving/... features can be added to the awesome Web GUI system later, but this can be used as a base to parse to a DB anyway :smile:

**Comment by langerhans** [comment]
Added in v0.5.0-alpha3, thanks @Sieberkev !
