### ISSUE TITLE
Pokestops only not working

### ISSUE THREAD

**Issue by classicalDonkey** [jabbink/PokemonGoBot#507]
**Description:**
Ok I am trying the new setting and when I pick the settings as below, it is walking and thats it, not hitting pokestops in a place i know there are like 20 within 100 meters out from the center.

# Should the bot loot the pokestops (true/false)
loot_pokestop=true

# Should the bot catch pokemons (true/false)
catch_pokemon=false

# Shout the bot auto fill incubators with eggs (true/false)
auto_fill_incubator=false

**Version:**
0.4.3

**Operating System:**
Windows 10

**Java version:**
V8 Update 101 (build 1.8.0_101-b13)

**Comment by CosmoRing** [comment]
Search before posting.

See: #461
