### ISSUE TITLE
[Suggestion] Bot API

### ISSUE THREAD

**Issue by rannmann** [jabbink/PokemonGoBot#510]
With the addition of the web UI, the bot runs a webserver.  Would it be easy to add a RESTful API to the bot?  Ex: The ability to GET `/player/level`, inventory, pokemon list, session statistics, and perform some basic actions such as shutting down the bot.

**Comment by alone23** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java

**Comment by MASSV** [comment]
Errr...the existing API does all of that already? what are you asking?

**Comment by rannmann** [comment]
You can get bot session statistics and perform bot actions (shutdown, change config options, etc) with the current API?

**Comment by Cy4n1d3** [comment]
I'd also like to have an endpoint to update the location the bot should head to or is located at :)

**Comment by langerhans** [comment]
This exists by now. Closing.
