### ISSUE TITLE
How do I attach a Intellij debugger to the running jvm ?

### ISSUE THREAD

**Issue by rngrofl** [jabbink/PokemonGoBot#512]
So the build and run goes fine on my windows 7 computer.
I already installed  Lombok plugin for Intellij.

I tried to run the jvm using gradlew run --debug-jvm / gradlew run --no-daemon -Dorg.gradle.debug=true

I imported the project into Intellij, and start with remote debug.

I could see the following from Intellij command line:
" Connected to the target VM, address: 'localhost:5005', transport: 'socket'
Disconnected from the target VM, address: 'localhost:5005', transport: 'socket'"

I could click the start and "stop remote" from Intellij . But looks like the program never stops at breakpoints.

So how do you guys debug? Just use print?

**Comment by jabbink** [comment]
Upper right corner in IntelliJ

![image](https://cloud.githubusercontent.com/assets/2461972/17189124/6fc708b2-5440-11e6-8948-6bd395c32f78.png)

Don't click this icon 
![image](https://cloud.githubusercontent.com/assets/2461972/17189129/788fc4ac-5440-11e6-82c2-423e6f60cea9.png)

click this one: 
![image](https://cloud.githubusercontent.com/assets/2461972/17189132/7e4abbc2-5440-11e6-82fa-e5016b5db693.png)

**Comment by rngrofl** [comment]
Yeah this I know I clicked the debug remote button.  The program just never stops at breakpoints. It keeps running.

**Comment by rngrofl** [comment]
Is this the reason?
@jabbink 

JS: fix that kotlin's breakpoints don't work with JavaScript debugger 

https://github.com/jetbrains/kotlin/commit/47e1ff34f0cbfa5137f3e9598f7955f107bf3815

**Comment by jabbink** [comment]
No idea, debugging and breakpoints work for me with kotlin 1.0.3 on IntelliJ IDEA 2016.1
