### ISSUE TITLE
[Suggestion] Sort Pokebank in the webinterface

### ISSUE THREAD

**Issue by kasagon** [jabbink/PokemonGoBot#514]
It would be handy if you can sort the Pokebank in the webinterface on CP and IV with a radio button or drop-down selector? How it is right now you need to restart the whole application to change the sort order.

Besides of that, a small thing I noticed: the notification box is really big for the 2 options that is has. Maybe adjust the height / min-height to 100px?

**Comment by tyman1292** [comment]
Webinterface ??

**Comment by Sieberkev** [comment]
#233

**Comment by Emuuung** [comment]
Web interface was merged in the develop branch a few hours ago, `check localhost:8000` in your web browser (Chrome, Safari, Mozilla, etc) when running the bot.

**Comment by kasagon** [comment]
They are still working with it, I think. Since the Egg window is not implemented yet (still there is some in the web code). 

It also would be nice that you would see the CP and IV (and time?) of the Pokemon you caught when you click on them on the map.

**Comment by Emuuung** [comment]
Egg-hatching window is still in development, but GUI is very functional already.

**Comment by Emuuung** [comment]
Anyways, we going off-topic, I did suggested this in #233 before it was merged. I don't know if they see it.

**Comment by Sieberkev** [comment]
The build-in webserver has been removed and replaced with some [external GUI](https://github.com/jabbink/PokemonGoBot/tree/gh-pages#custom-de-centralized-guis)'s.

We do not maintain their repositories, but you can ask on their issue trackers for extra functionality :)
