### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Leodenact** [jabbink/PokemonGoBot#515]
I am currently farming for squirtles/charmanders and dratinis. I've found different nest to find them in, now to the suggestion:

Once i set my starting location it will find some of my prefered pokemons in the beginning, but after a short while, the bots get far away from the starting location and thus not finding any of them

Is it possible to make in the config the radius it should walk within? like walk_within_meters=200 or whatever you choose.

Cheers :)

**Comment by jabbink** [comment]
#328
