### ISSUE TITLE
[Web GUI] (sockets) only listen on "localhost"

### ISSUE THREAD

**Issue by ColeB27** [jabbink/PokemonGoBot#519]
After portforwarding the port for the gui, I try to connect from my external IP Address, but the result is no data shown from the GUI, I opened the listener port aswell.

**Comment by jabbink** [comment]
Issue is that it only listens on localhost, afaik. renaming your issue.

**Comment by tyman1292** [comment]
is gui in 4.3 prebuilt?

**Comment by jabbink** [comment]
No. Test release (prebuilt) coming soon

**Comment by tyman1292** [comment]
Cant wait.

**Comment by ColeB27** [comment]
@jabbink thanks for the title change, better description of issue

**Comment by ColeB27** [comment]
@shilch

**Comment by celsian** [comment]
Fixed in #521, please close.
