### ISSUE TITLE
[Suggestion] Allow use of GMaps for more realistic pathing

### ISSUE THREAD

**Issue by fongoid** [jabbink/PokemonGoBot#520]
Put in a toggle and API key in settings, and grab walking directions between pokestops from Google API.
(My Java is super rusty or I'd do it)

e.g.
https://github.com/SwipeX/PokeMate/blob/master/src/main/java/dekk/pw/pokemate/tasks/Navigate.java

**Comment by jabbink** [comment]
almost implemented @pr0ves 

also #157 

also keep in mind that this will drastically reduce your xp/hour
