### ISSUE TITLE
Make option to keep more than just the highest rated Pokemon

### ISSUE THREAD

**Issue by jabbink** [jabbink/PokemonGoBot#53]
eg allow saving the top 5

**Comment by Spyderdreams** [comment]
If you name your highest I think that would be a fix Like I have a 1500 CP Arcanine I change his name to save him and start looking for a secondary. My bot is running with "autotransfer=true" and I have two now.

**Comment by jabbink** [comment]
Renaming doesn't prevent a transfer. Being above `transfer_cp_threshold` (default 400) prevents it.

**Comment by pashorizer** [comment]
Is anyone working on this? Otherwise I'll look into it tomorrow.
