### ISSUE TITLE
[Web GUI] Add name of trainer in title

### ISSUE THREAD

**Issue by jabbink** [jabbink/PokemonGoBot#534]
**Description:**
Makes it easier when you have many tabs with many bots to find a specific tab

**Comment by Emuuung** [comment]
@jabbink Do you mean adding the name of your PTC account or your google email to title?

**Comment by kasagon** [comment]
@Emuuung I think he means your trainer name, This should be not that hard to implement with JavaScript (document.title code), plus there is already a variable of the trainer name.

**Comment by Emuuung** [comment]
Ah, I was confused, you mean the title of the web browser when selecting the web GUI, I thought you meant the Profile window, because it already has the name of the trainer.

**Comment by langerhans** [comment]
This works in the RocketTheme UI.
