### ISSUE TITLE
[Suggestion] Evolve only for Pokedex registry

### ISSUE THREAD

**Issue by Emuuung** [jabbink/PokemonGoBot#535]
Since there is still a lot of discussion on how to implement an **evolving** strategy to the bot, there should be a separate feature to evolve pokemon only to fulfill the pokedex registry, this way if the bot catches a pokemon with 1 or 2 evolution, and their respective evolution are not in your pokedex registry, the bot will automatically evolve your strongest one in your pokebank (by CP or IV) when all the required resources are met. It could still be set to `false` as default.

**Comment by Loewe1000** [comment]
+1

**Comment by Agronis** [comment]
Please see #465 and close this as a duplicate.

**Comment by Emuuung** [comment]
@Agronis I realized the discussion was open in another issue as I stated in my first post, I **still** encourage a separate discussion because this a no-brainer, it doesn't take in consideration if it should use lucky eggs and it doesn't try to maximize EXP, nor tries to build the best team possible, it **JUST** builds the pokedex registry.

I hope a someone can contribute with a code/commit for this.

**Comment by devinsba** [comment]
@Emuuung my PR https://github.com/jabbink/PokemonGoBot/pull/444 already implements this. I currently have it default to a power/pokedex top priority. Then it focuses exclusively on power after that. Then XP
