### ISSUE TITLE
GUI only showing log

### ISSUE THREAD

**Issue by mopho12** [jabbink/PokemonGoBot#539]
**Description:**
Using release 0.5.0-alpha the GUI is only showing the log. 

**Steps to reproduce:**

1. Start bot using release 0.5.0-alpha.
2. Direct browser to localhost:8000

**Expected behavior:**
Should see the GUI as outlined in index.html file with map and player statistics.

**Actual behavior:**
See only reproduction of cmd line log. 

**Version:**
0.5.0-alpha

**Operating System:**
Windows 7

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by Alfondoo** [comment]
Move the window 💃

**Comment by Emuuung** [comment]
Mini-windows are resizeable and moveable.

**Comment by mopho12** [comment]
ah well now i just feel like a dumbass. Is there any way to change it so that all of the windows don't stack on top of each other?

**Comment by shilch** [comment]
The state  oft the Windows is saved
