### ISSUE TITLE
Hang around clusters of lured pokestops

### ISSUE THREAD

**Issue by jabbink** [jabbink/PokemonGoBot#54]
If there are multiple (or even one) pokestop with a lure, make an option to just idle there until the lure is gone.

**Comment by jabbink** [comment]
For now, dirty fix: `speed=0`

**Comment by apexjnr** [comment]
Pro problem solver @jabbink  i fcking love it X'D

**Comment by cleftfairy** [comment]
did this work? I tried it but my bot wandered off following the pokestops anyway. Even setting speed super low didn't seem to stop it.

**Comment by apexjnr** [comment]
@cleftfairy  never worked when i tried
