### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by pikachukaki** [jabbink/PokemonGoBot#542]
I just d/w this file and i can't or it wont let me login my credentials are correct!!
Server refused your login credentials. Are they correct?

**Comment by Agronis** [comment]
Please, form a complete sentence - even if in another language.

I don't understand what the problem is beyond possibly the fact the program is telling you that your credentials you entered are incorrect.

**Comment by pikachukaki** [comment]
Ok my bad it didn't want the google maps token in the config file!!!

**Comment by Agronis** [comment]
Please close this issue.

**Comment by pikachukaki** [comment]
calm m8

**Comment by Agronis** [comment]
Welcome to github.
