### ISSUE TITLE
Option to hide pokemon from the map

### ISSUE THREAD

**Issue by sargunster** [jabbink/PokemonGoBot#543]
![Screenshot](http://i.imgur.com/YveUvSP.png)

This map is pretty hard to read without having to zoom really far in. It would be a lot more clear if there was an option to hide pokemon icons from the map.

**Comment by tyman1292** [comment]
I think they should be removed after 30 sec or something.

**Comment by Emuuung** [comment]
I was gonna suggest the same but I just kept on using refresh for now, so I'd rather they work on something else right now; like the eggs windows.

**Comment by sargunster** [comment]
Refresh isn't really a solution, since it resets other stuff like the path.

**Comment by cwliias** [comment]
where did you even get this map from... I feel like im missing something from this program lol. I just run mine in cmd and have no map

**Comment by sargunster** [comment]
With the latest code, pull up http://localhost:8000/ while it's running.

You can change that port in the config file.

**Comment by cwliias** [comment]
all i got when i went there was a CMD prompt print out and 2 check boxes for notifications

**Comment by ursalame** [comment]
To delete all the pokemons from the map and their reference run in your browser console:
`caughtPokemonMarkers.forEach(function(marker) {marker.setMap(null);});caughtPokemonMarkers = [];`

or run in your browser URL:
`javascript:caughtPokemonMarkers.forEach(function(marker) {marker.setMap(null);});caughtPokemonMarkers = [];`

**Comment by ursalame** [comment]
To add a clear map button run this in your browser console:
```

//create btn
var btn = document.createElement("BUTTON");
var t = document.createTextNode("Clear map");
btn.appendChild(t);

//add btn action
btn.onclick=function(){clearMap();}; 

//append btn
var windowMap = document.getElementById("window-map");
var contentDiv = windowMap.getElementsByClassName("content")[0];
var optionsDiv = contentDiv.getElementsByTagName("div")[0];

optionsDiv.appendChild(btn);

//Clear functions
function clearMap(){
	deleteCaughtPokemonMarkers();
	deletePokestopMarkers();
	deletePolyLine();
}

function deleteCaughtPokemonMarkers(){
	caughtPokemonMarkers.forEach(
	    function(marker) {
		marker.setMap(null);
	    }
	);
	caughtPokemonMarkers = [];
}

function deletePokestopMarkers(){
	for (key in pokestopMarkers) {
	    pokestopMarkers[key].setMap(null);
	}

	pokestopMarkers = {};
}

function deletePolyLine(){
	polyLine.clear();
}
```

**Comment by cwliias** [comment]
Could you post a SS @langerhans  where it goes, The cmd window wont let my add anything while the bots running.

**Comment by langerhans** [comment]
In Chrome, press F12, go to the Console tab, paste the snippet into the input field at the bottom and press enter.

<img width="388" alt="bildschirmfoto 2016-07-28 um 09 44 37" src="https://cloud.githubusercontent.com/assets/5160000/17204827/f2693576-54a7-11e6-83df-aa15700f4f02.png">

There it is. I like it, could be two buttons to clear pokemon and pokestops maybe? @ursalame Maybe you want to put in a PR with this?

**Comment by russr123** [comment]
im not seeing any stops or pokes on the map?

**Comment by russr123** [comment]
28 Jul 20:52:01: Error running loop ProfileLoop!
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:73)
        at ink.abb.pogo.scraper.tasks.HatchEggs.run(HatchEggs.kt:22)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:177)
        at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:106)
        at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:32)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:71)
        ... 7 more

**Comment by sargunster** [comment]
@russr You should create a new issue for your error, since it's not related to this issue.

**Comment by Sieberkev** [comment]
The build-in webserver has been removed and replaced with some [external GUI](https://github.com/jabbink/PokemonGoBot/tree/gh-pages#custom-de-centralized-guis)'s.

We do not maintain their repositories, but you can ask on their issue trackers for extra functionality :)
