### ISSUE TITLE
Not able to get XP or items from stops

### ISSUE THREAD

**Issue by MrLuisArano** [jabbink/PokemonGoBot#548]
**Description:**
Not able to get XP or items from stops

**Steps to reproduce:**

1. Start Java application
2. See config values below
`
desired_catch_probability=0.8
desired_catch_probability_unwanted=0.8
random_next_pokestop_selection=1
speed=3.00
loot_pokestop=true
catch_pokemon=true
auto_fill_incubator=true
drop_items=false
item_revive=30
item_max_revive=30
item_potion=0
item_super_potion=100
item_hyper_potion=100
item_max_potion=100
item_poke_ball=100
item_great_ball=100
item_ultra_ball=100
item_master_ball=100
item_razz_berry=100
display_pokestop_rewards=true
display_pokemon_catch_rewards=true
display_keepalive=true
display_pokestop_name=true
autotransfer=false
keep_pokemon_amount=10
sort_by_iv=false
always_curve=false
never_use_berries=true
transfer_iv_threshold=70
transfer_cp_threshold=400
ignored_pokemon=MEWTWO
obligatory_transfer=DODUO,RATTATA,CATERPIE,PIDGEY`

**Stacktrace (If it's a crash):**
`28 Jul 00:06:43: Looted pokestop "Origami Sculpture"; +0 XP: []
28 Jul 00:06:44: Walking to pokestop "Origami Sculpture"
28 Jul 00:06:44: Walking to (28.29284, -81.408081) in 0.4257175709291317 steps.
28 Jul 00:06:44: Destination reached.
28 Jul 00:06:48: Getting map of (28.292868051750425, -81.40809437605168)
28 Jul 00:06:48: Looting nearby pokestop "Origami Sculpture"
28 Jul 00:06:49: Looted pokestop "Origami Sculpture"; +0 XP: []
28 Jul 00:06:49: Walking to pokestop "Origami Sculpture"
28 Jul 00:06:49: Walking to (28.29284, -81.408081) in 0.5742824334597301 steps.
28 Jul 00:06:49: Destination reached.
28 Jul 00:06:53: Getting map of (28.292887635974942, -81.408096004678)
28 Jul 00:06:53: Looting nearby pokestop "Origami Sculpture"
28 Jul 00:06:53: Looted pokestop "Origami Sculpture"; +0 XP: []
28 Jul 00:06:54: Walking to pokestop "Origami Sculpture"
28 Jul 00:06:54: Walking to (28.29284, -81.408081) in 0.42571756174812464 steps.
28 Jul 00:06:54: Destination reached.
28 Jul 00:06:58: Getting map of (28.292847114296535, -81.40809305893973)
28 Jul 00:06:58: Looting nearby pokestop "Origami Sculpture"
28 Jul 00:06:59: Looted pokestop "Origami Sculpture"; +0 XP: []
28 Jul 00:06:59: Walking to pokestop "Origami Sculpture"
28 Jul 00:06:59: Walking to (28.29284, -81.408081) in 0.5742824456816269 steps.
28 Jul 00:06:59: Destination reached.`

**Version:**
0.4.3

**Operating System:**
MAC OSX

**Java version:**
1.8.0

**Comment by Letrico** [comment]
You are soft banned. Try not to login at 2 different places in a short period of time. Soft ban time varies from 1 minute to few hours depending on how far you moved.

**Comment by MrLuisArano** [comment]
I am now able to login without a problem, sorry for the post
