### ISSUE TITLE
Changing the port with jar Release?

### ISSUE THREAD

**Issue by Mewks** [jabbink/PokemonGoBot#550]
Hi, I'm trying to figure this out and I'm sorry if its simple but how do I change the port of the web GUI if I'm using the jar release?

I can see the gui_port handle mentioned can I just add that into the config file? Or is it a command line thing? Thanks

**Comment by cwliias** [comment]
change it in the config i believe

**Comment by Mewks** [comment]
Yep its working thanks. Please close.
