### ISSUE TITLE
Improve destination in WebGUI

### ISSUE THREAD

**Issue by PabliniBis** [jabbink/PokemonGoBot#552]
whenever the you select a destination with right click in the map, it goes back to starting point.

it would be better to search for new pokestops around last destination marked

**Comment by langerhans** [comment]
Hm, that's exactly what it does for me, just checked on my map.

**Comment by langerhans** [comment]
Did you happen to click far outside of the starting area maybe? There is an initial starting area and normally the bot is not allowed to leave it. You can try `allow_leave_start_area=true` in the config and see if the problem persists.

**Comment by cwliias** [comment]
The right click feature has to be the best thing ever

**Comment by joligario** [comment]
Feature already works as @langerhans mentioned. Recommend close.

**Comment by langerhans** [comment]
Clsoing due to inactivity.
