### ISSUE TITLE
[Question] Whats Leave starting area for?

### ISSUE THREAD

**Issue by cwliias** [jabbink/PokemonGoBot#554]
Exactly how does this feature work/limit you

Allow leaving the starting area
allow_leave_start_area=false

# Max distance from starting point the bot should ever go in meters
# (-1: only limited by the initial pokestops (~3*3km); with allow_leave_start_area=true unlimited)
spawn_radius=-1

**Comment by langerhans** [comment]
The bot sets a certain area it roams around in (~3x3km, initial pokestop scan). With this feature you can make it also leave this area (`allow_leave_start_area=false`), or limit it further by using spawn_radius.
