### ISSUE TITLE
Bot not transfering Pokemon?

### ISSUE THREAD

**Issue by LOLwhat123** [jabbink/PokemonGoBot#557]
I fixed the config file and it finally worked on my account but now its saying my inventory is full stopping catching.
I set config to keep 1 of each and 80 IV and CP 400 default.

Went from 6 to 19 within 6-7 hours great bot btw :D

**Comment by pashorizer** [comment]
`autotransfer=true`?

**Comment by jabbink** [comment]
Also, maybe your inventory is full because those 250 Pokemon are above those thresholds.

**Comment by jabbink** [comment]
Or did you set that max keep option as well?

**Comment by Agronis** [comment]
>I set config to keep 1 of each and 80 IV and CP 400 default.

So - I think we need more clarification but what this means is that:

Regardless of CP/IV - You'll at least have 1 of each Pokemon.
If I capture a Pokemon =<80% - I will keep this, regardless if I already have one or not.
If I capture a Pokemon =<400CP - I will also keep this.

Your inventory, after like level 15 - would fill up fast.

**Comment by LOLwhat123** [comment]
fixed it, its the CP thing put CP higher and it worked. But what if I catch a max magikarp aka 262 i think :/ I wanna keep the fker lol
