### ISSUE TITLE
Error logging in

### ISSUE THREAD

**Issue by Rishabhpatted24** [jabbink/PokemonGoBot#558]
I use google , 
This is what i am getting today
http://prntscr.com/byj9gc
using 0.4.3

**Comment by pr0ves** [comment]
The servers are down, always check http://ispokemongodownornot.com if you have login problems. 
Closing.

**Comment by miracho** [comment]
servers are ok bro. but google is reply "null" codes.

**Comment by pr0ves** [comment]
Try the 0.5.0 version, and tell me if there are still problems.

**Comment by tessi** [comment]
This is a thing I get (which the author might mean)

```
28 Jul 11:54:23: Error running loop WalkingLoop!
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:307)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
        at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
        at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:82)
        at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:21)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:305)
        ... 10 more
```

maybe they changed their protobufs?

**Comment by pierobj** [comment]
Same issue here on 0.4.3, servers are good to go, the app is working fine.

**Comment by Arihiza** [comment]
Getting errors too. Keep on going though.
![cccc](https://cloud.githubusercontent.com/assets/20701055/17209221/1cfac2b0-5510-11e6-9c28-1a170fafe31b.png)

**Comment by karael** [comment]
function to fix (in main.kt) must be smthing like this

`fun getAuth(settings: Settings, http: OkHttpClient): CredentialProvider {
    val username = settings.username
    val password = settings.password

    val token = settings.token()

    val auth = if (username.contains('@')) {
        try {
            val token = GoogleAutoCredentialProvider(http, username, password)
        } catch (e: LoginFailedException) {
            throw e
        } catch (e: RemoteServerException) {
            throw e
        } catch (e: Exception) {
            // sometimes throws ArrayIndexOutOfBoundsException or other RTE's
            throw RemoteServerException(e)
        }
    } else {
        try {
            PtcCredentialProvider(http, username, password, time)
        } catch (e: LoginFailedException) {
            throw e
        } catch (e: RemoteServerException) {
            throw e
        } catch (e: Exception) {
            // sometimes throws ArrayIndexOutOfBoundsException or other RTE's
            throw RemoteServerException(e)
        }
    }

    return auth
}`

**Comment by pierobj** [comment]
Same issue on 0.5.0-alpha.

![screenshot](https://cloud.githubusercontent.com/assets/20699997/17209415/380bcae8-54bd-11e6-9b45-214ba3a63358.png)

**Comment by Kiggerbare** [comment]
Im getting the same trying to login, and working fine on the phone.

**Comment by Evuse** [comment]
I'm getting the same error with google logins.

java -jar pogo.scraper-all-0.5.0-alpha.jar 
28 lug 12:18:11: Logging in to game server...
D/GoogleCredentialProvider: 0
D/GoogleCredentialProvider: Get user to go to:null and enter code:null

With all version. 0.3 0.4 0.5. With the zipped version and with the github version :(

**Comment by pr0ves** [comment]
get the new config file https://raw.githubusercontent.com/jabbink/PokemonGoBot/master/config.properties.template
For the protobuf errors, go here #562

**Comment by pierobj** [comment]
Already used the last config file on 0.5.0-alpha.

**Comment by karael** [comment]
@pr0ves api have been update (login function has changed) so it's not about config problem.

**Comment by tessi** [comment]
Also, the stacktrace i posted above resolved itself. ¯\_(ツ)_/¯

**Comment by Evuse** [comment]
Last version with last config file, even trying #562. No way to make it works

**Comment by SiriusCrypto** [comment]
same issue, getting
D/GoogleCredentialProvider: Get user to go to:null and enter code:null

**Comment by Kiggerbare** [comment]
Seen in another post with the same issue someone say.
"the Google Rocket API project is at limit. There will be no more new device id for a while for google account. Try login with your PTC account or create a new one"
Perhaps it's the same here.

**Comment by Evuse** [comment]
What do you mean? i've always used my google account. is not a new one!

**Comment by Coldasicex** [comment]
guys, please #545
also, google accounts needs the new API...there is nothing we can do, just wait for a new release.
And PTC login servers are down...
Just chill
![qhuhcuc](https://cloud.githubusercontent.com/assets/20695595/17210289/0353f3a4-5498-11e6-8b4d-2525d3a13367.png)

**Comment by Arihiza** [comment]
It is working for me atm using my google account on 0.4.3.

**Comment by pr0ves** [comment]
Guys the fix for google logins should come with #559

**Comment by karael** [comment]
Ok working at home, but I did some changes on PokemonApi, waiting for fix then i ll PR

**Comment by Mewks** [comment]
Everything is working again....with no changes made. Still using the original 0.5 alpha.

**Comment by SiriusCrypto** [comment]
> Everything is working again....with no changes made. Still using the original 0.5 alpha.
nope still same here

**Comment by pr0ves** [comment]
The bot will work if you still have a token, it won't if you deleted it. Wait for karael's fix.
Also we'll try to release a new jar when the fix is implemented. You have only to wait.

**Comment by kasagon** [comment]
@pr0ves I can't get it running with token as well though:

    D/RequestHandler: Authenticated with static token
    D/RequestHandler: Authenticated with static token
    28 jul 14:31:55: Server returned unexpected error
    28 jul 14:31:55: Retrying...
    D/RequestHandler: Authenticated with static token
    D/RequestHandler: Authenticated with static token

**Comment by SiriusCrypto** [comment]
@kasagon keep in mind there are also server problems at login and game, http://www.mmoserverstatus.com/pokemon_go

**Comment by kasagon** [comment]
@pr0ves  @SiriusCrypto 
It looks like it is running though, even with that unexpected server error, closed CMD already, but after a while the webGUI started running.

**Comment by pr0ves** [comment]
@kasagon How old is the token?

**Comment by kasagon** [comment]
@pr0ves best timing ever?
Token was a few hours old, but it is working now, I don't know how or why though, since I closed CMD already. I will relaunch the bot in a few minutes and see what it does then.

**Comment by Evuse** [comment]
nothing has changed. help!
cannot login to google

**Comment by wudustan** [comment]
It’ll be alright. Just a Google API update. Fix incoming just gotta wait

**Comment by Evuse** [comment]
oki'll wait. Thanks :)

**Comment by thehu1k** [comment]
Can it be an problem that my google account detected some wierd activities ?

![knipsel1223](https://cloud.githubusercontent.com/assets/14089467/17213985/26a6deea-54d7-11e6-9979-63e55b17b525.PNG)

**Comment by Evuse** [comment]
no, i' using the bot since 6 days. Withu changing anything today is not working

**Comment by Evuse** [comment]
java -jar pogo.scraper-all-0.3.0.jar 
Display Keepalive Coordinates setting ("display_keepalive") not specified, defaulting to "true".
Logging in to game server...
D/GoogleLogin: Get user to go to:null and enter code:null

every account, every bot version.

**Comment by TheJ0k3r** [comment]
we know they are makening an fix man just wait

**Comment by ApexZ** [comment]
I have missed out on 3 dragonites now

**Comment by WillymarJ** [comment]
i use 0.5.0 alpha and login with google its error like `Logging in to game server...
D/GoogleLogin: Get user to go to:null and enter code:null`

**Comment by TunnelSnakesThatsus** [comment]
@WillymarJ  happenning for everyone i think...

**Comment by Rishabhpatted24** [comment]
i think this is a bug for everyone...best would be to be patient and wait for an update :)

**Comment by langerhans** [comment]
Rejoice brothers and sisters! Bot Jesus came down from bot heaven and brought us the fix in form of #575 . You shall be patient for a few more minutes until you can download the new release and go forth to spread the word of bot Jesus and how he fixed Google login for you!

**Comment by pierobj** [comment]
Still doesn't work to me with Google Login (0.5.0-alpha2), it returns:

`Server refused your login credentials. Are they correct?`

**Comment by pierobj** [comment]
@ #583
