### ISSUE TITLE
Latest build fails

### ISSUE THREAD

**Issue by mbaan** [jabbink/PokemonGoBot#56]
./gradlew build
:compileKotlin
e: /home/marco/pogo/git/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Main.kt: (14, 27): Unresolved reference: PtcLogin
e: /home/marco/pogo/git/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Main.kt: (82, 13): Unresolved reference: PtcLogin
e: /home/marco/pogo/git/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Main.kt: (86, 13): Unresolved reference: PtcLogin
:compileKotlin FAILED

Haven't had time to debug this myself. If it is something specific to my situation I'll happily investigate once I get home.

**Comment by mbaan** [comment]
To be clear, by latest I mean 089a0ff80a474b212cd0e4265166bf901093b0c8

**Comment by jabbink** [comment]
`./gradlew --refresh-dependencies clean build`
