### ISSUE TITLE
Not sure why it's stuck at building 91%

### ISSUE THREAD

**Issue by kelvinblade** [jabbink/PokemonGoBot#561]
**Description:**
Not sure why it's stuck at building 91%

**Steps to reproduce:**

1. ./gradlew clean build
2. ./gradlew run

**Expected behavior:**
Bot should be running?

**Actual behavior:**
Bot doesn't run

**Stacktrace (If it's a crash):**
:PokeGOAPI-Java:extractIncludeProto UP-TO-DATE
:PokeGOAPI-Java:extractProto UP-TO-DATE
:PokeGOAPI-Java:generateProto UP-TO-DATE
:PokeGOAPI-Java:compileJava UP-TO-DATE
:PokeGOAPI-Java:processResources UP-TO-DATE
:PokeGOAPI-Java:classes UP-TO-DATE
:PokeGOAPI-Java:jar UP-TO-DATE
:compileKotlin UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
28 Jul 17:52:53: Logging in to game server...
D/GoogleCredentialProvider: 0
D/GoogleCredentialProvider: Get user to go to:null and enter code:null
> Building 91% > :run

**Version:**
 v0.5.0-alpha

**Operating System:**
osx 10.11.5

**Java version:**
java version "1.8.0_101"

**Comment by ridwanariefin** [comment]
same here.

**Comment by karael** [comment]
Yep, bug already reported but it's kt and harder than java to fix for me I don't have setup my kt env, waiting for owner fix

**Comment by ridwanariefin** [comment]
i tried another bot program, and the problem still same, null.
sorry for bad english.

**Comment by langerhans** [comment]
This is unrelated to the google login error. The command will always be at 91% because the process will run under gradle and since it technically never finishes. Nothing ti worry about.

For google login issues check #545.
