### ISSUE TITLE
Error InvalidProtocolBufferException

### ISSUE THREAD

**Issue by pr0ves** [jabbink/PokemonGoBot#562]
Anybody that gets this error try this, from the root folder:
```
git submodule update --init --recursive
cd lib/PokeGoAPI-Java
git checkout Development
git pull
gradlew build
cd ../..
gradlew run
```

Report back if it worked

**Comment by pashorizer** [comment]
I had it before, but it seems like it solved it by himself.  Did not interrupt the jar

**Comment by pr0ves** [comment]
Right, closing then since looks like it's solved.

**Comment by Evuse** [comment]
I get another error if i do this.

./gradlew build
:extractIncludeProto
:extractProto
:generateProto
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
/Users/Carlo/Downloads/pkmn/27luglio/prova/PokemonGoBot/lib/PokeGOAPI-Java/src/main/java/com/pokegoapi/api/inventory/Inventories.java:139: error: cannot find symbol
> Building 15% > :compilif (itemData.getCandy().getFamilyId() != PokemonFamilyIdOuterClass.PokemonFamilyId.UNRECOGNIZED
			            ^
  symbol:   method getCandy()
  location: variable itemData of type InventoryItemData
/Users/Carlo/Downloads/pkmn/27luglio/prova/PokemonGoBot/lib/PokeGOAPI-Java/src/main/java/com/pokegoapi/api/inventory/Inventories.java:140: error: cannot find symbol
					&& itemData.getCandy().getFamilyId() != PokemonFamilyIdOuterClass.PokemonFamilyId.FAMILY_UNSET) {
					           ^
  symbol:   method getCandy()
  location: variable itemData of type InventoryItemData
/Users/Carlo/Downloads/pkmn/27luglio/prova/PokemonGoBot/lib/PokeGOAPI-Java/src/main/java/com/pokegoapi/api/inventory/Inventories.java:142: error: cannot find symbol
						itemData.getCandy().getFamilyId(),
						        ^
  symbol:   method getCandy()
  location: variable itemData of type InventoryItemData
/Users/Carlo/Downloads/pkmn/27luglio/prova/PokemonGoBot/lib/PokeGOAPI-Java/src/main/java/com/pokegoapi/api/inventory/Inventories.java:143: error: cannot find symbol
						itemData.getCandy().getCandy()
						        ^
  symbol:   method getCandy()
  location: variable itemData of type InventoryItemData
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 16.963 secs

**Comment by pashorizer** [comment]
@Evuse Go into your Project folder lib/pokegoapi
`git checkout Development`
`git pull`

and build again

**Comment by Evuse** [comment]
this is totally wrong. Wrong folder, wrong command :(
