### ISSUE TITLE
Bot doesn't show when you don't have any Pokeball, and doesn't resume catching after you got some Pokeballs.

### ISSUE THREAD

**Issue by kasagon** [jabbink/PokemonGoBot#563]
#### Log:

28 jul 04:30:53: Caught a SPEAROW with CP 100 and IV 57%
 Stamina: 2 | Attack: 12 | Defense: 12 | IV: 26 (57%): [200x XP, 3x Candy, 100x Stardust
28 jul  jul 04:30:53: Going to transfer SPEAROW with CP 100 and IV 57%; reason: CP < 500 and IV < 80% 
28 jul 04:30:53: Resuming walk.
28 jul 04:30:57: Getting map of (XX.XXXX, XX.XXXX)
28 jul 04:31:02: Getting map of (XX.XXXX, XX.XXXX)
28 jul 04:31:07: Getting map of (XX.XXXX, XX.XXXX)
28 jul 04:31:12: Getting map of (XX.XXXX, XX.XXXX)
28 jul 04:31:12: Pausing to catch pokemon...
28 jul 04:31:13: Resuming walk.
28 jul 04:31:14: Pausing to catch pokemon...
28 jul 04:31:15: Resuming walk.
28 jul 04:31:15: Pausing to catch pokemon...
28 jul 04:31:17: Resuming walk.
28 jul 04:31:17: Pausing to catch pokemon...
28 jul 04:31:17: Getting map of (XX.XXXX, XX.XXXX)
28 jul 04:31:20: Resuming walk.
28 jul 04:31:20: Pausing to catch pokemon...
28 jul 04:31:21: Resuming walk.
28 jul 04:31:22: Pausing to catch pokemon...
28 jul 04:31:22: Resuming walk.
28 jul 04:31:22: Pausing to catch pokemon...
28 jul 04:31:22: Getting map of (XX.XXXX, XX.XXXX)
28 jul 04:31:23: Resuming walk.
28 jul 04:31:23: Pausing to catch pokemon...
28 jul 04:31:25: Resuming walk.
28 jul 04:31:25: Pausing to catch pokemon...

The bot used it last Pokeball to catch the Spearow, after that the bot was pausing, and resuming the whole time, what caused to move the character really slowly, without any message that you don't have any Pokeballs.

After the bot got some Pokeball's again from a Pokestop, it didn't resumed the catching, but ignored the fact that it got Pokeballs again.

## **Steps to reproduce:**

1. Have no Pokeballs.
2. Let the bot walk.

## **Expected behavior:**
Walk further at normal speed.
When arrived at a Pokestop, after looting, check if there are Pokeballs in the inventory, if yes: go catch Pokemon again.

## **Actual behavior:**
Bot has no Pokeballs anymore, moving at a slow speed because the bot pauses the whole time.
When the bot got Pokeballs, it still doesn't catch Pokemon.

## **Version:**
commit hash : 39fb4d6

## **Operating System:**
Windows 10 Pro 64-bit

## **Java version:**
    D:\>java -version
    java version "1.8.0_102"
    Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**Comment by Coldasicex** [comment]
until it's fixed you can change catch pokemons to "false" and set drop pokeballs to 100-150
then you change back catch to "true"

**Comment by wartickler** [comment]
Is there some bug reporting template on the site or is this just @kasagon being nice using that formatting?

**Comment by kasagon** [comment]
@Coldasicex I am using that right now. Hope they will fix this though.

@wartickler It is a standard template when you report a new issue. And I changed a little bit too the template how it looked even nicer.

**Comment by Agronis** [comment]
This is a good idea actually and I almost posted a new issue linking to here but we have enough duplicates.

So...

pause_if_empty : true/false
pause_time : inMinutes

- If user depletes inventory, put Pokemon hunting on hold.
- Farm only Pokestops for time of pause_time.
- Pokemon on do not discard list will be excluded from this concept.
- When pause_time expires - re-engage Pokemon hunting.
