### ISSUE TITLE
Is spawn radius in metres or km? 

### ISSUE THREAD

**Issue by Mewks** [jabbink/PokemonGoBot#564]
Couldn't find it anywhere...

Is spawn radius in metres or km? 

Thanks

**Comment by kasagon** [comment]
@Mewks , according to the config.properties file, it is in metres:
>  #Max distance from starting point the bot should ever go in meters

**Comment by langerhans** [comment]
Correct, the S2 lib measures stuff in meters.

**Comment by Mewks** [comment]
Didnt have those details in my config file, I am using the 0.5 release. Apologies.
