### ISSUE TITLE
All pokemon fleeing

### ISSUE THREAD

**Issue by mtchm** [jabbink/PokemonGoBot#565]
Anyone else encountering this problem?

**Comment by siimveskilt** [comment]
Means you are soft banned...have to wait.

**Comment by mtchm** [comment]
Guess I've been experimenting a bit too much :) thanks

**Comment by wartickler** [comment]
soft ban

**Comment by wudustan** [comment]
This problem occurs when you are teleporting too far. It's equivalent to you having traveled a ridiculous speed to get there. Try to stay local or leave a long gap between travelling long distances.

**Comment by langerhans** [comment]
Correct, you're softbanned, most likely due to moving too fast between large distances. You will also observe that pokestops give no rewards. Just wait a while.
