### ISSUE TITLE
[bug?] loot further away.

### ISSUE THREAD

**Issue by accident12123** [jabbink/PokemonGoBot#569]
It appears when it loots is about half the distance that you can actually loot a pokestop in real life

A config option for how far away to attempt to loot might be useful if needed to adjust in the future.

**Comment by TunnelSnakesThatsus** [comment]
is the bot working for u rn??

**Comment by Rick058** [comment]
@TunnelSnakesThatsus The bot with a PTC account works fine, Google accounts don't work though.

**Comment by langerhans** [comment]
Don't think that's a bug. But where is the issue really? I mean what are those few meters? I don't really see the advantage in being able to loot from further away, probably marginal speed improvement.

**Comment by jabbink** [comment]
You sure the real life distance is 60 meters?

**Comment by langerhans** [comment]
Clsoing for inactivity.
