### ISSUE TITLE
GoogleLogin:null

### ISSUE THREAD

**Issue by michaeldajnowicz** [jabbink/PokemonGoBot#572]
java -jar pogo.scraper-all-0.4.2.jar
[33m28 Jul 12:41:41: Display Keepalive Coordinates setting ("display_keepalive") not specified, defaulting to "true". [0m
Logging in to game server...
D/GoogleLogin: Get user to go to:null and enter code:null

0.4.2

**Comment by TunnelSnakesThatsus** [comment]
happening to everyone im pretty sure

**Comment by casper-gh** [comment]
same here, I was about the post lol

**Comment by michaeldajnowicz** [comment]
oh, yeah last night I had closed it and re-opened the script to see that so I just tried it back in the morning same thing. guess i'm not the only one

**Comment by pvase666** [comment]
Same, it's not server issues.

**Comment by michaeldajnowicz** [comment]
pretty sure it would work for people that still had the bot on without ever closing after the issue had started.

**Comment by TunnelSnakesThatsus** [comment]
I think so too @michaeldajnowicz im just waiting for @jabbink or @karael to update

**Comment by langerhans** [comment]
#545 Folks. There it's a link now, you can click it, saved you from using the search function...
