### ISSUE TITLE
[possible bug] Getting "go to: null and enter code:null" error.

### ISSUE THREAD

**Issue by superkilerpokemon** [jabbink/PokemonGoBot#576]
Hello, 

I tried using the bot again but I keep getting this message. Both on 0.4.3 and 0.5 Alpha.
I already checked if the servers are up.

**Comment by langerhans** [comment]
![image](https://cloud.githubusercontent.com/assets/5160000/17222488/df8087ba-54f8-11e6-9491-412fa481456f.png)


#545

**Comment by superkilerpokemon** [comment]
im sorry :(
