### ISSUE TITLE
GoogleCredentialProvider error

### ISSUE THREAD

**Issue by d0tamon** [jabbink/PokemonGoBot#579]
**Description:**
Everytime it run the bot, it does not provide with me the code that I have to put on www.google.com/device but instead provides me with:

D/GoogleCredentialProvider: 0
D/GoogleCredentialProvider: Get user to go to:null and enter code:null

this is right after I put: java -jar pogo.scraper-all-0.4.3.jar

Version: 0.4.3
OS: Windows 10 64-bit

I am not good at running bots with command prompt so please help me out here

**Comment by slundi** [comment]
Me too
It was working but know I got this message :(

**Comment by langerhans** [comment]
#545 #558 

![image](https://cloud.githubusercontent.com/assets/5160000/17223119/84080ca2-54fb-11e6-9d60-fb4a9ae36a9f.png)
