### ISSUE TITLE
Not dropping Razz Berries, inventory full

### ISSUE THREAD

**Issue by CptJackieSparrow** [jabbink/PokemonGoBot#58]
I've logged in to my account after it's saying inventory full.
There was 370 razz berries, while inventory limit is 350.
Can we drop em too?

**Comment by VoxelBirthday** [comment]
If I remember reading somewhere correctly, I'm pretty sure there's a feature that will either soon be released, or has been. 
try adding
  "item_razz_berry=(max number you want of the berries)"

without quotations to the config.properties. 
I just tested and it gave no error but I'm not sure if it's working.

**Comment by CptJackieSparrow** [comment]
updated, works fine now :) sorry for cluster

**Comment by leontada** [comment]
Yeah, there's an old pull request with this option the coder will be sending another pull maybe mater today.

**Comment by jabbink** [comment]
If you set `drop_items=true` it should drop all razz berries, except 50; can you confirm this?
