### ISSUE TITLE
Go to: null and insert code: null

### ISSUE THREAD

**Issue by BetterCallPaul17** [jabbink/PokemonGoBot#580]
**Description:**
It fails to provide the code to input into google.com/device

```
C:\Users\PavelCrime\Desktop\PoGoBot>java -jar pogo.scraper-all-0.4.3.jar
28 lug 19:43:03: Logging in to game server...
D/GoogleCredentialProvider: 0
D/GoogleCredentialProvider: Get user to go to:null and enter code:null
```

**Steps to reproduce:**

1. Set up the config files
2. Try to login

**Expected behavior:**
Give out the code to input on google.com/device

**Actual behavior:**
It print out a null value

**Stacktrace (If it's a crash):**
Not a crash

**Version:**
Tried with 0.4.3 and 0.5.0

**Operating System:**
W7 64Bit

**Java version:**
[Full output of `java -version`]
1.8-102

**Comment by langerhans** [comment]
I'll be nice to you since you at least showed some effort in filling out the template (almost) fully.

This has been fixed and there have been about tree fiddy issues about it today. Just wait for the release :)

**Comment by BetterCallPaul17** [comment]
Sorry pal, I have checked some of the latest entries but I couldn't see anything realted.. My bad and thanks for understanding!
