### ISSUE TITLE
High Density Pokemon Zone - No Catch

### ISSUE THREAD

**Issue by Evuse** [jabbink/PokemonGoBot#584]
Hello, i'm running bot in time square, but i get a lot of "getting map" messages and really slow pokemon farming. Where am i wrong? Please help me.

28 Jul 20:06:07: Resuming walk.
28 Jul 20:06:09: Getting map of (40.759106451506746, -73.98435464629395)
28 Jul 20:06:14: Getting map of (40.7591229711902, -73.98433739447032)
28 Jul 20:06:19: Getting map of (40.75912154098255, -73.98425223844127)
28 Jul 20:06:24: Getting map of (40.759103096660475, -73.9842981229528)
28 Jul 20:06:29: Getting map of (40.75921006625485, -73.98416623207366)
28 Jul 20:06:34: Getting map of (40.759199852799235, -73.98416296901577)
28 Jul 20:06:34: Profile update: 3700 XP on LVL 3; 700/3000 (23.33%) to LVL 4 
28 Jul 20:06:34: XP gain: 2600 XP; Pokemon caught/transferred: 5/1; Items caught/dropped: 3/0;
Pokebank 6/250; Stardust 600; Inventory 43/350 
28 Jul 20:06:39: Getting map of (40.75922686129209, -73.98414694008441)
28 Jul 20:06:44: Getting map of (40.75917594263331, -73.98413979586581)
28 Jul 20:06:49: Getting map of (40.759251328066675, -73.98410591319778)
28 Jul 20:06:54: Getting map of (40.75926633360489, -73.98399384592913)
28 Jul 20:06:59: Getting map of (40.75922444565277, -73.98400427492405)
28 Jul 20:07:04: Getting map of (40.759283832212546, -73.98387600897834)
28 Jul 20:07:09: Getting map of (40.759278057495536, -73.98391381912258)
28 Jul 20:07:14: Getting map of (40.759306769710015, -73.98384511762633)
28 Jul 20:07:19: Getting map of (40.75930715543219, -73.98382431566262)
28 Jul 20:07:24: Getting map of (40.759341682956695, -73.98375441951954)
28 Jul 20:07:25: Looting nearby pokestop 051c88a1031a479d939587303aa263da.16
28 Jul 20:07:25: Looted pokestop 051c88a1031a479d939587303aa263da.16; +50 XP: [3xITEM_POKE_BALL] 
28 Jul 20:07:29: Getting map of (40.759366170408214, -73.98369352770086)
28 Jul 20:07:34: Getting map of (40.75934813791082, -73.98372852524659)
28 Jul 20:07:34: Profile update: 3750 XP on LVL 3; 750/3000 (25.00%) to LVL 4 
28 Jul 20:07:34: XP gain: 2650 XP; Pokemon caught/transferred: 5/1; Items caught/dropped: 6/0;
Pokebank 6/250; Stardust 600; Inventory 46/350 
28 Jul 20:07:39: Getting map of (40.759384712349856, -73.98366494452593)
28 Jul 20:07:44: Getting map of (40.7594060193864, -73.98364057129807)
28 Jul 20:07:49: Getting map of (40.7594330580085, -73.98358720830223)
28 Jul 20:07:54: Getting map of (40.75937542316843, -73.98357114663196)
28 Jul 20:07:59: Getting map of (40.75941371439184, -73.98350921155506)

**Comment by rirze** [comment]
Try looking at the pokevision map for the [area](https://pokevision.com/#/@40.75941371439184, -73.98350921155506). It doesn't seem like there's a super high density of pokemon around where the bot is. Just give it some time to move around.

**Comment by Evuse** [comment]
ok, i was guessing time square was the higher in the world. Any suggestion? Thanks

**Comment by rirze** [comment]
Just look around NYC (Central Park is always a good spot), try using tools like pokevision first before starting your bot. 

If there's nothing else, I would recommend closing this issue since it's not a technical problem.

**Comment by Evuse** [comment]
sure. i will, thanks

**Comment by MASSV** [comment]
try santa monica pier, always has 10+ lured stops and great selection of pokes, almost all rarer ones 34.008468, -118.498298
