### ISSUE TITLE
[Question] What are the known bugs in the latest develop build?

### ISSUE THREAD

**Issue by omar972** [jabbink/PokemonGoBot#586]
I'm Currently on commit ba305eb5fc740abdfeede7535eb684d47d2dbb82 and I'm hesitant to update to an Alpha build, so what should I expect if I were to update.

**Comment by rirze** [comment]
#582 
#583 might be because of token/2-factor auth methods

If you use a PTC account, you'll be fine (don't worry about the issues above).

**Comment by omar972** [comment]
Using google account and using 2-factor, guess I'll wait lol.
