### ISSUE TITLE
FAIL TO DROP ERROR

### ISSUE THREAD

**Issue by tyman1292** [jabbink/PokemonGoBot#587]
**Description:**
This has been happening.. just reporting have not seen a report.

This error is basicly spammed in the log:
Fail to Drop 1x ITEM_POTION:ERROR_NOT_ENOUGH_COPIES

**Steps to reproduce:**
1. Run bot.

**Version:**
5.0A prebuilt

**Operating System:**
win 7

**Java version:**
1.8.0_91

**Comment by langerhans** [comment]
Is this fixed after a restart of the bot?

**Comment by tyman1292** [comment]
not sure yet. ill test it.

**Comment by EyesReye** [comment]
No, and it also now says Failed To Transfer
