### ISSUE TITLE
Google Login Code 'null'

### ISSUE THREAD

**Issue by matty9090** [jabbink/PokemonGoBot#588]
**Description:**
Starting the bot as usual but this time the console outputs: "D/GoogleCredentialProvider: Get user to go to:null and enter code:null"

**Steps to reproduce:**

1. Username and password entered in config (no token, using google)
2. Start the bot

**Expected behavior:**
Shows url for google device and a code to be entered

**Actual behavior:**
URL for google device and code to be entered are both 'null'

**Version:**
0.4,3

**Operating System:**
Windows 10

**Java version:**
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by chandler14362** [comment]
Download version 0.5.0 alpha 2, it contains the fix for this issue.

**Comment by SSminowjohnson** [comment]
Can't use 0.5.0 alpha due to #582 :(

**Comment by matty9090** [comment]
Thanks, 0.5.0 alpha 2 does fix it, I've not run into #582  yet though

**Comment by nekolasin** [comment]
not work for my

**Comment by tayjaf** [comment]
#582 is effecting 0.5.0a2 for me.
