### ISSUE TITLE
Catching too quickly

### ISSUE THREAD

**Issue by wartickler** [jabbink/PokemonGoBot#59]
In the middle of Central Park and catching like mad! I would think that from their side they would see how quickly I am catching. If I was on the client I would have to wait a(n interminably) long while between catches. I would suggest a timer that pauses at least as long as the client between being able to capture. It could still move as I would still be walking through the park while I'm fiddling with the screen on a capture (but I wouldn't be hitting pokestops either...)

**Comment by leontada** [comment]
This is legit question. I tought about it yesterday when looking at my Journal, I had 4 pokemon caches in the same minute (timestamp).

**Comment by Kissy** [comment]
It seems to always catch without miss throw, which is almost impossible for a human ;)

**Comment by jabbink** [comment]
You are right, since I ran this I only saw it fail a throw once in 400 catches.

Also on the official app with all lags, and animations it takes about ~45 seconds to catch.

Will leave this open for others to discuss how to properly fix this (and what limits should be set).

**Comment by wartickler** [comment]
I'd guess we need to time how long it takes to do most actions. Also it might be good to set a random amount in between actions so that you aren't doing the same action in the same amount of time. That would be easy to discover in a database query.

**Comment by daveystruijk** [comment]
I agree, though the issue already lies in the [PokeGOAPI-Java](https://github.com/Grover-c13/PokeGOAPI-Java/blob/master/src/main/java/com/pokegoapi/api/map/pokemon/CatchablePokemon.java#L190), which sends an unrealistic amount of pokeball-throw requests within a few seconds. Maybe we can change that API to add certain delays.

**Comment by Dr4mEdo** [comment]
I agree, IMO, it should takes 30sec to catch a pokemon and 15 sec to spin a pokestop and 20 sec between exchange

**Comment by jabbink** [comment]
@daveystruijk 
>I agree, though the issue already lies in the PokeGOAPI-Java, which sends an unrealistic amount of pokeball-throw requests within a few seconds. Maybe we can change that API to add certain delays.

The catchPokemon method is called with `amount=-1` but in practice it will only try once, because it either gets the Pokemon (stop) or the pokemon escapes the ball, or flees, in which case it also stops.

The current `do/while` loop in the Java API is useless.

**Comment by CptJackieSparrow** [comment]
There could be an option in config file to toggle it.
but that'll decrease farming like 40 times?
i'd keep it closed, but it'll be nice to have that option for main accounts
(which i've already passed my main account i've been playing for 1 week in 24 hours with the bot)

**Comment by jabbink** [comment]
>15 sec to spin a pokestop

legit pokestop is <1 second as that animation is abortable (try it, click pokestop, spin it, click cancel, you get the items and xp)

**Comment by Lupinus** [comment]
The timeouts should not be hardcoded. This could all be part of some "anti-cheat-detection" settings. Things that need to be configurable.

* Pokeball miss chance
* Timouts between each action (looting Pokestop, throwing ball after encounter, wait after ball is thrown, etc.)
* Walking accuracy. After the next path has been set, the bot should distort it's path a bit. Walking speed could also vary.

Just a few suggestions. All these issues should be merge into one that deals with integrating human like behavior.

**Comment by wartickler** [comment]
I agree that hardcoded times wouldn't be safe. I keep trying to wrap my head around the parameters i would give to a Random() function. We need a random function for lots of things like missed throws, time for spinning pokestops, walking speed, etc.  Whether main account or bot account we don't want to attract attention.

**Comment by jabbink** [comment]
>Pokeball miss chance

Is built in now (well, it will never miss, but you can specify your desired catch probability which it will try to match as close as possible)

**Comment by accident12123** [comment]
I would include how fast a transfer happens as part of this also.   It just seems impossible for a person to achieve that speed.

**Comment by jabbink** [comment]
Lots of "human" randomization stuff has been added. Closing.
