### ISSUE TITLE
Can't find symbol Error 

### ISSUE THREAD

**Issue by rngrofl** [jabbink/PokemonGoBot#591]
**Description:**

Information: Compilation completed with 100 errors and 100 warnings in 13s 
Can't find symbol. 

C:\GIT\PokemonGoBot\lib\PokeGOAPI-Java\src\main\java\com\pokegoapi\api\map\pokemon\CatchResult.java
Error:(36, 17) java: cannot find symbol
  symbol:   method setFailed(boolean)
  location: class com.pokegoapi.api.map.pokemon.CatchResult
C:\GIT\PokemonGoBot\lib\PokeGOAPI-Java\src\main\java\com\pokegoapi\api\map\MapObjects.java
Error:(173, 40) java: cannot find symbol
  symbol:   method getNearbyPokemons()
  location: variable other of type com.pokegoapi.api.map.MapObjects
Error:(176, 43) java: cannot find symbol
  symbol:   method getCatchablePokemons()
  location: variable other of type com.pokegoapi.api.map.MapObjects
Error:(179, 38) java: cannot find symbol
  symbol:   method getWildPokemons()
  location: variable other of type com.pokegoapi.api.map.MapObjects

**Steps to reproduce:**

1.Intellij already installed lombok.
2. Followed the steps in readme.
3. Works fine to run from command line 
4. Can't run from Intellij. 

**Operating System:**
Windows 7

**Java version:**
java 8

**Comment by langerhans** [comment]
Install the Lombok plugin in IntelliJ and see if that fixes it.

**Comment by rngrofl** [comment]
already  installed

**Comment by langerhans** [comment]
Try refreshing the Gradle build by clicking the little refresh icon in the Gradle tool window in IntelliJ and then running a gradle task from the Gradle tool window with type `clean build`.

**Comment by rngrofl** [comment]
This works, Thanks a bunch.

Looks like the community edition  don't have the Gradle tool window. I had to switch to Ultimate edition.
