### ISSUE TITLE
Run Failed

### ISSUE THREAD

**Issue by MichaelWestergaard** [jabbink/PokemonGoBot#592]
~/PokemonGoBot# ./gradlew run --stacktrace
:PokeGOAPI-Java:extractIncludeProto UP-TO-DATE
:PokeGOAPI-Java:extractProto UP-TO-DATE
:PokeGOAPI-Java:generateProto UP-TO-DATE
:PokeGOAPI-Java:compileJava UP-TO-DATE
:PokeGOAPI-Java:processResources UP-TO-DATE
:PokeGOAPI-Java:classes UP-TO-DATE
:PokeGOAPI-Java:jar UP-TO-DATE
:compileKotlin UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
28 Jul 16:18:12: Logging in to game server...
28 Jul 16:18:13: Server refused your login credentials. Are they correct?
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
[http://pastebin.com/CEqQitdF](http://pastebin.com/CEqQitdF)

**Comment by langerhans** [comment]
See #583
