### ISSUE TITLE
Alpha 2 crash

### ISSUE THREAD

**Issue by cwliias** [jabbink/PokemonGoBot#595]
**Description:**
http://imgur.com/9cjlT3O

**Steps to reproduce:**

1. install alpha 2
2. Run Alpha 2

**Expected**
Launch

**Actual**
Crash

**Stacktrace (If it's a crash):**

http://imgur.com/9cjlT3O

**Version:**
.5 alpha 2

**Operating System:**
win 10

**Java version:**
[Full output of `java -version`]

**Comment by d0tamon** [comment]
#582

**Comment by cwliias** [comment]
@d0tamon is there a fix for this yet?

**Comment by d0tamon** [comment]
None that I know of mate

**Comment by cwliias** [comment]
Thanks bruv

**Comment by cwliias** [comment]
Back to .5!

**Comment by d0tamon** [comment]
Any version for me isn't working though, same errors across all versions and all different bots as well. Weird
