### ISSUE TITLE
BotLoop / WalkingLoop - Contents of buffer are null

### ISSUE THREAD

**Issue by wudustan** [jabbink/PokemonGoBot#597]
**Description:**
BotLoop / WalkingLoop - Contents of buffer are null

**Steps to reproduce:**

1. Run java -jar or 0.5.0 alpha 2
2. It happens

**Version:**
Release 0.5.0 alpha 2

`http://pastebin.com/iM3siq9q`

**Comment by langerhans** [comment]
Servers are overloaded/not responding. Keep trying.
