### ISSUE TITLE
Walkingloop

### ISSUE THREAD

**Issue by Spiritwolf213** [jabbink/PokemonGoBot#598]
**Description:**
Error running loop walkingloop

**Steps to reproduce:**

1. started up the bot
2. getting error after a couple of secs

**Expected behavior:**
reaching destination/getting map

**Actual behavior:**
error running loop walkingloop destination not reached

**Version:**
0.5.0alpha2.

(restarting the bot did not work since ive done it a couple of times already)

**Comment by langerhans** [comment]
See other issues... Servers are not working correctly at the moment.

**Comment by wudustan** [comment]
Thanks
