### ISSUE TITLE
[Question] Does this mean log in/server is down?

### ISSUE THREAD

**Issue by cwliias** [jabbink/PokemonGoBot#600]
> 28 Jul 14:40:57: Logging in to game server...
> D/GoogleCredentialProvider: 0
> D/GoogleCredentialProvider: Get user to go to:null and enter code:null

**Comment by langerhans** [comment]
This means you didn#t search the existing issues for the same error ;)

In short no, update the bot.

**Comment by cwliias** [comment]
XD i did, I thought going back to a stable build would still work, Guess not :(.

**Comment by d0tamon** [comment]
Tried and failed as well. Hoping this gets fixed because I need that Charizard

**Comment by cwliias** [comment]
I was surprised v0.4.3 didn't work/stopped working.

**Comment by Rick058** [comment]
4.3 doesn't work anymore with Google accounts, with a PTC account it still does function for me though.
Update to v0.5.0 alpha 2, works completely fine for me with a Google account.

**Comment by d0tamon** [comment]
I think after Niantic servers bailed in the morning, the bot stopped working

**Comment by cwliias** [comment]
@Rick058 how do you get past the flood?
