### ISSUE TITLE
Weird

### ISSUE THREAD

**Issue by megatixos** [jabbink/PokemonGoBot#601]
Log keep sending: Error running loop walkingloop, profileloop and many others.. but the bot works fine.. (i mean it catches pokemon, pokestops etc..) so why is it spamming so much these errors? i am using the latest developer.. in another issue jabbink stated its not bots fault but servers are bad.. but this time: http://ispokemongodownornot.com/ says everything is okay.. so is it still pokemons go servers or the bot problem?

**Comment by langerhans** [comment]
Servers are still flaky. Give it a bit to catch up again. Still not a bot issue really. That site is also not the enf of the truth ;)
