### ISSUE TITLE
Current develop build not working for me.

### ISSUE THREAD

**Issue by omar972** [jabbink/PokemonGoBot#602]
**Description:**

In case it's relevant, using google login and 2 step authorization is activated.

**Steps to reproduce:**

Run Bot

**Expected behavior:**
Bot works

**Actual behavior:**
Bot outputs: http://pastebin.com/GHSiTF7r then stops

**Stacktrace (If it's a crash):**
http://pastebin.com/Dt7TxELn

**Version:**
commit 61dc63f6289daf5f2dde80afb435c610017c99fa

**Operating System:**
Windows 8.1
**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) Client VM (build 25.101-b13, mixed mode, sharing)

**Comment by omar972** [comment]
I tried to run again, says "Server refused your login credentials. Are they correct?". I'm 100% sure they are correct, I actually copied the config from an older build that works and it refuses it. Referring to #583

**Comment by SiriusCrypto** [comment]
same here
