### ISSUE TITLE
GoogleCredentialProvider: Get user to go to:null and enter code:null

### ISSUE THREAD

**Issue by Leo3dprinter** [jabbink/PokemonGoBot#603]
On Prompt

C:\Users\User\Desktop\Bot>java -jar pogo.scraper-all-0.4.3.jar
28 Jul 14:59:13: Logging in to game server...
D/GoogleCredentialProvider: 0
D/GoogleCredentialProvider: Get user to go to:null and enter code:null

Any Idea how to solve this?

Pokemon Go Bot v0.4.3

**Comment by MyUncleSam** [comment]
see #600
