### ISSUE TITLE
How to use PTC?

### ISSUE THREAD

**Issue by Leo3dprinter** [jabbink/PokemonGoBot#605]
Im not really good with all these computer thingy.

I cant set up 5 alpha cuss is too much for my little computer knowledge.

How do I log using PTC?

**Comment by megatixos** [comment]
edit config.properties with notepad,
complete the fields as you want
(notice first field to complete is ur PTC username)
save notepad

**Comment by Leo3dprinter** [comment]
and what would be PTC exactly?
is that pokemon trainer club info?
Can you give an example of the info there?

**Comment by husbeard** [comment]
PTC is Pokemon Trainer Club - it's the account you use to log in that isn't Google.

Example:
username=thisguyiscool
password=botezlifezerocool

**Comment by Rofii** [comment]
"Im not really good with all these computer thingy."

-Someone on Github, 2016

**Comment by husbeard** [comment]
Hey, we all gotta start somewhere. I'm terrible at programming, but I'm boss at Cisco Networking and Computer Repair stuff.

**Comment by Agronis** [comment]
@husbeard 

Posting issues on the repository of the development of any project asking general questions isn't appropriate.

@Leo3dprinter 

# Please close this issue.

**Comment by husbeard** [comment]
True, just point him to the appropriate place to ask questions then.

**Comment by Rofii** [comment]
It's true that questions like this don't belong in the issues section of Github but it's also true that there is currently no better place to ask these questions ever since the Reddit thread was deleted. 

Perhaps we should begin working on the wiki and using it as a more friendly Readme.md or even better have a forum somewhere?

**Comment by langerhans** [comment]
You can get quick support like this on the Slack.
