### ISSUE TITLE
Google Token Issue

### ISSUE THREAD

**Issue by KyleBoyer** [jabbink/PokemonGoBot#606]
I just recently changed my Google Password, and now the token isn't working, thus I removed it from the config file. Now after that, the log(below) is what I get, and you can see that it is trying to authenticate based on the static token that is not set.

28 Jul 17:18:20: Logging in to game server...
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
28 Jul 17:18:22: Server returned unexpected error

**Comment by LOLwhat123** [comment]
same problem, servers are working perfectly fine atm

**Comment by accident12123** [comment]
same error trying but trying to use PTC

**Comment by Leo3dprinter** [comment]
how do you use PTC? I dont get it?

**Comment by MrLuisArano** [comment]
same error, same issue happening with 0.4.7

**Comment by KyleBoyer** [comment]
> how do you use PTC? I dont get it?

Pokemon Trainer Club is used by signing up without a gmail account, then instead of entering your gmail email address for the username in the config, you enter that information.

**Comment by KyleBoyer** [comment]
> same error, same issue happening with 0.4.7

I'm having the issue also with that one.

**Comment by accident12123** [comment]
issue 608 might actually be the root cause here and it's a soft ban.

**Comment by LOLwhat123** [comment]
both my accounts work perfectly fine on the phone so not soft banned

**Comment by alexpw** [comment]
This is not cause by auth for either Google/PTC.

If you are seeing the exact output that @KyleBoyer posted, as I was, then printing the exception that caused the "unexpected error", will point you to the underlying PokeGOAPI-Java api, specifically, https://github.com/Grover-c13/PokeGOAPI-Java/issues/327 as well as https://github.com/jabbink/PokemonGoBot/issues/608.

**Comment by TunnelSnakesThatsus** [comment]
so atm there is no fix??

**Comment by RaeneDev** [comment]
you can fix it yourself @TunnelSnakesThatsus :') I was messing around a bit and partially got it working.

**Comment by husbeard** [comment]
@TunnelSnakesThatsus - Right, there is no official fix yet.

**Comment by langerhans** [comment]
This should in theory be fixed in v0.5.0-alpha3
