### ISSUE TITLE
[SOLVED]WalkingLoop

### ISSUE THREAD

**Issue by Oliky** [jabbink/PokemonGoBot#607]
Everytime i start the bot i get instant an Error Msg .

The Bot is catching Pokemon and farming Stops . But very rarely . So i got a Pokemon every 3 min .

> 29 Jul 00:26:55: Error running loop WalkingLoop!
> com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
>         at com.pokegoapi.api.map.Map.getMapObjects(Map.java:307)
>         at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
>         at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
>         at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
>         at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
>         at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
>         at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:88)
>         at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:21)
>         at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
>         at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
>         at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
> Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
>         at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
>         at com.pokegoapi.api.map.Map.getMapObjects(Map.java:305)

Running version pogo.scraper-all-0.5.0-alpha2 on Windows 10
 **I get fixed it by downloading the newest Java Update !**

**Comment by kasagon** [comment]
@Oliky What Java version do you have?
Can you use the command "Java -version" in CMD.exe and provide us with the response you get?

**Comment by johnkingzton** [comment]
Issue wasn't fixed for me even with java update.

**Comment by izecell** [comment]
For me 0.4.3 is running without loop errors.
0.5.0 alpha & 0.5.0 alpha2 having the bot loop / walk loop error.
Updating any sort of component wasn't solving the issue.

**Comment by Agronis** [comment]
Those of you still with problem - are you running it from source code or from the Jar release?

Otherwise please list environment factors.

**Comment by pvase666** [comment]
Windows 10 64bit
Running from JAR file.
Latest JAVA JDK.

I got same error.

**Comment by kelvinblade** [comment]
0.5.0-alpha running from source code
WalkingLoop and BotLoop constantly
It was fine working yesterday

**Comment by Oliky** [comment]
Starting from .jar .
Getting also the loops but much less then before the update . Maybe it was only a server problem

**Comment by kelvinblade** [comment]
Using 0.4.3 from jar, much less than 0.5.0-alpha.
No walkingLoop. Only BotLoop and ProfileLoop but usable.
Also tried updating java.

**Comment by muschter** [comment]
If it is fixed, please close your issue. Thanks.

**Comment by cglatot** [comment]
I'm getting this error, but I have the latest Java version (1.8.0_101-b13) running the jar from 0.5.0-alpha 2.

**Comment by langerhans** [comment]
![image](https://cloud.githubusercontent.com/assets/5160000/17256343/712dbccc-55bd-11e6-8350-421a34184f46.png)
