### ISSUE TITLE
Use com.pokegoapi.api.map.* to know nearby pokemon and setup a priority system

### ISSUE THREAD

**Issue by pr0ves** [jabbink/PokemonGoBot#61]
There are live maps that use the pokegoapi to know the exact position of the pokemons and create a map.
We could use it to check nearby pokemons and also create a priority system, most likely another list, where if there's a pokemon nearby that is in that list, the bot will try to catch that one first and then resume the previous task.

**Comment by jabbink** [comment]
Is the `distance` for `NearbyPokemon` fixed already, or still statically `200m`? If so, those could easily be triangulated.

Also for the MapPokemon and WildPokemon a priority queue should still be made. Good point :+1:

**Comment by pr0ves** [comment]
Even if they fix it, to triangulate it the bot should teleport in 3 different points that are pretty far from one another; so I don't think we can add this feature right now.
Anyway I saw in another program, pokemongoMITM or something, that it managed to add the distance and also the direction like N,NE. Maybe that could be added to the api

**Comment by jabbink** [comment]
"NearbyPokemon" have no distance whatsoever anymore...
