### ISSUE TITLE
[Suggestion] Lower requests to 3/sec

### ISSUE THREAD

**Issue by cwliias** [jabbink/PokemonGoBot#610]
So it works. Kappa

**Comment by Letrico** [comment]
did you modify the source?

**Comment by bjodasso** [comment]
noone has pointed us to where to modify it.

**Comment by xenxes** [comment]
someone is working on a mod to the dependent pokemongoapi https://github.com/Grover-c13/PokeGOAPI-Java/issues/327

**Comment by Agronis** [comment]
[Real hotfix waiting for merge into PokoGOAPI](https://github.com/Grover-c13/PokeGOAPI-Java/pull/328).

**Comment by celsian** [comment]
@Agronis Did you update your submodule and try the bot? It's still non-functional.
