### ISSUE TITLE
Logging in to game server... D/GoogleCredentialProvider: 0 D/GoogleCredentialProvider: Get user to go to:null and enter code:null

### ISSUE THREAD

**Issue by johnkingzton** [jabbink/PokemonGoBot#611]
28 Jul 16:01:33: Logging in to game server...
D/GoogleCredentialProvider: 0
D/GoogleCredentialProvider: Get user to go to:null and enter code:null

I get this error even though ive filled out the config file properely
https://s31.postimg.org/72c9ylf4b/Untitled.png

**Comment by johnkingzton** [comment]
<img id="main-image" src="https://s31.postimg.org/72c9ylf4b/Untitled.png" style="display: block; width: 100%; max-width: 1280px; cursor: zoom-in;" data-full="//s31.postimg.org/6cthm8ekp/Untitled.png" data-width="1366" data-height="768" class="zoom">

**Comment by cwliias** [comment]
close  it #608
