### ISSUE TITLE
0.4.3 Server returned unexpected error. How can I fix this?

### ISSUE THREAD

**Issue by hdubb** [jabbink/PokemonGoBot#613]
28 Jul 17:25:00: Logging in to game server...
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
28 Jul 17:25:01: Server returned unexpected error
28 Jul 17:25:01: Retrying...
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
28 Jul 17:25:02: Server returned unexpected error
28 Jul 17:25:02: Retrying...
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
28 Jul 17:25:06: Server returned unexpected error
28 Jul 17:25:06: Retrying...
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
28 Jul 17:25:08: Server returned unexpected error
28 Jul 17:25:08: Failed to login. Stopping

**Comment by Agronis** [comment]
Close this ticket and use the search bar.

![SEARCH](https://cdn.meme.am/instances/400x/15488778.jpg)

**Comment by hdubb** [comment]
/r/iamverysmart
