### ISSUE TITLE
Ptc login issue: Server returned unexpected error

### ISSUE THREAD

**Issue by wgleiuni** [jabbink/PokemonGoBot#616]
**Description:**
28 Jul 18:48:13: Logging in to game server...
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
28 Jul 18:48:15: Server returned unexpected error
28 Jul 18:48:15: Retrying...
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
28 Jul 18:48:16: Server returned unexpected error
28 Jul 18:48:16: Retrying...
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
28 Jul 18:48:18: Server returned unexpected error
28 Jul 18:48:18: Retrying...
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
28 Jul 18:48:19: Server returned unexpected error
28 Jul 18:48:19: Failed to login. Stopping
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Steps to reproduce:**

1.  Mac
2. after gradle run

**Expected behavior:**
login successfully

**Actual behavior:**
Failed to login

**Version:**
git from Source

**Operating System:**
Mac

**Java version:**
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**Comment by TunnelSnakesThatsus** [comment]
same for me what the hell is going on!

**Comment by wgleiuni** [comment]
My username and password are already in config.properties, but I leave "token=" empty.

**Comment by TunnelSnakesThatsus** [comment]
same

**Comment by Emuuung** [comment]
Please close this issue as it is a duplicate.

**Comment by Rick058** [comment]
Have the same issues on the latest build with my Google account and also PTC, however PTC actually works (on Windows) but it is very buggy and not the best xp/hour on 4.3. I am still using build 4.3 as the latest 5 does not function at all with the current issues. Try 4.3? All I can suggest as it seem to work for me.

**Comment by TunnelSnakesThatsus** [comment]
@Rick058 It wont work itll tell me that token is null how is urs working?!?!?

**Comment by Rick058** [comment]
@TunnelSnakesThatsus 

> however **PTC** actually works

That's because I use a PTC account on 4.3, not a Google account. Google gives me null:null as well on 4.3 and doesn't work at all on 5.

If you only have a Google account I guess the best is to wait for a solution/bot update. None of the bots are currently working, neither from other creators.

**Comment by Agronis** [comment]
@wgleiuni 

# Please close this issue.

# Use search function.
