### ISSUE TITLE
Cant build #599

### ISSUE THREAD

**Issue by Scoboose** [jabbink/PokemonGoBot#618]
**Description:**
Build finishing successfully but with many errors and I can not run the bot.

**Steps to reproduce:**

Clone repo: git clone https://github.com/jabbink/PokemonGoBot.git && cd PokemonGoBot
Run git submodule update --init --recursive
Run from cmd: gradlew build
Rename ./config.properties.template to ./config.properties
Modify config.properties
run: gradlew run

**Expected behavior:**
Build correctly

**Actual behavior:**
http://pastebin.com/Wqkq4aYu

**Version:**
#599

**Operating System:**
windows 10

**Java version:**
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**Comment by RaeneDev** [comment]
Known issue atm that needs to be resolved. Seems API was limited to 3 server requests per second and the bot is trying to request more?(Someone correct me if I am wrong.)

**Comment by iamthasasquatch** [comment]
you are correct. They will have to add a Thread.sleep(300); to pretty much every function from my understanding. the api is updated with this hotfix so now you can actually get logged in but soon as the bot uses another function it will start spamming request and be blocked out

**Comment by Emuuung** [comment]
Please close this issue, it is a know issue that needs a lot of work.

**Comment by celsian** [comment]
> the api is updated with this hotfix so now you can actually get logged in but soon as the bot uses another function it will start spamming request and be blocked out

@iamthasasquatch Thast's strange, "28 Jul 20:56:02: Server returned unexpected error" and finally errors out with "28 Jul 20:56:07: Failed to login. Stopping" As such I cannot login. I have better luck with the latest release, but of course that errors out because of the thread request limitation. Is this what you're experiencing as well?

**Comment by langerhans** [comment]
Closing as duplicate, a fix will be worked on.

**Comment by Scoboose** [comment]
Should this be fixed in alpha 3?  I still can not build.

**Comment by langerhans** [comment]
Why, your log even says the build is successful?
