### ISSUE TITLE
[Request] First login settings

### ISSUE THREAD

**Issue by bolds07** [jabbink/PokemonGoBot#620]
Are there any way to deal with the first login settings programatically?
I mean, select skin color, clothes, name, and check that first agreement

If I create a new account, the bot doesn't see any pokestop or catchable pokemon until I go manually throught this first settings

Probably this is not on the roadmap of the API if someone can give me a tip about how to decript the packages and figure by myself the protocol I would be very glad

**Comment by Simpuhl** [comment]
Dude, takes like 5 mins to go through this shit or it would take a programmer like a day to figure it all out. Stop being lazy

**Comment by Rishabhpatted24** [comment]
Simpuhl , but 5 min to do it ..and then wait a few hours so thtat u can run bot on a different location..^ u know what i mean??

**Comment by RaeneDev** [comment]
Dirty & Ugly way; Autohotkey c; but @Simpuhl is kinda right... I can create like 6 accounts or so in 5 minutes. Autohotkey; maybe... 5 or 6 in a minute?

**Comment by langerhans** [comment]
>If I create a new account, the bot doesn't see any pokestop or catchable pokemon until I go manually throught this first settings

I don't have this issue. I have two test accounts that were never logged into from the app. Keeping this open as feature request. If someone wants to work on it go ahead. Not even sure if the api lib supports that yet.

**Comment by Emuuung** [comment]
The API doesn't support any of those, these actions are listed in the [API documentation](https://docs.google.com/spreadsheets/d/1Xv0Gw5PzIRaVou2xrl6r7qySrcmOKjQWLBjJA73YnJM/edit#gid=0) but are tagged as "Not planned" to develop.

So if anyone wanna add this feature I suggest you work it on the API github.

**Comment by bolds07** [comment]
@Simpuhl, if you dont want to help at least be smart, i created 60 accounts on pokemon page in 10 minutes yesterday and it didn't take one day to figure out, its three or four requests i'm tottaly sure the point is i cant understand the packages i sniff, and there some people who already are used to.

@langerhans are you sure you never loged? well, yesterday i created those accounts on PTC and they don't see any pokestop or pokemon

**Comment by langerhans** [comment]
That might just be the general problems we see right now. 100% sure I never logged in on the phone with either of those two accounts.

**Comment by bolds07** [comment]
I've tested again and now is working without login on phone.
