### ISSUE TITLE
Unexpected error returned on Google login

### ISSUE THREAD

**Issue by smileytechguy** [jabbink/PokemonGoBot#621]
**Description:**
Unable to login, using application specific password.  The password is shown as successfully being used to login.

**Steps to reproduce:**

1. Download jar or compile, tried both
2. Run after making config.properties with plaintext password, blank token and blank b64 password

**Expected behavior:**
Run

**Actual behavior:**
Errors

**Stacktrace (If it's a crash):**
29 Jul 00:42:55: Logging in to game server...
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
29 Jul 00:42:58: Server returned unexpected error 
29 Jul 00:42:58: Retrying...
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
29 Jul 00:42:59: Server returned unexpected error 
29 Jul 00:42:59: Retrying...
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
29 Jul 00:43:01: Server returned unexpected error 
29 Jul 00:43:01: Retrying...
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
29 Jul 00:43:03: Server returned unexpected error 
29 Jul 00:43:03: Failed to login. Stopping 

**Version:**
Alpha 2 of latest release  bf7f343a4e935d6d16fed134c71de308040d25f5, pull request #599

**Operating System:**
OS X 10.11 with SIP disabled

**Java version:**
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**Comment by Min3CraftDud3** [comment]
Can confirm same issue on Windows 8
Java version 1.8.0_91
JRE 1.8.0_91-b15

**Comment by picopowerr** [comment]
Same issue here. 

I have 2 factor auth turned off, so that cannot be the problem.

**Comment by RaeneDev** [comment]
Please Read Previous issues to see if you have any of the same issues. I don't mean to seem rude; but there have been at least 10 of these issues posted. Short answer; wait for next update. It's due to  the game limiting packets sent per second and some other related issues.

**Comment by Min3CraftDud3** [comment]
@RaeneDev it also doesnt help that the dev is now selling the bot on their site and requiring the use of an auth token

**Comment by picopowerr** [comment]
@RaeneDev I didn't get the "Server refused your login credentials. Are they correct?" so I assumed it was a different issue.

**Comment by Skander1998** [comment]
@Min3CraftDud3 real? link?

**Comment by Min3CraftDud3** [comment]
@Skander1998 
https://mygobot.org/dashboard

**Comment by Min3CraftDud3** [comment]
Nvm im retarded different dev

**Comment by Skander1998** [comment]
That's what I thought :p Necro works for now, if you can't wait.

**Comment by Min3CraftDud3** [comment]
@Skander1998 I was looking at the MyGoBot which is also not working and they are now charging for it.

**Comment by RaeneDev** [comment]
@Min3CraftDud3 @Skand1998 Different Dev and also looks a bit... suspicious. :p

**Comment by Min3CraftDud3** [comment]
@RaeneDev which is why i removed other posts, Didn't what my stupid moment to confuse anyone else

**Comment by RaeneDev** [comment]
@picopowerr Recheck your config. I was noticing that it would delete my password randomly? o.O 
But I'm pretty sure mine was getting this issue as well.

**Comment by picopowerr** [comment]
@RaeneDev Checked it to be sure, password still in there.

**Comment by Emuuung** [comment]
Latest server patch is preventing the bot from running or making it mal-function, please close this thread as it it being worked on adn wait for a new fix, if the problem persist after the fix then open an issue with more info.

**Comment by smileytechguy** [comment]
Closing due to duplicate
