### ISSUE TITLE
Error while bot running.

### ISSUE THREAD

**Issue by Arihiza** [jabbink/PokemonGoBot#626]
Keep getting this popping up every minute. Should I be worried?

> 29 Jul 18:31:16: Error running loop BotLoop! 
> com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
> 	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:307)
> 	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
> 	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
> 	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
> 	at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
> 	at ink.abb.pogo.scraper.tasks.WalkToUnusedPokestop.run(WalkToUnusedPokestop.kt:24)
> 	at ink.abb.pogo.scraper.Bot.task(Bot.kt:163)
> 	at ink.abb.pogo.scraper.tasks.ProcessPokestops.run(ProcessPokestops.kt:44)
> 	at ink.abb.pogo.scraper.Bot.task(Bot.kt:163)
> 	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:115)
> 	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:30)
> 	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:128)
> 	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:30)
> 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
> Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
> 	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
> 	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:305)
> 	... 13 more
> 

**Version:**
0.4.3

**Operating System:**
Linux Mint

**Java version:**
1.8.0_91

**Comment by HoneyWheat** [comment]
This is a known issue. Please read older posts first.

**Comment by Arihiza** [comment]
Yeah but in other ones bot aint working. It is still running for me...

**Comment by 80rrego** [comment]
Yeah just happened the same to me, I used earlier in the day, and right now the boot keep working but every line pops that messages

**Comment by Emuuung** [comment]
@Arihiza Then comment your bot behavior in the same opened issue and please close this one as a duplicate.

**Comment by langerhans** [comment]
Duplicate
