### ISSUE TITLE
Exception in thread "main" java.io.FileNotFoundException: config.properties

### ISSUE THREAD

**Issue by hellotony95** [jabbink/PokemonGoBot#628]
**Description:**
[Short description of the issue observed. If this is feature request you can modify the template as required.]

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]

**Expected behavior:**
[What should happen?]

**Actual behavior:**
[What actually happens]

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
[The version of the bot you used; when self-compiled: :exclamation: the commit hash :exclamation:]

**Operating System:**
[Your operating system]

**Java version:**
[Full output of `java -version`]

**Comment by Sieberkev** [comment]
Please follow the correct steps from the readme file:

-> Download config.properties.template and save it in the same directory

-> Rename config.properties.template to config.properties (**make sure your operating system doesn't rename it to config.properties.txt**)
