### ISSUE TITLE
suggestion, keep move in the area based on start point

### ISSUE THREAD

**Issue by alawing** [jabbink/PokemonGoBot#63]
suggestion, keep move in the area based on start point

**Comment by jabbink** [comment]
It stays in a 3*3km square around your start point and will NEVER leave that area (and after some time it will actually pass through your start again)

**Comment by alawing** [comment]
That's cool! Will it hatch eggs?

**Comment by jabbink** [comment]
Yes, but right now it won't put eggs in incubators, but if your `speed` is somewhere around or below 2.778 it will hatch them.

**Comment by RaeneDev** [comment]
could an option to change this 3*3km be added? for example..

# km distance around lat/long
distance_box=3

**Comment by jabbink** [comment]
Won't happen because right now the max it can do is 3*3 km and people wouldn't understand why it won't take larger values and I want to prevent useless issues on here.
