### ISSUE TITLE
Error Running loop Botloop!

### ISSUE THREAD

**Issue by EyesReye** [jabbink/PokemonGoBot#631]
**Description:**
Can someone tell me if this is a Bug in the Java File or just the servers having lag issues?

**Expected behavior:**
No Errors, Like yesterday

**Actual behavior:**
Keeps saying Error Running loop Profileloop or Botloop.

http://pastebin.com/uuWNq6Ye

**Version:**
0.4.3

**Operating System:**
Windows 8.1,

**Java version:**
Java is up to date (Updated it today)

**Comment by langerhans** [comment]
Known issue, wait for fix. Closing as duplicate.
