### ISSUE TITLE
Latest Clone - compilation failed

### ISSUE THREAD

**Issue by vamirineni87** [jabbink/PokemonGoBot#633]
**Description:**
```
[08:29:45.971 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :compileKotlin FAILED
\src\main\kotlin\ink\abb\pogo\scraper\Bot.kt: (74, 66): Unresolved reference: thenComparing
Unresolved reference: Base64
@HidesMembers public inline fun <T> Iterable<???>.forEach(action: (???) -> Unit): Unit defined in kotlin.collections
```
]

**Steps to reproduce:**

1. [git clone https://github.com/jabbink/PokemonGoBot.git && cd PokemonGoBot]
2. [git submodule update --init --recursive]
3. [gradlew build --info --debug --stacktrace >> log.log 2>&1]
fails here

**Expected behavior:**
[Compile to Jar]

**Actual behavior:**
[Fails build]

**Stacktrace (If it's a crash):**
[http://pastebin.com/JzJegYQa]

**Version:**
[git clone https://github.com/jabbink/PokemonGoBot.git]

**Operating System:**
[win 10]

**Java version:**
[java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b18, mixed mode)]

**Comment by vamirineni87** [comment]
Let me install JDK 1.8. I only have the runtime installed. !!

**Comment by vamirineni87** [comment]
same issue 
08:48:18.667 [DEBUG] [org.jetbrains.kotlin.gradle.tasks.KotlinCompile_Decorated] v: Configuring the compilation environment
08:48:26.167 [ERROR] [org.jetbrains.kotlin.gradle.tasks.KotlinCompile_Decorated] e: L:\PokemonGoBot\src\main\kotlin\ink\abb\pogo\scraper\Bot.kt: (74, 66): Unresolved reference: thenComparing
08:48:26.167 [ERROR] [org.jetbrains.kotlin.gradle.tasks.KotlinCompile_Decorated] e: L:\PokemonGoBot\src\main\kotlin\ink\abb\pogo\scraper\Settings.kt: (99, 103): Unresolved reference: Base64

**Comment by Sieberkev** [comment]
Strange, both are  1.8 functions which he complains about, yet your java -version says it's 1.8... Do you have by any chance both JDK 1.7 and 1.8 installed on your system?

**Comment by langerhans** [comment]
According to the stack trace you linked above you compiled with JDK 1.7. Do you maybe have multiple JDKs installed? Can you check `echo %JAVA_HOME%` and see where that points to?

**Comment by ToMeRhh** [comment]
open a new terminal and try again; what is the output of echo `%JAVA_HOME%` in it?

**Comment by vamirineni87** [comment]
Thanks folks, it was a path issue. I had a unrelated background script that was force setting path to JDK 1.7
