### ISSUE TITLE
REQUEST: Ability to use custom waypoints/paths, and manual override to walk to a location

### ISSUE THREAD

**Issue by smileytechguy** [jabbink/PokemonGoBot#635]
I want to be able to have it walk between a set of predefined points, such as spots near me with lots of Pokémon.  Also, I would like to be able to direct it to travel to a given set of coordinates, for if I see something rare on Pokévision or similar.

**Comment by TechnoDaft** [comment]
in the gui you can right click the map and your guy will walk there

**Comment by smileytechguy** [comment]
i had no idea, thanks
