### ISSUE TITLE
Login doesnt work

### ISSUE THREAD

**Issue by gutanoth** [jabbink/PokemonGoBot#636]
**Description:**
I get the following error when trying to run 0.4.3

D/GoogleCredentialProvider: Get user to go to:null and enter code:null

**Steps to reproduce:**

1. run the java code

**Comment by langerhans** [comment]
![image](https://cloud.githubusercontent.com/assets/5160000/17257951/e23913ba-55c4-11e6-93c9-2d9cda693980.png)

Update the bot...
