### ISSUE TITLE
Server Returned Unexpected Error

### ISSUE THREAD

**Issue by Killertom63** [jabbink/PokemonGoBot#637]
I was playing fine yesterday, but then it needed to be restarted. 

Now every time I connect it says 

Authenticated with static token
Authenticated with static token
server returned unexpected error. 

I'm still able to login on my phone, so I'm not banned. I have no idea what's broken about it. And yes I logout of my phone before using the windows application.

**Comment by langerhans** [comment]
Check the other issues before posting please ;)

**Comment by Killertom63** [comment]
I did and I couldn't find anything. Why don't you point me in the correct direction instead of just closing it -.-
