### ISSUE TITLE
Could we see the bag and pet counts

### ISSUE THREAD

**Issue by alawing** [jabbink/PokemonGoBot#64]
Could we see the bag and pet counts when watching profile updates log

Also could we see the CP when catched pokemons in log

**Comment by jabbink** [comment]
Bag numbers?

Pet numbers are the poke id I guess?

Adding CP of caught Pokemon sounds good

**Comment by alawing** [comment]
Sorry, I mean counts,

**Comment by jabbink** [comment]
Ah, makes sense. Good additions :+1:

**Comment by pr0ves** [comment]
Managed to add the number of pokemons, but can't do it for the inventory because the Bag class doesn't have a function to return a list of items, so I can't get a count

**Comment by elliottfeng** [comment]
notice that there are some Pokemon ID missed. Like Arcanine. 
Also, is it possible to make a statistics file after closing, showing how many caught, how much XP got.

**Comment by jabbink** [comment]
Pokebank implemented https://github.com/jabbink/PokemonGoBot/blob/master/src/main/kotlin/ink/abb/pogo/scraper/tasks/UpdateProfile.kt#L33
