### ISSUE TITLE
Random BotLoop and WalkingLoop error after period of time

### ISSUE THREAD

**Issue by smileytechguy** [jabbink/PokemonGoBot#641]
**Description:**
The bot was operating normally after a period of 30-60 minutes, and while getting map coordinates began throwing errors.  
Seems to be trying to re-authenicate, maybe the static key expired?

**Steps to reproduce:**

1. Google login using app password to bypass 2FA, no token (nor any idea of how to get one)
2. Run as usual

**Expected behavior:**
Continual running

**Actual behavior:**
Stops working while **allowing some map requests through, no pokemon or portal functionality

**Stacktrace (If it's a crash):**
https://ghostbin.com/paste/vrtfy

**Version:**
Self compiled using gradle from homebrew and gradlew from the directory - develop branch - b005051d7aca3c53991b9bd7edcecd74488c6ed4

**Operating System:**
OS X 10.11.6 Dev - SIP disabled

**Java version:**
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**configuration**
https://ghostbin.com/paste/9e3fg

**compilation results**
https://ghostbin.com/paste/ac5po

## EDIT
**Network limitations**
As it did not work without limiting network speed and latency, seen in issue #627, most people used NEWT but as I am using OS X, I am using "Network Link Conditioner", part of the Hardware IO Tools for Xcode 7.3

**Comment by langerhans** [comment]
Can you try v0.5.0-alpha3 and report back if you still see the same error?

**Comment by pvase666** [comment]
@langerhans  seems that working well, will report later . Thanks :)

**Comment by langerhans** [comment]
Those have been mostly irnoed out with alpha3 and 4. So closing here for now.
