### ISSUE TITLE
Can't import com.pokegoapi.auth.PtcCredentialProvider

### ISSUE THREAD

**Issue by dannydawson2001** [jabbink/PokemonGoBot#642]
I've included all necessary jars in my project (ie PokeGOAPI-Java-4f5b715380.jar).  It doesn't appear to include PtcCredentialProvider, but according to the JavaDoc, this should be a part of com.pokegoapi.auth. 

Can someone tell me where I'm going wrong?

Thanks!

**Comment by langerhans** [comment]
You should not include any jars. Gradle will do all the dependency management for you. Please follow the Readme on how to setup the project to build from source.
