### ISSUE TITLE
Install Help

### ISSUE THREAD

**Issue by vinc05** [jabbink/PokemonGoBot#644]
**Description:**
Can i install on derbian 8, 
how? thanks

**Operating System:**
Derbian 8
**Java version:**
8

**Comment by Sieberkev** [comment]
Yes it is possible if you follow the guidelines from the readme file. Just make 100% sure you use Oracle JDK/JRE 8 and NOT the default OpenJDK/JRE 8.

**Comment by BartWillems** [comment]
@Sieberkev Wew lad, it works perfectly on OpenJDK, I would even recommend to use OpenJDK in stead of Oracle's proprietary Java

**Comment by Sieberkev** [comment]
There are a bunch of issues that were reported here with people using OpenJDK #553, [this comment](https://github.com/jabbink/PokemonGoBot/issues/388#issuecomment-235219015) from jaddink ¯\\_(ツ)_/¯

**Comment by vinc05** [comment]
i use this

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

now why i can use gradlew build
i'have gradle installed


------------------------------------------------------------
Gradle 1.5
------------------------------------------------------------

Gradle build time: Wednesday, October 8, 2014 8:21:39 AM UTC
Groovy: 1.8.6

**Comment by vinc05** [comment]
ah ok i resolve ./gradlew for install and for ./gradlew build

**Comment by Sieberkev** [comment]
If it works please close the issue, thanks! :)

**Comment by BartWillems** [comment]
@sieberkev wew, I tried to compile it just now, failed with OpenJDK, success with oracle jdk :/ In all my years I've never encountered something like that :p
