### ISSUE TITLE
Bot wouldn't catch Pokemons

### ISSUE THREAD

**Issue by d0tamon** [jabbink/PokemonGoBot#649]
**Description:**
After using NEWT, the bot is only in walk mode and is unable to catch pokemons. I checked the config file and all seems fine there.

**Expected behavior:**
Catch Pokemons after a period of time

**Actual behavior:**
Getting map of (latitude, longitude)

**Stacktrace (If it's a crash):**

**Version:**
0.5.0-alpha2

**Operating System:**
Windows 10 64-bit
**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) Client VM (build 25.101-b13, mixed mode, sharing)

**Comment by PancakeZik** [comment]
I had same problem, use version 0.4.3 and it will work wonders

**Comment by d0tamon** [comment]
@PancakeZik v0.4.3 gives me googlecredentialprovider error. I cannot run any bot except v0.5.0-alpha2

**Comment by pashorizer** [comment]
Fixed here https://github.com/jabbink/PokemonGoBot/pull/574

**Comment by SoulCrest** [comment]
Can any Reupload a working JAR?
I am to Stupid to Fixx them self :(

Mfg

**Comment by langerhans** [comment]
I'll just believe pash that it's fixed. New release is in the works.
