### ISSUE TITLE
issue with obtaining a token 

### ISSUE THREAD

**Issue by mSmithe** [jabbink/PokemonGoBot#650]
when trying to activate the bot the google.com/device address and the code stoped showing to obtain the token

java -jar pogo.scraper-all-0.4.3.jar
30 Jul 16:45:48: Logging in to game server...
D/GoogleCredentialProvider: 0
D/GoogleCredentialProvider: Get user to go to:null and enter code:null

**Comment by Agronis** [comment]
Thanks for joining GitHub just to post this issue.

# Now learn to use the search function.

**Comment by Fuguesista** [comment]
change your version to the latest version
and good luck with that
#627
