### ISSUE TITLE
Is there going to be an update?

### ISSUE THREAD

**Issue by Rishabhpatted24** [jabbink/PokemonGoBot#651]
Its been a while since the last update...
NEWT doesn't do wonders for me...
Will there be a update fixing the issue? 
Sorry if wrong place to post. Will delete if not permitted..

**Comment by langerhans** [comment]
Come on people, show some patience. People are working on it, but you are aware they have lives too and other stuff they need to take care of yes?

People all over the worls spend ours to do some remarkable work just that some others can cheat on a game about catching virtual monsters. Think about it for a second and tell me if asking for ETAs does any good to that situation? :wink:
