### ISSUE TITLE
Dropped 3x ITEM_INCENSE_ORDINARY 

### ISSUE THREAD

**Issue by spantin** [jabbink/PokemonGoBot#656]
**Description:**
Ran the latest release with the same config file I've been using for previous versions and the first thing it did when I started it was drop my incense. No previous versions have done this and I'm using the same config file. Has anyone else encountered this? 

item_incense_ordinary=-1 should be a default

**Comment by pvase666** [comment]
Just add item_incense_ordinary=-1  to your config.properties file.

**Comment by spantin** [comment]
Yes. But what I'm suggesting is in PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Settings.kt. The defaults for lucky eggs and incense is currently 5. They should default to -1 since they are special items that are bought. If people copy their old config.properties file from alpha2 or older to alpha3 their extra eggs and incense will get dropped.

`Pair(ItemId.ITEM_LUCKY_EGG, 5),
Pair(ItemId.ITEM_INCENSE_ORDINARY, 5),`

Should be 

`Pair(ItemId.ITEM_LUCKY_EGG, -1),
Pair(ItemId.ITEM_INCENSE_ORDINARY, -1),`

**Comment by citruz** [comment]
This has been introduced in #609 because some people had problem with inventory overflows. You will get these items not only from the shop but also when leveling up.
Before running a new version of the bot, it is always helpful to have a look at the `config.properties.template` to see which new options have been added.

**Comment by kookiekrak** [comment]
except for the part where it's not present in the new config file with any default value

https://raw.githubusercontent.com/jabbink/PokemonGoBot/master/config.properties.template

i bought 20 incenses though iap which it dropped. is there a similar setting for lures that we don't know about as well?

**Comment by spantin** [comment]
Potions, Revives, Balls, and Berries are all obtainable from PokeStops. The rewards from level 1 to level cap will only net you a total of 16 lucky eggs and 16 incense. Unless purchased, you will never get more than 16. The inventory space gained by dropping them is negligible relative to their value. It makes more sense to lower the defaults for various items obtainable throw stops and not impose a default limit on the special items.

**Comment by kookiekrak** [comment]
@spantin @pvase666 

the correct settings are

item_lucky_egg=-1
item_incense=-1
item_lure_module=-1

**Comment by citruz** [comment]
@kookiekrak Yes it is in the config. Your link points to the master branch. https://github.com/jabbink/PokemonGoBot/blob/develop/config.properties.template
Sorry for your incenses. Yes, there is also a default limit for lures.

@spantin You're right that they don't use up much space in the inventory. I will submit a PR which sets the default for incences, lucky egg and lure to -1.

**Comment by kookiekrak** [comment]
@citruz no problem. Thanks!

**Comment by GrizzlyJay** [comment]
@citruz Yes, the parameters for eggs, incense, and lures are in the config file for people to git clone. The major screw up at the moment is the fact that the config file he linked is ACTUALLY the file that is being pointed to on the release page. So anybody that's new to this, or is doing a client is going to pull the config template from that link, thus dropping anything of real value. So whoever's making changes to the releases info needs to get their poop in a group.

**Comment by langerhans** [comment]
Fixed in #659
