### ISSUE TITLE
Discord Discussion Area

### ISSUE THREAD

**Issue by EpicAwesomeWolf** [jabbink/PokemonGoBot#658]
Uh hi, I didn't know if y'all had one, but I made a Discord server to get some more on demand help/area to discuss for the bot. If you want me to delete or something, let me know.

Link: discord.gg/GNFMs

**Comment by langerhans** [comment]
There is a Slack chat linked here https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md#contact
