### ISSUE TITLE
Getting map of (NaN, NaN)! [Solved]

### ISSUE THREAD

**Issue by ColeB27** [jabbink/PokemonGoBot#66]
Have JOLTEON () with 873 CP
Have GOLDUCK () with 563 CP
Have BELLSPROUT () with 133 CP
Have HORSEA () with 197 CP
Have VAPOREON () with 699 CP
Have VAPOREON () with 1373 CP
Have PARAS () with 271 CP
Have EEVEE () with 131 CP
Have MANKEY () with 107 CP
Have JIGGLYPUFF () with 204 CP
Have CATERPIE () with 24 CP
Have WEEDLE () with 100 CP
Have SEAKING () with 567 CP
Have VAPOREON () with 1092 CP
Have WARTORTLE () with 397 CP
Have BULBASAUR () with 347 CP
Have RATICATE () with 356 CP
Have RHYHORN () with 238 CP
Have LICKITUNG () with 341 CP
Have PIDGEOT () with 702 CP
Have EEVEE () with 344 CP
Have GOLBAT () with 610 CP
Have SHELLDER () with 74 CP
Have KAKUNA () with 128 CP
Have RATTATA () with 24 CP
Have JOLTEON () with 796 CP
Have CLEFABLE () with 842 CP
Have SANDSHREW () with 114 CP
Have PONYTA () with 154 CP
Have SQUIRTLE () with 205 CP
Have CUBONE () with 130 CP
Have POLIWAG () with 129 CP
Have SLOWBRO () with 903 CP
Have SLOWBRO () with 548 CP
Have SEAKING () with 417 CP
Have JYNX () with 467 CP
Have GYARADOS () with 1201 CP
Have STARYU () with 357 CP
Have EEVEE () with 381 CP
Have MAGIKARP () with 95 CP
Have NIDORINO () with 373 CP
Have TENTACRUEL () with 147 CP
Have GASTLY () with 73 CP
Have TANGELA () with 195 CP
Have KOFFING () with 15 CP
Have DRATINI () with 365 CP
Have GROWLITHE () with 205 CP
Have KRABBY () with 96 CP
Have KINGLER () with 131 CP
Have EEVEE () with 355 CP
Have FEAROW () with 111 CP
Have HAUNTER () with 218 CP
Have SPEAROW () with 215 CP
Have ODDISH () with 80 CP
Have GOLDUCK () with 658 CP
Have PIDGEY () with 123 CP
Have GEODUGE () with 219 CP
Have POLIWHIRL () with 398 CP
Have TENTACOOL () with 147 CP
Have GOLDUCK () with 860 CP
Have NIDORAN_MALE () with 94 CP
Have NIDORAN_FEMALE () with 128 CP
Have VENONAT () with 409 CP
Have CLEFARY () with 390 CP
Have GOLDUCK () with 492 CP
Have EKANS () with 292 CP
Have ZUBAT () with 168 CP
Have PIDGEOT () with 760 CP
Have GOLBAT () with 723 CP
Have PSYDUCK () with 275 CP
Have PINSIR () with 507 CP
Have DODUO () with 292 CP
Have METAPOD () with 139 CP
Have GOLDEEN () with 196 CP
Have VULPIX () with 53 CP
Getting map of (40.75896859803333, -73.98449749765875)
Getting initial pokestops...
Getting map of (40.75901459642814, -73.98442766605562)
Looting nearby pokestop bd36f5d2538a40f68cee46912755e513.12
Looted pokestop bd36f5d2538a40f68cee46912755e513.12: []
Walking to (40.759011, -73.984472) in 0.0 steps.
Destination reached.
Profile update : 136464 XP on LVL 16; 36464/40000 (91.16%) to LVL 17
Getting map of (NaN, NaN)
Walking to (40.771479, -73.994876) in NaN steps.
Profile update : 136464 XP on LVL 16; 36464/40000 (91.16%) to LVL 17
Getting map of (NaN, NaN)
Profile update : 136464 XP on LVL 16; 36464/40000 (91.16%) to LVL 17
Getting map of (NaN, NaN)
Profile update : 136464 XP on LVL 16; 36464/40000 (91.16%) to LVL 17
Getting map of (NaN, NaN)
Profile update : 136464 XP on LVL 16; 36464/40000 (91.16%) to LVL 17
Getting map of (NaN, NaN)
Profile update : 136464 XP on LVL 16; 36464/40000 (91.16%) to LVL 17
Getting map of (NaN, NaN)
Profile update : 136464 XP on LVL 16; 36464/40000 (91.16%) to LVL 17
Getting map of (NaN, NaN)
Profile update : 136464 XP on LVL 16; 36464/40000 (91.16%) to LVL 17
Getting map of (NaN, NaN)
Getting map of (NaN, NaN)
Profile update : 136464 XP on LVL 16; 36464/40000 (91.16%) to LVL 17
Profile update : 136464 XP on LVL 16; 36464/40000 (91.16%) to LVL 17

**Comment by RaeneDev** [comment]
May want to remove your username and token as they are both personal and tied to your account. anyone can view this.

**Comment by ColeB27** [comment]
@RaeneDev thanks! Saved me there!

**Comment by RaeneDev** [comment]
yep! It seems like it would be a problem with the long/lat from what I can see. Try putting something else in. I suggest using http://www.gps-coordinates.net/ as it allows address searching and the map isn't clustered/tiny.

**Comment by ColeB27** [comment]
@RaeneDev do you have any coordinates that are absolutely stocked with pokemon?

**Comment by RaeneDev** [comment]
I'm using coordinates from San Francisco as I live in the area and changing 20+ miles seems to set off a softban. 
but here's an example. 

latitude=37.774929
longitude=-122.419416
Personally. This location has tons of pokestops. As for pokemon. It mostly catches Zubats but I'm mostly using the bot for stardust while I'm at work.
San Francisco has a lot of uncommon/rare pokemon though. try different areas in SF with http://www.gps-coordinates.net/.

**Comment by jozsi** [comment]
This issue is still happening in latest master (commit 2a2ea31a94fa39e3cdaa127a31b2330300abf703), although the same coordinates worked well in release v0.3.0.

```
24 Jul 04:30:08: Walking to (47.057597, 21.913901) in 0.0 steps.
24 Jul 04:30:08: Destination reached.
24 Jul 04:30:12: Getting map of (NaN, NaN)
24 Jul 04:30:15: Walking to (47.049645, 21.908377) in NaN steps.
```

I guess it's related to a division by zero, because if I slightly change the coordinates (add 0.000001 to it), it has steps to go and works well. So the original coords might exactly have a pokestop on it.

**Comment by jozsi** [comment]
cc @jabbink

**Comment by jabbink** [comment]
Thanks, fixed.
