### ISSUE TITLE
Forced Google login

### ISSUE THREAD

**Issue by classicalDonkey** [jabbink/PokemonGoBot#662]
**Description:**
I have just started to use the new version and I am using a PTC account, but it is forcing me to link to a google account.

**Actual behavior:**
E:\Pokemon\Pokemon Go\Classicaldonkey>java -jar pogo.scraper-all-0.5.0.jar
30 Jul 21:09:21: Logging in to game server...
Please go to https://accounts.google.com/o/oauth2/auth?client_id=8482******40-73ri3t7plvk96pj4f85uj8otdat2alem.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=openid%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
Enter authorisation code:

**Version:**
Pokemon Go Bot v0.5.0 alpha 3

**Operating System:**
Windows 10

**Comment by langerhans** [comment]
Is there an `@` in your PTC username?

**Comment by classicalDonkey** [comment]
# PTC/Google login credentials

username=
classicaldonkey

**Comment by Sieberkev** [comment]
You have to put it on the same line :)

**Comment by classicalDonkey** [comment]
I do have it on the same line, and I have just deleted those lines and put them back in and still does that, I have another account that worked fine just this one!
