### ISSUE TITLE
Whislist: make it possible to localize the GUI and the output

### ISSUE THREAD

**Issue by urbalazs** [jabbink/PokemonGoBot#667]
**Description:**
It would be great, if the GUI and all the output can be translated into several languages.
Please, use .pot and .po format for the language files. There are many translation tool, that can handle this format, so translators don't need to learn, how to translate this program.

**Comment by Agronis** [comment]
We're looking into building out a clientside web app that'll impose an overhaul on the GUI.

Noted.

**Comment by urbalazs** [comment]
It seems this project is dead :(
I close this issue for now.
