### ISSUE TITLE
Server refused your login credentials. Are they correct?

### ISSUE THREAD

**Issue by kasagon** [jabbink/PokemonGoBot#669]
**Description:**
When I launch the bot, I get the error that the server refused my login credentials, but they are correct.

I am using a google account, and I am able to login at the Pokemon Go app and google.com as usual. I also copied my login credentials from an older version of the bot, where it still works (but I get those loops errors there)

Also, when I installed this version, I got a few hounderd lines with errors when building.

The error: http://pastebin.com/XpxZYKtU

**Steps to reproduce:**

1. Start the bot.

**Expected behavior:**
Bot should be running

**Actual behavior:**
Bot does not run

**Stacktrace (If it's a crash):**
http://pastebin.com/dpKGMTr8

**Version:**
Commit hash:

    C:\PokemonGoBot>git rev-parse --short HEAD
    62e2fb1

**Operating System:**
Windows 10 PRO 64-bit

**Java version:**

    C:\PokemonGoBot>java -version
    java version "1.8.0_102"
    Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**Comment by pashorizer** [comment]
Login is working. Check if you have any spaces in your credentials and/or using the correct path to config.properties in the project folder.

**Comment by kasagon** [comment]
@pashorizer Just fixed it, I am using the base64 password, I just put a # before the normal password field (how it is marked as comment) and it worked.

I guess it was taking the password from that empty field instead of the base64 field.
