### ISSUE TITLE
Add how many of each item type you would want to keep in config.properties

### ISSUE THREAD

**Issue by wartickler** [jabbink/PokemonGoBot#67]
I believe I understand your thinking that you don't really want to keep that much stuff in your inventory but I really would like to keep more than 5 of each ball type, revives,  potions, and (eventually) raspberries.

Perhaps an entry for each item type in the config.properties that lets us specify the number to keep?

**Comment by RaeneDev** [comment]
I mentioned this somewhere earlier but I believe it's being developed or already has been but with no note of it.

try adding things like this to the config. Personally haven't tested it myself to see if it works but it doesn't throw any errors.

(the -1 means to never toss)
item_revive=10
item_max_revive=40
item_great_ball=50
item_ultra_ball=-1
item_master_ball=-1
item_razz_berry=60

**Comment by wartickler** [comment]
Check out https://github.com/jabbink/PokemonGoBot/blob/089a0ff80a474b212cd0e4265166bf901093b0c8/src/main/kotlin/ink/abb/pogo/scraper/Settings.kt for the settings being read from the file. Your entries aren't crashing because nothing is looking for it. This hasn't been implemented yet.

**Comment by RaeneDev** [comment]
ah. I didnt see this but I swore I read somewhere about this

**Comment by leadboots5** [comment]
There is a pull request for it, but it needs to be updated since refactoring was done:
https://github.com/jabbink/PokemonGoBot/pull/36

**Comment by mroge009** [comment]
Added this in [#71](https://github.com/jabbink/PokemonGoBot/issues/71)
