### ISSUE TITLE
[Suggestion] Incubators

### ISSUE THREAD

**Issue by classicalDonkey** [jabbink/PokemonGoBot#670]
**Description:**
Is it possible to get a output that shows the status of the incubators?  So when it does its normal update, you get a list of the incubators and the distance that has been traveled.

**Comment by pashorizer** [comment]
Is it that important? I mean the hatched Pokemon will get checked after the set IV,CP etc. anyways.

**Comment by classicalDonkey** [comment]
ya but ti would be nice to know when a egg will hatch, the number of times i have thought a egg was close and no way to look.  i would have to stop the bot and open the app on my phone, but if it gave it in the feed I would not have to do that.

**Comment by BerserkerJP** [comment]
#709 Simple eggs window added
