### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by pikachukaki** [jabbink/PokemonGoBot#674]
> java.io.IOException: Cannot run program "C:\Users\Pikachukaki\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protoc\3.0.0-beta-3\71e76cad4f9b30aab172c44035d343c5bab47815\protoc-3.0.0-beta-3-windows-x86_64.exe": CreateProcess error=206, The filename or extension is too long

How can i fix this???

**Comment by TechnoDaft** [comment]
"The filename or extension is too long" hmm what does that say....maybe try doing it in C drive

**Comment by pikachukaki** [comment]
yeah how can i move this file so it will be able to build...it put it there by itself after typing "gradlew build"

**Comment by smileytechguy** [comment]
use the jar, thats the only way to get around javas limitations

**Comment by langerhans** [comment]
That's a Gradle bug on windows. Clone the project for example into C:\pogo and build from there.
