### ISSUE TITLE
Alpha3 not able to log in

### ISSUE THREAD

**Issue by Arihiza** [jabbink/PokemonGoBot#675]
I am able to log in with 0.4.3 and Alpha2 with the same config but it says the sever refused my config credentials. 

> saraneth@saraneth-HP-ENVY-15-Notebook-PC ~/Downloads $ java -jar pogo.scraper-all-0.5.0-alpha3.jar
> 31 Jul 16:35:46: Logging in to game server...
> 31 Jul 16:35:47: Server refused your login credentials. Are they correct? 
> saraneth@saraneth-HP-ENVY-15-Notebook-PC ~/Downloads $ java -jar pogo.scraper-all-0.5.0-alpha3.jar
> 31 Jul 16:37:07: Logging in to game server...
> 31 Jul 16:37:08: Server refused your login credentials. Are they correct? 
> saraneth@saraneth-HP-ENVY-15-Notebook-PC ~/Downloads $ java -jar pogo.scraper-all-0.5.0-alpha2.jar
> 31 Jul 16:37:29: Logging in to game server...
> D/GoogleCredentialProvider: 3600
> D/GoogleCredentialProvider: Refreshed Token eyJhbGciOiJSUzI1...
> D/RequestHandler: Authenticated with static token
> D/RequestHandler: Authenticated with static token

**Comment by TechnoDaft** [comment]
first hide your token if pokemon was tradable your fucked second use the development atm the releases dont work properly

**Comment by superkilerpokemon** [comment]
@TechnoDaft how to use devs?

**Comment by TechnoDaft** [comment]
go to the code and scroll down it tells you how just install git {cmd commands} and jdk

**Comment by superkilerpokemon** [comment]
@TechnoDaft I'm even too retarded to use that tutorial.

**Comment by TechnoDaft** [comment]
install https://git-scm.com/download/win and http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
after that just copy/paste everything into cmd easy

**Comment by langerhans** [comment]
Is this still an issue? If not please close.

**Comment by Arihiza** [comment]
Still an issue for me!

**Comment by langerhans** [comment]
In a sense of consolidating issues I'll close here cause it's the same as #583. Please continue investigation there. I can't reproduce this myself :/
