### ISSUE TITLE
[Suggestion] Blacklist Pokemon

### ISSUE THREAD

**Issue by sgk128** [jabbink/PokemonGoBot#679]
Hi Guys, I was wonder if it would be possible to blacklist a certain pokemon from being catch? When pokeballs are limited, it would be great it there is a way to just skip pokemons we dont need or want. Thanks for hard work.

**Comment by Rofii** [comment]
Set "desired_catch_probability_unwanted"=-1 in config and use "obligatory_transfer" for your blacklist. Profit.

**Comment by sgk128** [comment]
it seems to have work for a bit then stopped. is there a limit on how many i can have on there?

**Comment by TheJ0k3r** [comment]
Nope just paste the one after eatch other with an "," between and afcourse correct names
