### ISSUE TITLE
LoginFailed after (exactly) 1,5h

### ISSUE THREAD

**Issue by HoneyWheat** [jabbink/PokemonGoBot#680]
I noticed that the/my bot stops working after nearly excact 1,5h. After that I only get LoginFailedExeptions. Can somebody confirm this?!

- **Google login**
- **Version 0.5.0alpha3**

**Comment by alexpw** [comment]
yes, I experience this too.  I'm using a google account, in case that helps someone, but I only have wild speculation about why.

**Comment by GeitV** [comment]
I just got it too, but using PTC. My error says LoginFailedException: Error in API Url

**Comment by TheJ0k3r** [comment]
i think its because of not renewing the token or something

**Comment by sphinxid** [comment]
I confirmed this too with PTC login. Most probably the sso token already expired, but the bot keep trying to re-authenticated with the expired token.

**Comment by Mewks** [comment]
I can confirm this too however ONLY with Google. I have several PTC bots running for many hours now, no issues.

**Comment by matholland618** [comment]
I'm getting this error as well.

**Comment by BugSyst3m** [comment]
Can somebody come up with a script to kill and reload the bot every 1.5 hours ?

**Comment by TheJ0k3r** [comment]
i'm working on it

**Comment by TheJ0k3r** [comment]
With some batch files you can terminate your cmd and restart it its a crapy fix but it works

**Comment by Casual-User** [comment]
Running precompiled alpha.4 i got this after exactly TWO and a half hours....

**Comment by langerhans** [comment]
Hacky workaround for me is to restart the bot every 90 minutes: 
`while [ 1 ]; do killall java; nohup java -jar pogo.scraper-all-0.5.0-alpha4.jar &; sleep 5400; done`

**Comment by Mikeykingz** [comment]
How would you create a script for rebooting the bot for Mac OSX ?

**Comment by cozos** [comment]
@Mikeykingz I think that this comment has your solution: https://github.com/jabbink/PokemonGoBot/issues/680#issuecomment-236499717

```
while [ 1 ]; do killall java; nohup java -jar pogo.scraper-all-0.5.0-alpha4.jar &; sleep 5400; done
```

Haven't personally tried but looks like a shell script to me ...

I think I've figured out a `.bat` restart script for windows - that was a huge pain in the ass. Here's how I did it (feel free to correct me btw!)

You need to create two `.bat` files in the same directory as your JAR:

start.bat
```bat
java -jar pogo.scraper-all-0.5.0-alpha4.jar
```

restartscript.bat
```bat
:loop
START "pogobot" start.bat & timeout /t 3600 & taskkill /fi "WINDOWTITLE eq pogobot - start.bat*" /f & taskkill /fi "WINDOWTITLE eq pogobot - start.bat*" /f & timeout /t 10
goto loop
```

And then... you run `restartscript.bat` from the terminal or just from the file explorer

**Comment by jabbink** [comment]
Should be fixed.
