### ISSUE TITLE
How to build on os x?

### ISSUE THREAD

**Issue by chemikaz** [jabbink/PokemonGoBot#681]
I would like to get some help with building on os x. At "Run from terminal/cmd: gradlew build" I'm getting gradlew command not found.. Thank you for anwsers.

**Comment by alexpw** [comment]
The file is there in the base directory.   Use:  ./gradlew build

**Comment by TheFreakLord** [comment]
^ 

And if you are using an Unix-like OS but don't know how to execute files in the terminal, you should really consider switching to Windows.

**Comment by chemikaz** [comment]
**alexpw**, thank you for help appreciate it.
**TheFreakLord**, just want to learn something new buddy, thank you for your opinion.

**Comment by langerhans** [comment]
If you got it working, please close the issue :)

**Comment by chemikaz** [comment]
close

**Comment by smileytechguy** [comment]
@chemikaz you can also install homebrew using brew.sh, and install gradle there.  Then run gradle build from PATH
