### ISSUE TITLE
Bot dropping lucky eggs!

### ISSUE THREAD

**Issue by olgo92** [jabbink/PokemonGoBot#682]
**Description:**
I just updated to 5.0 alpha 3 release and started the bot and noticed it printing the following in the console:
Dropped 10x ITEM_LUCKY_EGG ←[0m

**Steps to reproduce:**

1. Update to 5.0 alpha 3 
2. Have some lucky eggs
3. start the bot
4. ???
5. Profit

**Expected behavior:**
I think it should never drop rare items!

**Actual behavior:**
It drops them!

**Comment by pashorizer** [comment]
Yeah, there is a new max number of items
https://github.com/jabbink/PokemonGoBot/blob/develop/config.properties.template#L58

**Comment by olgo92** [comment]
Why isnt it defaulting to -1 if not set directly?

**Comment by citruz** [comment]
I already submitted a fix for this #659
