### ISSUE TITLE
How to reduce the searching Area? (not an issue) 

### ISSUE THREAD

**Issue by Evuse** [jabbink/PokemonGoBot#683]
Hello guys can you please explain what i should edit on the config file to limit the searching area to 1km for example?

Thanks

**Comment by yashendra2797** [comment]
First, grab the latest [config.properties](https://raw.githubusercontent.com/jabbink/PokemonGoBot/develop/config.properties.template) file. Copy-paste all the old data into the new updated version, which has these two options:

`# Max distance from starting point the bot should ever go in meters
# (-1: only limited by the initial pokestops (~3*3km); with allow_leave_start_area=true unlimited)
spawn_radius=-1

# Set Timer in seconds to go back to the starting PokeStop (-1 disabled)
timerWalkToStartPokeStop=-1`

Use these options as you want to.

**Comment by langerhans** [comment]
Closing as question is answered.
