### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by blazemalan** [jabbink/PokemonGoBot#685]
**Description:**
[Short description of the issue observed. If this is feature request you can modify the template as required.]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.69 secs
Blazes-iMac-2:PokemonGoBot blaze$ 
**Steps to reproduce:**

1. ./gradlew run

**Expected behavior:**
[What should happen?]
Should have ran.

**Actual behavior:**
[What actually happens]
Build Failed

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]
Exception in thread "main" java.io.FileNotFoundException: config.properties (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:79)
:run FAILED

**Version:**
[The version of the bot you used; when self-compiled: :exclamation: the commit hash :exclamation:]
.5.0 alpha 3

**Operating System:**
[Your operating system]
OSX 10.12

**Java version:**
[Full output of `java -version`]
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by Sieberkev** [comment]
> FileNotFoundException: config.properties (No such file or directory)
Make sure the config.properties file is in the root directory where you run the `./gradlew run` command and your OS didn't rename it to config.properties.txt

**Comment by swtrpeter** [comment]
i cannot get the zip file to run at all.. I have been having issues with it since last night. I do everything in the wiki but how do you actually make it run ?

**Comment by blazemalan** [comment]
Thank you Sieberkev. Worked!

**Comment by Sieberkev** [comment]
@swtrpeter use `./gradlew run`

**Comment by swtrpeter** [comment]
@Sieberkev  where do I put ./gradlew run ? I am not a programmer.. Just trying to make this run.. Need a little more details.

**Comment by blazemalan** [comment]
@sieberkev this may be too hard for you then. This is all console commands in your terminal

**Comment by swtrpeter** [comment]
I can run commands in the terminal but I need to know if i need to run anything before the command above.

**Comment by swtrpeter** [comment]
![error](https://cloud.githubusercontent.com/assets/20620293/17277818/49d57fe2-5712-11e6-8e8e-41dc2926666c.PNG)

That is the error I am getting.. I have already tried gradlew clean build and it didnt help.. Can anyone help me with this ?

**Comment by blazemalan** [comment]
I'm on a Mac I'm not sure

**Comment by langerhans** [comment]
If you're not a programmer., please use the prebuilt versions. You seem to be on a totally wrong branch according to your screenshot.
