### ISSUE TITLE
gradlew run stuck at 92% on build: getting 0 initial pokestops

### ISSUE THREAD

**Issue by tdumas0613** [jabbink/PokemonGoBot#686]
I have just cloned the repo this morning 7/31/16. As the title states, when I execute ./gradlew run (I am on Mac OS) I get stuck while getting initial pokestops.  The program returns 0 pokestops and retrys every 10 seconds. From my understanding this number should not be zero and I appear to be stuck but cannot figure out why there are no pokestops returning. 

My config.properties file is here:

http://pastebin.com/7LgqMVz7

Has anyone else experienced this issue/know how to fix it?

**Comment by Sieberkev** [comment]
> The program returns 0 pokestops and retrys every 10 seconds. From my understanding this number should not be zero and I appear to be stuck but cannot figure out why there are no pokestops returning.

This is something server related I think, are you switching too fast from location to location? Waited a little bit before restarting?

**Comment by tdumas0613** [comment]
I've reran the "./gradlew run" command several times, with an wait time of 5-10 minutes before each rerun. As far as switching too fast from location to location goes, i don't believe my location is switching at all. It appears as though I am trying to get initial pokestops from the lat and long supplied in the config.properties file each time. There is a screen shot of the console output attached to this comment
<img width="345" alt="initial_pokestops" src="https://cloud.githubusercontent.com/assets/13876245/17278011/c903ac7c-5716-11e6-9b10-ddd2f3f44f36.png">

**Comment by langerhans** [comment]
This is most likely a server issue or a softban, not actually sure. Try to make sure you use the same location and try again in a few.

**Comment by tdumas0613** [comment]
I created a new account & only logged in from one location to test the softban theory with no change in results. I will try again in a few hours and post an update/close the issue if anything changes

**Comment by corex303** [comment]
I'm having the same issue

**Comment by tdumas0613** [comment]
Just checked again with a fresh account and very accurate lat long coordinates. The issue persisted.  I'm nearly certain this is not a softban.

**Comment by edwincheung555** [comment]
the same thing had happened to me, but after waiting 10 minutes, i set my coordinates right next to a place i knew had a pokestop and now the problem is fixed. So try to set your coordinate near a pokestop first and see if the problem is fixed or not. the only problem i have right now though is that im not catching any pokemon at all

**Comment by tdumas0613** [comment]
@edwincheung555 unfortunately setting my lat and long to a known pokestop didn't fix this problem for me :( 

any one else have success with this fix??

**Comment by Casual-User** [comment]
I have this reoccurring issue running 4 builds of alpha.4.
At the moment I fix it with stopping the respective bot, waiting for at least ten minutes and letting it respawn at fresh coordinates nearby. Since I got it immediately (don't know if by coincidence) when I started a second bot at the same coordinates as another, I believe in the soft ban hypothesis.

**Comment by Sieberkev** [comment]
The easiest way is just to run the precompiled JAR file. They just released a new alpha which works quite good :)

**Comment by Kegoscho** [comment]
@Sieberkev weeell not for me =D

First time run: blacklisted every new pokestop for 10 min (unusual server error or sth)
and now :getting 0 initial pokestops

**Comment by tdumas0613** [comment]
@Kegoscho running the precompiled jar did not work for me either :(

**Comment by tdumas0613** [comment]
Any one know if the latitude is North or South by default? I'm currently trying to indicate north in the config.properties file but am getting an "Failed to interpret Starting Latitude setting ("latitude")" error. I'm also digging through the code but am not fully confident in the radian math that is happening behind the scenes. Same question for longitude (West or East by default)

**Comment by tdumas0613** [comment]
Make sure to double check lat and long numbers. Use positive for North latitude and East longitude. Use negative numbers for South latitude and West longitude. After switching my longitude the program is running just fine.

**Comment by corex303** [comment]
Fixed by turning off my VPN. :)
