### ISSUE TITLE
Cannot get this to run.. Help ! !

### ISSUE THREAD

**Issue by swtrpeter** [jabbink/PokemonGoBot#687]
**Description:**
I cannot get this to run so please give me some help. I follow the steps in the wiki but I cannot figure out how to run the step git submodule update --init --recursive . I have tried running that in the folder command prompt but it throws an error. I am new to all of this so please add some details in how I could fix this.

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]

**Expected behavior:**
[What should happen?]

**Actual behavior:**
[What actually happens]

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
[The version of the bot you used; when self-compiled: :exclamation: the commit hash :exclamation:]

**Operating System:**
Windows 7

**Java version:**
[Full output of `java -version`]

**Comment by Sieberkev** [comment]
Are you are running this in windows? So you need to install GIT on your system: https://git-scm.com/download/win

**Comment by swtrpeter** [comment]
@Sieberkev I downloaded GIT last night. When I open command and run git submodule update --init --recursive in the folder i get FATAL bot  git repository

**Comment by swtrpeter** [comment]
@Sieberkev I can get the prebuilt to run but I have no map or anything visible when i got to local host via browser. So the only way I can see what is happening is just to watch terminal as its scanning.

**Comment by Sieberkev** [comment]
Sure you're going to [http://localhost:8000/](http://localhost:8000/) (and not just "localhost", it has to be port 8000)

**Comment by swtrpeter** [comment]
@Sieberkev  am going to 127.0.0.1:8000

**Comment by langerhans** [comment]
You have to move the windows around...

**Comment by swtrpeter** [comment]
![screen](https://cloud.githubusercontent.com/assets/20620293/17278048/5101c3ce-5718-11e6-9722-f07f4c3a9ac9.PNG)

Thats all I get @Sieberkev

**Comment by swtrpeter** [comment]
I think I have it figured out @Sieberkev . Does it show pokemon on the map also ?

**Comment by Sieberkev** [comment]
The pokestops and the pokemons, yes :-)

**Comment by swtrpeter** [comment]
okay I am not seeing any so I guess I need to change location

**Comment by swtrpeter** [comment]
@Sieberkev  How could i run this on host 0.0.0.0 to access from outside network ?

**Comment by langerhans** [comment]
It automatically runs on 0.0.0.0.

**Comment by swtrpeter** [comment]
Okay.. I try to access from different computer and it does not show anything but the GUI. It does not show any info

**Comment by langerhans** [comment]
Are you sure you are on the latest version?

**Comment by swtrpeter** [comment]
@langerhans I am using the 0.5.0 alpha build because I could get the other running so I had to use the pre built

**Comment by spantin** [comment]
@swtrpeter When you compile from source, are you using git clone to get the source or are you downloading the zip? I've noticed if I don't clone it and download the zip instead, then running "git submodule update --init --recursive" will give me that same "FATAL not git repository" error.

**Comment by swtrpeter** [comment]
@spantin Just tried what you told me and IT WORKED ! ! I really appreciate the help with this issue ! One other question I have though. I am trying to access this from outside my network. I have port forwarded the port but when the page loads it shows the gui but no information etc. Any ideas what could be causing this ?

**Comment by Sieberkev** [comment]
Did you forward both ports (8000 and 8001)?

**Comment by swtrpeter** [comment]
@Sieberkev  just forwarded both ports and that worked ! Thanks all of you for your help

**Comment by swtrpeter** [comment]
One more question for you folks.. What are the best config settings to catch higher level pokemon ?

**Comment by Rofii** [comment]
@swtrpeter That depends on what you consider higher level. I use this but I'm almost level 30.

```
desired_catch_probability=0.6
desired_catch_probability_unwanted=0.4
transfer_cp_threshold=600
```
