### ISSUE TITLE
ENCOUNTER_ALREADY_HAPPENED 5 times for each pokemon

### ISSUE THREAD

**Issue by vamirineni87** [jabbink/PokemonGoBot#688]
**Description:**
`Just checked out latest develop. The latest commit tried to fix an issue with multi threading where distributed locks are preventing catching pokemon. Now that issues is fixed, but instead the bot tries to catch the same Pokemon 5 times`

**Steps to reproduce:**
`1. Graddle run`

**Expected behavior:**
[Catch pokemon]

**Actual behavior:**
`[ENCOUNTER_ALREADY_HAPPENED 5 times for each pokemon]`

**Stacktrace (If it's a crash):**
`
13:00:22.230 [QUIET] [system.out]  Stamina: 12 | Attack: 14 | Defense: 2 | IV: 28 (62%)
13:00:22.282 [QUIET] [system.out] 31 Jul 13:00:22: Wrote export.
13:00:22.282 [QUIET] [system.out] 31 Jul 13:00:22: Getting initial pokestops...
13:00:22.649 [QUIET] [system.out] 31 Jul 13:00:22: Got 97 pokestops
13:00:23.153 [QUIET] [system.out] 31 Jul 13:00:23: Walking to (38.898495000000004, -77.027619) in 121.813340413203 steps.
13:00:23.558 [QUIET] [system.out] 31 Jul 13:00:23: Profile update: 1082383 XP on LVL 26; 182383/200000 (91.19%) to LVL 27
13:00:23.564 [QUIET] [system.out] 31 Jul 13:00:23: XP gain: 0 XP; Pokemon caught/transferred: 0/0; Items caught/dropped: 0/0;
Pokebank 176/250; Stardust 5086; Inventory 265/350
13:00:24.414 [QUIET] [system.out] 31 Jul 13:00:24: Wrote export.
13:00:43.328 [QUIET] [system.out] 31 Jul 13:00:43: Looting nearby pokestop 53cb3e08d8d24a3fbda60ed5e62e0fab.16
13:00:44.226 [QUIET] [system.out] 31 Jul 13:00:44: Looted pokestop 53cb3e08d8d24a3fbda60ed5e62e0fab.16; +50 XP
13:00:47.508 [QUIET] [system.out] 31 Jul 13:00:47: Destination reached.
13:00:47.819 [QUIET] [system.out] 31 Jul 13:00:47: Looting nearby pokestop 21ecb8b975ac4b09b484bb4438789deb.16
13:00:49.037 [QUIET] [system.out] 31 Jul 13:00:49: Looted pokestop 21ecb8b975ac4b09b484bb4438789deb.16; +50 XP
13:00:49.446 [QUIET] [system.out] 31 Jul 13:00:49: Walking to (38.897623, -77.027194) in 136.37264101696962 steps.
13:01:08.061 [QUIET] [system.out] 31 Jul 13:01:08: Found pokemon SPEAROW
13:01:08.899 [QUIET] [system.out] 31 Jul 13:01:08: Pausing to catch pokemon...
13:01:08.901 [QUIET] [system.out] 31 Jul 13:01:08: Found pokemon SPEAROW
13:01:08.923 [QUIET] [system.out] 31 Jul 13:01:08: Encountered pokemon SPEAROW with CP 300 and IV 60%
13:01:08.924 [QUIET] [system.out] 31 Jul 13:01:08: Using desired_catch_probability_unwanted because CP < 600 and IV < 86%
13:01:08.925 [QUIET] [system.out] 31 Jul 13:01:08: Using ITEM_POKE_BALL; achieved catch probability: 0.36311305, desired: 0.3
13:01:09.547 [QUIET] [system.out] 31 Jul 13:01:09: Error running loop BotLoop!
13:01:09.548 [ERROR] [system.err] java.lang.NullPointerException
13:01:09.550 [QUIET] [system.out] 31 Jul 13:01:09: Encountered pokemon SPEAROW with CP 300 and IV 60%
13:01:09.551 [ERROR] [system.err]       at com.pokegoapi.api.map.pokemon.CatchResult.getStatus(CatchResult.java:45)
13:01:09.551 [QUIET] [system.out] 31 Jul 13:01:09: Using desired_catch_probability_unwanted because CP < 600 and IV < 86%
13:01:09.551 [QUIET] [system.out] 31 Jul 13:01:09: Using ITEM_POKE_BALL; achieved catch probability: 0.36311305, desired: 0.3
13:01:09.551 [ERROR] [system.err]       at ink.abb.pogo.scraper.util.pokemon.CatchablePokemonKt.catch(CatchablePokemon.kt:45)
13:01:09.551 [ERROR] [system.err]       at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:62)
13:01:09.551 [ERROR] [system.err]       at ink.abb.pogo.scraper.Bot.task(Bot.kt:201)
13:01:09.551 [ERROR] [system.err]       at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:123)
13:01:09.551 [ERROR] [system.err]       at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:34)
13:01:09.551 [ERROR] [system.err]       at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:163)
13:01:09.551 [ERROR] [system.err]       at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:34)
13:01:09.551 [ERROR] [system.err]       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
13:01:10.620 [QUIET] [system.out] 31 Jul 13:01:10: Caught a SPEAROW with CP 300 and IV 60%
13:01:10.626 [QUIET] [system.out]  Stamina: 5 | Attack: 13 | Defense: 9 | IV: 27 (60%): [200x XP, 3x Candy, 100x Stardust]
13:01:10.626 [QUIET] [system.out] 31 Jul 13:01:10: Pausing to catch pokemon...
13:01:10.626 [QUIET] [system.out] 31 Jul 13:01:10: Found pokemon SPEAROW
13:01:11.100 [QUIET] [system.out] 31 Jul 13:01:11: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:01:11.104 [QUIET] [system.out] 31 Jul 13:01:11: Pausing to catch pokemon...
13:01:11.104 [QUIET] [system.out] 31 Jul 13:01:11: Found pokemon SPEAROW
13:01:11.584 [QUIET] [system.out] 31 Jul 13:01:11: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:01:11.588 [QUIET] [system.out] 31 Jul 13:01:11: Pausing to catch pokemon...
13:01:11.588 [QUIET] [system.out] 31 Jul 13:01:11: Found pokemon SPEAROW
13:01:12.060 [QUIET] [system.out] 31 Jul 13:01:12: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:01:12.067 [QUIET] [system.out] 31 Jul 13:01:12: Pausing to catch pokemon...
13:01:12.067 [QUIET] [system.out] 31 Jul 13:01:12: Found pokemon SPEAROW
13:01:12.558 [QUIET] [system.out] 31 Jul 13:01:12: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:01:12.561 [QUIET] [system.out] 31 Jul 13:01:12: Pausing to catch pokemon...
13:01:12.561 [QUIET] [system.out] 31 Jul 13:01:12: Found pokemon SPEAROW
13:01:13.060 [QUIET] [system.out] 31 Jul 13:01:13: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:01:13.063 [QUIET] [system.out] 31 Jul 13:01:13: Pausing to catch pokemon...
13:01:13.063 [QUIET] [system.out] 31 Jul 13:01:13: Found pokemon SPEAROW
13:01:13.934 [QUIET] [system.out] 31 Jul 13:01:13: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:01:13.943 [QUIET] [system.out] 31 Jul 13:01:13: Dropped 1x ITEM_GREAT_BALL
13:01:13.944 [QUIET] [system.out] 31 Jul 13:01:13: Going to transfer SPEAROW with CP 300 and IV 60%; reason: CP < 600 and IV < 86%
13:01:17.810 [QUIET] [system.out] 31 Jul 13:01:17: Looting nearby pokestop a8825e3e1fdd4c4086be35e5f01298ab.12
13:01:18.792 [QUIET] [system.out] 31 Jul 13:01:18: Looted pokestop a8825e3e1fdd4c4086be35e5f01298ab.12; +50 XP
13:01:21.960 [QUIET] [system.out] 31 Jul 13:01:21: Destination reached.
13:01:23.489 [QUIET] [system.out] 31 Jul 13:01:23: Walking to (38.898434, -77.025518) in 224.70146450823373 steps.
13:01:43.076 [QUIET] [system.out] 31 Jul 13:01:43: Looting nearby pokestop 2ac7005159e74b2eae333f4b28d24d80.16
13:01:44.190 [QUIET] [system.out] 31 Jul 13:01:44: Looted pokestop 2ac7005159e74b2eae333f4b28d24d80.16; +50 XP
13:02:03.078 [QUIET] [system.out] 31 Jul 13:02:03: Looting nearby pokestop 77e734e5e97347f6893578fa52f58a96.16
13:02:03.960 [QUIET] [system.out] 31 Jul 13:02:03: Looted pokestop 77e734e5e97347f6893578fa52f58a96.16; +50 XP
13:02:08.432 [QUIET] [system.out] 31 Jul 13:02:08: Destination reached.
13:02:13.299 [QUIET] [system.out] 31 Jul 13:02:13: Walking to (38.898257, -77.0238) in 196.9757625445638 steps.
13:02:22.915 [QUIET] [system.out] 31 Jul 13:02:22: Looting nearby pokestop c0c5a2a6270740bf97424c4aa4a1dfdf.16
13:02:23.858 [QUIET] [system.out] 31 Jul 13:02:23: Looted pokestop c0c5a2a6270740bf97424c4aa4a1dfdf.16; +50 XP
13:02:48.080 [QUIET] [system.out] 31 Jul 13:02:48: Found pokemon PIDGEY
13:02:48.566 [QUIET] [system.out] 31 Jul 13:02:48: Encountered pokemon PIDGEY with CP 305 and IV 42%
13:02:48.571 [QUIET] [system.out] 31 Jul 13:02:48: Using desired_catch_probability_unwanted because Obligatory transfer
13:02:48.571 [QUIET] [system.out] 31 Jul 13:02:48: Using ITEM_POKE_BALL; achieved catch probability: 0.34347802, desired: 0.3
13:02:48.614 [QUIET] [system.out] 31 Jul 13:02:48: Pausing to catch pokemon...
13:02:48.614 [QUIET] [system.out] 31 Jul 13:02:48: Found pokemon PIDGEY
13:02:49.104 [QUIET] [system.out] 31 Jul 13:02:49: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:02:49.108 [QUIET] [system.out] 31 Jul 13:02:49: Pausing to catch pokemon...
13:02:49.108 [QUIET] [system.out] 31 Jul 13:02:49: Found pokemon PIDGEY
13:02:49.582 [QUIET] [system.out] 31 Jul 13:02:49: Caught a PIDGEY with CP 305 and IV 42%
13:02:49.588 [QUIET] [system.out]  Stamina: 14 | Attack: 3 | Defense: 2 | IV: 19 (42%): [200x XP, 3x Candy, 100x Stardust]
13:02:49.589 [QUIET] [system.out] 31 Jul 13:02:49: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:02:49.589 [QUIET] [system.out] 31 Jul 13:02:49: Pausing to catch pokemon...
13:02:49.589 [QUIET] [system.out] 31 Jul 13:02:49: Found pokemon PIDGEY
13:02:50.134 [QUIET] [system.out] 31 Jul 13:02:50: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:02:50.137 [QUIET] [system.out] 31 Jul 13:02:50: Pausing to catch pokemon...
13:02:50.137 [QUIET] [system.out] 31 Jul 13:02:50: Found pokemon PIDGEY
13:02:50.137 [QUIET] [system.out] 31 Jul 13:02:50: Dropped 2x ITEM_POKE_BALL
13:02:50.934 [QUIET] [system.out] 31 Jul 13:02:50: Dropped 5x ITEM_GREAT_BALL
13:02:50.940 [QUIET] [system.out] 31 Jul 13:02:50: Going to transfer PIDGEY with CP 305 and IV 42%; reason: Obligatory transfer
13:02:50.940 [QUIET] [system.out] 31 Jul 13:02:50: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:02:50.940 [QUIET] [system.out] 31 Jul 13:02:50: Pausing to catch pokemon...
13:02:50.940 [QUIET] [system.out] 31 Jul 13:02:50: Found pokemon PIDGEY
13:02:51.546 [QUIET] [system.out] 31 Jul 13:02:51: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:02:51.552 [QUIET] [system.out] 31 Jul 13:02:51: Pausing to catch pokemon...
13:02:51.552 [QUIET] [system.out] 31 Jul 13:02:51: Found pokemon PIDGEY
13:02:52.031 [QUIET] [system.out] 31 Jul 13:02:52: Looting nearby pokestop f7fbcb3fb1064102b3d81939a0fc97f7.16
13:02:52.038 [QUIET] [system.out] 31 Jul 13:02:52: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:02:52.038 [QUIET] [system.out] 31 Jul 13:02:52: Pausing to catch pokemon...
13:02:52.038 [QUIET] [system.out] 31 Jul 13:02:52: Found pokemon PIDGEY
13:02:52.576 [QUIET] [system.out] 31 Jul 13:02:52: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:02:52.579 [QUIET] [system.out] 31 Jul 13:02:52: Pausing to catch pokemon...
13:02:52.579 [QUIET] [system.out] 31 Jul 13:02:52: Found pokemon PIDGEY
13:02:53.085 [QUIET] [system.out] 31 Jul 13:02:53: Looted pokestop f7fbcb3fb1064102b3d81939a0fc97f7.16; +50 XP
13:02:53.092 [QUIET] [system.out] 31 Jul 13:02:53: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:02:53.092 [QUIET] [system.out] 31 Jul 13:02:53: Pausing to catch pokemon...
13:02:53.092 [QUIET] [system.out] 31 Jul 13:02:53: Found pokemon PIDGEY
13:02:53.589 [QUIET] [system.out] 31 Jul 13:02:53: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:02:57.605 [QUIET] [system.out] 31 Jul 13:02:57: Destination reached.
13:02:58.645 [QUIET] [system.out] 31 Jul 13:02:58: Walking to (38.898334, -77.023188) in 70.52371982825942 steps.
13:03:08.263 [QUIET] [system.out] 31 Jul 13:03:08: Found pokemon WEEDLE
13:03:08.679 [QUIET] [system.out] 31 Jul 13:03:08: Pausing to catch pokemon...
13:03:08.683 [QUIET] [system.out] 31 Jul 13:03:08: Found pokemon WEEDLE
13:03:08.740 [QUIET] [system.out] 31 Jul 13:03:08: Encountered pokemon WEEDLE with CP 81 and IV 17%
13:03:08.740 [QUIET] [system.out] 31 Jul 13:03:08: Using desired_catch_probability_unwanted because CP < 600 and IV < 86%
13:03:08.740 [QUIET] [system.out] 31 Jul 13:03:08: Using ITEM_POKE_BALL; achieved catch probability: 0.5005415, desired: 0.3
13:03:09.279 [QUIET] [system.out] 31 Jul 13:03:09: Encountered pokemon WEEDLE with CP 81 and IV 17%
13:03:09.286 [QUIET] [system.out] 31 Jul 13:03:09: Using desired_catch_probability_unwanted because CP < 600 and IV < 86%
13:03:09.286 [QUIET] [system.out] 31 Jul 13:03:09: Using ITEM_POKE_BALL; achieved catch probability: 0.5005415, desired: 0.3
13:03:09.756 [QUIET] [system.out] 31 Jul 13:03:09: Caught a WEEDLE with CP 81 and IV 17%
13:03:09.759 [QUIET] [system.out]  Stamina: 8 | Attack: 0 | Defense: 0 | IV: 8 (17%): [200x XP, 3x Candy, 100x Stardust]
13:03:10.233 [QUIET] [system.out] 31 Jul 13:03:10: Dropped 2x ITEM_POKE_BALL
13:03:10.236 [QUIET] [system.out] 31 Jul 13:03:10: Capture of WEEDLE failed with status : CATCH_FLEE
13:03:10.236 [QUIET] [system.out] 31 Jul 13:03:10: Pausing to catch pokemon...
13:03:10.236 [QUIET] [system.out] 31 Jul 13:03:10: Found pokemon WEEDLE
13:03:10.236 [QUIET] [system.out] 31 Jul 13:03:10: Going to transfer WEEDLE with CP 81 and IV 17%; reason: CP < 600 and IV < 86%
13:03:10.852 [QUIET] [system.out] 31 Jul 13:03:10: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:03:10.856 [QUIET] [system.out] 31 Jul 13:03:10: Pausing to catch pokemon...
13:03:10.856 [QUIET] [system.out] 31 Jul 13:03:10: Found pokemon WEEDLE
13:03:11.340 [QUIET] [system.out] 31 Jul 13:03:11: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:03:11.344 [QUIET] [system.out] 31 Jul 13:03:11: Pausing to catch pokemon...
13:03:11.344 [QUIET] [system.out] 31 Jul 13:03:11: Found pokemon WEEDLE
13:03:11.344 [QUIET] [system.out] 31 Jul 13:03:11: Looting nearby pokestop bc2291929df04672ab985b217fd42f14.12
13:03:11.889 [QUIET] [system.out] 31 Jul 13:03:11: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:03:11.895 [QUIET] [system.out] 31 Jul 13:03:11: Pausing to catch pokemon...
13:03:11.895 [QUIET] [system.out] 31 Jul 13:03:11: Found pokemon WEEDLE
13:03:12.369 [QUIET] [system.out] 31 Jul 13:03:12: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:03:12.375 [QUIET] [system.out] 31 Jul 13:03:12: Pausing to catch pokemon...
13:03:12.375 [QUIET] [system.out] 31 Jul 13:03:12: Found pokemon WEEDLE
13:03:12.375 [QUIET] [system.out] 31 Jul 13:03:12: Looted pokestop bc2291929df04672ab985b217fd42f14.12; +50 XP
13:03:12.847 [QUIET] [system.out] 31 Jul 13:03:12: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:03:12.855 [QUIET] [system.out] 31 Jul 13:03:12: Pausing to catch pokemon...
13:03:12.855 [QUIET] [system.out] 31 Jul 13:03:12: Found pokemon WEEDLE
13:03:13.354 [QUIET] [system.out] 31 Jul 13:03:13: Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED
13:03:17.367 [QUIET] [system.out] 31 Jul 13:03:17: Destination reached.
13:03:18.751 [QUIET] [system.out] 31 Jul 13:03:18: Walking to (38.898632, -77.023742) in 76.97929622533377 steps.
13:03:28.375 [QUIET] [system.out] 31 Jul 13:03:28: Looting nearby pokestop 87d0ca7b86254e24abe212313600f5ec.12
13:03:29.359 [QUIET] [system.out] 31 Jul 13:03:29: Looted pokestop 87d0ca7b86254e24abe212313600f5ec.12; +100 XP
13:03:34.010 [QUIET] [system.out] 31 Jul 13:03:34: Destination reached.
13:03:38.708 [QUIET] [system.out] 31 Jul 13:03:38: Walking to (38.897445, -77.02371) in 173.61013290996198 steps.
13:04:08.264 [QUIET] [system.out] 31 Jul 13:04:08: Looting nearby pokestop fd9af9c6fd2e4e89916991c11bc81e74.12
13:04:09.158 [QUIET] [system.out] 31 Jul 13:04:09: Looted pokestop fd9af9c6fd2e4e89916991c11bc81e74.12; +50 XP
13:04:13.455 [QUIET] [system.out] 31 Jul 13:04:13: Found pokemon EEVEE
13:04:13.461 [QUIET] [system.out] 31 Jul 13:04:13: Pausing to catch pokemon...
13:04:13.461 [QUIET] [system.out] 31 Jul 13:04:13: Found pokemon EEVEE
13:04:14.002 [QUIET] [system.out] 31 Jul 13:04:14: Encountered pokemon EEVEE with CP 441 and IV 75%
13:04:14.006 [QUIET] [system.out] 31 Jul 13:04:14: Encountered pokemon EEVEE with CP 441 and IV 75%
13:04:14.587 [QUIET] [system.out] 31 Jul 13:04:14: Using ITEM_GREAT_BALL; Using Razz Berry; Using curve; achieved catch probability: 0.62589836, desired: 0.6
13:04:15.955 [QUIET] [system.out] 31 Jul 13:04:15: Caught a EEVEE with CP 441 and IV 75%
13:04:15.958 [QUIET] [system.out]  Stamina: 7 | Attack: 15 | Defense: 12 | IV: 34 (75%): [210x XP, 3x Candy, 100x Stardust]
13:04:16.470 [QUIET] [system.out] 31 Jul 13:04:16: Dropped 1x ITEM_POTION
13:04:16.938 [QUIET] [system.out] 31 Jul 13:04:16: Dropped 8x ITEM_POKE_BALL
> Building 92% > :run
`

**Version:**
`
Self Compiled - commit c59916e5bf0e0d875a9042565a72fb9e8c35923d
Author: pashorizer <samantoo@web.de>
`

**Operating System:**
[windows 10 / Ubuntu - tried on both]

**Java version:**
[jdk 1.8.10`]

**Comment by langerhans** [comment]
Known issue. This should be fixed on the latest api upstream changes. Will pull them over as soon as it's confirmed to fix this.

**Comment by pashorizer** [comment]
Fixed with https://github.com/jabbink/PokemonGoBot/pull/691

**Comment by fabioneves** [comment]
Thanks, testing this now!

**Comment by langerhans** [comment]
Fixed with #691 and #692
