### ISSUE TITLE
[Question] What is the "gui_port_socker" for?

### ISSUE THREAD

**Issue by casper-gh** [jabbink/PokemonGoBot#689]
I can open the GUI on the port I specified in `gui_port`, but what is `gui_port_socket` for?

Please excuse my networking stupidity.

**Comment by citruz** [comment]
`gui_port_socket` is for the Websocket which is used to pass data from the Server to the GUI.

**Comment by vamirineni87** [comment]
There is a webbased UI to check the log. for example, if I host of amazon ec2, i dont need to login to the console everytime to check the status. I can just check the webui.

**Comment by langerhans** [comment]
It's the Socket.io server port that feeds the data to the GUI. Due to the way this was implemented it has to run on a different port.

**Comment by Sieberkev** [comment]
Your browser will get the data it needs from the socket port.

If you run multiple bots on one computer you would have to input a unique portnumber for each bot (this is why it is in the config).

**Comment by casper-gh** [comment]
@Sieberkev so specify 2 ports for each bot? Can I only set `gui_port` and disable `gui_port_socket`? (ie, set it to 0)

**Comment by casper-gh** [comment]
Oh nvm I got it, sorry guys for my stupid question

**Comment by qifbox** [comment]
How can i open the GUI?

**Comment by Sieberkev** [comment]
You have to visit [http://localhost:8000/](http://localhost:8000/) in your browser when the bot is running

**Comment by Spiritwolf213** [comment]
and how do you setup a unique port? so you can run multiple bots at the same time

**Comment by Sieberkev** [comment]
In the configuration file:

> # Port where the webserver (gui) should listen, 0 = do not listen
> gui_port=8000
> # Port where the socketserver should listen, 0 = do not listen
> gui_port_socket=8001

**Comment by Spiritwolf213** [comment]
any specific numbers you need to fill in?

**Comment by Sieberkev** [comment]
No, just be sure you aren't using ports that are possible in use yet :) When they are in use you will get an error on startup so you know you have to change the number

**Comment by jabbink** [comment]
Fyi: updated and now only a socket port is specified.
