### ISSUE TITLE
"Pausing to catch pokemon" loop

### ISSUE THREAD

**Issue by Leodenact** [jabbink/PokemonGoBot#694]
It's pausing to catch pokemon all the time, just looping and nothing happens.. What's this?

**Comment by Sieberkev** [comment]
What version of the bot are you using? (JAR, what version? build from development branch, what commit?)

**Comment by Leodenact** [comment]
I downloaded the latest release

**Comment by Leodenact** [comment]
31 jul 21:18:10: Walking to (55.701847, 13.192762) in 125.4716553693016 steps.
31 jul 21:18:13: Pausing to catch pokemon...
31 jul 21:18:14: Getting map of (55.701573242689776, 13.19369200060931)
←[33;1m31 jul 21:18:15: Dropped 1x ITEM_REVIVE ←[0m
←[33;1m31 jul 21:18:16: Dropped 1x ITEM_POTION ←[0m
31 jul 21:18:17: Pausing to catch pokemon...
31 jul 21:18:19: Getting map of (55.70162715824246, 13.193650905303175)
31 jul 21:18:21: Pausing to catch pokemon...
31 jul 21:18:24: Getting map of (55.70157087468139, 13.193603412503636)
31 jul 21:18:26: Pausing to catch pokemon...
31 jul 21:18:29: Getting map of (55.70161958824013, 13.193535767036463)
31 jul 21:18:29: Pausing to catch pokemon...
31 jul 21:18:31: Looting nearby pokestop 23c4272975b0441799fa3c8477acd4d2.16
←[32;1m31 jul 21:18:32: Looted pokestop 23c4272975b0441799fa3c8477acd4d2.16; +50
 XP: [2xITEM_POKE_BALL, 1xITEM_GREAT_BALL] ←[0m
31 jul 21:18:33: Pausing to catch pokemon...
31 jul 21:18:34: Getting map of (55.701576328480556, 13.193584982813011)
31 jul 21:18:37: Pausing to catch pokemon...
31 jul 21:18:39: Getting map of (55.70166484673772, 13.193479970220709)
31 jul 21:18:41: Pausing to catch pokemon...
31 jul 21:18:44: Getting map of (55.70163419520448, 13.193402461878504)
31 jul 21:18:46: Pausing to catch pokemon...
31 jul 21:18:49: Getting map of (55.70166370512263, 13.193416064688233)
31 jul 21:18:49: Pausing to catch pokemon...
31 jul 21:18:53: Pausing to catch pokemon...

**Comment by pashorizer** [comment]
This is fixed in the newest commits on `develop`

**Comment by Leodenact** [comment]
How to get that one? I downloaded the latest source (from the code site), still didn't work. Still pausing to catch the pokemon. Any ideas?

**Comment by pashorizer** [comment]
@Leodenact A new release is on the way

**Comment by Leodenact** [comment]
When will it be released? Like now or tomorrow? :)

**Comment by Sieberkev** [comment]
Few minutes from now :)

**Comment by Leodenact** [comment]
Woaah I'm excited :dancer:

**Comment by langerhans** [comment]
Should be fixed in alpha 4 :)
