### ISSUE TITLE
Google Login Invalid Credentials

### ISSUE THREAD

**Issue by Evuse** [jabbink/PokemonGoBot#696]
Hello, i'm using Pokemon Go Bot v0.5.0 alpha 3 on my 2 Google Login Pokemon Go accounts.

The problem is that one google account works perfectly, the other google account gives me back this error when i try to launch the bot:

java -jar pogo.scraper-all-0.5.0-alpha3.jar 
31 Jul 21:17:57: Logging in to game server...
31 Jul 21:17:59: Server refused your login credentials. Are they correct? 

I am SUPER sure that credentials are correct because:
- I can login into my google account
- I can login on my pokemon google account from mobile.

What should i do?

The configuration between the 2 google accounts is exactly the same but one works and the other doesn't work. 

I'm running Pokemon Go Bot v0.5.0 alpha 3 on Debian with Java version "1.8.0_101".

If i can provide more info let me know. Thanks for your attention and for your time.

**Comment by Yayt** [comment]
do you use 2fa?

**Comment by Evuse** [comment]
No, i have not 2 factor auth :(

<img width="614" alt="schermata 2016-07-31 alle 21 39 06" src="https://cloud.githubusercontent.com/assets/20630600/17278851/4dfebd18-5767-11e6-895c-0ed10306c026.png">

**Comment by Killertom63** [comment]
I'm having the same issue, but with Pokemon account. Worked fine, then I restarted the bot. Still can login on my mobile.

**Comment by langerhans** [comment]
We had several of these now, so clsoing as duplicate. Check #583 for possible solutions.
