### ISSUE TITLE
No info in GUI web

### ISSUE THREAD

**Issue by aleixsb** [jabbink/PokemonGoBot#699]
**Description:**
After I run the bot, I can open the web GUI but no info is in there. I can only see the boxes but all of them are empty.

http://imgur.com/5Ksoiiy

**Steps to reproduce:**

Follow all steps in the Readme with the last versions alpha03

**Expected behavior:**
See some info in the web server

**Actual behavior:**
Only see the boxes but without any info

**Version:**
Last version available (alpha03) selfcompiled 

**Operating System:**
Ubuntu 16.04

**Java version:**
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by pashorizer** [comment]
Don't close the cmd/terminal after you started it

**Comment by aleixsb** [comment]
I don't close the terminal the bot is running when i'm getting that web page. In fact, I run the bot in screen so it keeps runing in background

**Comment by langerhans** [comment]
Try checking the browser developer console for any errors. Make sure the socket port is accessible in your firewall. By default it's 8001.

**Comment by aleixsb** [comment]
I'm using ngrok in order to access it..

I'm getting this errors in the browser developer console:
![image](https://cloud.githubusercontent.com/assets/5330902/17279359/26edf8a0-5772-11e6-83d1-4be9af7eee35.png)

It's maybe ngrok problem related?

**Comment by aleixsb** [comment]
Ok so it's because ngrok.
