### ISSUE TITLE
Randomly miss a throw every so often.

### ISSUE THREAD

**Issue by wartickler** [jabbink/PokemonGoBot#70]
I understand that the code throws perfect curve balls to the dead center every time. That's cool, though I sometimes mess those up and end up throwing a straight that misses. Sometimes I even miss straight throws when I play on the client. Shouldn't I miss here too? Maybe make a small, random margin of error in each toss that might miss to the top, left, bottom, or right every so often?

**Comment by daveystruijk** [comment]
The API already does [some randomization](https://github.com/Grover-c13/PokeGOAPI-Java/blob/master/src/main/java/com/pokegoapi/api/map/pokemon/CatchablePokemon.java#L166) by itself. You can easily replace [this line](https://github.com/jabbink/PokemonGoBot/blob/master/src/main/kotlin/ink/abb/pogo/scraper/tasks/CatchOneNearbyPokemon.kt#L51) with whatever margin you like. :)

I'm more worried about the timing between encounters though. Catching a couple of pokemon within seconds seems like a good way to get banned.

**Comment by jabbink** [comment]
Implemented some time ago with the desired catch rate thing.
