### ISSUE TITLE
unable to access jarfile

### ISSUE THREAD

**Issue by edwincheung555** [jabbink/PokemonGoBot#701]
im on Mac terminal and whenever i type in java -jar pogo.scraper-all-0.5.0-alpha3.jar, all it gives me is "unable to access jarfile"

**Comment by Sieberkev** [comment]
Make sure you are working in the directory where the jar file is located before running the java command :)

**Comment by langerhans** [comment]
The issue template is there for a reason and that is certainly not to delete it. Provide the required info and we might be able to help you  ;)

**Comment by edwincheung555** [comment]
**Description:**
im on Mac terminal and whenever i type in java -jar pogo.scraper-all-0.5.0-alpha3.jar, all it gives me is "unable to access jarfile"

**Steps to reproduce:**

1. Download Java 1.8
2. Download all files necessary
3. rename config.properties.template to config.properties
4.fill in all of the blanks
5.opened the terminal and typed in  java -jar pogo.scraper-all-0.5.0-alpha3.jar

**Expected behavior:**
Should've worked, but didnt

**Actual behavior:**
get "unable to access jarfile java -jar pogo.scraper-all-0.5.0-alpha3.jar"



**Version:**
[The version of the bot you used; when self-compiled: :exclamation: the commit hash 
Version 0.5.0 alpha3

**Operating System:**
[Your operating system]
Mac OSX El Capitan v10.11.05
**Java version:**
[Full output of `java -version`]
1.8.0_101

**Comment by langerhans** [comment]
If you open the Terminal.app and just type the command you won#t be in the right directory. If you for example saved the jar file in your Downloads directory, first type ``cd ~/Downloads` in your terminal.

**Comment by edwincheung555** [comment]
whoa, okay thanks, it worked. But now all im getting is got 0 pokestops retrying in 10 seconds. Is it just that the coordinates i put has no pokestops in it?

**Comment by langerhans** [comment]
Could be the issue. There is another one tracking that already tho, so I'll close here. see #686
