### ISSUE TITLE
Is evolve possible yet?

### ISSUE THREAD

**Issue by Leodenact** [jabbink/PokemonGoBot#702]
A week ago I read that developers here had working evolving scripts, but still it isn't in the bundle release. Maybe someone knows if there are files for it here and if it's possible?

**Comment by Sieberkev** [comment]
There is a PR WIP #444

**Comment by Killertom63** [comment]
Can't you just login to your mobile, or tablet and evolve everything you want?

**Comment by Sieberkev** [comment]
Where would be the fun in doing THAT? :D

**Comment by Rofii** [comment]
@Leodenact Please close this issue. Thanks :)
