### ISSUE TITLE
gradlew build or clean build  failed

### ISSUE THREAD

**Issue by junjun4747** [jabbink/PokemonGoBot#703]
in terminal i can't get around with step 3 always gave me the error

:clean UP-TO-DATE
:PokeGOAPI-Java:clean UP-TO-DATE
:PokeGOAPI-Java:extractIncludeProto
:PokeGOAPI-Java:extractProto
:PokeGOAPI-Java:generateProto
:PokeGOAPI-Java:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:PokeGOAPI-Java:processResources
:PokeGOAPI-Java:classes
:PokeGOAPI-Java:jar
:compileKotlin
e: /Users/jun/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Bot.kt: (79, 66): Unresolved reference: thenComparing
e: /Users/jun/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Settings.kt: (105, 103): Unresolved reference: Base64
e: /Users/jun/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Settings.kt: (215, 14): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun CharSequence.lines(): List<String> defined in kotlin.text
e: /Users/jun/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Settings.kt: (215, 22): Cannot choose among the following candidates without completing type inference: 
@HidesMembers public inline fun <T> Iterable<???>.forEach(action: (???) -> Unit): Unit defined in kotlin.collections
@HidesMembers public inline fun <K, V> Map<???, ???>.forEach(action: (Map.Entry<???, ???>) -> Unit): Unit defined in kotlin.collections
e: /Users/jun/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Settings.kt: (216, 17): Unresolved reference: it
e: /Users/jun/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Settings.kt: (216, 31): Unresolved reference: it
e: /Users/jun/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Settings.kt: (219, 24): Unresolved reference: it
e: /Users/jun/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Settings.kt: (220, 37): Unresolved reference: it
e: /Users/jun/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/gui/WebServer.kt: (21, 18): Unresolved reference: stream
e: /Users/jun/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/gui/WebServer.kt: (40, 22): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun CharSequence.lines(): List<String> defined in kotlin.text
e: /Users/jun/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/gui/WebServer.kt: (40, 38): Unresolved reference: Collectors
e: /Users/jun/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/tasks/Export.kt: (87, 74): Unresolved reference: thenComparing
e: /Users/jun/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/util/directions/RouteRequest.kt: (26, 45): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun CharSequence.lines(): List<String> defined in kotlin.text
e: /Users/jun/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/util/directions/RouteRequest.kt: (26, 53): Cannot choose among the following candidates without completing type inference: 
@HidesMembers public inline fun <T> Iterable<???>.forEach(action: (???) -> Unit): Unit defined in kotlin.collections
@HidesMembers public inline fun <K, V> Map<???, ???>.forEach(action: (Map.Entry<???, ???>) -> Unit): Unit defined in kotlin.collections
e: /Users/jun/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/util/directions/RouteRequest.kt: (27, 24): Unresolved reference: it
e: /Users/jun/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/util/io/CSVWriter.kt: (15, 18): Unresolved reference: StringJoiner
e: /Users/jun/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/util/io/CSVWriter.kt: (37, 18): Unresolved reference: StringJoiner
:compileKotlin FAILED
:PokeGOAPI-Java:bundle

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

i did some google.  i realized that it had no kotlin installed. then i followed the instructions online to get kotlin installed. but still im getting the same error "execution failed for task cmmpilekotlin.

**Comment by Sieberkev** [comment]
Use Oracle JDK 8 to build (you are using 7 now) :)

**Comment by langerhans** [comment]
Use JDK 8 as outlined in the Readme. If you wouldn't have deleted the issue template you'd have noticed it yourself ;)

**Comment by junjun4747** [comment]
im using mac. and i did follow the usage instructions in the README file. im also confused why it shows  e:/ , it does not exist. im using mac, do i have to make some modification with the git clone?
