### ISSUE TITLE
0 initial pokestops found. retrying in 10 seconds.

### ISSUE THREAD

**Issue by alkalisdad** [jabbink/PokemonGoBot#704]
**Description:**
0 initial pokestops found. retrying in 10 seconds.

**Steps to reproduce:**

**Expected behavior:**
Bot starts

**Actual behavior:**
Error message comes up 

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
5.0.4

**Operating System:**
[Your operating system]

**Java version:**
[Full output of `java -version`]

**Comment by Sieberkev** [comment]
Duplicate of #686

**Comment by langerhans** [comment]
Check your lat/lon. You probably mixed something up there.
