### ISSUE TITLE
Not catching any Pokemon.

### ISSUE THREAD

**Issue by hiren63** [jabbink/PokemonGoBot#705]
I am currently using the newest version of the bot. Although I'm not getting any errors or any crashes, it is doing something really weird, I don't know if it happens to anyone else. The problem is that it will catch a few Pokemon in a succession for about a minute and then it just goes around looking for pokestops for the next 5-6 minutes, without catching any Pokemon in the process.

**Comment by dvasko** [comment]
0.5.0 alpha4, everything works fine
