### ISSUE TITLE
Not Catching any pokemon

### ISSUE THREAD

**Issue by edwincheung555** [jabbink/PokemonGoBot#706]
**Description:**
Everything works fine, its running, its collecting pokestops. the only thing thats wrong is that so far, ive been running the bot for half an hour and i havent caught a single pokemon

**Steps to reproduce:**

1. have current settings http://pastebin.com/GTCtAuHw
2. run bot

**Expected behavior:**
should get pokemon

**Actual behavior:**
dont get any pokemon

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
0.5.0 alpha4

**Operating System:**
Mac OSX El Capitan v10.11.05

**Java version:**
1.8

**Comment by casper-gh** [comment]
Too much `speed=100`

Set it to default 2.8

**Comment by edwincheung555** [comment]
i had it at the default for around 20 minutes but it wasnt catching anything so i decided to bump it up. Ive also tried to go at a speed  of 1.5 but any speed i try, i still dont get any pokemon

**Comment by casper-gh** [comment]
What does the log look like? or the GUI?

Is it moving? Is it spinning pokestop still?

**Comment by edwincheung555** [comment]
http://pastebin.com/eRd094ZF
it is moving and spinning pokestops. everything is working fine except for the fact i havent gotten any pokemon ever since i tried it 2 hours ago

**Comment by casper-gh** [comment]
happened to me before latest update, I bumped up walk speed to 25 and it worked, but now i only set to 2.8 and still work.

Also looks like account is new? Did you open the game and catch the first pokemon?

**Comment by edwincheung555** [comment]
yes i did. and like i said, ive tried this with my other account which was level 20 and it still caught no pokemon, i have no idea how to fix it. im using the latest update of the bot

**Comment by tyman1292** [comment]
I know it sounds weird.. but also make sure your time on your computer is correctly synced with a webserver.

**Comment by edwincheung555** [comment]
and what exactly do you mean by that. like how do i correctly sync with a webserver?

**Comment by norecha** [comment]
I also have a similar issue. Pokemons are found extremely rare. Like couple/hr rare

**Comment by langerhans** [comment]
Those coordinates look a bit off. Are you sure this is where you expect that many pokemon? Try central park or santa monica bay to name just two.

**Comment by edwincheung555** [comment]
alright, ive tried a place like pier 39 in san Francisco and it works fine. also, ive decided to keep the default settings and change as least as possible, so maybe that will fix your problem, norecha

**Comment by russr123** [comment]
same for me, looking at the live map, 1 of 2 things will happen.
either he will catch 1 or 2 when it 1st spawns then no more after that,, or it will hit the 1st stop and get stuck and never move.
speeds checked from 1.5 to 8

**Comment by gabrielklein** [comment]
Avoid running the phone app when you run the bot... and if you use the app, the position in the app and the position in the bot should make sense (You cannot jump from one city to another in 5 minutes...)

**Comment by jabbink** [comment]
(or move with 100m/s)

**Comment by langerhans** [comment]
Well I guess this can be closed then.
