### ISSUE TITLE
[Question] Any way to view GUI on Iphone/Ipad safari?

### ISSUE THREAD

**Issue by casper-gh** [jabbink/PokemonGoBot#707]
I can drag and drop the boxes on a computer browser, but cannot on iphone/ipad browser (Chrome and Safari).

Did I miss something?

**Comment by SiriusCrypto** [comment]
I havent found a way yet, but i just watch the log on my iphone by typing in your computer's IP followed by port. Like: 1.1.1.1:8000 then i just click the log.

If anyone has a better way id love to find out as well lol

**Comment by Sawuasfoiythl** [comment]
I don't do much with the web side of development but there is a snippet (not entirely sure what to call it) of code that adds mobile support for standard mouse functions on jQuery. It's called jQuery UI Touch Punch (http://touchpunch.furf.com/). Perhaps someone with better knowledge on jQuery would like to implement this into the webserver's page.

**Comment by langerhans** [comment]
Not possible right now, but there are several open PRs to address this. #549 #710 for example.
