### ISSUE TITLE
Configure ip binding for webserver.

### ISSUE THREAD

**Issue by GenuineSounds** [jabbink/PokemonGoBot#708]
**Description:**
Add ip bindings to the InetSocketAdress constructor.

`val server = HttpServer.create(InetSocketAddress(ip, port), 0)`

https://github.com/jabbink/PokemonGoBot/blob/develop/src/main/kotlin/ink/abb/pogo/scraper/gui/WebServer.kt#L27

And all the necessary changes to the configs.

**Comment by smileytechguy** [comment]
?

**Comment by langerhans** [comment]
Yes, at the moment both bind to 0.0.0.0. I'd suggest handling that in your firewall for now. #622 will take care of that later down the line.

**Comment by Sieberkev** [comment]
The internal webserver has been removed and replaced by externally hosted pages.
