### ISSUE TITLE
[Feature] Transfer according to your candy count

### ISSUE THREAD

**Issue by norecha** [jabbink/PokemonGoBot#715]
If you have 120 pidgey candies and 20 pidgeys, keep top 10 of them(120/12) and transfer only 8 of them.
Reasoning: I save about 50 evolves lined up and pop a lucky egg and evolve all of them. Right now if I disable transferring, I will run out of poke space; if I enable it, I won't have anything left to evolve. Setting min to keep is not an option either since candy counts are different

**Comment by Killertom63** [comment]
You could plan ahead and just add a pidgey to the ignored_pokemon so you can keep them. Then you can level them up. :)

**Comment by kauegimenes** [comment]
Nice feature! +1

**Comment by Sieberkev** [comment]
Mass evolving (+ optional lucky egg) got implemented with #939
