### ISSUE TITLE
Encountered this morning bootloops and profileloops

### ISSUE THREAD

**Issue by Shazgul** [jabbink/PokemonGoBot#716]
**Description:**
I've encountered this morning bootloops and profileloops from 07:53 AM to 08:47 AM (GMT +1), was it maybe an Softban or Server down?
The error-messages came every 10 seconds.

**Steps to reproduce:**
Had run the Bot at the same time.

**Expected behavior:**
Normal straight botting.

**Actual behavior:**
01 Aug 07:53:06: Error running loop BotLoop! 
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url 
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
	at java.lang.Thread.run(Thread.java:745)
01 Aug 07:53:11: Getting map of (LATITUDE, LONGITUDE)
D/RequestHandler: Authenticated with static token

01 Aug 07:53:58: Failed to update profile and inventories 
D/RequestHandler: Authenticated with static token
01 Aug 07:53:58: Error running loop ProfileLoop! 
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url 
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
	at java.lang.Thread.run(Thread.java:745)
01 Aug 07:54:01: Getting map of (LATITUDE, LONGITUDE)
D/RequestHandler: Authenticated with static token

after this it just runs normal again...

01 Aug 08:48:01: Getting map of (LATITUDE, LONGITUDE)
D/RequestHandler: Authenticated with static token
01 Aug 08:48:02: Looting nearby pokestop POKESTOPHASH.11
01 Aug 08:48:03: Looted pokestop POKESTOPHASH.11; +50 XP: [1xITEM_RAZZ_BERRY, 3xITEM_POKE_BALL] 

**Version:**
pogo.scraper-all-0.5.0-alpha4.jar 

**Operating System:**
Ubuntu 16.04.

**Java version:**
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK Server VM (build 25.91-b14, mixed mode)

**Comment by svombergen** [comment]
#680 Seems like same issue.

**Comment by Shazgul** [comment]
Not really, it just came for me after about 5 Hours and didn't came again aftr this time.

**Comment by thegimliboy** [comment]
Same here.

**Comment by Sieberkev** [comment]
This is an issue in the external Java API: https://github.com/Grover-c13/PokeGOAPI-Java/issues/417

**Comment by ursalame** [comment]
Here's a script to start the bot, wait for some time, kill it and start it again:

Here's a little bash script that can help you:

```
#!/bin/bash
EXPR="java -jar pogo.scraper-all-0.5.0-alpha4.jar &"; 
WAIT_BEFORE_KILLING=50m;
WAIT_AFTER_KILL_TO_FORCE_KILL=30s;
WAIT_BEFORE_LOOPING=1m;

while true
do
	eval $EXPR;
	PID=$!;
	
	sleep $WAIT_BEFORE_KILLING;
	kill $PID;

	sleep $WAIT_AFTER_KILL_TO_FORCE_KILL;
	kill -9 $PID;
	
	sleep $WAIT_BEFORE_LOOPING;		
done
```

**Comment by jozsi** [comment]
Or a Windows Bat(ch) script:
```batch
@echo off
:loop
start C:\Users\jozsi\Dev\PokemonGoBot\gradlew.bat run
timeout /t 3600 >null
taskkill /f /im "java.exe" >null
timeout /t 30 >null
goto loop
```

**Comment by vamirineni87** [comment]
This kills all java programs. I modified it slightly to only kill the bot.

2 batch files:

Control batch:
``@echo off 
:loop
start runpogo.bat
timeout /t 3600
taskkill /f /FI "WINDOWTITLE eq pogoscrapper-vendeep" 
timeout /t 30
goto loop
``

Run batch:
`TITLE pogoscrapper
"C:\Program Files\Java\jre1.8.0_101\bin\java.exe" -jar pogo.scraper-all-0.5.0-alpha4.jar
pause`


btw, how  do you guys get the multiline code comments to work!!

**Comment by jozsi** [comment]
@vamirineni87: wrap it between triple backquotes and on a separate line:
![image](https://cloud.githubusercontent.com/assets/840815/17330539/d2f156fc-58cf-11e6-8558-b784daa79257.png)

**Comment by vamirineni87** [comment]
I also randomized my controller script. 
Run 15 - 30 mins, kill, wait 5 - 10 mins... Repeat

```
@echo off
TITLE pogoscrapper-tisukapalli-controller
:loop
start runpogo.bat
SET /A seconds=%RANDOM% * 900 / 32768 + 900
timeout /t %seconds%
taskkill /f /FI "WINDOWTITLE eq running-pogoscrapper-tisukapalli" /T
SET /A seconds=%RANDOM% * 300 / 32768 + 300
timeout /t %seconds%
goto loop
```

**Comment by jabbink** [comment]
API bug, should be fixed, also search before posting, please.
