### ISSUE TITLE
[Error] Pokestop out of range; distance: XY

### ISSUE THREAD

**Issue by Casual-User** [jabbink/PokemonGoBot#718]
**Description:**
Out of a sudden, all my bots found all Pokestops to be out of range.

**Steps to reproduce:**

First time encountered. All bots for around 4 Minutes

**Expected behavior:**
NOT that.

**Actual behavior:**
walking around, not getting XP from Pokestops without getting the usual soft ban messages

**Stacktrace (If it's a crash):**
see titel. No more info in stacktrace

**Version:**
precompiled Alpha.4

**Operating System:**
MacOSX

**Java version:**
latest

**Comment by Sieberkev** [comment]
I had something similar for a very short time (5 minutes) for 2 stops, then it fixed itself.

**Comment by Casual-User** [comment]
Yeah, one of my bots came back to life after 4 minutes. The others I had already restarted out of scepticism

**Comment by pashorizer** [comment]
What is your `speed` value?

**Comment by Casual-User** [comment]
My speed value is 3.96

**Comment by Sieberkev** [comment]
Pokemon Go implemented some extra softbans when looting too much stops too fast, this was probably already some sort of initial phase of that ([FAQ](https://github.com/jabbink/PokemonGoBot/blob/develop/FAQ.md#the-bot-doesnt-findloot-pokestops)).
