### ISSUE TITLE
Bot Always moving

### ISSUE THREAD

**Issue by Jackerrer** [jabbink/PokemonGoBot#719]
Bot is always walking arround.

I have try to put move speed to 0m/s but it changes nothing

**Comment by alexpw** [comment]
There's a (new?) config option that looks to do what you want:

# Allow leaving the starting area
allow_leave_start_area=true

**Comment by Jackerrer** [comment]
oh didin't saw it ><
thanks ><

**Comment by Sieberkev** [comment]
If this fixed your issue, please close it ;)

**Comment by Jackerrer** [comment]
No it didn't fix it.
I want him to don't move.
But with the 
allow_leave_start_area=false
and
spawn_radius=-1
he his chilling around in 3*3km.
and not stay at strat position.

**Comment by pashorizer** [comment]
Did you set `speed=0` exactly like that?

**Comment by Jackerrer** [comment]
Yes i did

**Comment by JetAlone** [comment]
If you must stay in start position try comment MAPS API KEY.

pon., 1.08.2016 o 11:15 użytkownik Jackerrer <notifications@github.com>
napisał:
