### ISSUE TITLE
Idea: Session Stats

### ISSUE THREAD

**Issue by MarceloAlves** [jabbink/PokemonGoBot#72]
I think it would be pretty neat to serve up a page that shows some session stats like pokemon caught, current position, items collected, etc. I don't know java but if someone wants to put in an http server and serve up some json I can put together a quick page for it. Thoughts?

**Comment by jabbink** [comment]
#74 implements this

**Comment by MarceloAlves** [comment]
Ah dang. Didn't even see that. Thanks!
