### ISSUE TITLE
[FEATURE] Use items it would otherwise drop

### ISSUE THREAD

**Issue by svombergen** [jabbink/PokemonGoBot#723]
**Description:**
Would be nice to have the bot use the items it is about to drop because of the drop_item configuration settings. Such as: razz berry, great balls or even incense or lucky egg.

Can do a standard 5 or so item buffer where bot will not drop items but will try to use it first time it can. And drop it anyway if the item count goes more than 5 over the set configuration.

**Comment by yashendra2797** [comment]
I agree! Better to use an item than needlessly drop it.

**Comment by jabbink** [comment]
#235
