### ISSUE TITLE
[Bug?] Autotransfer Duplicate P.s=false => Stops Autotransfer completely

### ISSUE THREAD

**Issue by Casual-User** [jabbink/PokemonGoBot#725]
**Description:**
After I switched of the autotransfer of duplicate pokemon in the config file,
Bot keeps all pokemons and doesn't even transfer the obligatory transfer ones.

from config file:
"Pokemon Transfer
should the bot auto transfer duplicate pokemon
autotransfer=false"

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]

**Expected behavior:**
should not only keep the strongest of each pokemon (autotransfer duplicate p=true), but all above the defined strength

**Actual behavior:**
stops autotransfer altogether

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
precompiled built alpha.4

**Operating System:**
OSX

**Java version:**
recent

**Comment by pashorizer** [comment]
Well, that description was before all the new settings appeared. `autotransfer=false` disables every transfer. So it has to be `true`.
If you don't want duplicate pokemon, there is this option
https://github.com/jabbink/PokemonGoBot/blob/develop/config.properties.template#L87

**Comment by Casual-User** [comment]
Ah, ok. So it's just the description that needs some polish, almost as I thought. Thanks!
