### ISSUE TITLE
[Issue] Cannot bind socket if more than one instance of the bot

### ISSUE THREAD

**Issue by fabioneves** [jabbink/PokemonGoBot#726]
**Description:**
Cannot bind web socket if we have more than one bot running from the same machine, even if the ports are changed.

**Steps to reproduce:**

1. Run first bot with socket on port 8000/8001
2. Run second bot with socket on port 9000/9001 for example

**Expected behavior:**
We should be able to access the WebUI on the specified ports, at least I was expecting that.

**Actual behavior:**
Can't access the WebUI for the second bot on port 9000, there's an error in console saying that it cannot bind to the address, because it's already being used (first bot).

**Version:**
Latest develop branch

**Operating System:**
Linux / CentOS 7

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by irisheoin** [comment]
I tested there and have 2 running, one 8000/8001 and other 8002/8003 and both woking on OS X 10.11.6, java version "1.8.0_102" running pogo.scraper-all-0.5.0-alpha4.jar

**Comment by fabioneves** [comment]
I'm using gradlew script, maybe it's because of that.

**Comment by jabbink** [comment]
Change the port or set it to `0` (= no webserver).

Also the current bot allows multiple configs at once.
