### ISSUE TITLE
Incorrect Pokemon Title

### ISSUE THREAD

**Issue by joligario** [jabbink/PokemonGoBot#743]
**Description:**
Encounter and catch ELECTABUZZ, but NIDORAN_FEMALE appears on map and transferred.

**Steps to reproduce:**
1. Watch log window.

**Expected behavior:**
Assumed correct title.

**Actual behavior:**
Either incorrect title of caught or transferred.

**Stacktrace (If it's a crash):**
N/A

**Version:**
https://github.com/jabbink/PokemonGoBot/commit/8d2ddfc3105d2e379b92b8406a549db4a3c98498

**Operating System:**
Win10 x64

**Java version:**
8_101

**Comment by theoi** [comment]
This is a bug with the actual game, I'm pretty sure. There are theories regarding this being proof of Ditto but it's probably just a bug

**Comment by joligario** [comment]
Highly possible. And after reading comments about nests being broken up, this farm location used to have tons of Electrabuzz. Will continue to monitor.

**Comment by joligario** [comment]
Thinking this was a server bug. What was an Electabuzz farm now seems to be a Needoran farm.
