### ISSUE TITLE
[suggestion] Enhanced Inventory Management System

### ISSUE THREAD

**Issue by Casual-User** [jabbink/PokemonGoBot#744]
**Description:**
At the moment, the bot discards more valuable items instead of less valuable items.
This behaviour is caused by the current item management system that only allows to provide max amounts per item type and doesn't allow to set truly relative item priorities.

Instead of keeping fixed max amounts per item type, an enhanced item management algorithm would work down a priority pyramid. 

**Expected behavior:**
The system should work like this: 
Until an item count of 349 is reached (400+ if upgraded), items should be discarded in regard to their in game value. To get this done, follow theses steps: 
 II first: get/compute current item count;
 II second: compute current 'item overflow' (the excess over 349/else);
 II third: discard phase. 
    start with least valuable item type (as defined in config file) and discard NUMBER (whatever is less: 'item overflow' / all); continue with second least valuable item and discard NUMBER (whatever is less: 'item overflow' / all); continue until item overflow = 0;

**Version:**
precompiled alpha.4

**Comment by vamirineni87** [comment]
Good idea. Another way is to track the CP/IV limits for each Type of pokemon. 
ex: PINSIR I need it above 1000 cp and 85% IV
vs a POLIWAG (which can be evolved) set it above 600 cp and 85% IV

**Comment by FrancYescO** [comment]
https://github.com/jabbink/PokemonGoBot/pull/946

**Comment by langerhans** [comment]
Added in #946
