### ISSUE TITLE
[Help] Config not finding longitude

### ISSUE THREAD

**Issue by RovingSpirit** [jabbink/PokemonGoBot#746]
**Description:**
Please don't ignore/close this because you think i've missed a space, i've checked and there is no space before or after my longitude coords, but the bot still says Longitude not specified.
# Token to login directly
token=0
latitude=33.8657378
longitude=151.203993
Could using pages to edit config.properties (changed filetype back to .properties after) cause this problem?

**Version:**
0.5.0 

**Operating System:**
OSX El Cap

**Java version:**
[Full output of `java -version`]

**Comment by Cypherke** [comment]
which java version? exact error? also there can be no 0 after token= it  needs to be empty

**Comment by RovingSpirit** [comment]
Problem was unintended formatting caused by editing using pages, i downloaded an open source text editor and it's all sorted. Thanks for commenting/trying to help!
