### ISSUE TITLE
Does incense work? 

### ISSUE THREAD

**Issue by Killertom63** [jabbink/PokemonGoBot#748]
If I pop an incense and a lucky egg on my mobile. Then quit it, boot the bot. Does the incense and lucky egg still work? 

Can we add something to the GUI that allows us to pop an incense or lucky egg, along with a timer? 

Keep up the good work!

**Comment by jabbink** [comment]
Lucky egg yes. Incense is currently not available, #728 should fix that

**Comment by Killertom63** [comment]
Thanks

**Comment by smileytechguy** [comment]
@jabbink are you saying incense won't work if you close the app and start the bot, or just that there is no way to view the egg/incense in the GUI?  If the first, how does #728 fix it?
