### ISSUE TITLE
Should first encounter then try to catch

### ISSUE THREAD

**Issue by alawing** [jabbink/PokemonGoBot#75]
first encounter with pokemon
{
      then check ball status
      try catch
      if catch/flee, break
      else if escape, continue
}

was trying to add the option to retry catch if escaped from the ball, but the program logic needs change to what I described, but I am not familiar with kotlin.

the POGOProtos proviede CatchStatus.CATCH_ESCAPE which means pokemon break the ball but still in encounter, we could add it for more chance to catch

**Comment by jabbink** [comment]
Encountering is already done, the rest: good point, will raise this problem in the upstream API

**Comment by jabbink** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/issues/138
