### ISSUE TITLE
Wrong Pokemon CP at transfering

### ISSUE THREAD

**Issue by Shazgul** [jabbink/PokemonGoBot#751]
**Description:**
Bot encountered an Jynx with 6xx but at transfering it says 4xx

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]

**Expected behavior:**
6xx Jynx shouldnt be transfered because of 500 CP and 90 IV Settings.

**Actual behavior:**
02 Aug 14:25:06: Pausing to catch pokemon...
02 Aug 14:25:07: Caught a JYNX with CP 644 and IV 60%
 Stamina: 9 | Attack: 15 | Defense: 3 | IV: 27 (60%): [210x XP, 3x Candy, 100x Stardust] 
02 Aug 14:25:07: Going to transfer JYNX with CP 458 and IV 57%; reason: CP < 500 and IV < 90% 

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
Alpha 4

**Operating System:**
Ubuntu 16.04

**Java version:**
OpenJDK 8

**Comment by Sieberkev** [comment]
It's not the same pokemon, but a badder one it kicks from the list:

> Caught a JYNX with CP 644 and IV 60%
> transfer JYNX with CP 458 and IV 57%

**Comment by Shazgul** [comment]
But there was no other Jynx with these Stats of 458 / 57 :o

**Comment by vamirineni87** [comment]
May be an egg hatched and you didnt see it? Can you check the log and see if its there..

**Comment by Shazgul** [comment]
No egg hatched, just some Pokestops spinned until this Pokemon came.

**Comment by Shazgul** [comment]
Happened again, this time with an hatched Egg:

02 Aug 15:14:29: Looted pokestop xxx; +50 XP: [1xITEM_POKE_BALL, 1xITEM_GREAT_BALL, 1xITEM_POTION] 
02 Aug 15:14:38: Profile update: xxx XP on LVL xxx; xxx/xxx (6,06%) to LVL xxx 
02 Aug 15:14:38: XP gain: xxx XP; Pokemon caught/transferred: xxx/xxx; Items caught/dropped: xxx/xxx;
Pokebank xxx/xxx; Stardust xxx; Inventory xxx/xxx 
02 Aug 15:14:39: Dropped 1x ITEM_POTION 
02 Aug 15:14:39: Dropped 1x ITEM_POKE_BALL 
02 Aug 15:14:40: Dropped 1x ITEM_GREAT_BALL 
02 Aug 15:14:40: Hatched SANDSHREW with 446 CP and 88% IV; +16 candy; +500 XP; +1266 stardust 
02 Aug 15:14:41: Put egg of 5.0km in unused incubator 
02 Aug 15:14:41: Wrote export.
02 Aug 15:14:43: Dropped 1x ITEM_RAZZ_BERRY 
02 Aug 15:14:43: Going to transfer SANDSHREW with CP 430 and IV 80%; reason: CP < 500 and IV < 90%

**Comment by Shazgul** [comment]
Ah now i understand, it just kicks the badder pokemon for the better one?

**Comment by Cypherke** [comment]
yep, it does. You can change these settings with autotransfer=false (not transferring any pokemon now)
