### ISSUE TITLE
[IMPROVEMENT] UI: Add IV Notification Option

### ISSUE THREAD

**Issue by CosmoRing** [jabbink/PokemonGoBot#757]
Add to the Notifications option on the UI an option to notify when a Pokemon with a specific IV% or higher is caught. 

Use example: Notify when a Pokemon with 100% IV is caught so people that have multiple bot's running in the same region can force the other bots to that position.

If i'm not mistaken CP can variate from bot to bot, but IV is the same.

**Comment by eruecco87** [comment]
I created a separate repository for an UI Theme I created. I also added that feature you mentioned.

You can check it out here: https://github.com/eruecco87/PokemonGoBot-RocketTheme
