### ISSUE TITLE
Feature Request - Webserver Port change able

### ISSUE THREAD

**Issue by Galaxy200** [jabbink/PokemonGoBot#758]
It would be really cool to have the chance to change the Webserver port.

**Comment by Sieberkev** [comment]
Well talk about a lucky day for you, it's right at the bottom of the config file!

**Comment by Galaxy200** [comment]
Then im blind, i cant find it i just see the, List of pokemon names and Above this is list of pokemon you always want to trancsfer regardless of CP

**Comment by Sieberkev** [comment]
What version of the bot are you using? In the most recent develop build at this moment you can find it [here](https://github.com/jabbink/PokemonGoBot/blob/develop/config.properties.template#L129-L132).

**Comment by Galaxy200** [comment]
i think i use an older version, i will update it. thx for the fast answer!
