### ISSUE TITLE
No info in web UI

### ISSUE THREAD

**Issue by WillemSV** [jabbink/PokemonGoBot#759]
**Description:**
I can't get any data to load in web UI in Chrome/Firefox/Safari on mac.

**Steps to reproduce:**

1. Start bot
2. Open UI

**Expected behavior:**
Info in the UI

**Actual behavior:**
All boxes stay empty

**Stacktrace (If it's a crash):**
This is the error I'm getting in console multiple times

_"A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:8000' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute."_

**Version:**
0.5.0-alpha 4

**Operating System:**
OSX 10.11.1

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by TheWayAway** [comment]
Is your bot running normally as well?

**Comment by WillemSV** [comment]
@TheWayAway Yup no issues at all

**Comment by itsavirusforyou** [comment]
Do you have any other bots or maps running that might be conflicting with the port or something?

**Comment by WillemSV** [comment]
Nope

**Comment by jabbink** [comment]
Can you try going to http://pogo.abb.ink/map.html

**Comment by jabbink** [comment]
Editing comments seems broken on my mobile client: http://pogo.abb.ink/0.5.0-alpha4/map.html

**Comment by WillemSV** [comment]
That did the trick. It works now

**Comment by eruecco87** [comment]
@TheWayAway you can also check out this interface for the Bot http://oscarviquez.com/pogo/
