### ISSUE TITLE
Failed to interpret Starting Latitude setting ("latitude") & Execution failed for task ':run'.

### ISSUE THREAD

**Issue by ferdytan** [jabbink/PokemonGoBot#763]
**Description:**
Failed to interpret Starting Latitude setting ("latitude"), got "" 
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

**Steps to reproduce:**

1. ./gradlew run

**Expected behavior:**
running

**Actual behavior:**
03 Aug 11:28:50: Failed to interpret Starting Latitude setting ("latitude"), got "" 
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Stacktrace (If it's a crash):**
http://pastebin.com/evBHjtSf

**Version:**
Pokemon Go Bot v0.5.0 alpha 4

**Operating System:**
MacOSX El Capitan 10.11.4

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by rbailloux** [comment]
The config.properties file comes with empty latitude and longitude.
You have to manually set them.
Regards

**Comment by ferdytan** [comment]
Thank You it worked after i insert the latitude and longitude
