### ISSUE TITLE
build fails on comparekotlin

### ISSUE THREAD

**Issue by junchaowu** [jabbink/PokemonGoBot#765]
java 1.8 on mac.

when run ./gradlew build from root dir of the project, I got following error log.

java.lang.RuntimeException: java.io.FileNotFoundException: PokemonGoBot/lib/PokeGOAPI-Java/build/libs/PokeGOAPI-Java-0.0.1-SNAPSHOT.jar!/okhttp3/OkHttpClient.class

**Comment by Cypherke** [comment]
did you do step 2 from the readme?
> Run git submodule update --init --recursive

**Comment by jabbink** [comment]
That step isn't necessary anymore (since 1 minute ago) and the error looks more like he isn't doing `gradlew run` but executing the **non** fat jar, which requires you to put the okhttp jar in the same directory
