### ISSUE TITLE
Improve 'catch rate'

### ISSUE THREAD

**Issue by staurakis** [jabbink/PokemonGoBot#766]
**Description:**
Hello all,
i was wondering, how is it possible to 'force' the bot to have a better 'catch rate' by using better balls etc especially on higher pokemons.
I tried by changing the 'desired_catch_probability' but i'm not sure I have made a change since i don't see the bot changing the way it is evaluating what ball to choose for example.
I hope i have put this on the right place. Excuse me if not.

**Version:**
alpha 4

**Operating System:**
Windows 7

**Comment by Cypherke** [comment]
The bot calculates the catch rate on the values you give it. If you set desired_catch_probability to 1 it will calculate to catch the pokemon in 1 throw. Of course this can still fail as there are alot of variables to include.

**Comment by staurakis** [comment]
Yes that's what i thought so as well and that's what i have set it to.
Thank you very much for your so fast reply!

**Comment by jabbink** [comment]
If you set the desired catch rate to 1, it may still fail if you don't have the berries or ultra/master balls. Also make sure you have `never_use_berries=false`

**Comment by staurakis** [comment]
Indeed i have set the values to always have ultra/master balls and never_use_berries-false.
My point was if somehow there was a way to 'force' use of ultra and berries for pokemons you definitely want. What i have noticed is that it calculates the probability and decides based on how 'good' the encounter is, i.e. how much you 'should' want the pokemon.
So, to sum up, indeed the logic behind it is the best and one can achieve my logic by simply lowering the value of transfer_iv_threshold.
Again, thank you very much for the reply!

**Comment by jabbink** [comment]
The probability thing is **serverside**. So if you put in desired prob = 1, and the bot says: achieved: 1 (or higher); desired 1. You have a 100.000000% chance of catching the pokemon on the first try.

Either that, or the server is returning garbage data.
