### ISSUE TITLE
[Feature Request] Use of incense

### ISSUE THREAD

**Issue by Cordyceps9** [jabbink/PokemonGoBot#767]
Option to use incense when available and walking around? 

Alternatively, if you drop an incense in the app before starting the bot, is the effect carried forward into the gameplay of the bot?

**Comment by desmondev** [comment]
> Alternatively, if you drop an incense in the app before starting the bot, is the effect carried forward into the gameplay of the bot?
Yes it is

**Comment by jabbink** [comment]
> Option to use incense when available and walking around?

Duplicate

>Alternatively, if you drop an incense in the app before starting the bot, is the effect carried forward into the gameplay of the bot?

Yes
