### ISSUE TITLE
Exeption in thread main - bot not usable 

### ISSUE THREAD

**Issue by Sanafan** [jabbink/PokemonGoBot#768]
Hey Guys,
just wanted to try the bot. Downloaded anything, created a new folder which includes "config.properties" and "pogobo.jar" which is the latest release. This is what happens, when i start the jar file via terminal:

`Sits-Mac-mini:pgo sit$ java -jar pogobo.jar` 
`03 Aug 09:10:11: Logging in to game server...`
`03 Aug 09:10:12: Logged in successfully`
`Getting profile data from pogo server.`
`D/RequestHandler: Authenticated with static token`
`Exception in thread "main" java.lang.NullPointerException`
	`at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:42)`
	`at ink.abb.pogo.scraper.MainKt.main(Main.kt:145)`

So do you know what to do know and how to fix this? Any help would be appreciated

**Comment by Sieberkev** [comment]
Which released version is this pogobo.jar file?

**Comment by Sadfaffel** [comment]
I had the same problem, i just went to my phone, finished the start tutorial and started the bot again. Worked.

**Comment by Sanafan** [comment]
Already did that (the tutorial thing) - running now on win 10 VM - working fine but it feels like the bot doesn't find many pokemons. 
![bildschirmfoto 2016-08-03 um 10 02 20](https://cloud.githubusercontent.com/assets/8384797/17358293/7095a9c6-5961-11e6-9010-3e45b14b2168.png)

**Comment by Sadfaffel** [comment]
https://github.com/jabbink/PokemonGoBot/issues/21 
Maybe this helps.
