### ISSUE TITLE
Cant typ gradlew run

### ISSUE THREAD

**Issue by beauterham** [jabbink/PokemonGoBot#771]
I just wanted to test out ur new update.
I folowed ur guide and the Gradlew installation is succesfull.

The code:

```
Welcome to Gradle 2.14.1.
To run a build, run gradlew <task> ...
To see a list of available tasks, run gradlew tasks
To see a list of command-line options, run gradlew --help
To see more detail about a task, run gradlew help --task <task>
BUILD SUCCESSFUL
Total time: 1.51 secs
This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
[Proces voltooid]
```

But when i try to do step 5 i cant typ anything in the terminal.

(probl easy fix but i'm noob with this)

**Comment by jabbink** [comment]
That output suggests you just executed `gradlew` without the `build after it.

**Comment by beauterham** [comment]
But @jabbink 
What i call `gradlew` i keep getting the same outcome

**Comment by Sieberkev** [comment]
you have to type/paste `./gradlew build`

**Comment by beauterham** [comment]
Maar @Sieberkev ik kan niet daaronder typen of pasten of wat dan ook

**Comment by jabbink** [comment]
Same line
