### ISSUE TITLE
[BOTLOOP] Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED after commit hash 7a3246e

### ISSUE THREAD

**Issue by nostyler** [jabbink/PokemonGoBot#772]
**Description:**
Compiled from github a few minutes ago. It finds the first Pokemon, captures it but then it does not 'move on' to another one. Resulting in continuous `xxx (default: BotLoop): Encounter failed with result: ENCOUNTER_ALREADY_HAPPENED` statements

**Steps to reproduce:**

1. Clone repository (development)
2. Build
3. Run

**Expected behavior:**
Continue to a next Pokemon once the first one was caught

**Actual behavior:**
It continues to try and catch the first caught Pokemon

**Stacktrace (If it's a crash):**
Not applicable.

**Version:**
Commit hash 7a3246e

**Operating System:**
Ubuntu 16.04

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by jabbink** [comment]
Is the time of your computer correct?

**Comment by nostyler** [comment]
Yes it is.

**Comment by trxit** [comment]
same here. time syncs after ntp server but still get the error

**Comment by jabbink** [comment]
Turned out to be an API issue. I expected it to be already updated for the slower map objects fix.

**Comment by nostyler** [comment]
OK. I will retest once it is available.
