### ISSUE TITLE
[WEBUI] Map location set to http://pogo.abb.ink/0.5.0-alpha4/map.html after commit hash 7a3246e

### ISSUE THREAD

**Issue by nostyler** [jabbink/PokemonGoBot#773]
**Description:**
Am seeing the following message: `(default): Open the map on http://pogo.abb.ink/0.5.0-alpha4/map.html` and cannot open the WEBUI

**Steps to reproduce:**

1. Clone repository
2. Build
3. Run

**Expected behavior:**
Approach the WEBUI by navigating to http://ip_address:8000

**Actual behavior:**
WEBUI is not up and running (or approachable) on the machine.

**Stacktrace (If it's a crash):**
Not applicable.

**Version:**
Commit hash 7a3246e

**Operating System:**
Ubuntu 16.04

Java version:
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by jabbink** [comment]
Have you tried doing what it says?

**Comment by nostyler** [comment]
Yes and there is a WEBUI running there, but it is not populated with my data (or any data at all).

**Comment by jabbink** [comment]
Did you change ports? If so, specify your IP and port after the # sign. Eg #192.168.0.2:12345

**Comment by nostyler** [comment]
No I did not. Maybe worth mentioning that I am running the bot on a remote box (at online.net)?

**Comment by Peyphour** [comment]
map.html#host:port doesn't work for me either

**Comment by jabbink** [comment]
>No I did not. Maybe worth mentioning that I am running the bot on a remote box (at online.net)?

Then make sure the port is forwarded properly and instead of going to i.dont.know.what.online.net:800**0**, go to [http://pogo.abb.ink/0.5.0-alpha4/map.html#i.dont.know.what.online.net:800**1**](http://pogo.abb.ink/0.5.0-alpha4/map.html#i.dont.know.what.online.net:8001)

**Comment by beauterham** [comment]
Its al under eachother.
U can move everything and u should see every option

**Comment by nostyler** [comment]
OK! Nice! Thank you both!
