### ISSUE TITLE
CATCH_FLEE, not looting pokestops :3

### ISSUE THREAD

**Issue by creepercon0826** [jabbink/PokemonGoBot#783]
03 Aug 23:47:12: Found pokemon EEVEE
03 Aug 23:47:13: Encountered pokemon EEVEE with CP 45 and IV 66%
**03 Aug 23:47:13: Using ITEM_POKE_BALL; achieved catch probability: 0.9615507, desired: 0.4**
03 **Aug 23:47:14: Capture of EEVEE failed with status : CATCH_FLEE**
03 Aug 23:47:17: Getting map of (41.707313206251754, -1.0015728557912227)
03 Aug 23:47:22: Getting map of (41.707437790733415, -1.0014253858552673)
03 Aug 23:47:22: Looting nearby pokestop a6de0512be21480595dce7635491f0c2.16
**03 Aug 23:47:23: Looted pokestop a6de0512be21480595dce7635491f0c2.16; +0 XP: []**
03 Aug 23:47:27: Getting map of (41.70746020858014, -1.0013869390354964)
03 Aug 23:47:27: Looting nearby pokestop a6de0512be21480595dce7635491f0c2.16
**03 Aug 23:47:28: Looted pokestop a6de0512be21480595dce7635491f0c2.16; +0 XP: []**
03 Aug 23:47:32: Getting map of (41.70753666771662, -1.0013069361870164)
03 Aug 23:47:32: Destination reached.
03 Aug 23:47:32: Looting nearby pokestop a6de0512be21480595dce7635491f0c2.16

**Expected behavior:**
catch EEVEE, loot pokestop 
**Actual behavior:**
it says 0.96 probability to catch eeve, but it still fled :(, this happens to almost every pokemon i encounter.

and it doesnt loot pokestops as well :(((((

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
**java -jar pogo.scraper-all-0.5.0-alpha4.jar**

**Java version:**
latest

**Comment by ksaiyanz** [comment]
Sounds like you have been soft-banned.

**Comment by creepercon0826** [comment]
@ksaiyanz hmmm.... how long is the cool down span

**Comment by ksaiyanz** [comment]
Its about an hour, try not to teleport around the map at an unreasonable speed. FOr example if you teleport 60 miles away, wait about 20 min or so first.

**Comment by fabioneves** [comment]
Just let the bot hang around, as soon as it tries to spin pokestops 30-40x times, it'll unban.

**Comment by creepercon0826** [comment]
@ksaiyanz @fabioneves  oh okok, thanks guys :))

**Comment by jabbink** [comment]
@fabioneves you have to enable that in the config first. Then after about 10 secs you are unbanned.
