### ISSUE TITLE
Can I draw where I want it to go, and loop that path?

### ISSUE THREAD

**Issue by Leodenact** [jabbink/PokemonGoBot#786]
I see you can pinpoint where you want your trainer to go at the localhost gui, but can I draw the waypoints and loop them also?

**Comment by russr123** [comment]
u can click them in a loop, but when it hit the last click, it will either STOP and get stuck, OR it will head to the nearest stop and keep going....

**Comment by langerhans** [comment]
You can upload a GPX file.
