### ISSUE TITLE
Can't locate config.properties

### ISSUE THREAD

**Issue by dwfz** [jabbink/PokemonGoBot#788]
**Description:**
Cannot find config.properties, made sure that it wasn't a text file

**Steps to reproduce:**

1.running  java -jar pogo.scraper-all-0.5.0-alpha-alpha4.jar in cmd

**Expected behavior:**
Run successfully 
**Actual behavior:**
error that it cannot find config.properties even though they are in the same directory

**Version:**
0.5.0 alpha4

**Operating System:**
windows 10 pro

**Java version:**
jdk8u101

**Comment by fabioneves** [comment]
You probably have the wrong file extension for the config file. Search google on how to see file extensions on windows, you probably have config.properties.txt or something.

**Comment by dwfz** [comment]
Ok it saved as a java file instead of a properties file, thank you
