### ISSUE TITLE
gradlew build tests error 

### ISSUE THREAD

**Issue by dwfz** [jabbink/PokemonGoBot#791]
**Description:**

![image](https://cloud.githubusercontent.com/assets/14083792/17376434/8bc134aa-5983-11e6-9fa6-19befd22b6e9.png)

the latest release is in the same directory
**Steps to reproduce:**

1. gladlew run

**Expected behavior:**
should build

**Actual behavior:**
error

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
[The version of the bot you used; when self-compiled: :exclamation: the commit hash :exclamation:]
.5.0 alpha4
**Operating System:**
[Your operating system]
windows 10
**Java version:**
[Full output of `java -version`]
jdk 8u101

**Comment by pashorizer** [comment]
Don't rename the `compile.properties.template`. You need that. Make a copy of it.

**Comment by dwfz** [comment]
oh shit. thank u
