### ISSUE TITLE
Gradlew Run Stuck @ 83%

### ISSUE THREAD

**Issue by dwfz** [jabbink/PokemonGoBot#793]
**Description:**
build was successful but error when try to run

**Steps to reproduce:**

1. gradlew run

**Expected behavior:**
successful run

**Actual behavior:**
freezes at 83%

**Stacktrace (If it's a crash):**
http://pastebin.com/dAuvtsMt

**Version:**
[The version of the bot you used; when self-compiled: :exclamation: the commit hash :exclamation:]
.5.0alpha4

**Operating System:**
windows 10

**Java version:**
jdk8.101

**Comment by jabbink** [comment]
It doesn't freeze. The `run` (or `bootRun`) task contains compiling, starting, running and closing. Closing is 17%. Because the bot is running it's on 83%. When you press Ctrl+C it will go to 100%.
