### ISSUE TITLE
Error to login

### ISSUE THREAD

**Issue by CaosJunior** [jabbink/PokemonGoBot#797]
C:\Users\User\Desktop\BOT>java -jar pogo.scraper-all-0.4.3.jar
03 ago 17:22:14: Logging in to game server...
D/GoogleCredentialProvider: 0
D/GoogleCredentialProvider: Get user to go to:null and enter code:null

I'm getting this when i open the bot (version 0.4.3), it was working normal some minutes ago, anyone having this issue?

**Comment by jabbink** [comment]
Why do you use such outdated software?

**Comment by mojin7** [comment]
The page does say... If you want one that "works" use 0.4.3

**Comment by CaosJunior** [comment]
Like mojin7 said... Also,the newest version start to spam an error after some minutes open, with 0.4.3 i don't have any error.
