### ISSUE TITLE
Working fine untill about 15min ago

### ISSUE THREAD

**Issue by qwertychacha2002** [jabbink/PokemonGoBot#799]
Everything was working completely fine untill about 15min ago. Then it stopped working and gave me this long error code. It is now logging in succesfully but it finds no pokestops (even though I'm in Central Park)

**Version:**
pogo.scraper-all-0.5.0-alpha4.jar

**Operating System:**
OSX El Capitan Version 10.11.5 (15F34)

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by ksaiyanz** [comment]
Apparently, Niantic made some changes to the server which broke all bots. Need to wait for a fix.

**Comment by pet90210** [comment]
same here , PokemonGo-Map isn't working as well!

**Comment by bakxsteen** [comment]
Old versions have been blacklisted since 30 minutes.

**Comment by jabbink** [comment]
Fixed
