### ISSUE TITLE
GUI using wrong account

### ISSUE THREAD

**Issue by NinjaStew** [jabbink/PokemonGoBot#805]
I currently have the bot running, but the GUI displays another one of my accounts that's not in use at the moment. The only error message I'm receiving is from the pogo link, where the console log says 'Error running loop BotLoop!'

**Comment by jabbink** [comment]
Make sure the account is correctly set in `bot-settings/default.json` in case you ever ran the bot before.

If not: please specify all information from the issue template.

**Comment by NinjaStew** [comment]
I don't have any files in my bot-settings folder. I did only have the folder generated after launching this last release, so I didn't find it peculiar.

**Comment by NinjaStew** [comment]
So I have figured out the issue with the GUI, but now my only concern is the files missing from my bot-settings folder. I don't suppose you would have the document templates available for download, would you?

**Comment by langerhans** [comment]
From what I understand you are not using the multi bot fuinction. Then the bot-settings folder does not really matter. Don't worry about the files in there.
