### ISSUE TITLE
Automatic scroll of events window on http://pogo.abb.ink/RocketTheme/

### ISSUE THREAD

**Issue by staurakis** [jabbink/PokemonGoBot#808]
Is there a way to make the events window to automatically scrolling down with the latest events? As far as i understand right now you have to manually scroll down to see the newest events. It wasn't like that before.  Furthermore, is it possible to change the size of this window?
Thank you very much in advance for your great help.
You have made a magnificent work! :)

**Comment by toffaste1337** [comment]
Right now there are no "easy" way to do this.
If you are using chrome(also other browsers) this will work:

Rightclick the console window, and find the div "log-wrapper", rightclick, add attribute, type `id="log-wrapper"`

Next, head over to the console, paste the code below and press enter.
`function scrollDown(){
	var objDiv = document.getElementById("log-wrapper");
	objDiv.scrollTop = objDiv.scrollHeight;
	setTimeout(function(){
	scrollDown();
	}, 400)
}
scrollDown();
`

**Comment by staurakis** [comment]
Thank you very much!!!
