### ISSUE TITLE
multiple bot accounts .json files

### ISSUE THREAD

**Issue by pirocoptero** [jabbink/PokemonGoBot#810]
I'm having trouble with multiples accounts. i removed the user and pass from the .properties and have created two .json files with a name respective for each one. however I am getting error on login. Can you show two examples of .json file configuration?? i must leave blank the .properties username and password if i use multiples accounts?

Exception in thread "multipleone" java.lang.IllegalStateException: Server refused your login credentials. Are they correct?

**Comment by smileytechguy** [comment]
What you can do (what I'm doing) is make 2 seperate folders, each with a normal config.propeties and just run the bot from each folder seperately

**Comment by pirocoptero** [comment]
@smileytechguy i tried this, it was like i did before, but when i try this i get this error...

java.lang.RuntimeException: java.net.BindException: Address already in use

**Comment by tomtobac** [comment]
@pirocoptero sound like we need some kind of file there, in Bot-settings/,

**Comment by toffaste1337** [comment]
Do you have different ports @pirocoptero ?

**Comment by pirocoptero** [comment]
@tomtobac yep! Actually i have it. How i get it, we need the files according to each account, but i have error for each one.

**Comment by toffaste1337** [comment]
@pirocoptero start your bot like this
java -jar PokemonGoBot-0.5.0.jar --server.port=8090

**Comment by pirocoptero** [comment]
@toffaste1337 the port is not the problem, i can authenticate with only one account, my problem is with multiples .json files. 

07 ago 13:48:40 (firstaccount): Logging in to game server...
07 ago 13:48:40 (secondaccount): Logging in to game server...
Exception in thread "central" Exception in thread "washington" java.lang.IllegalStateException: Server refused your login credentials. Are they correct?
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:102)
	at ink.abb.pogo.scraper.MainKt.startBot$default(Main.kt:89)
	at ink.abb.pogo.scraper.services.BotService.submitBot(BotService.kt:39)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:62)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
java.lang.IllegalStateException: Server refused your login credentials. Are they correct?
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:102)
	at ink.abb.pogo.scraper.MainKt.startBot$default(Main.kt:89)
	at ink.abb.pogo.scraper.services.BotService.submitBot(BotService.kt:39)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:62)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by pirocoptero** [comment]
one of my exemple account json file is like this, offcourse, with the right values on latitude, longitude and credentials:

{ "name" : "firstaccount", "latitude" : mylatitude, "longitude" : mylongitude, "credentials" : { "type" : "ptc", "username": "myuser@gmail.com", "password": "mypass" } }

**Comment by toffaste1337** [comment]
So what did you name the config? Default.json ? I don't know if it matters though

**Comment by toffaste1337** [comment]
{
  "latitude" : x.xx,
  "longitude" : x.xx,
  "credentials" : {
    "type" : "google",
    "token" : ""
  },
  "speed" : 2.8,
  "followStreets" : false,
  "dropItems" : true,
  "uselessItems" : {
    "ITEM_REVIVE" : 20,
    "ITEM_MAX_REVIVE" : 10,
    "ITEM_POTION" : 0,
    "ITEM_SUPER_POTION" : 30,
    "ITEM_HYPER_POTION" : 50,
    "ITEM_MAX_POTION" : 50,
    "ITEM_POKE_BALL" : 40,
    "ITEM_GREAT_BALL" : 50,
    "ITEM_ULTRA_BALL" : 50,
    "ITEM_MASTER_BALL" : 10,
    "ITEM_RAZZ_BERRY" : 40,
    "ITEM_LUCKY_EGG" : -1,
    "ITEM_INCENSE_ORDINARY" : -1,
    "ITEM_TROY_DISK" : -1
  },
  "profileUpdateTimer" : 60,
  "timerWalkToStartPokestop" : -1,
  "randomNextPokestopSelection" : 5,
  "desiredCatchProbability" : 0.4,
  "desiredCatchProbabilityUnwanted" : 0.0,
  "autotransfer" : true,
  "keepPokemonAmount" : 1,
  "maxPokemonAmount" : -1,
  "displayKeepalive" : true,
  "displayPokestopName" : false,
  "displayPokestopRewards" : true,
  "displayPokemonCatchRewards" : true,
  "displayIfPokemonFromLure" : true,
  "lootPokestop" : true,
  "catchPokemon" : true,
  "autoFillIncubator" : true,
  "sortByIv" : false,
  "alwaysCurve" : false,
  "neverUseBerries" : true,
  "allowLeaveStartArea" : false,
  "spawnRadius" : -1,
  "banSpinCount" : 0,
  "transferCpThreshold" : 400,
  "transferIvThreshold" : 80,
  "ignoredPokemon" : [ "EEVEE", "MEWTWO", "CHARMANDER" ],
  "obligatoryTransfer" : [ "DODUO", "RATTATA", "CATERPIE", "PIDGEY" ],
  "export" : "",
  "guiPortSocket" : 8001,
  "initialMapSize" : 9,
  "version" : "0.5.0"
}
use this as the config, and then you will get the token from the link on first start :)

**Comment by toffaste1337** [comment]
Also if anyone needs this, default config for ptc.
`{
  "latitude" : x.xx,
  "longitude" : x.xx,
  "credentials" : {
    "type" : "ptc",
    "username" : "my-username",
    "password" : "my-password"
  },
  "speed" : 2.8,
  "followStreets" : false,
  "dropItems" : true,
  "uselessItems" : {
    "ITEM_REVIVE" : 20,
    "ITEM_MAX_REVIVE" : 10,
    "ITEM_POTION" : 0,
    "ITEM_SUPER_POTION" : 30,
    "ITEM_HYPER_POTION" : 50,
    "ITEM_MAX_POTION" : 50,
    "ITEM_POKE_BALL" : 40,
    "ITEM_GREAT_BALL" : 50,
    "ITEM_ULTRA_BALL" : 50,
    "ITEM_MASTER_BALL" : 10,
    "ITEM_RAZZ_BERRY" : 40,
    "ITEM_LUCKY_EGG" : -1,
    "ITEM_INCENSE_ORDINARY" : -1,
    "ITEM_TROY_DISK" : -1
  },
  "profileUpdateTimer" : 60,
  "timerWalkToStartPokestop" : -1,
  "randomNextPokestopSelection" : 5,
  "desiredCatchProbability" : 0.4,
  "desiredCatchProbabilityUnwanted" : 0.0,
  "autotransfer" : true,
  "keepPokemonAmount" : 1,
  "maxPokemonAmount" : -1,
  "displayKeepalive" : true,
  "displayPokestopName" : false,
  "displayPokestopRewards" : true,
  "displayPokemonCatchRewards" : true,
  "displayIfPokemonFromLure" : true,
  "lootPokestop" : true,
  "catchPokemon" : true,
  "autoFillIncubator" : true,
  "sortByIv" : false,
  "alwaysCurve" : false,
  "neverUseBerries" : true,
  "allowLeaveStartArea" : false,
  "spawnRadius" : -1,
  "banSpinCount" : 0,
  "transferCpThreshold" : 400,
  "transferIvThreshold" : 80,
  "ignoredPokemon" : [ "EEVEE", "MEWTWO", "CHARMANDER" ],
  "obligatoryTransfer" : [ "DODUO", "RATTATA", "CATERPIE", "PIDGEY" ],
  "export" : "",
  "guiPortSocket" : 8002,
  "initialMapSize" : 9,
  "version" : "0.5.0"
}`
Make sure to have different guiPortSocket on all profiles.

**Comment by pirocoptero** [comment]
Thank you @toffaste1337 , i see when i started the first time and the default json was changed like your recommendation. Thank you so much!!!

Full Solution:

inside the Bot-settings folder we need json files according each one account we want to use.

Example: accountone.json accounttwo.json accountthree.json

inside of each one of this file we must have this settings:
**PS: if you want authenticate with you pokemon trainer club you must to change the credentials type "google" to "ptc" and "token" to "password"**

`{
"latitude" : x.xx,
"longitude" : x.xx,
"credentials" : {
"type" : "google",
"token" : "YOUR_GOOGLE_ACCOUNT_TOKEN(LINK BELOW THIS CODE)"
},
"speed" : 2.8,
"followStreets" : false,
"dropItems" : true,
"uselessItems" : {
"ITEM_REVIVE" : 20,
"ITEM_MAX_REVIVE" : 10,
"ITEM_POTION" : 0,
"ITEM_SUPER_POTION" : 30,
"ITEM_HYPER_POTION" : 50,
"ITEM_MAX_POTION" : 50,
"ITEM_POKE_BALL" : 40,
"ITEM_GREAT_BALL" : 50,
"ITEM_ULTRA_BALL" : 50,
"ITEM_MASTER_BALL" : 10,
"ITEM_RAZZ_BERRY" : 40,
"ITEM_LUCKY_EGG" : -1,
"ITEM_INCENSE_ORDINARY" : -1,
"ITEM_TROY_DISK" : -1
},
"profileUpdateTimer" : 60,
"timerWalkToStartPokestop" : -1,
"randomNextPokestopSelection" : 5,
"desiredCatchProbability" : 0.4,
"desiredCatchProbabilityUnwanted" : 0.0,
"autotransfer" : true,
"keepPokemonAmount" : 1,
"maxPokemonAmount" : -1,
"displayKeepalive" : true,
"displayPokestopName" : false,
"displayPokestopRewards" : true,
"displayPokemonCatchRewards" : true,
"displayIfPokemonFromLure" : true,
"lootPokestop" : true,
"catchPokemon" : true,
"autoFillIncubator" : true,
"sortByIv" : false,
"alwaysCurve" : false,
"neverUseBerries" : true,
"allowLeaveStartArea" : false,
"spawnRadius" : -1,
"banSpinCount" : 0,
"transferCpThreshold" : 400,
"transferIvThreshold" : 80,
"ignoredPokemon" : [ "EEVEE", "MEWTWO", "CHARMANDER" ],
"obligatoryTransfer" : [ "DODUO", "RATTATA", "CATERPIE", "PIDGEY" ],
"export" : "",
"guiPortSocket" : 8001,
"initialMapSize" : 9,
"version" : "0.5.0"
}`

LINK TO YOUR GOOGLE TOKEN: [https://accounts.google.com/AccountChooser?continue=https://accounts.google.com/o/oauth2/auth?scope%3Dopenid%2Bemail%2Bhttps://www.googleapis.com/auth/userinfo.email](Google Token)

Credits to @toffaste1337

**Comment by tomtobac** [comment]
@pirocoptero and then java -jar pogobot.jar
and it will take all accounts with the same jar?

**Comment by toffaste1337** [comment]
@tomtobac yes, and when you launch the map, just change the port there for each account :)

**Comment by andrew1135** [comment]
this link:

LINK TO YOUR GOOGLE TOKEN: https://accounts.google.com/AccountChooser?continue=https://accounts.google.com/o/oauth2/auth?scope%3Dopenid%2Bemail%2Bhttps://www.googleapis.com/auth/userinfo.email


it is not working for me. other link??

**Comment by tomtobac** [comment]
@andrew1135
you don't need to put your token.
Just put ur creedentials like this:

`
"credentials" : { 
   "type" : "google", 
   "token" : "",
   "username": "<your_username>",
   "password": "<your_password>" 
},
`

**Comment by classicalDonkey** [comment]
Is it just me or does the GUI not work if you using for multi accounts at once?

**Comment by tomtobac** [comment]
me neither, for `locahost:8001` :'(

**Comment by classicalDonkey** [comment]
@tomtobac you need to use www.pogo.abb.ink/RocketTheme/ to access now, are you doing that?

**Comment by andrew1135** [comment]
each account must have diferent port

"guiPortSocket" : 8001,

"guiPortSocket" : 8002,

"guiPortSocket" : 8003,

**Comment by classicalDonkey** [comment]
@andrew1135 ya i have have different one and the GUI does not update as things happen, its showing the same map for the 3 i am running and two are in a different place

**Comment by tomtobac** [comment]
@classicalDonkey wtf? i thought it was localhost, what the fuck is ` www.pogo.abb.ink/RocketTheme/` ¿?
should be something like that in vps server: `localhost:8000/RocketTheme/`?

**Comment by classicalDonkey** [comment]
@tomtobac ya its been changed so you have to use pogo.abb.ink/RocketTheme/ now and then you select the port to use

**Comment by tomtobac** [comment]
@classicalDonkey ah oki! Thanks! its working for me >_<

**Comment by pirocoptero** [comment]
the bot run fine, but i can't access the pogo.abb.ink/RocketTheme/ because my server is getting error.

Exception in thread "mycity" java.net.BindException: Address already in use

but never is running in this door "guiPortSocket" : 8002

**Comment by jabbink** [comment]
Make sure you only run a SINGLE instance of the bot (the bot handles multiple accounts now).

The bot needs port 8080 for coordination though (it has a REST interface to restart bots). If you need port 8080 for something else, start java with the parameter `--server.port=8090` (or any other port) on the command line.

**Comment by casper-gh** [comment]
I got the multiple bots working, but I could only access GUI on the first port 8001 although my other bot is set at 8002.

Also on the working GUI, the cmd line log keeps loading and never shows

**Comment by pirocoptero** [comment]
@jabbink thank you so much!

**Comment by nesttle** [comment]
Multi JSON generator (PHP) for Jabbink's Bot
https://github.com/nesttle/PokemonGoBot-JSON-Generator
