### ISSUE TITLE
GUI not working

### ISSUE THREAD

**Issue by pliebig** [jabbink/PokemonGoBot#812]
**Description:**
Trying to open the GUI. But its not working. Bot is working, but the GUI is not opening
config file:

**Port where the socketserver should listen, 0 = do not listen**
gui_port_socket=8001

**Expected behavior:**
The GUI should open on http://0.0.0.0:8001

**Actual behavior:**
Empty Page, no response

**Version:**
0.5.0
**Operating System:**
OSX

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by smileytechguy** [comment]
Please read the README.  The update now has you go to http://pogo.abb.ink/RocketTheme/ .  Please use this instead
