### ISSUE TITLE
Bot seems to be ignoring gui_port_socket

### ISSUE THREAD

**Issue by matmen** [jabbink/PokemonGoBot#813]
**Description:**
I cant get multiple instances in multiple folders on one machine running.

**Steps to reproduce:**

1. Copy the Bot into two seperate folders
2. Change the gui_port_socket to another value on the 2nd bot
3. Start the bots

**Expected behavior:**
Two instances running in two consoles

**Actual behavior:**
Bot crashes with Adress already in use

**Stacktrace (If it's a crash):**
https://gitlab.com/snippets/23813

**Version:**
0.5.0

**Operating System:**
Windows 10 x64

**Java version:**
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b15)
Java HotSpot(TM) Client VM (build 25.91-b15, mixed mode, sharing)

**Comment by casper-gh** [comment]
Same issue, got `Address already in use` even port set to 0

**Comment by jabbink** [comment]
Read the Readme/frontpage

**Comment by jabbink** [comment]
![image](https://cloud.githubusercontent.com/assets/2461972/17464451/2e30f992-5cdf-11e6-9a98-94eb0728cc98.png)

**Comment by matmen** [comment]
Need them in multiple folders though - else i wouldnt have created this.

**Comment by jabbink** [comment]
Why do you need that? You can put many configs in a single `bot-settings` directory and that saves you a lot of memory (only one JRE instance).

Anyways: start the bot like `java -jar PokemonGoBot.jar --server.port=8090` so the bot management interface (for handling multiple bots) gets started on port 8090.

**Comment by casper-gh** [comment]
@jabbink anyway to disable all GUI port? I just need a cmd line logs.
