### ISSUE TITLE
Listener on port 16969 for sniping

### ISSUE THREAD

**Issue by KyleBoyer** [jabbink/PokemonGoBot#818]
I have a pogo feeder running on port 16969 and it never seems to snipe the pokemon it finds. Additionally, the feeder never even stated that a connection was established.

**Comment by muschter** [comment]
That is because this repository does not happen to have sniping. Jabbink himself even stated that it was not on the feature list at the moment. [Here is his comment.](https://i.gyazo.com/e1db10ebc552734f55183366c79e44b0.png)

**Comment by langerhans** [comment]
Closing for now as this specific thing is not supported right now. Sniping will be here at some point soon-ish I guess.
