### ISSUE TITLE
Google app password doesn't work anymore

### ISSUE THREAD

**Issue by casper-gh** [jabbink/PokemonGoBot#820]
On v4 I was able to use a generated app password for google account (no need for token) so I could automatically restart the bot after a certain amount of time.

Now even when I use app password i still need to generate a token...

**Comment by toffaste1337** [comment]
That's just how it is now, not an issue. The token doesn't change.

**Comment by casper-gh** [comment]
Actually when running the bot separately (using config.properties), I can still use my google app password.
