### ISSUE TITLE
Rocket Theme UI Bug

### ISSUE THREAD

**Issue by Elmo337** [jabbink/PokemonGoBot#821]
**Description:**
When u run Multiple Bots on the bot-settings Folder the GUI will not show on the Command Line
It Just Load

**Version:**
0.5.0

**Operating System:**
Debian 7

**Java version:**
1.8

**Comment by toffaste1337** [comment]
Same problem. Running two bots, the Command line only shows at the one running on port 8001. The one running on port 8002 keeps loading. Have tried resetting panel positions and refreshing as this has worked once before, but not anymore.
![image](https://cloud.githubusercontent.com/assets/6287600/17482078/733e72a2-5d80-11e6-8ba8-d7f9841ef204.png)

**Comment by jabbink** [comment]
Are you running 1 bot with multiple configs or multiple java instances @toffaste1337?

**Comment by jabbink** [comment]
@Elmo337 did you set a different `guiPortSocket` in both json files?

**Comment by CosmoRing** [comment]
@toffaste1337 see https://github.com/eruecco87/PokemonGoBot-RocketTheme/issues/6, that seems to be a know issue to the developer of the RocketTheme

**Comment by langerhans** [comment]
Closing as there is a related issue in the other repo.
