### ISSUE TITLE
Can't run the bot

### ISSUE THREAD

**Issue by abdellahaski** [jabbink/PokemonGoBot#822]
**Description:**
Guys I can't run the bot I get an error after i type the "java -jar PokemonGoBot-0.5.0.jar" command
I've tried the cmd with and without the admin privilege 

**Steps to reproduce:**

1. I've edited the config file and I've placed it on the same folder as the jar file
2. Opened the cmd and I've used the CD the go to folder where the jar file and I've typed: java -jar PokemonGoBot-0.5.0.jar

**Actual behavior:**
Got an error

**Stacktrace (If it's a crash):**
Here is the log: [http://pastebin.com/yHRN2tzP](http://pastebin.com/yHRN2tzP)

**Version:**
PokemonGoBot-0.5.0

**Operating System:**
windows 10 pro

**Java version:**
C:\Users\Abdellah\Desktop\pokemongobot>java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by Turtizzle** [comment]
Some other process seems to be using your GUI port already.
Try killing all remaining bot-processes from previous starts, or simply change the port in your config to something unused.

**Comment by abdellahaski** [comment]
Thanks but How could i know which process is using the GUI port?

**Comment by abdellahaski** [comment]
or how could I know the unused ports?

**Comment by Silver331** [comment]
Address already in use: bind

--server.port=8090

**Comment by abdellahaski** [comment]
It's working now but there is no GUI??

**Comment by Venome** [comment]
@abdellahaski read here https://github.com/jabbink/PokemonGoBot

**Comment by edwincheung555** [comment]
i got the same exact message except with no "Bind" after "address already in use" its just blank. http://pastebin.com/iXJB2Dap Im not really a techie or know anything much bout computers so can someone give me a step by step of how to fix it, that'd be awesome

**Comment by jabbink** [comment]
Address already in use, read the FAQ
