### ISSUE TITLE
why Got 0 pokestops?

### ISSUE THREAD

**Issue by dongqdong** [jabbink/PokemonGoBot#823]
08 agu 08:22:50 (default): Getting map of (37.80863743696821, -122.40995352748445)
08 agu 08:22:50 (default): Getting initial pokestops...
08 agu 08:22:51 (default): Got 0 pokestops

i run in intellij？

**Comment by kkacim** [comment]
Same here 
`08 août 10:10:55 (default): Getting initial pokestops...
08 août 10:10:56 (default): Got 0 pokestops
←[31;1m08 août 10:10:56 (default): Retrying in 10 seconds... ←[0m
08 août 10:11:06 (default): Got 0 pokestops
←[31;1m08 août 10:11:06 (default): Retrying in 10 seconds... ←[0m
08 août 10:11:16 (default): Got 0 pokestops
←[31;1m08 août 10:11:16 (default): Retrying in 10 seconds... ←[0m
08 août 10:11:27 (default): Got 0 pokestops
←[31;1m08 août 10:11:27 (default): Retrying in 10 seconds... ←[0m
08 août 10:11:37 (default): Got 0 pokestops
←[31;1m08 août 10:11:37 (default): Retrying in 10 seconds... ←[0m
08 août 10:11:47 (default): Got 0 pokestops
←[31;1m08 août 10:11:47 (default): Retrying in 10 seconds... ←[0m
08 août 10:11:57 (default): Got 0 pokestops
←[31;1m08 août 10:11:57 (default): Retrying in 10 seconds... ←[0m
08 août 10:12:08 (default): Got 0 pokestops
←[31;1m08 août 10:12:08 (default): Retrying in 10 seconds... ←[0m
08 août 10:12:18 (default): Got 0 pokestops
←[31;1m08 août 10:12:18 (default): Retrying in 10 seconds... ←[0m
08 août 10:12:28 (default): Got 0 pokestops
←[31;1m08 août 10:12:28 (default): Retrying in 10 seconds... ←[0m
08 août 10:12:39 (default): Got 0 pokestops
←[31;1m08 août 10:12:39 (default): Retrying in 10 seconds... ←[0m
08 août 10:12:49 (default): Got 0 pokestops
←[31;1m08 août 10:12:49 (default): Retrying in 10 seconds... ←[0m
08 août 10:12:59 (default): Got 0 pokestops`

**Comment by kkacim** [comment]
Hello, same problem here : 

![2016-08-08_10-15-42](https://cloud.githubusercontent.com/assets/11404571/17473512/1e849de2-5d51-11e6-82a2-2113e7544209.jpg)

**Comment by kkacim** [comment]
Problem fixed after i changed my starting coordinates ? weird

**Comment by LeGrosRelou** [comment]
Hi ! 

Again the same thing, since last week... Any solutions ?

**Comment by nesttle** [comment]
Same here :(

**Comment by FrancYescO** [comment]
IP Ban

**Comment by jabbink** [comment]
Make sure your lat/lng is correct and if they are, decrease `initial_map_size` to 7 or even 5 (or even 3).

Also Niantic appears to be ratelimiting to ~40 accounts per IP again. So if you have more accounts than that at once, it might fail.

**Comment by gabrielklein** [comment]
Avoid using the mobile app at the same time too :)

**Comment by gabrielklein** [comment]
I saw the same issue when setting it to Australia. New York works perfectly. (I'm in Europe.)
I have waited ~8 hours before setting it to australia.

**Comment by Mixone-FinallyHere** [comment]
40 accounts on same IP? are they just using bot to make accounts to sell? :-1:

**Comment by kkacim** [comment]
Lat/Lng are correct, initial_map_size reduced to 3. Still not able to get pokestops "Got 0 pokestops...".
Can play normal on phone, so no softban. 
And tried to run the bot with different IPs, same result ..

**Comment by gabrielklein** [comment]
Can you try with: (New York)
latitude=40.72
longitude=-74

Don't forget to kill the application on the phone....

**Comment by kkacim** [comment]
I'm in paris, so don't wanna try teleporting to New york :D

**Comment by JoshLev** [comment]
same problem with me for past 3 versions

**Comment by Mixone-FinallyHere** [comment]
kill a

**Comment by Mixone-FinallyHere** [comment]
kill and restart a couple times, always works for me

**Comment by Jobzakung** [comment]
Someone in here can fix it now?

**Comment by tloy1966** [comment]
get same problem

**Comment by Sieberkev** [comment]
[FAQ](https://github.com/jabbink/PokemonGoBot/blob/develop/FAQ.md#the-bot-doesnt-findloot-pokestops)
