### ISSUE TITLE
starting latitude problem

### ISSUE THREAD

**Issue by ahr174** [jabbink/PokemonGoBot#826]
**Description:**
Hi, this is my 1st time using bot, but is seems complicated for me.
every time I used the bot, I always got [Starting Latitude setting ("latitude") not specified in config.properties!]. 

this is the input on config.properties, there is no space before or after the latitude's value

token=
latitude=37.808
longitude=-122.41

**Operating System:**
[OSX El Capitan 10.11.6]

really appreciate your help

**Comment by Killertom63** [comment]
Mine are 

"latitude=32.780160
longitude=-96.797724"

Are you sure you've got the entire number for yours? You might not be being specific enough?

**Comment by ahr174** [comment]
i try your number man, but it doesn't work for me.

**Comment by ahr174** [comment]
here are the log and config @Killertom63 

![screen shot 2016-08-08 at 16 54 43](https://cloud.githubusercontent.com/assets/20897314/17476393/0f2b0258-5d8a-11e6-9745-a98a80fe61b8.jpg)

![screen shot 2016-08-08 at 16 56 09](https://cloud.githubusercontent.com/assets/20897314/17476396/11524fd2-5d8a-11e6-9e4d-2c20b8c47a17.jpg)

**Comment by zoegalaxy** [comment]
I have the same Starting Latitude problem, hopefully someone can help us with this. thanks

**Comment by zoegalaxy** [comment]
@jabbink brother, can you help us on this issue with the latitude problem? Thanks a lot!

**Comment by jabbink** [comment]
Are you sure your file isn't called `config.properties.rtf` or `config.properties.txt`?

**Comment by ahr174** [comment]
@jabbink yes im sure, but don't know it doesn't work for me.

![screen shot 2016-08-08 at 20 38 00](https://cloud.githubusercontent.com/assets/20897314/17481613/4a611d1c-5da8-11e6-8d1d-83c80c343e78.jpg)

**Comment by toffaste1337** [comment]
@ahr174 Try using the .json settings in the folder "bot-settings". 
Check here to get templates. #810

**Comment by ahr174** [comment]
@toffaste1337 it come out like this, but im not sure if i'm doing it right

so i just put XXXX.json file into bot-setting folder right? 

![screen shot 2016-08-08 at 21 03 38](https://cloud.githubusercontent.com/assets/20897314/17482439/fab8b7d0-5dab-11e6-8631-358c8e00d634.jpg)

**Comment by jabbink** [comment]
You have invalid characters in your json file. Open it in a text editor and show what line 1, character 11 contains.

**Comment by zoegalaxy** [comment]
I have the same issue also as @ahr174 

![screen shot 2016-08-08 at 10 28 49 pm](https://cloud.githubusercontent.com/assets/20904378/17483196/b1e130e4-5db7-11e6-85c9-951a6f33d616.png)

mine is line 1, column 3. But I don't know what is wrong.

![screen shot 2016-08-08 at 10 29 54 pm](https://cloud.githubusercontent.com/assets/20904378/17483207/b974bf1a-5db7-11e6-9769-c8b5e5f86233.png)

Also, how about the information inside config.properties... do I need to remove the username and password information since it is already inside the config.json?

**Comment by toffaste1337** [comment]
@zoegalaxy the bot-settings json configs overrides the config.properties. Are there any spaces after the curly bracket on line one?

**Comment by zoegalaxy** [comment]
@toffaste1337 I did this, and I still got error on line 1, column 3.

![screen shot 2016-08-08 at 10 36 15 pm](https://cloud.githubusercontent.com/assets/20904378/17483440/99bd1086-5db8-11e6-85fe-b5baddc36c15.png)

**Comment by toffaste1337** [comment]
Try using an online json formatter tool to check your json file.

**Comment by zoegalaxy** [comment]
Weird, it has double quotes but why the error?

![screen shot 2016-08-08 at 10 39 08 pm](https://cloud.githubusercontent.com/assets/20904378/17483533/fed488d2-5db8-11e6-9b6f-af4e1eabbdfd.png)

**Comment by toffaste1337** [comment]
Really weird, I use the same config, it works for me.

**Comment by zoegalaxy** [comment]
@toffaste1337 Notice the double quote with error and without? The one with error is curly, while the one without are just straight lines.

I was able to fix it by copying the straight-line double quotes and pasting it on the curly ones.

I got this:

![screen shot 2016-08-08 at 10 49 31 pm](https://cloud.githubusercontent.com/assets/20904378/17483905/676d67a0-5dba-11e6-96c4-d94747cd0fad.png)

BUT..... it has the same error! 😢 


![screen shot 2016-08-08 at 10 50 51 pm](https://cloud.githubusercontent.com/assets/20904378/17483979/a2828ffa-5dba-11e6-861e-145365c3bac6.png)

**Comment by zoegalaxy** [comment]
Ooops I put my username and password, anyway it's okay it is a dummy account lol.

**Comment by toffaste1337** [comment]
Change the password now :)

**Comment by zoegalaxy** [comment]
@toffaste1337 hahaha.. I changed already.

Now I'm stuck, don't know what to do hahaha...

**Comment by toffaste1337** [comment]
@zoegalaxy do you have the latest java version?

**Comment by zoegalaxy** [comment]
![screen shot 2016-08-08 at 10 58 28 pm](https://cloud.githubusercontent.com/assets/20904378/17484274/a683a660-5dbb-11e6-99ea-263b5b6f3f99.png)

@toffaste1337 Is this the latest?

**Comment by toffaste1337** [comment]
Yes, same as the newest from java update atleast, and newer than what I have.

**Comment by toffaste1337** [comment]
#846 Try to download the template from here.

**Comment by zoegalaxy** [comment]
@toffaste1337 Okay, the bot was able to login. I don't know why but somehow my textedit app messes up the file. What I did is I use a JSON online editor and copy paste the json template there.  It works.

Thanks!

I have another problem, but I'll figure it out. My bot keeps retrying and says 0 pokestop. lol

**Comment by toffaste1337** [comment]
Maybe a softban. 
change `"banSpinCount" : 0` to `"banSpinCount" : 45` or 40

**Comment by zoegalaxy** [comment]
@toffaste1337 changed it to 45 and 40, but still retrying. Is there a thread already for this issue?

**Comment by zoegalaxy** [comment]
@toffaste1337 ooops fixed it! just change the starting coordinates.

Thanks a lot for your help! Cheers!

**Comment by ahr174** [comment]
@toffaste1337 mine still have an issue with line 1 column 11 as before, even though i use online editor 

![screen shot 2016-08-08 at 22 24 22](https://cloud.githubusercontent.com/assets/20897314/17485268/5e843dba-5db7-11e6-9cdc-2d565c655ee0.jpg)

**Comment by zoegalaxy** [comment]
@ahr174 Bro, on your codes notice the italicised double quotes on your username and password.  I think it causes issues.

I use this site to create and edit the json file:  http://www.jsoneditoronline.org/#/

Open it then create a new file, then copy and paste the json.template.  Make your modifications on your latitude, longitude, username, and password.

Click save to disk, it will then go to your downloads. Just drag the file into your bot-setting folder.

It worked for me.

**Comment by ahr174** [comment]
@zoegalaxy solved, thanks all. cheers

**Comment by jabbink** [comment]
![image](https://cloud.githubusercontent.com/assets/2461972/17487039/6dfe04ca-5d93-11e6-8f9f-95abc37e2e4b.png)
Your latitude is completely wrong btw.
