### ISSUE TITLE
[Suggestion] Variable speed & precision

### ISSUE THREAD

**Issue by Dr4mEdo** [jabbink/PokemonGoBot#83]
Always in order to approach reality, I think it could be a good idea to add a variability to speed (who is always walking the same speed ?) and to the GPS precision.

Something like 2.5±0.3 m/s, what do you think ?

**Comment by mbaan** [comment]
Perhaps the same for how many items you hold? Ranges instead of static value.

**Comment by jabbink** [comment]
Implemented.
