### ISSUE TITLE
Best latitude longitude?

### ISSUE THREAD

**Issue by dwfz** [jabbink/PokemonGoBot#832]
I've been using central park's but I was wondering if anybody else had a successful location, trying to get that xp/hr up

**Comment by Killertom63** [comment]
I do central Dallas, but that's only because I live near there.

**Comment by ArgonQQ** [comment]
South of central park is awesome!

**Comment by russr123** [comment]
carp nest  37.810285, -122.417823

https://skiplagged.com/catch-that/#37.806,-122.406,15

**Comment by russr123** [comment]
only still working map that i know of, but vary hit and miss on citys..

https://skiplagged.com/catch-that/#41.966,-91.535,4

**Comment by jabbink** [comment]
# Central Park 40.775737 -73.971749
# Central Park Zuid 40.767202 -73.976699
# Santa Monica Pier 34.008185 -118.498067
# Farfetch'ed 34.684021 135.491545
