### ISSUE TITLE
Starting Latitude setting ("latitude") not specified in config.properties

### ISSUE THREAD

**Issue by pedda007** [jabbink/PokemonGoBot#833]
Hi Guys,
could anybody help me with this error message?
Did i something wrong?

Thanks,
pedda.

**Comment by Dewinster** [comment]
Hi Pedda007,

The value you've entered in the Latitude field in the config file is not a valid Latitude value.

Regards,
Dewin

**Comment by pedda007** [comment]
Hi Dewinster,

thanks for your quick reply. I checked the longitude and the latitude via google maps. And they are right. I already deleted the last 2 digits of both values, but i got the same error. In the attached file  i made a screenshot of the whole console. Maybe you or anybody else can help me out.

Thanks,
Pedda.
![bildschirmfoto 2016-08-08 um 08 55 30](https://cloud.githubusercontent.com/assets/20835895/17471625/f38eed0a-5d45-11e6-979d-9da2e98da1cc.png)

**Comment by pedda007** [comment]
And here is a screenshot of the config file.
![bildschirmfoto 2016-08-08 um 08 57 07](https://cloud.githubusercontent.com/assets/20835895/17471672/2f656b24-5d46-11e6-8d9e-4dbc4738a187.png)

**Comment by Dewinster** [comment]
Hmm seems legit to me.
Can you enter these values just to try:

latitude=40.781027
longitude=-73.967429

**Comment by pedda007** [comment]
Same error again :( I really don't know what i did wrong....

**Comment by Killertom63** [comment]
Can you ensure you're not copying and pasting them in. Sometimes when copy and pasting it causes unneeded spaces.

**Comment by pashorizer** [comment]
Looks like your `config.properties` is not in the same folder as your jar file. Since it is defaulting values which you have already set.

**Comment by pedda007** [comment]
I don't know what i did wrong. I downloaded the properties file again, changed the longitude and the latitude and it worked out. So thanks guys for your answers!

**Comment by ahr174** [comment]
i got same problem man, tried it many time with different location
