### ISSUE TITLE
Gui "Blocked wrong request"

### ISSUE THREAD

**Issue by lummuswayne** [jabbink/PokemonGoBot#834]
Description:
I have the config setup to go to port 8001 and when i try to load the page it shows (in the console).
warn 10284 - - - [tLoopGroup-3-16] c.c.Socketio.handeler.AuthorizeHandler       : Blocked wrong request! url: /, ip: /0:0:0:0:0:0:0:1:56599
warn 10284 - - - [tLoopGroup-3-16] c.c.Socketio.handeler.AuthorizeHandler       : Blocked wrong request! url: /favicon.ico, ip: /0:0:0:0:0:0:0:1:56599

No idea the problem so no idea how to reproduce this for others.

Expected behavior:
Web Gui should load

Actual behavior:
Stays Blank and and gives the above warning in console

Version:
 0.5.0

Operating System:
 Windows 10 Home

Java version:
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

**Comment by Killertom63** [comment]
Set your start.bat to 
"java -jar PokemonGoBot-0.5.0.jar --server.port=8090"

Then connect to - "http://pogo.abb.ink/RocketTheme/" for GUI.

**Comment by citruz** [comment]
Don't try to access the port directly, use the GUI located at [http://pogo.abb.ink/RocketTheme/](http://pogo.abb.ink/RocketTheme/) (as it also says in the console log).

**Comment by lummuswayne** [comment]
thank you very much for the simple fix its working good and well now 
thanks a bunch
