### ISSUE TITLE
GPX support

### ISSUE THREAD

**Issue by joeyroosing** [jabbink/PokemonGoBot#835]
**Description:**
Not really an issue, just curious if GPX support will be added back in. The ability to go from a to b and catch pokemon along the path was brilliant.

**Expected behavior:**
Upload a GPX, the trainer will walk to that location and catch everything in its path.

**Version:**
v0.5.0

**Operating System:**
Windows

**Java version:**
Java 8 latest

**Comment by jabbink** [comment]
The old UI has GPX support

http://pogo.abb.ink/0.5.0-alpha4/map.html

@eruecco87 made the new one I think, maybe he will add it to `RocketTheme`
