### ISSUE TITLE
Is it possible to run behind vpn

### ISSUE THREAD

**Issue by swtrpeter** [jabbink/PokemonGoBot#837]
**Description:**
Tried running behind VPN with no success. Is it possible to run this behind VPN ? 

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]

**Expected behavior:**
[What should happen?]

**Actual behavior:**
[What actually happens]

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
[The version of the bot you used; when self-compiled: :exclamation: the commit hash :exclamation:]

**Operating System:**
[Your operating system]

**Java version:**
[Full output of `java -version`]

**Comment by swtrpeter** [comment]
I understand this may be a stupid question but surely someone can help me out. Try to run it and terminal pops up then goes away. @jabbink

**Comment by staurakis** [comment]
type in the run line of the start menu of windows: cmd (or press [windows key] + r and then type cmd).
Then navigate to the directory you like and then run the execute command. This will not close the windows after an error and you will be able to see it.

**Comment by langerhans** [comment]
Sure it's possible. If it doesn't work behind a VPN, then that's not a bot issue. Also try actually filling out the issue template next time...
