### ISSUE TITLE
bug pokestop

### ISSUE THREAD

**Issue by Thecraftdu34** [jabbink/PokemonGoBot#845]
08 août 15:51:02 (default: BotLoop): Looted pokestop "Mairie Du 5e Arrondissement"; +0 XP: [] 
08 août 15:51:05 (default: BotLoop): Getting map of (45.75777333192896, 4.801213068142736)
08 août 15:51:06 (default: BotLoop): Looting nearby pokestop "Mairie Du 5e Arrondissement"
08 août 15:51:07 (default: BotLoop): Looted pokestop "Mairie Du 5e Arrondissement"; +0 XP: [] 
08 août 15:51:08 (default: WalkingLoop): Destination reached.
08 août 15:51:10 (default: BotLoop): Getting map of (45.75770710305223, 4.801340899409302)
08 août 15:51:11 (default: BotLoop): Looting nearby pokestop "Mairie Du 5e Arrondissement"
08 août 15:51:12 (default: BotLoop): Looted pokestop "Mairie Du 5e Arrondissement"; +0 XP: [] 
08 août 15:51:13 (default: BotLoop): Walking to pokestop "Aire De Jeu Nénuphar"

**Comment by toffaste1337** [comment]
Does it get stuck in this "loop" forever, or does it just stop there for a while? Sometimes it will try again a couple of times untill you get XP and loot from the pokestop.

**Comment by jabbink** [comment]
You're soft banned. You teleported. Unban yourself by setting the ban_* parameter to 40.
