### ISSUE TITLE
File not found exception config.properties

### ISSUE THREAD

**Issue by limyangsern** [jabbink/PokemonGoBot#848]
Can someone help with this issue
![screen shot 2016-08-08 at 10 53 43 pm](https://cloud.githubusercontent.com/assets/20908217/17484168/53877a7c-5dbb-11e6-9800-4962e9771036.png)

**Comment by Sieberkev** [comment]
Start it from the directory of the JAR file (I can see in your screenshot you aren't).

So do `cd ~/Downloads/1/` first, and run the jar file in the directory where the files are at :)

(or move the jar file + configuration to a separated directory, cd to there and run from there)

**Comment by limyangsern** [comment]
OMG THANKS A LOT BRO!
