### ISSUE TITLE
Show the CP of a pokemon on encounter

### ISSUE THREAD

**Issue by ToMeRhh** [jabbink/PokemonGoBot#85]
something like:
Found pokemon EEVEE (CP=**XXX**)
Encountered pokemon EEVEE 
Caught a EEVEE using ITEM_POKE_BALL 

I looked at 'encounterResult', and it doesn't look like there's a CP field there, but I saw other implementations that does have this information.

**Comment by mroge009** [comment]
Where did you see CP implementation on pokemon encounter?

**Comment by ToMeRhh** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/pokemon_catch_worker.py#L39
it uses python pgoapi, but I don't know how it gets this information...

**Comment by CosmoRing** [comment]
I already added that on #36. waiting to see if it will get added

**Comment by mroge009** [comment]
@ToMeRhh Yeah, I don't know how they got that information.  Is this JAVA API Complete?
