### ISSUE TITLE
PokeStop not gathering info. Wont collect items or catch pokemon

### ISSUE THREAD

**Issue by brewskis** [jabbink/PokemonGoBot#851]
After running the .jar I am connected to the server but after I am logged in, it wont do anything after that.

 08 Aug 08:21:44 (default): Getting initial pokestops...
08 Aug 08:21:44 (default): Got 100 pokestops
08 Aug 08:21:44 (default): Running socket server on port 8001
08 Aug 08:21:44 (default: BotLoop): Getting map of (33.542016582310815, -117.78379826762377)
08 Aug 08:21:44 (default: BotLoop): Looting nearby pokestop 7c22fee9af2c466dbee2020c04320776.16
2016-08-08 08:21:44.616  INFO 78200 --- [        default] c.c.socketio.SocketIOServer              : Session store / pubsub factory used: MemoryStoreFactory (local session store only)
2016-08-08 08:21:44.727  INFO 78200 --- [ntLoopGroup-2-1] c.c.socketio.SocketIOServer              : SocketIO server started at port: 8001
08 Aug 08:21:44 (default): Open the map on http://pogo.abb.ink/RocketTheme/ 
08 Aug 08:21:45 (default: ProfileLoop): Profile update: 557252 XP on LVL 23; 122252/125000 (97.80%) to LVL 24 
08 Aug 08:21:45 (default: ProfileLoop): XP gain: 0 XP; Pokemon caught/transferred: 0/0; Pokemon caught from lures: 0; Items caught/dropped: 0/0;
Pokebank 121/250; Stardust 13234; Inventory 215/350 
08 Aug 08:21:45 (default: BotLoop): Looted pokestop 7c22fee9af2c466dbee2020c04320776.16; +0 XP: [] 
08 Aug 08:21:45 (default: BotLoop): Walking to (33.54177, -117.78377) in 54.23027066211077 steps.
08 Aug 08:21:49 (default: BotLoop): Getting map of (33.54196327934681, -117.7838006340711)
08 Aug 08:21:49 (default: BotLoop): Looting nearby pokestop 98aa2324fe354c4180ae5840463881c5.12

**Comment by pashorizer** [comment]
You are softbanned. Use this https://github.com/jabbink/PokemonGoBot/blob/develop/config.properties.template#L112

**Comment by brewskis** [comment]
Thank you, so what does this mean? what do i need to change the value to?

**Comment by bhowell2** [comment]
Set it to 40

**Comment by bhowell2** [comment]
Set it to 40

**Comment by Danman00** [comment]
Set ban_spin_count= to 40
