### ISSUE TITLE
can't Run the bot 

### ISSUE THREAD

**Issue by ghostb0y** [jabbink/PokemonGoBot#854]
i Run Jar File and this what i got 
 http://store2.up-00.com/2016-08/1470673594331.jpg 

and the config.properties File

# PTC/Google login credentials
username=
# Choose plaintext or base64'd password
password=
base64_password=
# Token to login directly
token=15
latitude=xxxxxxx
longitude=xxxxxxxxxxxx
# Desired probability to catch Pokemon with 1 throw
desired_catch_probability=0.4
# Desired probability to catch unwanted Pokemon (obligatory_transfer; low IV; low CP)
# Set to -1 to not attempt catching at all
desired_catch_probability_unwanted=0.0
# Number of nearest unused pokestops to randomly select
# The next pokestop from (1/infinite)
random_next_pokestop_selection=5
## Walking
# Meters per second
speed=20
# Should the bot follow the streets (true) or just go directly to pokestops/waypoints
follow_streets=false
# Should the bot loot the pokestops (true/false)
loot_pokestop=true
# Should the bot catch pokemons (true/false)
catch_pokemon=true
# Should the bot auto fill incubators with eggs (true/false)
auto_fill_incubator=true
## Items drop
# Should the bot EVER drop items (true/false)
drop_items=true
# Max number of each item that the bot should keep if "drop_items" is enabled
# Use -1 in an item to never drop this specific item
# The default values add up to 350
item_revive=20
item_max_revive=10
item_potion=0
item_super_potion=30
item_hyper_potion=50
item_max_potion=50
item_poke_ball=55
item_great_ball=-1
item_ultra_ball=-1
item_master_ball=-1
item_razz_berry=40
item_lucky_egg=-1
item_incense=-1
item_lure_module=-1
## Extra Info
# Should the bot display rewards pokestop (true/false)
display_pokestop_rewards=true
# Should the bot display if it caught a pokemon from a lure (true/false)
display_if_pokemon_from_lure=true
# Should the bot display rewards when catching pokemon (true/false)
display_pokemon_catch_rewards=true
# Display keepalive coordinates
display_keepalive=true
# Should the bot display information of where it's walking to (true/false)
# This will show the name of the pokestop that it's walking to and
#   replace on the loot log the pokestop id for its name
# WARNING:  this will increase the https requests without any need. If
#           the servers are slow it's recommended to turn off this setting
display_pokestop_name=false
## Pokemon Transfer
# Should the bot auto transfer duplicate pokemon
autotransfer=true
# Minimum amount of pokemon type to keep
keep_pokemon_amount=1
# Maximum amount of pokemon type to keep (-1 to keep all)
max_pokemon_amount=-1
# Sort by IV first instead of CP
sort_by_iv=false
# Always throw curveballs
always_curve=false
# Never use berries
never_use_berries=true
# Allow leaving the starting area
allow_leave_start_area=false
# Max distance from starting point the bot should ever go in meters
# (-1: only limited by the initial pokestops (~3*3km); with allow_leave_start_area=true unlimited)
spawn_radius=-1
# Number of times the pokestop should be spun to attempt softban bypass (0 to disable, 40 recommended value to work)
ban_spin_count=0
# Set timer in seconds to go back to the starting pokestop (-1 disabled)
timer_walk_to_start_pokestop=-1
# Set profile update timer (Default: 60)
profile_update_timer=60
# Minimum IV percentage to keep a pokemon (to ignore IV: use -1)
# between 0 and 100, suggested 80
transfer_iv_threshold=80
# Minimum CP to keep a pokemon (to ignore CP: use -1)
transfer_cp_threshold=600
# List of pokemon you don't want to transfer regardless of CP
# The names must be divided by a ","
# If you want all pokemons to be transferred just leave it blank
ignored_pokemon=
# List of pokemon you always want to transfer regardless of CP
obligatory_transfer=DODUO,RATTATA,CATERPIE,PIDGEY
# Port where the socketserver should listen, 0 = do not listen
gui_port_socket=8001
# Export player/pokemondata on Profile Update. Options are:
#   *empty*  Don't export (default)
#   CSV      Correct USA/UK CSV format ("," as delimiter and "." as decimal separator)
#   DSV      European CSV/DSV format (";" as delimiter and "," as decimal separator)
#              Use this one if your MS Excel can't handle the default CSV option
export=
# Initial map size (S2 tiles) to fetch (max. 9: ~3*3km area)
initial_map_size=9

can Explain with simple way how to Setup :8ball:  
thanks

**Comment by CosmoRing** [comment]
Plz search before posting.

See: #749 #726 #690 #806

**Comment by Killertom63** [comment]
Change your start.bat to 

"java -jar PokemonGoBot-0.5.0.jar --server.port=8090"

**Comment by ghostb0y** [comment]
it is Work thanks
