### ISSUE TITLE
Adding to the ptc.json file

### ISSUE THREAD

**Issue by classicalDonkey** [jabbink/PokemonGoBot#855]
**Description:**
I am using the json file to run multi bots at once and I would like to know is the list in a set order, can we add things to it?  As I have noticed that in the old file you have the line 

# Should the bot camp around lured x pokestops (-1 = off; 1 = one needs to be in range; 2 = two..., etc)
camp_lure_pokestop=-1

Can I just add 

"camp_lure_pokestop" : true, 

to the json file at the end?

**Comment by Kalerion** [comment]
Default setting is:
"campLurePokestop" : -1

So it's automatically disabled.

**Comment by classicalDonkey** [comment]
@kalerion Ya but can i just add it to the file or does it go in a set order?

**Comment by toffaste1337** [comment]
@classicalDonkey put it under `"lootPokestop" : true,` for example, make sure to end the next line with a comma.

**Comment by Kalerion** [comment]
@classicalDonkey Anywhere in the file.(But outside of closed settings like items to throw away etc) I have my "default" .json template which only has a few settings since the bot will migrate the rest.
