### ISSUE TITLE
Feature Requests: Automaticall accept TOS / Complete tutorial / Give account a name

### ISSUE THREAD

**Issue by Kalerion** [jabbink/PokemonGoBot#856]
**Automaticall accept TOS**
`Every new account needs to accept the TOS ingame before it can catch pomeon`
-> Make the bot auto-accept the TOS

**Complete tutorial**
`New accounts are given a tutorial where they need to catch one of the 3 (4) starters`
-> Complete tutorial so Bots wont get flagged for never completing tutorial

**Complete tutorial**
`New accounts don't have a name`
-> New accounts could get flagged if they didn't choose a name. Have a setting where you could "provide" a username and if it's taken it'll add 1 random number to it. If it's still take add another.. etc (default setting is to *NOT* name new account)

**Comment by CosmoRing** [comment]
And while you're at it, you can go and add a way to choose a team.

**Comment by mtchm** [comment]
This literally takes 2 minutes of your time...

**Comment by Kalerion** [comment]
@mtchm Not if you're running multiple bots at a time for different locations. 

So you would have to spoof to specific locations first (So you won't get softbanned / have to wait multiple hours) and then repeat the tutorial 10+ times? I assumed that the question makes it clear that this is intended for multiple bots / automation.

**Comment by mtchm** [comment]
You can do the tutorial on your mobile without GPS on, your 'first' login would still be at the location given in your config file. There are so many other features that should have priority imo.

**Comment by smileytechguy** [comment]
Its not in the current API, you can't use it

**Comment by Sieberkev** [comment]
This is implemented with the new API PR #1237
