### ISSUE TITLE
Bot is not running

### ISSUE THREAD

**Issue by edwincheung555** [jabbink/PokemonGoBot#861]
**Description:**
my bot doesnt seem to work. ive gotten it to work in previous versions quite easily but when i run this version, i get this long error

**Steps to reproduce:**

1. Do all step necessary, download, fill in blanks, etc 
2. run bot

**Expected behavior:**
it should work

**Actual behavior:**
i get this a really long error

**Stacktrace (If it's a crash):**
http://pastebin.com/iXJB2Dap

**Version:**
PokemonGoBot-0.5.0.jar

**Operating System:**
Mac OS X El Capitan 10.11.5

**Java version:**
1.8.0_101

**Comment by mtchm** [comment]
https://github.com/jabbink/PokemonGoBot/issues/806#issuecomment-238089960
