### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by Benzt2h** [jabbink/PokemonGoBot#866]
http://imgur.com/a/j5UDT
http://imgur.com/a/KbTAy

**Comment by Peyphour** [comment]
Search before posting ...

#854 #749 #806 #690

**Comment by Peyphour** [comment]
https://github.com/jabbink/PokemonGoBot/issues/854#issuecomment-238317209

**Comment by Benzt2h** [comment]
thx working Start the bot : java -jar PokemonGoBot-0.5.0.jar --server.port=8090
