### ISSUE TITLE
[FEATURE] Movesets in GUI

### ISSUE THREAD

**Issue by Sadye** [jabbink/PokemonGoBot#871]
Could it be possible to get Movesets (+ dps?) in the GUI. 

I have a snippet to calculate dps and possible dps including evolutions (and possible movesets). It's in java though.

**Comment by Sieberkev** [comment]
The build-in webserver has been removed and replaced with some [external GUI](https://github.com/jabbink/PokemonGoBot/tree/gh-pages#custom-de-centralized-guis)'s.

We do not maintain their repositories, but you can ask on their issue trackers for extra functionality :)
