### ISSUE TITLE
The bot does not calculate IV first then CP.

### ISSUE THREAD

**Issue by kiaph** [jabbink/PokemonGoBot#875]
**Description:**
[Short description of the issue observed. If this is feature request you can modify the template as required.]

**Steps to reproduce:**

1. [Step 1]
Set config to select IV first by setting the false value to true.
2. [Step 2]
Set the IV and CP values to the numbers you would like.

**Expected behavior:**
[What should happen?]
The bot should check the IV, if below 80%  git rid of it.
The bot should keep otherwise.
If the bot should keep, the bot checks if above CP 500
If below 500 the bot should transfer to pokemon
The bot should keep otherwise.

**Actual behavior:**
[What actually happens]
The bot keeps the pokemon if it qualifies for IV,
and if IV is off, the bot keeps it if it qualifies just for CP
The bot never considers the second term only the first, thus feeling pokemon storage with
A: A bunch of weak CP with strong IV pokemon 
B: A bunch of strong CP with weak IV pokemon.

A and B are unavoidable , but can be greatly reduced. Unavoidable because my CP value has to be low enough to get 1of3_Evolve_Stages_pokemon as well as 1of2_Evolve_Stages_pokemon because the CP max with good IVs between the two vary about 200CP it basically forces me to accept a bunch of unwanted pokemon as it is. However due to the bot not sorting them 100% correctly I end up with way more of A and B conditions than what I would experience if the bot did check both IV and CP before keeping the pokemon.

Remember the preferred way to deal with the keep 1 of each pokemon option is to allow the only exception to this  &&  is for pokemon that I only have 1 of, if keeping the pokemon means I end up with 2, transfer the worst of the two.

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
[The version of the bot you used; when self-compiled: :exclamation: the commit hash :exclamation:]
latest as of 8/7/2016 pokebot 0.5.0 jar (havent checked to see if their is a newer one, I will feel stupid if their is and this issue is already resolved, if so, please excuse my stupidity)
**Operating System:**
[Your operating system]
window 10

**Java version:**
[Full output of `java -version`]
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Kiaph>
C:\Users\Kiaph>java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) Client VM (build 25.101-b13, mixed mode)

C:\Users\Kiaph>

**Comment by jabbink** [comment]
If you don't care for cp, would setting the XP threshold to -1 work for you?

**Comment by Sieberkev** [comment]
Closed due to inactivity. If the solution provided is not the solution you want, please explain ;)
