### ISSUE TITLE
Not getting inital pokestops

### ISSUE THREAD

**Issue by loganrussell48** [jabbink/PokemonGoBot#876]
**Description:**
The bot, when started, searches for the initial pokestops nearby and then will not succeed. It will then retry in 10 seconds, but it will never get them. 

**Steps to reproduce:**

1. Start Bot

**Expected behavior:**
Bot should run following the configuration in the file

**Actual behavior:**
bot tries repeatedly to get pokestops, always getting 0.

**Version:**
0.5.0

**Operating System:**
Ubuntu

**Java version:**
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by pizdece** [comment]
Try initial_map_size=6

**Comment by langerhans** [comment]
Duplicate, alsoo inactive. Try the above mentioned solution, if that doesn't work report back in one of the existing issues about it.
