### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by mcfowlz** [jabbink/PokemonGoBot#878]
when i run it it stops after saying: default): Starting Latitude setting ("latitude") not specified in config.properties! 

i have put a latitude and longitude into the textedit 
# Token to login directly
token=
latitude=51.5055
longitude=-0.0754
^^ thats what i put in

and whats a token?

**Comment by toffaste1337** [comment]
Consider using the new json config. 
Google: https://github.com/jabbink/PokemonGoBot/issues/810#issuecomment-238094907
PTC: https://github.com/jabbink/PokemonGoBot/issues/810#issuecomment-238096287

**Comment by jabbink** [comment]
Run the bot from the directory that contains the config file.
