### ISSUE TITLE
add some "interrupt handlers" to show useful data

### ISSUE THREAD

**Issue by ToMeRhh** [jabbink/PokemonGoBot#88]
The idea is to have information showing on request, rather then filling the console every second or so.
Preferably the information will show on a CTRL+key keypress, what I had in mind (maybe someone would suggest more interesting stuff):

```
Current inventory:
Item_name -> Item_amount
(there isn't a lot of item types; we can put all here)

Top 5 Pokemons:
1. pokemon_name -> pokemon_cp
...
5. pokemon_name -> pokemon_cp

XP-Gained, items collected/dropped, pokemons collected/dropped (instead of spamming the console)

```

**Comment by jabbink** [comment]
@apottere is working on a web interface, would that be something you like as well instead of info on interrupt? If yes, I close this and let @apottere work on the web thingy.

**Comment by ToMeRhh** [comment]
a web interface that could show all the info I suggested? hell yea @apottere!!
