### ISSUE TITLE
Not sure how to fix but please help

### ISSUE THREAD

**Issue by trevorantram** [jabbink/PokemonGoBot#880]
Not sure why this happens 
<img width="1280" alt="screen shot 2016-08-08 at 10 20 09 pm" src="https://cloud.githubusercontent.com/assets/18074199/17502507/785a686e-5db6-11e6-8961-07c00d8fee3c.png">

<img width="1280" alt="screen shot 2016-08-08 at 10 20 13 pm" src="https://cloud.githubusercontent.com/assets/18074199/17502508/7bc0aae0-5db6-11e6-8d9c-a3e3c0328189.png">

it originally worked then it started doing this.

**Comment by toffaste1337** [comment]
Try this. https://github.com/jabbink/PokemonGoBot/issues/858#issuecomment-238388259

**Comment by trevorantram** [comment]
did not work

**Comment by langerhans** [comment]
You have a bot still running in the background with the same gui_socket_port setting. Either close the bot fully before restarting it or change the ports. Also the latest version will retry to bind to the port automatically.
