### ISSUE TITLE
[Question] Slowing down the bot

### ISSUE THREAD

**Issue by vamirineni87** [jabbink/PokemonGoBot#884]
**Description:**
Is it currently possible to limit the actions to be more human like? For example, if I increase my threshold for CP or IV, when the bot starts, it immediately transfers all. May be 3 a second. Its not realistic. Is there a way to delay transfer one every 3 - 5 secs?

Similarly any other actions that humans do, catching pokemon, evolving, dropping... is it possible to slowdown the bot?

**Comment by marcoaca** [comment]
Niantic can detect that you are not playing with the real app... Does not matter if the bot looks more human! At some point we will all be banned lol, so enjoy that extra xp/hr while it lasts ☺
