### ISSUE TITLE
Exception in thread "default" java.io.FileNotFoundException

### ISSUE THREAD

**Issue by JayZ-98** [jabbink/PokemonGoBot#888]
**Description:**
I've been getting these errors even though my file is a ".properties".
Undertow started on port(s) 8080 (http)
Exception in thread "default" java.io.FileNotFoundException: config.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:77)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

What should i do to fix this?

**Comment by Tom2942** [comment]
1. Create a new text document
2. Go to Format > Make Rich Text
3. Copy the settings from your original config.preferences to the new text document
4. Save the file

**Comment by addisonrudd** [comment]
@Tom2942 i have the same problem. I did as you said and it still did it. Any other tips?

**Comment by limyangsern** [comment]
check my previous issue, remember to CD to the directory first before launching jar

**Comment by addisonrudd** [comment]
@limyangsern i did that also. i think. Do you mean typing "cd" then putting the folder in.

**Comment by limyangsern** [comment]
@addisonrudd Yes, we tend to forget cd to the directory before we launch the jar, and also check if your extension is correct, try to screenshot here

**Comment by zoegalaxy** [comment]
has something to do with the file extension of config.properties
see this #889

**Comment by ChesterChin92** [comment]
Guys, If you want to skip all the typing. create a .bat files and paste the code below.

The code will resolve your directory and run the program directly. :-) Cheers. 

`@echo off
cd %~dp0
echo Changed directory to %~dp0
java -jar PokemonGoBot-0.5.0.jar
pause`

**Comment by staurakis** [comment]
@jabbink I seriously don't believe it has anything to do with paths etc.....
This is a server side problem which this program cannot overcome after it happens...

**Comment by limyangsern** [comment]
@staurakis  no, its definitely your directory problem, i solved mine, which is same as urs!

**Comment by limyangsern** [comment]
![screen shot 2016-08-08 at 10 53 43 pm](https://cloud.githubusercontent.com/assets/20908217/17511206/76a9dcea-5e54-11e6-8b41-ac32c9b51466.png)

**Comment by limyangsern** [comment]
1. make sure your extension is correct.
2. go terminal, type cd [directory]
3. type java -jar [ur file name]

**Comment by staurakis** [comment]
@limyangsern i am running on a windows machine and i always go and run the program from the directory is in......
I execute it as you suggest (ofcourse) and no i still have the issue....

**Comment by limyangsern** [comment]
check if windows have changed your file to .txt

**Comment by staurakis** [comment]
:) no it is the correct extension....
![clipboard03](https://cloud.githubusercontent.com/assets/17766054/17511421/742aac48-5e2b-11e6-9c27-eb5dd558ce95.jpg)
![clipboard02](https://cloud.githubusercontent.com/assets/17766054/17511422/742c6b00-5e2b-11e6-8d9a-4e33d8cbbae8.jpg)

**Comment by staurakis** [comment]
as said before, i have replicated the issue. The issue is server side error. The problem is there is code to 'catch' the issue/error and overcome it.... @jabbink

**Comment by jabbink** [comment]
There is no "server side issue". You are clearly not running the jar from the directory that also contains your config.properties.

**Comment by staurakis** [comment]
@jabbink of course. I was referring to Niantic.
Secondly, as you can also see from the screen captures above, i am running the jar file frim the same directory as the config file.

**Comment by staurakis** [comment]
Sorry @jabbink my mistake, i was referring to the authorization issue.
