### ISSUE TITLE
Keep getting error please help 

### ISSUE THREAD

**Issue by addisonrudd** [jabbink/PokemonGoBot#889]
Undertow started on port(s) 8080 (http)
Exception in thread "default" java.io.FileNotFoundException: config.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:77)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
2016-08-09 02:58:40.261  INFO 1146 --- [           main] ink.abb.pogo.scraper.MainKt              : Started MainKt in 4.205 seconds (JVM running for 4.793)

**Comment by rbailloux** [comment]
Seems pretty clear to me. You need to have your config.properties file in the same folder as your jar.

**Comment by addisonrudd** [comment]
@rbailloux i do.

**Comment by Casiuss** [comment]
No you dont.
Exception in thread "default" java.io.FileNotFoundException: config.properties (No such file or directory)
clearly says it can't find its config file

**Comment by zoegalaxy** [comment]
@addisonrudd double check that your config.properties file extension is not config.properties.rtf and/or config.properties.txt

TextEdit does this therefore right click on the config.properties file, select Get Info, change the config.rtf to config.properties

![screen shot 2016-08-09 at 3 08 04 pm](https://cloud.githubusercontent.com/assets/20904378/17507603/224a64e6-5e43-11e6-943b-2488813b7495.png)

**Comment by addisonrudd** [comment]
@zoegalaxy THANK YOU SO MUCH

**Comment by addisonrudd** [comment]
@zoegalaxy now i have another problem. It says long and lat aren't set and then stops. But I've checked everything a hundred times and they are set and correct.

**Comment by zoegalaxy** [comment]
@addisonrudd I had the same problems as you when I first use the bot haha..

1. Error cannot find config.properties --> extension issue, make sure file is not *.rtf
2. Problem with latitude and longitude --> use *.json instead, refer to this #810 
3. Problem with latitude and longitude --> Even with *.json, you will encounter latitude error. my theory, when using TextEdit to modify the *.json file it somehow change the normal double quote into a italicised double quote. Not sure why, but program sees this as an error. My solution, use the online JSON editor. Reference #826 

I use this site to create and edit the json file: http://www.jsoneditoronline.org/#/

Open it then create a new file, then copy and paste the json.template. Make your modifications on your latitude, longitude, username, and password.

Click save to disk, it will then go to your downloads. Just drag the file into your bot-setting folder.

It worked for me.

**Comment by addisonrudd** [comment]
@zoegalaxy okay thanks. So do i delete the .properties one. Or keep it there and put the other in in the settings

**Comment by zoegalaxy** [comment]
@addisonrudd you can keep it there, config.json will override the config.properties

**Comment by addisonrudd** [comment]
@zoegalaxy i still got the same error

**Comment by rbailloux** [comment]
can you show us the latitude / longitude part of your config file ?

**Comment by addisonrudd** [comment]
@rbailloux its for sure not that. Its something else.  let me show you guys my folders
<img width="761" alt="screen shot 2016-08-09 at 3 53 33 am" src="https://cloud.githubusercontent.com/assets/20824760/17508820/e4a91618-5de4-11e6-8b76-1c1b7f9e360e.png">

**Comment by zoegalaxy** [comment]
@addisonrudd where are the rest of the files?? also, put the config.json inside the bot-settings folder.

Your bot folder should look like this:

![screen shot 2016-08-09 at 4 06 38 pm](https://cloud.githubusercontent.com/assets/20904378/17509205/5aeb1c7a-5e4b-11e6-81ea-f89345e5882e.png)

**Comment by addisonrudd** [comment]
@zoegalaxy where do i get the rest of the files?

**Comment by zoegalaxy** [comment]
@addisonrudd oh wait.. I'm not sure if they are really needed. I just have them inside my folder.  Anyway, try to put the json file first inside the bot-settings folder. see if it'll work.

**Comment by addisonrudd** [comment]
@zoegalaxy then this comes up

<img width="575" alt="screen shot 2016-08-09 at 4 12 13 am" src="https://cloud.githubusercontent.com/assets/20824760/17509343/7a15f390-5de7-11e6-8bb2-542fc8a77ab1.png">

**Comment by langerhans** [comment]
Your JSON file is malformed. Please check the official discord for such support questions as this is not a bot issue really ;)
