### ISSUE TITLE
Logging to .txt

### ISSUE THREAD

**Issue by kasagon** [jabbink/PokemonGoBot#91]
Would it be possible to log every action to a .txt file? 

I would really appreciate that since CMD doesn't show everything after a while, and since I got errors when I leave the bot running for a while, so I can't watch back what happened.

**Comment by jabbink** [comment]
http://stackoverflow.com/questions/11239924/windows-batch-tee-command might help for now.

For Mac OS X and Linux users: `java -jar pogo.scraper.jar | tee output.txt`

**Comment by russr123** [comment]
i use this as a launch .bat file

--------------------------------------
set LOGFILE=POGO.log
:: Max log file size allowed in bytes before rotation and archive. 1048576 bytes is one megabyte
set LOG_MAX_SIZE=104857600
if not exist %LOGFILE% echo. > %LOGFILE%

:: If the log was too big, go ahead and rotate it.
del %LOGFILE%.ancient 2>NUL
rename %LOGFILE%.oldest %LOGFILE%.ancient 2>NUL
rename %LOGFILE%.older %LOGFILE%.oldest 2>NUL
rename %LOGFILE%.old %LOGFILE%.older 2>NUL
rename %LOGFILE% %LOGFILE%.old 2>NUL

java -jar pogo.scraper-all-0.3.0.jar  >> "%LOGFILE%" 2>NUL
pause


-------------------------------

u wont see any output in the cmd window, so you will need to open the log to see the google login info

**Comment by pr0ves** [comment]
You can use `tee` which does the same thing as echo but prints the output on the terminal too.
It's not implemented in windows but just google `tee windows` and you'll find the version for windows

**Comment by iamthasasquatch** [comment]
Using this you lose the colors in the console window however it works.

http://www.softpedia.com/get/System/System-Miscellaneous/Wintee.shtml

put that in same folder and run make a batch file that does

gradlew run | wtee logname.txt

**Comment by apottere** [comment]
For linux users, you can use `tee -a out.txt` to append to the log file and not delete it every time.

**Comment by iamthasasquatch** [comment]
here is the command I use for logging it to a timestamp file.

bat file named start.bat

gradlew run | wtee %time:~0,2%-%time:~3,2%-%time:~6,2%_%date:~-10,2%-%date:~-7,2%-%date:~-4,4%Log.txt

or
java -jar pogo.scraper-all-0.3.0.jar | wtee %time:~0,2%-%time:~3,2%-%time:~6,2%_%date:~-10,2%-%date:~-7,2%-%date:~-4,4%Log.txt

**Comment by jabbink** [comment]
Closed in #894
