### ISSUE TITLE
Eggs are not being Incubated

### ISSUE THREAD

**Issue by ajorgensen** [jabbink/PokemonGoBot#911]
**Description:**
I have an egg in an incubator that I had manually placed there. When running the bot I expect that the egg should continue incubating however it stays at 2.6 / 5 km and does not advance regardless of distance walked. I have the bots walking rate set to 2.0 m/s.

**Steps to reproduce:**

1. Manually place an egg in an incubator
2. Run the bot
3. See that the egg has not made any progress toward hatching

**Expected behavior:**
I expect the egg to have made progress toward hatching

**Actual behavior:**
No progress has been made

**Version:**
develop branch at commit 647e7291a64d874f52b0b506f0262be5a8722cfd

**Operating System:**
OSX

**Java version:**
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

**Comment by jabbink** [comment]
>See that the egg has not made any progress toward hatching
After how many minutes?

**Comment by ajorgensen** [comment]
Any amount of time. If i set the bot to walk say 2 miles, watch it do so in the ui, and then check back on the egg status it is still the same.

**Comment by jabbink** [comment]
After how many minutes exactly did you check the progress?

**Comment by ajorgensen** [comment]
I ran the bot last night, it likely traveled around 3 - 4 miles and I checked this morning in the app itself and no progress had been made, so maybe 12 hours or so?

**Comment by hiren63** [comment]
@ajorgensen How did you have the bot run for that long, for me it stops In 2 hours everytime.

**Comment by ajorgensen** [comment]
I just ran `gradlew run` and then set some waypoints in the UI which did a loop around my apartment. I dont know if it was running for a full 2 hours, I generally only run if for at most an hour maybe any hour and a half.

**Comment by jabbink** [comment]
If that happened with Google, try v0.5.1. Probably related to a different problem (that 1.5-2h timeout; should be fixed)

**Comment by ajorgensen** [comment]
I am using PTC as a login method, sorry I forgot to mention that.

**Comment by TheWayAway** [comment]
I also noticed this same issue, doesn't seem like my eggs are incubating. PTC login as well.

Is it supposed to display some line in the logs / or the Web UI that the eggs are being incubated? 

Will try v0.5.1 later today.

**Comment by Killertom63** [comment]
Make sure you're not running too fast as then it wont add to the incubation time.

**Comment by ajorgensen** [comment]
As mentioned above I have it set at 2 m/s in the config which is slower than the default 2.8 m/s

**Comment by jabbink** [comment]
You mentioned a circle around your apartment. Pogo calculates the distance walked in a very weird way: they take your location every minute and add the distance since the location of 1 minute earlier. So eg you run in a circle that takes exactly 1 minute to finish, you never walk a single centimeter.

(Also the distance walked only updates once every 5 minutes)

**Comment by ajorgensen** [comment]
Ah sorry it was a very large circle (more like a square actually) with each leg was around a mile or so.

After a quick experiment it seems that turning the walking rate down to 1.5 m/s allows for the incubators to work now. I can try to experiment with some other values and report back but it seems that the default value in the config (and even down to 2 m/s) does not work for egg incubation.

**Comment by Killertom63** [comment]
@ajorgensen No problem. It is weird though, because my config walking speed is at 3.5 and I hatch eggs all the time. However, I don't have a set route like you. Mine is just wondering around Dallas.

**Comment by ajorgensen** [comment]
I've read it should work up to 20 MPH (8.9 meters per second) so it seems really strange that it doesnt work. I've noticed it not working both when setting a route and letting the bot just go. I can do more experimentation to see if i can find some common thread.

**Comment by ajorgensen** [comment]
Strange, seems to be working now. I'll go ahead and close as I'm having a hard to reproducing. Thanks for the help!
