### ISSUE TITLE
Failed to update profile and inventory (level 40)

### ISSUE THREAD

**Issue by d-moos** [jabbink/PokemonGoBot#913]
**Description:**
Profile update does not work (e.g. not transfering any pokemons due to crash)

**Steps to reproduce:**

1. Get a level 40 account
2. start the bot

**Expected behavior:**
no errors.. should transfer pokemons.

**Actual behavior:**
exception occurs & pokemons stay in inventory

**Stacktrace (If it's a crash):**
09 Aug 18:35:09 (default: BotLoop): Error running loop BotLoop!
java.lang.ArrayIndexOutOfBoundsException: 40
        at ink.abb.pogo.scraper.gui.SocketServer.sendProfile(SocketServer.kt:73)
        at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:2                8)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:221)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:126)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:33)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:169)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:33)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
09 Aug 18:35:14 (default: BotLoop): Getting map of (47.387696160781076, 8.521010                678533731)

**Version:**
0.5.0

**Operating System:**
Win 10

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by jabbink** [comment]
Nice catch.

As a temporary issue: can you check if setting `gui_port_socket=0` fixes this problem for you (the GUI won't work then, though) as the problem seems as if it crashes when it tries to send the required XP for the next level to the GUI (and there is no next level)

**Comment by d-moos** [comment]
Hi,

Transfering seems to work.
Although I still get an error in the and now

`09 Aug 21:35:05 (default: BotLoop): Looted pokestop 46b36b3aa399423394f470574042                                                                                                                                                                                               c97a.16; +50 XP: [3xITEM_POKE_BALL]
09 Aug 21:35:05 (default: ProfileLoop): Failed to update profile and inventories                                                                                                                                                                                               
09 Aug 21:35:05 (default: BotLoop): Walking to (47.388581, 8.518506) in 26.763508271112915 steps.
09 Aug 21:35:09 (default: BotLoop): Getting map of (47.38822907066097, 8.518676237096637)
09 Aug 21:35:09 (default: BotLoop): Dropped 3x ITEM_REVIVE
09 Aug 21:35:10 (default: BotLoop): Dropped 1x ITEM_MAX_REVIVE
09 Aug 21:35:11 (default: BotLoop): Dropped 2x ITEM_POTION
09 Aug 21:35:11 (default: WalkingLoop): Destination reached.
09 Aug 21:35:11 (default: BotLoop): Dropped 4x ITEM_POKE_BALL
09 Aug 21:35:11 (default: BotLoop): Going to transfer PIDGEY with CP 10 and IV 64%; reason: Obligatory transfer
09 Aug 21:35:13 (default: BotLoop): Walking to (47.388581, 8.518506) in 0.2364914831493419 steps.
09 Aug 21:35:13 (default: WalkingLoop): Destination reached.
09 Aug 21:35:14 (default: BotLoop): Getting map of (47.38853762882261, 8.5185645021829)
09 Aug 21:35:14 (default: BotLoop): Found pokemon PIDGEY
09 Aug 21:35:15 (default: BotLoop): Encountered pokemon PIDGEY with CP 452 and IV 33%
09 Aug 21:35:15 (default: BotLoop): Using desired_catch_probability_unwanted because Obligatory transfer
09 Aug 21:35:15 (default: BotLoop): Using ITEM_GREAT_BALL; Using curve; achieved catch probability: 0.58652484, desired: 1.0
09 Aug 21:35:16 (default: BotLoop): Using ITEM_POKE_BALL; Using curve; achieved catch probability: 0.47800976, desired: 1.0
V/CatchablePokemon: Pokemon caught/or flee
`

**Comment by jabbink** [comment]
Hmm if you compile from source, a quickfix would be to add a 41st fake level with a few billion XP and recompile it

**Comment by d-moos** [comment]
This might be the best solution for now.
