### ISSUE TITLE
Starting Latitude setting ("latitude") not specified in config.properties! (Version 0.5.1)

### ISSUE THREAD

**Issue by JudeMurphy** [jabbink/PokemonGoBot#914]
**Description:**

I HAVE TRIED THE JSON VERSION FORMATTING, AND IT DID NOT WORK. Can someone please provide a sample config file that they are using. So I can try it? My config file is attached

Receiving this error on startup:
09 Aug 12:23:32 [default] - Item Drop setting ("drop_items") not specified, defaulting to "true".
09 Aug 12:23:32 [default] - Set Profile Update Timer setting ("profile_update_timer") not specified, defaulting to "60".
09 Aug 12:23:32 [default] - Set Timer to return the first Pokestop (minutes) setting ("timer_walk_to_start_pokestop") not specified, defaulting to "-1".
09 Aug 12:23:32 [default] - Starting Latitude setting ("latitude") not specified in config.properties!

**Steps to reproduce:**

1. Start the bot, and this happens.

**Expected behavior:**
Bot should start.

**Version:**
0.5.1

**Operating System:**
Mac OS - El Capitan 10.11.6 

**Java version:**
1.8.0

[config.properties.txt](https://github.com/jabbink/PokemonGoBot/files/409437/config.properties.txt)

**Comment by jabbink** [comment]
![image](https://cloud.githubusercontent.com/assets/2461972/17524997/200e8662-5e61-11e6-9c38-60d0794ae3bf.png)

You messed up downloading the file. In a terminal do 

```
rm config.properties
https://raw.githubusercontent.com/jabbink/PokemonGoBot/develop/config.properties.template > config.properties
nano config.properties
```

Make your changes. Ctrl+X, y, ENTER
