### ISSUE TITLE
GUI Showing old data from 0.5.0 not displaying new bot running on 0.5.1

### ISSUE THREAD

**Issue by Taclaa** [jabbink/PokemonGoBot#916]
GUI at http://pogo.abb.ink/RocketTheme/ is not showing new bot data, and map is static in old location.

Using in terminal java -jar PokemonGoBot-0.5.1.jar

OSX El Capitan 10.11.5

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by jabbink** [comment]
you probably didn't fully wait for the old version to terminate

`killall java`

**Comment by GenuineSounds** [comment]
I've had this before as well, I think I fixed it by hitting the reset window positions button. That seemed to refresh the bad variables or something.

**Comment by Taclaa** [comment]
BOOM! done using the reset window positions button then a refresh! 

Great work guys! thanks for the bot!

**Comment by GenuineSounds** [comment]
@jabbink Not EVERYTHING is the jvm's fault :japanese_goblin:

**Comment by CosmoRing** [comment]
@GenuineSounds I't is. The developer of the GUI already knows the issue.
