### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by ShaaiLo** [jabbink/PokemonGoBot#918]
Can somone help me with the 2 Factor Auth ?! I try to create it, but it always failed on me.
Would be nice if someone help me with TeamViewer. !

**Comment by Danman00** [comment]
where exactly occures the problem ?

**Comment by ShaaiLo** [comment]
i Cant find the place where i have to put the code in the right place.

**Comment by Danman00** [comment]
lets start at the beginning

1. Whats your OS
2. Are u using the latest version of the bot ?
3. pls Provide a look in your config.properties with pastebin ! 
4. pls provide a stack trace also with pastebin !

thx

**Comment by ShaaiLo** [comment]
all i need is create a 2 Factor auth. If this works, the bot will work too.

**Comment by toffaste1337** [comment]
@ShaaiLo Do you mean an app password for google login?

**Comment by ShaaiLo** [comment]
on google chrome i have to create a 2 factor auth. I choose Email with  Windows Computer. Then i get a number of 16 and these numbers i have to change. but i donnt know how. so i ask here for help with teamviewer

**Comment by toffaste1337** [comment]
If you're using the `config.properties` file, go here and create an app password: https://security.google.com/settings/security/apppasswords 
If you're using the `config.json` file, leave token blank and you will get a link to a page to generate a token on the first run.

**Comment by ShaaiLo** [comment]
https://security.google.com/settings/security/apppasswords 
 i have to create a 2 factor auth. I choose Email with Windows Computer. Then i get a number of 16 and these numbers i have to change. but i donnt know how. so i ask here for help with teamviewer

**Comment by toffaste1337** [comment]
Dude what the fuck are you talking about? I tried to help but your questions are out of this world. "Email with Windows Computer".. WHAT?

**Comment by langerhans** [comment]
This is not a generic support forum here...
