### ISSUE TITLE
stops catching 

### ISSUE THREAD

**Issue by russr123** [jabbink/PokemonGoBot#919]
**Description:**
works for so long, then just dies....

inventory isn't near full
Pokebank	125 / 250
Items	164 / 400

this is the last catch from the log

←[0;39m←[32m09 Aug 15:12:28 [default: BotLoop] - Found pokemon PARAS
←[0;39m←[37m09 Aug 15:12:28 [default: WalkingLoop] - Pausing to catch pokemon...
←[0;39m←[32m09 Aug 15:12:28 [default: BotLoop] - Encountered pokemon PARAS with CP 237 and IV 64%
←[0;39m←[33m09 Aug 15:12:28 [default: BotLoop] - Using ITEM_POKE_BALL; Using curve; achieved catch probability
: 0.5786982, desired: 0.8
←[0;39mV/CatchablePokemon: Pokemon caught/or flee
←[36m09 Aug 15:12:29 [default: BotLoop] - Caught a PARAS with CP 237 and IV 64%
 Stamina: 4 | Attack: 12 | Defense: 13 | IV: 29 (64%) (lured pokemon) : [210x XP, 3x Candy, 100x Stardust]
←[0;39m←[37m09 Aug 15:12:32 [default: WalkingLoop] - Destination reached.
←[0;39m←[37m09 Aug 15:12:32 [default: BotLoop] - Getting map of (37.806994692696065, -122.42272292136082)
←[0;39m←[37m09 Aug 15:12:32 [default: BotLoop] - Walking to 37.80773265494054, -122.42151260375977
←[0;39m←[37m09 Aug 15:12:32 [default: WalkingLoop] - Walking to (37.80773265494054, -122.42151260375978) in 13
5.43086062111252 steps.
←[0;39m←[37m09 Aug 15:12:37 [default: BotLoop] - Getting map of (37.80710893251456, -122.42252704258537)
←[0;39m←[37m09 Aug 15:12:42 [default: BotLoop] - Getting map of (37.807254812599076, -122.4222191283712)
←[0;39m←[37m09 Aug 15:12:47 [default: BotLoop] - Getting map of (37.807360042479964, -122.42208182683152)
←[0;39m←[37m09 Aug 15:12:52 [default: BotLoop] - Getting map of (37.80748988814244, -122.42182733366599)
←[0;39m←[37m09 Aug 15:12:57 [default: BotLoop] - Getting map of (37.807647333844855, -122.42156787484441)
←[0;39m←[37m09 Aug 15:13:00 [default: WalkingLoop] - Destination reached.
←[0;39m←[37m09 Aug 15:13:02 [default: BotLoop] - Getting map of (37.80777768722033, -122.42146678541961)
←[0;39m←[37m09 Aug 15:13:03 [default: BotLoop] - Walking to 37.80861421150694, -122.42084741592407
←[0;39m←[37m09 Aug 15:13:03 [default: WalkingLoop] - Walking to (37.80861421150694, -122.42084741592407) in 11
2.57399442854005 steps.
←[0;39m←[37m09 Aug 15:13:07 [default: BotLoop] - Getting map of (37.80791522328676, -122.42132448587482)
←[0;39m←[37m09 Aug 15:13:12 [default: BotLoop] - Getting map of (37.808094358061055, -122.42122249158605)
←[0;39m←[35m09 Aug 15:13:16 [default: ProfileLoop] - Profile update: 884580 XP on LVL 25; 174580/190000 (91.88
%) to LVL 26
←[0;39m←[35m09 Aug 15:13:16 [default: ProfileLoop] - XP gain: 13500 XP; Pokemon caught/transferred: 57/30; Pok
emon caught from lures: 29; Items caught/dropped: 114/20;
Pokebank 134/250; Stardust 64415; Inventory 164/400

**Version:**
v0.5.1

**Operating System:**
win7 64bit

**Java version:**
8.101
![image](https://cloud.githubusercontent.com/assets/20584235/17530774/ff42421c-5e46-11e6-8f21-42864a8819b0.png)

**Comment by Danman00** [comment]
i dont see an error here pls provide a stack trace when the bot crashes

**Comment by jabbink** [comment]
Maybe related to https://github.com/Grover-c13/PokeGOAPI-Java/issues/515#issuecomment-238671528

**Comment by russr123** [comment]
> @Danman00  "stack trace " the browser console log?

**Comment by russr123** [comment]
tested on a 2nd PC, same, no errors in the cmd box

**Comment by russr123** [comment]
got this on PTC

09 Aug 23:39:28 [default: BotLoop] - Error running loop BotLoop!
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.util.ArrayList$Itr.next(Unknown Source)
        at ink.abb.pogo.scraper.tasks.ReleasePokemon.run(ReleasePokemon.kt:74)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:239)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:146)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:33)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:187)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:33)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by jabbink** [comment]
>java.util.ConcurrentModificationException

Different problem. Some threading issue in the API, shouldn't break a thing.

**Comment by russr123** [comment]
then i dont see any errors... both google and PTC, it will catch from 5 to 15min then just stops...

**Comment by Danman00** [comment]
I encountered something similar like russr123 
i run 1 bot with 2 json files yesterday with 0.5.1 there was no problem that both accounts catch
but now only my second account continues catching, i also got the same problem with 0.5.2 

the json files are correct but pls have a look
Account 1 http://pastebin.com/1Ejc951G
Account 2 http://pastebin.com/pwhRCeJh

the bot keeps running but account 1 doenst catch anything so there's no crash.

**Comment by Sieberkev** [comment]
This is a softban seen when multiple accounts bot on the same IP
