### ISSUE TITLE
Pokestop out of range

### ISSUE THREAD

**Issue by superxuxin** [jabbink/PokemonGoBot#923]
**Description:**
Pokestop out of range; distance: 0.49087538951423976

**Steps to reproduce:**

After running version v0.5.1 for about 10 mins, all pokestops are out of range

**Operating System:**
windows 7

**Comment by Sieberkev** [comment]
What is your configuration for "speed"? I found if I lowered it a bit I get a lot less (to almost none) "out of range" errors

**Comment by superxuxin** [comment]
2.8 by default. Would you suggest lower it to something different?

**Comment by toffaste1337** [comment]
2.8 seems to be the most efficient speed.

**Comment by mrabbie** [comment]
Yep, happened sometimes for me, 2 out of 4 bots run i'm getting this error. Sometimes it is happened after 10 - 15 minutes, sometimes after an hour. Speed also by default 2.8

any idea what might be wrong?

**Comment by shilch** [comment]
This is a pokestop ban that you get when you visit 2k pokestops in 24 hours. It seems to be temp ban only. [Link](https://www.reddit.com/r/pokemongodev/comments/4xkqmq/new_ban_types_and_their_causes/)

**Comment by jabbink** [comment]
This was from before they introduced those bans. It was a bug in the code that would sometimes allow this to happen.
