### ISSUE TITLE
unexpected http code : 403

### ISSUE THREAD

**Issue by BartWillems** [jabbink/PokemonGoBot#924]
**Description:**
RemoteServerException(http 403) AFTER authenticating with the google servers

**Steps to reproduce:**

1. java -jar pokemon.jar

**Expected behavior:**
Receiving my profile info, then botting fun

**Actual behavior:**
`Error 403, after login
`

**Stacktrace (If it's a crash):**
[stacktrace](http://pastebin.com/mxQPH4cN)

**Version:**
0.5.1, not self compiled

**Operating System:**
FreeBSD 10.3

**Java version:**
```
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)
```

**Note**
_This is running on a digital ocean machine on a server in Frankfurt, maybe the Pokemon Go servers block my requests because I try to bot in Belgium?_ 
**Edit:** 
Scratch that, even with coordinates in Frankfurt it's fubar

> A web server may or may not return a 403 Forbidden HTTP status code in response to a request from a client for a web page or resource to indicate that the server can be reached and understood the request, but refuses to take any further action. Status code 403 responses are the result of the web server being configured to deny access, for some reason, to the requested resource by the client.

**Comment by Killertom63** [comment]
Try setting your start.bat to 

"java -jar PokemonGoBot-0.5.1.jar --server.port=8090"

Obviously "PokemonGoBot-0.5.1.jar" should be the jar you named.

**Comment by BartWillems** [comment]
@Killertom63 I've already tried that, it gives the same error

**Comment by Killertom63** [comment]
I dunno if this will help, but have you port forwarded the ports you're using?

**Comment by BartWillems** [comment]
Don't have to, my droplet has a public IP, the firewall is configured to allow all trafic :/

**Comment by BartWillems** [comment]
What OS do you run on your droplet?

**Comment by odannyc** [comment]
Debian

**Comment by toffaste1337** [comment]
Guys, it is probably too many pokemon logins per ip.

**Comment by Peyphour** [comment]
Niantic blocked a lot of IPs from OVH, Digital Ocean etc

**Comment by reusu** [comment]
@Peyphour and Vultr

**Comment by Peyphour** [comment]
No idea

**Comment by Tjessx** [comment]
Same on 2 Aws servers here, These server hosts have a certain IP range (aws 52....., digital oceans 188....) They probs blocked the most popular ones
