### ISSUE TITLE
When trying to run bot the bot can not find innital pokestops. It says retrying in 10 sec and keeps on failing to find any. Tried turning off loot pokestops. It didnt work.

### ISSUE THREAD

**Issue by JoshLev** [jabbink/PokemonGoBot#927]
**Description:**
[Short description of the issue observed. If this is feature request you can modify the template as required.]

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]

**Expected behavior:**
[What should happen?]

**Actual behavior:**
[What actually happens]

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
[The version of the bot you used; when self-compiled: :exclamation: the commit hash :exclamation:]

**Operating System:**
[Your operating system]

**Java version:**
[Full output of `java -version`]

**Comment by zoegalaxy** [comment]
set your banSpinCount to 40

**Comment by Peyphour** [comment]
And fill the template, it's made for that
