### ISSUE TITLE
Can't find initial pokestops

### ISSUE THREAD

**Issue by JoshLev** [jabbink/PokemonGoBot#928]
**Description:**
When trying to run bot the bot can not find initial pokestops. It says retrying in 10 sec and keeps on failing to find any. Tried turning off loot pokestops. It didn't work.

**Version:**

0.5.1

**Operating System:**
Windows 10

**Java version:**
Most current

**Comment by Sieberkev** [comment]
What is your starting lat/long?

**Comment by etkstim** [comment]
Same issue

**Comment by langerhans** [comment]
Duplicate, search existing issues before opening new please.
