### ISSUE TITLE
[QUESTION] max number of each item

### ISSUE THREAD

**Issue by elliottfeng** [jabbink/PokemonGoBot#93]
# max number of each item that the bot should keep if "drop_items" is ennabled
# use -1 in a item to never drop this specific item
item_revive=20
item_max_revive=20
item_potion=20
item_super_potion=5
item_hyper_potion=5
item_max_potion=5
item_poke_ball=5
item_great_ball=300
item_ultra_ball=-1
item_master_ball=-1

is this working now? with 0.3 Jar

**Comment by CosmoRing** [comment]
Already implemented in master. #36

**Comment by Mewks** [comment]
Mine doesn't seem to be working. Even if I set Potions to 200 for example, it will still drop them when it reaches 20, weird?

I know its reading the config file correctly because its loading the location and login and stuff perfectly fine.

```
## Items drop
# should the bot EVER drop items (true/false)
drop_items=true

# max number of each item that the bot should keep if "drop_items" is ennabled
# use -1 in a item to never drop this specific item
item_revive=100
item_max_revive=100
item_potion=100
item_super_potion=200
item_hyper_potion=200
item_max_potion=100
item_poke_ball=200
item_great_ball=-1
item_ultra_ball=-1
item_master_ball=-1
item_razz_berry=100
```

Thats what it looks like.

**Comment by jabbink** [comment]
It's not in the 0.3.0 jar yet, compile from source, it is on `master`
