### ISSUE TITLE
how to make a course for your bot to follow?

### ISSUE THREAD

**Issue by OMAoxide** [jabbink/PokemonGoBot#930]
**Description:**
[Short description of the issue observed. If this is feature request you can modify the template as required.]

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]

**Expected behavior:**
[What should happen?]

**Actual behavior:**
[What actually happens]

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
[The version of the bot you used; when self-compiled: :exclamation: the commit hash :exclamation:]

**Operating System:**
[Your operating system]

**Java version:**
[Full output of `java -version`]

**Comment by smileytechguy** [comment]
Right click on map to make a point, you can do this repeatedly and the bot will go from point to point

**Comment by OMAoxide** [comment]
@smileytechguy Im on mac OS X and I don't know how to have my bot and GUI all in one like this picture
![gui](https://cloud.githubusercontent.com/assets/20779648/17542729/3c35dca4-5e80-11e6-9d52-d44a296caaf5.png).
So when i right click on my map it does nothing. How do i fix this?

**Comment by gabrielklein** [comment]
You have a left button on mac  now?
1) Try to click in different places (road, etc...)
2) Try to use firefox or chrome.

It works perfectly on my environment. I cannot remove points.

**Comment by smileytechguy** [comment]
@OMAoxide 
1. Use the newest update with rockettheme
2. Right click (2 fingers instead of 1 on trackpad, idk mouse) on map
3. Once the bot reaches its current destination it will go there

**Comment by mrabbie** [comment]
http://pogo.abb.ink/RocketTheme/

to open the GUI here's the link and it's in the FAQ.
