### ISSUE TITLE
Can't run "gradlew build"

### ISSUE THREAD

**Issue by toutoux05** [jabbink/PokemonGoBot#931]
C:\ESD\PokemonGoBot-develop>gradlew build
:compileKotlin UP-TO-DATE
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_102 contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.573 secs

**Comment by Peyphour** [comment]
You need the JDK as well

**Comment by Mixone-FinallyHere** [comment]
You can get it from [Oracle's downloads site](http://www.oracle.com/technetwork/java/javase/downloads/index.html).
