### ISSUE TITLE
GUI map not making any movement

### ISSUE THREAD

**Issue by reinforcers** [jabbink/PokemonGoBot#936]
**Description:**
GUI map not making any movement or tracking movement. just showing pokemon and pokestop

**Steps to reproduce:**
not sure how. but from new setting I try camp_lure_pokestop=1 and initial_map_size=7. maybe thats the problem?

**Expected behavior:**
just move around when no lure, i guess (in GUI)

**Actual behavior:**
stop in initial point, but in log it is moving

**Stacktrace (If it's a crash):**
![scrot](https://cloud.githubusercontent.com/assets/3624158/17546817/1c267962-5f0e-11e6-8402-47202d9cf5b4.png)

**Version:**
0.5.1

**Operating System:**
Ubuntu 14.04

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) Server VM (build 25.101-b13, mixed mode)

**Comment by aukeboskma** [comment]
I had the same problem this morning.

**Comment by jabbink** [comment]
>camp_lure_pokestop=1

Possibly camping near 1 lured pokestop.

**Comment by reinforcers** [comment]
yep, I try to restart mine with camp_lure_pokestop=-1 it work like a charm XD

**Comment by Mixone-FinallyHere** [comment]
maybe rather than camp standing still make the bot move around the area of effect? I'd say it is about a radius of 10-20 metres (not sure though)

**Comment by Casual-User** [comment]
@Mixone-FinallyHere 
Hi Miguel, I opened another ticket (#947) for this idea that bothered me too. Best regards!
