### ISSUE TITLE
No pokestops found

### ISSUE THREAD

**Issue by ruthger92** [jabbink/PokemonGoBot#943]
10 aug 15:26:32 [default] - Getting initial pokestops...
10 aug 15:26:32 [default] - Got 0 pokestops
10 aug 15:26:32 [default] - Retrying in 10 seconds...
10 aug 15:26:42 [default] - Got 0 pokestops
10 aug 15:26:42 [default] - Retrying in 10 seconds...

**Comment by qwertychacha2002** [comment]
Try either checking your coordinates again or reducing the initial map size

**Comment by ruthger92** [comment]
Already checked that ;)! Anyone else got this?

**Comment by mtchm** [comment]
Did you also reduce the initial map size, like he proposed?

**Comment by mrabbie** [comment]
yep, sometimes i got this, what it do and most of the time works is reduce the initial map size (it's in config.properties just above pokemon list name) to 6 or 3, or wait around 10 to 15 minutes and try to run the bot again.

**Comment by nokingah** [comment]
I've had the same issue. It keeps happening even though I've reduced the size to 6

**Comment by Casual-User** [comment]
Happened to me too. Recently, when my walking speed was 29 m/s what functions quite well sometimes and sometimes gets me an instant soft ban. It might be a new form of soft ban that is less easy to overcome since there are no pokéstops to spin left. Logged back into the iOS app and haven't stops there either...

**Comment by warius** [comment]
Could it be server being saturated?

**Comment by qfcartal** [comment]
Same problem, used to work. Tried slowing the bot, changing coordinates, reducing the size of the map, waiting 1h, disabling look_pokestops. Nothing seems to work.

**Comment by hudzmozquito** [comment]
I solve this problem by resetting the connection

**Comment by Casual-User** [comment]
It's higly probable an IP ban. I used the iOS app over a potentially banned WiFi: no stops found. Deactivation of WiFi and going 3G: stops are there as normal. I would like to learn how long these IP bans are. What's your experience?

**Comment by okjinkok** [comment]
Same here...

11 Aug 11:08:37 [default] - Getting map of (22.304992433595054, 114.16388296074638)
11 Aug 11:08:37 [default] - Getting initial pokestops...
11 Aug 11:08:38 [default] - Got 0 pokestops
11 Aug 11:08:38 [default] - Retrying in 10 seconds...
11 Aug 11:08:49 [default] - Got 0 pokestops
11 Aug 11:08:49 [default] - Retrying in 10 seconds...

**Comment by okjinkok** [comment]
It's done... Just change your map size to 6 or 3... It's on config.properties

# Initial map size (S2 tiles) to fetch (max. 9: ~3*3km area)
initial_map_size=9


9 is the default size... try to change it to 6 or 3.... wait for 10 to 15 minutes and then try again... It's work for me...

**Comment by langerhans** [comment]
Duplicate.
