### ISSUE TITLE
Bot stops catching pokemon and will not transfer pokemon under 400 cp or 80% IV

### ISSUE THREAD

**Issue by qwertychacha2002** [jabbink/PokemonGoBot#944]
**Description:**
Once my poke bank is 250/250 the bot stops encountering wild pokemon but wont transfer any either. Is there a way to manually transfer?

**Steps to reproduce:**

1. Fill pokebank (250/250)

**Expected behavior:**
[What should happen?]

**Actual behavior:**
[What actually happens]

**Version:**
PokemonGoBot-0.5.1.jar

**Operating System:**
OSX El Capitan Version 10.11.5

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by staurakis** [comment]
Log in the application (Pokemon Go) of Niantic and do it manually from there?

**Comment by Casual-User** [comment]
Yeah, it is a problem that I already encountered in 0.5.0 and before. 
Restarting the bot did help, though. Best regards!

**Comment by zoegalaxy** [comment]
I feel you. Just now, I manually login and free up Pokemon space 😫

**Comment by russr123** [comment]
make sure you didnt rename them, that will stop xfer..

**Comment by langerhans** [comment]
Also restarting the bot usually runs the proper clearing tasks again.
