### ISSUE TITLE
Bot stops at Building 83% with banner visible

### ISSUE THREAD

**Issue by Phrohdoh** [jabbink/PokemonGoBot#951]
**Description:**
The bot does not actually play the game anymore it just stops at 83% with the banner displayed.
```
$ ./gradlew run
:compileKotlin
:compileJava
:processResources UP-TO-DATE
:createProperties
:classes
:run
                                  ,'\
    _.----.        ____         ,'  _\   ___    ___     ____        ;-.               ,
_,-'       `.     |    |  /`.   \,-'    |   \  /   |   |    \  |`.   \ '.           .'/
\      __    \    '-.  | /   `.  ___    |    \/    |   '-.   \ |  |   \  \ .---. .-' /
 \.    \ \   |  __  |  |/    ,','_  `.  |          | __  |    \|  |    '. '     `\_.'
   \    \/   /,' _`.|      ,' / / / /   |          ,' _`.|     |  |      |(),()  |     ,
    \     ,-'/  /   \    ,'   | \/ / ,`.|         /  /   \  |     |      (  __   /   .' \
     \    \ |   \_/  |   `-.  \    `'  /|  |    ||   \_/  | |\    |     .''.___.'--,/\_,|
      \    \ \      /       `-.`.___,-' |  |\  /| \      /  | |   |    {  /     \   }   |
       \    \ `.__,'|  |`-._    `|      |__| \/ |  `.__,'|  | |   |     '.\     /_.'    /
        \_.-'       |__|    `-._ |              '-.|     '-.| |   |      |'-.-',  `; _.'
                                `'                            '-._|      |  |  |   |`
                                                                         `""`""`"""`
> Building 83% > :run
```

**Steps to reproduce:**
`./gradlew run`

**Expected behavior:**
The bot should connect and play as it should.

**Actual behavior:**
Stuck at `Building 83% > :run` with the ASCII banner. No other output.

**Version:**
0880f53a035ec199cac5c1172be438f3a17087d7

**Operating System:**
OS X 10.11.5

**Java version:**
```
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

**Comment by mtchm** [comment]
https://github.com/jabbink/PokemonGoBot/issues/793

**Comment by smileytechguy** [comment]
Takes a bit to load...

**Comment by Phrohdoh** [comment]
Oops sorry I had not seen #793.
@smileytechguy That is understandable in general. But at least 15 minutes of load time seems a bit ludicrous.

**Comment by jabbink** [comment]
#793 also has a port duplicate, but someone complaining that a task, which also includes cleaning up and closing, gets stuck at 83%. Hint: it doesn't. When you (gradlew) **run** something, 100% would be a successful execution and shutdown.

**Comment by chongivan** [comment]
try in terminal
killall -9 java
