### ISSUE TITLE
[Enhancement] Display move set owned by a pokemon?

### ISSUE THREAD

**Issue by CLGitDev** [jabbink/PokemonGoBot#953]
Other than IVs, the move set of a pokemon is a critical factor to determine if it is strong enough to be kept. I personally feel it will be a good idea if the info can be displayed somewhere, say in the console.

Looks like the API have two functions, getMove1() and getMove2(), that can be leveraged for this purpose?

(Would like to bring this up and see if there's wider interest in this area.)

**Comment by Sieberkev** [comment]
At this moment, that information (and a lot more) is available in the CSV export.

**Comment by CLGitDev** [comment]
@Sieberkev Thanks for your info, I'll definitely check that out. Apologies for my ignorance on the CSV feature.

**Comment by langerhans** [comment]
There is an issue about this already, closing here :)
