### ISSUE TITLE
I can't use the bot, it stays on "Logging in to game server"

### ISSUE THREAD

**Issue by arttara** [jabbink/PokemonGoBot#956]
hi all,

I face issues when logging (I left the token slot blank as I don't know where to find it, this may be the source of the problem, how to find it ?), here is a screeshot : 
10 août 19:08:46 [main] - Running with Spring Boot v1.3.6.RELEASE, Spring v4.2.7.RELEASE
10 août 19:08:46 [main] - No active profile set, falling back to default profiles: default
10 août 19:08:51 [main] - UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
10 août 19:08:51 [main] - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
10 août 19:08:55 [default] - config.properties file not found. Trying config.properties.txt...
10 août 19:08:55 [main] - Started MainKt in 9.458 seconds (JVM running for 11.749)
10 août 19:08:55 [default] - Logging in to game server...
 
and nothing happen afterwards, what should I do ?
Thanks a lot for your help!

**Comment by jabbink** [comment]
Which version are you using?

**Comment by arttara** [comment]
v0.5.1

**Comment by jabbink** [comment]
1. Please upgrade to 0.5.2
2. How many bots are you using?

**Comment by arttara** [comment]
and I use it on a mac, this is my first one

**Comment by jabbink** [comment]
Leave it empty, in the few cases it is needed, the bot will set it itself.

**Comment by arttara** [comment]
ah ok, thanks!

**Comment by Safti54** [comment]
where can i download the new version ?

**Comment by langerhans** [comment]
@Safti54 on the releases page.
@arttara If that issue is solved, please close it.
