### ISSUE TITLE
Picking what eggs to be entered first for Hatching

### ISSUE THREAD

**Issue by classicalDonkey** [jabbink/PokemonGoBot#958]
**Description:**
Sorry if this has been covered, I did look for other posts.  Is it possible to have an option to pick what order eggs are put in?  for example I would prefer 10k to be put before 5 k.  So for example it does a 2k, then 10k then 2k then 5k then back to 2k and so on.  So if you have a 10k it will also put that to the next in line.

"egghatching_order" : [ "10", "5","2" ],

So it will always pick the first in line if you have an egg of that distance, but I would not want it to just do 5k after 5k so thats why I think it should do a 2k between each time.

**Comment by Peyphour** [comment]
So just put 10k eggs in first ?

**Comment by jabbink** [comment]
This is done for weeks already https://github.com/jabbink/PokemonGoBot/blob/a8379e21daaafe3589820823bd64579c13843e5a/src/main/kotlin/ink/abb/pogo/scraper/tasks/HatchEggs.kt#L42-L44
