### ISSUE TITLE
Walk and WalkToStartPokestop bug

### ISSUE THREAD

**Issue by marceloueda** [jabbink/PokemonGoBot#959]
I haven't investigated much further but it seems to me that something is missing in the Walk and WalkToStartPokestop tasks.

In these tasks I can only see a call to ctx.server.setLocation() which only updates location in the GUI map as far as I understand.
Shouldn't there be a call to ctx.api.setLocation() too?

**Comment by bg-git-hub** [comment]
So, is there a bug, or you just don't understand the code?

**Comment by marceloueda** [comment]
There's a bug in my opinion.

**Comment by jabbink** [comment]
https://github.com/jabbink/PokemonGoBot/blob/f31717ddab2f207b80c8c4742c99ae87b6a3eb1f/src/main/kotlin/ink/abb/pogo/scraper/Bot.kt#L143-L143

calls the set thing every 5 secs.

**Comment by jabbink** [comment]
Yep. Server heavily rate limits stuff so updating the api location every 0.2s is overkill.

**Comment by marceloueda** [comment]
Got it, thanks for answering!
