### ISSUE TITLE
[BUG] XP not in pokestop rewards

### ISSUE THREAD

**Issue by CosmoRing** [jabbink/PokemonGoBot#96]
Needs to be added XP to the rewards in the pokestop spin and replace current code related to full inventory to only display XP gained.

**Comment by jabbink** [comment]
XP for a pokestop is always 50, or isn't it?

In the case you get 0, you're probably soft banned and you get a warning in your console.

**Comment by jabbink** [comment]
Anyways: put it in

**Comment by CosmoRing** [comment]
Don't you get 100 XP with lucky egg on?

**Comment by jabbink** [comment]
Yes, maybe the server doesn't return a different number and the client does everything *2.
