### ISSUE TITLE
Change the Export File Output

### ISSUE THREAD

**Issue by pet90210** [jabbink/PokemonGoBot#960]
**Export File**
The Export of the Export file works well ... for me the way it is arranged isn't the best one.
Is there a way to change the Output of this File?

For Example, I just need the Name of the Pokemon, CP, Max CP, IV%, Move 1, Move 1 Type, Power Move 1, Move 2, Move 2 Type, Power Move 2.

Thank you!
Pet90210

**Version:**
latest 0.5.2

**Operating System:**
MAC OSX

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by Sieberkev** [comment]
I don't want to burden the (already heavy) configuration with too much options. With Excel you can do some nifty stuff with "import from text" in one base tab where all the information is, and make your own proper visualisations in others.

That's the power of Excel :)

Or you can delete/hide the columns you don't want, I do it like that at the moment :p

**Comment by pet90210** [comment]
@Sieberkev I#m deleting as well - thought it would be relativ easy to make a custom version ;)
I Think I will make a script for excel, so it removes automatical while importing the Data :p

**Comment by jabbink** [comment]
I think @Sieberkev's idea is better for now as it doesn't overcomplicate the settings and allows everyone to automatically change the layout in Excel.
