### ISSUE TITLE
Update GUI

### ISSUE THREAD

**Issue by Peyphour** [jabbink/PokemonGoBot#962]
GUI has been updated, maybe the hosting site should update it as well ?

**Comment by Peyphour** [comment]
No, http://pogo.abb.ink/RocketTheme is managed by @jabbink

**Comment by NoobWithBoobs** [comment]
@Peyphour oh, okay, 👍  thanks for telling me

**Comment by swtrpeter** [comment]
+1

**Comment by Sieberkev** [comment]
This is moved to http://ui.pogobot.club and maintained on the [gh-pages branch](https://github.com/jabbink/PokemonGoBot/tree/gh-pages).
