### ISSUE TITLE
Autostart the bot

### ISSUE THREAD

**Issue by Leodenact** [jabbink/PokemonGoBot#963]
Since the bot stops itself after like 1hour to 2 hours, it would be great with some knowledge on how to autostart the bot. Im currently running 4 bots, and since the recent api update I have to start them manually in cmd with java -jar PokemonGoBot-0.5.1.jar --server.port=80XX. 
XX=different ports for my 4 different acccs.

I've seen people posting about this before, but I simply can't follow the conversation because there is too many codes. I have NO knowledge in scripting or coding, so a NOOB-friendly guide would be appreciated.

Thanks alot for this wonderful support guys, take care<3

**Comment by Danman00** [comment]
looks like u where searching for something like this ...
#449

**Comment by Leodenact** [comment]
How?

**Comment by Leodenact** [comment]
I see the keystroke.txt but how can i modify it to restrt the 4 bots im using?
