### ISSUE TITLE
Bug - [default: BotLoop] - No Pokeballs in your inventory; blacklisting Pokemon

### ISSUE THREAD

**Issue by DiogoRNeves** [jabbink/PokemonGoBot#964]
**Description:**
Bot reports to blacklist pokemon because there are no pokeballs, but I have 50 Pokeballs, 50 great balls and 50 Utraballs. After that encounter rate gets lower (before blacklist: 12 pokemon in 25 minutes, after blacklist: 11 pokemons in 40 minutes) and the XP/hours dropped from ~12k/hour to ~9k/hour

**Steps to reproduce:**

1. Run the bot
2. Wait for No Pokeballs message to show up

**Expected behavior:**
DNA

**Actual behavior:**
DNA

**Stacktrace (If it's a crash):**
No stack trace, so here's log results: http://pastebin.com/Pd8Pwh34

**Version:**
0.5.2

**Operating System:**
Mac OS X

**Java version:**
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

I tried restarting the bot and the result did duplicate. Was faster to get the no poke ball message on the second run, but still, it happened. Not sure the encounter rate drop is related, but it sure doesn't look like a coincidence...

**Comment by jabbink** [comment]
Not fully fixed; should occur much less though.

**Comment by NoobWithBoobs** [comment]
same issue with me, my workaround was

config.properties
   item_poke_ball=-1

**Comment by Mixone-FinallyHere** [comment]
this happens to me aswell but the next pokemon suddenly it does have pokeballs its weird haha

**Comment by conradsze** [comment]
![screen shot 2016-08-11 at 8 08 12 pm](https://cloud.githubusercontent.com/assets/11471832/17611958/d656f8d2-6000-11e6-9d1d-271efe207a36.png)
I wasn't sure if I had pokeball in my inventory, I'm sure I have tons of master and ultraballs because of the "group_items_by_type" in version 0.5.2

**Comment by Mixone-FinallyHere** [comment]
Taking a look through the code it seems to be an unhandled NULL return from one of the API calls in CatchablePokemon.java
it reurns NULL if inventory empty but also if there was an error on network side (so catch_flee and not_encountered are properly handled, just not whatever this one is) and the NULL result defauts to this message
don't know enough about how the app works to be able to tell what the actual network issue could be

**Comment by Sieberkev** [comment]
This looks a lot like a softban.

#1095 added optional delays between catching and limits to stop the bot when you reach a certain amount

**Comment by FrancYescO** [comment]
(nope was a bug solved by @jabbink in some commit)
