### ISSUE TITLE
Maybe a silly question

### ISSUE THREAD

**Issue by Leodenact** [jabbink/PokemonGoBot#969]
If someone could help with this it would be gold!

I start my bot like this java -jar PokemonGoBot-0.5.1.jar --server.port=8092 after i opened that folder with CMD, and it works perfectly, but how can i make a bat file, that automaticly restart this ( java -jar PokemonGoBot-0.5.1.jar --server.port=8092) every hour or so?

Thanks  :)

**Comment by mtchm** [comment]
https://github.com/jabbink/PokemonGoBot/issues/966
