### ISSUE TITLE
Java API Gradle build issue?

### ISSUE THREAD

**Issue by mroge009** [jabbink/PokemonGoBot#97]
ERROR:
`Could not find com.github.Grover-c13:PokeGOAPI-Java:master-SNAPSHOT. Searched in the following locations: https://repo1.maven.org/maven2/com/github/Grover-c13/PokeGOAPI-Java/master-SNAPSHOT/maven-metadata.xml https://repo1.maven.org/maven2/com/github/Grover-c13/PokeGOAPI-Java/master-SNAPSHOT/PokeGOAPI-Java-master-SNAPSHOT.pom https://repo1.maven.org/maven2/com/github/Grover-c13/PokeGOAPI-Java/master-SNAPSHOT/PokeGOAPI-Java-master-SNAPSHOT.jar https://jitpack.io/com/github/Grover-c13/PokeGOAPI-Java/master-SNAPSHOT/maven-metadata.xml https://jitpack.io/com/github/Grover-c13/PokeGOAPI-Java/master-SNAPSHOT/PokeGOAPI-Java-master-4f5b715380-1.pom https://jitpack.io/com/github/Grover-c13/PokeGOAPI-Java/master-SNAPSHOT/PokeGOAPI-Java-master-4f5b715380-1.jar Required by: ink.abb:pogo.scraper:0.3.0  Consult IDE log for more details (Help | Show Log)`

Linked here: https://github.com/Grover-c13/PokeGOAPI-Java/issues/139

**Comment by mroge009** [comment]
Fixed by changing the compile line to 'com.github.Grover-c13:PokeGOAPI-Java:4f5b715380' instead.

**Comment by mroge009** [comment]
Leaving open incase someone needs to see.

**Comment by Javapt** [comment]
Adding the following tom build.grade is a more permanent solution since it will account for future changes,

configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

**Comment by jabbink** [comment]
jitpack was broken tonight

**Comment by gargomoma** [comment]
cloned via git, and changed the compile line.

Build error persists T_T
