### ISSUE TITLE
Stuck on 83% when I run it and the bot doesnt actually start.

### ISSUE THREAD

**Issue by dyze1114** [jabbink/PokemonGoBot#970]
I've been running it for a day now with no issues, but I stopped it, edited the config file, try to rerun the bot by coding in `./gradlew run` and then this happened:

```
Carolyns-iMac:PokemonGoBot daniel$ ./gradlew run
:compileKotlin UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:createProperties
:classes
:run
                                  ,'\
    _.----.        ____         ,'  _\   ___    ___     ____        ;-.               ,
_,-'       `.     |    |  /`.   \,-'    |   \  /   |   |    \  |`.   \ '.           .'/
\      __    \    '-.  | /   `.  ___    |    \/    |   '-.   \ |  |   \  \ .---. .-' /
 \.    \ \   |  __  |  |/    ,','_  `.  |          | __  |    \|  |    '. '     `\_.'
   \    \/   /,' _`.|      ,' / / / /   |          ,' _`.|     |  |      |(),()  |     ,
    \     ,-'/  /   \    ,'   | \/ / ,`.|         /  /   \  |     |      (  __   /   .' \
     \    \ |   \_/  |   `-.  \    `'  /|  |    ||   \_/  | |\    |     .''.___.'--,/\_,|
      \    \ \      /       `-.`.___,-' |  |\  /| \      /  | |   |    {  /     \   }   |
       \    \ `.__,'|  |`-._    `|      |__| \/ |  `.__,'|  | |   |     '.\     /_.'    /
        \_.-'       |__|    `-._ |              '-.|     '-.| |   |      |'-.-',  `; _.'
                                `'                            '-._|      |  |  |   |`
                                                                         `""`""`"""`
> Building 83% > :run
``` 

It's been 20 minutes and it hasn't done anything. Can someone help?

**Comment by jabbink** [comment]
Unrelated to the 83%, that number is 100% correct and not a bug (search).

No idea why it wouldn't log more. Can you try running the precompiled jar?

**Comment by dyze1114** [comment]
> Can you try running the precompiled jar?

I'm not sure what that means, I'm not too good with this stuff. I barely got through the tutorial haha

**Comment by BKer** [comment]
I noticed this behaviour of not moving on/logging more details as well, but it was due to port 8080 being in use already. Hope this helps.

**Comment by pet90210** [comment]
@dyze1114 does it happen when you restart the bot. Happens to me sometime as well ... 
try killall java in the console.

**Comment by langerhans** [comment]
Also when the build fails try to disable the test `./gradlew build -x test`

**Comment by yashendra2797** [comment]
Figured out how to bypass this problem!

So,

1. Use `./gradlew build -x test` to bypass the 'Test failed' error

1. Run normally using `./gradlew run`

1. If you face this problem, type `killall java`. However, this somehow doesn't work. So, open Activity Monitor (or its equivalent), search for 'java', and force quit all of them. I had 4 'java' instances which I needed to quit even after using `killall java`. 

1. Now you can run it fine.

**Comment by AlexBoulyga** [comment]
Skipping Tests however is not good! Something vor someone messed up...

**Comment by yashendra2797** [comment]
@AlexBoulyga True. But if you're compiling from the git, you know the risks.

**Comment by chongivan** [comment]
try in terminal
killall -9 java
