### ISSUE TITLE
Starting Latitude setting ("latitude") not specified in config.properties!

### ISSUE THREAD

**Issue by charliedumdum** [jabbink/PokemonGoBot#972]
in my config i have my settings for longitude and latitude to start from like this : 

# Token to login directly
token=
latitude= 37.7921713413267
longitude= -122.411915298286

and when i run the bot i am getting this error message:
"Starting Latitude setting ("latitude") not specified in config.properties!"

if anyone could help it would be appreciated :)

**Comment by stupiz** [comment]
remove space before the value

> latitude=37.7921713413267
> longitude=-122.411915298286

**Comment by charliedumdum** [comment]
still getting the same error with no spaces unfortunately :(

**Comment by toffaste1337** [comment]
Try 
`latitude=37.7921713
longitude=-122.41191`

**Comment by RovingSpirit** [comment]
What program are you using to edit it? If you're on a mac editing with pages it messes with the config, download atom or another file editor instead

**Comment by NoobWithBoobs** [comment]
you likely have an UTF-8 encode issue. Especially if you copied and pasted config file directly from the website. Instead download them directly and edit them in programs like notepad++ or Brackets .
Single Bot
https://raw.githubusercontent.com/jabbink/PokemonGoBot/develop/config.properties.template

Multi Bots
https://raw.githubusercontent.com/jabbink/PokemonGoBot/develop/json-template.json


Let me know if that helps

**Comment by ahr174** [comment]
check this #826

**Comment by charliedumdum** [comment]
issue is now fixed, thankyou very much @RovingSpirit
