### ISSUE TITLE
Account stolen by apparent bot

### ISSUE THREAD

**Issue by MichaelSeph** [jabbink/PokemonGoBot#975]
Account stolen by apparent bot, wtf ? Did not use it anywhere else... possible general Pokemon Go issue ?

**Comment by Grover-c13** [comment]
What makes you think the account was stolen

**Comment by smileytechguy** [comment]
please elaborate

**Comment by BKer** [comment]
A bit of an obvious question maybe, but are you using a private or a shared machine to run the bot on?

**Comment by Peyphour** [comment]
If he used an old version, the credentials where exposed via the rest API so anyone could stole the account

**Comment by staurakis** [comment]
Actually he has to elaborate on what he means by stolen (how he came to this conclusion), where the bot was running (on what machine) and of course if this is the only code that run historically.

**Comment by Peyphour** [comment]
Prior to 0.5.1, every request to `{server_url}:{server_port}/api/bots` would reveal all credentials so it wouldn't surprise me it the account (Google or PTC) was really stolen

**Comment by MichaelSeph** [comment]
Yes it was 0.5.0, revealed where ? It was a single instance on PTC on my local machine without any other connection or server. And well it's clear because this happened (and mails were in english where my own support mails are in spanish):

![392cdf54e1545a30498054746ab05cf5](https://cloud.githubusercontent.com/assets/20837523/17585834/5fbba6ce-5fbe-11e6-9517-45e8b71e8d47.png)

**Comment by keyur24** [comment]
Hahaha I would never TRY THIS

**Comment by MichaelSeph** [comment]
Found out that the thief bot was actually from NecroBot :D

**Comment by CosmoRing** [comment]
> Did not use it anywhere else
actually from NecroBot

So you did use somewhere else...

**Comment by MichaelSeph** [comment]
Note the "kidding" part. Maybe was bit late.

**Comment by langerhans** [comment]
![image](https://cloud.githubusercontent.com/assets/5160000/17601616/4e171e58-6009-11e6-8049-e54116420c04.png)
