### ISSUE TITLE
Egg KM Walked not shown in GUI

### ISSUE THREAD

**Issue by FrancYescO** [jabbink/PokemonGoBot#989]

**Comment by Peyphour** [comment]
Fix this : 
`fun sendEggs() {
        if (ctx != null) {
            val eggs = EventEggs()
            for (egg in ctx!!.api.cachedInventories.hatchery.eggs) {
                val eggObj = EventEggs.Egg()
                // eggObj.distanceWalked = egg.eggKmWalked
                eggObj.distanceTarget = egg.eggKmWalkedTarget
                eggs.eggs.add(eggObj)
            }
            server?.broadcastOperations?.sendEvent("eggs", eggs)
        }
    }`

**Comment by GonnaLoseItAll** [comment]
I've the same problem. The fix for me was just deleting the cookies of pogo.abb.ink. 
If you don't want to delete the cookie, just go incognito :)
