### ISSUE TITLE
Webpage (map) not updating after moving/hiding panels

### ISSUE THREAD

**Issue by badeip** [jabbink/PokemonGoBot#996]
**Description:**
Webpage not updating after moving/hiding panels

**Steps to reproduce:**

1. go to: http://pogo.abb.ink/RocketTheme/
2. move/hide a panel
3. restart bot
4. observe webpage

**Expected behaviour:**
The respective panels should update
 
**Actual behaviour:**
They don't

**Workaround:**
Go to: Options -> Reset panel positions

**Version:**
0.5.2

**Operating System:**
Reproducible on both OSX and Linux

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by CosmoRing** [comment]
Known issue, already reported to the right repo: https://github.com/eruecco87/PokemonGoBot-RocketTheme/issues/6

**Comment by badeip** [comment]
Sorry about that.
Closing issue.
