### ISSUE TITLE
Feature Request - Add proxy support

### ISSUE THREAD

**Issue by ghost** [jabbink/PokemonGoBot#997]
**Description:**
Would be awesome if you could add proxy support to the bot.

**Steps to reproduce:**

**Expected behavior:**
Add proxy settings in config file

**Actual behavior:**
[What actually happens]

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
[The version of the bot you used; when self-compiled: :exclamation: the commit hash :exclamation:]

**Operating System:**
[Your operating system]

**Java version:**
[Full output of `java -version`]

**Comment by ryangardner** [comment]
does it work if you use command line properties passed in? 

`-Dhttp.proxyHost=10.0.0.100 -Dhttp.proxyPort=8800 -Djava.net.useSystemProxies=true` ?

I'm not sure if the underlying http library in use will use the system proxies but if they do that'd be an easy way to do it

**Comment by swtrpeter** [comment]
@ryangardner i will have to try when i get home.. I will let you know the results

**Comment by swtrpeter** [comment]
@ryangardner how could I add this in when starting the bot ?

**Comment by ryangardner** [comment]
If you build the jar and run it with `java -jar` you would put it in the
command line... So `java -Djava.whatever=whatever -jar yourjar.jar`

**Comment by swtrpeter** [comment]
@ryangardner could the proxy settings just be inserted in the java control panel ? If you put them in the java control panel network settings would those proxy settings apply to the bot when ran ?

**Comment by ryangardner** [comment]
Maybe? I'm not sure. It's worth trying

**Comment by swtrpeter** [comment]
@ryangardner how would I be able tell if its running off of the proxy ip ? Sorry if these are dumb questions but I appreciate the help.

**Comment by ryangardner** [comment]
I'm not sure. You could set up a local proxy like Charles and set your java
system preferences to use that proxy and see if you see traffic flow
through it... I'm not sure. I haven't really done much with proxies in a
long time

**Comment by Peyphour** [comment]
I will make a PR later to integrate proxy support in the config files

**Comment by Peyphour** [comment]
#1020

**Comment by Cy4n1d3** [comment]
That's a good start, thank you :)
Any plans on SOCKS5 support?

**Comment by Peyphour** [comment]
Later today :)

**Comment by Cy4n1d3** [comment]
Awesome, I'll keep an eye on this and test as soon as SOCKS is available!

**Comment by Peyphour** [comment]
Done, I'm not too familiar with using proxy and java but it SHOULD work

**Comment by Cy4n1d3** [comment]
Confirmed! I can log in from a banned location using a SOCKS5 proxy :)

**Comment by Sieberkev** [comment]
Implemented with #1020
