### ISSUE TITLE
Cannot run two bots

### ISSUE THREAD

**Issue by Bukplug** [jabbink/PokemonGoBot#999]
When I try to use more than one bot on only one Server the second bot crashes. (Webserver is deactivated)

**Steps to reproduce:**

1. start first bot
2. Start secound bot

**Expected behavior:**
both bots have to start

**Actual behavior:**
One bot crashes

**Stacktrack:**
Adress already bind

**Version:**
Newst Java

**Operating System:**
Ubuntu

**Java version:**
 java -version                  
openjdk version "1.8.0_66-internal"                  
OpenJDK Runtime Environment (build 1.8.0_66-internal-
b17)                                                 
OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode
)

**Comment by classicalDonkey** [comment]
Look here 

https://github.com/jabbink/PokemonGoBot/issues/777#issuecomment-237219032

**Comment by langerhans** [comment]
Well duh, you need to configure different ports per bot or use the integrated multi bot feature. Check the FAQ.
